### ISSUE TITLE
[openapi] ModelDatiLingua - campo codiceLingua

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#10]
Per il campo del modello indicato in oggetto c'è una tabella su cui basarsi per valorizzarlo? Oppure è e sarà per sempre previsto solo per la lingua tedesca quindi possiamo scolpire direttamente DE?

**Comment by asqueglia** [comment]
Buongiorno, va sicuramente prevista la tabella di decodifica per il multilinguismo..  sarà prevista quando sarà implementato il multilinguismo. Al momento abbiamo solo anticipato la firma del servizio che gestirà il multilingua per verificare insieme se questo approccio può andare bene.
