### ISSUE TITLE
[webapp] e [SC] - comune di Lissone

### ISSUE THREAD

**Issue by rvinzani** [italia/ansc#1001]
### Ambiente

produzione

### Provenienza segnalazione

Comune

### Riferimenti operatore/comune

Lissone

### Data del test (yyyy-mm-dd)

28/08/2024

### Caso d'uso

5.2.1.5.4

### Descrivi il problema

Buongiorno,
dobbiamo trascrivere un decreto di acquisto di cittadinanza italiana che abbiamo ricevuto dal Consolato d’Italia in Londra.
Abbiamo riscontrato un errore nella sezione “ATTO DA TRASCRIVERE”
Possiamo inserire come Stato ente “Italia” (e successivamente scegliere la provincia e il Comune) , ma in fase di conferma il programma restituisce un errore richiedendo uno stato estero.
Nella Minuta dovrebbe poi comparire  “emesso da ministero dell'interno in ROMA” (ora esce “emesso da ministero dell'interno proveniente da ITALIA”).
Vi chiediamo cortesemente di verificare.
 

Per maggior chiarezza, segnaliamo inoltre,  che nella sezione “Dati Generali”, l’etichetta del campo “data trascrizione” dovrebbe essere modificata in “data richiesta trascrizione” in quanto si sta parlando della data in cui il Consolato ha richiesto al Comune la trascrizione del Decreto di concessione della Cittadinanza italiana.
Negli allegato dovrebbe essere prevista anche la richiesta di trascrizione dal consolato

Segnaliamo infine che nella minuta manca questa frase:
“Il giuramento prescritto per far luogo alla trascrizione è stato prestato da “Cognome Nome” in data “Data giuramento” con “Estremi giuramento”  e quindi nei termini di cui all'art. 10 della legge 5 febbraio 1992, n. 91”  come il caso d’uso 52153.
Formula 93 da adattare

**Comment by asqueglia** [comment]
Rilascio effettuato nella versione 1.32.10
