### ISSUE TITLE
[webapp]: Indice annuale con dati duplicati

### ISSUE THREAD

**Issue by asqueglia** [italia/ansc#1003]
### Ambiente

produzione

### Provenienza segnalazione

Comune

### Riferimenti operatore/comune

ROSIGNANO

### Descrivi il problema

L'indice annuale generato per l'anno 2023 contiene dati duplicati

**Comment by mttfranci** [comment]
Chiudiamo la issue.
Con la patch [1.32.10](https://github.com/italia/ansc/releases/tag/v1.32.10) il problema dovrebbe essere risolto.
Inoltre ora l'ordinamento nell'indice abbiene per numero nazionale dell'evento.
Gli indici non sono aggiornati automatica, è pertanto necessario sottomottore di nuovo le richieste di generazione.

Saluti

Assistenza ANSC
