### ISSUE TITLE
[webapp]: [3.1.2.1.1.1] Matrimonio con rito civile con delega di altro comune o consolato nella casa comunale 

### ISSUE THREAD

**Issue by rvinzani** [italia/ansc#1005]
### Ambiente

produzione

### Provenienza segnalazione

Comune

### Riferimenti operatore/comune

Valeggio sul Mincio

### Data del test (yyyy-mm-dd)

29/08/2024

### Caso d'uso

3.1.2.1.1.1

### Descrivi il problema

Nel caso di interprete femminile nella composizione, in alcuni punti non è gestito correttamente il genere e c'è una duplicazione nell'indicazione della residenza

**Comment by asqueglia** [comment]
Rilascio effettuato nella versione 1.32.10
