### ISSUE TITLE
[SC]: Errore 400003 - Presa visione non trovata per id evento

### ISSUE THREAD

**Issue by ATropeano** [italia/ansc#1007]
### Ambiente

pre-produzione

### Servizio

R012 - Servizi cooperativi firma elettronica del dichiarante

### idOperazione

assente

### idEvento o idAnsc

3314207

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Castel San Pietro Terme

### Data del test (yyyy-mm-dd)

2024-08-30

### Descrivi il problema

Invocando il servizio firmadichiarante/invio-email di un atto di nascita ottengo l'errore seguente. L'invocazione di questa firma elettronica della madre (firmante insieme al padre dichiarante), è stata fatta di seguito all'invio della firma cartacea dichiarante (padre), avvenuto con successo. 
{
	"errors": [
		{
			"code": "400003",
			"severity": "E",
			"text": "Presa visione non trovata per id evento: 3314207"
		}
	],
	"esito": {
		"codice": "400003",
		"descrizione": "Presa visione non trovata per id evento: 3314207"
	},
	"testataRisposta": {
		"idComune": 2447,
		"idEsito": 1,
		"idOperazioneComune": "a37d0082-5cc5-4214-ad8c-02440e9a34a3"
	}
}

### Come riprodurre il problema

1. Validazione un atto di nascita
2. Scarico Anteprima Atto
3. Invio scansione firma cartacea dichiarante (padre)
4. Richiesta invio link per presa visione atto della madre (firmataria insieme al padre - dichiarante)

### Payload (json)

```JSON
{
	"emailDichiarante": "alessio.tropeano@datagraph.it",
	"idEvento": "3314207",
	"idAnsc": "2024-3314207-3-037020",
	"firmatario": {
		"cognome": "Bianchina",
		"nome": "Rosina",
		"sesso": "F",
		"dataNascita": "1978-08-08"
	},
	"testataRichiesta": {
		"idComune": 2447,
		"idOperazioneComune": "a37d0082-5cc5-4214-ad8c-02440e9a34a3",
		"dataOraRichiesta": "2024-08-30T12:38:56.5426721Z",
		"nomeApplicativo": "Test ANSC .NET",
		"versioneApplicativo": "1",
		"fornitoreApplicativo": "Datagraph s.r.l."
	},
	"datiPaginazione": {
		"numPagina": 1,
		"numRecordPagina": 100
	}
}
```

**Comment by asqueglia** [comment]
Buongiorno, i dati passati in ingresso al servizio di firma dichiarante elettronica, non sono corretti. E' stato trasmesso il cognome Bianchina, invece il cognome registrato per l'atto in questione è **Bianchini**  non Bianchina.
Chiudiamo pertanto la issue. In caso di ulteriori problematiche ne riapra una altra dedicata
