### ISSUE TITLE
[SC]: Casi d'uso non coerenti dopo successive validazioni.

### ISSUE THREAD

**Issue by gcuci** [italia/ansc#1008]
### Ambiente

pre-produzione

### Servizio

R009 - Servizi cooperativi validazione evento

### idOperazione

2447425; 2455636

### idEvento o idAnsc

3313979

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Bagnacavallo

### Data del test (yyyy-mm-dd)

2024-08-30

### Descrivi il problema

Buonasera,

segnaliamo un comportamento anomalo che si verifica quando si effettuano successive validazioni, di un evento in stato confermato, con la modifica del caso d'uso.

Nel dettaglio, è stato prima validato un evento di nascita, per un caso d'uso Dic_Nasc_025 ('Dichiarazione entro i 10 giorni - resa dalla madre con il consenso del padre reso mediante atto notarile – filiazione fuori dal matrimonio'), con esito positivo (idOperazione: 2447425).
Successivamente, viene validato nuovamente l'evento ma con un altro caso d'uso, in quanto nella prima validazione non era stata acquisita l'informazione del 'nato morto', che causa appunto l'utilizzo di un altro caso d'uso (Dic_Nasc_027 - 'Dichiarazione nei termini di filiazione fuori dal matrimonio resa all'USC dalla madre con consenso paterno espresso con atto notarile di bimbo nato morto'). Anche questa nuova validazione, viene effettuata con esito positivo (idOperazione: 2455636).

Accedendo però alla Web Application ANSC, ed effettuando una ricerca per evento di nascita, con ID Atto, sembrerebbe che la modifica del caso d'uso, sia stata acquisita correttamente:

![im1](https://github.com/user-attachments/assets/1f8df16b-09e5-4bbb-9227-e2a3ac7cf776)

ma entrando nella visualizzazione dei metadati dell'evento, viene visualizzato il caso d'uso originario, prima della validazione successiva: 

![im2](https://github.com/user-attachments/assets/8789186a-b2d1-4d71-9bd2-8904cfbcd563)

In attesa di riscontro,

cordiali saluti.

**Comment by asqueglia** [comment]
Buongiorno, il sistema non consente di modificare il codice del caso d'uso una volta confermato l'evento. Quello che risulta dalle operazioni effettuate è che è stata modificata la descrizione del caso d'uso ma non il codice; da tenere presente che
 [**1.1.2.1.2.1.0.3**] Dichiarazione nei termini di filiazione fuori dal matrimonio resa all'usc dalla madre con consenso paterno espresso con atto notarile di bimbo nato morto

**[1.1.2.1.2.0.0.3**] Dichiarazione entro i 10 giorni - resa dalla madre con il consenso del padre reso mediante atto notarile – filiazione fuori dal matrimonio

Pur avendo modificato la descrizione, il codice del caso d'uso per l'evento 3313979 da voi registrato è rimasto il **11212003**.

Analizzeremo la possibilità di inserire un controllo bloccante se in fase di aggiornamento dell'evento, viene trasmesso un codice caso d'uso (idUsecase) non coerente.

**Comment by gcuci** [comment]
Buongiorno

abbiamo controllato le due operazioni indicate: 2447425 e 2455636.

Non risulta però nelle request inviate, incoerenza tra id e descrizione del caso d'uso.

Nella prima (2447425), è stato passato come idUsecase : '11212003', e come descrizioneCasoUso: 'Dichiarazione entro i 10 giorni - resa dalla madre con il consenso del padre reso mediante atto notarile – filiazione fuori dal matrimonio'.
Nella seconda (2455636), in cui vengono passati anche id e idAnsc, in quanto l'evento era già stato validato una prima volta, è stato passato come idUsecase : '11212103', e come descrizioneCasoUso: 'Dichiarazione nei termini di filiazione fuori dal matrimonio resa all'USC dalla madre con consenso paterno espresso con atto notarile di bimbo nato morto'.

Ed entrambe sono state correttamente validate.

Se, come avete indicato, non è possibile modificare il caso d'uso, una volta confermato un evento, bisognerebbe aggiungere anche questo controllo, per evitare disallineamenti, anche perchè, non avevamo trovato indicazioni in tal senso, nella documentazione.

**Comment by gbuemi** [comment]
La segnalazione è stata corretta e appena rilasciata con la versione 1.33.0
