### ISSUE TITLE
Discordanza tra tabelle Use Case

### ISSUE THREAD

**Issue by LucaBonini64** [italia/ansc#101]
Buongiorno,
nell'ultima versione pubblicata trovo tra gli Use Case di test nel documento ANSC_Piano_Test.xlsx i seguenti:
2112 - Richiesta trascrizione atto di morte all'estero richiesto da privati
2113 - Richiesta trascrizione atto di morte all'estero richiesto da pubblica autorità
131110 - Trascrizione di atto di nascita avvenuta all’estero su richiesta dell’autorità diplomatica o consolare (DICHIARANTE MAGGIORENNE)
mentre nella tabella di decodifica (ANSC_03) trovo:
2212 - Richiesta trascrizione atto di morte all'estero richiesto da privati con istanza scritta
2213 - Richiesta trascrizione atto di morte all'estero richiesto da pubblica autorita'
1311 - Trascrizione di atto di nascita avvenuta all'estero su richiesta dell'autorita' diplomatica o consolare
sono in realtà gli stessi use case?

Inoltre nella cartella Mapping_casi_uso il file 3_dec_use_case.xlsx non contiene numerosi use case che sono invece presenti negli altri file (esempio 1331 - Trascrizione del decreto prefettizio di cambiamento del nome e cognome), presumo che quest'ultimo file sia ancora in fase di implementazione, è corretto?

Grazie.

Luca Bonini APKAPPA

**Comment by anbatistini** [comment]
Buongiorno,
verifichiamo e le facciamo sapere.

**Comment by asqueglia** [comment]
Buongiorno, i casi d'uso presenti sulla tabella delle decodifiche vengono rilasciati a gruppi, ad ogni nuova versione del sistema.
In particolare
2112 -> non presente nella tabella di decodifica
2113 ->non presente nella tabella di decodifica
131110 -> non presente nella tabella di decodifica

2212 -> Morte_006 non ancora rilasciato
2213 -> Morte_007 rilasciato con la versione 1.5.2
1311 -> Trascr_005 rilasciato con la versione v1.6.0

i casi d'uso non presenti al momento sulla tabella di decodifica, verranno codificati, aggiunti e rilasciati in una delle prossime versioni del sistema.
