### ISSUE TITLE
[SC]: Estratto per copia integrale - errore "Non trovata l'associazione tra il soggetto intestatario e l'evento"

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#1011]
### Ambiente

produzione

### Servizio

R002 - Servizi cooperativi certificazioni

### idOperazione

308849

### idEvento o idAnsc

26731

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Lissone - biadanpad

### Data del test (yyyy-mm-dd)

2024-09-03

### Descrivi il problema

Tentando di generare l'estratto per copia integrale dell'atto, si riceve in rirposta l'errore "Non trovata l'associazione tra il soggetto intestatario e l'evento"

### Payload (json)

```JSON
REQUEST:
{
  "idAnsc": "2024-26731-235-108028",
  "idEvento": "26731",
  "richiedente": {
    "codiceFiscale": "XXXXX",
    "cognome": "XXXXX",
    "nome": "XXXXX",
    "sesso": "X",
    "dataNascita": "XXXX-XX-XX",
    "idComuneNascita": "XXXXX",
    "nomeComuneNascita": "XXXXX",
    "idProvinciaNascita": "XXXXX",
    "siglaProvinciaNascita": "XXXXX",
    "idStatoNascita": "XXXXX",
    "nomeStatoNascita": "XXXXX",
    "indirizzoResidenza": "",
    "idNazionalita": "XXXXX",
    "nazionalita": "XXXXX"
  },
  "intestatario": {
    "id": "15914985"
  },
  "idTipoCertificato": "3",
  "conPaternitaMaternita": false,
  "testataRichiesta": {
    "idComune": 5000,
    "idOperazioneComune": "2519",
    "dataOraRichiesta": "2024-09-03T12:25:02.224+02:00",
    "nomeApplicativo": "urbi",
    "versioneApplicativo": "1.3.8",
    "fornitoreApplicativo": "padigitale"
  }
}

RESPONSE:
{
  "testataRisposta": {
    "idComune": 5000,
    "idOperazioneComune": "2519",
    "idOperazione": "308849"
  },
  "errors": [
    {
      "code": "404003",
      "severity": "E",
      "text": "Non trovata l'associazione tra il soggetto intestatario e l'evento"
    }
  ],
  "infos": [
    {
      "code": "110527",
      "severity": "I",
      "text": "Informazioni sull'operazione da fornire in caso di assistenza : data:2024-09-03 10:25:11 , idOperazione:308849"
    }
  ]
}
```

**Comment by gbuemi** [comment]
Salve @biadanpad,
la problematica è stara risolta, chiudiamo la issue.

Un saluto,
Supporto ANSC

**Comment by biadanpad** [comment]
Buonasera, 
Il comune ci ha segnalato che lo stesso problema è stato riscontrato per un altro atto.
idOperazione: 312867

**Comment by gbuemi** [comment]
Buongiorno @biadanpad,
la questione è stara risolta, chiudiamo la issue.

Un saluto,
Supporto ANSC

**Comment by biadanpad** [comment]
Buongiorno,
la questione non è affatto risolta: il comune riscontra ancora lo stesso problema (idOperazione: 316188, 316529, 316316, 316678).
Vi prego di verificare con attenzione l'effettiva risoluzione definitiva del problema prima di chiudere la issue.

**Comment by gbuemi** [comment]
Buon pomeriggio,
per gli eventi finora segnalati la questione è stata risolta da centro e non ci risultano anomalie. La fix per risolvere il problema alla radice è in fase di test e verrà rilasciata al più presto, fino a quel momento l'anomalia potrebbe ripresentarsi per questo caso d'uso specifico.

Per gli idOperazione forniti ci risulta che il problema è presente su 3 atti (un idOperazione fa riferimento allo stesso estratto) ed è stato appena risolto.

Vi assicuriamo che le verifiche sono sempre fatte con attenzione prima di chiudere le issue.

Grazie e saluti,
Supporto ANSC

**Comment by asqueglia** [comment]
La segnalazione è stata corretta e appena rilasciata con la versione 1.32.12.0

**Comment by biadanpad** [comment]
Il comune continua a riscontrare lo stesso errore:
2024-27177-239-108028  -"idOperazione": "316529"
2024-27123-241-108028 - "idOperazione": "316316"
2024-27142-243-108028 - "idOperazione": "316678"
2024-27274-245-108028 - "idOperazione": "320072"
2024-27293-247-108028 - "idOperazione": "320623"

Il comune mi dice che sono tutti atti con caso d'uso 523153.

Si prega di risolvere definitivamente il problema.

**Comment by gbuemi** [comment]
Buongiorno @biadanpad,
stiamo verificando, vi chiediamo conferma sul primo atto segnalato, ci risulta che la richiesta con idOperazione 316529 faccia riferimento all'atto 2024-27117-239-108028. E' questo l'atto da verificare?

Grazie,
Supporto ANSC

**Comment by gbuemi** [comment]
Buongiorno @biadanpad,
è stato effettuato l'intervento da centro per gli atti _2024-27274-245-108028_ e _2024-27293-247-108028_, adesso è possibile richiedere il l'estratto per copia integrale.

Per il primo atto segnalato _2024-27177-239-108028 -"idOperazione": "316529"_ ci risulta che l'atto sia _2024-**27117**-239-108028_ e che l'intervento è già stato effettuato. Anche per gli atti _2024-27123-241-108028_ e _2024-27142-243-108028_ ci risulta che l'intervento sia già stato effettuato. 
Lo avete comunicato al comune? Tra il 6 settembre e ieri 11 settembre non ci risultano accessi al servizio di certificazione per questi tre atti.

Vi comunichiamo inoltre che l'intervento che risolve il problema è stato risolto e rilasciato nel pomeriggio del 9 settembre. Come già comunicato, per gli atti inseriti prima della versione 1.32.12 e per questo caso d'uso specifico, l'anomalia potrebbe ripresentarsi e necessita un intervento da centro.

Per velocizzare analisi e interventi vi preghiamo, gentilmente, di essere più precisi possibile in fase di segnalazione delle anomalie.

Chiudiamo la issue, se dovessero esserci altri casi che necessitano un intervento da centro riaprite pure.

Grazie.

Un saluto,
Supporto ANSC
