### ISSUE TITLE
[SC]: Validazione caso 333000 - errore per campi obbligatori richiesti ma non conosciuti dall'USC

### ISSUE THREAD

**Issue by siscomanpr** [italia/ansc#1012]
### Ambiente

produzione

### Servizio

R009 - Servizi cooperativi validazione evento

### idOperazione

309719

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Comune di Carrù

### Data del test (yyyy-mm-dd)

03/09/2024

### Descrivi il problema

La validazione di un atto di matrimonio con caso d'uso 333000 (Trascrizione sentenze di Tribunali stranieri - richiesta di trascrizione da parte del Consolato/Ambasciata), fallisce per via di una serie di campi obbligatori che però l'USC non ha a disposizione e quindi non può inserire:
![image](https://github.com/user-attachments/assets/f5d1d60f-d8b3-4841-9c96-106b5d0b0049)
Potete rendere non obbligatori la residenza e la cittadinanza dei coniugi per il caso d'uso in oggetto (e se possibile su tutti i casi d'uso che prevedono una trascrizione di un documento straniero)?

Il comune di Carrù resta in attesa di un riscontro per poter procedere con la validazione dell'atto.

Grazie per l'attenzione
Siscom SPA

**Comment by gbuemi** [comment]
Buongiorno,
procediamo con l'intervento richiesto, seguiranno aggiornamenti.

Un saluto,
Supporto ANSC

**Comment by asqueglia** [comment]
La segnalazione è stata corretta e appena rilasciata con la versione 1.32.12.0
