### ISSUE TITLE
[webapp]: allegati del provvedimento di rifiuto

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#1013]
### Ambiente

pre-produzione

### Provenienza segnalazione

Software House

### Riferimenti operatore/comune

Anna Maraspin, Sala Bolognese

### Descrivi il problema

Formato atto di nascita con genitori residenti in un altro Comune
QUesto Comune rifiuta l'atto e ci manda il provvedimento
Se vado in consultazione rifiuto e cerco di scaricare gli allegati mi compare il messaggio bloccante "Attenzione. L'utente loggato non ha accesso alla risorsa" 
Questo messaggio è solo in ambiente di test? In produzione il Comune potrà scaricarsi gli allegati per capire meglio,eventualmente, il rifiuto? Nei servizi cooperativi sarà possibile?

**Comment by gbuemi** [comment]
La segnalazione è stata corretta e appena rilasciata con la versione 1.33.0
