### ISSUE TITLE
[SC]: Dati in ingresso non corretti- Anteprima Atto

### ISSUE THREAD

**Issue by KibMcris** [italia/ansc#1016]
### Ambiente

pre-produzione

### Servizio

R005 - Servizi cooperativi consultazione, R010 - Servizi cooperativi anteprima

### idOperazione

2471721

### idEvento o idAnsc

2024-3413691-339-102044

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Tropea

### Data del test (yyyy-mm-dd)

05/09/2024

### Descrivi il problema

Dopo aver validato con successo il caso d'uso 52261, richiedendo l'anteprima dell'atto ANSC risponde con l'errore:
`HTTP Status 400 
{"testataRisposta":{"idComune":10288,"idOperazioneComune":"11","idOperazione":"2471721","idEsito":1},"errors":[{"code":"400003","severity":"E","text":"Dati in ingresso non corretti"}],"infos":[{"code":"110527","severity":"I","text":"Informazioni sull'operazione da fornire in caso di assistenza : data:2024-09-05 14:40:14 , idOperazione:2471721"}]}`

**Comment by gbuemi** [comment]
La segnalazione è stata corretta e appena rilasciata con la versione 1.33.0
