### ISSUE TITLE
[SC]: R009 - caso d'uso 344000 Accordo di modifica delle condizioni di separazione o divorzio (Sep_Div_004)

### ISSUE THREAD

**Issue by siscomanpr** [italia/ansc#1017]
### Ambiente

pre-produzione

### Servizio

R009 - Servizi cooperativi validazione evento

### idOperazione

2472683

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Serravalle Sesia

### Data del test (yyyy-mm-dd)

06/09/2024

### Descrivi il problema

Tentando di validare il caso d'uso in oggetto riceviamo i seguenti errori bloccanti:

![image](https://github.com/user-attachments/assets/9abdcabb-2f09-4d6e-9dd0-1e979936b648)

Vorremmo alcuni chiarimenti sui 2 campi segnalati come anomalia:
- il campo evento.separazione.tipoAccordo è stato popolato con il valore 5 "Modifica delle condizioni di scioglimento/cessazione effetti civili" e non capiamo il motivo per cui richiede che venga indicato per forza il valore 4. 
- il campo evento.separazione.dataConfermaAccordo a cosa si riferisce? quale sarebbe la data di conferma richiesta visto che per questo caso non è prevista una conferma? 

Facciamo presente che l'evento su cui è stato fatto il test risulta in stato "confermato" perché indicando 4 nel primo campo e una data di conferma fittizia, come richiedono gli errori bloccanti, la validazione avviene correttamente.

Grazie per l'attenzione
Siscom SPA

**Comment by gbuemi** [comment]
Buongiorno @siscomanpr,
rispondiamo per punti:

-  il campo _evento.separazione.tipoAccordo_ per questo caso d'uso da documentazione fa riferimento alla decodifica ANSC_53 il cui valore 4 corrisponde "Modifica delle condizioni di separazione" conformemente al caso d'suo 344000. Un valore diverso risulterebbe incoerente con il caso d'uso scelto;
- il campo evento.separazione.dataConfermaAccordo verrà reso opzionale e seguiranno aggiornamenti.

Un saluto,
Supporto ANSC

**Comment by siscomanpr** [comment]
Buongiorno @gbuemi,
il caso 344000 si riferisce a "Separazioni e divorzi: Accordo di modifica delle condizioni di separazione **o divorzio**", quindi crediamo debba accettare anche il valore 5 della tabella di decodifica 53 (Modifica delle condizioni di scioglimento/cessazione effetti civili). 
Mi può dare un riscontro in merito?

Per la data di conferma, va bene, grazie.

Cordiali saluti
Siscom

**Comment by siscomanpr** [comment]
Mi perdoni ma non capisco.
Il caso d'uso 345000 si riferisce alle trascrizioni di negoziazione assistita da avvocati, qui invece si sta parlando di Modifica delle condizioni di divorzio, non di un nuovo divorzio. 
Se è come mi sta dicendo, perché il caso 344000 nella descrizione contempla anche la casistica "o divorzio"? E' quindi sbagliata la descrizione del caso d'uso 344000 e dovrebbe chiamarsi:
"Separazioni e divorzi: Accordo di modifica delle condizioni di separazione"
invece di:
"Separazioni e divorzi: Accordo di modifica delle condizioni di separazione o divorzio" ?

Cordiali saluti
Siscom

**Comment by gbuemi** [comment]
Salve @siscomanpr,
formule e allegati per i due casi d'uso in questione sono differenti e al momento non è prevista una modifica all'albero dei casi d'uso.

Un saluto,
Supporto ANSC

**Comment by gbuemi** [comment]
La segnalazione è stata corretta e appena rilasciata con la versione 1.33.0
