### ISSUE TITLE
[webapp]: Soggetto Padre mancante nello usecase 11227000

### ISSUE THREAD

**Issue by corradosacco** [italia/ansc#1018]
### Ambiente

pre-produzione

### Provenienza segnalazione

Software House

### Riferimenti operatore/comune

Corrado Sacco/Milano

### Data del test (yyyy-mm-dd)

2024/09/09

### Caso d'uso

11227000

### Descrivi il problema

La formula 7 richiede i dati del padre ma la WebApp non li richiede ed il mapping non li prevede.

**Comment by gbuemi** [comment]
La segnalazione è stata corretta e appena rilasciata con la versione 1.33.0
