### ISSUE TITLE
[SC]: Firma USC Attestazione di Conformità - Errore "Firma non avvenuta con successo"

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/ansc#1019]
### Ambiente

pre-produzione

### Servizio

R007 - Servizi cooperativi firma ufficiale di stato civile

### idOperazione

2482895,2482913,2482941

### idEvento o idAnsc

2024-3414097-235-039010

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

FAENZA

### Data del test (yyyy-mm-dd)

2024-09-10

### Descrivi il problema

ottenuta l'attestazione di conformità (ws R010 - idOperazioneAnsc 2482854), non riusciamo ad eseguire il servizio di firma.
su 3 tentativi eseguiti, la risposta è sempre:
```
  <errors>
    <severity>E</severity>
    <code>406004</code>
    <text>Firma non avvenuta con successo</text>
  </errors>
```

non è chiaro quale sia il problema collegato al processo di firma.
(si pone lo stesso problema di interpretazione del messaggio già segnalato con issue #172 )

attendo riscontro.
grazie
Alessandro ADS

**Comment by asqueglia** [comment]
Buongiorno analizziamo e le facciamo sapere quanto prima.

**Comment by asqueglia** [comment]
Indagando la problematica abbiamo appurato che si è trattato di un problema di connessione con il servizio di firma PAdES. Potete riprovare ? stiamo lavorando per cecare di rendere  più chiari i messaggi di errore restituiti.

**Comment by AMonopoliADS** [comment]
ad un primo tentativo la chiamata è andata in timeout (ws R007 - idOperazione**Comune** 2024005782)

al secondo tentativo la chiamata è andata a buon fine (ws R007 - idOperazione**Ansc** 2485293) e mi ha permesso di procedere con gli step successivi di firma USC dell'atto (ws R007) e di data validazione (ws R014)

non so se volete analizzare il motivo del timeout
intanto grazie

**Comment by asqueglia** [comment]
Certamente analizzeremo la questione che non si verifica però in maniera sistematica. Grazie a lei. Intanto chiudiamo questa issue per il caso specifico.
