### ISSUE TITLE
[R006] Firma Dichiarante - Errore 400003 (Dati in ingresso non corretti)

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#102]
data: 2023-05-10
ambiente: pre-produzione

Buonasera, 
testando il servizio di firma dichiarante (R006) ricevo l'errore con codice 400003 (Dati in ingresso non corretti). Di seguito il payload della richiesta e la risposta:

JWS Payload:
{
	"firmaDichiaranteInput":
	{
		"contenuto":"JVBERi0xLjcKCjQgMCBvYmoKKE......",
		"protocollo":"123/2023",
		"nomefile":"aaaaaaaa.pdf",
		"idEvento":"951934",
		"tipoFile":"1",
		"tipoAllegato":"999",
		"stato":"1",
		"listaFirmatari":
		[
			{
				"nome":"XXXXX",
				"cognome":"XXXX",
				"codiceFiscale":"XXXXXXXXXXXXXXXX",
				"sesso":"X",
				"dataNascita":"XXXX-XX-XX"
			}
		]
	},
	"testataRichiesta":
	{
		"idComune":5000
	}
}

Service EndPoint: https://anscservicepre.anpr.interno.it/services/service/firma/firmadichiarante/upload/1
HttpResponse Code: 400
HttpResponse Body:
{
	"errors":
	[
		{
			"code":"400003",
			"severity":"E",
			"text":"Dati in ingresso non corretti"
		}
	],
	"testataRisposta":
	{
		"idComune":5000,
		"idEsito":1,
		"idOperazione":
		"1587591"
	}
}

Il campo contenuto è stato troncato per leggibilità.

Ho provato, per il firmatario, a passare solo il codice fiscale, ma non cambia nulla.

Potreste aiutarmi a capire a cosa è dovuto l'errore?
In generale, c'è modo di capire quale dei dati in ingresso non è corretto?

**Comment by amusarra** [comment]
Salve @biadanpad
Per questo caso d'uso specifico ed evento, quando è stato inserito a sistema con (idEvento: 951934), non è stato specificato nessun firmatario tramite l'opportuno `flagFirmatario` impostato a `true`. Per questo evento è quindi possibile procedere direttamente con la firma USC (Ufficiale di Stato Civile). Questo è il motivo dell'errore ottenuto.

Con la prossima release, il messaggio di errore sarà reso molto più chiaro.

Chiudo la issue, nel caso fosse necessario, può riaprirla.

Saluti.
Supporto ANSC.
