### ISSUE TITLE
[SC]: dati richiesti per il Segreatario Comunale

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#1023]
### Ambiente

pre-produzione

### Servizio

R009 - Servizi cooperativi validazione evento

### idOperazione

assente

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

ponsacco, anna maraspin

### Descrivi il problema

Buongiorno,
ho notato una discrepanza tra webapp e mapping relativamente ai campi obbligatori del segretario comunale. Faccio riferimento al mapping matr_003 ma vale anche per altri.
Nella webapp ho obbligatori: ruolo, nome e residenza
![image](https://github.com/user-attachments/assets/10b84bcc-75a2-4b1b-bbb9-00fc352fad48)
mentre nel mapping solo ruolo e nome
![image](https://github.com/user-attachments/assets/466a03b9-447b-4558-8185-c086800ac318)

Mi fate sapere se la documentazione è errata o meno, per favore?
grazie

**Comment by asqueglia** [comment]
Buongiorno, analizziamo il problema  e le facciamo sapere appena possibile.

**Comment by amusarra** [comment]
Risolta con il rilascio della release https://github.com/italia/ansc/releases/tag/v1.32.14
