### ISSUE TITLE
[R012]: Errore 400003 - Presa visione non trovata per id evento: 3414434

### ISSUE THREAD

**Issue by LucaBonini64** [italia/ansc#1024]
### Ambiente

pre-produzione

### Servizio

R012 - Servizi cooperativi firma elettronica del dichiarante

### idOperazione

assente

### idEvento o idAnsc

3414434

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Novi Ligure

### Data del test (yyyy-mm-dd)

2024-09-12

### Descrivi il problema

In un matrimonio civile, dopo aver eseguito l'upload dell'atto di matrimonio firmato dallo sposo e dai testimoni in maniera cartacea  alla richiesta dell'invio del link per la firma digitale della sposa il sistema restituisce l'errore: Presa visione non trovata per id evento: 3414434

### Come riprodurre il problema

1. Inserito un atto di matrimonio use case 311111
2. Validato l'atto di Stato Civile
3. Richiesta la presa visione per le firme cartacee ed ottenuta con IdOperazione 2492292
4. inserito l'allegato della presa visione (id allegato ansc 3024406)
5. richiesta il servizio R012 per la firma della sposa

### Payload (json)

```JSON
{
	"emailDichiarante": "luca.bonini@apkappa.it",
	"idEvento": "3414434",
	"idAnsc": "2024-3414434-21-006114",
	"firmatario": {
		"cognome": "DA FRE'",
		"nome": "GRAZIELLA"
	},
	"testataRichiesta": {
		"idComune": 6498,
		"idOperazioneComune": "885",
		"dataOraRichiesta": "2024-09-12T15:51:14.8203372+02:00",
		"nomeApplicativo": "hyperSIC.StatoCivile",
		"versioneApplicativo": "9.23.20.01.1L01",
		"fornitoreApplicativo": "APKAPPA S.r.l."
	}
}
```

**Comment by amusarra** [comment]
Salve @LucaBonini64 
Abbiamo preso in carico la segnalazione. 

Cordiali Saluti.
Supporto ANSC.

**Comment by amusarra** [comment]
Salve @LucaBonini64 
Abbiamo verificato sull'evento inviato in validazione che nessuno è impostato come firmatario. 

Cordiali Saluti.
Supporto ANSC.
