### ISSUE TITLE
[SC]: R007 errore firma evento di annotazione di rettifica

### ISSUE THREAD

**Issue by siscomanpr** [italia/ansc#1025]
### Ambiente

produzione

### Servizio

R007 - Servizi cooperativi firma ufficiale di stato civile

### idOperazione

330080

### idEvento o idAnsc

25570

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Comune di Loano

### Data del test (yyyy-mm-dd)

13/09/2024

### Descrivi il problema

Buongiorno, 
il comune di Loano sta cercando di firmare un evento di annotazione di rettifica in ambiente di produzione ma il servizio R007 restituisce errore bloccante `Firma non avvenuta con successo` (codice errore: 406004).
Hanno provato con più operatori inserendo più volte la password e l'OTP della firma remota, quindi escludiamo si possa trattare di un errore di credenziali.
Facciamo presente che la validazione dell'evento 25570 tramite il servizio R013 avviene correttamente. 

Potete verificare il motivo dell'errore?

P.S. Se può servire posso allegare i json delle richieste (e risposte) verso R013 e di R007.

Grazie per l'attenzione
Siscom SPA per il comune di LOANO.

**Comment by asqueglia** [comment]
Buongionro abbiamo preso in carico la verifica . Facciamo sapere appena possibile

**Comment by amusarra** [comment]
Risolta con il rilascio della release https://github.com/italia/ansc/releases/tag/v1.32.14
