### ISSUE TITLE
[SC]: Problemi con la 1311

### ISSUE THREAD

**Issue by OrazioCostanzo** [italia/ansc#1027]
### Ambiente

pre-produzione

### Servizio

R009 - Servizi cooperativi validazione evento

### idOperazione

2500652

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

COMUNETEST052032 - INF.OR

### Data del test (yyyy-mm-dd)

2024-09-16

### Descrivi il problema

Salve, ho riscontrato un problema con il caso 1311.

Secondo quanto riportato nel file CSV disponibile all'indirizzo https://github.com/italia/ansc/blob/main/docs/Mapping_casi_uso/trascrizioni/Trascr_005.csv e in base al funzionamento della web app, se nel campo trascrizioneNascita.atto.enteEstero viene inserita una nazione diversa da "ITALIA", allora è necessario fornire i seguenti dati:

1. trascrizioneNascita.atto.enteEstero.nomeAnagraficaConsolato
2. trascrizioneNascita.atto.enteEstero.idAnagraficaConsolato

Se, invece, la nazione indicata è "ITALIA", devono essere inseriti questi dati:

1. trascrizioneNascita.atto.enteEstero.siglaProvinciaEnte
2. trascrizioneNascita.atto.enteEstero.idProvinciaEnte
3. trascrizioneNascita.atto.enteEstero.nomeComuneEnte
4. trascrizioneNascita.atto.enteEstero.idComuneEnte

Ho tentato di inviare i dati con la seguente struttura JSON:

"trascrizioneNascita": {
   "testoLibero": "Riassunto libero",
   "attoEstero": {
      "enteEstero": {
         "nomeNazioneEnte": "FRANCIA",
         "nomeComuneEnte": "",
         "estremiDocumento": "estremi documento",
         "nomeAnagraficaConsolato": "",
         "comuneEstero": "localita estera",
         "siglaProvinciaEnte": "",
         "dataTrascrizione": "2024-09-04",
         "descrizione": "descrizione documento",
         "nazioneEnte": "61",
         "idComuneEnte": "",
         "nomeEnte": "Nome ente Trascrizione",
         "idAnagraficaConsolato": "",
         "idProvinciaEnte": ""
      }
   },
   "dataComunicazione": "2024-09-04",
   "atto": {
      "enteEstero": {
         "nomeNazioneEnte": "ITALIA",
         "nomeComuneEnte": "SAN CIPIRELLO",
         "estremiDocumento": "",
         "nomeAnagraficaConsolato": "",
         "comuneEstero": "",
         "siglaProvinciaEnte": "PA",
         "dataTrascrizione": "",
         "descrizione": "",
         "nazioneEnte": "90",
         "idComuneEnte": "8485",
         "nomeEnte": "Nome ente autorita mittente",
         "idAnagraficaConsolato": "",
         "idProvinciaEnte": "082"
      }
   }
}

Tuttavia, il servizio ha restituito un errore:
{
   "testataRisposta": {
      "idComune": 9493,
      "idOperazioneComune": "18059",
      "idOperazione": "2500867",
      "idEsito": 1
   },
   "errors": [
      {
         "code": "400003",
         "severity": "E",
         "text": "Per proseguire è necessario inserire un Ente estero"
      },
      {
         "code": "400003",
         "severity": "E",
         "text": "Per proseguire è necessario inserire un nome NazioneEnte estero"
      }
   ],
   "infos": [
      {
         "code": "110527",
         "severity": "I",
         "text": "Informazioni sull'operazione da fornire in caso di assistenza : data:2024-09-16 13:45:11 , idOperazione:2500867"
      }
   ]
}

Allego uno screen del payload creato direttamente dalla web app che e' identico a quello inviato al servizio.
![Screenshot 2024-09-16 152426](https://github.com/user-attachments/assets/12a4dd6b-de52-4677-9b00-e953e3a512bd)

### Payload (json)

```JSON
Request paylod completo:

{
   "testataRichiesta":{
      "versioneApplicativo":"1.0.0",
      "idOperazioneComune":"18059",
      "idComune":9493,
      "dataOraRichiesta":"2024-09-16T13:45:10.495709",
      "nomeApplicativo":"SIDe",
      "fornitoreApplicativo":"SistemiInformativi"
   },
   "evento":{
      "operatoreNome":"Alessandro",
      "idTipoEvento":"1",
      "composizioneCompleta":"Oggi ventotto del mese agosto dell'anno duemilaventiquattro alle ore undici e minuti quarantatre nella Casa Comunale.\r\nIo sottoscritto Ufficiale JENTE Ufficiale dello Stato Civile del Comune di Siena per delegazione avuta ho ricevuto dalla Direzione dell'Azienda Ospedaliera Universitaria Senese la dichiarazione di nascita n. ... pervenuta al protocollo di questo Comune in data 28\/08\/2024 prot. ......  relativa a:   NEW1311 NEW1311\r\ndi cui mi ha trasmesso copia.\r\nAderendo a tale richiesta provvedo alla trascrizione per intero del documento come segue:\r\nATTO DI DICHIARAZIONE DI NASCITA\r\nL'anno duemilaventiquattro addi' ventotto del mese di agosto alle ore |OREREG| e minuti |MINREG|\r\npresso l'Azienda Ospedaliera Universitaria Senese, sita nel Comune di Siena, innanzi al sottoscritto addetto alla Direzione Sanitaria, a cio' espressamente autorizzato dal Direttore Sanitario, con delega conservata in atti, e' comparso il Signor:\r\n PAPINI RICCARDO\r\nnato a CAMPIGLIA MARITTIMA\r\nil 18\/02\/1957\r\nresidente in SIENA\r\ncittadino Italiano\r\n-\r\nil quale nella sua veste di padre dichiara quanto segue:\r\n-\r\nIl giorno uno del mese di gennaio dell'anno millenovecentoottanta\r\nalle ore undici e minuti undici\r\n-\r\nin questo Centro di nascita e' nato un bambino di sesso MASCHILE\r\nal quale viene attribuito il nome di NEW1311\r\n-\r\nDetto bambino, la cui nascita e' comprovata dall'allegata attestazione  di nascita, e' nato dalla Signora:\r\nLEONI LORELLA\r\nnata a FOLLONICA\r\nil 15 settembre 1960\r\ncittadina Italiana\r\nresidente in SIENA\r\n-\r\nconiugata con il Signor PAPINI RICCARDO\r\nnato a CAMPIGLIA MARITTIMA\r\nil 18 febbraio 1957\r\ncittadino Italiano\r\nresidente a SIENA\r\n-\r\nIl bambino medesimo e' gemello con altro al quale si riferisce il precedente\/seguente atto n.=== ed e' il PRIMO\/SECONDO nato come mi ha attestato il dichiarante.\r\n-\r\nIl presente atto, dopo essere stato letto, viene insieme con me sottoscritto dal dichiarante ed inviato, per sua espressa volonta', al Comune di: SIENA.\r\nIl dichiarante f.to PAPINI RICCARDO\r\nL'Addetto della Direzione Sanitaria firma autografa omessa (art.3 D.L.39\/1993)\r\n(\r\n-\r\n-\r\n-\r\n-\r\n-\r\n-\r\n-\r\n-\r\n-\r\n-\r\n-\r\n-\r\n-\r\n-\r\n-\r\nDopo di che ho munito del mio visto ed inserito nel volume degli allegati a questo registro la copia dell'attestazione di nascita e del documento trascritto.\r\nL'UFFICIALE DELLO STATO CIVILE",
      "idVersion":"100012",
      "annoAtto":"2024",
      "intestatari":[
         {
            "siglaProvinciaResidenza":"",
            "nomeStatoNascita":"ITALIA",
            "dataNascita":"2024-01-01",
            "cognome":"NEW1311",
            "nazionalita":"ITALIANA",
            "codiceFiscale":"NWENWE80M20G273Z",
            "idStatoResidenza":"",
            "idStatoNascita":"90",
            "nomeComuneResidenza":"",
            "flagComparente":true,
            "nomeComuneNascita":"PALERMO",
            "flagFirmatario":true,
            "flagDichiarante":false,
            "id":"",
            "idComuneNascita":"6843",
            "idNazionalita":"90",
            "idProvinciaNascita":"082",
            "indirizzoResidenza":"",
            "descrizionestatocivile":"",
            "idComuneResidenza":"",
            "idsoggettoanpr":"",
            "idProvinciaResidenza":"",
            "documentoRiconoscimento":{
               
            },
            "nome":"NEW1311",
            "idstatocivile":"",
            "siglaProvinciaNascita":"PA",
            "nomeStatoResidenza":"",
            "sesso":"M"
         }
      ],
      "allegati":[
         {
            "hashAllegato":"HksTH8CFhTxZmY12AT7uJimGZvCSIefbRGwvEtH6E04=",
            "idStatoAllegato":"3",
            "id":"2921342",
            "idTipoAllegato":"27"
         },
         {
            "hashAllegato":"HksTH8CFhTxZmY12AT7uJimGZvCSIefbRGwvEtH6E04=",
            "idStatoAllegato":"3",
            "id":"2921343",
            "idTipoAllegato":"26"
         }
      ],
      "stato":"CONFERMATO",
      "padre":{
         "siglaProvinciaResidenza":"SI",
         "nomeStatoNascita":"ITALIA",
         "dataNascita":"1957-02-18",
         "cognome":"PAPINI",
         "nazionalita":"ITALIANA",
         "codiceFiscale":"PPNRCR57B18B509W",
         "idStatoResidenza":"90",
         "idStatoNascita":"90",
         "nomeComuneResidenza":"SIENA",
         "flagComparente":false,
         "nomeComuneNascita":"CAMPIGLIA MARITTIMA",
         "flagFirmatario":false,
         "flagDichiarante":false,
         "id":"",
         "idComuneNascita":"1643",
         "idNazionalita":"90",
         "idProvinciaNascita":"049",
         "indirizzoResidenza":"",
         "idComuneResidenza":"9493",
         "idsoggettoanpr":"24708050",
         "idProvinciaResidenza":"052",
         "documentoRiconoscimento":{
            
         },
         "nome":"RICCARDO",
         "siglaProvinciaNascita":"LI",
         "nomeStatoResidenza":"ITALIA",
         "sesso":"M"
      },
      "descrizioneCasoUso":"Trascrizione di nascita: Trascrizione di atto di nascita avvenuta all'estero su richiesta dell'autorita' diplomatica o consolare",
      "numeroatto":"4211",
      "ausilioInterprete":false,
      "operatore":"PTTRNZ66L13C661Y",
      "dataformazione":"2024-08-28",
      "ora":"11",
      "trascrizioneNascita":{
         "testoLibero":"Riassunto libero",
         "attoEstero":{
            "enteEstero":{
               "nomeNazioneEnte":"FRANCIA",
               "nomeComuneEnte":"",
               "estremiDocumento":"estremi documento",
               "nomeAnagraficaConsolato":"",
               "comuneEstero":"localita estera",
               "siglaProvinciaEnte":"",
               "dataTrascrizione":"2024-09-04",
               "descrizione":"descrizione documento",
               "nazioneEnte":"61",
               "idComuneEnte":"",
               "nomeEnte":"Nome ente Trascrizione",
               "idAnagraficaConsolato":"",
               "idProvinciaEnte":""
            }
         },
         "dataComunicazione":"2024-09-04",
         "atto":{
            "enteEstero":{
               "nomeNazioneEnte":"ITALIA",
               "nomeComuneEnte":"SAN CIPIRELLO",
               "estremiDocumento":"",
               "nomeAnagraficaConsolato":"",
               "comuneEstero":"",
               "siglaProvinciaEnte":"PA",
               "dataTrascrizione":"",
               "descrizione":"",
               "nazioneEnte":"90",
               "idComuneEnte":"8485",
               "nomeEnte":"Nome ente autorita mittente",
               "idAnagraficaConsolato":"",
               "idProvinciaEnte":"082"
            }
         }
      },
      "minuto":"43",
      "operatoreCognome":"Ghinelli",
      "datiDiNascita":{
         "sceltaCognome":"6",
         "minutoNascita":"11",
         "natoVivoMaDeceduto":"",
         "luogoFiliazione":"",
         "oraNascita":"11",
         "tipoAccertamento":"",
         "natoMorto":"",
         "precisazioneCognome":""
      },
      "idComuneRegistrazione":"9493",
      "madre":{
         "siglaProvinciaResidenza":"SI",
         "nomeStatoNascita":"ITALIA",
         "dataNascita":"1960-09-15",
         "cognome":"LEONI",
         "nazionalita":"ITALIANA",
         "codiceFiscale":"LNELLL60P55D656W",
         "idStatoResidenza":"90",
         "idStatoNascita":"90",
         "nomeComuneResidenza":"SIENA",
         "flagComparente":false,
         "nomeComuneNascita":"FOLLONICA",
         "flagFirmatario":false,
         "flagDichiarante":false,
         "id":"",
         "idComuneNascita":"3960",
         "idNazionalita":"90",
         "idProvinciaNascita":"053",
         "indirizzoResidenza":"",
         "idComuneResidenza":"9493",
         "idsoggettoanpr":"24708048",
         "idProvinciaResidenza":"052",
         "documentoRiconoscimento":{
            
         },
         "nome":"LORELLA",
         "siglaProvinciaNascita":"GR",
         "nomeStatoResidenza":"ITALIA",
         "sesso":"F"
      },
      "idUsecase":"1311",
      "idProvinciaRegistrazione":"052",
      "siglaProvinciaRegistrazione":"SI",
      "idtipocontenuto":"1",
      "redattoNellaCasaComunale":true,
      "ruoloOperatore":"1",
      "nomeComuneRegistrazione":"SIENA"
   }
}
```

**Comment by gbuemi** [comment]
Buon pomeriggio,
confermiamo che è necessario inserire un ente estero. La webapp in fase di compilazione assume il comportamento da lei descritto però, cliccando sulla validazione, ottiene lo stesso errore che riscontra sui servizi cooperativi.

Un saluto,
Supporto ANSC

**Comment by OrazioCostanzo** [comment]
Buon pomeriggio,
come ente estero che dati accetta?

**Comment by OrazioCostanzo** [comment]
Buongiorno, Ho bisogno di capire come risolvere questo problema dato che si propone anche creando l'atto via webapp.
Anche tra i dati della webapp non riesco a trovare ente estero e nome ente estero.

Aspetto vostre notizie.

**Comment by gbuemi** [comment]
Buon pomeriggio @OrazioCostanzo ,
essendo rimasta chiusa la issue ci era sfuggito il commento della settimana scorsa.

Come indicato sulla documentazione al link https://github.com/italia/ansc/blob/main/docs/openapi/model_evento.yaml :

- il campo `evento.trascrizioneNascita.atto.enteEstero.nazioneEnte` non può essere ITALIA perchè l'enteEstero è appunto estero (decodifica ANPR_02)
- il campo `evento.trascrizioneNascita.atto.enteEstero.nomeNazioneEnte` è la descrizione dello stato coerente con l'identificativo al punto precedente.

A seguire un esempio di oggetto trascrizioneNascita coerente

`"trascrizioneNascita": {
            "atto": {
                "enteEstero": {
                    "comuneEstero": "",
                    "dataTrascrizione": "",
                    "descrizione": "",
                    "estremiDocumento": "",
                    "idAnagraficaConsolato": "181",
                    "idComuneEnte": "",
                    "idProvinciaEnte": "",
                    "nazioneEnte": "2",
                    "nomeAnagraficaConsolato": "TIRANA",
                    "nomeComuneEnte": "",
                    "nomeEnte": "Nome ente autorita mittente",
                    "nomeNazioneEnte": "ALBANIA",
                    "siglaProvinciaEnte": ""
                }
            },
            "attoEstero": {
                "enteEstero": {
                    "comuneEstero": "localita estera",
                    "dataTrascrizione": "2024-09-04",
                    "descrizione": "descrizione documento",
                    "estremiDocumento": "estremi documento",
                    "idAnagraficaConsolato": "",
                    "idComuneEnte": "",
                    "idProvinciaEnte": "",
                    "nazioneEnte": "2",
                    "nomeAnagraficaConsolato": "",
                    "nomeComuneEnte": "",
                    "nomeEnte": "Nome ente Trascrizione",
                    "nomeNazioneEnte": "ALBANIA",
                    "siglaProvinciaEnte": ""
                }
            },
            "dataComunicazione": "2024-09-04",
            "testoLibero": "Riassunto libero"
        }`

Un saluto,
Supporto ANSC

**Comment by OrazioCostanzo** [comment]
Grazie per la risposta.
Il mio dubbio e' nato a causa della presenza di "ITALIA" tra gli stati da poter scegliere nella lista presente nella webapp.
