### ISSUE TITLE
[SC]: usecase 11111000 - errore su firma attestazione di conformità

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#1028]
### Ambiente

pre-produzione

### Servizio

R007 - Servizi cooperativi firma ufficiale di stato civile

### idOperazione

non pervenuto

### idEvento o idAnsc

2024-3414796-027042

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

venezia, anna grossi

### Descrivi il problema

Buongiorno,
il comune richiede lo scarico dell'attestazione di conformità. Al momento della firma dell'ufficiale di tale allegato si riceve la seguente risposta 
![image](https://github.com/user-attachments/assets/f48b2ce5-6ac7-461d-ab67-9b0e96fa8bb7)

Il significato di questo errore? Problema vostro?

**Comment by gbuemi** [comment]
Buongiorno @annamaraspin,
dai dati forniti vediamo che l'atto 3414796 si trova nello stato "FIRMATO PER CONFORMITA", firma effettuata alle 8:31 di questa mattina. Ipotizziamo quindi che state provando a firmarlo nuovamente.

Per approfondire il KO della singola chiamata è necessario fornirci dei dettagli in più, come HTTP URL, payload inviato, JWT token, http code response, relativo payload e orario della richiesta. Vi raccomandiamo di fornire sempre l'id operazione per velocizzare l'analisi.

Se non sono necessarie ulteriori verifiche vi chiediamo gentilmente di chiudere la issue.

Un saluto,
Supporto ANSC

**Comment by annamaraspin** [comment]
il primo tentativo è andato male, altrimenti non avrebbero continuato a firmare.
dirò all'utente di rifare un altro atto uguale, non posso fare altro a questo punto
grazie lo stesso

**Comment by gbuemi** [comment]
Per evitare che ci sia un problema lato client o qualsiasi altra questione che non dipenda dai servizi cooperativi ANSC vi confermiamo che gli accessi sono 4, il primo conclusosi con successo e gli altri KO. A seguire gli orari:

- 8:31:54 -> OK
- 8.32:11 -> KO
- 8:32:46 -> KO
- 8:40:55 -> KO

Per qualche ragione dopo l'avvenuta firma di attestazione di conformità sono stati fatti altri accessi. Pertanto anche con un altro atto uguale potrebbe verificarsi il problema che non dipende da ANSC.

Grazie e saluti,
Supporto ANSC
