### ISSUE TITLE
[SC]: Estratto per copia integrale - Errore interno

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#1029]
### Ambiente

pre-produzione

### Servizio

R002 - Servizi cooperativi certificazioni

### idOperazione

2502723

### idEvento o idAnsc

3414756

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Lissone - biadanpad

### Data del test (yyyy-mm-dd)

2024-09-17

### Descrivi il problema

Richiamando il servizio per la generazione dell'estratto per copia integrale si riceve l'errore in oggetto

### Payload (json)

```JSON
REQUEST:
{
  "idAnsc": "2024-3414756-35-108028",
  "idEvento": "3414756",
  "richiedente": {
    "cognome": "ROSSI",
    "nome": "GIAMMARIA",
    "sesso": "M",
    "dataNascita": "2024-09-14",
    "idComuneNascita": "5000",
    "nomeComuneNascita": "LISSONE (MB)",
    "idProvinciaNascita": "108",
    "siglaProvinciaNascita": "MB",
    "idStatoNascita": "90",
    "nomeStatoNascita": "ITALIA",
    "idComuneResidenza": "5000",
    "nomeComuneResidenza": "LISSONE (MB)",
    "idProvinciaResidenza": "108",
    "siglaProvinciaResidenza": "MB",
    "idStatoResidenza": "90",
    "nomeStatoResidenza": "ITALIA",
    "idNazionalita": "90",
    "nazionalita": "ITALIANA"
  },
  "intestatario": {
    "id": "3118554"
  },
  "idTipoCertificato": "3",
  "conPaternitaMaternita": false,
  "usoMatrimonio": false,
  "testataRichiesta": {
    "idComune": 5000,
    "idOperazioneComune": "11795",
    "dataOraRichiesta": "2024-09-17T09:01:39.558+02:00",
    "nomeApplicativo": "urbi",
    "versioneApplicativo": "1.3.10",
    "fornitoreApplicativo": "padigitale"
  }
}

RESPONSE:
{
  "testataRisposta": {
    "idComune": 5000,
    "idOperazioneComune": "11795",
    "idOperazione": "2502723"
  },
  "errors": [
    {
      "code": "500",
      "severity": "E",
      "text": "Errore interno"
    }
  ],
  "infos": [
    {
      "code": "110527",
      "severity": "I",
      "text": "Informazioni sull'operazione da fornire in caso di assistenza : data:2024-09-17 07:01:40 , idOperazione:2502723"
    }
  ]
}
```

**Comment by asqueglia** [comment]
Il problema è stato risolto

**Comment by biadanpad** [comment]
No, continuo a ricevere lo stesso errore

idOperazione: 2594618, 2594693

REQUEST:
{
    "idAnsc": "2024-3414756-35-108028",
    "idEvento": "3414756",
    "richiedente": {
        "codiceFiscale": "CTTMGH68B41E617G",
        "cognome": "CITTERIO",
        "nome": "MARGHERITA",
        "sesso": "F",
        "dataNascita": "1968-02-01",
        "idComuneNascita": "5001",
        "nomeComuneNascita": "LISSONE",
        "idProvinciaNascita": "15",
        "siglaProvinciaNascita": "MI",
        "idStatoNascita": "90",
        "nomeStatoNascita": "ITALIA",
        "idComuneResidenza": "5000",
        "nomeComuneResidenza": "LISSONE",
        "idProvinciaResidenza": "108",
        "siglaProvinciaResidenza": "MB",
        "idStatoResidenza": "90",
        "nomeStatoResidenza": "ITALIA",
        "indirizzoResidenza": "VIA MAMELI GOFFREDO,52 sc.C int.0"
    },
    "intestatario": {
        "id": "3118554"
    },
    "idTipoCertificato": "3",
    "testataRichiesta": {
        "idComune": 5000,
        "idOperazioneComune": "0",
        "dataOraRichiesta": "2024-10-10T10:53:12.336+02:00",
        "nomeApplicativo": "urbi",
        "versioneApplicativo": "1.4.0",
        "fornitoreApplicativo": "padigitale"
    }
}

RESPONSE:
{
    "testataRisposta": {
        "idComune": 5000,
        "idOperazioneComune": "0",
        "idOperazione": "2594693"
    },
    "errors": [{
            "code": "500",
            "severity": "E",
            "text": "Errore interno"
        }
    ],
    "infos": [{
            "code": "110527",
            "severity": "I",
            "text": "Informazioni sull'operazione da fornire in caso di assistenza : data:2024-10-10 08:53:14 , idOperazione:2594693"
        }
    ]
}

**Comment by asqueglia** [comment]
Buongiorno comunichiamo che con la patch 1.33.3 è stata rilasciata la correttiva.
