### ISSUE TITLE
Atto di morte - Caso d'uso Morte_004

### ISSUE THREAD

**Issue by antonioluberto** [italia/ansc#103]
Il caso d'uso in oggetto si riferisce al caso di
"Decesso relativo a cadavere rinvenuto non identificato".
In queste situazioni, l'ufficiale di stato civile riceve comunicazione tipicamente dal Tribunale di competenza, comunque da Ente italiano; la modellazione prevede invece attualmente l'indicazione dei campi:

![image](https://github.com/italia/ansc/assets/26415430/b90c5199-7f0b-4f40-9664-5910dfff0469)

riferiti ad ipotetica autorità estera.
Potreste chiarire/correggere?
Grazie,
Antonio

**Comment by anbatistini** [comment]
Buongiorno,
verifichiamo e le facciamo sapere.

**Comment by anbatistini** [comment]
Normativamente può esistere la casistica in cui la comunicazione proviene da un ente estero?

**Comment by antonioluberto** [comment]
Ritengo di no: l'usc redige un atto di morte a seguito di rinvenimento di cadavere non identificato, solo se il rinvenimento avviene sul proprio territorio comunale e solo a seguito di indicazione da parte dell'autorità giudiziaria (che dubito possa pertanto mai essere autorità straniera).

**Comment by asqueglia** [comment]
Buongiorno, confermiamo che per il caso d'uso segnalato, provvederemo ad apportare la correzione utilizzando l'ente italiano. Le faremo sapere non appena rilasciamo la correttiva.

**Comment by asqueglia** [comment]
Buongiorno con la versione 1.9.0 appena rilasciata abbiamo corretto l'errore. E' possibile riprovare. chiudiamo la issue in caso vi preghiamo di riaprirla.
