### ISSUE TITLE
[webapp]: duplicazione anagrafiche atto di matrimonio

### ISSUE THREAD

**Issue by antonioluberto** [italia/ansc#1030]
### Ambiente

produzione

### Provenienza segnalazione

Software House

### Riferimenti operatore/comune

Grottaferrata

### Data del test (yyyy-mm-dd)

14/09/2024

### Caso d'uso

Matr_001

### Descrivi il problema

Atto di matrimonio 2024-28143-848-058046
E' stato creato da Web App l'atto di matrimonio per i soggetti:
- Cesarini Paolo, Id ANSC: 15920288
- Di Pietro Francesca, Id ANSC: 15920291

All'atto della creazione, per i due soggetti non è stata eseguita ricerca da ANPR; si è invece proceduto all'inserimento manuale delle generalità con il risultato che le due anagrafiche in questione risultano prive dell' Id ANPR (Cesarini Paolo ha in effetti idANPR = 100968452; Di Pietro Francesca ha in effetti idANPR = 103077599).
Allo stato attuale abbiamo quindi, sia per lo sposo che per la sposa:
- un'anagrafica con Id ANSC valorizzato e Id ANPR non valorizzato,
- un'anagrafica con Id ANSC non valorizzato e Id ANPR valorizzato.

Le due anagrafiche riferiscono in effetti al medesimo soggetto.
E' possibile unificare le due coppie di anagrafiche?
E' pensabile rendere disponibile su WebApp una funzionalità che consenta all'utente di procedere autonomamente alla riconciliazione delle anagrafiche in casi quali quelli sopra descritti?

**Comment by rvinzani** [comment]
E' possibile riconciliare le anagrafiche tramite la funzione presente sulla web app Riconciliazione soggetto per id presente nel menù Altri servizi oppure utilizzando il servizio R0018_servizi.
Chiudo la issue pregandola di riaprirla nel caso avesse ulteriori richieste inerenti lo stesso argomento

**Comment by antonioluberto** [comment]
Buongiorno.
Abbiamo provato la funzionalità sulla webApp indicata da ANSC ma, per entrambe le anagrafiche (i due coniugi) si ottiene il seguente errore:

![image](https://github.com/user-attachments/assets/8f0fb86d-bfcb-4db4-ba67-be8610e07a8e)

**Comment by asqueglia** [comment]
Buon pomeriggio, verifichiamo e le facciamo sapere

**Comment by asqueglia** [comment]
Buon pomeriggio, il servizio di riconciliazione è stato implementato allo scopo di riconciliare due soggetti censiti in ansc con due identificativi diversi (idAnsc diversi) ma con stessa anagrafica in quanto rispondenti ad uno stesso soggetto. Il servizio non è stato pensato per riconciliare una anagrafica presente in ansc e una presente solo in anpr; valuteremo se estendere il servizio di riconciliazione per consentire questa possibilità.

**Comment by asqueglia** [comment]
Chiudiamo la issue
