### ISSUE TITLE
[SC]: [R005] Errore in ricerca intestatario con dati anagrafici

### ISSUE THREAD

**Issue by LucaBonini64** [italia/ansc#1037]
### Ambiente

pre-produzione

### Servizio

R005 - Servizi cooperativi consultazione

### idOperazione

2506763

### idEvento o idAnsc

assente

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Novi Ligure

### Data del test (yyyy-mm-dd)

2024-09-17

### Descrivi il problema

Eseguendo una ricerca su 'https://anscservicepre.anpr.interno.it/services/service/ricerca/consultazione/ansc/intestatario/1' inserendo nei criteri ricerca soggetto i dati anagrafici otteniamo l'errore "400003" - "Data di Nascita non valido".
La data da nascita del soggetto ricercato ci sembra inserita correttamente e la richiesta per il medesimo soggetto eseguita tramite codice fiscale funziona correttamente.

### Come riprodurre il problema

1. Inviare all'url indicato una richiesta come da Payload sotto riportato

### Payload (json)

```JSON
{
	"criteriRicercaSoggetto": {
		"cognome": "ROSSINI",
		"nome": "ROBERTO",
		"sesso": "M",
		"idComuneNascita": "7308",
		"nomeComuneNascita": "PISA",
		"siglaProvinciaNascita": "PI",
		"codiceStatoNascita": "90",
		"nomeStatoNascita": "ITALIA",
		"datanascita": "1936-11-12T00:00:00"
	},
	"testataRichiesta": {
		"idComune": 6498,
		"idOperazioneComune": "940",
		"dataOraRichiesta": "2024-09-17T17:46:01.1740979+02:00",
		"nomeApplicativo": "hyperSIC.StatoCivile",
		"versioneApplicativo": "9.23.20.01.1L01",
		"fornitoreApplicativo": "APKAPPA S.r.l."
	}
}
```

**Comment by asqueglia** [comment]
Buongiorno la data di nascita è stata trasmessa con un formato non valido, come espressamente riportato nel messaggio di errore. Il formato valido è yyyy-gg-mm senza il timezone.
Un payload funzionante senza il codice fiscale è ad esempio questo che vi riportiamo di seguito:

 "criteriRicercaSoggetto": {
        "cognome": "ROSSINI",
        "nome": "ROBERTO",
        "sesso": "M",
        "idComuneNascita": "7308",
        "nomeComuneNascita": "PISA",
        "siglaProvinciaNascita": "PI",
        "idStatoNascita": "90",
        "datanascita": "1936-11-12",
        "idComuneResidenza": 7308,
        "nomeStatoNascita": "ITALIA",
        "idProvinciaNascita": 50,
        "idProvinciaResidenza": 50,
        "idStatoResidenza": "90"
    } 

Chiudiamo pertanto la issue. Se ne avete necessità apritene una altra specifica.
