### ISSUE TITLE
Firma dichiarante non obbligatoria.

### ISSUE THREAD

**Issue by gcuci** [italia/ansc#104]
buongiorno,

segnaliamo un problema di processo, relativamente allo step di 'Firma Dichiarante' per gli Eventi.

In alcuni casi, per alcune tipologie di Atti (es. Atto di Morte parte II serie B, Atto di Nascita parte II serie B, ... ed altri), non è prevista l'obbligatorietà della firma del dichiarante.

L'attuale flusso ANSC, però, prevede obbligatoriamente l'esecuzione di questo step, prima di poter eseguire il successivo di 'Firma USC'.

Bisognerebbe rivedere questo vincolo, per poter completare la registrazione dell'Evento, anche per questa tipologia di Atti. 

In attesa di un riscontro,

cordiali saluti.

**Comment by asqueglia** [comment]
Chiudo la issue, nel caso la riapra.
