### ISSUE TITLE
[SC]: API non allineate con i mapping dei casi d'uso (flagIrreperibile)

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#1043]
### Ambiente

pre-produzione, produzione

### Servizio

R009 - Servizi cooperativi validazione evento

### idOperazione

-

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Lissone - biadanpad

### Data del test (yyyy-mm-dd)

2024-09-19

### Descrivi il problema

Le API non sono allineate con i mapping dei casi d'uso: manca il campo flagIrreperibile nella classe ModelSoggetto

**Comment by asqueglia** [comment]
Buongiorno, la gestione dei soggetti irreperibili non è ancora stata rilasciata. Da piano operativo il rilascio è previsto per fine settembre inizio ottobre, come indicato nella roadmap

https://github.com/italia/ansc/blob/main/docs/Roadmap.md

 Chiudiamo pertanto la issue
