### ISSUE TITLE
[SC]: usecase 411212 - dati obbligatori non reperibili perché inesistenti

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#1046]
### Ambiente

pre-produzione

### Servizio

R009 - Servizi cooperativi validazione evento

### idOperazione

assente

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

venezia, anna 

### Descrivi il problema

Buongiorno,
il Comune di Venezia mi ha riferito che nella casistica di imminente pericolo di vita non c'è la richiesta di costituzione.
Dai mapping invece sono dati obbligatori .
Se avete bisogno di ulteriori informazioni, resto a disposizione per contattare l'utente

**Comment by asqueglia** [comment]
Buongionro verifichiamo e le facciamo sapere.

**Comment by annamaraspin** [comment]
Buongiorno,
ci sono novità ? Nella 1.33 ho visto che il mapping è rimasto coi campi obbligatori
