### ISSUE TITLE
[SC]: caso d'uso 311111 -cittadinanza dei testimoni-data di nascita del celebrante -

### ISSUE THREAD

**Issue by dandreap** [italia/ansc#1047]
### Ambiente

pre-produzione

### Servizio

R001 - Servizi cooperativi allegati, R002 - Servizi cooperativi certificazioni, R003 - Servizi cooperativi comunicazioni, R004 - Servizi cooperativi consultazione anagrafe per gestione anagrafica evento di stato civile

### idOperazione

assente

### idEvento o idAnsc

3414372

### Provenienza segnalazione

Comune

### Comune di riferimento e operatore

comune di Tarcento

### Data del test (yyyy-mm-dd)

20-09-2024

### Descrivi il problema

Nell'atto non è previsto che venga inserita la data di nascita del celebrante e la cittadinanza dei testimoni. Pertanto tali dati non dovrebbero essere richiesti (in quanto la normativa non prevede l'inserimento di tali dati nell'atto di matrimonio) e tanto meno dovrebbero comparire nei metadati della copia integrale dell'atto

**Comment by rvinzani** [comment]
Buongiorno, i dati da lei citati, sebbene possano essere inviati al sistema, non sono dati obbligatori. Quindi possono essere omessi.
Chiudo la issue. Nel caso ci fossero ulteriori richieste di chiarimento si prega di riaprire la issue stessa. Saluti
