### ISSUE TITLE
[webapp]: dichiarazioni di nascita- non prevista l'indicazione della cittadinanza del nato 

### ISSUE THREAD

**Issue by dandreap** [italia/ansc#1048]
### Ambiente

pre-produzione

### Provenienza segnalazione

Comune

### Riferimenti operatore/comune

D'ANDREA PAOL

### Descrivi il problema

Nell'atto di nascita (dichiarazione di nascita) di un bimbo appena nato, la cittadinanza del nato NON deve essere inserita. Nell'atto non è indicata in nessun posto. La normativa (combinato disposto artt.11, 29, 30 e 31 dpr 396/2000 e formulario D.M.5/4/2002) non prevede l'indicazione della cittadinanza del nuovo nato, sia essa conosciuta o da definire. Pertanto tale dato non dovrebbe essere reso obbligatorio e tanto meno dovrebbe comparire nei metadati indicati nell'estratto per copia integrale.

**Comment by asqueglia** [comment]
Buongiorno, come da lei indicato il sistema non richiede la cittadinanza per il soggetto nato come si evince dalle schermate della Web App ANSC

![image](https://github.com/user-attachments/assets/37c2f39c-f70d-4edc-b60e-2afb12a68bb3)


Chiudiamo oertanto la issue. In caso di ulteriori dubbi si prega di aprirne una altra dedicata.
