### ISSUE TITLE
Indisponibilità Web app ANSC ambiente di preproduzione

### ISSUE THREAD

**Issue by rvinzani** [italia/ansc#105]
Si comunica una momentanea indisponibilità della web app di ANSC dell'ambiente di preproduzione
Verrà comunicato tempestivamente l'avvenuto ripristino non appena l'applicazione tornerà disponibile

**Comment by antonioluberto** [comment]
Si segnala il mancato funzionamento anche della WebApp di ANPR

**Comment by mttfranci** [comment]
@antonioluberto l'anomalia dovvrebbe essere superata. Potreste riprovare?
Saluti

Assistenza ANSC

**Comment by antonioluberto** [comment]
Buongiorno.
La WebApp ANSC ha ripreso a funzionare, confermo.
Continua, invece, a non funzionare la WebApp ANPR sul medesimo ambiente; potete darci indicazioni anche in relazione a quest'ultima?

**Comment by mttfranci** [comment]
Buongiorno @antonioluberto  io riesco ad accedere correttamente alla web app di anpr in test. Avete tutti il problema?

**Comment by antonioluberto** [comment]
Ora riesco ad accedere anche alla WebApp di ANPR
