### ISSUE TITLE
[SC]: Anteprima atto UseCase 52341

### ISSUE THREAD

**Issue by KibMcris** [italia/ansc#1050]
### Ambiente

pre-produzione

### Servizio

R010 - Servizi cooperativi anteprima

### idOperazione

2517822

### idEvento o idAnsc

2024-3415373-174-102044

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Tropea

### Data del test (yyyy-mm-dd)

20/09/2024

### Descrivi il problema

Con idoperazionecomune=2403 è stato correttamente validato il caso d'uso in oggetto. L'evento ha idansc 2024-3415373-174-102044. Con successiva operazionecomune=2404 è stata richiesta l'anteprima dell'atto con servizio R010. ANSC risponde con errore
`HTTP Status 400 
{"testataRisposta":{"idComune":10288,"idOperazioneComune":"2404","idOperazione":"2517822","idEsito":1},"errors":[{"code":"400003","severity":"E","text":"Dati in ingresso non corretti"}],"infos":[{"code":"110527","severity":"I","text":"Informazioni sull'operazione da fornire in caso di assistenza : data:2024-09-20 07:17:21 , idOperazione:2517822"}]}`

**Comment by gbuemi** [comment]
Buongiorno,
abbiamo preso in carico la issue.

Un saluto
Supporto ANSC

**Comment by gbuemi** [comment]
La segnalazione è stata corretta e appena rilasciata con la versione 1.33.0
