### ISSUE TITLE
[SC]: manca spazio firma per avvocati

### ISSUE THREAD

**Issue by Hdemografici** [italia/ansc#1054]
### Ambiente

pre-produzione

### Servizio

R010 - Servizi cooperativi anteprima

### idOperazione

2519275

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

colli al metauro

### Data del test (yyyy-mm-dd)

2024-09-20

### Descrivi il problema

con al validazione R009 - idOperazione: 2519274 - sono stati inviati i dati degli avvocati con indicata la loro presenza, nella successiva R010 c'è lo spazio per la firma solo per gli sposi, è corretto o devono firmare anche gli avvocati se sono presenti?

**Comment by asqueglia** [comment]
Buongiorno prendiamo in carico la segnalazione, confermiamo che anche gli avvocati dovrebbero firmare l'atto.

**Comment by gbuemi** [comment]
La segnalazione è stata corretta e appena rilasciata con la versione 1.33.0
