### ISSUE TITLE
[SC]: Informazioni su campi presenti servizio R016 e suo utilizzo nei provvedimenti di rifiuto delle notifiche

### ISSUE THREAD

**Issue by MichelaGarzoni** [italia/ansc#1055]
### Ambiente

pre-produzione

### Servizio

R008 - Servizi cooperativi notifiche

### idOperazione

assente

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Duino - Aurisina

### Descrivi il problema

Buongiorno,
ho alcuni dubbi in relazione ai provvedimenti di rifiuto delle notifiche in quanto non riesco ad evidenziare quali servizi cooperativi utilizzare per poter eseguire le stesse cose che vengono presentate lato web-app e non trovo documentazione in merito a questo processo.

In elenco i miei dubbi:

1- sulla web-app, dopo il primo rifiuto di una notifica, mi viene chiesto di inserire un provvedimento: a questo punto, utilizzando il servizio cooperativo [R008]/notifiche/ricerca il campo idStatoFlussoNotifiche assume il valore 3(rifiutato). Se inserisco il provvedimento di rifiuto e rieseguo la ricerca della notifica, questa presenta sempre il valore 3 nel campo idStatoFlussoNotifiche. Come faccio a distinguere lato servizio cooperativo se per la notifica è stato inserito già il provvedimento di rifiuto o meno?

2- [R008]/notifiche/ricerca: impostando un intervallo temporale come filtro di ricerca, ottengo un elenco di notifiche. Per le notifiche relative alle "annotazioni automatiche" ho presente l'idAnsc dell'annotazione, ma non ha nessun campo che faccia riferimento all'evento per cui è stata generata tale annotazione. Come faccio a collegare tale annotazione all'evento?

3- Web-App inserimento provvedimento di rifiuto: oltre ai campi "motivazione rifiuto" e "numero protocollo provvedimento rifiuto" richiede di inserire l'intestatario (un eventuale secondo intestatario) e gli allegati relativi al provvedimento di rifiuto, i quali sono da verificare e convalidare. A termine si passa alla validazione del provvedimenti di rifiuto. Sui servizi cooperativi, il servizio di validazione del provvedimento di rifiuto da utilizzare è l'[R016]/rifiuto/validazione/evento? in tal caso, come mai nello yaml non trovo la struttura ed i campi da popolare relativi agli allegati inviati e agli intestatari? E' errata la mia interpretazione su quale servizio utilizzare? Qual è la sequenza corretta dei servizi da richiamare?
Grazie

**Comment by gbuemi** [comment]
Buongiorno @MichelaGarzoni,
grazie per la segnalazione provvederemo a inserire la documentazione aggiornata che preveda la gestione del rifiuto.

Rispondiamo per punti alle domande:

1. invocando il servizio /notifiche/getNotificheByEvento/{version} viene restituito il campo idStatoRifiuto (decodifica 112_dec_stato_rifiuto) tramite il quale è possibile verificare lo stato del rifiuto. Stiamo valutando di inserirlo in response al servizio /notifiche/ricerca/{version}
2. il servizio /notifiche/ricerca/{version} restituisce l'evento delle notifiche e non l'evento sorgente, invece il servizio /notifiche/getNotificheByEvento/{version} restituisce le notifiche generate a partire da l'idevento sorgente
3. l'API /rifiuto/validazione/evento/{version} che potete utilizzare per la validazione del provvedimento di rifiuto, prende in input il ModelEvento.yaml e quindi è possibile inviare le stesse informazioni presenti sulla webapp ANSC, vedi documentazione 
https://github.com/italia/ansc/blob/57259c23076a076dc1bd70867e823b96536c12cc/docs/openapi/R016_evento_rifiuto.yaml#L54

Un saluto,
Supporto ANSC
