### ISSUE TITLE
[SC]: [R005] Ricerca intestatario con dati anagrafici non restituisce il risultato

### ISSUE THREAD

**Issue by LucaBonini64** [italia/ansc#1056]
### Ambiente

pre-produzione

### Servizio

R005 - Servizi cooperativi consultazione

### idOperazione

2526871

### idEvento o idAnsc

assente

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Novi Ligure

### Data del test (yyyy-mm-dd)

2024-09-24

### Descrivi il problema

Eseguendo una ricerca su 'https://anscservicepre.anpr.interno.it/services/service/ricerca/consultazione/ansc/intestatario/1' inserendo nei criteri ricerca soggetto i dati anagrafici come da voi indicato non viene restituito nessun errore ma la risposta non contiene nessun individuo: "soggetti": []
La ricerca per codice fiscale invece restituisce la persona con gli stessi dati che abbiamo inserito nel payload di richiesta.

### Come riprodurre il problema

1. Inviare all'url indicato una richiesta come da Payload sotto riportato

### Payload (json)

```JSON
{
	"criteriRicercaSoggetto": {
		"cognome": "MORA",
		"nome": "ROSA",
		"sesso": "F",
		"idComuneNascita": "10617",
		"nomeComuneNascita": "VERBANIA",
		"siglaProvinciaNascita": "VB",
		"codiceStatoNascita": "90",
		"nomeStatoNascita": "ITALIA",
		"datanascita": "1995-12-04"
	},
	"testataRichiesta": {
		"idComune": 6498,
		"idOperazioneComune": "1007",
		"dataOraRichiesta": "2024-09-24T10:09:51.8667035+02:00",
		"nomeApplicativo": "hyperSIC.StatoCivile",
		"versioneApplicativo": "9.23.20.01.1L02",
		"fornitoreApplicativo": "APKAPPA S.r.l."
	}
}
```

**Comment by gbuemi** [comment]
Salve @LucaBonini64,
abbiamo preso in carico la segnalazione.

Un saluto,
Supporto ANSC
