### ISSUE TITLE
[webapp]: Campi obbligatori per caso d'uso 433000 e 434000

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#1057]
### Ambiente

pre-produzione, produzione

### Provenienza segnalazione

Software House

### Riferimenti operatore/comune

Lissone - biadanpad

### Data del test (yyyy-mm-dd)

2024-09-24

### Caso d'uso

433000 e 434000

### Descrivi il problema

In entrambi i casi d'uso vengono richiesti i campi Stato, Provincia, Comune e LocalitàEstera (alcuni dei quali obbligatori) nella sezione "Dati della trascrizione".
Una volta completato l'atto, scaricandolo con il servizio di consultazione evento, si nota che tali campi non sono registrati nell'atto stesso.

Inoltre, nella sezione "Autorità mittente" viene richiesto come obbligatorio il campo "Indirizzo Ente". Ci viene il dubbio che questo dato possa non essere noto. Tale indirizzo non viene nemmeno riportato nella minuta dell'atto. Potreste cortesemente verificare l'effettiva obbligatorietà del dato?

**Comment by rvinzani** [comment]
Prendiamo in carico la sua segnalazione. Le daremo risposta quanto prima

**Comment by gbuemi** [comment]
La segnalazione è stata corretta e appena rilasciata con la versione 1.33.0

**Comment by biadanpad** [comment]
Buonasera, 
abbiamo visto in WebApp che tutta la sezione "Autorità Mittente" è diventata opzionale, ma nel momento in cui se ne specifica uno dei dati, anche tutti gli altri diventano obbligatori.
Il nostro dubbio iniziale era relativo all'obbligatorietà del solo "Indirizzo Ente" dell'"Autorità Mittente", pertanto il nostro dubbio rimane.
Attualmente, nel caso in cui si conosca il "Nome Ente", gli "Estremi Documento" e lo "Stato Ente" ma non l'"Indirizzo Ente", non è possibile inserire nessuno dei dati.

Attendiamo un riscontro.

**Comment by gbuemi** [comment]
Buongiorno @biadanpad ,
la prendiamo in carico, seguiranno aggiornamenti.

Un saluto,
Supporto ANSC

**Comment by asqueglia** [comment]
Buongiorno comunichiamo che con la patch 1.33.3 è stata rilasciata la correttiva.
