### ISSUE TITLE
[SC]: elenco comuni che hanno aderito ad ANSC

### ISSUE THREAD

**Issue by Hdemografici** [italia/ansc#1058]
### Ambiente

pre-produzione

### Servizio

R901 - Servizio di configurazione per il reperibimento delle tabelle di decodifica

### idOperazione

2531514

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

colli al metauro

### Data del test (yyyy-mm-dd)

2024-09-25

### Descrivi il problema

Buongiorno, i comuni dell'elenco ritornato con idDecodifica: 110, vengono aggiunti solo dopo l'utilizzo dei servizi cooperativi  oppure anche con il solo utilizzo della web app?
grazie

**Comment by rvinzani** [comment]
Buongiorno, in ambiente di produzione il servizio restituisce l'elenco dei comuni che hanno inserito la data di dichiarazione di adesione. La modalità di formazione degli atti non influisce. Chiudo la issue. Nel caso fossero necessari ulteriori chiarimenti si prega di riaprire la issue
