### ISSUE TITLE
[SC]: errore in fase di firma atto "USC dell'operazione di firma diverso da chi ha firmato l'attestazione" 

### ISSUE THREAD

**Issue by siscomanpr** [italia/ansc#1059]
### Ambiente

produzione

### Servizio

R007 - Servizi cooperativi firma ufficiale di stato civile

### idOperazione

369731

### Provenienza segnalazione

Comune

### Comune di riferimento e operatore

Serravalle Sesia

### Data del test (yyyy-mm-dd)

25/09/2024

### Descrivi il problema

L'impiegata del comune di Serravalle Sesia stava procedendo con la firma USC di una trascrizione di un matrimonio e riceve l'errore
`400103 - USC dell'operazione di firma diverso da chi ha firmato l'attestazione` (idOperazione: 369731)
In realtà l'operatore che sta firmando l'atto è lo stesso che aveva firmato l'attestazione di conformità pochi minuti prima (con idOperazione 369323).
Potete controllare il motivo di questo errore?

**Comment by gbuemi** [comment]
Buongiorno @siscomanpr,
il problema dovrebbe essere stato risolto, potete per favore far riprovare? Vi invitiamo a chiudere la issue in caso di test concluso con successo.

Un saluto,
Supporto ANSC

**Comment by siscomanpr** [comment]
L'evento ora è stato firmato correttamente, grazie.
