### ISSUE TITLE
[SC]: Upload Allegati - Verbale Pubblicazione: Errore "Tipo Allegato non valido"

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/ansc#1064]
### Ambiente

pre-produzione

### Servizio

R001 - Servizi cooperativi allegati

### idOperazione

2552542

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

FAENZA

### Data del test (yyyy-mm-dd)

2024-10-01

### Descrivi il problema

cdu 321311 - Dichiarazione: Matrimonio con Rito Religioso Cattolico

il caso d'uso non prevede allegati obbligatori, ma ne considera svariati non obbligatori (rif. Matr_007.xlsx)
si tenta di inviare con servizio di upload (R001) il Verbale di Pubblicazione (codice 104 - rif. tabella 9)

la comunicazione va in errore e restituisce il seguente messaggio: "Tipo Allegato non valido"

potete verificare?

grazie
Alessandro ADS

**Comment by gbuemi** [comment]
Buongiorno @AMonopoliADS,
la questione è rientrata, adesso dovreste poter effettuare l'upload del tipo allegato 104.

Un saluto,
Supporto ANSC
