### ISSUE TITLE
[SC]: Annotazione per Rettifica (14630000) - Messaggio "errore interno"

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/ansc#1066]
### Ambiente

produzione

### Servizio

R013 - Servizi cooperativi per la validazione della rettifica

### idOperazione

393060

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Valeggio sul Mincio

### Data del test (yyyy-mm-dd)

2024-10-02

### Descrivi il problema

buongiorno.

si tenta di inviare un'annotazione di rettifica (ws R013) su atto di nascita con idAnsc 2024-9928-193-023089.
il servizio di validazione risponde con un generico "errore interno" che non permette di individuare quale sia il problema.

attendiamo indicazioni sulle cause dell'errore e possibilmente di avere messaggi più chiari anche in casi come questo.

grazie
Alessandro ADS

**Comment by AMonopoliADS** [comment]
come anticipato nella call di questa mattina, ci servirebbe un riscontro su questa issue aperta da circa una settimana, per un problema in ambiente di produzione.

grazie

**Comment by mttfranci** [comment]
Salve @AMonopoliADS ci sembra di capire che l'operazione non sia stat più provata dopo il 2 ottobre.

Visto che c'è stato un nuovo rilascio il 3 ottobre (https://github.com/italia/ansc/releases/tag/v1.33.0) pensate sia possibile riprovare prima di continuare l'indagine?

Grazie in anticipo.

**Comment by AMonopoliADS** [comment]
ciao Matteo.
non avendo trovato riferimenti al problema nel changelog del rilascio non abbiamo pensato che si potesse essere risolto.
per questo abbiamo atteso per riprovare.

comunque, abbiamo fatto adesso una nuova prova e l'errore persiste:
`Informazioni sull'operazione da fornire in caso di assistenza : data:2024-10-09 11:46:54 , idOperazione:410517`

(tra l'altro faccio notare che la richiesta è partita alle 13:46 ed il messaggio di errore riporta l'orario delle 11:46)

**Comment by mttfranci** [comment]
Buonasera.

Abbiamo trovate le trace aggiuntive e stiamo verificando la segnalazione.
Vi facciamo sapere appena possibile.

Saluti

**Comment by mttfranci** [comment]
Buon pomeriggio @AMonopoliADS  potreste riprovare?

Abbiamo rilasciato una fix (anche se ancora non abbiamo pubblicato il changelog).

Saluti

**Comment by AMonopoliADS** [comment]
ho riprovato e la validazione è stata eseguita con successo.
grazie
