### ISSUE TITLE
[SC]: [feature] Annotazione modificativa su atti cartacei (ID 95)

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#1069]
### Ambiente

pre-produzione

### Servizio

R008 - Servizi cooperativi notifiche

### idOperazione

assente

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

ponsacco, anna maraspin

### Descrivi il problema

Buongiorno,
a cosa serve la nuova feature in oggetto? Non c'è nessuna documentazione in merito.
Grazie

**Comment by rvinzani** [comment]
Gent.le Dott.ssa Maraspin, in realtà questo tipo di annotazione ha il solo scopo di tracciare l'operazione in ANSC ma senza nessun riflesso sull'atto e di conseguenza sulle certificazioni dello stesso che devono continuare ad essere gestite localmente dal comune. Spero di averle risposto. Chiudo pertanto la issue. La prego di riaprirla se la spiegazione non fosse esauriente. Saluti
