### ISSUE TITLE
Titolo: [R009] Campi obbligatori non previsti per caso d'uso Matr_007.

### ISSUE THREAD

**Issue by gcuci** [italia/ansc#107]
buonasera,

segnaliamo che il servizio di validazione, per il caso d'uso indicato nel titolo, restituisce degli errori di obbligatorietà, per alcuni campi del Luogo Celebrazione, indicati invece come non obbligatori nel relativo file di mapping:

![image](https://github.com/italia/ansc/assets/128400400/ac478ac7-42c2-4c07-b7d0-e62e43310494)

Per un'esempio di invocazione del servizio in preProduzione, potete considerare l'operazione con id: 1588717

Di seguito la Response restituita:

{
    "testataRisposta": {
        "idComune": 595,
        "idOperazioneComune": "1262",
        "idOperazione": "1588717",
        "idEsito": 1
    },
    "errors": [
        {
            "code": "400003",
            "severity": "E",
            "text": "Il campo evento.datiEventoMatrimonio.luogoCelebrazione.idProvincia nella sezione Luogo Celebrazione è obbligatorio"
        },
        {
            "code": "400003",
            "severity": "E",
            "text": "Il campo evento.datiEventoMatrimonio.luogoCelebrazione.siglaProvincia nella sezione Luogo Celebrazione è obbligatorio"
        },
        {
            "code": "400003",
            "severity": "E",
            "text": "Il campo evento.datiEventoMatrimonio.luogoCelebrazione.idComune nella sezione Luogo Celebrazione è obbligatorio"
        },
        {
            "code": "400003",
            "severity": "E",
            "text": "Il campo evento.datiEventoMatrimonio.luogoCelebrazione.nomeComune nella sezione Luogo Celebrazione è obbligatorio"
        },
        {
            "code": "400003",
            "severity": "E",
            "text": "Il campo evento.datiEventoMatrimonio.luogoCelebrazione.indirizzo nella sezione Luogo Celebrazione è obbligatorio"
        },
        {
            "code": "400003",
            "severity": "E",
            "text": "Il campo evento.datiEventoMatrimonio.luogoCelebrazione.numeroCivico nella sezione Luogo Celebrazione è obbligatorio"
        }
    ]
}

In attesa di un riscontro,

cordiali saluti.

**Comment by rfamiglini** [comment]
Buongiorno,
verifichiamo e le facciamo sapere.
