### ISSUE TITLE
[SC]: Firma USC per Rettifiche - Firma non avvenuta con successo.

### ISSUE THREAD

**Issue by gcuci** [italia/ansc#1070]
### Ambiente

pre-produzione

### Servizio

R007 - Servizi cooperativi firma ufficiale di stato civile

### idOperazione

2572935

### idEvento o idAnsc

3514321

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Bagnacavallo

### Data del test (yyyy-mm-dd)

2024-10-04

### Descrivi il problema

Il servizio di Firma USC (R007), per Annotazioni di Rettifica, che sinora aveva funzionato correttamente, restituisce adesso, sempre un errore di 'Firma non avvenuta con successo'.

**Comment by amusarra** [comment]
Salve @gcuci 
Abbiamo preso in carico la segnalazione.

Cordiali Saluti.
Supporto ANSC.

**Comment by asqueglia** [comment]
Buongiorno comunichiamo che con la patch 1.33.3 è stata rilasciata la correttiva.

**Comment by gcuci** [comment]
Buongiorno,

segnaliamo che da questa mattina stiamo provando ad effettuare delle Firme USC per Annotazioni di Rettifica (servizio R007), ma otteniamo nuovamente la stessa response: 'Firma non avvenuta con successo'. L'ultima invocazione l'abbiamo effettuata alle 15:26 (idOperazione: '2776459', idEvento: '3715208').

In attesa di riscontro,

cordiali saluti.

**Comment by amusarra** [comment]
Salve @gcuci 
Potrebbe eseguire nuovamente un test di firma?
Qualora dovesse andare positivamente la preghiamo di chiudere la issue.

Grazie.
Supporto ANSC.

**Comment by gcuci** [comment]
Perfetto, adesso funziona correttamente (idOperazione: '2781984' e '2781997').

Grazie.
