### ISSUE TITLE
[SC]: anomalia redazione atto di matrimonio (Matr_007)

### ISSUE THREAD

**Issue by antonioluberto** [italia/ansc#1071]
### Ambiente

produzione

### Servizio

R009 - Servizi cooperativi validazione evento

### idOperazione

non dispinibile

### idEvento o idAnsc

2024 -21510 -680 - 058046

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Grottaferrata

### Data del test (yyyy-mm-dd)

24/09/2024

### Descrivi il problema

E' stato creato l'atto di matrimonio 2024 -21510 -680 - 058046 ("Confermato"); ai titolari sono stati attribuiti gli identificativi ANSC:
- 14412803, per lo sposo,
- 14412805, per la sposa.

Quindi è stata eseguita la sottoscrizione da parte dei comparenti (Firmato dal dichiarante) ed è stata firmata la dichiarazione di conformità (Firmato per conformità).
A questo punto, per un non meglio identificabile problema risultava impossibile concludere l'atto con la sottoscrizione digitale da parte dell'usc su applicazione locale; l'usc ha quindi provato ad eseguire la sottoscrizione digitale medesima su WebApp ma a quel punto l'atto è letteralmente "sparito" dalla WebApp.
Inoltre, se adesso proviamo a creare ex-novo l'atto con i medesimi titolari otteniamo l'errore 
_400317 : Id dell'intestatario inesistente_.
Come dobbiamo procedere a questo punto

**Comment by mttfranci** [comment]
Buongiorno @antonioluberto a noi risulta che l'atto id evento 21510 sia stato cancellato (Pulsante elimina dalla web app di ANSC) il 6 Agosto 2024.

Riguardo al messaggio : 
`400317 : Id dell'intestatario inesistente.`

Sapreste indicarci l'id operazione?

Grazie in anticipo.

**Comment by antonioluberto** [comment]
{"idComune":4559,"idOperazioneComune":"c4c1826a-aac1-4a46-b8f9-0435689becdd","idOperazione":"404263","idEsito":1},"errors":[{"code":"400317","severity":"E","text":"Id dell'intestatario inesistente"}],"infos":[{"code":"110527","severity":"I","text":"Informazioni sull'operazione da fornire in caso di assistenza : data:2024-10-07 10:08:00 , idOperazione:404263"}],"warnings":[{"code":"400003","severity":"W","text":"Attenzione! La data formazione, se impostata, deve essere la data odierna"},{"code":"400003","severity":"W","text":"Attenzione! La data formazione, se impostata, deve essere la data odierna"}]}

**Comment by mttfranci** [comment]
Salve @antonioluberto quando l'evento viene eliminato (come in questo caso da web app) l'applicazione prova a cancellare anche gli intestatari (se non hanno altri eventi collegati) come in questo caso.

Pertanto gli id degli intestatari dell'atto cancellato (21510), non sono più utilizzabili in questo caso.

Saluti

Assistenza ANSC
