### ISSUE TITLE
[webapp]: Delucidazione funzionamento ricezione notifica 

### ISSUE THREAD

**Issue by Hdemografici** [italia/ansc#1073]
### Ambiente

pre-produzione

### Provenienza segnalazione

Software House

### Riferimenti operatore/comune

-

### Data del test (yyyy-mm-dd)

09/10/2024

### Caso d'uso

11212002 / 2102

### Descrivi il problema

buongiorno,
è stato inserito in WA, come Comune di Cartoceto, atto di nascita 2024-3514867-3-041010 (GALLI GIULIO)
caso uso 11212002
ID ANSC 3224353

successivamente, sempre tramite WA e come Comune di Colli al Metauro, è stato inserito atto di morte 2024-3514870-4-041069, agganciando la stessa posizione creata con l'atto di nascita precedentemente citato
caso uso 2102

dopo aver chiuso l'atto di morte si nota che nella sezione "notifiche" della WA del Comune di Colli al Metauro viene proposta la notifica dell'annotazione automatica di morte (2024-3514872-00000-041069) pronta per essere gestita

in questa circostanza si chiede: considerato che il detentore dell'atto di nascita su cui dovrebbe essere apposta l'annotazione di morte è il Comune di Cartoceto, la notifica relativa all'apposizione dell'annotazione non avrebbe dovuto essere proposta nella WA di Cartoceto invece che Colli al Metauro?

grazie per l'attenzione

**Comment by asqueglia** [comment]
Buongiorno, il comune di CARTOCETO non risulta un comune che ha aderito al sistema; questo è il motivo per cui non vengono inviate le notifiche. In produzione c'è un controllo bloccante che impedisce ad un comune non aderente di utilizzare il sistema ANSC. Tale controllo non è presente in ambiente di test per consentire a voi comuni e alle software house, tutti i test incrociati possibili. Per capire se un comune ha aderito o meno è possibile utilizzare il servizio R901 /config/decodifica/data_adesione/{version}

Abbiamo provveduto a censire il comune di CARTOCETO tra i comuni aderenti al sistema in modo da consentirvi di riprovare il test da capo.
Chiudiamo pertanto la issue. In caso di ulteriori problemi preghiamo di aprirne una dedicata.
