### ISSUE TITLE
[SC]: R008 - Consultazione notifiche: non vengono restituiti in response i datiPaginazione

### ISSUE THREAD

**Issue by davidePanettieri** [italia/ansc#1074]
### Ambiente

pre-produzione

### Servizio

R008 - Servizi cooperativi notifiche

### idOperazione

2589093

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Comune di Milano

### Data del test (yyyy-mm-dd)

2024-10-09

### Descrivi il problema

Buongiorno, stiamo riscontrando il seguente problema sul servizio R008 - Consultazione notifiche: non vengono restituiti in response i datiPaginazione.
Allego request e response della chiamata al servizio:

**URL**:  https://anscservicepre.anpr.interno.it/services/service/notifiche/notifiche/ricerca/1

**Request:**

`{
    "testataRichiesta": {
        "idComune": 5646,
        "idOperazioneComune": "APP2022032210000",
        "dataOraRichiesta": "2024-10-09",
        "nomeApplicativo": "SIDe",
        "versioneApplicativo": "1.0.0",
        "fornitoreApplicativo": "SistemiInformativi"
    },
    "criteriRicercaNotifiche": {
        "dataInizio": null,
        "dataFine": null,
        "idAnsc": "2023-1215356-855-015146",
        "idTipoEvento": null,
        "idTipoContenuto": null,
        "idStatoFlussoNotifiche": null,
        "idGenereNotifiche": null,
        "soggettoRicerca": null
    }
}`

**Response:**

`{
    "testataRisposta": {
        "idComune": 5646,
        "idOperazioneComune": "APP2022032210000",
        "idOperazione": "2589093",
        "idEsito": 0
    },
    "notifiche": [
        {
            "id": "2243215",
            "idAnsc": "2023-1215356-855-015146",
            "idComuneFormazione": "5646",
            "idComuneCompetente": "5646",
            "idStatoFlussoNotifiche": "2",
            "idGenereNotifiche": "2",
            "idSoggettoRif": "2243209",
            "dataInizioValidita": "2023-12-06T11:00:00Z",
            "dataFineValidita": "9999-12-31T11:00:00Z",
            "descrizione": "Decesso in caso di morte violenta",
            "idcanalenotifica": 0
        }
    ]
}`

**Comment by amusarra** [comment]
Salve @davidePanettieri 
Abbiamo preso in carico la sua segnalazione.

Cordiali Saluti.
Supporto ANSC.

**Comment by davidePanettieri** [comment]
Buonasera, ci sono aggiornamenti per questa segnalazione?

**Comment by asqueglia** [comment]
Buongiorno comunichiamo che con la patch 1.33.3 è stata rilasciata la correttiva.
