### ISSUE TITLE
[SC]: Servizio generazione certificati plurilingue internazionali (R019) irraggiungibile

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#1075]
### Ambiente

pre-produzione

### Servizio

R009 - Servizi cooperativi validazione evento

### idOperazione

-

### idEvento o idAnsc

-

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Lissone - biadanpad

### Data del test (yyyy-mm-dd)

2024-10-10

### Descrivi il problema

Il servizio di generazione dei certificati internazionali risulta irrangiungibile.

Non è inoltre possibile selezionare tale in fase di inserimento di una nuova issue:
![image](https://github.com/user-attachments/assets/bb05a900-75b8-4ca9-a4fb-e68be5852ce4)

### Payload (json)

```JSON
REQUEST:
{
    "idEvento": "3514792",
    "idTipoCertificato": "2",
    "stato": "ITALIA",
    "certificatoMatrimonio": {
        "marito": {
            "soggetto": {}
        },
        "moglie": {
            "soggetto": {}
        }
    },
    "testataRichiesta": {
        "idComune": 5000,
        "idOperazioneComune": "9614",
        "dataOraRichiesta": "2024-10-10T08:31:38.885+02:00",
        "nomeApplicativo": "urbi",
        "versioneApplicativo": "1.4.0",
        "fornitoreApplicativo": "padigitale"
    }
}

RESPONSE:
Service EndPoint: https://anscservicepre.anpr.interno.it/services/service/val/certificato-internazionale/create/1
HttpResponse Code: 404
HttpResponse Body:
```

**Comment by gbuemi** [comment]
Buongiorno @biadanpad ,
vi comunichiamo che purtroppo è presente un errore sullo yaml dell'R019, nella sezione "servers" in cui sono stati dichiarati gli url di produzione e preproduzione. Vi invitiamo adesso a configurare gli url così come dichiarato qui https://github.com/italia/ansc/blob/fda1e72fbe07a266b978bec1488a9effbd0f80dc/docs/openapi/R002_certificazione.yaml#L5 

Vi confermiamo invece che i paths dichiarati sull'R019 sono corretti.

Quindi, nel caso da voi indicato l'endpoint di preproduzione completo è: **https://anscservicepre.anpr.interno.it/services/service/certificazione/certificato-internazionale/create/1** 

Provvederemo ad aggiornare la documentazione e ad aggiungere l'R019 come selezione in fase di apertura di una nuova issue.

Grazie per la segnalazione.

Un saluto,
Supporto ANSC
