### ISSUE TITLE
[SC]: usecase 350000	Dichiarazione di riconciliazione	Matr_Riconc_001

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#1076]
### Ambiente

pre-produzione

### Servizio

R001 - Servizi cooperativi allegati, R009 - Servizi cooperativi validazione evento

### idOperazione

assente

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

venezia, anna maraspin

### Descrivi il problema

Buongiorno,
il Comune di Venezia ha forti dubbi sull'obbligatorietà relativamente :
1) ai dati relativi all'atto di matrimonio
![image](https://github.com/user-attachments/assets/c5e26715-ba3b-42d5-a416-a036cb9b4814)
2) ad allegare la copia dell'atto di matrimonio 

Inoltre secondo loro, oltre alla firma dei due dichiaranti, dovrebbe esser proposta anche quella dell'ufficiale dello stato civile.

**Comment by asqueglia** [comment]
Buon pomeriggio verifichiamo e vi facciamo sapere

**Comment by annamaraspin** [comment]
Grazie mille,
ho riferito al Comune e non ha nulla da obiettare.
Chiudo il ticket
