### ISSUE TITLE
[webapp]: Non permette di indicare il comune di nascita valido alla data

### ISSUE THREAD

**Issue by migmar68** [italia/ansc#1078]
### Ambiente

pre-produzione

### Provenienza segnalazione

Software House

### Riferimenti operatore/comune

Migliori

### Descrivi il problema

Nel simulare un atto di matrimonio, volevo indicare un Sindaco nato a Rimini nel 1985. 
Rimini diventa provincia nel 1992, mentre prima faceva parte della provincia di Forlì.

Usando la web app vedo questo:
![image](https://github.com/user-attachments/assets/d6815c86-d432-40de-82de-63c278e83f76)

- mancano le provincie valide alla data: manca FORLì che esisteva
- è presente "FORLI'-CESENA" e anche "RIMINI" che non esistevano
- se scelgo una di queste province inesistenti mi mostra i comuni attuali
- se scelgo "FORLI'-CESENA" non vedo RIMINI tra i comuni
- la simulazione è in un atto di matrimonio, ma il problema sembra presente in tutti gli atti
- quello di RIMINI è solo un esempio, la segnalazione vale per tutti i "comuni storici", che devono essere indicati come luogo di nascita

**Comment by asqueglia** [comment]
Buon pomeriggio verifichiamo e le facciamo sapere

**Comment by asqueglia** [comment]
Buongiorno comunichiamo che con la patch 1.33.3 è stata rilasciata la correttiva.
