### ISSUE TITLE
[SC]: Errore servizio R019  - "Dati in ingresso della paginazione non completi"

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#1080]
### Ambiente

pre-produzione

### Servizio

R019 - Servizi cooperativi per la creazione dei certificati internazionali plurilingue per lo stato civile

### idOperazione

2602726

### idEvento o idAnsc

3513428

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Lissone - biadanpad

### Data del test (yyyy-mm-dd)

2024-10-11

### Descrivi il problema

Chiamando il servizio R019 per ottenere l'elenco delle annotazioni, ritorna l'errore in oggetto

### Payload (json)

```JSON
REQUEST:
{
  "idEvento": "3513428",
  "testataRichiesta": {
    "idComune": 5000,
    "idOperazioneComune": "0",
    "dataOraRichiesta": "2024-10-11T10:16:23.032+02:00",
    "nomeApplicativo": "urbi",
    "versioneApplicativo": "1.4.0",
    "fornitoreApplicativo": "padigitale"
  }
}

RESPONSE:
{
    "testataRisposta": {
        "idComune": 5000,
        "idOperazioneComune": "0",
        "idOperazione": "2602726",
        "idEsito": 999
    },
    "errors": [{
            "code": "400004",
            "severity": "E",
            "text": "Dati in ingresso della paginazione non completi"
        }
    ],
    "infos": [{
            "code": "110527",
            "severity": "I",
            "text": "Informazioni sull'operazione da fornire in caso di assistenza : data:2024-10-11 08:16:25 , idOperazione:2602726"
        }
    ],
    "listaAnnotazioni": null
}
```

**Comment by gbuemi** [comment]
Buongiorno @biadanpad,
abbiamo preso in carico la segnalazione.

Un saluto,
Supporto ANSC

**Comment by gbuemi** [comment]
Buongiorno @biadanpad,
vi invitiamo ad aggiungere nel payload la struttura datiPaginazione, anche vuota in questo caso specifico, così come definita a seguire https://github.com/italia/ansc/blob/ca0c79f0fe53dc1dc764955c0e7e717c71720dfe/docs/openapi/base_servizi.yaml#L76 

In questo caso sarebbe quindi:
`{
  "datiPaginazione": {
  },
  "idEvento": "3513428",
  "testataRichiesta": {
    "idComune": 5000,
    "idOperazioneComune": "0",
    "dataOraRichiesta": "2024-10-11T10:16:23.032+02:00",
    "nomeApplicativo": "urbi",
    "versioneApplicativo": "1.4.0",
    "fornitoreApplicativo": "padigitale"
  }
}`

Un saluto,
Supporto ANSC
