### ISSUE TITLE
[SC]: Firma USC Annotazioni (R007) - Errore "Firma non avvenuta con successo"

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/ansc#1082]
### Ambiente

pre-produzione

### Servizio

R007 - Servizi cooperativi firma ufficiale di stato civile

### idOperazione

2607213, 2607212

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

FAENZA

### Data del test (yyyy-mm-dd)

2024-10-11

### Descrivi il problema

i tentativi di firma di annotazione dell'ultima mezz'ora ritornano tutti l'errore "Firma non avvenuta con successo"

è problema temporaneo forse dovuto al recente rilascio o c'è qualche problema che non capiamo nell'invio del servizio?
grazie

Alessandro ADS

**Comment by asqueglia** [comment]
Buongiorno verifichiamo e le facciamo sapere

**Comment by asqueglia** [comment]
Buongiorno abbiamo verificato dal payload da voi inviato che mancano i parametri di firma, da ciò l'errore ottenuto.

Di seguito il payload da voi inviato

{"testataRichiesta":{"idComune":"3743","idOperazioneComune":2024006372,"dataOraRichiesta":"2024-10-11T16:46:08","nomeApplicativo":"DE4GSDZK","versioneApplicativo":"V4.5.7.8-SNAPSHOT","fornitoreApplicativo":"ADS"},"firmaInput":{"idEvento":3515447}}


di seguito un esempio di payload funzionante

 "firmaInput": {
        "idEvento": "3515447",
        "parametriFirma": {
            "idTipoFirma": "1",
            "idModalitaInput": "2",
            "inputFirma1": "VGVzdFVzZXI=",
            "inputFirma2": "VGVzdFBhc3N3b3Jk",
            "inputFirma3": "VGVzdE90cA=="
        }

Si consiglia di fare riferimento alle specifiche del servizio di firma R007 riportate in documentazione.
Chiudiamo pertanto la issue. In caso di ulteriori problematiche si prega di aprirne una dedicata.

**Comment by AMonopoliADS** [comment]
ok. grazie Angela, 

verifichiamo come mai non siano partite le credenziali.
onestamente non ci avevo guardato perchè il servizio è già utilizzato con successo da tempo.

insisto però sul fatto che il messaggio "firma non avvenuta con successo" non aiuta per nulla a capire quale sia il problema.
in un caso come questo, non è proprio possibile che il servizio risponda con un messaggio che faccia capire che la richiesta non contiene le credenziali utili per la firma?

grazie
