### ISSUE TITLE
[webapp]: problemi di accesso alla webapp

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#1083]
### Ambiente

pre-produzione

### Provenienza segnalazione

Software House

### Riferimenti operatore/comune

biadanpad

### Data del test (yyyy-mm-dd)

2024-10-14

### Descrivi il problema

Buongiorno, 
questa mattina non riesco ad accedere alla webapp di pre-produzione. Una volta selezionato il certificato personale compare l'errore di seguito anche dopo aver pulito icoockie del browser e utilizzando una finestra di navigazione in incognito:

![image](https://github.com/user-attachments/assets/272cb14e-6c16-45f5-98cd-08bdadc60704)

![image](https://github.com/user-attachments/assets/929234b4-ceca-4687-b1c2-ab4c5c688095)

**Comment by asqueglia** [comment]
Buongiorno verifichiamo e le facciamo sapere

**Comment by asqueglia** [comment]
Buongiorno, l'accesso con spid funziona. Intanto potete utilizzare spid per accedere. Stiamo verificando l'accesso tramite certificati.

**Comment by biadanpad** [comment]
Riprovato. Funziona
