### ISSUE TITLE
[SC]: Annotazione - Validazione: msg. "errore interno" / Firma USC: msg. "firma non avvenuta con successo"

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/ansc#1085]
### Ambiente

pre-produzione

### Servizio

R007 - Servizi cooperativi firma ufficiale di stato civile, R013 - Servizi cooperativi per la validazione della rettifica

### idOperazione

2612698, 2612705

### idEvento o idAnsc

2024-3515541-289-039010

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

FAENZA

### Data del test (yyyy-mm-dd)

2024-10-14

### Descrivi il problema

risolta l'anomalia di cui alla issue #1082 , il servizio continua a restituire l'errore "Firma non avvenuta con successo" (rif. idOperazioneAnsc 2612705 - idAttoAnsc 2024-3515541-289-039010)

abbiamo provato anche a ri-validare la comunicazione con idVersione 100016, ottenendo invece un generico "errore interno" (rif. idOperzioneAnsc 2612698 - idAttoAnsc 2024-3515541-289-039010, validato con successo questa mattina)

abbiamo anche provato a creare una nuova annotazione da zero (rif. idOperazioneAnsc 2612677), ma il servizio restituisce sempre "errore interno"
qualcosa di similare si verificava in produzione - rif. issue #1066 - ed è stato risolto da voi con un rilascio
è possibile che si verifichi la stessa anomalia in pre-produzione?

potete aiutarci a capire?
grazie
Alessandro ADS

**Comment by asqueglia** [comment]
Buon pomeriggio, verifichiamo e le facciamo sapere
