### ISSUE TITLE
[SC]: I dati del soggetto intestatario non sono conformi ai dati anagrafici registrati

### ISSUE THREAD

**Issue by Hdemografici** [italia/ansc#1086]
### Ambiente

pre-produzione

### Servizio

R009 - Servizi cooperativi validazione evento

### idOperazione

2614143

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Colli al Metauro

### Data del test (yyyy-mm-dd)

14/10/2024

### Descrivi il problema

Buon pomeriggio,
caso uso 411111 (Unione civile nella casa comunale)
inviando servizio R009 in riferimento ad atto relativo a cittadini con id ANSC 3228570 e 3119415
viene restituito il seguente errore:

"Attenzione! I dati del soggetto intestatario con (idANPR,idANSC)=(151941757,3228570) inseriti non sono conformi ai dati anagrafici registrati"

(si precisa che in precedenza era stato provato altro atto relativo a stessi cittadini - id operazione 2614011)

si chiede una delucidazione sulla possibile causa dell'errore sopra riportato

grazie per l'attenzione

**Comment by gbuemi** [comment]
Buongiorno @Hdemografici,
vi comunichiamo che l'errore restituito è coerente con le operazioni effettuate.

Nella seconda validazione sono stati inoltrati (idANPR,idANSC)=(151941757,3228570) non coerenti, in quanto l'idanprsoggetto 151941757 fa riferimento ad un altro idanscsoggetto 3226588 (soggetto con un secondo nome) sul quale è stato registrato un atto giorni prima con idAnsc 2024-3515246-7-041010. 

Un saluto,
Supporto ANSC
