### ISSUE TITLE
[SC]: gestione annotazioni

### ISSUE THREAD

**Issue by MichelaGarzoni** [italia/ansc#1090]
### Ambiente

pre-produzione

### Servizio

R008 - Servizi cooperativi notifiche

### idOperazione

assente

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Duino - Garzoni

### Data del test (yyyy-mm-dd)

2024-10-17

### Descrivi il problema

Abbiamo inserito sul comune di Duino un atto di Morte per una persona residente a Tarcento e nata a Udine (presente atto originale di Nascita). Tutti e tre i comuni sono in ANSC in pre-produzione. 
Risultato del test:
- Duino riceve l'annotazione automatica di morte (che andrebbe al comune dove c'è l'atto originale di nascita (Udine)) da inviare via pec: " ([DUINO AURISINA-DEVIN NABREŽINA - Annotazione automatica id 2024-3516596-00000-032001 ( da inviare via PEC )]
17 ottobre 2024 - AUGUSTO BAGNOLI - 2024-3516596-00000-032001 "
- Tarcento riceve l'atto di morte: " id_Ansc: 2024-3516595-148-032001 "
- Udine non riceve nulla
Come mai Duino riceve l'annotazione, che dovrebbe andare a Udine, e Tarcento riceve l'atto quando dovrebbe ricevere solo la notifica anagrafica?
In questo modo a Udine l'atto di nascita rimane incompleto in modo inconsapevole, in quanto non riceve alcuna notifica.

**Comment by asqueglia** [comment]
Buongiorno, quando l'atto primario è cartaceo la gestione dell'annotazione è extra flusso tramite PEC e la notifica viene inviata al comune di formazione dell'atto secondario (nel vostro esempio il comune di registrazione dell'atto di morte); questo il motivo per cui Udine non ha ricevuto alcuna notifica. Gli atti cartacei sono gestiti al di fuori del sistema con le attuali modalità operative. Chiudiamo pertanto la issue, in caso di ulteriori dubbi si prega di aprirne una altra dedicata
