### ISSUE TITLE
[SC]: Indicazione errata idNazionalita (cittadinanza)

### ISSUE THREAD

**Issue by migmar68** [italia/ansc#1092]
### Ambiente

produzione

### Servizio

R009 - Servizi cooperativi validazione evento

### idOperazione

assente

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Migliori

### Descrivi il problema

Buongiorno
Abbiamo rilevato un refuso dovuto a errata interpretazione, che abbiamo però anche in produzione a Rosignano Marittimo.
Nel compilare i campi
"idnazionalita"
"nazionalita"
del deceduto, testimone, genitore, ecc... lo sviluppatore nel caso di cittadinanza italiana ha passato erroneamente il codice istat. Per esempio nell'ambiente di test ("idAnsc":"2024-3516429-264-099031"), passa per questi due campi i seguenti valori:
"idNazionalita":"**100**"
"nazionalita":"**ITALIA**"

Viene passato erroneamente il codice istat, appunto valore 100, mentre nella tabella stati di ANPR, la riga Italia prevede come ID = **90**.
La riga con ID = **100**, corrisponde al **LIBANO**.

Quindi vengono passati due valori incongruenti, di cui non ce ne siamo accorti prima, perchè la copia integrale è corretta (riporta ITALIA). Per la segnalazione sul comportamento ANSC apro issue separata #1093 .

In merito al comportamento del servizio cooperativo osservo per vostre valutazioni:
- non c'è controllo lato server tra la corrispondenza dei 2 campi che dobbiamo valorizzare
- la tabella pubblica di ANPR degli stati esteri, riporta comunque solo la colonna Denominazione, non la colonna descrizione Cittadinanza. Quindi nella tabella pubblica abbiamo la riga con LIBANO, ma non c'è nessuna colonna nel file con valore **LIBANESE**.
- in conseguenza di questa considerazione, abbiamo corretto per passare nei prossimi atti 100-ITALIA nei 2 campi, ma non comunicheremo 100-ITALIANA

Abbiamo provato con successo in ambiente di test sull'id atto 3414797, a correggere il campo "Nazionalita" tramite la web application - correzione evento con nota tecnica.
Provvediamo a informare il comune.

**Comment by gbuemi** [comment]
Buon pomeriggio,
va bene al momento inviare la denominazione presente sulla tabella pubblica di ANPR degli stati esteri e ITALIA invece di ITALIANA. Però con id 90 e non il codice istat 100, come da voi indicato.

Per la congruenza idNazionalita e nazionalita valuteremo se inserire il controllo, attualmente è presente per lo stato di nascita.
 
Un saluto,
Supporto ANSC
