### ISSUE TITLE
[webapp]: Incongruenza tra copia integrale e visualizza evento a video (Nazionalità)

### ISSUE THREAD

**Issue by migmar68** [italia/ansc#1093]
### Ambiente

produzione

### Provenienza segnalazione

Software House

### Riferimenti operatore/comune

Maggioli - Migliori

### Descrivi il problema

Buongiorno
In conseguenza della issue precedente #1092  , segnalo il comportamento anomalo di ANSC che ci ha tratto in inganno.
Come indicato abbiamo erroneamente passato via servizi cooperativi, il valore dell'ID cittadinanza, indicando per italiana:
"idNazionalita":"100"
"nazionalita":"ITALIA"

Il valore corretto di ID sarebbe 90, mentre 100 corrisponde a LIBANO.

Ora dai nostri test, quando viene richiesta la copia integrale da ANSC, viene stampato il valore del campo NAZIONALITA, per cui l'operatore nella situazione descritta legge:
CITTADINANZA **ITALIA**
e ovviamente non si accorge della incongruenza.

Viceversa se vado a video, a interrogare l'atto, sembra che venga usato il campo ID e decodificato perchè si legge :
CITTADINANZA **LIBANESE**

C'è quindi una differenza di comportamento pensiamo da sanare.

**Comment by gbuemi** [comment]
Buon pomeriggio,
i pdf sono basati sul valore testuale la webapp interpreta invece l'identificativo. 
Per sanare la problematica vi invitiamo ad agire tramite nota tecnica, consultando tutti gli atti di morte registrati da gestionale che ci sembrano avere tutti id nazionalità errata.

Un saluto,
Supporto ANSC
