### ISSUE TITLE
[SC]: Allegati fermi in stato '2' (In corso di verifica).

### ISSUE THREAD

**Issue by gcuci** [italia/ansc#1097]
### Ambiente

pre-produzione

### Servizio

R001 - Servizi cooperativi allegati

### idOperazione

2635763

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Bagnacavallo

### Data del test (yyyy-mm-dd)

2024-10-17

### Descrivi il problema

Da qualche ora, il servizio di verifica dello stato di un allegato, già inviato correttamente con il servizio di 'upload', restituisce costantemente lo stato '2' (In corso di verifica), a successive invocazioni dello stesso.

Il comportamento si sta verificando con tutti gli allegati che stiamo provando ad inviare.

**Comment by gbuemi** [comment]
Buongiorno @gcuci,
vediamo che ci sono stati degli errori temporanei rientrati nel pomeriggio. Non ci risultano problematiche al momento e l'allegato con id 3231773 risulta correttamente inserito. Chiudiamo la issue.

Un saluto,
Supporto ANSC
