### ISSUE TITLE
[SC]: Mancanza dati in risposta consultazione ansc intestatario

### ISSUE THREAD

**Issue by LucaBonini64** [italia/ansc#1098]
### Ambiente

pre-produzione

### Servizio

R005 - Servizi cooperativi consultazione

### idOperazione

2636999

### idEvento o idAnsc

assente

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Novi Ligure

### Data del test (yyyy-mm-dd)

2024-10-17

### Descrivi il problema

Eseguendo una interrogazione del servizio ricerca/consultazione/ansc/intestatario, il modelSoggettoInt risulta mancante dei campi idNazionalita e nazionalita previsti nello yaml

### Come riprodurre il problema

1. Eseguire una ricerca per una persona presente in ANPR con il servizio ricerca/consultazione/ansc/intestatario
2. Si allega il payload della risposta senza i campi attesi

### Payload (json)

```JSON
{
	"testataRisposta": {
		"idComune": 6498,
		"idOperazioneComune": "1457",
		"idOperazione": "2636999",
		"idEsito": 0
	},
	"datiPaginazione": {
		"numPagina": 1,
		"numRecordPagina": 30,
		"numRecordTotali": 0
	},
	"infos": [
		{
			"code": "110527",
			"severity": "I",
			"text": "Informazioni sull'operazione da fornire in caso di assistenza : data:2024-10-17 14:44:55 , idOperazione:2636999"
		}
	],
	"soggetti": [
		{
			"id": null,
			"cognome": "****",
			"nome": "****",
			"sesso": "F",
			"datains": null,
			"dataultimoagg": null,
			"codiceFiscale": ""****",
			"idComuneNascita": 10617,
			"idStatoNascita": "90",
			"idComuneResidenza": 1759,
			"nomeStatoNascita": "ITALIA",
			"idProvinciaNascita": 103,
			"nomeComuneNascita": "VERBANIA",
			"idProvinciaResidenza": 103,
			"siglaProvinciaNascita": "VB",
			"idANPR": "****",
			"dataNascita": "****",
			"idStatoResidenza": "90"
		}
	]
}
```

**Comment by gbuemi** [comment]
Buongiorno @LucaBonini64,
al prossimo rilascio la questione verrà risolta.

Un saluto,
Supporto ANSC

**Comment by asqueglia** [comment]
Con il rilascio della versione 1.34.0 la segnalazione è stata risolta
