### ISSUE TITLE
Richiesta di implementazione alla documentazione (Mapping e Changelog)

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#11]
Vi riporto il ticket aperto in Teams a cui non ho mai ricevuto una risposta (vedi parti evidenziate nell'immagine)

Ho notato che nel mapping del singolo uso sono indicati dei campi obbligatori ed altri no. 
Persino il testo dell'atto nel mapping compare in certe casistiche ed in altre no, ed è un campo sempre obbligatorio sempre e per tutti i registri. 
Idem per il modello Event ad esempio: nel tracciato ci sono tantissimi campi ma nel mapping sempre i soliti quattro. Diventa difficile lavorare così.
Anche nel changelog ho notato che mancano tantissime variazioni (già aperto un ticket ad hoc) ed ogni volta, per scrupolo, si rivede tutto da capo a piedi. Capirete che questo porta via tantissimo tempo e non ci aiuta nell'andare avanti con il lavoro ancora non fatto.

![Cattura_doc](https://user-images.githubusercontent.com/127182190/223435506-39e7d827-40b2-46e0-85fe-2c446f1433a2.PNG)

**Comment by mttfranci** [comment]
Salve.

Grazie alla migrazione alla piattaforma github, il dettaglio delle modifiche si può ottenere con un git diff, ad esempio sul singolo file CSV. Questo è una delle motivazioni per cui abbiamo migrato qui la documentazione. Stiamo comunque valutando la produzione di ulteriore documentazione di supporto

![image](https://user-images.githubusercontent.com/29305782/223353215-eb05a53f-949e-461f-96de-7fe8d9347998.png)

Inoltre se credete, stavamo valudando di lasciare nella documentazione solo la versione CSV, per cui la verifica delle differenze è più agevole trattandosi di un formato di testo.
Pensate sia auspicabile?

Saluti

Assistenza ANSC

**Comment by annamaraspin** [comment]
Ok per compare le tabelle di decodifica anche se ogni volta bisogna fare il compare su tutte le tabelle ( e non sono poche) . 
Mi pareva più veloce menzionare nel changelog le modifiche effettuate (o almeno menzionare di riguardare solo la tabella xy e non tutte ad esempio).
Per la parte di mapping e tracciato_evento che vi ho chiesto implementazioni è impossibile la vostra soluzione perché non porterebbe a nessun risultato. Deve essere implementato il mapping indicando almeno tutti i campi obbligatori per quell'uso prevista nel tracciato_evento.

**Comment by mttfranci** [comment]
Cercheremo di fare il possibile per rendere più agevole il recepimento delle modifiche. Intanto mi permetto di segnalare che con il rilascio della versione 1.5.0 è stato reso disponibile il servizio di configurazione delle decodifiche (analogamente a quanto già avveniva in ANPR e come richiesto in alcuni degli incontri tenuti in questi mesi) : 

https://github.com/italia/ansc/blob/main/docs/openapi/R901_config_decodifica.yaml

Tale servizio permette di accedere in modo applicativo all'elenco e al dettaglio delle tabelle di decodifiche.

Siamo a disposizione per ogni ulteriore chiarimento.

Saluti

Assistenza ANSC
