### ISSUE TITLE
[R002] Certificazioni: Errore gestione tipologia estratto

### ISSUE THREAD

**Issue by antonioluberto** [italia/ansc#110]
Richiedendo da servizio l'emissione dell'estratto con indicazione
IdTipoCertificato = 2 (estratto per riassunto)
otteniamo in risposta l'estratto integrale.

Richiedendo da servizio l'emissione dell'estratto con indicazione
IdTipoCertificato = 3 (estratto integrale)
otteniamo in risposta l'estratto per riassunto.

**Comment by amusarra** [comment]
Salve @antonioluberto potrebbe fornire l'idOperazione o eventualemte il payload utilizzanto?

Grazie.
Supporto ANSC.

**Comment by antonioluberto** [comment]
Il problema è risolto con il rilascio di ieri sera.

**Comment by amusarra** [comment]
@antonioluberto molto bene. Procedo allora con la chiusura della issue.

Grazie.
Supporto ANSC
