### ISSUE TITLE
[SC]: Validazione annotazione di rettifica per errore materiale - Errore Interno

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#1101]
### Ambiente

produzione

### Servizio

R013 - Servizi cooperativi per la validazione della rettifica

### idOperazione

425052

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Lissone - biadanpad

### Data del test (yyyy-mm-dd)

2024-10-17

### Descrivi il problema

Tentando di validare un'annotazione di rettifica per errore materiale relativamente all'atto con id 2024-31025-56-108028 si riceve l'errore in oggetto

**Comment by amusarra** [comment]
Salve @biadanpad 
Abbiamo preso in carico la segnalazione.

Cordiali Saluti.
Supporto ANSC.

**Comment by amusarra** [comment]
Salve @biadanpad 
Dai nostri sistemi di tracciamento risulta che la richiesta è stata eseguita il 2024-10-16T15:33:45 e non il 17/10 come indicato sulla issue. 

Questa problematica dovrebbe essere stata risolta con il rilascio della release [v1.33.3](https://github.com/italia/ansc/releases/tag/v1.33.3).

Vi invitiamo a fare nuovamente la risottomissione al fine di verificare la risoluzione. Nel caso fosse risolto, vi preghiamo di chiedere la issue.

Cordiali Saluti.
Supporto ANSC.

**Comment by biadanpad** [comment]
Il comune mi ha appena detto che il problema persiste

**Comment by biadanpad** [comment]
Buongiorno, 
dal comune mi hanno detto che il problema è risolto.

Adesso però hanno ricevuto un "Errore interno" in fase di firma dell'USC. idOperazione: 429122

**Comment by amusarra** [comment]
> Buongiorno, dal comune mi hanno detto che il problema è risolto.
> 
> Adesso però hanno ricevuto un "Errore interno" in fase di firma dell'USC. idOperazione: 429122

Adesso verificheremo.

Grazie.
Supporto ANSC.

**Comment by amusarra** [comment]
Salve @biadanpad 
Potrebbe chiedere al comune di riprovare? Potrebbe essere un problema temporaneo sul servizio di firma.

Grazie.
Supporto ANSC.

**Comment by amusarra** [comment]
Salve @biadanpad
Chiudo la issue non avevo ricevuto conferma. Nel caso riapra la stessa.

Cordiali Saluti.
Supporto ANSC.

**Comment by biadanpad** [comment]
Buongiorno, 
non ho ricevuto un feedback su questo caso specifico, ma dal comune mi segnalano lo stesso problema di firma dell'USC su un'altra annotazione dello stesso genere (rettifica per errore materiale). idOperazione: 437294

**Comment by biadanpad** [comment]
Buongiorno,
non ho ricevuto un feedback su questo caso specifico, ma dal comune mi segnalano lo stesso problema di firma dell'USC su un'altra annotazione dello stesso genere (rettifica per errore materiale). idOperazione: 437294

**Comment by amusarra** [comment]
> Buongiorno, non ho ricevuto un feedback su questo caso specifico, ma dal comune mi segnalano lo stesso problema di firma dell'USC su un'altra annotazione dello stesso genere (rettifica per errore materiale). idOperazione: 437294

Dai nostri sistemi risulta questa situazione sulla vostra firma.

`11:59:07.970 ERROR traceId=, spanId=, sampled= [it.so.an.si.re.SignerRest] (executor-thread-20) Errore : exceptions.ServizioFirmaRemotaException: Errore servizio firma remota: 0004: Otp Credential Invalid Or Blocked: exceptions.ServizioFirmaRemotaException: Errore servizio firma remota: 0004: Otp Credential Invalid Or Blocked
`

Consigliamo di verificare lo stato dell'account di firma.

Cordiali Saluti.
Supporto ANSC.
