### ISSUE TITLE
[SC]: usecase311212	Matrimonio con Rito Civile fuori dalla casa comunale in Imminente Pericolo di Vita   MATR_003

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#1102]
### Ambiente

pre-produzione

### Servizio

R001 - Servizi cooperativi allegati

### idOperazione

assente

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

venezia

### Descrivi il problema

Buongiorno,
mi dicono dal Comune di Venezia che manca il certificato medico come allegato.

**Comment by mttfranci** [comment]
Buongiorno @annamaraspin, grazie della segnalazione.
Prendiamo in esame la richiesta sottoponendola ad ANUSCA al fine di verificare il modo migliore di procedere.

Saluti

Assistenza ANSC

**Comment by mttfranci** [comment]
Ok grazie, verifichiamo.

Saluti

Assistenza ANSC

**Comment by mttfranci** [comment]
@annamaraspin , dovremmo rilasciare la modifica che soddisfa la richiesta nei prossimi rilasci.

Saluti

Assistenza ANSC

PS: simile alla #1121

**Comment by asqueglia** [comment]
Con il rilascio della versione 1.34.0 la segnalazione è stata risolta
