### ISSUE TITLE
[SC]: Cittadinanza - Notifiche ANPR che arrivano tramite web-service

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/ansc#1104]
### Ambiente

pre-produzione

### Servizio

R014 - Servizi cooperativi per la gestione data di validità verso anagrafe

### idOperazione

nessuno

### idEvento o idAnsc

2024-3515137-367-039010

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

FAENZA

### Descrivi il problema

atto di acquisto cittadinanza 2024-3515137-367-039010

lato ANSC
- è stata inviata la comunicazione di validazione data (ws R014)
- le notifiche sono state scaricate e approvate

lato ANPR 
- dalla web-app vediamo la notifica di MUTAZIONE_CITTADINANZA ma la stessa non viene scaricata tramite web-service (
richiesta anche questa mattina la lista delle notifiche dal 10/10 ad oggi non viene scaricato niente
(rif. idOperazioneAnpr 75549530 - ws 4005 - operazione NA00)

potete verificare per piacere?

grazie
Alessandro ADS

**Comment by gbuemi** [comment]
Buona sera @AMonopoliADS,
potete riprovare a scaricare le notifiche sempre con lo stesso range di data? La questione è rientrata.

Un saluto,
Supporto ANSC

**Comment by AMonopoliADS** [comment]
buongiorno @gbuemi 

ho appena provato.
richiesta delle notifiche relative al periodo 10/10/24 - 22/10/24 
idOperazioneAnpr della Richiesta: 75565552 (2024-10-22T08:05:39 - con dataDisponibilità: 2024-10-22T08:20:41.089+02:00)
idOperazioneAnpr della Verifica di Stato: 75565587 (2024-10-22T08:21:47)

e continuo a non ricevere le notifiche

**Comment by gbuemi** [comment]
Buongiorno @AMonopoliADS ,
ci scusiamo per l'inconveniente, verifichiamo nuovamente.

Grazie,
Supporto ANSC

**Comment by gbuemi** [comment]
Buongiorno @AMonopoliADS,
causa fraintendimento interno, 3 giorni fa dovevamo chiedervi di verificare l'operazione originale, ovvero la 75549530 causa bug in fase di risoluzione.

Adesso è stato fatto un nuovo rilascio che risolve il problema, vi invitiamo pertanto a risottomettere una nuova richiesta con i parametri già indicati e chiudiamo la issue.

Scusate ancora per l'inconveniente.

Un saluto,
Supporto ANSC
