### ISSUE TITLE
[SC]: Errore in fase di firma attestazione di conformità

### ISSUE THREAD

**Issue by MichelaGarzoni** [italia/ansc#1105]
### Ambiente

pre-produzione

### Servizio

R007 - Servizi cooperativi firma ufficiale di stato civile

### idOperazione

2646306

### idEvento o idAnsc

2024-3517191-153-032001

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Duino - Garzoni

### Data del test (yyyy-mm-dd)

2024-10-21

### Descrivi il problema

In fase di firma di conformità degli allegati, mediante servizi cooperativi, abbiamo avuto un primo errore relativo a time-out. Dopo un attimo abbiamo quindi riprovato ad inviare il json per l'attestazione di conformità, ma non ci ha più permesso di firmarla (406004 - Firma non avvenuta con successo). Abbiamo provato ad eseguire la firma da WebApp e questa si è conclusa correttamente. Volevamo capire come mai ci veniva rifiutato il servizio di firma da servizio cooperativo.

### Payload (json)

```JSON
{
"testataRichiesta":{
"idComune":3655
,"idOperazioneComune":"153"
,"dataOraRichiesta":"2024-10-21T11:52:21Z"
,"nomeApplicativo":"ASCOT Stato Civile"
,"versioneApplicativo":"21.99.0000"
,"fornitoreApplicativo":"Insiel S.p.A"
}
,"idTipoFlusso":0
,"firmaInput":{
"idEvento":"3517191"
,"parametriFirma":{
"idTipoFirma":"1"
,"idModalitaInput":"2"
,"inputFirma1":"VGVzdFVzZXI="
,"inputFirma2":"VGVzdFBhc3N3b3Jk"
,"inputFirma3":"VGVzdE90cA=="
}
}
}
```

**Comment by amusarra** [comment]
Salve @MichelaGarzoni 
Abbiamo preso in carico la segnalazione.

Cordiali Saluti.
Supporto ANSC.

**Comment by amusarra** [comment]
Salve @MichelaGarzoni 
Dai nostri sistemi i log sono stati ruotati e non siamo riusciti a fare ulteriori indagini. Potrebbero esserci stati dei problemi temporanei con il servizio di firma. Vi invitiamo a fare un nuovo test e nel caso in cui non dovessero esserci altri problemi, vi chiederemo di chiudere la issue.

Come nota, vi chiediamo di controllare il formato dell'ora `dataOraRichiesta`; dai nostri sistemi quella UTC (Z) è `2024-10-21T09:52:21Z` e non `2024-10-21T11:52:21Z` che dovrebbe invece essere `2024-10-21T09:52:21+02:00`. Vi torna?

Cordiali Saluti.
Supporto ANSC.

**Comment by MichelaGarzoni** [comment]
Buongiorno @amusarra , il formato dell'ora da voi indicato corrisponde alla prima prova di firma eseguita, successivamente abbiamo richiamato il servizio più volte fino all'ora da noi indicata. Appena riusciamo a riprodurre l'errore vi ricontattiamo per ulteriori verifiche.
Grazie
