### ISSUE TITLE
[SC]: Errore attribuzione numero unico ANPR a sposo non presente in ANPR

### ISSUE THREAD

**Issue by LucaBonini64** [italia/ansc#1108]
### Ambiente

pre-produzione

### Servizio

R009 - Servizi cooperativi validazione evento

### idOperazione

assente

### idEvento o idAnsc

3517437

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Novi Ligure

### Data del test (yyyy-mm-dd)

2024-10-22

### Descrivi il problema

Inserendo un matrimonio religioso, abbiamo comunicato i dati degli sposi di cui uno già presente in ANPR con ID unico nazionale XF98298HU e la sposa non presente in ANPR. Dopo aver inserito il matrimonio ci siamo accorti che alla sposa è stato attribuito il medesimo numero unico nazionale dello sposo, quindi facendo un'interrogazione per ID ANPR XF98298HU vengono restituiti due soggetti diversi.

**Comment by amusarra** [comment]
Salve @LucaBonini64 
Potrebbe indicarci l'idOperazione come richiesto e quale servizio d'interrogazione ha richiesto?

Cordiali Saluti.
Supporto ANSC.

**Comment by LucaBonini64** [comment]
Mi sono accorto della duplicazione perché nel fare una ricerca dell'intestatario, servizio R005, con il payLoad:
{"criteriRicercaSoggetto":{"idAnprUnico":"XF98298HU"},
"testataRichiesta":{"idComune":6498,"idOperazioneComune":"1531","dataOraRichiesta":"2024-10-22T16:22:36.9205294+02:00","nomeApplicativo":"hyperSIC.StatoCivile","versioneApplicativo":"9.23.21.00.1L03","fornitoreApplicativo":"APKAPPA S.r.l."}}
ho ricevuto una risposta multipla, vedi id operazione 2657277.
Ovviamente non sarà l'operazione di consultazione che ha duplicato il numero unico nazionale ma presumo l'operazione di validazione dell'evento fatto oggi per inserire l'evento 3517437, purtroppo non ho più il payload inviato per la validazione.
