### ISSUE TITLE
[R012] problema con la firma digitale (impossibilità di accedere con CNS)

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#111]
Ho implementato l'invio della mail per la firma elettronica. Ricevo correttamente la mail, clicco sul link, si apre la pagina per scegliere il metodo di autenticazione e scelgo CNS. A questo punto si apre questa pagina:

![errore CNS](https://github.com/italia/ansc/assets/131870281/a13d359f-5f5b-478a-aaa0-d65e42fdea23)

Ho provato con 3 diversi browser, anche in modalità "in incognito", ma ho sempre lo stesso problema. In alcuni casi mi chiede di selezionare un certificato, seleziono quello che ho ricevuto per email, ma poi si presenta lo stesso problema.

**Comment by mttfranci** [comment]
@biadanpad l'anomalia dovrebbe essere superata. Potreste riprovare?
Grazie in anticipo.

**Comment by biadanpad** [comment]
Buongiorno, 
confermo che adesso funziona regolarmente.

Grazie.
