### ISSUE TITLE
Matrimonio in imminente pericolo di vita - Accertamento volontà non digitabile 

### ISSUE THREAD

**Issue by ANPRCdMI** [italia/ansc#1110]
### Ambiente

pre-produzione

### Provenienza segnalazione

Software House

### Riferimenti operatore/comune

Comune di Milano

### Data del test (yyyy-mm-dd)

2024-10-22

### Caso d'uso

3.1.1.2.1.2

### Descrivi il problema

Se i dati dello sposo o della sposa vengono inseriti manualmente, il flag "Imminente pericolo di vita" è selezionabile e il campo (obbligatorio) "Accertamento volontà" è digitabile.

Se  invece i dati dello sposo o della sposa vengono acquisiti da ANPR mediante il bottone Ricerca, il flag "Imminente pericolo di vita" è selezionabile ma il campo (obbligatorio) "Accertamento volontà" risulta protetto, impedendo di fatto il salvataggio dei dati e il completamento dell'atto

**Comment by asqueglia** [comment]
Buongiorno prendiamo in carico la segnalazione.

**Comment by asqueglia** [comment]
Con il rilascio della versione 1.34.0 la segnalazione è stata risolta
