### ISSUE TITLE
[SC]: impossibile creazione atto di morte (Morte_001)

### ISSUE THREAD

**Issue by antonioluberto** [italia/ansc#1111]
### Ambiente

produzione

### Servizio

R009 - Servizi cooperativi validazione evento

### idOperazione

442950

### Provenienza segnalazione

Comune

### Comune di riferimento e operatore

Grottaferrata

### Data del test (yyyy-mm-dd)

24/10/2024

### Descrivi il problema

All'invocazione del servizio R009 per la creazione dell'atto di morte (caso d'uso: Morte_001), otteniamo l'errore:

"Il campo evento.intestatari[0].idANPR nella sezione Deceduto non corrisponde al pattern ^[a-zA-Z0-9]{9}$"},{"code":"400003","severity":"E","text":"Il campo evento.datiEventoMorte.comparente1.idANPR nella sezione Comparente 1 non corrisponde al pattern ^[a-zA-Z0-9]

**Comment by asqueglia** [comment]
Buongiorno state trasmettendo nel campo idANPR, sia del comparente che dell'intestatario anzichè l'identificativo unico ANPR, l'id soggetto anpr.

 "comparente1": {
                "idsoggettoanpr": "yyyyyyyy",
                **"idANPR": "yyyyyyyy",**
                "codiceFiscale": "XXXXXXXXXXXXX",

da ciò l'errore che ricevete.
L'identificativo unico è alfanumerico di 9 caratteri e potete recuperarlo da ANPR per i soggetti indicati se volete trasmetterlo; non è comunque obbligatorio.

**Comment by antonioluberto** [comment]
Procederemo senz'altro a differenziare la valorizzazione dei due campi:
"idsoggettoanpr": 
"idANPR": 

ma qualcosa non è del tutto chiara:

a) in ambiente di pre-produzione non è attivo il controllo che questa mattina ha impedito la creazione dell'atto di morte presso il Comune; si veda a riguardo, da ultimo, l'atto di morte (Morte_001) 
"idOperazione":"2668711"
identificativo nazionale atto: 2024-3613543-216-058046
in relazione al quale è indicato sia per il titolare che per il dichiarante il medesimo valore per i due campi

![image](https://github.com/user-attachments/assets/b523055f-2158-4447-bf8a-e4b0ec05a1ca)


![image](https://github.com/user-attachments/assets/1dba7122-91ff-4894-b856-3df4b47bbec4)

E' possibile allineare i controlli fra i due ambienti in maniera tale che, in futuro, da parte nostra si possa avere evidenza di problemi del tipo in discussione (e, quindi, di tutte le nostre possibili imperfezioni implementative) già in sede di test?

b) in ambiente di produzione, per altro atto prodotto dal Comune questa mattina
idOperazione:442554
identificativo nazionale atto:2024-32257-993-058046
non si è avuta alcun'anomalia nella creazione/conferma dell'atto su ANSC; qui, ancora, in relazione agli avvocati i due campi
"idsoggettoanpr": 
"idANPR": 
sono stati valorizzati allo stesso modo.

E' possibile che il controllo che esclude la possibilità che i due campi:
"idsoggettoanpr": 
"idANPR": 

sia in effetti attivo (al momento solo in produzione) limitatamente ai soggetti titolari?

Rimaniamo in attesa di vostra indicazione.
Saluti,
Antonio

**Comment by asqueglia** [comment]
Con il rilascio della versione 1.34.0 la segnalazione è stata risolta
