### ISSUE TITLE
[SC]: usecase 51105 acquisto automatico di cittadina straniera che si sposa con cittadino italiano fino al 27 aprile 1983

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#1112]
### Ambiente

pre-produzione

### Servizio

R009 - Servizi cooperativi validazione evento

### idOperazione

assente

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

ponsacco, anna maraspin

### Descrivi il problema

Buongiorno,
ho chiesto ad alcuni dei nostri Comuni informazioni relativamente allo usecase in oggetto in quanto non trovavo da nessuna parte la formula corretta.
Mi è stato riferito che la normativa non prevede la formazione atto per questo caso e che di conseguenza è giusto che non ci sia la formula. 
Svista da parte del Ministero/Anusca o ci saranno cambiamenti imminenti nella legge che preveda la formazione di un atto?

**Comment by asqueglia** [comment]
Buongiorno, chiederemo agli esperti ANUSCA e le faremo sapere.

**Comment by annamaraspin** [comment]
Buongiorno, integro il ticket con una mail arrivatami oggi dal Comune di Venezia

"ho fatto alcune verifica del caso atto in oggetto e, come prevedevo, non esiste una formula per atto o annotazione in quanto trattandosi di automatismo di legge non era prevista.
Ho fatto una prova in Webapp e ci sono due errore di fondo:
1) il sistema propone il caso atto all'interno delle dichiarazioni di acquisto;
2) l'atto che viene costruito è una trascrizione di una attestazione o provvedimento.
A mio parere dovrebbe trattarsi, eventualmente, di trascrizione di un atto di rinuncia alla cittadinanza italiana (pervenuto ora per allora dall'estero) a seguito dell'acquisto automatico come previsto dall'art. 7 della L. n. 123/1983 oppure, se proprio prevedono una presa d'atto dell'acquisto automatico a seguito di procedimento di ricognizione effettuato ora per allo da un usc e il quale il MI decide di farlo trascrivere, sarebbe necessario rivedere il tipo di caso atto e non inserirlo nelle dichiarazioni di acquisto.

Ho sentito Anusca e confermando quanto ti evidenzio, mi hanno suggerito di segnalarlo per discutere del caso negli incontri periodici."

**Comment by asqueglia** [comment]
Buongiorno da un approfondimento con ANUSCA, si ritiene opportuno conservare questo caso d’uso, sebbene non frequente e non obbligatorio integrarlo,  da utilizzare però soltanto nei casi opportuni come indicato. Si chiude pertanto la issue. In caso di ulteriori dubbi si prega di aprire una issue dedicata.
