### ISSUE TITLE
[SC]: controllo bloccante su valida evento

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#1115]
### Ambiente

pre-produzione

### Servizio

R009 - Servizi cooperativi validazione evento

### idOperazione

2673676

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

ponsacco, anna maraspin

### Descrivi il problema

Buongiorno,
ho fatto questo test:
intrapresa casistica citt_001 e validato atto con successo, mi torna idatto 2024-3613749-583-050028
subito dopo averlo validato e prima di firmare l'atto, lo leggo e mi accorgo di aver preso la casistica sbagliata.
Ritorno indietro e intraprendo la casistica citt_008.
Quando valido l'atto e mi torna "400016 - Id caso d'uso non modificabile" con idOperazione:2673676

Sbagliamo noi a passarvi qualche dato oppure dopo il valida evento non è più possibile ripensarci?
Fino ad un paio di settimane fa non mi è mai capitato questo blocco.

grazie

**Comment by asqueglia** [comment]
Buongiorno, non è possibile modificare il codice del caso d'uso; i casi d'uso sono codificati e i dati di ciascun caso d'uso sono diversi. Il messaggio di errore è quindi corretto. Chiudiamo pertanto la issue. In caso di ulteriori dubbi s prega di aprirne una altra dedicata.
