### ISSUE TITLE
[webapp]: Invio notifiche ad ANPR dopo registrazione atto ANSC

### ISSUE THREAD

**Issue by SimonaGrisi** [italia/ansc#1120]
### Ambiente

pre-produzione

### Provenienza segnalazione

Comune

### Riferimenti operatore/comune

Simona Grisi

### Descrivi il problema

Dopo aver inserito tramite la WEB App ANSC un atto di nascita con entrambi i genitori residenti ed averlo validato mi aspettavo una notifica su ANPR; 
La prova è stata fatta in ambiente di pre-produzione ed i genitori residenti sono presenti in ANPR in ambiente di test.
L'atto inserito è il numero 3514534 (id atto) 2024-3514534-1-017074 (id-ansc), potreste indicarmi eventuali errori o se è stato  omesso qualche passaggio?
Si ringrazia anticipatamente per l'aiuto.

**Comment by asqueglia** [comment]
Buongiorno,  anche se il cittadino è residente nello stesso comune che ha formato l'atto è necessario confermare la notifica per presa visione. Come descritto in documentazione, dalla Web App ANSC selezionare la campanella in alto a destra; verrà mostrata la notifica dell'atto di nascita registrato; tramite il pulsante 'Gestisci' è necessario confermare la presa visione dell'atto. Senza questa conferma esplicita non partono le comunicazioni anagrafiche. Nel vostro caso non avete ancora confermato la presa visione.

Chiudiamo pertanto la issue pregando di aprirne una altra dedicata in caso di ulteriori dubbi.
