### ISSUE TITLE
[webapp]: Creazione di annotazione su atti di altro Comune

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#1123]
### Ambiente

pre-produzione

### Provenienza segnalazione

Software House

### Riferimenti operatore/comune

ponsacco, anna maraspin

### Descrivi il problema

Credo che lo stesso problema potrebbero esserci anche sui servizi cooperativi (provvederò quando sarà sviluppata questa parte nel nostro gestionale)

L'operazione che voglio effettuare è : Annotazione di errore materiale.
Io Comune di Ponsacco devo scegliere su che atto provvedere alla correzione. Pensavo che si potesse scegliere solo atti del proprio comune (Ponsacco) invece no. 
Se cerco l'atto fatto a Duino, ad esempio, me lo seleziona tranquillamente. 
Implemento la formula dell'annotazione con la correzione e vado ad impostare il valore che dovrebbe assumere quel dato errato.
Salvo e mando la comunicazione ad ANSC.
Andando nella webapp di Duino davo per scontato che comparisse una notifica dell'annotazione a cui provvedere all'accettazione o rifiuto: invece no. Il nulla.
Dalla webapp sia del Comune di Ponsacco che di Duino ho provato a richiedere copia dell'atto e l'estratto della copia integrale: c'è l'annotazione correttiva apposta.

Ho contattato un paio dei nostri Comuni in quanto mi sono sorti dubbi su questa operazione: 
E' corretto che un altro Comune vada a correggere un mio atto? 
E che Duino, Comune che ha redatto l'atto, non venga avvisato in nessuna maniera? 

La risposta unanime dei Comuni è stata (copio/incollo):
"
La competenza alla correzione di un atto è dell'usc che l'ha formato e non mi risultano modifiche alla legge

 Art. 98
L'ufficiale dello stato civile, d'ufficio o su istanza di chiunque ne abbia interesse, corregge gli errori materiali di scrittura in cui egli sia incorso nella redazione degli atti mediante annotazione dandone contestualmente avviso al prefetto, al procuratore della Repubblica del luogo dove è stato registrato l'atto nonché agli interessati. Con le medesime modalità, l'ufficiale dello stato civile procede, inoltre, su istanza di chiunque ne abbia interesse, alla correzione degli atti formati, quando emerge la discordanza tra le indicazioni in essi riportate e quelle risultanti da altri documenti rilasciati dalle autorità competenti. (10) ((
Allego anche la circolare MI del 2023, che aveva modificato l'art. 98 a seguito della Cartabia, dove è chiara la competenza dell'usc.
Inoltre, ho riguardato l'art. 6, 4° comma del DM 18.10.2022 su ansc e ribadisce che per la rettifica  o correzione di una atto di segue la normativa vigente.
"

[circ-dait-022-servdemo-01-03-2023.pdf](https://github.com/user-attachments/files/17556717/circ-dait-022-servdemo-01-03-2023.pdf)

**Comment by asqueglia** [comment]
Buongiorno, provvediamo alla verifica ma confermiamo quanto riportato dai comuni ossia che la competenza della correzione di un atto è del comune che ha formato l'atto. Verifichiamo immediatamente la segnalazione.

**Comment by annamaraspin** [comment]
Grazie.
Al caso volete che faccia un'altra prova e vi indichi gli atti , numeri ansc e altri dati necessari per risalire al tutto? Purtroppo della vecchia prova non avevo preso nota di nulla pensando che non funzionasse.

**Comment by asqueglia** [comment]
Buon pomeriggio, abbiamo appena fatto una prova sia da Web App che lato servizi cooperativi e abbiamo verificato che scatta il controllo bloccante seguente:
'L'evento da rettificare è stato emesso dal comune di XXXX, non è possibile rettificare l'atto da un comune diverso.'

Forse utilizzate una versione dei servizi vecchia ? se rifate una prova molto meglio in modo da poter controllare il problema.

**Comment by annamaraspin** [comment]
Fatto tutto con la webapp (se ricordo bene il 23 o 24 ottobre) perché nel nostro gestionale non abbiamo ancora sviluppato le annotazioni.
Riprovo subito e vi faccio sapere

**Comment by annamaraspin** [comment]
Effettivamente mi è comparso il messaggio e non mi lascia proseguire come da sua risposta.
Non so cosa sia successo la scorsa settimana quando sono riuscita ad eseguirlo assieme alle colleghe.
L'importante è che non lo faccia più, al caso ci annoteremo tutti i dati importanti dalla prossima volta che se capita qualcosa di strano vi diamo tutte le informazioni fin da subito.
grazie e buon pomeriggio
