### ISSUE TITLE
[webapp]: problema di metadati

### ISSUE THREAD

**Issue by dandreap** [italia/ansc#1128]
### Ambiente

pre-produzione

### Provenienza segnalazione

Comune

### Riferimenti operatore/comune

D'ANDREA PAOLA

### Data del test (yyyy-mm-dd)

31-10-2024

### Caso d'uso

[3.1.1.1.1.1]

### Descrivi il problema

Nel matrimonio civile nella casa comunale, nei meta dati viene riportata la data di nascita dell'ufficiale di stato civile che celebra il matrimonio. Tale campo non dovrebbe esistere, nemmeno se popolato all'interno della formazione dell'atto.

**Comment by asqueglia** [comment]
Buongiorno, i metadati dell'atto contengono tutte le informazioni inviate ed acquisite dal sistema_; nel corpo dell'atto invece (la minuta) compaiono soltanto i dati espressamente richiesti dalle formule. Questi i requisiti concordati. Oltre alla copia integrale così come la conoscete oggi (comprensiva di estratti e metadati), comunichiamo che prossimamente sarà disponibile la copia integrale semplificata che conterrà solo la minuta dell'atto senza i metadati.

Chiudiamo pertanto la issue ; in caso di dubbi si prega di aprirne una altra dedicata.
