### ISSUE TITLE
[webapp]: Esatta definizione del celebrante del matrimonio (ufficiale dello stato civile) e indicazione del comune di matrimnio

### ISSUE THREAD

**Issue by dandreap** [italia/ansc#1129]
### Ambiente

pre-produzione

### Provenienza segnalazione

Comune

### Riferimenti operatore/comune

D'ANDREA PAOLA

### Data del test (yyyy-mm-dd)

31-10-2024

### Caso d'uso

[3.1.1.1.1.1]

### Descrivi il problema

Ci sono piu problemi nella parte iniziale dell'atto di matrimonio, in particolare a partire dal nome del celebrante fino alla dicitura "vestito in forma ufficiale".
Innanzitutto non capisco perchè c'è la possibilità di scelta tra diversi tipi di officiante (sindaco/vicesindaco/ufficiale dello stato civile/ comune cittadino/comandante nave/comandante aerero"). E' corretto che ci sia sindaco o vicesindaco (che agisce in assenza del sindaco), ma ufficiale dello stato civile o comune cittadino o comandante nave o comandante aereo non ha senso che venga riportato in questo campo. Si tratta di matrimoni celebrati da un ufficiale di stato civile sia esso il sindaco o il vicesindaco (in assenza del sindaco) o da un impiegato del comune (ufficiale di stato civile per delegazione avuta) o un comune cittadino (ufficiale di stato civile per delega avuta).  Non si tratterà mai di un comandate di nave o aereo.

**Comment by dandreap** [comment]
Scusate... manca un pezzo del quesito...
la formula iniziale deve essere nel caso del sindaco quale celebrante
... Avanti a me, Cognome e nome, sindaco, ufficiale dello Stato civile del comune di________________ (1)  vestito in forma ufficiale....
nel caso di vice sindaco
... Aventi a me, Cognome e NOme, vice sindaco, ufficiale dello stato civile del comune di _____________ (1) in assenza del sindaco, vestito in forma ufficiale....
nel caso di ufficiale di stato civile delegato (sia esso l'impiegato comunale o il privato cittadino)
...Avanti a me, Cognome e Nome, ufficiale dello stato civile del comune di____________________ (1) per delegazione avuta, vestito in forma ufficiale
A seconda del caso manca sia l'indicazione di "ufficiale di stato civile", manca il COMUNE DI CELEBRAZIONE, manca l'indicazione necessaria dopo il punto (1) (cioè per delegazione avuta, o in assenza/impedimento del sindaco)

**Comment by asqueglia** [comment]
Buongiorno, l'attività è stata presa in carico ed approfondita con ANUSCA. 
Nello specifico verrà effettuato il seguente intervento:

Nel caso il matrimonio/Unione civile sia celebrato da Sindaco, la frase di apertura sarà:
…avanti a me, SIPARI ELISEO, **Ufficiale dello Stato Civile del comune di XXX, Sindaco,** vestito in forma ufficiale, sono personalmente comparsi:
Nel caso il matrimonio/Unione civile sia celebrato da Vicesindaco la frase di apertura sarà:
…avanti a me, SIPARI ELISEO, **Ufficiale dello Stato Civile del comune di XXX, Vicesindaco,** vestito in forma ufficiale, sono personalmente comparsi:
Nel caso il matrimonio/Unione civile sia celebrato da Ufficiale di Stato civile la frase di apertura sarà:
….avanti a me, SIPARI ELISEO, **Ufficiale dello Stato Civile del comune di XXX, delegato,**  vestito in forma ufficiale, sono personalmente comparsi:
Nel caso il matrimonio/Unione civile sia celebrato da un soggetto diverso da Sindaco, Vicesindaco, Ufficiale di Stato civile la frase di apertura sarà:
..avanti a me, SIPARI ELISEO, **Ufficiale dello Stato Civile del comune di XXX, delegato,** vestito in forma ufficiale, sono personalmente comparsi:

Faremo sapere quando l'attività verrà rilasciata

**Comment by asqueglia** [comment]
Con il rilascio della patch 1.34.7 è stata corretta la segnalazione. Chiudiamo la issue. In caso di ulteriori malfunzionamenti si prega di aprire una issue dedciata
