### ISSUE TITLE
[webapp]: caso 311111 - matrimonio- Consultazione in ansc (sezione annotazioni): annotazione scelta della separazione dei beni non in elenco

### ISSUE THREAD

**Issue by dandreap** [italia/ansc#1130]
### Ambiente

pre-produzione

### Provenienza segnalazione

Comune

### Riferimenti operatore/comune

D'ANDREA PAOLA

### Data del test (yyyy-mm-dd)

04-11-2024

### Caso d'uso

311111

### Descrivi il problema

Ho inserito un matrimonio celebrato nella casa comunale tramite il mio software (id atto 3615046). Gli sposi hanno scelto la separazione dei beni. Da ansc ho richiamato l'atto (ricerca per evento-id atto 3615046). Dal menu a tendina "azione" ho selezionato "annotazioni" e il responso è stato che non ci sono annotazioni. Se invece richiedo la copia integrale, è visibile l'annotazione di scelta della separazione dei beni.
[github1.odt](https://github.com/user-attachments/files/17614704/github1.odt)

**Comment by asqueglia** [comment]
Buongiorno, abbiamo verificato che la separazione dei beni è stata tramessa come annotazione contestuale alla registrazione dell'atto; essendo una annotazione contestuale non compare nella consultazione annotazioni in quanto, almeno al momento, tale funzionalità è dedicata alle annotazioni registrate successivamente la registrazione dell'atto; malgrado ciò le certificazioni e gli estratti (riassunto e integrale) tengono conto dell'annotazione contestuale registrata. Chiudiamo pertanto la issue. In caso di ulteriori dubbi, la preghiamo di aprirne una altra dedicata.
