### ISSUE TITLE
[webapp]: Notifica anagrafica evento divorzio

### ISSUE THREAD

**Issue by Hdemografici** [italia/ansc#1131]
### Ambiente

pre-produzione

### Provenienza segnalazione

Software House

### Riferimenti operatore/comune

Halley informatica

### Data del test (yyyy-mm-dd)

04/11/2024

### Caso d'uso

345000

### Descrivi il problema

Buongiorno,
tramite WA del Comune di Colli al Metauro è stato inserito atto di trascrizione negoziazione assistita art.6 D.L. 132/2014 di cessazione degli effetti civili di matrimonio (caso uso 345000) relativa a soggetti con ID ANSC 3418768 e 3418771 entrambi residente a Colli al Metauro (ID ANPR 152941848 e 152941849)
atto 2024-3713343-12-041069

dopo aver chiuso l'atto, salvato la data di validità anagrafica e apposto la firma dell'ufficiale di stato civile sono state approvate le notifiche lato ANSC in data 4/11/2024
verificando lato ANPR dalla funzione "Notifiche ANSC" non si riscontrano ad oggi nella WA notifiche relative all'evento divorzio dei cittadini interessati

discorso trasponibile anche effettuando prove utilizzando i servizi cooperativi

si chiede delucidazione sul motivo per il quale non viene generata la notifica anagrafica dell'evento divorzio e quindi capire se stiamo sbagliando qualcosa nell'interpretazione del flusso di lavoro in questa circostanza  

grazie per l'attenzione

**Comment by asqueglia** [comment]
Buongiorno, verifichiamo e le facciamo sapere

**Comment by asqueglia** [comment]
Buon pomeriggio abbiamo verificato che non sono state approvate tutte le notifiche generate da sistema; questo il motivo per cui non è stata generata la notifica di predisposizione anagrafica. Nello specifico le notifiche da approvare sono

3418792 Annotazione automatica id 2024-3713346-00000-041069 ( da inviare via PEC )  -> per il soggetto 3418771
3418790 Annotazione automatica id 2024-3713345-00000-041069 ( da inviare via PEC ) -> per il soggetto 3418768

si tratta di due annotazioni automatiche generate da sistema da inviare via pec destinate all'atto di nascita cartaceo. Risultano ancora da approvare.

Chiudiamo pertanto la issue. In caso di ulteriori dubbi si prega di aprire una altra issue dedicata
