### ISSUE TITLE
[SC]: versione 1.34  caso d'uso 2214

### ISSUE THREAD

**Issue by migmar68** [italia/ansc#1132]
### Ambiente

produzione

### Servizio

R009 - Servizi cooperativi validazione evento

### idOperazione

assente

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Poggio a Caiano

### Descrivi il problema

nella documentazione della nuova versione 1.34  
è previsto il caso d'uso 
2214	Trascrizione atto morte su richiesta dell'interessato per art. 19
a riga 202 del file Decodifiche\3_dec_use_case.xlsx
![image](https://github.com/user-attachments/assets/5a99f22d-4f3e-48d3-bbed-175d9c5a0db2)

questa riga mi sembra mancante invece nel file corrispondente di associazione con variabili e controlli.
![image](https://github.com/user-attachments/assets/fe0cc4a2-ea6d-4d2f-924e-9faa1dbbacf9)

**Comment by asqueglia** [comment]
Buon pomeriggio, con la versione 1.34.1 è stata corretta la segnalazione.
