### ISSUE TITLE
[webapp]: [3.6.9.0.0.0] Annotazione modificativa generica

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#1134]
### Ambiente

pre-produzione

### Provenienza segnalazione

Software House

### Riferimenti operatore/comune

 anna maraspin, ponsacco

### Data del test (yyyy-mm-dd)

2024-11-06

### Caso d'uso

[3.6.9.0.0.0]

### Descrivi il problema

Buongiorno, 
ho fatto questi due test e avrei bisogno di una delucidazione
TEST 1) valorizzo e salvo i dati relativi a Intestatario, Atto di riferimento, Soggetto collegato, Dati generali e Composizione libera. Mi accordo che in Soggetto collegato ho preso una persona sbagliata, non dovevo impostare nulla in realtà . Premo Ripulisci e poi salvo. Quando vado a validare l'atto mi torna l'errore
![image](https://github.com/user-attachments/assets/0243401e-af53-4ce5-91f7-3f30256a6c90)
Nel mapping del caso il "soggetto collegato " non ha nessun campo obbligatorio
TEST 2) valorizzo e salvo i dati relativi a Intestatario, Atto di riferimento, Dati generali e Composizione libera. Non faccio nulla in Soggetto Collegato. Provo a validare --> tutto OK

delucidazione: nel Soggetto Collegato devo cercare se esiste già la mia persona con il cognome e/o nome nuovo perché è stato formato un atto prima della mia annotazione? 

Grazie

**Comment by asqueglia** [comment]
Buon pomeriggio, il soggetto collegato è una sezione che consente di riconciliare il soggetto contestualmente alla registrazione dell'annotazione modificativa.
Ad esempio supponiamo che nel sistema sia presente un atto di nascita di un soggetto A di cui successivamente si acquisisce l'atto di matrimonio con nuove generalità (esempio nuovo cognome ) generando quindi un soggetto B; quando si registra l'annotazione in oggetto, è possibile contestualmente fare la riconciliazione delle due anagrafiche, tramite la sezione soggetto collegato.

Per quanto riguarda il bug riscontrato verifichiamo e le facciamo sapere.

**Comment by annamaraspin** [comment]
Ok, grazie. Ero giunta alla conclusione su "soggetto collegato" corretta.

Mi ero dimenticata: nell'intestatario non tutti i campi sono in sola lettura. Credo anche questo un bug.

**Comment by asqueglia** [comment]
L'anomalia segnalata è stata corretta. Chiudiamo pertanto la issue
