### ISSUE TITLE
[SC]: anomalia comune competente notifica di tipo "annotazione"

### ISSUE THREAD

**Issue by antonioluberto** [italia/ansc#1135]
### Ambiente

pre-produzione

### Servizio

R008 - Servizi cooperativi notifiche

### idOperazione

2729360

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Seregno

### Data del test (yyyy-mm-dd)

06/11/2024

### Descrivi il problema

Su ambiente di pre-produzione del Comune di Seregno è stato creato l'atto di matrimonio 
2024-3713807-16-108039
trasferendo in ANSC i riferimenti completi agli atti di nascita, rispettivamente, dello sposo:

![image](https://github.com/user-attachments/assets/302cbb3a-bf71-4b47-89d4-4928618ef081)

e della sposa:

![image](https://github.com/user-attachments/assets/ea2fd1dc-22da-4661-8397-41888510fda7).

In riferimento all'atto medesimo si ottengono, le due notifiche di tipo annotazione:
"idAnsc":"2024-3713809-00000-108039"
"idAnsc":"2024-3713810-00000-108039" .

La prima, in particolare ("idAnsc":"2024-3713809-00000-108039"), è quella relativa all'annotazione di matrimonio da apporsi sull'atto di nascita dello sposo. Per quanto rappresentato sopra, ANSC sa quale sia il Comune presso il quale si trovi l'atto (cartaceo) di nascita dello sposo; sa quindi quale sia il Comune "competente" per l'annotazione e, nel particolare caso specifico, sa che si tratta di Comune diverso (Grottaferrata) da quello che ha formato l'atto di matrimonio (Seregno); ciononostante, il servizio R008 restituisce indicazione del _Comune competente_ sempre coincidente con l'indicazione del _Comune formazione_:

![image](https://github.com/user-attachments/assets/a2cb0993-e876-4fdc-956c-6b51606cdf6e)

**Comment by asqueglia** [comment]
Buongiorno, attualmente tutti gli atti cartacei sono gestiti allo stesso modo; per tutti gli atti cartacei il sistema invia le notifiche relative alle proposte di annotazione, al comune di formazione dell'atto sorgente da cui scaturiscono le annotazioni. L'evolutiva segnalata è prevista per il prossimo anno. 
Chiudiamo pertanto la issue. In caso di dubbi o ulteriori incertezze preghiamo di aprire una issue dedicata.
