### ISSUE TITLE
[SC]: Errore validazione caso d'uso di servizio con nuovi campi flagCertificatoSemplice e flagEstrattoPerRiassunto

### ISSUE THREAD

**Issue by siscomanpr** [italia/ansc#1136]
### Ambiente

pre-produzione

### Servizio

R009 - Servizi cooperativi validazione evento

### idOperazione

2729901

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Serravalle Sesia

### Descrivi il problema

Con la versione 1.34 sono stati introdotti i nuovi campi flagCertificatoSemplice e flagEstrattoPerRiassunto da utilizzare per i casi d'uso di servizio. 
Tentando di trasmettere un atto con caso d'uso di servizio 1399 (trascrizioni nascita), ci restituisce errore:
`Attenzione! è possibile valorizzare i campi (flagCertificatoSemplice,flagEstrattoPerRiassunto) solo per i casi d'uso di servizio. `
E' un bug o abbiamo interpretato male la modalità di utilizzo dei nuovi campi?

**Comment by asqueglia** [comment]
Buongionon, verifichiamo e le facciamo sapere.

**Comment by asqueglia** [comment]
Buongiorno, la trasmissione dei fag indicati non è possibile per i seguenti casi d'uso, in quanto già prevedono tutte e tre le tipologie di certificazione

319999
329999
339999
2199
2299
11999999
1399
4199
439999

Potete quindi utilizzare i flag solo per i casi d'uso di servizio che non rientrano nella lista sopra elencata.
Adegueremo il messaggio di errrore per renderelo più esplicativo.

**Comment by asqueglia** [comment]
Chiudiamo la issue
