### ISSUE TITLE
[webapp]: Procedura di Proposta Adesione ANSC

### ISSUE THREAD

**Issue by KibMcris** [italia/ansc#1140]
### Ambiente

produzione

### Provenienza segnalazione

Software House

### Riferimenti operatore/comune

Kibernetes

### Descrivi il problema

Dalla sezione di Amministrazione con la smart card del Sindaco (comune di Pontedera), cliccando su "Proposta di Adesione", il sistema ANSC risponde con errore 500 con un messaggio che indica che prima di procedere occorre effettuare la richiesta della firme remote.
![image](https://github.com/user-attachments/assets/5872352a-0e11-40f0-8334-17dbfd5f702c)

Oltre l'errore in sè, gli ufficiali di stato civile potrebbero essere già in possesso di firma remota, quindi lo step non dovrebbe essere obbligatorio.

Facciamo presente che nei giorni scorsi la stessa procedura in altri enti è andata regolarmente a buon fine senza effettuare nessuna richiesta relativa alle firme remote.

**Comment by asqueglia** [comment]
Buongiorno, verifichiamo e le facciano sapere

**Comment by asqueglia** [comment]
Buongiorno potete riprovare. Ci scusiamo per il disservizio temporaneo. Chiudiamo pertanto la issue. In caso di ulteriori problematiche si prega di riaprirla.
