### ISSUE TITLE
[webapp]: Adozione artt. 25-27 Legge n. 183/1984 (annotazione F.122)

### ISSUE THREAD

**Issue by Hdemografici** [italia/ansc#1141]
### Ambiente

pre-produzione

### Provenienza segnalazione

Software House

### Riferimenti operatore/comune

Halley informatica 

### Data del test (yyyy-mm-dd)

07/11/2024

### Caso d'uso

1341

### Descrivi il problema

caso sentenza del tribunale per i minorenni che pronuncia l'adozione di minore ai sensi degli artt. 25-27 Legge n. 183/1984 (in questo caso affidamento preadottivo di cittadino italiano e dopo 1 anno viene emanata sentenza)

inserito da WA del Comune di Cartoceto atto di nascita utilizzando caso uso "1341 – Trascrizione sentenza emessa dal tribunale minori"
atto 2024-3713981-1-041010

nel testo dell'annotazione automatica 2024‐3713983‐00000‐041010 generata al termine del flusso di lavoro da apporre sull'atto di nascita viene riportata la formula 122-bis del formulario con riferimento di legge art. 35 Legge n. 183/1984 (adozione pronunciata all'estero ed il Tribunale italiano ordina la trascrizione della sentenza straniera, probabilmente più inerente al caso d'uso 1352).

In questa circostanza si ritiene dovrebbe essere proposta la formula 122 del formulario:

- ... (nome e cognome) è stato(a) adottato(a) da ... ai sensi degli articoli 25 e
seguenti della legge 4 maggio 1983, n. 184 (provvedimento del Tribunale per i
minorenni di ... in data ... n. ... trascritto nei registri di nascita del Comune di ...
anno ... parte ... serie ... n. ...) e pertanto assume il cognome di ...

si chiede quindi di valutare la possibilità di prevedere una variante per il caso d'uso in oggetto, prevedendo la possibilità di registrare l'annotazione 122

grazie per l'attenzione

**Comment by asqueglia** [comment]
Buongiorno, prendiamo in carico la segnalazione. Le facciamo sapere quando disponibile la correttiva

**Comment by asqueglia** [comment]
Buongiorno, con la patch 1.34.2 la segnalazione è stata corretta. Chiudiamo pertanto la issue
