### ISSUE TITLE
[SC]: Errore Interno firma Ufficiale Stato Civile

### ISSUE THREAD

**Issue by KibMcris** [italia/ansc#1145]
### Ambiente

produzione

### Servizio

R007 - Servizi cooperativi firma ufficiale di stato civile

### idOperazione

477787

### idEvento o idAnsc

33529

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Agrigento - Gaetano D'agostino

### Data del test (yyyy-mm-dd)

11/11/2024

### Descrivi il problema

Con operazione comune =4088 invocato il servizio di firma USC per la sottoscrizione dell'atto.
Ansc risponde con errore
HTTP Status 500 
`{"errors":[{"code":"500","severity":"E","text":"Errore` interno"}],"infos":[{"code":"110527","severity":"I","text":"Informazioni sull'operazione da fornire in caso di assistenza : data:2024-11-11 09:48:44 , idOperazione:477787"}],"testataRisposta":{"idComune":99,"idEsito":999,"idOperazione":"477787","idOperazioneComune":"4088"}}`

Abbiamo provato a prendere sia un nuovo OTP ANSC sia a rigenerare l'OTP della firma remota dell'USC. nell'eventualità che fossero scaduti.
Il sistema risponde sempre con errore interno, pur facendo questi tentativi.

L'atto deve essere sottoscritto in produzione

**Comment by asqueglia** [comment]
Buongiorno, abbiamo verificato che l'evento indicato risulta firmato stamattina alle 9:28. Chiudiamo pertanto la issue. In caso di ulteriori dubbi si prega di aprire una issue dedicata
