### ISSUE TITLE
[SC]: Obbligatorietà che non dovrebbe essere richiesta per il caso d'uso Rico_007 (12222121).

### ISSUE THREAD

**Issue by gcuci** [italia/ansc#1146]
### Ambiente

pre-produzione

### Servizio

R009 - Servizi cooperativi validazione evento

### idOperazione

2752647

### idEvento o idAnsc

2024-3714396-92-048017

### Provenienza segnalazione

Comune

### Comune di riferimento e operatore

Firenze

### Data del test (yyyy-mm-dd)

2024-11-11

### Descrivi il problema

Buongiorno,

il Comune di Firenze, ci segnala che per il caso d'uso '12222121'-'Rico_007' (Riconoscimento materno di figlio ultraquattordicenne già riconosciuto dal padre), non dovrebbe essere richiesta l'obbligatorietà dell'allegato 'Copia dell'atto di assenso del figlio' (id: 14).

In attesa di riscontro,

cordiali saluti.

**Comment by asqueglia** [comment]
Buongiorno, verifichiamo la segnalzaione con ANUSCA e le faremo sapere

**Comment by rvinzani** [comment]
Aggiungo che per gli infraquattordicenni l'allegato dell'assenso del figlio non è previsto
