### ISSUE TITLE
[SC]: errore validazione usecase 1312 - dati soggetto intestatario non conformi ai dati anagrafici registrati

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#1147]
### Ambiente

produzione

### Servizio

R009 - Servizi cooperativi validazione evento

### idOperazione

479897

### idEvento o idAnsc

-

### Provenienza segnalazione

Comune

### Comune di riferimento e operatore

Lissone - biadanpad

### Data del test (yyyy-mm-dd)

2024-11-12

### Descrivi il problema

Tentando di validare l'atto si ottiene l'errore "Attenzione! I dati del soggetto intestatario con idANSC=17614448 inseriti non sono conformi ai dati anagrafici registrati"

Facendo una verifica, però, non abbiamo capito quali sono i dati non conformi

### Payload (json)

```JSON
RESPONSE:
{
  "testataRisposta": {
    "idComune": 5000,
    "idOperazioneComune": "12490",
    "idOperazione": "479897",
    "idEsito": 1
  },
  "errors": [
    {
      "code": "400003",
      "severity": "E",
      "text": "Attenzione! I dati del soggetto intestatario con idANSC=17614448 inseriti non sono conformi ai dati anagrafici registrati"
    }
  ],
  "infos": [
    {
      "code": "110527",
      "severity": "I",
      "text": "Informazioni sull'operazione da fornire in caso di assistenza : data:2024-11-12 08:26:20 , idOperazione:479897"
    }
  ]
}
```

**Comment by asqueglia** [comment]
Buon pomeriggio, verifichiamo e facciamo sapere appena possibile

**Comment by biadanpad** [comment]
Dal comune ci hanno comunicato che sono riusciti a validare correttamente l'atto

**Comment by asqueglia** [comment]
Buongiorno, si sono riusciti in quanto abbiamo sanato da centro l'anomalia che si è venuta a generare sul soggetto intestatario a seguito della rettifica per art.98. In pratica nel payload della rettifica ci inviate un dato non previsto (in grassetto) che ha generato il problema.; 

"evento": {
        "idTipoEvento": "5",
        "idtipocontenuto": "2",
        "idUsecase": "53729",
        "descrizioneCasoUso": "Annotazione per errore materiale",
        "stato": "CONFERMATO",
        "idVersion": "100016",
        "dataformazione": "2024-11-08",
        "ora": "09",
        "minuto": "39",
        "operatore": "xxxxx",
        "operatoreNome": "xxxx",
        "operatoreCognome": "xxxx",
        "idComuneRegistrazione": "5000",
        "nomeComuneRegistrazione": "LISSONE",
        "idProvinciaRegistrazione": "108",
        "siglaProvinciaRegistrazione": "MB",
        "numeroatto": "xxxx",
        "allegati": [
            {
                "id": "xxx",
                "idTipoAllegato": "998",
                "hashAllegato": "xxxx",
                "descrizione": "xxxx",
                "idStatoAllegato": "3"
            }
        ],
        **"intestatari": [
            {
                "id": "xxxx"
            }
        ],**
        "eventoCollegato": {
            "id": "33312"
        },
        "datiRettifica": { ....... },
       "eventoModificato": {....}

abbiamo corretto la problematica con la patch 1.34.3 restituendo un messaggio di warning in cui avvisiamo che quel dato (intestatari vuoto a meno dell'identificativo) sotto evento, verrà ignorato; sono importanti infatti i dati sotto eventoModificato.

Chiudiamo pertanto la issue; in caso di ulteriori segnalazioni si prega di aprire una issue dedicata.
