### ISSUE TITLE
[SC]: Firma non avvenuta con successo

### ISSUE THREAD

**Issue by KibMcris** [italia/ansc#1148]
### Ambiente

produzione

### Servizio

R007 - Servizi cooperativi firma ufficiale di stato civile

### idOperazione

482892

### idEvento o idAnsc

2024-33666-69-102044

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Tropea- Andrea Cirillo

### Data del test (yyyy-mm-dd)

12/11/2024

### Descrivi il problema

Con idOperazioneComune=1297, è stata validata correttamente l'annotazione art.98 per errore materiale del cognome. Con successiva operazione. Con operazione ANSC=482886, ANSC ha validato l'annotazione con il numero 2024-33666-69-102044.
Arrivando a firmare l'annotazione,  ANSC risponde con il seguente errore:

HTTP Status 400 
`{"errors":[{"code":"406004","severity":"E","text":"Firma` non avvenuta con successo"}],"infos":[{"code":"110527","severity":"I","text":"Informazioni sull'operazione da fornire in caso di assistenza : data:2024-11-12 16:26:52 , `idOperazione:482892"}],"testataRisposta":{"idComune":10288,"idEsito":1,"idOperazione":"482892","idOperazioneComune":"1300"}}`

Abbiamo provato a firmare più volte l'annotazione (con otp di firma remota diversi), ma l'errore permane. Abbiamo verificato che l'OTP ANSC risulta essere valido poichè altri servizi rispondono correttamente.
Entrando sulla web app, consultando l'atto appare adesso il seguente errore:
![image](https://github.com/user-attachments/assets/121b701a-1338-48df-9829-a3c7c114a046)

Restiamo in attesa di riscontro

**Comment by asqueglia** [comment]
Buon pomeriggio, dalle verifiche effettuate abbiamo appurato che avete effettuato più tentativi con otp scaduto e le credenziali di firma sono state bloccate. Potete riprovare. Chiudiamo pertanto la issue. In caso di dubbi o ulteriori problematiche si prega di aprire una issue dedicata.

**Comment by asqueglia** [comment]
Buongiorno, prendiamo in carico la segnalazione, sebbene differente dal titolo della issue. Preghiamo di non riaprire issue su argomenti chiusi,  ma di aprirne nuove dedicate a nuove segnalazioni.

**Comment by asqueglia** [comment]
Buon giorno la segnalazione è stata corretta chiudiamo pertanto la issue
