### ISSUE TITLE
Adozione casi particolari caso d'uso 1342

### ISSUE THREAD

**Issue by rvinzani** [italia/ansc#1149]
### Ambiente

pre-produzione

### Provenienza segnalazione

Comune

### Riferimenti operatore/comune

Lissone

### Data del test (yyyy-mm-dd)

11/11/2024

### Caso d'uso

1342

### Descrivi il problema

in area di test abbiamo provato ieri ad inserire un atto con il caso d’uso in oggetto in quanto dovremo procedere al più presto con la trascrizione effettiva di una sentenza  in ANSC.

 

L’atto inserito è il numero 2024-3714422-130-108028 ed è relativo alla nascita registrata con il numero 2024-xxxx-114-108028.

Il caso era il seguente: bambina (xxxxxx xxxxx) registrata con il solo riconoscimento materno (xxxxx xxxxxx), adottata successivamente (ADOZIONE IN CASI PARTICOLARI) dal Sig. xxxxx xxxxxxx.

 

L’atto di nascita 2024-3714417-114-108028 è stato inserito con la sola indicazione della mamma xxxxxxx xxxxx.

La trascrizione della sentenza di adozione è stata inserita al n. 2024-xxxxx-130-108028 con la sola indicazione del padre adottivo e con l’indicazione del nuovo cognome attribuito alla minore.

Il risultato è stato il seguente:

 

In una prova precedente (atto 2024-xxxxxx-128-108028) avevamo inserito nei metadati entrambi i genitori (adottante è biologico), ma abbiamo visto che l’annotazione da apporre sull’atto di nascita veniva generata da ANSC in modo errato: entrambi i genitori figuravano come adottanti (vedi allegato A).
Abbiamo perciò inserito un altro atto riportando nei metadati solo le generalità dell’adottante (padre xxxx xxxxx). L’annotazione generata da ANSC indica correttamente che la bambina è stata adottata da xxxx xxxx , ma indica anche “e …” (vedi allegato “annotazione_adozione”). Questa parte deve essere omessa nel caso in cui l’adottante sia un solo genitore.
Nella certificazione, ANSC riporta correttamente il cognome assunto dalla minore a seguito di adozione (xxxxx xxxxxx) ma come genitore indica solo l’adottante xxxx xxxxxxx(vedi allegato certificazione_adozione). La certificazione corretta deve riportare i genitori che avevano riconosciuto la minore alla nascita (nel nostro caso solo la mamma xxxxxx  xxxxxxx come da atto numero 2024-xxxxx-114-108028 ); nell’annotazione (sempre certificabile) deve essere riportato che la bambina è stata adottata dall’/dagli adottante/i (nel nostro caso solo il padre). Come potete vedere nell’estratto però non viene riportata alcuna annotazione.

**Comment by asqueglia** [comment]
Con la patch 1.34.5 è stata corretta l'anomalia. Chiudiamo la issue

**Comment by asqueglia** [comment]
Come da accordi intercorsi nella call del 19/11,
si comunica che verrà preso in carico l'aggiornamento del caso d'uso come segue:

**nel corpo del certificato/estratto devono essere ripotati i nomi dei genitori biologici (il genitore può essere anche uno solo)
solo nell'annotazione compaiono i genitori (o il genitore) adottante
nell'estratto la annotazione sarà sempre certificabile
E' necessario aggiornare il caso d'uso per gestire due ulteriori sezioni madre e padre biologiche**

**Comment by asqueglia** [comment]
Buongiorno la segnalazione è stata corretta con la versione 1.35.0
