### ISSUE TITLE
[SC]: Mancanza notifica di trascrizione atto di morte

### ISSUE THREAD

**Issue by LucaBonini64** [italia/ansc#1150]
### Ambiente

pre-produzione

### Servizio

R008 - Servizi cooperativi notifiche

### idOperazione

2760254

### idEvento o idAnsc

2024-3714702-42-006114

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Novi Ligure

### Data del test (yyyy-mm-dd)

2024-11-12

### Descrivi il problema

Eseguendo a Novi Ligure un atto di morte con useCase 2102 di una cittadina residente in Cannobio (non subentrato in ANSC) e nata a Pisa (in ANSC) con atto cartaceo riceviamo come notifiche esclusivamente la notifica "Annotazione automatica id 2024-3714703-00000-006114 ( da inviare via PEC )" per l'annotazione sull'atto di nascita.
1) dalla 'Guida all'utilizzo nel periodo di adesione progressiva' mi aspettavo di ricevere anche la copia dell'atto di morte per la trascrizione da inviare via PEC (cap. 6.2 caso D2) mentre questo non è avvenuto.
2) è vero che l'atto di nascita è cartaceo, ma il comune dell'atto di nascita è in ANSC, la notifica dell'annotazione automatica non doveva andare direttamente a Pisa come da figura 3 dei flussi di conferma notifiche?
Per il punto due posso immaginare che valga solo se l'atto di nascita è digitale, anche se capirete che il giro delle PEC sembra un appesantimento del procedimento, mentre per il punto uno ditemi se sto sbagliando qualcosa.
Grazie

### Come riprodurre il problema

1. Inserito atto di morte come indicato sopra
2. Inserita data validità evento con servizio R014
3. Eseguita ricerca notifiche con servizio R008

**Comment by asqueglia** [comment]
Buon pomeriggio, 
Per il punto 1. verifichiamo e le facciamo sapere
Per il punto 2. comunichiamo che attualmente tutti gli atti cartacei sono gestiti allo stesso modo (indipendentemente se il comune è subentrato in ANSC o meno); per tutti gli atti cartacei il sistema invia le notifiche relative alle proposte di annotazione, al comune di formazione dell'atto sorgente da cui scaturiscono le annotazioni. L'evolutiva segnalata è prevista per il prossimo anno.
Chiudiamo pertanto la issue. In caso di dubbi o ulteriori incertezze preghiamo di aprire una issue dedicata.

**Comment by asqueglia** [comment]
Buon pomeriggio confermiamo che ad oggi le notifiche di presa visione dell'atto (ex trascrizione) vengono inviate al comune di residenza solo se il comune ha aderito, in caso contrario il tutto deve essere gestito extra flusso via PEC (compreso lo scarico dell'atto in formato pdf che può essere effettuato tramite la consultazione o anteprima atto. Eventuali evolutive in merito verranno valutate e analizzate per il prossimo anno.
Chiudiamo pertanto la issue. In caso di ulteriori dubbi si prega di aprire una issue dedicata.
