### ISSUE TITLE
[webapp]: Trasferimento in anagrafe cittadinanza

### ISSUE THREAD

**Issue by Hdemografici** [italia/ansc#1152]
### Ambiente

pre-produzione

### Provenienza segnalazione

Software House

### Riferimenti operatore/comune

Halley Informatica

### Data del test (yyyy-mm-dd)

13/11/2024

### Caso d'uso

52153

### Descrivi il problema

inserito direttamente tramite WA (Comune di Cartoceto) atto cittadinanza 2024-3614955-1-041010
caso uso 52153 - Trascrizione del decreto per matrimonio-unione civile-naturalizzazione-presentazione cittadino
in fase di chiusura dell'atto è stata impostata come data validità anagrafica 14/11/2024 
(nei casi di acquisto cittadinanza ai sensi art.5 o 9 Legge n.91/1992 l'ufficiale di stato civile redige 2 atti: giuramento e trascrizione del Decreto della Prefettura o del Presidente della Repubblica, solitamente redatti nella stessa data e la decorrenza giuridica dell'acquisto è il giorno dopo il giuramento, quindi la prova eseguita rappresenta un caso reale)

dopo aver chiuso l'atto approvo le notifiche lato stato civile
controllando poi le notifiche lato anagrafe troviamo già fin da oggi la notifica per l'aggiornamento anagrafico

è corretto che la notifica venga visualizzata il giorno prima rispetto alla data di validità anagrafica dell'evento o si tratta di caso da correggere?

**Comment by asqueglia** [comment]
Buon pomeriggio, si è corretto che la notifica venga inviata subito ma nei dati della notifica compare anche la data di decorrenza anagrafica, visionabile dall'USC che potrà quindi decidere come e quando effettuare la registrazione della corrispondente operazione anagrafica. L'operazione anagrafica non è automatica ma è solo notificata; è l'USC che deve poi prenderla in carico valutarla e registrarla.

Chiudiamo pertanto la issue. In caso di dubbi ulteriori si prega di aprirne una altra dedicata.
