### ISSUE TITLE
[webapp]: Annotazioni apposte su atti digitali formati da altro comune

### ISSUE THREAD

**Issue by dandreap** [italia/ansc#1153]
### Ambiente

pre-produzione

### Provenienza segnalazione

Comune

### Riferimenti operatore/comune

COMUNE DI TARCENTO-D'ANDREA PAOLA

### Data del test (yyyy-mm-dd)

2024-11-14

### Descrivi il problema

Ansc (webapp) permette che un comune apponga annotazioni sull'atto di stato civile formato da altro comune. Il test è stato eseguito sull'atto di nascita id ansc n.3715082 numero comunale 110 del comune di Duino-Aurisina e sull'atto di nascita id ansc 3515026 numero comunale 46 del comune di Udine.
Al comune di Udine e a quello di Duino non è arrivata alcuna notifica da gestire.  Negli estratti di nascita compare l'annotazione effettuata da questo comune.

**Comment by asqueglia** [comment]
Buon pomeriggio prendiamo in carico la segnalazione e le faremo sapere quanto prima

**Comment by asqueglia** [comment]
Buongiorno con la patch 1.34.5 è stata corretta la segnalazione. Chiudiamo pertanto la issue
