### ISSUE TITLE
[webapp]: Annotazioni certificazione internazionale

### ISSUE THREAD

**Issue by Hdemografici** [italia/ansc#1156]
### Ambiente

pre-produzione

### Provenienza segnalazione

Software House

### Riferimenti operatore/comune

Halley informatica - Cartoceto

### Data del test (yyyy-mm-dd)

14/11/2024

### Descrivi il problema

buon pomeriggio

si chiede di valutare il seguente caso:

da WA (Comune di Cartoceto)
inserito atto di nascita 2024-3715205-1-041010 (trascrizione dall'estero caso uso 1311)
ID ANSC soggetto 3427035
inseriti successivamente
-atto di matrimonio 2024-3715209-1-041010 (trascrizione dall'estero caso uso 332000) per stesso cittadino 3427035
-atto di divorzio  2024-3715213-2-041010 (trascrizione dall'estero caso uso 347000) per stesso cittadino 3427035

accettate le notifiche relative agli sopra elencati e quindi apposte annotazioni di matrimonio e divorzio su atto di nascita 2024-3715205-1-041010

utilizzando ora la funzione "rilascia certificato internazionale" e scegliendo "estratto atto nascita" per atto 2024-3715205-1-041010 si nota che:
-nella sezione "altre enunciazioni dell'atto" vengono riportati i testi delle annotazioni delle annotazioni di matrimonio e divorzio per intero e non nella forma contratta prevista dall'art. 5 della Convenzione Vienna 8 settembre 1976
-la WA prevede un'unica scelta nel campo "sigla" riguardo i simboli convenzionali correlati all'evento da annotare. Può capitare, come nel caso dell'atto di nascita preso come esempio, che in un atto siano annotati due o più eventi che prevedono una forma convenzionale stringata. La selezione del campo "sigla" dovrebbe essere caratterizzato da una scelta multipla in base alle annotazioni inserite nell'atto.

Con l'occasione si chiede se un Comune che ha aderito ad ANSC, in alcuni casi come quello in esame, possa procedere al rilascio del certificato internazionale utilizzando il testo proposto dalla software house, oppure debba necessariamente utilizzare il testo ANSC apportando le opportune modifiche.

art.5 Convenzione Vienna:
"Per indicare il matrimonio, la separazione legale, il divorzio, l’annullamento del
matrimonio, il decesso del titolare dell’atto di nascita come anche il decesso dei
marito o della moglie, sono utilizzati esclusivamente i seguenti simboli: Mar =
matrimonio; Sc = separazione legale; Div = divorzio; A = annullamento; D = decesso;
Dm = decesso del marito; Df = decesso della moglie. Questi simboli sono seguiti
dalla data e dal luogo dell’evento. Il simbolo «Mar» è anche seguito dal cognome e
dal nome del coniuge."

grazie per l'attenzione

**Comment by asqueglia** [comment]
Buongionro, approfondiremo la richiesta con gli esperti ANUSCA e le faremo sapere appena possibile.

**Comment by asqueglia** [comment]
A seguito di approfondimento con ANSUCA si conferma che verranno prese in carico le segnalazioni

**Comment by asqueglia** [comment]
Con il rilascio della versione 1.36.0, la segnalazione è stata corretta
