### ISSUE TITLE
[webapp]: Assistenza per annotazione su atto cartaceo a seguito di creazione atto digitale (separazione davanti USC)

### ISSUE THREAD

**Issue by rvinzani** [italia/ansc#1157]
### Ambiente

produzione

### Provenienza segnalazione

Comune

### Riferimenti operatore/comune

Gesturi

### Data del test (yyyy-mm-dd)

14/11/2024

### Descrivi il problema

Relativamente all'atto di nascita dei coniugi, condivido che l'annotazione da apporre è esclusivamente quella di divorzio. Ma il D.M. 9 dicembre 2014 di cui si allega specifica circolare introdusse, tra l'altro, la formula 175-quinques che prevede l'annotazione specifica per le separazioni innanzi l'ufficiale dello stato civile, a margine dell'atto di matrimonio. La stessa, mi risulta essere ancora vigente.
FORMULA 175-quinques Annotazione di separazione personale dei coniugi mediante accordo concluso innanzi all'ufficiale dello stato civile (articolo 12, decreto-legge 12 settembre 2014 n. 132, convertito, con modificazioni, dalla legge 10 novembre 2014 no 162, e articolo 49, primo comma, lettera gter, decreto del presidente della Repubblica 3 novembre 2000, no 396)
"Con accordo concluso innanzi all 'u.fficiale di stato civile del Comune di 00000, in data oooo, di cui all 'atto iscritto nei registri di matrimonio del predetto ujjicio dello stato civile, a! n. 000 0 parte 000 0 0 serie oo 0 00 , e confermato con dichiarazioni di cui all 'atto iscritto nei predetti registri, a! n. 000 0 parte 00 0 0 0 serie 0 00 0 0 , i coniugi (indicare le genera/ita dei coniugi) di cui a! matrimonio controscritto si sono separati."

**Comment by asqueglia** [comment]
riferita a #1155

**Comment by asqueglia** [comment]
Buongiorno la segnalazione è stata corretta con la versione 1.35.0
