### ISSUE TITLE
[SC]: Tipo accertamento "dichiarazione sostitutiva" non sempre consentito

### ISSUE THREAD

**Issue by migmar68** [italia/ansc#1159]
### Ambiente

pre-produzione

### Servizio

R009 - Servizi cooperativi validazione evento

### idOperazione

assente

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Maggioli

### Descrivi il problema

Nel fare diverse prove, abbiamo trovato un errore segnalato da ANSC quando la dichiarazione di nascita è fatta da sanitario : non accetta il valore 3 "dichiarazione sostitutiva" nel campo evento.datiDiNascita.Dettagli evento.Tipo Accertamento.
Non ci siamo segnati l'operazione perchè poi ci siamo persi nei vari controlli.

Abbiamo controllato sia la documentazione che la web app, e non capiamo come mai questo campo che a nostro avviso fa riferimento alla tabella decodifica 78 , dovrebbe limitare i valori ammessi.
Eppure nella web app, per i casi 11125000 e 11125100 i valori presentati nella combo tipo accertamento sono solo i primi due della tabella, è assente la "dichiarazione sostitutiva". Invece nel caso 11125200 (stesso caso d'uso ma bambino nato vivo e morto prima dich.nascita) la web app prevede correttamente tutti e 3 i casi.

Controllando il mapping dei casi d'uso, non vediamo nessuna nota per cui i valori del campo dovrebbero essere limitati.
Però notiamo che tra gli allegati, i casi d'uso 11125000 e 11125100 prevedono:
- Allegati	Attestazione di nascita
- Allegati	Constatazione di avvenuto parto

Mentre l'altro caso d'uso 11125200 , aggiunge un terzo allegato:
- Dichiarazione di nascita sostitutiva resa da dichiarante

Se la formulazione della web app è corretta, pensiamo sia da migliorare la documentazione nel mapping dei casi d'uso.
Ci sembra comunque strano un diverso comportamento del tipo di accertamento che è possibile presentare.

Aggiungo che controllando altre casistiche similari rileviamo questa differenza, senza capire un denominatore comune. Provo ad allegare un file limitato ai casi dove dichiara sanitario.
Potete verificare? grazie

**Comment by asqueglia** [comment]
ANUSCA conferma che è corretto consentire anche per un sanitario di inserire la dichiarazione sostitutiva; Prendiamo in carico la segnalzione

**Comment by asqueglia** [comment]
Buongiorno la segnalazione è stata corretta con la versione 1.35.0
