### ISSUE TITLE
Errore Testimone2- Caso d'uso 311111 Atti di Matrimonio

### ISSUE THREAD

**Issue by KibMcris** [italia/ansc#116]
Ambiente di pre-produzione 
la richiesta di validazione di un matrimonio civile celebrato nella casa comunale (caso d'uso 311111 Atti di Matrimonio) presenta un comportamento anomalo per quanto riguarda il Testimone2.

Infatti, se il Testimone2 risulta nato all'estero otteniamo in risposta il seguente messaggio di errore:

{"code":"400003","severity":"E","text":"Il campo evento.datiEventoMatrimonio.testimone2.idProvinciaNascita nella sezione Testimone 2 è obbligatorio"},{"code":"400003","severity":"E","text":"Il campo evento.datiEventoMatrimonio.testimone2.siglaProvinciaNascita nella sezione Testimone 2 è obbligatorio"}

Ad esempio è possibile vedere la seguente operazione.
idComune:10288,
idOperazioneComune:12,
dataOraRichiesta":"2023-05-17 16:02:09
idOperazione: 1590422
Valorizzando invece lo stesso cittadino nell'oggetto Testimone1 l'atto viene correttamente validato e registrato.

Vedere l'operazione
idComune:10288,
idOperazioneComune:12,
dataOraRichiesta:2023-05-17 16:03:21
idOperazione: 1590425

Se necessario possiamo fornire i file json.

**Comment by asqueglia** [comment]
Buongiorno, verifichiamo e le facciamo sapere

**Comment by asqueglia** [comment]
Buonasera, è stata rilasciata la versione 1.8.1 che dovrebbe risolvere la presente segnalazione. E' possibile riprovare.
