### ISSUE TITLE
[SC]: titolare con generalità diverse su atti diversi

### ISSUE THREAD

**Issue by antonioluberto** [italia/ansc#1166]
### Ambiente

pre-produzione

### Servizio

R009 - Servizi cooperativi validazione evento

### idOperazione

2805455

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Grottaferrata

### Data del test (yyyy-mm-dd)

20/11/2024

### Descrivi il problema

Su ambiente di pre-produzione del Comune di Grottaferrata abbiamo creato atto di matrimonio
2024-3716309-255-058046
sul quale lo sposo è
Cognome: RAMPONI
Nome: LUCIANO

Conclusa la redazione dell'atto di matrimonio, i soggetto titolari (sposo/a) presentano certamente ID_ANSC proprio; lo sposo ha, in particolare
ID_ANSC = 3430764.
Abbiamo quindi avviato, per il soggetto sposo, la redazione dell'atto di nascita per trascrizione dall'estero (Trascr_006); sull'atto di nascita il soggetto deve figurare con descrizione diversa del 
"Nome": ALEJANDRO LUCIANO
Siamo quindi nel caso in cui il medesimo individuo fisico debba figurare con generalità diverse su due atti diversi; immaginiamo che, per fare in modo che ANSC sappia che 
- lo sposo dell'atto 2024-3716309-255-058046
- il titolare dell'atto di nascita in redazione
sono il medesimo individuo, alla creazione dell'atto di nascita si debba da parte nostra valorizzare l'ID_ANSC del soggetto in esame)
Al tentativo di creazione dell'atto di nascita, in risposta all'invocazione del servizio R009 abbiamo però l'errore:
"Attenzione! I dati del soggetto intestatario con idANSC=3430764 inseriti non sono conformi ai dati anagrafici registrati".

C'è un errore da parte nostra?
E' qualcosa che deve ancora essere gestito/risolto lato ANSC?

Rimaniamo in attesa di vostro riscontro e naturalmente a disposizione.

**Comment by asqueglia** [comment]
Chiudiamo la issue. In caso di ulteriori dubbi si prega di aprire una discussion specifica
