### ISSUE TITLE
[SC]: modifica generalità titolare atto in fase di redazione

### ISSUE THREAD

**Issue by antonioluberto** [italia/ansc#1167]
### Ambiente

pre-produzione

### Servizio

R009 - Servizi cooperativi validazione evento

### idOperazione

2805778

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Grottaferrata

### Data del test (yyyy-mm-dd)

20/11/2024

### Descrivi il problema

Su ambiente di pre-produzione del Comune di Grottaferrata abbiamo creato l'atto di nascita
2024-3716326-257-058046
per il cui soggetto titolare si sono inizialmente indicate le generalità
Cognome: LICATA
Nome: MAURO.
Alla creazione dell'atto in ANSC (Stato ANSC: Confermato) al soggetto titolare è stato attribuito 
ID_ANSC = 3430818.

Supponiamo che a questo punto, prima della sottoscrizione da parte dei dichiaranti, l'usc si accorga di aver sbagliato l'indicazione del nome e corregga quindi quest'ultima in: BERNARDO MAURO.

Ci aspetteremmo di poter reinviare l'atto in ANSC indicando per il titolare:
a) nome aggiornato
b) ID_ANSC = 3430818
così che, una volta concluso con successo il secondo invio, in ANSC 
- per il soggetto con ID_ANSC = 3430818, risulti aggiornata l'indicazione relativa al "nome" 
- l'atto di nascita presenti tutti i metadati correttamente aggiornati
In effetti però, se procediamo al secondo invio attenendoci alle ipotesi di cui ai punti a) e b) sopra, dal servizio R009 abbiamo errore:

{"testataRisposta":{"idComune":4559,"idOperazioneComune":"32a498eb-2c7c-4399-99cc-ace312fb3b8f","idOperazione":"2805778","idEsito":1},"errors":[{"code":"500","severity":"E","text":"Errore interno"}],"infos":[{"code":"110527","severity":"I","text":"Informazioni sull'operazione da fornire in caso di assistenza : data:2024-11-20 15:45:22 , idOperazione:2805778"}],"idEvento":"3716326","idTipoEvento":"1","idAnsc":"2024-3716326-257-058046"}.

Provando altro casi analoghi, abbiamo verificato che se al secondo invio non si riporta, nell'invocazione del servizio R009, l'ID_ANSC attribuito inizialmente al soggetto titolare, l'operazione va a buon fine; ci sorge però il sospetto che in questo caso l'anagrafica venga duplicata (non aggiornata) e che questo si traduca nella presenza di anagrafiche non associate ad alcun evento.

Potreste darci indicazioni su quale sia il modo corretto di procedere e se vi siano evoluzioni/correzioni su vostra pianificazione in merito?

**Comment by asqueglia** [comment]
Buon pomeriggio, il comportamento descritto in questo caso è sicuramente un errore; provvediamo a verificare le faremo sapere il prima possibile

**Comment by asqueglia** [comment]
Buongiorno la segnalazione è stata corretta con la versione 1.35.0
