### ISSUE TITLE
[SC]: Ricerca intestatario: incongruenza campo comune nascita estero

### ISSUE THREAD

**Issue by siscomanpr** [italia/ansc#1169]
### Ambiente

pre-produzione

### Servizio

R005 - Servizi cooperativi consultazione

### idOperazione

2812162

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Serravalle Sesia

### Data del test (yyyy-mm-dd)

21/11/2024

### Descrivi il problema

Abbiamo rilevato che la ricerca per intestatario non restituisce il campo del nome della località estera per i soggetti nati all'estero.

E' stato registrato un evento di matrimonio per un soggetto (id=3431433) dove è stato indicato come "localitaEsteraNascita": "CORDOBA". 
Consultando l'evento, nel blocco degli intestatari, riceviamo il campo "localitaEsteraNascita" correttamente valorizzato a "CORDOBA".
Se invece tentiamo di effettuare una consultazione per intestatario con il servizio R005 (idOperazione=2812162) come risposta riceviamo il soggetto con solo il nome dello stato estero, ma senza il campo della località estera di nascita impostato.

Abbiamo quindi provato a fare la stessa ricerca per intestatario tramite la web app, indicando come parametro solo l'IDANSC del soggetto, e qui viene compilato anche il campo della località estera di nascita CORDOBA (vedi immagine)

![image](https://github.com/user-attachments/assets/6308d598-cfda-452d-bd8f-1c9588ffeed4)

E' possibile sanare questa differenza di comportamento restituendo anche tramite i SC il nome della località estera di nascita?

Restiamo in attesa di un riscontro.
Grazie per l'attenzione.

Siscom SPA

### Payload (json)

```JSON
REQUEST
{
    "criteriRicercaSoggetto": {
        "idAnscSoggetto": "3431433"
    },
    "testataRichiesta": {
        "idComune": 9419,
        "idOperazioneComune": "202400000000000000000000079767",
        "dataOraRichiesta": "2024-11-21T15:43:36.8631935+01:00",
        "nomeApplicativo": "xxxxxxxxx",
        "versioneApplicativo": "xxxxxxxxx",
        "fornitoreApplicativo": "SISCOM"
    }
}

RESPONSE
{
    "testataRisposta": {
        "idComune": 9419,
        "idOperazioneComune": "202400000000000000000000079767",
        "idOperazione": "2812162",
        "idEsito": 0
    },
    "datiPaginazione": {
        "numPagina": 1,
        "numRecordPagina": 30,
        "numRecordTotali": 1
    },
    "infos": [
        {
            "code": "110527",
            "severity": "I",
            "text": "Informazioni sull'operazione da fornire in caso di assistenza : data:2024-11-21 14:43:43 , idOperazione:2812162"
        }
    ],
    "soggetti": [
        {
            "id": "3431433",
            "codiceFiscale": "",
            "cognome": "FERNANDEZ",
            "nome": "MARIA",
            "sesso": "F",
            "dataNascita": "1984-11-11",
            "idStatoNascita": "8",
            "nomeStatoNascita": "ARGENTINA",
            "idStatoResidenza": "",
            "documentoRiconoscimento": {}
        }
    ]
}
```

**Comment by asqueglia** [comment]
Buon pomeriggio, prendiamo in carico la segnalazione. Faremo sapere appena possibile

**Comment by asqueglia** [comment]
Buongiorno la segnalazione è stata corretta con la versione 1.35.0
