### ISSUE TITLE
Anteprima - Errore "Dati in ingresso non corretti"

### ISSUE THREAD

**Issue by KibMcris** [italia/ansc#117]
ambiente di pre-produzione

Per l'atto ID 952343 di morte- Caso d'uso di servizio (trascrizioni di morte) 2299-  otteniamo in risposta alla richiesta di anteprima l'errore seguente:
{"testataRisposta":{"idComune":10288,"idOperazioneComune":"11","idOperazione":"1590416","idEsito":1},"errors":[{"code":"400003","severity":"E","text":"Dati in ingresso non corretti"}]}

Successivamente però riusciamo a confermare e sottoscrivere correttamente l'atto.

Accedendo alla Web App abbiamo notato che cliccando su "Visualizza Atto" il sistema risponde con errore "Errore di connessione
Richiesta fallita codice errore 500".

Per l'atto invece ID 952344 di morte-  Caso d'uso di servizio (trascrizioni di morte) 2299- non abbiamo ottenuto errori in risposta e siamo riusciti a visualizzare l'anteprima.

Confrontando i file di richiesta non abbiamo rilevato differenze.

Potete darci qualche indicazione?
Grazie

**Comment by amusarra** [comment]
Salve @KibMcris siamo riusciti a replicare l'anomalia e presa in gestione.

Saluti.
Supporto ANSC

**Comment by KibMcris** [comment]
Salve @amusarra, segnalo che otteniamo lo stesso errore anche nel caso d'uso 51103- Straniero nato in Italia che vi abbia risieduto legalmente senza interruzioni fino alla maggiore età. 
Validando il modello, ANSC risponde correttamente con il seguente messaggio:

{"testataRisposta":{"idComune":10288,"idOperazioneComune":"12","idOperazione":"1590891","idEsito":0},"idEvento":"952384","idTipoEvento":"5","idAnsc":"2023-952384-1-102044"}

Alla richiesta di visualizzazione dell'anteprima però otteniamo l'errore:
"testataRisposta":{"idComune":10288,"idOperazioneComune":"11","idOperazione":"1590885","idEsito":1},"errors":[{"code":"400003","severity":"E","text":"Dati in ingresso non corretti"}]}.

Provando ad andare comunque avanti non riusciamo, in questo caso, a scaricare il processo verbale per la sottoscrizione dato che in risposta otteniamo l'errore:
{"testataRisposta":{"idComune":10288,"idOperazioneComune":"11","idOperazione":"1590887","idEsito":1},"errors":[{"code":"400003","severity":"E","text":"Dati in ingresso non corretti"}]}.

Rimaniamo in attesa di un riscontro
Grazie

**Comment by amusarra** [comment]
Salve @KibMcris quanto segnalato rientra nello stesso BUG che abbiamo preso in carico.

Saluti.
Supporto ANSC.

**Comment by asqueglia** [comment]
Buongiorno con la versione 1.9.0 appena rilasciata abbiamo corretto l'errore. E' possibile riprovare. chiudiamo la issue in caso vi preghiamo di riaprirla.

**Comment by KibMcris** [comment]
Buongiorno confermo che per il caso d'uso -Caso d'uso di servizio (trascrizioni di morte) 2299 funziona adesso correttamente come da atto ID 953259.

Abbiamo riprovato anche il caso d'uso 51103- Straniero nato in Italia che vi abbia risieduto legalmente senza interruzioni fino alla maggiore età con ID Atto 953260.
In questo caso però, riusciamo a validare correttamente l'atto, otteniamo in risposta alla richiesta di visualizzazione dell'anteprima il seguente errore:

HTTP Status 400 
{"testataRisposta":{"idComune":10288,"idOperazioneComune":"11","idOperazione":"1595862","idEsito":1},"errors":[{"code":"400003","severity":"E","text":"Dati in ingresso non corretti"}]}

Entrando nella WEB APP di ANSC, entrando in editazione dell'atto, il sistema risponde con errore "Errore di connessione
Richiesta fallita codice errore 500".

**Comment by amusarra** [comment]
Salve @KibMcris 
Abbiamo effettivamente rilevato dall'analisi dei log del sistema l'errore specifico segnalato che sembra dovuto a `documentoRiconoscimento.tipologiaDocumento`.

Riapriamo questa issue e prendiamo in carico.

Cordiali Saluti.
Supporto ANSC.

**Comment by asqueglia** [comment]
Buongiorno confermiamo che con il rilascio della versione 1.9.1 la segnalazione è stata corretta. E' possibile riprovare. Chiudiamo la issue, nel caso la preghiamo di riaprirla.
