### ISSUE TITLE
[webapp]: casistica [1.1.1.1.2.2.0.0] Dichiarazione nei termini di filiazione nel matrimonio resa dalla madre all'usc di bimbo nato vivo ma morto prima della denuncia di nascita

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#1171]
### Ambiente

pre-produzione

### Provenienza segnalazione

Software House

### Riferimenti operatore/comune

 anna maraspin, ponsacco

### Data del test (yyyy-mm-dd)

2024-11-25

### Caso d'uso

1.1.1.1.2.2.0.0

### Descrivi il problema

Ho compilato tutti i campi e introdotto gli allegati

![image](https://github.com/user-attachments/assets/731956fa-1208-448d-ae3a-3e22cf53eae4)

al momento di validare l'atto esce questo (la region INTERPRETE non viene visualizzata giustamente in quanto le parti comprendono la lingua)

![image](https://github.com/user-attachments/assets/8b4706bd-87b4-403f-a6c0-801c029cb69e)

**Comment by asqueglia** [comment]
Buon pomeriggio, verifichiamo e le facciamo sapere. Da test interni non siamo al momento riusciti a replicare la problematica.

**Comment by annamaraspin** [comment]
Ho riprovato per scrupolo
sia prendendo quello in bozza (id 3716752) che facendone uno da zero pochi secondi fa (3716947).

**Comment by annamaraspin** [comment]
Buongiorno,
sistema operativo 	Windows 11 Pro  Versione	23H2
accedo tramite Edge, clicco su CNS, scelgo il mio codice fiscale, poi sulla postazione di Ponsacco.
Sul pannellino di servizi attivi vado in Stato Civile, tendina "nascita" dove scelgo le dichiarazioni.
I dati scelti lungo il percorso li avete nel ticket originale. Non credo che dipenda dai dati inseriti nelle regioni del padre, madre, etc.

**Comment by asqueglia** [comment]
Buongiorno, gentilmente potrebbe fare lo stesso test aprendo la pagina del browser in modalità incognito ?
![image](https://github.com/user-attachments/assets/ccfd98ed-395f-4f2c-9b82-2617b7ade874)

Vorrei capire se la problematica è legata alla cache. Grazie mille. Purtroppo non riusciamo a replicare il problema .

**Comment by annamaraspin** [comment]
Buongiorno,
riprovato in incognito.
Al valida dell'evento

![image](https://github.com/user-attachments/assets/39c18fa2-9e4f-49d5-9e2f-80acaf56295f)


In questi giorni stavo provando vari atti sulla webapp (soprattutto quelli multi intestatari ) : non riesco a portar a termine nessuno per errori simili a questo (vedi anche il ticket che ha chiuso con una soluzione impossibile visto che si tratta di webapp #1185).
Questo problema è almeno dalle ultime due versioni, prima mai successo.

**Comment by asqueglia** [comment]
Buonasera, malgrado non siamo riusciti a replicare la casistica abbiamo rilasciato una fix che speriamo risolva il problema. Potrebbe farci sapere se adesso le funziona  ?

**Comment by annamaraspin** [comment]
Buongiorno,
adesso  funziona se comincio un atto nuovo da zero.  Però se riprendo quelli già iniziati oggetto del ticket: la validazione viene sempre bloccata per gli stessi errori.
