### ISSUE TITLE
[SC]: cambiamento del nome e cognome a seguito di notifica ANSC

### ISSUE THREAD

**Issue by Hdemografici** [italia/ansc#1172]
### Ambiente

pre-produzione

### Servizio

R008 - Servizi cooperativi notifiche

### idOperazione

s4005:2210258 (idnotifica)

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Halley informatica 

### Descrivi il problema

ambiente Pre-produzione 
cittadino residente nel comune A (Colli al Metauro)  iscritto per nascita con atto ANSC del comune A (caso uso 1.1.2.1.2.0.0.2).
Successivamente nel comune B viene redatto un atto ANSC per modificare le generalità del cittadino (caso uso 1.3.3.1), nel caso specifico il cognome.
Tramite notifica ricevo i dati originali e non i dati modificati, per poter leggere i dati modificati dovrei utilizzare il servizio R005.
Questo passaggio è un problema, l'operatore di anagrafe potrebbe non avere le necessarie abilitazioni per consultare ANSC soprattutto nei comuni dove gli uffici di anagrafe e stato civile sono separati.

idNotifica letta tramite s4005:2210258
idAnsc per atto cambio cognome:2024-3514964-6-041010 (Cartoceto)
idAnsc nascita originale:2024-3514963-351-041069 (Colli al Metauro)

**Comment by gbuemi** [comment]
Buonasera,
faremo in modo di inoltrare le informazioni richieste, seguiranno aggiornamenti.

Un saluto,
Supporto ANSC

**Comment by asqueglia** [comment]
Buongiorno la segnalazione è stata corretta con la versione 1.35.0
