### ISSUE TITLE
Atto di matrimonio con impedimenti alla firma

### ISSUE THREAD

**Issue by ANPRCdMI** [italia/ansc#1175]
### Ambiente

pre-produzione

### Provenienza segnalazione

Software House

### Riferimenti operatore/comune

Comune di Milano

### Data del test (yyyy-mm-dd)

2024-11-27

### Caso d'uso

311111

### Descrivi il problema

Predisponendo un atto di matrimonio di rito civile, sia in casa comunale che fuori, selezionando un motivo di impedimento comprensione sposo e/o sposa, il testo dell'atto non viene compilato

Vedere bozza 3717727

### Come riprodurre il problema

1. Selezionare Matrimonio - evento rito civile - non su delega altro comune - in casa comunale - senza riconoscimento figli
2. Comprensione sposo e/o sposa = una condizione diversa da "Nulla da segnalare"
3. Compilare quadro "Dati generali" e cliccare bottone "Salva dati"
4. Nel riquadro "Composizione" non appare il testo dell'atto

**Comment by amusarra** [comment]
Salve @ANPRCdMI 
Abbiamo preso in carico la vostra segnalazione.

Cordiali Saluti.
Supporto ANSC.
