### ISSUE TITLE
[webapp]: Sindaco firmatario atto cittadinanza

### ISSUE THREAD

**Issue by Hdemografici** [italia/ansc#1176]
### Ambiente

pre-produzione

### Provenienza segnalazione

Software House

### Riferimenti operatore/comune

Halley informatica

### Caso d'uso

51106

### Descrivi il problema

buongiorno,
in riferimento al caso di acquisto cittadinanza ai sensi art. 5 o 9 Legge n.91/1992, si procede alla redazione dell'atto di giuramento (caso uso 51106 / 51107) e trascrizione del decreto (caso uso 52153)

in questi casi può capitare che l'atto venga preparato dal funzionario operativo/Ufficiale di stato civile delegato e poi firmato dal Sindaco come Ufficiale di stato civile nell'ambito di una cerimonia di conferimento/concessione della cittadinanza italiana 

solitamente il Sindaco non segue direttamente le operazioni di redazione dell'atto e non avrebbe di base quindi un profilo abilitato alla redazione degli atti, si chiede quindi il seguente parere:

è possibile/legittimo pensare di introdurre per questi casi d'uso un funzionamento assimilabile a quello della flag "firmatario" posto nella sezione "Officiante" in fase di redazione di matrimonio civile (es. caso uso 31111)? 
In modo che il sindaco possa apporre propria firma cartacea insieme al comparente, poi in un secondo momento l'atto verrebbe chiuso da funzionario comunale operativo/Ufficiale di stato civile delegato.
Oppure l'iter di redazione dell'atto dovrebbe necessariamente essere gestito con l'autenticazione del Sindaco censito anch'esso come utente operativo?

grazie per l'attenzione

**Comment by asqueglia** [comment]
Buongiorno, comunichiamo che è prevista per fine dicembre, l'a attività che consentirà proprio la firma in differita del sindaco nella prestazione di giuramento della cittadinanza. Vi comunicheremo il rilascio dell'attività su questa issue.

**Comment by asqueglia** [comment]
Buongiorno con la versione 1.36.0 è stata effettuata l'attività richiesta. Chiudiamo pertanto la issue
