### ISSUE TITLE
[SC]: Rilascio certificazione come copia integrale dell'atto - errore interno in risposta

### ISSUE THREAD

**Issue by LucaBonini64** [italia/ansc#1180]
### Ambiente

pre-produzione

### Servizio

R002 - Servizi cooperativi certificazioni

### idOperazione

2851958

### idEvento o idAnsc

2024-3517437-31-006114

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Novi Ligure

### Data del test (yyyy-mm-dd)

2024-11-29

### Descrivi il problema

Inserendo una richiesta di copia integrale otteniamo anche per atti diversi sempre la risposta:
"code": "500", "severity": "E", "text": "Errore interno"

### Come riprodurre il problema

1. Si esegue la richiesta di un certificato con idTipoCertificato=3
2. Il certificato viene richiesto come Ente in quanto da utilizzare per invio come copia integrale ad altro ente

### Payload (json)

```JSON
{
	"idAnsc": "2024-3517437-31-006114",
	"enteRichiedente": {
		"nomeEnte": "COMUNE DI NOVI LIGURE",
		"idComuneEnte": "6498",
		"nomeComuneEnte": "NOVI LIGURE",
		"siglaProvinciaEnte": "AL",
		"nazioneEnte": "90",
		"nomeNazioneEnte": "ITALIA",
		"indirizzoEnte": "VIA PAOLO GIACOMETTI 22"
	},
	"intestatario": {
		"id": "3234770"
	},
	"idTipoCertificato": "3",
	"conPaternitaMaternita": false,
	"usoMatrimonio": false,
	"testataRichiesta": {
		"idComune": 6498,
		"idOperazioneComune": "LB1804",
		"dataOraRichiesta": "2024-11-29T10:59:38.98576+01:00",
		"nomeApplicativo": "hyperSIC.StatoCivile",
		"versioneApplicativo": "9.23.22.00.1M02",
		"fornitoreApplicativo": "APKAPPA S.r.l."
	}
}
```

**Comment by asqueglia** [comment]
Buon pomeriggio, abbiamo analizzato il payload della richiesta; se inserite nella sezione enteRichiedente anche l'id della provincia il servizio risponde correttamente. Provvederemo comunque a gestire l'errore riscontrato.
Di seguito un esempio:

 _"enteRichiedente": {
        "nomeEnte": "COMUNE DI NOVI LIGURE",
        "idComuneEnte": "6498",
        "nomeComuneEnte": "NOVI LIGURE",
        "idProvinciaEnte": "6",
        "siglaProvinciaEnte": "AL",
        "nazioneEnte": "90",
        "nomeNazioneEnte": "ITALIA",
        "indirizzoEnte": "VIA PAOLO GIACOMETTI 22"
    },_

**Comment by asqueglia** [comment]
Con il rilascio della versione 1.36.0, la segnalazione è stata corretta
