### ISSUE TITLE
[webapp]: Mancata creazione notifiche anagrafiche

### ISSUE THREAD

**Issue by MoniaPedrazzoli** [italia/ansc#1181]
### Ambiente

pre-produzione

### Provenienza segnalazione

Software House

### Riferimenti operatore/comune

Monia Pedrazzoli

### Data del test (yyyy-mm-dd)

28/11/2024

### Descrivi il problema

Buongiorno, abbiamo inserito per il comune 018005 l'atto di nascita con ID 3717966 relativo a soggetti residenti nel comune, ma non abbiamo ricevuto alcuna notifica anagrafica nella webapp ANPR (non ci sono nemmeno notifiche ANSC di cui prendere visione). 
La richiesta di abilitazione all'ambiente di pre-produzione ANSC per questo comune risale a ieri, potete controllare se risulta censito correttamente? Scaricando la tabella 110 sembrerebbe di no. 
Ci servirebbe lo stesso controllo anche per il comune 033040.
Grazie

**Comment by asqueglia** [comment]
Buongionro, verifichiamo e le facciamo sapere appena possibile

**Comment by asqueglia** [comment]
Buongiorno, i comuni effettivamente non erano censiti per cui abbiamo provveduto da centro a inserire la dichiarazione di adesione. Per riprovare il test dovete rifare l'atto ex novo. Chiudiamo pertanto la issue. In caso di ulteriori problematiche si prega di aprire una issue dedicata.
