### ISSUE TITLE
[SC]: Ordine firmatari atto unione civile - caso d'uso 411111

### ISSUE THREAD

**Issue by siscomanpr** [italia/ansc#1182]
### Ambiente

produzione

### Servizio

R010 - Servizi cooperativi anteprima

### idOperazione

vari

### idEvento o idAnsc

35121

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Magliano Alpi

### Data del test (yyyy-mm-dd)

29/11/2024

### Descrivi il problema

Per conto del comune di Magliano Alpi, si segnala che in fase di Anteprima di un evento di Unione civile per presa visione (modalità di firma cartacea dei dichiaranti), l'ordine dei firmatari è errato. 
L'ideale sarebbe che venissero ordinati nel seguente modo:
Soggetto 1
Soggetto 2
Testimone 1
Testimone 2
Officiante

Invece attualmente il PDF generato elenca i firmatari con un ordinamento che sembra casuale.

Tra l'altro l'impiegata del comune ha notato che, se l'anteprima viene fatta più volte, l'ordine in cui compaiono i firmatari non è sempre lo stesso da una volta all'altra. 
Allego 2 immagini che mostrano i diversi ordinamenti dei firmatari rilevati:

![image](https://github.com/user-attachments/assets/1a61b3b7-aac8-4a61-af89-95319c593506)

![image](https://github.com/user-attachments/assets/eb4415c9-e7d7-4a0e-8445-023736fa8a07)

Se può aiutare, i 2 soggetti che si sono uniti sono FRANCESCA e TERESA

Restiamo in attesa di un riscontro.

Siscom SPA

**Comment by asqueglia** [comment]
Buongiorno, prendiamo in carico la segnalazione e le facciamo sapere non appena possibile.

**Comment by asqueglia** [comment]
Con il rilascio della versione 1.36.0, la segnalazione è stata corretta
