### ISSUE TITLE
[webapp]: [5.2.8.2.1] Trascrizione atti multipli cittadinanza

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#1185]
### Ambiente

pre-produzione

### Provenienza segnalazione

Software House

### Riferimenti operatore/comune

 anna maraspin, ponsacco

### Data del test (yyyy-mm-dd)

2024-12-02

### Caso d'uso

5.2.8.2.1

### Descrivi il problema

Buongiorno,
ho effettuato queste scelte
![image](https://github.com/user-attachments/assets/19c11029-2257-49cf-8cad-1f20c8340666)

Ho compilato tutti i campi obbligatori ed inserito l'allegato obbligatorio

Al momento del valida atto
![image](https://github.com/user-attachments/assets/da8399f6-37a8-49df-bdaf-a59b05df18c0)

Atto salvato in bozza con id 3813310)

**Comment by asqueglia** [comment]
Buongiorno, il problema dipende dal fatto che non è stato trasmesso nel payload il dato tipo richiedente che è obbligatorio; nel suo caso trattandosi di privato è necessario trasmettere "idTipoRichiedente": 1 come da esempio sotto indicato

 "richiedente": {
            "idTipoRichiedente": 1,
            "privato": {
                "nome": "PROVA",
                "flagDichiarante": true,
                "flagComparente": false,
                "flagFirmatario": true,
                "documentoRiconoscimento": {},
                "flagIrreperibile": false
            }

Chiudiamo pertanto la issue.

**Comment by annamaraspin** [comment]
il tipo richiedente l'ho selezionato altrimenti come avrei potuto arrivare fino a quel punto? 

![image](https://github.com/user-attachments/assets/734004cc-c33c-434f-abfe-91591e13acd9)
