### ISSUE TITLE
[SC]: Assenza degli estremi dell'Atto, nell'Annotazione automatica (caso d'uso 52143: Citt_004).

### ISSUE THREAD

**Issue by gcuci** [italia/ansc#1187]
### Ambiente

produzione

### Servizio

R010 - Servizi cooperativi anteprima

### idOperazione

assente

### idEvento o idAnsc

2024-34939-00000-036005

### Provenienza segnalazione

Comune

### Comune di riferimento e operatore

Carpi

### Data del test (yyyy-mm-dd)

2024-11-27

### Descrivi il problema

Buongiorno,

il Comune di Carpi, ci ha segnalato l'assenza del riferimento all'Atto di Cittadinanza di Trascrizione, nell'Annotazione automatica, acquisita tramite Notifica, per il caso d'uso 'Trascrizione: Figlio minore di chi ha acquista la cittadinanza italiana' (id: 52143; cod: Citt_004).

Per un esempio, potete far riferimento alla Notifica con ID: 18221532, relativa all'Annotazione automatica con idAnsc: 2024-34939-00000-036005.

In attesa di riscontro,

cordiali saluti.

**Comment by asqueglia** [comment]
Buongiorno, verifichiamo e le facciamo sapere.

**Comment by asqueglia** [comment]
Buongiorno, nell'annotazione automatica è stato riportato il numero dell'atto originale che poi è stato trascritto. E' necessario riportare invece l'identificativo ANSC dell'atto trascritto che ha generato l'annotazione 2024-34938-521-036005, è corretto ?

**Comment by gcuci** [comment]
Non esattamente. Il testo generato resta valido, bisogna aggiungere, dopo il punto, quest'altra frase:
'Atto di cittadinanza del Comune di <nomeComune> con numero <idAnscAttoTrascritto>'.

**Comment by gcuci** [comment]
Specifico meglio:
'Atto di cittadinanza del Comune di --nomeComune-- con numero --idAnscAttoTrascritto--'.

**Comment by asqueglia** [comment]
Buongiorno, la formula applicata è

**FORM. 140-sexies Annotazione dell'attestazione relativa all'acquisto, alla perdita o al 
riacquisto della cittadinanza italiana (art. 16, ottavo comma del D.P.R. 12 ottobre 1993, n. 572 
e art. 49, primo comma, lett. i) del D.P.R. 3 novembre 2000, n. 396).**
Con atto del … (indicare l'Autorità che ha effettuato l'attestazione) in data … n. … ha attestato che 
… (nome e cognome) è (o: non è) cittadino italiano.

per qualsiasi modifica o aggiunta rispetto al formulario vigente, dobbiamo fare un passaggio con ANUSCA. Provvederemo a chiedere chiarimenti e le faremo sapere

**Comment by asqueglia** [comment]
Buongiorno, da un approfondimento ANUSCA conferma che nella formula va riportato l’idAnsc dell’atto trascritto; gli estremi dell’attestazione non vanno riportati. Procederemo quindi in tal senso.

**Comment by asqueglia** [comment]
Con il rilascio della versione 1.36.0, la segnalazione è stata corretta
