### ISSUE TITLE
[SC]: Verifica Stato Allegati - Restituisce sempre stato 1

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#1188]
### Ambiente

pre-produzione

### Servizio

R001 - Servizi cooperativi allegati

### idOperazione

2864787

### idEvento o idAnsc

-

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Lissone - biadanpad

### Data del test (yyyy-mm-dd)

2024-12-04

### Descrivi il problema

Il servizio di verifica dello stato dell'allegato risponde sempre con stato = 1.
Lo stesso problema si riscontra in WebApp

**Comment by asqueglia** [comment]
Buongiorno, verifichiamo e le facciamo sapere

**Comment by mttfranci** [comment]
Salve l'allegato che avete indicato nella richiesta sembra in stato 3 al momento.
Potete verificare nuovamente?
Forse è stato solo un rallentamento temporaneo.

**Comment by biadanpad** [comment]
Adesso sembra funzionare di nuovo regolarmente.

Il problema si era verificato già ieri nel tardo pomeriggio.
