### ISSUE TITLE
[webapp]: Verifica stato allegato - sempre "In attesa..."

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#1189]
### Ambiente

pre-produzione

### Provenienza segnalazione

Software House

### Riferimenti operatore/comune

Lissone - biadanpad

### Data del test (yyyy-mm-dd)

2024-12-04

### Caso d'uso

tutti

### Descrivi il problema

La verifica dello stato degli allegati risponde sempre "In caricamento..."
Lo stesso problema si riscontra nei Servizi Cooperativi

**Comment by asqueglia** [comment]
Buongiorno, verifichiamo e le facciamo sapere

**Comment by mttfranci** [comment]
Salve @biadanpad , il problema persiste? 
Inoltre anche se valesse per tutti, vi preghiamo di fornire sempre almeno un caso di riferimento.

Saluti

**Comment by biadanpad** [comment]
Adesso sembra funzionare di nuovo regolarmente.

Il problema si era verificato già ieri nel tardo pomeriggio.
