### ISSUE TITLE
[R008] - Errore invocazione servizi

### ISSUE THREAD

**Issue by ManuelDeMeo** [italia/ansc#119]
Ambiente: pre-produzione
Data test: 18/05/2023
IdOperazione: "1590744",""1590745", "1590748"

Buongiorno, provando ad invocare gli endpoint del servizio R008:
/notifiche/ricerca/
/notifiche/getNotificheByEvento/

Otteniamo il seguente errore in risposta:
"403002","E", "L'utente non e' autorizzato ad usare la funzione selezionata"

Potete usare come riferimento gli IdOperazione forniti in richiesta

**Comment by gcuci** [comment]
buongiorno,

anche a noi il servizio restituisce lo stesso errore.

idOperazione: 1590845.

**Comment by amusarra** [comment]
Buongiorno @ManuelDeMeo e @gcuci
Abbiamo preso in carico la segnalazione e siamo in fase di verifica.

**Comment by amusarra** [comment]
Buon pomeriggio @ManuelDeMeo e @gcuci 
Per quanto riguarda l'endpoint `/notifiche/getNotificheByEvento/` non è un servizio da utilizzare nel normale flusso delle notifiche e nei prossimi rilasci dovrebbe essere anche rimosso.

Il servizio per di ricerca per notifiche tra i comuni è `{{R008}}/notifiche/ricerca/`.
Prendendo in esame lo specifico payload dell'idOperazione 1590748 e invocandolo con una nostra utenza, il servizio risponde correttamente.

```json
    "criteriRicercaNotifiche": {
        "dataInizio": "2023-05-1",
        "dataFine": "2023-05-18",
        "idAnsc": null,
        "idTipoEvento": null,
        "idTipoContenuto": null,
        "soggettoRicerca": null
    }
```
Payload Request R008 - idOperazione 1590748

```json
{
    "testataRisposta": {
        "idComune": 580,
        "idOperazioneComune": "APP2022032210000",
        "idOperazione": "1591293",
        "idEsito": 0
    },
    "notifiche": [
        {
            "idAnsc": "2023-952391-4323449-999999",
            "idComuneFormazione": "1000000",
            "idComuneCompetente": "580",
            "idSoggettoRif": "1933450",
            "dataInizioValidita": "2023-05-18 14:55:00.0",
            "dataFineValidita": "2023-06-17 14:55:00.0"
        },
        {
            "idAnsc": "2023-952390-4323447-999999",
            "idComuneFormazione": "1000000",
            "idComuneCompetente": "580",
            "idSoggettoRif": "1933450",
            "dataInizioValidita": "2023-05-18 14:48:00.0",
            "dataFineValidita": "2023-06-17 14:48:00.0"
        }
    ]
}
```
Payload Response R008

In genere l'errore indicato `"403002","E", "L'utente non e' autorizzato ad usare la funzione selezionata"` deriva dal fatto che idComune specificato sul payload con coincida con il valore specificato sul token JWT.

Invitiamo a fare questo controllo. Nel frattempo chiudiamo la issue, in caso di necessità riaprite senza alcun problema.

Cordiali Saluti.
Supporto ANSC.

**Comment by gcuci** [comment]
Abbiamo provato con il servizio di ricerca (.../notifiche/ricerca/), ma ci viene restituito lo stesso errore. Ecco la Response:
{
    "testataRisposta": {
        "idComune": 595,
        "idOperazioneComune": "7000",
        "idOperazione": "1591316",
        "idEsito": 999
    },
    "errors": [
        {
            "code": "403002",
            "severity": "E",
            "text": "L'utente non e' autorizzato ad usare la funzione selezionata"
        }
    ]
}

L'idComune che inviamo è corretto, ed è lo stesso che utilizziamo regolarmente nell'invocazione degli altri servizi, ottenendo risposte valide.

**Comment by amusarra** [comment]
Salve @gcuci avete verificato che il token JWT sia conforme alla richiesta, nei termini di degli attributi sub, sede e postazione? Fare riferimento al documento https://github.com/italia/ansc/blob/main/docs/Note/SpecificheTecnicheServiziCooperativiJWT/SpecificheTecnicheServiziCooperativiJWT_v1.1.0.pdf

**Comment by gcuci** [comment]
Il JWT lo creiamo nello stesso modo, per le chiamate anche agli altri servizi, i quali, come detto, ci restituiscono risposte valide.
Provando a settare in modo incoerente sede e postazione, il servizio risponde in questo modo:

{
    "operation": "/services/service/notifiche/notifiche/ricerca/1",
    "error": "500",
    "error_description": "Richiesta invalida"
}

Mentre mettendo i valori corretti, otteniamo sempre (di seguito, Response ad un'invocazione del servizio, appena eseguita):

{
    "testataRisposta": {
        "idComune": 595,
        "idOperazioneComune": "7000",
        "idOperazione": "1591834",
        "idEsito": 999
    },
    "errors": [
        {
            "code": "403002",
            "severity": "E",
            "text": "L'utente non e' autorizzato ad usare la funzione selezionata"
        }
    ]
}

**Comment by amusarra** [comment]
@gcuci faremo delle verifiche cercando di replicare il caso. Intanto riapro la issue.

Cordiali Saluti.
Supporto ANSC.

**Comment by amusarra** [comment]
Buongiorno @ManuelDeMeo e @gcuci 
Per informarvi che il bug da voi riscontrato sarà rilasciato la release 1.9.0 che dovrebbe avvenire entro la giornata del 31/05/2023.

**Comment by asqueglia** [comment]
Buongiorno con la versione 1.9.0 appena rilasciata è stato corretto l'errore. E' possibile riprovare. La issue viene chiusa in caso si prega di riaprirla.
