### ISSUE TITLE
[SC]: Non è possibile modificare lo stato dell'evento durante una rettifica

### ISSUE THREAD

**Issue by Hdemografici** [italia/ansc#1193]
### Ambiente

pre-produzione

### Servizio

R013 - Servizi cooperativi per la validazione della rettifica

### idOperazione

2869049

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

colli al metauro

### Data del test (yyyy-mm-dd)

2024-12-04

### Descrivi il problema

non riesco a capire il motivo dell'errore ritornato, potete aiutarmi
grazie

**Comment by asqueglia** [comment]
Buongiorno, nella sezione eventoModificato devono essere trasmessi tutti i metadati dell'evento originario con la modifica che si intende fare; vanno trasmessi anche i metadati non modificati; dal payload da voi indicato invece si desume che sono stati trasmessi solo alcuni dati dell'intestatario e basta. Non si è capito inoltre quale sia il dato che intendete correggere con la rettifica per art.98.

Di seguito un payload di esempio di quanto detto 

  "evento": {
        "idTipoEvento": "1",
        "idtipocontenuto": "2",
        "idUsecase": "14640000",
        "descrizioneCasoUso": "Annotazione per rettifica di errore materiale",
        "stato": "CONFERMATO",
        "dataformazione": "2023-03-16",
        "ora": "09",
        "minuto": "52",
        "annoAtto": "2023",
        "numeroatto": "123",
        "idComuneRegistrazione": "1000000",
        "nomeComuneRegistrazione": "ANPR",
        "idProvinciaRegistrazione": "58",
        "siglaProvinciaRegistrazione": "RM",
        "operatore": "CRUMRA67S47Z127B",
        "ruoloOperatore": "2",
        "operatoreNome": "MARIE",
        "operatoreCognome": "CURIE",
        "redattoNellaCasaComunale": true,
        "datiRettifica": {
            "eventoCollegato": {
                "idAnsc": "2024-580947-43234-021009",
                "idComuneRegistrazione": "021009",
                "nomeComuneRegistrazione": "BRAIES",
                "idProvinciaRegistrazione": "21",
                "siglaProvinciaRegistrazione": "BZ",
                "idtipocontenuto": "1",
                "dataformazione": "2024-05-15",
                "numeroatto": "43234",
                "annoAtto": "2024",
                "tipologia": "1",
                "serie": "",
                "parte": ""
            },
            "dettaglioRettifica": "**Ai sensi dell'art. 98, c. 1 del D.P.R. n. 396/2000 l'atto soprascritto (o circoscritto) viene corretto nel senso che dove è scritto: GAETANO de leggersi ed intendersi CARLO**",
            "idTipoRettifica": "1"
        },
        "composizioneCompleta": "**Ai sensi dell'art. 98, c. 1 del D.P.R. n. 396/2000 l'atto soprascritto (o circoscritto) viene corretto nel senso che dove è scritto: GAETANO de leggersi ed intendersi CARLO**",
        "datains": "2023-03-23T09:52:39.207824",
        "dataultimoagg": "2023-03-23T10:15:25.453759"
    },
    "eventoModificato": {
        "id": 580947,
        "idAnsc": "2024-580947-43234-021009",
        "idTipoEvento": "1",
        "idtipocontenuto": "1",
        "idUsecase": "11111000",
        "descrizioneCasoUso": "Dichiarazione entro i 10 giorni - resa dal padre",
        "stato": "FIRMATO DA USC",
        "dataDecorrenza": "2024-05-15",
        "dataformazione": "2024-05-15",
        "ora": "18",
        "minuto": "36",
        "annoAtto": "2024",
        "numeroatto": "43234",
        "tipoDichiarante": "1",
        "ausilioInterprete": "false",
        "idComuneRegistrazione": "021009",
        "nomeComuneRegistrazione": "BRAIES",
        "idProvinciaRegistrazione": "21",
        "siglaProvinciaRegistrazione": "BZ",
        "operatore": "CRUMRA67S47Z127B",
        "ruoloOperatore": "2",
        "operatoreNome": "MARIE",
        "operatoreCognome": "CURIE",
        "redattoNellaCasaComunale": true,
        "allegati": [
            {
                "id": 581492,
                "idTipoAllegato": 1,
                "hashAllegato": "oeAYUrRzqVnj1SNO6pyjSJrOyd+4KTjVHxpF2YCiP+U=",
                "descrizione": "Attestazione di nascita",
                "idStatoAllegato": 3,
                "flagAttestazione": true
            },
            {
                "id": 581497,
                "idTipoAllegato": 999,
                "hashAllegato": "Ngv9LQpoztJEpH85OqaFTG8paofdvzjbWLNIvSu25pk=",
                "descrizione": "Processo verbale",
                "idStatoAllegato": 3,
                "flagAttestazione": true
            },
            {
                "id": 581502,
                "idTipoAllegato": 99,
                "hashAllegato": "a5f89cef1a77213b8fd420b50f40c5435b6ef624fe823f52d450326bc0912f60",
                "descrizione": "Attestazione di conformità",
                "idStatoAllegato": 3
            }
        ],
        "intestatari": [
            {
                "id": "581494",
                "cognome": "XXXXX",
                **"nome": "CARLO",**
                "sesso": "M",
                "dataNascita": "2024-05-15",
                "idComuneNascita": "8165",
                "nomeComuneNascita": "ROMA",
                "idProvinciaNascita": "58",
                "siglaProvinciaNascita": "ROMA",
                "idStatoNascita": "90",
                "nomeStatoNascita": "ITALIA",
                "idComuneResidenza": "2780",
                "nomeComuneResidenza": "CESENA",
                "idProvinciaResidenza": "40",
                "siglaProvinciaResidenza": "FC",
                "idStatoResidenza": "90",
                "nomeStatoResidenza": "ITALIA",
                "indirizzoResidenza": "",
                "documentoRiconoscimento": {}
            }
        ],
        "madre": {
            "id": "45686",
            "idsoggettoanpr": "266044",
            "codiceFiscale": "XXXX",
            "nome": "XXXX",
            "sesso": "F",
            "dataNascita": "2020-05-01",
            "idComuneNascita": "8165",
            "nomeComuneNascita": "ROMA",
            "idProvinciaNascita": "58",
            "siglaProvinciaNascita": "RM",
            "idStatoNascita": "90",
            "nomeStatoNascita": "ITALIA",
            "idComuneResidenza": "2780",
            "nomeComuneResidenza": "CESENA",
            "idProvinciaResidenza": "40",
            "siglaProvinciaResidenza": "FC",
            "idStatoResidenza": "90",
            "nomeStatoResidenza": "ITALIA",
            "idNazionalita": "90",
            "nazionalita": "ITALIANA",
            "flagDichiarante": false,
            "flagComparente": false,
            "flagFirmatario": false,
            "documentoRiconoscimento": {}
        },
        "padre": {
            "id": "43500",
            "idsoggettoanpr": "265097",
            "codiceFiscale": "XXXX",
            "cognome": "XXXX",
            "nome": "XXXXX",
            "sesso": "M",
            "dataNascita": "1989-06-28",
            "idComuneNascita": "18345",
            "nomeComuneNascita": "ROMA",
            "idProvinciaNascita": "58",
            "siglaProvinciaNascita": "RM",
            "idStatoNascita": "90",
            "nomeStatoNascita": "ITALIA",
            "idComuneResidenza": "2780",
            "nomeComuneResidenza": "CESENA",
            "idProvinciaResidenza": "40",
            "siglaProvinciaResidenza": "FC",
            "idStatoResidenza": "90",
            "nomeStatoResidenza": "ITALIA",
            "idNazionalita": "11",
            "nazionalita": "AUSTRIACA",
            "flagDichiarante": true,
            "flagComparente": false,
            "flagFirmatario": true,
            "documentoRiconoscimento": {}
        },
        "datiDichiarante": {
            "comprensione": "0"
        },
        "datiDiNascita": {
            "sceltaCognome": "1",
            "oraNascita": "18",
            "minutoNascita": "37",
            "natoMorto": "NO",
            "natoVivoMaDeceduto": "NO",
            "tipoAccertamento": "1"
        },
        "composizioneCompleta": "L'anno 2022 addì .......",
        "datains": "2024-05-28T13:36:55.041107",
        "dataultimoagg": "2024-05-28T13:59:49.964148",
        "flagsecretato": 0,
        "idVersion": 100010,
        "operatoreFirmatario": "TRNLNA91D41A083B",
        "operatoreFirmatarioNome": "ALAN",
        "operatoreFirmatarioCognome": "TURING"
    }
}

Chiudiamo pertanto la issue. In caso di ulteriori dubbi in merito si prega di riaprirla
