### ISSUE TITLE
[webapp]: Mancata creazione notifiche anagrafiche - atto di morte 3813595

### ISSUE THREAD

**Issue by MoniaPedrazzoli** [italia/ansc#1194]
### Ambiente

pre-produzione

### Provenienza segnalazione

Software House

### Riferimenti operatore/comune

Monia Pedrazzoli

### Data del test (yyyy-mm-dd)

04/12/2024

### Descrivi il problema

Buongiorno, abbiamo inserito per il comune 018005 l'atto di morte con ID 3813595 relativo a un soggetto residente nel comune, ma non abbiamo ricevuto alcuna notifica anagrafica nella webapp ANPR (la notifica ANSC di cui prendere visione è presente e risulta accettata).
L'abilitazione all'ambiente di pre-produzione ANSC per questo comune risale a ieri (rif. #1181) e nella tabella 110 è presente.
Potete controllare come mai non riceviamo la notifica anagrafica?
Grazie

**Comment by gbuemi** [comment]
Salve @MoniaPedrazzoli ,
abbiamo risolto la questione, adesso la notifica è stata generata con successo.

Un saluto,
Supporto ANSC
