### ISSUE TITLE
[SC]: Tipologia d'uso certificato non coerente con scelta effettuata

### ISSUE THREAD

**Issue by Hdemografici** [italia/ansc#1196]
### Ambiente

pre-produzione

### Servizio

R002 - Servizi cooperativi certificazioni

### idOperazione

2865146

### idEvento o idAnsc

2024‐3718110‐677‐041069

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Halley Informatica - Colli al Metauro

### Data del test (yyyy-mm-dd)

04/12/2024

### Descrivi il problema

buon pomeriggio, 

atto di nascita ANSC 2024‐3718110‐677‐041069
effettuando vari tentativi di invocazione del servizio R002 per l'atto sopracitato, selezionando tipologie d'uso diverse, si nota che nel certificato/estratto di nascita viene sempre riportata in basso la dicitura:

"Il presente certificato non può essere prodotto agli organi della Pubblica Amministrazione o ai privati gestori di pubblici servizi."

sebbene siano stati selezionati anche usi diversi  da "Art. 40 comma 2 DPR 445/2000"

uso 1
testataRisposta 
idComune: 22758
idOperazioneComune: SCH20241204095525200
idOperazione: 2865146

uso 2
testataRisposta 
idComune: 22758
idOperazioneComune: SCH20241204095556187
idOperazione: 2865147

uso 3
testataRisposta 
idComune: 22758
idOperazioneComune: SCH20241204095631216
idOperazione: 2865149

uso 4
testataRisposta 
idComune: 22758
idOperazioneComune: SCH20241204095705241
idOperazione: 2865150

uso 5
testataRisposta 
idComune: 22758
idOperazioneComune: SCH20241204095734588
idOperazione: 2865151

uso 6
idComune: 22758
idOperazioneComune: SCH20241204095818801
idOperazione: 2865153

si chiede quale possa essere l'origine della problematica

grazie per l'attenzione

**Comment by asqueglia** [comment]
Buongionro, avete trasmesso come idTipoUso un numero non coerente 01, 02, 03 ecc...; si richiede di attenenrsi alla tabella di decodifica che prevede di trasmettere l'id dela tipologia d'uso come 1, 2, 3 ecc...

Chiudiamo pertanto la issue
