### ISSUE TITLE
PROBLEMA DI ACCESSO in preproduzione ANSC

### ISSUE THREAD

**Issue by Mymma** [italia/ansc#1197]
### Ambiente

pre-produzione

### Provenienza segnalazione

Comune

### Riferimenti operatore/comune

IRMA LILIANA PITTAU

### Caso d'uso

accesso 

### Descrivi il problema

sto cercando di accedere all'ambiente di preproduzione di ANSC ma mi restituisce l'errore: "login error" sono als di Anpr dovrei poter entrare con le mie credenziale oppure solo il sindaco può accedere?

**Comment by asqueglia** [comment]
Buongiorno, l’ALS può accedere alla console di sicurezza di ANPR per aggiungere nominativi o assegnare i profili di stato civile a soggetti già censiti come ufficiali di anagrafe. Il Sindaco ha il compito di accedere al sistema per inserire la proposta di adesione; il giorno dell’adesione il Sindaco inserirà la dichiarazione di adesione con la data di chiusura dei registri al giorno precedente. Chiudiamo pertanto la issue. Se ci fossero ulteriori richieste si prega di  aprire una specifica discussion.
