### ISSUE TITLE
[R010] Errore in invocazione servizio per Trascr_999

### ISSUE THREAD

**Issue by ManuelDeMeo** [italia/ansc#12]
Buongiorno,
segnalo che per lo specifico caso d'uso (Id: 1399) il servizio di anteprima restituisce errore.  Per altri casi d'uso invece, il servizio funziona correttamente.
Verificando da webapp invece, l'anteprima per lo stesso atto, viene recuperata correttamente (anche se il titolo risulta essere Estratto per copia integrale di nascita)

Aggiungo richiesta e risposta:

Request:
`{
   "presaVisione":null,
   "evento":{
      "id":"949652",
      "idAnsc":"2023-949652-13-058046",
      "idTipoEvento":null,
      "idtipocontenuto":null,
      "idUsecase":"1399",
      "descrizioneCasoUso":null,
      "stato":null,
      "dataformazione":null,
      "annoAtto":null,
      "meseAtto":null,
      "giornoAtto":null,
      "ora":null,
      "minuto":null,
      "operatore":null,
      "ruoloOperatore":null,
      "operatoreNome":null,
      "operatoreCognome":null,
      "redattoNellaCasaComunale":null,
      "luogoRedazione":null,
      "idComuneRegistrazione":null,
      "nomeComuneRegistrazione":null,
      "idProvinciaRegistrazione":null,
      "siglaProvinciaRegistrazione":null,
      "dataDecorrenza":null,
      "numeroatto":null,
      "tipoDichiarante":null,
      "ausilioInterprete":null,
      "conTestimoni":null,
      "noteRitardo":null,
      "motivoAnnullamento":null,
      "tipoConsenso":null,
      "certificabile":null,
      "datiRiconoscimento":null,
      "sentenzaFiglioIncestuoso":null,
      "propostaAnnotazione":null,
      "datiProdotti":null,
      "allegati":null,
      "intestatari":null,
      "variazioni":null,
      "enteDichiarante":null,
      "ufficialeStatoCivile":null,
      "madre":null,
      "padre":null,
      "coniuge":null,
      "dichiarante":null,
      "interprete":null,
      "datiDichiarante":null,
      "datiDiNascita":null,
      "datiDiMorte":null,
      "datiRinvenuto":null,
      "datiEventoRiconoscimento":null,
      "datiEventoCittadinanza":null,
      "datiEventoMatrimonio":null,
      "datiEventoUnioneCivile":null,
      "riconoscimentoMadre":null,
      "riconoscimentoPadre":null,
      "riconoscimento":null,
      "consenso":null,
      "consensoMadre":null,
      "consensoPadre":null,
      "attoNotarileConsensoMadre":null,
      "attoNotarileConsensoPadre":null,
      "trascrizioneNascita":null,
      "trascrizioneCittadinanza":null,
      "trascrizioneMorte":null,
      "trascrizioneMatrimonio":null,
      "trascrizioneUnioneCivile":null,
      "trascrizioneSeparazione":null,
      "riconciliazione":null,
      "separazione":null,
      "negoziazioneAssistita":null,
      "scioglimentoUnioneCivile":null,
      "tribunale":null,
      "eventoCollegato":null,
      "datiAnnotazione":null,
      "datiEventoMorte":null,
      "datiAssenso":null,
      "datiRettifica":null,
      "datiLingua":null,
      "composizioneCompleta":null
   },
   "testataRichiesta":{
      "idComune":4559,
      "idOperazioneComune":"2",
      "dataOraRichiesta":"1",
      "nomeApplicativo":"testSC",
      "versioneApplicativo":"1.0.0",
      "fornitoreApplicativo":"Test"
   },
   "datiPaginazione":null
}`

Response:
`{
   "testataRisposta":{
      "idComune":4559,
      "idOperazioneComune":"2",
      "idOperazione":"1561253",
      "idEsito":1
   },
   "errors":[
      {
         "code":"400001",
         "severity":"E",
         "text":"Use Case non valido"
      }
   ]
}`

**Comment by asqueglia** [comment]
Buongiorno, la ringraziamo per la segnalazione. Verifichiamo e le facciamo sapere.

**Comment by asqueglia** [comment]
Buonasera, è stata rilasciata la versione 1.5.2 che risolve ala segnalazione. Si prega di riprovare.

**Comment by ManuelDeMeo** [comment]
Grazie, confermo la risoluzione
