### ISSUE TITLE
[R012] Firma dichiarante elettronica invio email: errore in caricamento della pagina di sottoscrizione

### ISSUE THREAD

**Issue by MichelaGarzoni** [italia/ansc#120]
Buongiorno, ho inviato la seguente richiesta di firma digitale (ora anonimizzata):

```json
{
    "testataRichiesta": {
        "idComune": 3655,
        "idOperazioneComune": "1",
        "dataOraRichiesta": "2023-05-18T11:25:36Z",
        "nomeApplicativo": "XXXXX",
        "versioneApplicativo": "21.99.0000",
        "fornitoreApplicativo": "Fornitore"
    },
    "emailDichiarante": "michela.garzoni@insiel.it",
    "idEvento": "952192",
    "idAnsc": "2023-952192-20230050000012-032001",
    "firmatario": {
        "cognome": "XXXX",
        "nome": "YYYY"
    }
}
```

ho ottenuto la risposta:

```json
{
    "esito": {
        "codice": "200",
        "descrizione": "Ok"
    },
    "testataRisposta": {
        "idComune": 3655,
        "idEsito": 0,
        "idOperazioneComune": "1"
    },
    "idPresaVisione": "1926654"
}

```

e mi è arrivata la relativa mail con il link per poter notificare la presa visione (https://anscwebpre.anpr.interno.it/sc/login/9e60559219266545a57-4fe4-9e20-51472cc9bdc7)
ma accedendo a tale link ottengo sempre il messaggio
"si è verificato un errore, si prega di ricaricare la pagina":

![image](https://github.com/italia/ansc/assets/128141738/08a5a347-eafc-4e6b-bd15-12b38f2a06de)

Grazie

**Comment by amusarra** [comment]
Buongiorno @MichelaGarzoni 
Abbiamo preso in carico la segnalazione.

Cordiali Saluti.
Supporto ANSC

**Comment by asqueglia** [comment]
Buongiorno con la versione 1.9.0 appena rilasciata è stato corretto l'errore. E' possibile riprovare. La issue viene chiusa in caso si prega di riaprirla.
