### ISSUE TITLE
[webapp]: Modifica certificabilità annotazione

### ISSUE THREAD

**Issue by Hdemografici** [italia/ansc#1202]
### Ambiente

produzione

### Provenienza segnalazione

Software House

### Riferimenti operatore/comune

Halley Informatica - Sissa Trecasali

### Data del test (yyyy-mm-dd)

11/12/2024

### Descrivi il problema

buon pomeriggio
ambiente di produzione - Comune di Sissa Trecasali
è stato inserito atto di nascita dall'estero: 2024-36396-29-034049
successivamente in questo è stata inserita annotazione di acquisto cittadinanza: 2024-36401-30-034049
l'invio dell'annotazione nel sistema ANSC, tramite servizi cooperativi, è stato effettuato impostando erroneamente l'annotazione non certificabile
si necessità quindi rettifica della condizione di certificabilità per l'evento 2024-36401-30-034049

in tale circostanza si chiede quale sia la via corretta per procedere alla correzione
da WA, provando da "Altri servizi" / "Correzione di annotazione" si riscontra la possibilità di modificare solo il testo dell'annotazione 

grazie per l'attenzione

**Comment by asqueglia** [comment]
Buongiorno,
il sistema non prevede servizi atti a correggere la certificabilità dell'annotazione e non è possibile intervenire da centro su un evento (in questo caso un evento di tipo annotazione) già chiuso e firmato. L'unica cosa che è possibile richiedere è la disassociazione dell'annotazione dall'atto, richiedere di rendere inefficace l'annotazione e procedere poi all'inserimento di una nuova annotazione trasmettendo questa volta il flag sulla certificabilità corretto. Se per voi è una soluzione perseguibile vi preghiamo di inviare tramite PEC la richiesta di intervento alla casella di assistenza.ansc@sogei.it

Chiudiamo pertanto la issue.
