### ISSUE TITLE
[webapp]: Notifica annotazione divorzio estero su atto matrimonio

### ISSUE THREAD

**Issue by Hdemografici** [italia/ansc#1205]
### Ambiente

produzione

### Provenienza segnalazione

Software House

### Riferimenti operatore/comune

Halley informatica - Lomazzo

### Data del test (yyyy-mm-dd)

12/12/2024

### Caso d'uso

347000

### Descrivi il problema

buongiorno,
tramite servizi cooperativi il Comune di Lomazzo ha inserito:
atto matrimonio 2024-36614-2-013133 (trascrizione matrimonio avvenuto all'estero caso uso 332000)
atto matrimonio 2024-36629-3-013133 (trascrizione divorzio avvenuto all'estero caso uso 347000)
gli atti sono riferiti a SPOSO straniero non residente / SPOSA cittadina AIRE del Comune di Lomazzo

dopo la trascrizione dell'atto di divorzio si nota la creazione in WA della seguente notifica:
-annotazione automatica da inviare via pec 2024-36636-00000-013133 (da inviare via PEC)
riferita a Sposo, annotazione formula n.170

in questo caso non si tratterebbe di annotazione da inviare via PEC ma da approvare per apposizione automatica su atto matrimonio dello stesso Comune 2024-36614-2-013133

grazie per l'attenzione

**Comment by asqueglia** [comment]
Buongiorno verifichiamo e le facciamo saper quanto prima

**Comment by asqueglia** [comment]
Buongiorno, per l'evento sopra indicato abbiamo apportato la correttiva da centro. Potete verificare che, una volta approvata, l'annotazione adesso risulta correttamente apposta sull'atto di matrimonio. Prendiamo invece in carico il bug segnalato

**Comment by Hdemografici** [comment]
Buongiorno, effettuata approvazione della notifica e confermiamo che l'annotazione risulta correttamente apposta sull'atto di matrimonio

**Comment by asqueglia** [comment]
Con il rilascio della versione 1.36.0, la segnalazione è stata corretta
