### ISSUE TITLE
[webapp]: testo annotazione matrimonio F.132 su atto nascita

### ISSUE THREAD

**Issue by Hdemografici** [italia/ansc#1206]
### Ambiente

produzione

### Provenienza segnalazione

Software House

### Riferimenti operatore/comune

Halley informatica

### Data del test (yyyy-mm-dd)

12/12/2024

### Descrivi il problema

buon pomeriggio,
tramite servizi cooperativi il comune di Sissa Trecasali ha inserito atto di matrimonio 2024-36558-31-034049 riferita a cittadino che risultava avere atto di nascita trascritto digitalmente nello stesso Comune

nel testo dell'annotazione di matrimonio generata automaticamente dal sistema ANSC per l'atto di nascita si riscontra il seguente testo:

"XXX ha contratto matrimonio con YYY il zz/zz/zzzz in XXX (XX). L'atto fu trascritto nei registri di matrimonio del Comune di XXX con numero 2024-36558-31-034049."

Confrontando il testo sopra riportato con quello presente nel formulario ufficiale (formula F.132) si riscontrano delle piccole differenze (non sostanziali):

-al posto di "in XXX (XX)" dovrebbe essere riportato "nel Comune di XXX (XX)"
-al posto di "numero 2024-36558-31-034049" dovrebbe essere riportato "n. 2024-36558-31-034049"

si chiede di valutare eventuale adeguamento

grazie per l'attenzione

**Comment by asqueglia** [comment]
Buongiorno provvediamo a verificare e le facciamo sapere

**Comment by asqueglia** [comment]
Con il rilascio della versione 1.36.0, la segnalazione è stata corretta
