### ISSUE TITLE
[SC]: casistica unciv_003 allegato mancante

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#1209]
### Ambiente

pre-produzione

### Servizio

R001 - Servizi cooperativi allegati

### idOperazione

assente

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

ponsacco, anna maraspin

### Descrivi il problema

Buongiorno,
tra gli allegati ci dovrebbe essere anche il certificato medico, obbligatorio (come introdotto per matr_003 nella versione 1.34).

**Comment by asqueglia** [comment]
Buongiorno verifichiamo e le facciamo sapere

**Comment by asqueglia** [comment]
Con il rilascio della versione 1.36.0, la segnalazione è stata corretta
