### ISSUE TITLE
[R006] - Errore in firma autografa per casi d'uso Dic_Nasc_044 e Dic_Nasc_046

### ISSUE THREAD

**Issue by ManuelDeMeo** [italia/ansc#121]
Buongiorno,
riscontriamo un errore nell'invocazione del servizio R006 (/firmadichiarante/upload/1) per i casi d'uso in oggetto: Dic_Nasc_044 e Dic_Nasc_046.

In particolare, per entrambi, otteniamo l'errore per cui non è prevista la firma del dichiarante.

Nella richiesta di seguito, trovate anche un id operazione di riferimento.

Test effettuato: 18/05/2023
Ambiente: preproduzione

`
{
	"errors": [
		{
			"code": "401003",
			"severity": "E",
			"text": "Per l'evento indicato non è prevista la firma del dichiarante"
		}
	],
	"testataRisposta": {
		"idComune": 4559,
		"idEsito": 1,
		"idOperazione": "1590805",
		"idOperazioneComune": "2"
	}
}
`

**Comment by asqueglia** [comment]
Buongiorno, da verifiche interne abbiamo visto che l'operazione indicata si riferisce all'evento 952380. Per questo evento non è stato trasmesso il flagFirmatario a true per il soggetto madre che è dichiarante. Infatti vediamo che sono stati trasmessi per la madre i seguenti flag
flagDichiarante = true
flagComparente= true
flagFirmatario = false

se nessun soggetto collegato all'evento presenta il flagFirmatario a true, il servizio di firma restituisce errore bloccante in quanto nessun soggetto è stato dichiarato firmatario.
