### ISSUE TITLE
Errore 400003 in R006 Unione Civile use case 431000

### ISSUE THREAD

**Issue by eschoysman** [italia/ansc#1212]
### Ambiente

pre-produzione

### Servizio

R006 - Servizi cooperativi firma dichiarante

### idOperazione

2913800

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Siena 9493

### Data del test (yyyy-mm-dd)

2024/12/17

### Descrivi il problema

Durante le prove per il caso d'uso in oggetto (Unione civile 431000), nello step di "Invio Firma Dichiarante" inviamo i due uniti civilmente e l'officiante. Tuttavia la chiamata ottiene la risposta seguente (la request è in allegato):

Response payload:
```json
{
    "errors": [
        {
            "code": "400003",
            "severity": "E",
            "text": "Non sono stati recuperati firmatari per i dati inseriti"
        }
    ],
    "infos": [
        {
            "code": "110527",
            "severity": "I",
            "text": "Informazioni sull'operazione da fornire in caso di assistenza : data:2024-12-17 15:54:35 , idOperazione:2913800"
        }
    ],
    "testataRisposta": {
        "idComune": 9493,
        "idEsito": 1,
        "idOperazione": "2913800",
        "idOperazioneComune": "23018"
    }
}
```

Vorrei capire se è dovuto al fatto che l'officiante non è recuperato (i due uniti civilmente sono presenti sui vostri sistemi, mentre il firmatario con codice fiscale FFCJNT00E15A390I non si trova) oppure se il problema è un altro.

Inoltre: esiste un documento che permette di capire quali firmatari sono necessari per i diversi atti? Se l'officiante è sempre richiesto?

### Payload (json)

```JSON
Request payload:
{
    "firmaDichiaranteInput": {
        "contenuto": CONTENUTO_PDF,
        "idEvento": "3913526",
        "listaFirmatari": [
            {
                "codiceFiscale": "RSCRST00T16I726W",
                "cognome": "AR_USECASE_M",
                "dataNascita": "2000-12-16",
                "nome": "AR_TEST2_431000",
                "sesso": "M"
            },
            {
                "codiceFiscale": "SSCSST01T16I726C",
                "cognome": "AS_USECASE_M",
                "dataNascita": "2001-12-16",
                "nome": "AS_TEST2_431000",
                "sesso": "M"
            },
            {
                "codiceFiscale": "FFCJNT00E15A390I",
                "cognome": "Ufficiale",
                "dataNascita": "2000-05-15",
                "nome": "JENTE",
                "sesso": "M"
            }
        ],
        "nomefile": "SC157456.pdf",
        "tipoAllegato": "999",
        "tipoFile": "1"
    },
    "testataRichiesta": {
        "dataOraRichiesta": "2024-12-17T15:54:33.997486",
        "fornitoreApplicativo": "SistemiInformativi",
        "idComune": 9493,
        "idOperazioneComune": "23018",
        "nomeApplicativo": "SIDe",
        "versioneApplicativo": "1.0.0"
    }
}
```

**Comment by asqueglia** [comment]
Buongiorno, l'atto che state registrando è una trascrizione di unione civile dall'estero richiesta dall' interessato. 
In questo caso il soggetto firmatario è solo l'interessato che richiede la trascrizione all'USC.
Tramite servizi cooperativi, avete comunque facoltà di indicare espressamente chi siano i soggetti firmatari; in generale, quindi, da servizi cooperativi siete voi ad indicare chi sono i soggetti firmatari di un atto attraverso il flagFirmatario=true nella sezione soggetto.
Nel caso specificato avete indicato come firmatari  gli uniti civilmente  e il soggetto interessato che ha richiesto la trascrizione che è stesso uno degli intestatari; per cui come firmatari dovreste adesso indicare appunto tali soggetti :
RSCRST00T16I726W --> unito civilmente
SSCSST01T16I726C --> unito civilmente
RSCRST00T16I726W --> interessato che effettua la richiesta

 "listaFirmatari": [
            {
                "codiceFiscale": "RSCRST00T16I726W",
                "cognome": "AR_USECASE_M",
                "dataNascita": "2000-12-16",
                "nome": "AR_TEST2_431000",
                "sesso": "M"
            },
            {
                "codiceFiscale": "SSCSST01T16I726C",
                "cognome": "AS_USECASE_M",
                "dataNascita": "2001-12-16",
                "nome": "AS_TEST2_431000",
                "sesso": "M"
            },
            {
                "codiceFiscale": "RSCRST00T16I726W",
                "cognome": "AR_USECASE_M",
                "dataNascita": "2000-12-16",
                "nome": "AR_TEST2_431000",
                "sesso": "M"
            }
        ],

Si specifica inoltre che quando il dichiarante è anche l'intestatario (in questo caso l'unito civilmente), non è necessario trasmetterlo due volte sia nella sezione intestatario che nella sezione dichiarante; è necessario trasmetterlo SOLO nella sezione intestatario impostando il flagDichiarante=true come avete appunto fatto, senza trasmetterlo anche nella sezione dichiarante.
Si consiglia di ripetere il test registrando l'atto ex novo come da indicazioni.

Chiudiamo pertanto la issue. In caso di ulteriori problemi restiamo a disposizione.
