### ISSUE TITLE
[webapp]: Mancata creazione notifiche anagrafiche - atto di nascita 3913639

### ISSUE THREAD

**Issue by MoniaPedrazzoli** [italia/ansc#1215]
### Ambiente

pre-produzione

### Provenienza segnalazione

Software House

### Riferimenti operatore/comune

Monia Pedrazzoli

### Data del test (yyyy-mm-dd)

18/12/2024

### Descrivi il problema

Buongiorno, abbiamo inserito per il comune 018005 l'atto di nascita con ID 3913639 con madre iscritta all'AIRE del comune che ha redatto l'atto e comune di nascita italiano, diverso dal comune che ha redatto l'atto. Non abbiamo ricevuto alcuna notifica anagrafica nella webapp ANPR (manca anche la notifica ANSC di cui prendere visione). Mi rendo conto che si tratta di un caso particolare ma vi chiederei comunque di controllare.
Grazie

**Comment by gbuemi** [comment]
Buongiorno @MoniaPedrazzoli,
non sono state generate le notifiche ANSC e ANPR perché è necessario inviare il comune AIRE per l'intestatario oppure fare in modo che vengano ereditati quelli della madre, impostando il flagTrasmissioneResidenzaEstera valorizzato a true.
Da normativa non possono essere ereditati in modo automatico dalla madre, dev'essere richiesto.

Un saluto,
Supporto ANSC
