### ISSUE TITLE
[SC]: Anteprima Conformità: Controllo su Firma Dichiaranti - Messaggio di Errore

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/ansc#1216]
### Ambiente

produzione

### Servizio

R010 - Servizi cooperativi anteprima

### idOperazione

624232

### idEvento o idAnsc

2024-37468-613-023089

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Valeggio sul Mincio

### Data del test (yyyy-mm-dd)

2024-12-19

### Descrivi il problema

come già segnalato con issue #970, che risulta sotto monitoraggio, sta capitando anche a Valeggio la stessa situazione.

il servizio di Anteprima Attestazione Conformità (R010) restituisce l'errore "L'evento non può essere firmato, l'atto necessita della firma di uno o più dichiaranti".

in realtà il servizio di Firma Dichiaranti (R006) è stato inviato, ma l'atto risulta ancora in stato "CONFERMATO" (forse a motivo della verifica dell'allegato mandato in upload)
abbiamo anche cercato di ri-mandare il documento di firma ma - giustamente - il sistema segnala "Allegato associato all'utente è già in elaborazione" (idOperazioneAnsc 624622)

l'atto è bloccato.
possibilmente, vi chiediamo un riscontro urgente.

grazie
Alessandro ADS

**Comment by asqueglia** [comment]
Buongiorno stiamo verificando la situazione e facciano sapere a breve

**Comment by asqueglia** [comment]
Buongiorno @AMonopoliADS  potete riprovare la validazione dell'atto. Abbiamo provveduto a sbloccare da centro.
