### ISSUE TITLE
[SC]: Anteprima caso uso 1364 - Dati in ingresso non corretti

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#1218]
### Ambiente

pre-produzione

### Servizio

R010 - Servizi cooperativi anteprima

### idOperazione

2928775

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

biadanpad - Lissone

### Data del test (yyyy-mm-dd)

2024-12-23

### Descrivi il problema

Il servizio di generazione anteprima restituisce l'errore in oggetto

**Comment by asqueglia** [comment]
Buongiorno stiamo verificando e le facciamo sapere.

**Comment by asqueglia** [comment]
Buongiorno, l'anomalia è stata corretta con la patch 1.36.1. Chiudiamo pertanto la issue.
