### ISSUE TITLE
[SC]: Certificazione e Estratti per Copia Integrale

### ISSUE THREAD

**Issue by KibMcris** [italia/ansc#1219]
### Ambiente

produzione

### Servizio

R002 - Servizi cooperativi certificazioni

### idOperazione

assente

### idEvento o idAnsc

2024-37954-54-050029

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Pontedera

### Data del test (yyyy-mm-dd)

23-12-2024

### Descrivi il problema

Dopo aver sottoscritto l'atto con idansc 2024-37954-54-050029, l'ufficiale di stato civile ha tentato di generare il certificato relativo all'atto appena concluso.
Ansc risponde con l'errore:
`Il Tipo di certificato CERTIFICATO_SEMPLICE non può essere generato per l'atto 37954"`

L'atto in oggetto si riferisce ad un atto di morte riferito ad una trascrizione da altro comune perciò registrato con caso d'uso "Caso d'uso di servizio (trascrizioni di morte)".

Abbiamo provato anche dall'ambiente di test su atto della stessa natura e l'errore si presenta per tutti i tipi di certificati:
- Certificato Semplice;
- Estratto;
- Copia Integrale.
Da web app di test rileviamo lo stesso errore per la copia integrale, mentre il certificato e l'estratto non sono selezionabili.

Il comune riferisce che per l'estratto è corretto che non venga emesso, poichè in questo caso occorre certificare l'atto originale cartaceo, mentre per il certificato semplice e l'estratto non è corretto che non siano prodotti da ANSC.

Ci siamo confrontati anche con altri comuni e tutti ci hanno confermato la stessa cosa.

Potete approfondire?

Restiamo in attesa di riscontro

**Comment by asqueglia** [comment]
Buon pomeriggio, 
dalle verifiche effettuate abbiamo appurato che per l’atto indicato registrato con caso d’uso di servizio, non sono state trasmesse le informazioni circa le tipologie di certificazione emissibili; con la versione 1.34.0 infatti è stata data la possibilità agli USC di indicare esplicitamente le tipologie di certificazione emissibili quando l’atto viene registrato con un caso d’uso di servizio (attività presente nel changelog con identificativo _ID109: indicazione esplicita delle tipologie di certificazione emissibili nei casi d’uso di servizio_); questo è il motivo per cui è al momento possibile solo l'emissione dell'estratto integrale che per default è sempre possibile.
In caso si desideri per quest'atto la possibilità di emettere anche certificati semplici ed estratti per riassunto, è possibile intervenire da centro; fateci sapere al riguardo con una email alla casella di supporto ansc supporto-ansc@sogei.it che ci autorizza.

IL problema sull'estratto integrale invece era dovuto ad un disservizio temporaneo immediatamente rientrato, per cui potete riprovare.
Chiudiamo pertanto la issue.
