### ISSUE TITLE
[R002] Certificazioni: Documento di riconoscimento non specificato.

### ISSUE THREAD

**Issue by gcuci** [italia/ansc#122]
Buongiorno

segnaliamo che con l'ultimo aggiornamento (1.8.0), la risposta del servizio è cambiata, ma ci restituisce sempre un'anomalia. Di seguito la Response ricevuta, da cui si evince l'idOperazione:

{
    "testataRisposta": {
        "idComune": 595,
        "idOperazioneComune": "1034",
        "idOperazione": "1590946"
    },
    "errors": [
        {
            "code": "400001",
            "severity": "E",
            "text": "Documento di riconocimento non specificato"
        }
    ]
}

Nel caso di esempio abbiamo valorizzato i due ModelSoggetto (richiedente ed intestatario), entrambi con i dati dell'intestatario (è lo sposo di un evento di Matrimonio).

Potete darci anche indicazioni più precise su come deve essere valorizzato il richiedente (chi può esserlo), e quali i dati obbligatori per entrambi i ModelSoggetto?

In attesa di un riscontro,

cordiali saluti.

**Comment by asqueglia** [comment]
Buongiorno, verifichiamo e le faremo sapere il prima possbile.
