### ISSUE TITLE
[SC]: Errore Firma Attestazione Conformità 

### ISSUE THREAD

**Issue by KibMcris** [italia/ansc#1222]
### Ambiente

produzione

### Servizio

R007 - Servizi cooperativi firma ufficiale di stato civile

### idOperazione

663761

### idEvento o idAnsc

2024-38527-71-050029

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Pontedera

### Data del test (yyyy-mm-dd)

31-12-2024

### Descrivi il problema

Dopo aver convalidato correttamente l'atto 2024-38527-71-050029, l'Ufficiale di stato civile ha tentato di firmare l'attestazione di conformità degli allegati. Sia da servizi cooperativi che da webapp di ANSC, viene restituito l'errore:

`HTTP Status 400 
{"errors":[{"code":"406004","severity":"E","text":"Firma non avvenuta con successo"}],"infos":[{"code":"110527","severity":"I","text":"Informazioni sull'operazione da fornire in caso di assistenza : data:2024-12-31 08:28:16 , idOperazione:663761"}],"testataRisposta":{"idComune":7460,"idEsito":1,"idOperazione":"663761","idOperazioneComune":"7346"}}`

Per l'atto attualmente non è possibile concludere l'iter.
Si resta in attesa di riscontro
Grazie

**Comment by siscomanpr** [comment]
Anche alcuni nostri clienti ci segnalano lo stesso errore in fase di firma, sia dell'attestazione che firma USC.

Siscom SPA

**Comment by biadanpad** [comment]
Anche Lissone sta riscontrando lo stesso problema. E' urgente il ripristino dei servizi

**Comment by gbuemi** [comment]
Buongiorno @KibMcris @siscomanpr @biadanpad,
la questione è rientrata.

Un saluto,
Supporto ANSC
