### ISSUE TITLE
[SC]: Validazione - Atto di Morte - msg. "Verifica allegato in corso" - atto bloccato

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/ansc#1223]
### Ambiente

produzione

### Servizio

R009 - Servizi cooperativi validazione evento

### idOperazione

665169

### idEvento o idAnsc

non assegnato

### Provenienza segnalazione

Comune

### Comune di riferimento e operatore

San Lazzaro di Savena

### Data del test (yyyy-mm-dd)

2024-12-31

### Descrivi il problema

si tenta di validare atto di morte con idOperazioneAnsc 665169.
la validazione va in errore a causa di verifica degli allegati sempre in corso da circa 45 minuti.
la registrazione dell'atto è bloccata.
potete verificare ed intervenire?
grazie
Alessandro ADS

**Comment by siscomanpr** [comment]
Anche alcuni nostri clienti ci segnalano lo stesso problema con la validazione degli atti per la validazione degli allegati.

Siscom SPA

**Comment by rvinzani** [comment]
Buongiorno, abbiamo preso in carico il problema. Vi faremo sapere appena possibile

**Comment by biadanpad** [comment]
Anche Lissone sta riscontrando lo stesso problema. E' urgente il ripristino dei servizi

**Comment by KibMcris** [comment]
Anche Tropea sta riscontrando lo stesso problema.

**Comment by rvinzani** [comment]
Il problema sembra rientrato. Potete per favore provare e darci un riscontro?

**Comment by biadanpad** [comment]
Da Lissone dicono che sono riusciti ad allegare i file correttamente

**Comment by siscomanpr** [comment]
I comuni che ci hanno segnalato il problema sono riusciti a validare allegati e atti.

**Comment by KibMcris** [comment]
Anche Tropea è riuscito correttamente ad allegare i documenti

**Comment by AMonopoliADS** [comment]
la validazione è andata a buon fine, ma il cliente segnala di non riuscire a firmarlo.
sembrerebbe lo stesso problema segnalato in altra issue... (ultimo tentativo ore 11:19)
problema di firma, appena segnalato anche dal comune di Lama Mocogno

**Comment by gbuemi** [comment]
@AMonopoliADS non riscontriamo problemi generalizzati, potete fornirci un idoperazione per quest'ultima segnalazione.
Grazie

**Comment by AMonopoliADS** [comment]
a San Lazzaro sono riusciti a firmare l'atto alle 11:53.
a Lama Mocogno l'errore di firma era associato alla comunicazione con idOperazioneAnsc 667471 delle 11:42.
ma anche loro sono riusciti a completare l'atto, per tentativi successivi, alle 11:55
