### ISSUE TITLE
Chiarimenti per Firma e Presa Visione

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#124]
Buonasera, 
in uno dei test eseguiti, dopo aver validato un atto di nascita (IdAnsc=2023-952458-66-108028) ho richiamato il servizio di presa visione e successivamente ho portato a termine una delle 2 firme elettroniche attese.
A questo punto se provo a chiamare nuovamente il servizio di presa visione, ricevo il seguente errore:

{
    "testataRisposta": {
        "idComune": 5000,
        "idOperazione": "1591294",
        "idEsito": 1
    },
    "errors": [{
            "code": "400003",
            "severity": "E",
            "text": "Lo stato dell'atto non e' CONFERMATO e non consente l'operazione"
        }
    ]
}

Non c'è modo, dopo aver applicato una delle firme attese, di visionare nuovamente l'atto?

**Comment by amusarra** [comment]
Buongiorno @biadanpad 
Dopo che il firmatario/i hanno eseguito la presa visione, non è possibile tornare indietro, quindi il messaggio è corretto.
Chiudo la issue. Per eventuali questioni, riapra la issue.

Cordiali Saluti.
Supporto ANSC.

**Comment by biadanpad** [comment]
Lavorando con la WebApp, se per errore chiudo il browser dopo aver ad esempio portato a termine 1 firma elettronica su due, non posso portare a termine la procedura di firma inquanto non c'è la possibilità di ricaricare l'atto per firmarlo.
