### ISSUE TITLE
[R012] Invio email per firma elettronica dichiarante - servizio non disponibile [continuo della #126]

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#128]
Sembra che ci siano ancora problemi:

![image](https://github.com/italia/ansc/assets/131870281/4c470477-9fba-4778-82fe-ac1119e27a44)

**Comment by amusarra** [comment]
Salve @biadanpad 
È molto probabile che il link sia scaduto da quando sia stato generato.
Al fine di poter verificare sui log del sistema abbiamo bisogno di conoscere l'identificativo dell'evento, idOperazione e link ottenuto via email

Cordiali Saluti.
Supporto ANSC.

**Comment by biadanpad** [comment]
E' probabile che stessi provando a firmare un documento già firmato..
Grazie

**Comment by amusarra** [comment]
@biadanpad well done!
