### ISSUE TITLE
[web-service] Atti di Nascita - Indicazione del sesso

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/ansc#131]
in sede di validazione di atto, il sistema accetta l'indicazione del sesso con lettere minuscole (in generale, nei dati del soggetto intestatario / padre / madre).
tutto il processo di perfezionamento dell'atto (comprensivo di firma) va a buon fine, ma andando ad interrogare l'atto nella web-app il sesso non viene valorizzato.

vedere come esempio l'atto con idAnsc 2023-952659-72-039010

qual è il problema?

il sesso va mandato in maiuscolo (e quindi forse il sistema non dovrebbe accettare il minuscolo)?
oppure c'è un problema di visualizzazione nella web-app?

grazie
Alessandro Monopoli ADS

**Comment by asqueglia** [comment]
Buongiorno con la versione 1.9.0 appena rilasciata abbiamo corretto l'errore. E' possibile riprovare. chiudiamo la issue in caso vi preghiamo di riaprirla.
