### ISSUE TITLE
Chiarimento: Atto Definitivo

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#132]
Buonasera, 
una volta completata la procedura delle firme dei dichiaranti e USC, quale servizio (e con quali parametri) dobbiamo invocare al fine di ottenere il file PDF definitivo dell'atto?

**Comment by asqueglia** [comment]
Buongiorno, per ottenere la copia conforme all'originale è necessario utilizzare il servizio di certificazione R002 specificando la tipologia di certificato 3 = 'Estratto integrale'. Può trovare un esempio di payload nella documentazione al path seguente
docs/CasiTest/payload_test/R002_certificazione.json
