### ISSUE TITLE
Chiarimento: Stato Firma Elettronica

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#134]
Buonasera, 
esiste un modo per conoscere lo stato della firma elettronica di ogni singolo firmatario?

Al momento mi sembra di capire che il servizio di "pooling-statoatto" R012 ritorna 4 solo quando tutti i dichiaranti hanno firmato, anche se in input gli viene passato l'idPresaVisione ritornato dal servizio "invio-email" R012

**Comment by amusarra** [comment]
Buongiorno @biadanpad 
Così come indicato dalle [OpenAPI](https://github.com/italia/ansc/blob/ed5461cb526ac201b69cc5f979bf336511aa9f28/docs/openapi/R012_firma_dichiarante_elettronica.yaml#LL230C27-L230C27), il servizio restituisce lo stato dell'evento e non della presa visione.

Per voi sarebbe utile ottenere anche lo stato della presa visione?

Cordiali Saluti.
Supporto ANSC.

**Comment by amusarra** [comment]
Salve @biadanpad 
Accogliamo il vostro suggerimento verificando se possibile inserire come miglioria al servizio di presa visione.
Chiudo questa issue.

Cordiali Saluti.
Supporto ANSC.

**Comment by biadanpad** [comment]
Buonasera, 
a mio avviso non è una miglioria ma una necessità: supponiamo di dover fare 2 firme elettroniche. Invio la mail di richiesta a entrambi, uno dei 2 firma mentre l'altro no. Dopo 15 minuti (tempo di timeout della validità dei link) il secondo non ha ancora firmato. Se a questo punto richiamo  il servizio di "pooling-statoatto" R012 con entrambi gli idPresaVisione, lo stato della firma per entrambi sarà "link non più valido" anche se uno dei due ha firmato.
Nella WebApp, posso vedere in ogni momento chi ha firmato e chi no. Questo tipo di servizio è quello che mi aspettavo fosse riportato anche nelle API.
Vorrei un orizzonte temporale per capire in che direzione sviluppare la nostra applicazione.
