### ISSUE TITLE
Errore Visualizzazione Atto di Nascita con caso d'uso 11999999

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#136]
Dopo aver firmato un Atto di Nascita con caso d'uso 11999999 (firma effettuata sia da dichiaranti sia da USC) non riesco a fare nessuna anteprima (nè come bozza nà per presa visione).

Anche la WebApp ha dei problemi credo analoghi:
![image](https://github.com/italia/ansc/assets/131870281/680e1233-e0a5-4240-9a66-7ff36f11a8dc)

**Comment by asqueglia** [comment]
Buongiorno verifichiamo e le facciamo sapere quanto prima

**Comment by amusarra** [comment]
Buongiorno @biadanpad
La stessa anomalia è stata segnalata dalla issue #135 e la causa è la medesima.

Cordiali Saluti.
Supporto ANSC.

**Comment by biadanpad** [comment]
Grazie, 
in questo modo ho risolto il problema.

Quale servizio devo richiamare per ottenere lo stesso PDF che mi viene generato cliccando il tasto "Visualizza Pdf" della WebApp?
Ho provato con il servizio di anteprima ma ricevo il seguente codice di errore:
{
    "testataRisposta": {
        "idComune": 5000,
        "idOperazione": "1592862",
        "idEsito": 1
    },
    "errors": [{
            "code": "400003",
            "severity": "E",
            "text": "Lo stato dell'atto non e' CONFERMATO e non consente l'operazione"
        }
    ]
}

**Comment by biadanpad** [comment]
Sonoriuscito ad ottenere il PDF usando il servizio R002, grazie.
