### ISSUE TITLE
Chiarimento: Stato Firma Elettronica - prosegue la #134

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#137]
Buonasera, 
a mio avviso non è una miglioria ma una necessità: supponiamo di dover fare 2 firme elettroniche. Invio la mail di richiesta a entrambi, uno dei 2 firma mentre l'altro no. Dopo 15 minuti (tempo di timeout della validità dei link) il secondo non ha ancora firmato. Se a questo punto richiamo  il servizio di "pooling-statoatto" R012 con entrambi gli idPresaVisione, lo stato della firma per entrambi sarà "link non più valido" anche se uno dei due ha firmato.
Nella WebApp, posso vedere in ogni momento chi ha firmato e chi no. Questo tipo di servizio è quello che mi aspettavo fosse riportato anche nelle API.
Vorrei un orizzonte temporale per capire in che direzione sviluppare la nostra applicazione.

**Comment by asqueglia** [comment]
Buongiorno, abbiamo preso in carico la richiesta. Il servizio di verifica stato sarà esteso in modo da consentire la verifica di ogni singola firma.

**Comment by amusarra** [comment]
Chiudiamo la issue per via del rilascio della versione 1.10.0 che risolve questa segnalazione.

Cordiali Saluti.
Supporto ANSC.
