### ISSUE TITLE
[web-service] Errore "Nessun dato associato all'utente"

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/ansc#139]
ambiente PRE-PROD - comune di FAENZA (id 3743)

servizio R001 - Upload 
(endpoint: https://anscservicepre.anpr.interno.it/services/service/doc/allegato/upload/1)
(idOperazioneComune 2023000482)
inviata due volte:
- al primo tentativo di invio (idOperazioneAnsc 1593153) la response ha segnalato l'errore 404002 - Nessun dato associato all'utente
- al secondo tenativo (idOperazioneAnsc 1593167), l'invio ha avuto esito positivo.

stessa cosa (sullo stesso atto) per servizio R009 - Validazione
(https://anscservicepre.anpr.interno.it/services/service/val/validazione/evento/1)
(idOperazioneComune 2023000481)
- al primo tentativo (idOperazioneAnsc 1593169), la response ha segnalato l'errore 404002 - Nessun dato associato all'utente
- al secondo tentativo (idOperazioneAnsc 1593173), l'invio ha avuto esito positivo

le request mi sembra siano le medesime.
c'è qualcosa che dipende da noi che ha scatenato questi errori?

grazie
Alessandro Monopoli ADS

**Comment by amusarra** [comment]
Salve @AMonopoliADS 
L'errore deriva dal fatto che l'otp ricevuto è errato, nel caso specifico è stato impostato a `123465` invece di `123456`. 
Chiudiamo la issue.

Cordiali Saluti.
Supporto ANSC.
