### ISSUE TITLE
[R005] - Servizio consultazione evento

### ISSUE THREAD

**Issue by ManuelDeMeo** [italia/ansc#14]
Buongiorno,
segnalo un potenziale problema riguardo il servizio R005 /consultazione/ansc/soggetto/1

Se la richiesta contiene il codice fiscale, non otteniamo niente in risposta. Viceversa con gli stessi parametri (escluso il codice fiscale) otteniamo il risultato aspettato.

Inserisco le richieste sotto.

Richiesta che restituisce l'evento:
`{
   "criteriRicercaSoggetto":{
      "idAnpr":null,
      "codiceFiscale":null,
      "cognome":"DE MEO",
      "nome":"MATTEA",
      "sesso":"F",
      "idComuneNascita":"4559",
      "nomeComuneNascita":"GROTTAFERRATA",
      "siglaProvinciaNascita":"RM",
      "codiceStatoNascita":"100",
      "nomeStatoNascita":"ITALIA",
      "datanascita":"2023-03-06"
   },
   "testataRichiesta":{
      "idComune":4559,
      "idOperazioneComune":"2",
      "dataOraRichiesta":"2023-03-08",
      "nomeApplicativo":"testSC",
      "versioneApplicativo":"1.0.0",
      "fornitoreApplicativo":"Test"
   },
   "datiPaginazione":null
}`
Richiesta che non restituisce nulla:
`{
   "criteriRicercaSoggetto":{
      "idAnpr":null,
      "codiceFiscale":"DMEMTT23C46E204T",
      "cognome":"DE MEO",
      "nome":"MATTEA",
      "sesso":"F",
      "idComuneNascita":"4559",
      "nomeComuneNascita":"GROTTAFERRATA",
      "siglaProvinciaNascita":"RM",
      "codiceStatoNascita":"100",
      "nomeStatoNascita":"ITALIA",
      "datanascita":"2023-03-06"
   },
   "testataRichiesta":{
      "idComune":4559,
      "idOperazioneComune":"2",
      "dataOraRichiesta":"2023-03-08",
      "nomeApplicativo":"testSC",
      "versioneApplicativo":"1.0.0",
      "fornitoreApplicativo":"Test"
   },
   "datiPaginazione":null
}`

**Comment by mttfranci** [comment]
Salve, @ManuelDeMeo

Suggeriamo, nell'aprire, le segnalazioni, di seguire le indicazioni del template sull'apertura issue : 
https://github.com/italia/ansc/blob/main/.github/ISSUE_TEMPLATE.md

In particolare sarebbe utile avere, oltre al payload : 
* Ambiente in cui il comportamento è stato verificato
* Url richiamata
* Id operazione e/o payload della risposta.
 
Grazie in anticipo.

Saluti

Assistenza ANSC

**Comment by ManuelDeMeo** [comment]
- Ambiente: preproduzione
- Url: https://anscservicepre.anpr.interno.it/services/service/ricerca/consultazione/ansc/soggetto/1
- Id operazione delle due richieste di cui alla segnalazione sono rispettivamente: 1561479 e 1561480

**Comment by mttfranci** [comment]
Salve.
Allora è normale che non troviate il soggetto per codice fiscale in quanto al momento della registrazione dell'evento di nascita, giustamente non è stato fornito il codice fiscale (che al momento della registrazione dell'evento di nascita non è solitamente disponibile).

Ci sembra anche di aver individuato l'evento 2023-949674-12-058046, inviato con operazione 1561329. (e in effetti il codice fiscale non sembra presente neanche nel payload)

Da tenere presente che i soggetti intestari vengono ricercati solo nell'anagrafica dello stato civile. 

Saluti

Assistenza ANSC
