### ISSUE TITLE
[R006] Firma Dichiarante - errore: firmatario non presente per l'evento

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#140]
Chiamando il servizio R006 per un atto con caso d'uso 11111000 ricevo l'errore in oggetto anche se il soggetto indicato nel payload è uno dei firmatari (vedi estratto per copia integrale allegato).
Di seguito il playload e la response

PAYLOAD:
{
    "firmaDichiaranteInput": {
        "contenuto": "JVBERi0xLjcKCjQgMCBvYmoKCiUlRU9GCg\u003d\u003d",
        "protocollo": "123/2023",
        "nomefile": "aaaaaaaa.pdf",
        "idEvento": "952939",
        "tipoFile": "1",
        "tipoAllegato": "999",
        "stato": "1",
        "listaFirmatari": [{
                "nome": "ZIO",
                "cognome": "ROBA",
                "codiceFiscale": "RBOZIO78D02H620K",
                "sesso": "M",
                "dataNascita": "1978-04-02"
            }
        ]
    },
    "testataRichiesta": {
        "idComune": 5000,
        "nomeApplicativo": "urbi",
        "versioneApplicativo": "0.1.0",
        "fornitoreApplicativo": "padigitale"
    },
    "datiPaginazione": {
        "numRecordTotali": 0
    }
}

RESPONSE:
{
    "errors": [{
            "code": "400003",
            "severity": "E",
            "text": "Uno o più soggetti firmatari indicati non presenti per l'evento fornito"
        }
    ],
    "testataRisposta": {
        "idComune": 5000,
        "idEsito": 1,
        "idOperazione": "1593687"
    }
}

ESTRATTO PER COPIA INTEGRALE:
[Estratto per copia integrale.pdf](https://github.com/italia/ansc/files/11573029/Estratto.per.copia.integrale.pdf)

**Comment by amusarra** [comment]
Salve @biadanpad
Per l'evento in questione i firmatari sono tre. Alla chiamata al servizio di firma occorre quindi passare la lista dei tre firmatari o non passarne nessuno nel caso dovessero firmare tutti in modo autografo.

Il `codiceFiscale` non andrebbe passato visto che in fase di validazione non è stato inserito.

La invitiamo quindi a riprovare. Nel frattempo chiudiamo la issue, nel caso fosse necessario la riapra.

Cordiali Saluti.
Supporto ANSC.
