### ISSUE TITLE
Chiarimento: scaricamento atto dopo la firma USC

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#141]
Buongiorno, 
quale servizio (e con quale parametri) devo invocare per ottenere l'atto a valle della firma dell'Ufficiale di Stato Civile?
Intendo dire lo stesso file PDF che posso scaricare dalla WebApp cliccando il tasto "Ottieni atto registrato" (vedi immagine)
![1](https://github.com/italia/ansc/assets/131870281/dfc5c749-f9a0-491e-ba84-36fc52617ee9)

**Comment by amusarra** [comment]
Buongiorno @biadanpad 
Il servizio da utilizzare per ottenere l'Estratto per copia integrale è [{{R002}}/certificato](docs/openapi/R002_certificazione.yaml) utilizzando il valore 3 per l'attributo [idTipoCertificato](https://github.com/italia/ansc/blob/0a6af710e9b70f619b3cb00f9d9bed65b8cef8e4/docs/openapi/R002_certificazione.yaml#L71).

Chiudiamo la issue, se fosse necessario la riapra.

Cordiali Saluti.
Supporto ANSC.
