### ISSUE TITLE
Segnalazione su model_evento.yaml - Format date

### ISSUE THREAD

**Issue by siscomanpr** [italia/ansc#142]
Nel file yaml del model evento alcuni campi che contengono delle date sono correttamente indicati con `format: date` come da specifiche OpenApi, ma allo stesso tempo alcuni campi non lo sono (es: ModelSoggetto -> dataNascita oppure ModelEnteDichiarante -> dataTrascrizione).
È possibile uniformare le specifiche in modo i campi data abbiano le stesse specifiche?

**Comment by amusarra** [comment]
Salve @siscomanpr 
Abbiamo preso in carico la sua segnalazione che abbiamo in pianificazione.

Cordiali Saluti.
Supporto ANSC

**Comment by asqueglia** [comment]
Buongiorno confermiamo che con il rilascio della versione 1.9.1 la segnalazione è stata corretta. E' possibile riprovare. Chiudiamo la issue, nel caso la preghiamo di riaprirla.

**Comment by siscomanpr** [comment]
Buongiorno, 

Abbiamo verificato e effettivamente sono state aggiunte le format, tranne nel campo dataAtto di ModelAttoCollegato.
È possibile aggiungerlo anche in quel campo?
