### ISSUE TITLE
Problema invocazione servizi ANSC

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#144]
Buongiorno,
premetto che l'azienda per cui lavoro ed un'altra si collabora nello sviluppo del software con l'integrazione ad ANSC. Quindi stesso software ma che viene testato su macchine diverse.
All'altra azienda funziona quasi tutto, a me va in timed out la connessione già al servizio di Invio allegati (se presente un documento da inviare) oppure con quella successiva di Validazione atto.
Accedo con utente collegato al mio codice fiscale, ho installato tutti i certificati (infatti alla webapp accedo senza problemi).
L'URL che invochiamo è questo: https://anscservicepre.anpr.interno.it/services/service/val/validazione/evento/1

**Comment by amusarra** [comment]
Buongiorno @annamaraspin 
Sulla chiamata ai servizi non c'è un filtro sull'indirizzo IP sorgente, per cui, se entrambe i chiamanti hanno gli stessi requisti in termini di certificati dovrebbe esserci alcun problema.

Se la connessione va in timeout (immagino che abbiate verificato lo stacktrace) per tutti i servizi, consiglio di verificare che questa non sia bloccata da qualche componente della vostra rete.

Potremmo fare un primo controllo se fornisce l'idOperazione, con cui potremmo verificare se la chiamata è arrivata sul sistema.

Cordiali Saluti.
Supporto ANSC.

**Comment by annamaraspin** [comment]
Mi dispiace ma non posso darLe nessun IdOperazione perché non avviene nemmeno il dialogo con i Vostri servizi.
Riprovo a richiedere ai colleghi.
Grazie mille

**Comment by amusarra** [comment]
Provate a escludere problemi di rete e ottenere uno stacktrace dell'errore ed eventualmente tracciare la chiamata con Wireshark o tool similari.

Cordiali saluti.
Supporto ANSC

**Comment by amusarra** [comment]
Buongiorno @annamaraspin 
Avete avuto modo di riprovare? Non credo che sia un problema legato ai servizi.
Fateci sapere, nel frattempo chiudiamo la issue, nel caso di problemi con i servizi non esitate a riaprire.

Cordiali Saluti.
Supporto ANSC.

**Comment by annamaraspin** [comment]
Buongiorno,
mi scusi se non mi sono fatta viva prima... i miei colleghi ci stanno lavorando sopra, sto attendendo loro notizie.
Grazie mille per l'aiuto
