### ISSUE TITLE
Casi d'Uso 341000- 342000- 343000 (Separazioni e Divorzi)

### ISSUE THREAD

**Issue by KibMcris** [italia/ansc#145]
Ambiente di pre-produzione

Stiamo implementando i casi d'uso in oggetto (Accordo di separazione, accordo di scioglimento e cessazione effetti civili e conferme degli accordi). 

Ci siamo accorti che, pur indicando i metadati degli eventuali avvocati presenti questi non vengono riportati nell'anteprima dell'atto.

Inoltre, occorre prevedere che gli avvocati debbano (in questi casi) sottoscrivere gli atti al pari dei coniugi dichiaranti. Abbiamo provato anche da WEB APP e non sembra prevista la firma da parte degli avvocati.
Precisiamo che nell'effettuare la richiesta di validazione ad ANSC, abbiamo specificato flagfirmatario=true per entrambi gli avvocati.
Vedere idOperazione ANSC=1594475

Nei medesimi casi d'uso, consultando la documentazione, l'oggetto datiEventoMatrimonio, non risulta tra quelli da specificare.
Nell'anteprima dell'atto però viene visualizzata tale sezione e valorizzata la seguente Data trasmissione: 01/01/0001.
Vedere Atto 953020

Inoltre da oggi pomeriggio, al momento delle firme, l'errore:
HTTP Status 400 
{"errors":[{"code":"406004","severity":"E","text":"Firma non avvenuta con successo"}],"testataRisposta":{"idComune":10288,"idEsito":1,"idOperazione":"1594450","idOperazioneComune":"11"}}

Andando su WEBAPP troviamo che l'atto risulta nello stato "FIRMATO DAL DICHIARANTE".

**Comment by KibMcris** [comment]
L'errore sulla firma sembra risolto.

**Comment by asqueglia** [comment]
Buongiorno, è stata rilasciata la versione 1.9.1. Potete verificare se il problema si ripresenta ? in caso ci fosse ancora qualcosa da segnalare  la preghiamo di specificare nel dettaglio il problema che si presenta fornendo l'idoperazione effettuata in modo da poter verificare più celermente.
