### ISSUE TITLE
Filiazione fuori dal matrimonio senza riconoscimento

### ISSUE THREAD

**Issue by antonioluberto** [italia/ansc#146]
Atto di nascita.
Nel caso di "filiazione fuori dal matrimonio senza riconoscimento", in assenza di caso d'uso appositamente modellato, facciamo riferimento al "Dic_Nasc_999".
La modellazione prevede per "Dic_Nasc_999" l'indicazione di padre/madre (che in questo caso non ci sono) mentre non prevede l'indicazione del dichiarante (che certamente c'è e deve poter sottoscrivere l'atto).

Da un controllo su WebApp:
a) nel caso di filiazione fuori dal matrimonio, non è possibile indicare se la filiazione medesima avvenga con o senza riconoscimento.
b) non è possibile indicare come dichiarante un soggetto diverso da
Padre
Madre
Procuratore del padre
Procuratore della madre

E' certamente necessario introdurre la gestione necessaria affinché l'usc possa recepire la dichiarazione di nascita (da parte di soggetto che abbia assistito al parte, da parte del direttore di istituto per minori presso il quale sia stato consegnato il nato, da altro soggetto) riferita a "filiazione fuori dal matrimonio senza riconoscimento", redigere l'atto, consentirne la sottoscrizione al dichiarante, produrre le comunicazioni previste.

**Comment by antonioluberto** [comment]
Nel caso di specie in effetti la dichiarazione di nascita può essere resa da soggetto che non ha assistito al parto (esempio: il direttore dell'istituto per minori presso il quale sia avvenuto il ritrovamento del nato); ci parrebbe pertanto più corretto il riferimento ad altro specifico caso d'uso, mantenendo in generale sul Dic_Nas_999 la possibilità di indicare in dichiarante terzo.
Ciò detto, applicativamente possiamo certamente ricondurre il caso di specie al caso d'uso [1.1.3.1.5.0.0.0] .
Attendiamo vostre indicazioni finali

**Comment by asqueglia** [comment]
Buongionro, se non vedete altri problemi, confermiamo che va bene ricondurre il caso al 1.1.3.1.5.0.0.0

**Comment by asqueglia** [comment]
La issue viene chiusa; in caso di ulteriori problemi si prega di aprirne una nuova.
