### ISSUE TITLE
Notifiche per aggiornamento anagrafe

### ISSUE THREAD

**Issue by antonioluberto** [italia/ansc#147]
In attesa di indicazioni rispetto a #119 , con la presente si richiede un chiarimento di carattere generale sulla gestione delle notifiche che, a seguito di specifico evento di Stato Civile,  dovranno essere recepite per il successi aggiornamento di ANPR. 
La generazione del procedimento anagrafico collegato ad un dato evento di stato civile richiede l'indicazione di riferimenti anagrafici che al momento ci pare non siano previsti in modellazione; 
esempio:
per generare il procedimento d'iscrizione in anagrafe del titolare di un atto di nascita è certamente necessario conoscere quale sia la famiglia anagrafica nella quale il titolare debba confluire. Manca però attualmente in modellazione la possibilità di indicare l'identificativo ANPR della famiglia di destinazione (ovvero della convivenza anagrafica di destinazione, nel particolare caso di filiazione senza riconoscimento).

E' previsto aggiornamento a breve della documentazione nel senso sopra descritto?

**Comment by amusarra** [comment]
@antonioluberto il sistema ANSC invia nella notifica di predisposizione verso il sistema ANPR i soli dati di competenza dello Stato Civile, sarà poi l'ufficiale di Anagrafe a fare le verifiche del caso sulla predisposizione ricevuta e le successive azioni.

Chiudiamo la issue.

Cordiali Saluti.
Supporto ANSC.
