### ISSUE TITLE
Tabella 53 Ansc- Tipo Accordo Separazione/Divorzio

### ISSUE THREAD

**Issue by KibMcris** [italia/ansc#148]
Ambiente di pre-produzione

Poiché, a seguito di divorzio, è possibile con un atto di accordo (che non deve essere confermato con un secondo atto), modificare le condizioni del divorzio tramite dichiarazione all'ufficiale dello stato civile oppure tramite negoziazione assistita di fronte agli avvocati, occorrerebbe aggiungere una nuova codifica nella tabella 53 di ANSC (53_dec_tipo_accordo_separazione.xlsx) corrispondente alla modifica delle condizioni di scioglimento/cessazione effetti civili.

Questa ulteriore codifica servirebbe per gestire tutte le possibilità con il caso d'uso 345000-Trascrizione della convenzione di negoziazione assistita ai sensi dell’art.6 Decreto-legge n.132/2014 convertito con Legge 10.11.2014 n.162

**Comment by asqueglia** [comment]
Buongiorno grazie mille per la segnalazione; verificheremo e le faremo sapere.
