### ISSUE TITLE
[ws R002] Certificazione - msg. "Errore nella validazione del JWS"

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/ansc#149]
ambiente pre-produzione - comune di FAENZA (idComune 3743)
endpoint: https://anscservicepre.anpr.interno.it/services/service/certificazione/certificato/1

il servizio di certificazione ci restituisce l'errore in oggetto.
escludendo un problema nella creazione del JWS, mi aspetto che il messaggio nasconda invece qualche anomalia nella struttura della request, che non riusciamo ad individuare.

dalle prove fatte, se escludo dalla request la sezione "richiedente", il servizio ritorna un errore consistente che è
"Soggetto richiedente non valido"
se aggiungo la sezione "richiedente" (che mi sembra avere le caratteristiche dell'esempio che avete pubblicato) il servizio restituisce l'errore "... nella validazione del JWS".

alcuni esempi di comunicazioni che potete verificare sono:
- idOperazioneComune 2023000560 (richiesta di certificato semplice) abbiamo provato passando anche l'idSoggettoAnpr pur non essendo obbligatorio
- idOperazioneComune 2023000561 (richiesta di estratto per riassunto) senza idSoggettoAnpr
- idOperazioneComune 2023000562 (richiesta di estratto integrale) senza idSoggettoAnpr

per tutti questi esempi il risultato è il medesimo.
ci sarebbe utile capire cosa non va nella request.

grazie
Alessandro Monopoli ADS

**Comment by amusarra** [comment]
Salve @AMonopoliADS 
Immagino che abbiate letto il documento [SpecificheTecnicheServiziCooperativiJWT_v1.1.0.pdf ](https://github.com/italia/ansc/blob/dcc6dc23787abf34509ee2d783e359c4cc5728d9/docs/Note/SpecificheTecnicheServiziCooperativiJWT/SpecificheTecnicheServiziCooperativiJWT_v1.1.0.pdf) e in particolare la sezione delle FAQ dove sono riportati i più comuni problemi, come quello da voi riportato.

Da come avete scritto, sembra che il problema sia dovuto alla presenza dell'oggetto `richiedente` che per qualche motivo crea il problema. Avete verificato che il payload d'esempio non abbia qualche carattere "particolare" che potrebbe creare qualche problema al framework che usate per generare il JWS e in particolare la signature?

Vi consiglio di leggere il 3 punto della FAQ del documento menzionato in precedenza. Solitamente quello risolve il problema.

Nel caso di ulteriori problemi non esitate a scrivere su questa issue.

Cordiali Saluti.
Supporto ANSC.

**Comment by asqueglia** [comment]
Buongiorno dalle verifiche effettuate sulla operazione indicata, abbiamo notato che il payload della richiesta inviata riporta l'elemento 'Richiedente' anzichè 'richiedente' (tutto in minuscolo), da ciò l'errore restituito 'Soggetto richiedente non valido'.
Comunichiamo però che c'è un bug già preso in carico, che riguarda l'obbligatorietà del documento di riconoscimento richiesto per il richiedente, che stiamo provvedendo a correggere.
Come workaround potete aggiungere, solo per il momento, il documento di riconoscimento con il numero.

Di seguito il payload della richiesta corretta che potete provare

{
    "testataRichiesta": {
        "idComune": "xxx",
        "idOperazioneComune": xxxx,
        "dataOraRichiesta": "2023-05-30T14:22:13",
        "nomeApplicativo": "xxx",
        "versioneApplicativo": "xxxx",
        "fornitoreApplicativo": "xxx"
    },
    "idAnsc": "2023-xxx-xx-xxxx",
    "idEvento": xxxx,
    "intestatario": {
        "id": xxxx
    },
    "**richiedente**": {
        "idSoggettoAnpr": 27996119,
        "codiceFiscale": "xxxxx",
        "cognome": "xxx",
        "nome": "xx",
        "sesso": "M",
        "dataNascita": "1972-02-08",
        "idComuneNascita": "6002",
        "nomeComuneNascita": "MONTEGRANARO",
        "idProvinciaNascita": "44",
        "siglaProvinciaNascita": "AP",
        "idStatoNascita": "90",
        "nomeStatoNascita": "ITALIA",
        "idComuneResidenza": "3743",
        "nomeComuneResidenza": "FAENZA",
        "idProvinciaResidenza": "39",
        "siglaProvinciaResidenza": "RA",
        "idStatoResidenza": "90",
        "nomeStatoResidenza": "ITALIA",
        "idNazionalita": "90",
        "nazionalita": "ITALIANA", 
        **"documentoRiconoscimento": {
            "numeroDocumento": "XXXX"
        }**
    },
    "idTipoCertificato": "1"
}

avviseremo appena abbiamo corretto il bug dichiarato relativo alla obbligatorietà del documento riconoscimento

**Comment by AMonopoliADS** [comment]
grazie Angela (e grazie anche Antonio ovviamente)

stavo proprio rispondendo anche io per argomentare i motivi per cui ritenevo che il problema non fosse nel JWS, ma nel 
contenuto dei dati (anche perchè in passato abbiamo avuto una situazione analoga con il servizio R010)

immagino (e spero) che la soluzione del bug sia un messaggio che indichi esplicitamente l'assenza del dato obbligatorio.

preciso, comunque, che nel payload pubblicato come esempio anche con la 1.8.1 non c'è traccia dell'oggetto documentoRiconoscimento.

grazie per i riscontri.
Alessandro

**Comment by AMonopoliADS** [comment]
@asqueglia l'aggiunta dell'oggetto "documentoRiconoscimento" non ha risolto il problema.
ho provato anche ad includere tutti gli elementi del documento (non solo il numero) ma ottengo lo stesso risultato.
per evitare refusi da vecchie comunicazioni ho provato a creare nuovi id, che sono questi:
- idOperazioneComune 2023000564 (con tutti gli elementi del documentoRiconoscimento)
- idOperazioneComune 2023000565 (con solo il numeroDocumento)
- idOperazioneComune 2023000566 (con solo il numeroDocumento)

**Comment by amusarra** [comment]
> grazie Angela (e grazie anche Antonio ovviamente)
> 
> stavo proprio rispondendo anche io per argomentare i motivi per cui ritenevo che il problema non fosse nel JWS, ma nel contenuto dei dati (anche perchè in passato abbiamo avuto una situazione analoga con il servizio R010)
> 
> immagino (e spero) che la soluzione del bug sia un messaggio che indichi esplicitamente l'assenza del dato obbligatorio.
> 
> preciso, comunque, che nel payload pubblicato come esempio anche con la 1.8.1 non c'è traccia dell'oggetto documentoRiconoscimento.
> 
> grazie per i riscontri. Alessandro

@AMonopoliADS  riguardo il bug dell'obbligatorietà del `documentoRiconoscimento` sul servizio di certificazione, sarà oggetto del rilascio della versione 1.9.0 del sistema previsto per oggi 31/05/2023.

**Comment by AMonopoliADS** [comment]
abbiamo verificato che dopo il rilascio della v1.9.0 il documentoRiconoscimento non è più obbligatorio.
abbiamo nel contempo individuato la causa del disallineamento che produceva l'errore in validazione JWS.

grazie

**Comment by amusarra** [comment]
Ottimo @AMonopoliADS 
Provvediamo a chiudere la issue.

Cordiali Saluti.
Supporto ANSC.
