### ISSUE TITLE
Individuazione ID di comuni, province, stati e soggetti

### ISSUE THREAD

**Issue by SAlberto** [italia/ansc#15]
Buongiorno, 
come facciamo ad individuare i codici identificativi dei comuni, province e stati richiesti ad esempio nell'oggetto ModelSoggetto? 
Se un soggetto non è presente in ANSC immagino che il campo ID di ModelSoggetto possa essere lasciato vuoto. 
In qualche documento è disponibile l'elenco dei campi obbligatori? 
Ringrazio anticipatamente.
Cordiali saluti

**Comment by mttfranci** [comment]
Salve. 

gli identifativi di [stati](https://www.anagrafenazionale.interno.it/wp-content/uploads/2022/10/tabella_2_statiesteri.xlsx), [comuni e province](https://www.anagrafenazionale.interno.it/wp-content/uploads/ANPR_archivio_comuni.csv) sono quelli delle [decodifiche del sistema ANPR](https://www.anagrafenazionale.interno.it/area-tecnica/tabelle-di-decodifica/)

Ovviamente gli ID dei soggetti vanno indicati solo se disponibili. (però per gli eventi successivi al primo sullo stesso soggetto è opportuno indicarli).

In generale i campi obbilgiatori sono quelli presenti nella [documentazione di mapping.](https://github.com/italia/ansc/tree/main/docs/Mapping_casi_uso).

Ad ogni modo stiamo lavorando per rendere la documentazione il più possibile fruibile. (Ad esempio pensiamo di aggiornare la definizione del model evento con il riferimento alle tabelle di decodifica di comuni e stati).

Saluti

Assistenza ANSC
