### ISSUE TITLE
[ws R010 / R002] Anteprima / Certificazione: gestione del tipoFile

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/ansc#152]
ambiente pre-produzione - comune di FAENZA (idComune 3743)

segnalo una diversa gestione del campo tipoFile, nelle response dei servizi:
- R010 - anteprima evento (endpoint: https://anscservicepre.anpr.interno.it/services/service/anteprima/anteprima/evento/1)
- R002 - certificazione (endpoint: https://anscservicepre.anpr.interno.it/services/service/certificazione/certificato/1)

per entrambi i servizi la documentazione riporta alle codifiche registrate in tabella ANSC_10, ma succede quanto segue:
- per R010 (anteprima evento): il servizio restituisce tipoFile 'PDF' (quindi quello che in tabella è la DESCRIZIONE e non l'ID)
(vedere ad esempio idOperazioneAnsc 1595657)

pensavamo fosse normale così, invece i servizi di certificazione si comportano diversamente:
- per R002 (certificazione - idTipoCertificato '1'): il servizio restituisce tipoFile = '1' (sempre PDF, ma in questo caso l'ID)
(vedere idOperazioneAnsc 1595683)
- per R002 (certificazione - idTipoCertificato '2'): il servizio restituisce tipoFile = '2' (che da tabella '10' corrisponde a DOC, pur essendo il file "preview.pdf")
(vedere idOperazioneAnsc 1595684)
- per R002 (certificazione - idTipoCertificato '3'): il servizio restituisce tipoFile = '3' (che da tabella '10' corrisponde a TIF, pur essendo il file "preview.pdf")
(vedere idOperazioneAnsc 1595707)

alla luce di tutte le prove fatte, ho il sospetto che nella response del servizio R002 al posto del tipoFile sia stato indicato l'idTipoCertificato...
a parte questo primo bug, chiedo conferma definitiva di quale valore avete previsto debba essere restituito all'interno dell'elemento tipoFile.

grazie
Alessandro Monopoli ADS

**Comment by amusarra** [comment]
Buongiorno @AMonopoliADS 
Indubbiamente c'è l'anomalia. Come da specifiche OpenAPI riguardo l'attributo `tipoFile`, questo dovrebbe restituire quanto indicato, ovvero, i possibili valori indicati su [docs/Decodifiche/10_dec_tipo_file.csv](docs/Decodifiche/10_dec_tipo_file.csv)

Abbiamo preso in carico la segnalazione.

Cordiali Saluti.
Supporto ANSC.

**Comment by asqueglia** [comment]
Buongiorno confermiamo che con il rilascio della versione 1.9.1 la segnalazione è stata corretta. E' possibile riprovare. Chiudiamo la issue, nel caso la preghiamo di riaprirla.
