### ISSUE TITLE
Segnalazione campi mancanti su model_evento.yaml versione 1.9.0

### ISSUE THREAD

**Issue by siscomanpr** [italia/ansc#154]
Sul model_evento.yaml (e il relativo file pdf di documentazione) non c'è traccia del campo idContenitore segnalato come informazione aggiunta nella release 1.9.0

Di contro è stato trovato un nuovo campo chiamato genitoreConCittadinanza (sotto ModelTrascrizioneCittadinanza) di cui non c'è traccia nel Changelog

**Comment by asqueglia** [comment]
Buongiorno, l'idContenitore viene utilizzato nella gestione dei parti gemellari e plurigemellari; si riferisce al contenitore che lega logicamente gli atti dei gemelli, è un meccanismo interno del sistema; non dovete valorizzarlo voi ma è automaticamente gestito da sistema nel momento in cui viene invocato il servizio di prenotazioni numeri che crea le bozze degli atti di ogni gemello assegnando l'identificativo nazionale. Si consiglia di leggere la guida operativa per la registrazione di parti gemellari e plurigemellari e di verificare il payload di esempio per l'invocazione del servizio di prenotazione.

Il flusso per gestire i parti gemellari e plurigemellari è il seguente:

- invocazione servizio di prenotazione {{R009}}/prenota/evento/v1
- completamento degli atti in bozza predisposti dal servizio di prenotazione, tramite invocazione del servizio di validazione R009, specificando per ogni atto l'identificativo nazionale restituito dal servizio di prenotazione.

**Comment by amusarra** [comment]
@siscomanpr chiudiamo la issue in quanto la questione dovrebbe essere risolta e non è stato ricevuto nessun feedback sulla risposta di @asqueglia. Nel caso fosse necessario invitiamo nuovamente all'apertura.

Cordiali Saluti.
Supporto ANSC.
