### ISSUE TITLE
Ambiente di Test ANSC

### ISSUE THREAD

**Issue by ATropeano** [italia/ansc#155]
Buongiorno. L'ambiente per i primi test delle **API ANSC** è quello con gli EndPoint con il suffisso "pre", 
ad esempio https://anscservicepre.anpr.interno.it/services/service/ricerca/consultazione/anagrafica/1.9.0
oppure ne esiste uno con il suffisso "test" come per ANPR?
ad esempio https://anscservicetest.anpr.interno.it/services/service/ricerca/consultazione/anagrafica/1.9.0

Grazie.
Alessio Tropeano
Datagraph srl

**Comment by amusarra** [comment]
Salve @ATropeano 
Confermiamo il suffisso `pre` per l'ambiente di test, ovvero, pre-produzione per il sistema ANSC.
Per i path dello specifico servizio menzionato, le consiglio di vedere le relative specifiche [OpenAPI](docs/openapi/R005_consultazione_ansc.yaml)

Chiudiamo questa issue. Nel caso di altre domande riapra pure.

Cordiali Saluti.
Supporto ANSC.
