### ISSUE TITLE
Errore invio email per firma elettronica (caso d'uso 2199)

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#156]
Richiamando il servizio di invio email per firma elettronica ricevo un errore. Di seguito request e response (la stessa richiesta per altri casi d'uso funziona regolarmente):

REQUEST:
{
    "emailDichiarante": "daniele.bianchini@padigitale.it",
    "idEvento": "953310",
    "idAnsc": "2023-953310-7-108028",
    "firmatario": {
        "cognome": "ROBA",
        "nome": "BABBO"
    },
    "testataRichiesta": {
        "idComune": 5000,
        "idOperazioneComune": "19",
        "dataOraRichiesta": "2023-06-01T15:42:51.813+02:00",
        "nomeApplicativo": "urbi",
        "versioneApplicativo": "0.1.0",
        "fornitoreApplicativo": "padigitale"
    }
}

RESPONSE:
{
    "errors": [{
            "code": "404001",
            "severity": "E",
            "text": "Dati non presenti"
        }
    ],
    "esito": {
        "codice": "404001",
        "descrizione": "Dati non presenti"
    },
    "testataRisposta": {
        "idComune": 5000,
        "idEsito": 1,
        "idOperazioneComune": "19"
    }
}

**Comment by amusarra** [comment]
Salve @biadanpad 
Per il caso d'uso di servizio da voi validato _**non è stato specificato nessun firmatario**_, è corretta quindi la risposta del servizio.
In questi casi d'uso di servizio è possibile che non ci siano firmatari dichiaranti.

Chiudo la issue, in caso di ulteriori questioni riaprite pure.

Cordiali Saluti.
Supporto ANSC:
