### ISSUE TITLE
Errore chiamata al servizio R001 , invio allegato

### ISSUE THREAD

**Issue by elenadimartino** [italia/ansc#157]
Richiamando il servizio di invio allegato riceviamo un errore :  Status[500 Internal Server Error]: {"message":"internal.error","errors":null} , che non  si presenta sempre . Stamattina l'invio dello stesso file veniva inviato correttamente. In allegato la request  inviata
[AllegatoUploadRequest.txt](https://github.com/italia/ansc/files/11626816/AllegatoUploadRequest.txt)

Cordiali Saluti

**Comment by amusarra** [comment]
Buongiorno @elenadimartino 
È possibile che sia stato un errore temporaneo. In questo momento il servizio di upload funziona correttamente senza restituire nessun errore HTTP/500.

Chiudiamo la issue, in caso di necessita non esiti a riaprire.

Cordiali Saluti.
Supporto ANSC.
