### ISSUE TITLE
[R008] Errore 500 in consultazione notifiche

### ISSUE THREAD

**Issue by siscomanpr** [italia/ansc#158]
Provando a chiamare il servizio R008 per la ricerca delle notifiche otteniamo errore 500 - errore interno
L'url invocato è : https://anscservicepre.anpr.interno.it/services/service/notifiche/notifiche/ricerca/1
idOperazione=1596433
ambiente=pre-prod

Riesco ad ottenere una risposta valida solo se compilo come parametro il campo idANSC oltre alla data di inizio e fine.

**Comment by amusarra** [comment]
Salve @siscomanpr 
Abbiamo preso in carico la segnalazione e confermiamo che si tratta di un bug.

Cordiali Saluti.
Supporto ANSC.

**Comment by amusarra** [comment]
Buongiorno @siscomanpr 
Verifichiamo ma dovrebbe essere stato risolto con la release 1.9.0.

Può rifare un test?

Cordiali Saluti.
Supporto ANSC.

**Comment by asqueglia** [comment]
Buongiorno confermiamo che con il rilascio della versione 1.9.1 la segnalazione è stata corretta. E' possibile riprovare. Chiudiamo la issue, nel caso la preghiamo di riaprirla.
