### ISSUE TITLE
[R005] Consultazione annotazioni automatiche

### ISSUE THREAD

**Issue by siscomanpr** [italia/ansc#159]
Stiamo tendando di consultare le annotazioni automatiche ma rileviamo alcune difficoltà.
Impostando come parametri le 2 date di inizio e fine, idTipoContenuto=4, idTipoEvento=1 e idComunale=9419, non riceviamo risultati.
Otteniamo risultati solo se non indichiamo l'idComunale. Il problema è che ci ritroviamo decine di annotazioni fatte anche da altri comuni, quindi non è una strada attuabile il giorno in cui ci saranno 8000 comuni subentrati che ogni giorno registreranno centinaia di annotazioni.
Come possiamo consultare solo le annotazioni generate da un determinato Comune? A cosa si riferisce l'idComunale?
Inoltre le date di inizio e fine presenti nei parametri di ricerca, si riferiscono alla data dell'evento "Annotazione" generato dal sistema? Queste annotazioni automatiche, che data hanno rispetto all'evento che le ha generate? La data in cui l'atto è stato firmato da USC?

Ambiente: pre
Caso di consultazione con idComunale valorizzato:
"idOperazione":"1596465"
(otteniamo un elenco vuoto)

Caso di consultazione senza idComunale valorizzato:
"idOperazione":"1596472"
(otteniamo l'elenco)

**Comment by asqueglia** [comment]
Buongiorno, provvederemo ad estendere il servizio di consultazione annotazioni dando la possibilità in input di indicare l'id dell'evento sorgente che ha generato l'annotazione automatica, in modo da renderne più semplice la ricerca. Le faremo sapere il prima possibile quando verrà rilasciata questa estensione.

**Comment by asqueglia** [comment]
Buonasera con la versione 1.11.0 è stata corretta la segnalazione. 
La issue viene chiusa nel caso si prega di riaprirla.
