### ISSUE TITLE
[R012] - Richiesta informazioni su IdPresaVisione

### ISSUE THREAD

**Issue by ManuelDeMeo** [italia/ansc#16]
Buon pomeriggio,

come valorizzare l'idPresaVisione per la chiamata al servizio https://anscservicepre.anpr.interno.it/services/service/firma/firmadichiarante/invio-email/1 ?

Cosa rappresenta questo idPresaVisione?

**Comment by mttfranci** [comment]
Salve. Stiamo lavorando per migliorare l'interfaccia del servizio.
Aggiorneremo la documentato nei prossimi rilasci.

Saluti.

Assistenza ANSC
