### ISSUE TITLE
[R013] - Internal Server Error (500) in risposta all'invocazione del servizio 

### ISSUE THREAD

**Issue by LoreL56** [italia/ansc#161]
Buongiorno,
abbiamo provato ad invocare il servizio R013 per inserire un annotazione di rettifica.

Il servizio di inserimento va in errore 
L'id operazione della risposta è : 1596582

Avevamo già provato ad invocare tale servizio nelle settimane precedenti e non avevamo riscontrato questo problema.

Inoltre avevamo dei dubbi sulle annotazioni di rettifica:

* Il flusso per questo tipo di annotazione prevede una fase di firma da parte dell'ufficiale dello stato civile (analogamente a quanto già avviene per le annotazioni di tipo integrativo) è corretto? Parrebbe in effetti inverosimile l'apposizione di annotazione in assenza della sottoscrizione da parte dell'usc competente, ma chiediamo comunque una vostra conferma.
* Il campo della richiesta "Evento"->"ComposizioneCompleta" rappresenta il testo dell'annotazione? Che differenza c'è rispetto a ciò che indichiamo su "evento"->"datiRettifica"->"dettaglioRettifica" ?

Grazie

**Comment by asqueglia** [comment]
Buongiorno, provvediamo a verificare e le faremo sapere quanto prima.
Per quanto riguarda le domande poste:
- confermiamo che la firma del dichiarante non è prevista; secondo voi è necessaria per le annotazioni per rettifica ?
- Il campo della richiesta "Evento"->"ComposizioneCompleta" rappresenta il testo dell'annotazione comprensivo di formula ministeriale da utilizzare, ad esempio : "Con provvedimento del Tribunale di ROMA (RM) Numero AAAA in data 23/02/2023 l'atto di cui sopra è stato così rettificato: Il nome dell'intestatario è Alessio"
-  il campo "evento"->"datiRettifica"->"dettaglioRettifica" rappresenta il testo della rettifica senza formula, ad esempio  'Il nome dell'intestatario è Alessio'.

**Comment by LoreL56** [comment]
Grazie del chiarimento per quanto riguarda i campi della richiesta.
L'altra domanda era riferita alla firma dell'ufficiale dello stato civile, non a quella del dichiarante. Volevamo appunto conferma che fosse necessario questo passaggio di stato anche nel vostro flusso.

**Comment by asqueglia** [comment]
Buongiorno si confermiamo che è necessaria la firma dell'USC per concludere la registrazione di qualsiasi evento.

**Comment by asqueglia** [comment]
Buongiorno confermiamo che con il rilascio della versione 1.9.1 la segnalazione è stata corretta. E' possibile riprovare. Chiudiamo la issue, nel caso la preghiamo di riaprirla.
