### ISSUE TITLE
Dati officiante su atto di matrimonio

### ISSUE THREAD

**Issue by antonioluberto** [italia/ansc#162]
Buongiorno.
Nei casi d'uso
Matr_001
Matr_002
Matr_003
la sezione:
![image](https://github.com/italia/ansc/assets/26415430/03ad511a-82db-4bee-93dd-c99a51ddddac)

è pensata per contenere i dati relativi a colui che - diverso dall'usc che redige l'atto -celebra il matrimonio?
Se si, allora nessuno dei tre campi dovrebbe risultare obbligatorio.
Se no - e se, quindi, ci si aspetta che la sezione in esame contenga i dati dell'usc laddove sia quest'ultimo a celebrare il matrimonio - per quale ragione è obbligatorio solo il nome e non il cognome?

**Comment by asqueglia** [comment]
Buongiorno la sezione officiante si riferisce all'USC delegato a celebrare il matrimonio, diverso dall'USC che si occupa di formare l'atto digitale. Cos' come in ANPR è previsto che un soggetto possa essere senza nome o senza cognome, anche in ANSC è stato ritenuto di rendere obbligatorio solo una dei due campi; preciso che su questo punto è ancora aperta una discussione che riguarda più in generale tutti i soggetti. Chiaramente qualora siano a disposizioni entrambe le informazioni nome e cognome, queste vanno inoltrate al sistema ed acquisite.

**Comment by asqueglia** [comment]
Buongiorno, essendo le casistiche varie, il sistema richiede che venga espressamente indicato nel campo officiante, chi celebra il matrimonio; nel caso in cui il matrimonio è celebrato dallo stesso ufficiale di stato civile che forma l'atto, il sistema richiede che venga comunque passata obbligatoriamente l'informazione nel campo officiante utilizzando gli stessi dati dell'USC già presenti nel campo operatore come da lei indicato.
Preciso comunque che ci è stato indicato da ANUSCA che questa è una ipotesi remota in quanto generalmente l'operatore che forma l'atto di matrimonio non è colui che lo celebra.

**Comment by asqueglia** [comment]
Buongiorno, chiudiamo la issue, nel caso la preghiamo di riaprirla.
