### ISSUE TITLE
[R002] chiarimenti su campi da compilare per richiesta atto registrato post firma USC

### ISSUE THREAD

**Issue by MichelaGarzoni** [italia/ansc#163]
Buongiorno, mi servirebbero dei chiarimenti:
a conclusione della registrazione dell'atto, post firma dell'USC vogliamo utilizzare lo stesso servizio R002 di certificazione, utilizzato nella web-app, per poter estrarre l'atto appena registrato.
Nel json di richiesta del servizio abbiamo impostato il campo "idTipoCertificato" con il valore 3 ed inserito i campi idAnsc (2023-953006-20230080000007-032001) ed idEvento (953006).

In questo caso vengono richiesti i campi di un "_richiedente_": in questa fase, chi è il richiedente e quali sono i campi obbligatori?

Viene richiesto anche l'inserimento dei dati relativi all'"_intestatario_" ed abbiamo compilato i campi nel seguente modo (qua anonimizzati), riprendendoli da quelli dell'atto validato e firmato:
_"intestatario":{
 "codiceFiscale":"S.........................."
,"cognome":"S..."
,"nome":"N..."
,"sesso":"F"
,"dataNascita":"1946-00-00"
,"idComuneNascita":"010"
,"nomeComuneNascita":"AACHEN"
,"idProvinciaNascita":"216"
,"idStatoNascita":"216"
,"nomeStatoNascita":"GERMANIA"
,"idComuneResidenza":"006"
,"nomeComuneResidenza":"TRIESTE"
,"idProvinciaResidenza":"032"
,"siglaProvinciaResidenza":"TS"
,"idStatoResidenza":"100"
,"nomeStatoResidenza":"ITALIA"
,"idNazionalita":"100"
,"nazionalita":"ITALIANA"}_

ma otteniamo l'errore:
_"idOperazione": "1596824"
    },
    "errors": [
        {
            "code": "400001",
            "severity": "E",
            "text": "Id soggetto intestatario non valido"
        }
    ]_

cosa manca al campo intestatario? Quali sono i campi obbligatori per ottenere l'atto registrato?
Grazie

**Comment by asqueglia** [comment]
Buongiorno, in merito all'intestatario verifichiamo l'anomalia e le facciamo sapere quanto prima.
Per quanto riguarda la domanda sul richiedente, comunichiamo che si tratta del soggetto che richiede il certificato che potrebbe essere uguale oppure diverso dall'intestatario; si tratta comunque di un dato obbligatorio.

**Comment by asqueglia** [comment]
Buonasera con la versione 1.11.0 è stata corretta la segnalazione. 
La issue viene chiusa nel caso si prega di riaprirla.
