### ISSUE TITLE
Dati assistente sposi minorenni

### ISSUE THREAD

**Issue by antonioluberto** [italia/ansc#164]
In tutti i casi d'uso relativi al matrimonio, esempio:
Matr_001
Matr_002
Matr_003
Matr_007
Matr_008

la modellazione prevede sia possibile indicare un solo tutore per sposo/a eventualmente minorenne/i:

![image](https://github.com/italia/ansc/assets/26415430/3d4482ca-7efe-474f-99e1-3f7d2e40fd59)

La norma prevede però che ad assistere ciascuno degli sposi minorenni possano essere:
- un genitore
- entrambi i genitori
- un tutore/curatore.

E' possibile quindi si abbiano fino a 4 assistenti legali

**Comment by asqueglia** [comment]
Buongiorno, verificheremo quanto segnalato e vi faremo sapere quanto prima.
Da una prima analisi della formula prevista in caso di scelta di separazione di beni con sposo/a minorenne, sembra che gli assistenti legali al più possano essere due (caso dei genitori).
Nel caso in cui entrambi gli sposi siano minorenni e siano assistiti entrambi dai rispettivi genitori, allora si possono avere in totale 4 assistenti legali. E' corretta come interpretazione ? riporto sotto la formula in cui si evince quanto scritto.

Nelle ipotesi di cui all'art. 165 del codice civile, specificare che il minore, o i minori, sono assistiti 
dai genitori esercenti la potestà **o** dal tutore **o** dal curatore speciale, indicandone le generalità e 
precisando gli estremi dell'eventuale provvedimento di nomina.

**Comment by antonioluberto** [comment]
Confermo: possono aversi fino a 4 assistenti legali.

**Comment by amusarra** [comment]
Chiudiamo la issue per via del rilascio della versione 1.10.0 che risolve questa segnalazione.

Cordiali Saluti.
Supporto ANSC.
