### ISSUE TITLE
Firma dichiarante non disponibile nella Web Application.

### ISSUE THREAD

**Issue by gcuci** [italia/ansc#166]
buongiorno,

segnaliamo che per alcuni eventi registrati (in stato 'CONFERMATO'), per i quali vi è almeno un comparente con flagDichiarante e flagFirmatario a 'true', dalla Web Application non è possibile effettuare la Firma Dichiarante, in quanto propone direttamente la Firma USC.

Procedendo invece tramite l'invocazione dei servizi REST, il processo funziona correttamente (prima Firma Dichiarante e poi Firma USC).

Un caso di esempio, è l'evento di morte, con idEvento = 953313, per il quale, come si vede nell'Anteprima, c'è un dichiarante firmatario, ma l'interfaccia propone direttamente la Firma USC.

  
In attesa di un riscontro,

cordiali saluti.

**Comment by amusarra** [comment]
Salve @gcuci.
Stando a quanto ha scritto, la Web App non le mostra la lista dei firmatari, così come indicato dalla figura a seguire, corretto?
Al fine di poter indagare e replicare il problema, attraverso gli strumenti di sviluppo del browser, sarebbe utile individuare se qualche chiamata alle API da parte della Web App andasse in errore.

Nel frattempo cercheremo di replicare il suo problema ma sarebbe utile avere l'idOperazione relativo all'inserimento. dell'evento, informazione utile al fine di recuperare il payload JSON della richiesta di validazione.

![image](https://github.com/italia/ansc/assets/708110/828b1b1d-4336-4bee-9923-60273eb17a26)
 
Cordiali Saluti.
Supporto ANSC.

**Comment by gcuci** [comment]
si, corretto.

l'ultima operazione di validazione effettuata sull'evento, ha avuto questo esito (da cui l'idOperazione):
{
  "idEvento": "953313",
  "idAnsc": "2023-953313-29538-039002",
  "idTipoEvento": "2",
  "testataRisposta": {
    "idComune": 595,
    "idOperazioneComune": "1727",
    "idOperazione": "1596398",
    "idEsito": 0
  },
  "": "ValidazioneEventoResponse"
}

**Comment by amusarra** [comment]
@gcuci abbiamo recuperato il payload dell'evento.
È possibile verificare se lato Web App, tramite i tool di sviluppo del browser ci sono errori sulle chiamate ai servizi?

Grazie.
Supporto ANSC.

**Comment by amusarra** [comment]
@gcuci abbiamo replicato il caso. Sostanzialmente lo step della vista della lista dei firmatari viene saltato perché già confermato, tra cui il tipo di firma CARTACE o PRESA VISIONE (via link inviato per email).

![image](https://github.com/italia/ansc/assets/708110/b8d968c6-3260-4663-bf58-71caf3f71578)

Per tornare alla lista dei Dichiaranti basta cliccare sul pulsante "Torna a Conferma Evento".

![image](https://github.com/italia/ansc/assets/708110/fa86e365-db40-467a-aaef-6ab775897fb8)

Cordiali Saluti.
Supporto ANSC.

**Comment by amusarra** [comment]
@gcuci chiudiamo la issue. Nel caso in cui dovesse avere altre domande di chiarimenti non esiti a riaprire la issue.

Cordiali Saluti.
Supporto ANSC.

**Comment by amusarra** [comment]
> @gcuci segnaliamo la presenta di elementi non conformi alle OpenAPI come per esempio `"": "ModelSoggetto"`. Al momento sono ignorati questi elementi ma le prossime release potrebbero essere più restrittive.
> 
> ```json
> {
>     "evento": {
>         "intestatari": [
>             {
>                 "": "ModelSoggetto"
>             }
>         ],
>         "coniuge": {
>             "": "ModelSoggetto"
>         },
>         "datiDiMorte": {
>         },
>         "datiEventoMorte": {
>             "numeroComparenti": "1",
>             "comparente1": {
>                 "": "ModelSoggetto"
>             }
>         },
>     },
>     "": "ValidazioneEventoRequest"
> }
> ```
> 
> Payload - Parte del payload JSON
> 
> Cordiali Saluti. Supporto ANSC.

Quale tool avete usato per generare il client partendo dalle OpenAPI? Chiediamo perché effettivamente è strano che in fase di serializzazione siano riportati elementi come quelli evidenziati.

Grazie.
Supporto ANSC.

**Comment by gcuci** [comment]
se può servire,

abbiamo validato un nuovo evento di Morte (invocando prima il servizio di ConsultazioneANSC, per eventuale recupero dell'idANSC dell'intestatario, e poi il servizio di Validazione). Di seguito la response della Validazione:

{
  "idEvento": "953610",
  "idAnsc": "2023-953610-29642-039002",
  "idTipoEvento": "2",
  "testataRisposta": {
    "idComune": 595,
    "idOperazioneComune": "1763",
    "idOperazione": "1597836",
    "idEsito": 0
  },
  "": "ValidazioneEventoResponse"
}

Accedendo alla Web Application, cercato l'evento, e cliccato su 'Modifica e Completa', viene visualizzata questa pagina:

![image](https://github.com/italia/ansc/assets/128400400/c7b51c40-5334-4285-8a38-be2f0207deb9)

da cui si può solo proseguire con la Firma USC, mentre è presente un comparente1 con il flagFirmatario = 'true'. A parte le operazioni indicate, sull'evento, ne tramite i servizi, ne tramite Web Application, è stata effettuata altra operazione. (Segnaliamo anche che prima di venir visualizzata la pagina per la firma USC, viene visualizzata, per un attimo, la pagina per la firma dichiarante, con la scelta della tipologia di firma, ma scompare subito).

Se invece procediamo tramite i servizi REST, il flusso funziona correttamente, accettando prima la firma dichiarante e poi quella USC. 



Riguardo invece la generazione del client, a partire dagli Swagger, utilizziamo Swagger CodeGen for Java.

**Comment by amusarra** [comment]
@gcuci come scritto in precedenza il comportamento della Web App è corretto. Per vedere la lista dei firmatari, dovrebbe cliccare sul pulsante **"Torna a Conferma Evento"**.

Riguardo il codice del client generato con Swagger CodeGen for Java è strano che serializzi i JSON con quegli elementi, a meno che la versione usata non sia compatibile con OpenAPI 3.0.0.
 
Cordiali Saluti.
Suporto ANSC.

**Comment by asqueglia** [comment]
Buongiorno confermiamo che con il rilascio della versione 1.9.1 la segnalazione è stata corretta. E' possibile riprovare. Chiudiamo la issue, nel caso la preghiamo di riaprirla.
