### ISSUE TITLE
[ws R010] Anteprima - Errore "Dati in ingresso non corretti"

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/ansc#169]
ambiente pre-produzione - comune di FAENZA (id 3743)
endpoint: https://anscservicepre.anpr.interno.it/services/service/anteprima/anteprima/evento/1
idOperazioneComune: 2023000650

nel caso specifico si tratta di trascrizione di nascita inviata come caso d'uso: 1399 - Caso d'uso di servizio (trascrizioni nascita)
la validazione dell'atto è andata a buon fine (idAttoAnsc: 2023-953502-122-039010), ma la richiesta di anteprima produce l'errore in oggetto.

ho visto un bug analogo relativo alle trascrizioni di morte, che avete risolto con la v1.9.0.

vi chiederei di verificare l'errore anche sulle nascite.

grazie
Alessandro Monopoli ADS

**Comment by asqueglia** [comment]
Buongiorno verifichiamo e le facciamo sapere quanto prima.

**Comment by amusarra** [comment]
Chiudiamo la issue per via del rilascio della versione 1.10.0 che risolve questa segnalazione.

Cordiali Saluti.
Supporto ANSC.
