### ISSUE TITLE
NASCITA (DIC_NASC_012 e DIC_NASC_013)

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#17]
Nella tabella degli usecase mi trovo queste due descrizioni ma manca il particolare di chi va a fare la dichiarazione. 

Dichiarazione tardiva di filiazione nel matrimonio resa all'USC di filiazione di bimbo nato morto ( Dic_Nasc_012)
Dichiarazione tardiva di filiazione nel matrimonio resa all'USC di bimbo nato vivo ma morto prima della denuncia di nascita ( Dic_Nasc_013)

**Comment by asqueglia** [comment]
Buongiorno, in merito alle schede indicate la sezione dati dichiarante deve essere inviata solo se il dichiarante è diverso da padre e madre (es. procuratore speciale del padre o della madre); se il dichiarante invece è uno dei genitore allora basta usare i flag appositi per etichettarlo come dichiarante e firmatario. Il tipo di dichiarante è veicolato invece dall'apposito metadato tipoDichiarante che fa riferimento alla tabella di decodifica 4_dec_tipo_dichiarante.
