### ISSUE TITLE
[R010] Anteprima - Errore "Dati in ingresso non corretti"

### ISSUE THREAD

**Issue by LoreL56** [italia/ansc#171]
Buonasera,
dopo aver inviato un atto di nascita (Caso d'uso -> Rico_013 , ovvero con idUseCase 12323100)
proviamo ad invocare il servizio di visualizzazione dell'anteprima ma ci viene ritornato l'errore 400003 "Dati in ingresso non corretti".

idOperazione: 1598376

Grazie

**Comment by amusarra** [comment]
Salve @LoreL56 
L'errore è dovuto alla mancanza dell'attributo `modelAtto.datiEventoRiconoscimento.preMorto`. Per lo usecase [12323100](https://github.com/italia/ansc/blob/6865d7cc81f8abbff7621855ad3119d6e7806292/docs/Mapping_casi_uso/riconoscimenti/Rico_013.csv) effettivamente il dato non è obbligatorio, per cui il servizio non dovrebbe andare in errore. 

Al momento, per risolvere il problema, potreste passare l'attributo `modelAtto.datiEventoRiconoscimento.preMorto` con il valore a `false`.

Lato nostro gestiremo questa issue per sviluppare la fix.

Cordiali Saluti.
Supporto ANSC.

**Comment by antonioluberto** [comment]
Abbiamo provato anche passando l'attributo "modelAtto.datiEventoRiconoscimento.preMorto" con il valore a "false", ma la richiesta va comunque in errore.

**Comment by amusarra** [comment]
@antonioluberto in ogni caso la fix è stata presa in carico e in via di sviluppo.

Cordiali Saluti.
Supporto ANSC.

**Comment by asqueglia** [comment]
Buongiorno confermiamo che con il rilascio della versione 1.9.1 la segnalazione è stata corretta. E' possibile riprovare. Chiudiamo la issue, nel caso la preghiamo di riaprirla.
