### ISSUE TITLE
[web-service] Messaggi di Errore

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/ansc#172]
ambiente di pre-produzione - comune di FAENZA (id 3743)

come già anticipato per altre vie, riepilogo alcune situazioni di ambiguità nei messaggi di errore restituiti dai web-service.

caso '1': l'errata indicazione dell'OTP viene segnalata con msg. "Nessun dato associato all'utente" (rif. idOperazioneComune 2023000683).
sarebbe più utile sapere che il problema è l'OTP sbagliato

caso '2': il servizio di firma USC (R007) invocato senza prima inviare il servizio di firma dichiarante (R006), restituisce l'errore "Firma non avvenuta con successo" (rif. idOperazioneComune 2023000687)
questa è solo una supposizione, perchè in effetti non si capisce bene quale sia realmente il problema.
il dato di fatto che è che se dopo questo errore inviamo la firma dichiarante (R006), la firma USC dopo va a buon fine.
c'è da aggiungere, però, che lo stesso errore compare anche nella situazione di cui alla issue #133 (per la quale siamo ancora in attesa delle verifiche)
anche in questo caso, quindi, sarebbe più utile un messaggio che permetta di capire con più immediatezza la natura dell'errore.

ritengo sia molto importante esplicitare il più possibile la causa o la situazione che genera l'errore, al fine semplificare il lavoro dell'utente finale; così che l'operatore non si trovi costretto a chiedere il supporto della SW House o di Sogei per capire quale sia il problema.
questo vale in particolare per queste due situazioni segnalate, ma spero si tenga conto di questa esigenza in generale.

grazie.
Alessandro Monopoli ADS

**Comment by amusarra** [comment]
Buongiorno @AMonopoliADS 
Abbiamo preso in carico la vostra richiesta di miglioria dei messaggi di errori.

Cordiali Saluti.
Supporto ANSC.
