### ISSUE TITLE
[R006 -Firma Dichiarante] errore in upload del file firmato in modo autografo

### ISSUE THREAD

**Issue by MichelaGarzoni** [italia/ansc#176]
Buongiorno, 
utilizzando il servizio di caricamento file firmato dal dichiarante ci viene restituito l'errore "400003 - Non è possibile firmare l'atto, perchè non è in stato = CONFERMATO" e non riusciamo a capire se è un problema legato ai dati inviati al servizio, in quanto l'atto risulta in stato confermato già in fase di validazione, o a qualche nostra mancanza nei passi relativi alla firma digitale (ma l'atto è stato correttamente scaricato per la firma).
Esempio (con allegato troncato per ridurne la dimensione):

{
"testataRichiesta":{
"idComune":3655
,"idOperazioneComune":"20230050000020"
,"dataOraRichiesta":"2023-06-09T09:57:58Z"
,"nomeApplicativo":"ASCOT Stato Civile"
,"versioneApplicativo":"21.99.0000"
,"fornitoreApplicativo":"Insiel S.p.A"
}
,"firmaDichiaranteInput":{
"contenuto":"JVBERi0xLjQKJaqrrK0KMSAwIG9iago8PAo....................................................0RjJCOTZBMTMxODJEODZFMjNGNUY5NT5dCiAgL1NpemUgMzM1Cj4+CnN0YXJ0eHJlZgoxMjI3NjUKJSVFT0YK"
,"protocollo":"N\/A"
,"nomefile":"pdf_atto_di_morte_001.pdf"
,"idEvento":"953739"
,"tipoFile":1
,"tipoAllegato":999
,"stato":"1"
}
}

E la risposta che otteniamo è la seguente:
{
    "errors": [
        {
            "code": "400003",
            "severity": "E",
            "text": "Non è possibile firmare l'atto, perchè non è in stato = CONFERMATO"
        }
    ],
    "testataRisposta": {
        "idComune": 3655,
        "idEsito": 1,
        "idOperazione": "1599561",
        "idOperazioneComune": "20230050000020"
    }
}

Abbiamo provato ad inserire la listaFirmatari sia vuota che con il singolo firmatario presente ma le cose non cambiano e abbiamo provato anche a togliere il campo "protocollo" ma l'esito è rimasto lo stesso.

Grazie

**Comment by amusarra** [comment]
Buongiorno @MichelaGarzoni 
Da analisi condotte, l'evento risulta nello stato **FIRMATO DAL DICHIARANTE**, ecco il motivo dell'errore.
Se non ci sono altre questioni le chiediamo di chiudere la issue.

Cordiali Saluti.
Supporto ANSC.

![image](https://github.com/italia/ansc/assets/708110/bb42adeb-4c19-4cc7-9839-09aac1deb40f)

**Comment by MichelaGarzoni** [comment]
Grazie, probabilmente allora abbiamo noi un errore interno per cui non vediamo la conferma dell'invio dell'allegato
