### ISSUE TITLE
[R009 - validazione] richiesti campi non corretti per matrimonio usecase 311111

### ISSUE THREAD

**Issue by MichelaGarzoni** [italia/ansc#177]
Buongiorno,
in fase di test degli usecase relativi al matrimonio, nella validazione del caso 311111 abbiamo riscontrato un'incongruenza nelle segnalazioni di errore che ci vengono indicate.
Es.:
{
"testataRichiesta":{
"idComune":3655
,"idOperazioneComune":"20230120000003"
,"dataOraRichiesta":"2023-06-08T15:53:05Z"
,"nomeApplicativo":"ASCOT Stato Civile"
,"versioneApplicativo":"21.99.0000"
,"fornitoreApplicativo":"Insiel S.p.A"
}
,"evento":{
"idTipoEvento":"3"
,"idtipocontenuto":"1"
,"idUsecase":"311111"
,"descrizioneCasoUso":"Matrimonio con Rito Civile nella casa comunale"
,"stato":"CONFERMATO"
,"secretato":"0"
,"dataformazione":"2023-06-01"
,"ora":"14"
,"minuto":"34"
,"numeroatto":"20230120000003"
,"ausilioInterprete":"FALSE"
,"idComuneRegistrazione":3655
,"nomeComuneRegistrazione":"DUINO AURISINA-DEVIN NABRE\u017DINA"
,"idProvinciaRegistrazione":"32"
,"siglaProvinciaRegistrazione":"TS"
,"certificabile":"1"
,"composizioneCompleta":"xxxxxxxxxxxxxxxxxxxxxxx"
,"interprete":{
}
,"datiEventoMatrimonio":{
"dataEvento":"2023-06-01"
,"oraEvento":"15"
,"minutoEvento":"05"
,"officiante":"8"
,"nomeOfficiante":"Comandante Nave"
,"comprensioneSposo":"0"
,"comprensioneSposa":"0"
,"numeroTestimoni":"2"
,"testimone1":{
"cognome":"XXXXX"
,"nome":"XXXXXX"
,"sesso":"F"
,"dataNascita":"dddd-dd-dd"
,"idComuneNascita":"080"
,"nomeComuneNascita":"TREVI NEL LAZIO"
,"idProvinciaNascita":"060"
,"siglaProvinciaNascita":"FR"
,"idStatoNascita":"100"
,"nomeStatoNascita":"ITALIA"
,"idComuneResidenza":"3655"
,"nomeComuneResidenza":"DUINO AURISINA-DEVIN NABRE\u017DINA"
,"idProvinciaResidenza":"32"
,"siglaProvinciaResidenza":"TS"
,"idStatoResidenza":"100"
,"nomeStatoResidenza":"ITALIA"
,"idNazionalita":"443"
,"nazionalita":"NIGERIANA"
,"flagDichiarante":"true"
,"flagComparente":"false"
,"flagFirmatario":"true"
}
,"testimone2":{
"cognome":"EEEEEE"
,"nome":"EEEEEE"
,"sesso":"M"
,"dataNascita":"FFFF-FF-FF"
,"idComuneNascita":"091"
,"nomeComuneNascita":"ROMA"
,"idProvinciaNascita":"058"
,"siglaProvinciaNascita":"RM"
,"idStatoNascita":"100"
,"nomeStatoNascita":"ITALIA"
,"idComuneResidenza":"012"
,"nomeComuneResidenza":"MONFALCONE"
,"idProvinciaResidenza":"031"
,"siglaProvinciaResidenza":"GO"
,"idStatoResidenza":"100"
,"nomeStatoResidenza":"ITALIA"
,"idNazionalita":"231"
,"nazionalita":"NORVEGESE"
,"flagDichiarante":"true"
,"flagComparente":"false"
,"flagFirmatario":"true"
}
,"testimone3":{
}
,"testimone4":{
}
,"segretarioComunale":{
}
,"pubblicazioneInPiuComuni":"False"
,"riduzioneTerminiPubblicazione":"False"
,"omissionePubblicazione":"False"
,"rigettoOpposizione":"False"
,"estintaOpposizione":"False"
,**"difettoEta":"False"**
,**"impedimentoParentela":"False"**
,"divietoTemporaneo":"False"
,"regimePatrimoniale":{
"tipo":"1"
,"attoNotarile":"False"
,"assistenteLegale":{
}
}
,"figli":[
{
}
]
,"datiEventoRiconoscimento":{
}
,"consensoRiconoscimento":{
}
,"impedimentoSposo":{
}
,"impedimentoSposa":{
}
}
,"intestatari":[
{
"idSoggettoAnpr":"NNNNNNNNNN"
,"cognome":"GGGGGGGGGG"
,"nome":"GGGGGGGGGG"
,"sesso":"M"
,"dataNascita":"DDDD-DD-DD"
,"idComuneNascita":"006"
,"nomeComuneNascita":"TRIESTE"
,"idProvinciaNascita":"032"
,"siglaProvinciaNascita":"TS"
,"idStatoNascita":"100"
,"nomeStatoNascita":"ITALIA"
,"idComuneResidenza":"3655"
,"nomeComuneResidenza":"DUINO AURISINA-DEVIN NABRE\u017DINA"
,"idProvinciaResidenza":"32"
,"siglaProvinciaResidenza":"TS"
,"idStatoResidenza":"100"
,"nomeStatoResidenza":"ITALIA"
,"idNazionalita":"100"
,"nazionalita":"ITALIANO"
,"flagDichiarante":"True"
,"flagComparente":"True"
,"flagFirmatario":"True"
}
,{
"cognome":"RRRRRRRRRR"
,"nome":"GGGGGGGGGGG"
,"sesso":"F"
,"dataNascita":"DDDD-DD-DD"
,"idComuneNascita":"006"
,"nomeComuneNascita":"TRIESTE"
,"idProvinciaNascita":"032"
,"siglaProvinciaNascita":"TS"
,"idStatoNascita":"100"
,"nomeStatoNascita":"ITALIA"
,"idComuneResidenza":"006"
,"nomeComuneResidenza":"TRIESTE"
,"idProvinciaResidenza":"032"
,"siglaProvinciaResidenza":"TS"
,"idStatoResidenza":"100"
,"nomeStatoResidenza":"ITALIA"
,"idNazionalita":"100"
,"nazionalita":"ITALIANA"
,"flagDichiarante":"True"
,"flagComparente":"True"
,"flagFirmatario":"True"
}
]
}
}

 tralasciando altri errori che stiamo gestendo, abbiamo impostato i flag evidenziati in grassetto in false ma ci viene richiesto comunque di popolare l'autorizzazioneParentela e l'autorizzazioneDifettoEta.

Esito invio:
{
    "testataRisposta": {
        "idComune": 3655,
        "idOperazioneComune": "20230120000003",
        "idOperazione": "1599565",
        "idEsito": 1
    },
    "errors": [
        {................}
        {
            "code": "400003",
            "severity": "E",
            "text": "Il campo evento.datiEventoMatrimonio.autorizzazioneDifettoEta.dataTrascrizione nella sezione Impedimento - Difetto di età è obbligatorio"
        },
        {
            "code": "400003",
            "severity": "E",
            "text": "Il campo evento.datiEventoMatrimonio.autorizzazioneDifettoEta.estremiDocumento nella sezione Impedimento - Difetto di età è obbligatorio"
        },
        {
            "code": "400003",
            "severity": "E",
            "text": "Il campo evento.datiEventoMatrimonio.autorizzazioneDifettoEta.nomeEnte nella sezione Impedimento - Difetto di età è obbligatorio"
        },
        {
            "code": "400003",
            "severity": "E",
            "text": "Il campo evento.datiEventoMatrimonio.autorizzazioneDifettoEta.idProvinciaEnte nella sezione Impedimento - Difetto di età è obbligatorio"
        },
        {
            "code": "400003",
            "severity": "E",
            "text": "Il campo evento.datiEventoMatrimonio.autorizzazioneDifettoEta.siglaProvinciaEnte nella sezione Impedimento - Difetto di età è obbligatorio"
        },
        {
            "code": "400003",
            "severity": "E",
            "text": "Il campo evento.datiEventoMatrimonio.autorizzazioneDifettoEta.idComuneEnte nella sezione Impedimento - Difetto di età è obbligatorio"
        },
        {
            "code": "400003",
            "severity": "E",
            "text": "Il campo evento.datiEventoMatrimonio.autorizzazioneDifettoEta.nomeComuneEnte nella sezione Impedimento - Difetto di età è obbligatorio"
        },
        {
            "code": "400003",
            "severity": "E",
            "text": "Il campo evento.datiEventoMatrimonio.autorizzazioneParentela.dataTrascrizione nella sezione Impedimento - Parentela è obbligatorio"
        },
        {
            "code": "400003",
            "severity": "E",
            "text": "Il campo evento.datiEventoMatrimonio.autorizzazioneParentela.estremiDocumento nella sezione Impedimento - Parentela è obbligatorio"
        },
        {
            "code": "400003",
            "severity": "E",
            "text": "Il campo evento.datiEventoMatrimonio.autorizzazioneParentela.nomeEnte nella sezione Impedimento - Parentela è obbligatorio"
        },
        {
            "code": "400003",
            "severity": "E",
            "text": "Il campo evento.datiEventoMatrimonio.autorizzazioneParentela.idProvinciaEnte nella sezione Impedimento - Parentela è obbligatorio"
        },
        {
            "code": "400003",
            "severity": "E",
            "text": "Il campo evento.datiEventoMatrimonio.autorizzazioneParentela.siglaProvinciaEnte nella sezione Impedimento - Parentela è obbligatorio"
        },
        {
            "code": "400003",
            "severity": "E",
            "text": "Il campo evento.datiEventoMatrimonio.autorizzazioneParentela.idComuneEnte nella sezione Impedimento - Parentela è obbligatorio"
        },
        {
            "code": "400003",
            "severity": "E",
            "text": "Il campo evento.datiEventoMatrimonio.autorizzazioneParentela.nomeComuneEnte nella sezione Impedimento - Parentela è obbligatorio"
        }
    ]
}

 Grazie

**Comment by amusarra** [comment]
Salve @MichelaGarzoni 
Immagino che faccia riferimento agli attributi `difettoEta`, `impedimentoParentela` impostato al valore stringa `"False"`, corretto? Riporto a seguire l'estratto.

```json
...
            },
            "testimone3": {},
            "testimone4": {},
            "segretarioComunale": {},
            "pubblicazioneInPiuComuni": "False",
            "riduzioneTerminiPubblicazione": "False",
            "omissionePubblicazione": "False",
            "rigettoOpposizione": "False",
            "estintaOpposizione": "False",
            "difettoEta": "False",
            "impedimentoParentela": "False",
            "divietoTemporaneo": "False",
            "regimePatrimoniale": {
                "tipo": "1",
                "attoNotarile": "False",
                "assistenteLegale": {}
            },
...
```
Payload 1 - Esempio di estratto dal payload di validazione evento

Stando alla documentazione OpenAPI e in particolare [model_evento.yam](https://github.com/italia/ansc/blob/6865d7cc81f8abbff7621855ad3119d6e7806292/docs/openapi/model_evento.yaml#L1500), l'attributo `difettoEta` può assumere i valori indicati dalla tabella decodifica [ANSC_47](https://github.com/italia/ansc/blob/6865d7cc81f8abbff7621855ad3119d6e7806292/docs/Decodifiche/47_dec_difetto_eta.csv) da cui è evidente che il valore `False` non è ammesso.

Lo stesso discorso vale anche per l'attributo `impedimentoParentela` i cui valori devono essere quelli indicati dalla tabella di decodifica [ANSC_48](https://github.com/italia/ansc/blob/6865d7cc81f8abbff7621855ad3119d6e7806292/docs/Decodifiche/48_dec_impedimento.csv)

Impostando correttamente i valori di questi due attributi, dovreste ottenere dal servizio il comportamento desiderato.

Spero di essere stato chiaro nell'esposizione.

Cordiali Saluti.
Supporto ANSC

**Comment by MichelaGarzoni** [comment]
Grazie mille, abbiamo quindi interpretato male i campi impedimentoParentela considerandoli praticamente dei flag e non con valori definiti. Ci era sfuggita questa particolarità.

**Comment by amusarra** [comment]
@MichelaGarzoni ottimo.
