### ISSUE TITLE
Chiarimento: scaricamento atto dopo la firma USC (segue #141)

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#178]
Come da vostro suggerimento ho utilizato il servizio R002/certificato, ma l'estratto per copia integrale che ottengo non è quello atteso. Allego l'estratto ottenuto tramite il servizio (R012_certificato.pdf) e quello che posso invece scaricare dalla WebApp (WebApp.pdf).
[R012_certificato.pdf](https://github.com/italia/ansc/files/11704492/R012_certificato.pdf)
[WebApp.pdf](https://github.com/italia/ansc/files/11704493/WebApp.pdf)

**Comment by biadanpad** [comment]
Se genero l'atto con la webapp, al termine della procedura posso scaricare il seguente documento:
[WebApp - OttieniAttoRegistrato.pdf](https://github.com/italia/ansc/files/11720885/WebApp.-.OttieniAttoRegistrato.pdf)

cliccando sul tasto "Ottieni atto registrato"
![image](https://github.com/italia/ansc/assets/131870281/3bf747da-d9f3-42ff-9830-e8a1f3f3f498)

Questo documento contiene la sezione "Firmatari" nella quale sono riportati tutti i firmatari con la specifica del tipo di firma. L'estratto che posso scaricare con il servizio R002/certificato non contiene questa sezione.

Come faccio a scaricare l'atto registrato (comprensivo di tutte le firme) in modo da poterlo archiviare nel nostro gestionale?

**Comment by biadanpad** [comment]
Come faccio a scaricare l'atto registrato (comprensivo di tutte le firme) in modo da poterlo archiviare nel nostro gestionale?

**Comment by amusarra** [comment]
@biadanpad abbiamo verificato l'esistenza di un bug di cui abbiamo preso in carico la risoluzione.

Cordiali Saluti.
Supporto ANSC.

**Comment by asqueglia** [comment]
Buongiorno, è stata appena rilasciata la versione 1.13.0 che corregge il bug segnalato. Chiudiamo pertanto la issue; in caso di ulteriori problematiche si prega di aprirne una nuova.
