### ISSUE TITLE
Metadati non corretti sulla WebApp

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#179]
Al termine di generazione di un atto tramite i servizi forniti, i metadati presenti sulla WebApp non risultano conformi a quelli inviati. Allego estratto per copia integrale e screenshot della WebApp
[WebApp.pdf](https://github.com/italia/ansc/files/11704557/WebApp.pdf)
![image](https://github.com/italia/ansc/assets/131870281/ca544ff1-eb12-40c9-8f31-f8c329985e1d)
![image](https://github.com/italia/ansc/assets/131870281/c4a52936-2d25-4777-aca6-4f32466c5b45)
![image](https://github.com/italia/ansc/assets/131870281/03e73ae7-a82b-4274-b847-1e856eabe711)
![image](https://github.com/italia/ansc/assets/131870281/39a2de4b-da58-4924-8e62-46d611d48e8d)
![image](https://github.com/italia/ansc/assets/131870281/dac0bc8c-b076-4c87-b171-5eb6580ea977)

**Comment by amusarra** [comment]
Salve @biadanpad 
In questo modo non riusciamo a capire le differenze senza avere l'identificativo dell'evento e il payload di validazione.

Cordiali Saluti.
Supporto ANSC.

**Comment by biadanpad** [comment]
Ho appena ricreato un atto. L'identificativo 953808

Di seguito il payload della validazione:

{
    "evento": {
        "idAnsc": "",
        "idTipoEvento": "1",
        "idtipocontenuto": "1",
        "idUsecase": "11111000",
        "stato": "CONFERMATO",
        "dataformazione": "2023-06-09",
        "ora": "15",
        "minuto": "30",
        "operatore": "DLCNTN57L67A064W",
        "operatoreNome": "MARTINA",
        "operatoreCognome": "GORI",
        "idComuneRegistrazione": "5000",
        "nomeComuneRegistrazione": "LISSONE",
        "idProvinciaRegistrazione": "108",
        "siglaProvinciaRegistrazione": "MB",
        "numeroatto": "7",
        "tipoDichiarante": "1",
        "ausilioInterprete": "false",
        "intestatari": [{
                "cognome": "ROBA",
                "nome": "MASSIMO",
                "sesso": "M",
                "dataNascita": "1955-12-07",
                "idComuneNascita": "16449",
                "nomeComuneNascita": "GENOVA",
                "idProvinciaNascita": "10",
                "siglaProvinciaNascita": "GE",
                "idStatoNascita": "100",
                "nomeStatoNascita": "ITALIA"
            }
        ],
        "madre": {
            "cognome": "ROBA",
            "nome": "MAMMA",
            "sesso": "F",
            "dataNascita": "1931-05-06",
            "idComuneNascita": "20499",
            "nomeComuneNascita": "UDINE",
            "idProvinciaNascita": "30",
            "siglaProvinciaNascita": "UD",
            "idStatoNascita": "100",
            "nomeStatoNascita": "ITALIA",
            "idComuneResidenza": "10323",
            "nomeComuneResidenza": "UDINE",
            "idProvinciaResidenza": "30",
            "siglaProvinciaResidenza": "UD",
            "idStatoResidenza": "100",
            "nomeStatoResidenza": "ITALIA",
            "idNazionalita": "100",
            "nazionalita": "ITALIANA",
            "flagDichiarante": false,
            "flagComparente": false,
            "flagFirmatario": false
        },
        "padre": {
            "cognome": "ROBA",
            "nome": "BABBO",
            "sesso": "M",
            "dataNascita": "1925-04-02",
            "idComuneNascita": "18610",
            "nomeComuneNascita": "TARANTO",
            "idProvinciaNascita": "73",
            "siglaProvinciaNascita": "TA",
            "idStatoNascita": "100",
            "nomeStatoNascita": "ITALIA",
            "idComuneResidenza": "18610",
            "nomeComuneResidenza": "TARANTO",
            "idProvinciaResidenza": "73",
            "siglaProvinciaResidenza": "TA",
            "idStatoResidenza": "100",
            "nomeStatoResidenza": "ITALIA",
            "idNazionalita": "100",
            "nazionalita": "ITALIANO",
            "flagDichiarante": false,
            "flagComparente": false,
            "flagFirmatario": false
        },
        "datiDichiarante": {
            "comprensione": "0"
        },
        "datiDiNascita": {
            "luogoFiliazione": "ospedale del comune di GENOVA",
            "oraNascita": "1",
            "minutoNascita": "54",
            "tipoAccertamento": "4"
        },
        "composizioneCompleta": " L\u0027anno duemilaventitre addi\u0027 nove del mese di giugno alle ore quindici e minuti trenta nella  -  % casa comunale. Avanti a me, GORI MARTINA, , Ufficiale dello stato civile del Comune di  -------  % QUARRATA per delega avuta e\u0027 compars   nat in  li  residente in   quale mi ha dichiarato  -----  % quanto segue: ---------------------------------------------------------------------------------  % Il giorno SETTE del mese di DICEMBRE dell\u0027anno MILLENOVECENTOCINQUANTACINQUE alle ore UNA e  --  % minuti CINQUANTAQUATTRO nel ospedale del comune di GENOVA da ROBA MAMMA nata in UDINE il  -----  % 06.05.1931 cittadina ITALIANA residente in UDINE moglie del dichiarante, cittadino ITALIANO e\u0027   % nato un bambino di sesso MASCHILE. ------------------------------------------------------------  % A detto bambino che non mi viene presentato, ma della cui nascita io mi sono accertato a mezzo   % della attestazione di nascita rilasciata dall\u0027ostetrica il dichiarante dà il nome di MASSIMO .   % -----------------------------------------------------------------------------------------------  % Il presente atto viene letto all\u0027 intervenuto, il quale insieme con me, lo sottoscrive. -------  %                                                                                                  %                                                                                                  %                                                                                                  %                                                                                                  %                                                                                                  %L\u0027UFFICIALE DI STATO CIVILE:                                                                    %\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d            %"
    },
    "testataRichiesta": {
        "idComune": 5000,
        "idOperazioneComune": "8",
        "dataOraRichiesta": "2023-06-09T15:31:14.461+02:00",
        "nomeApplicativo": "urbi",
        "versioneApplicativo": "0.1.0",
        "fornitoreApplicativo": "padigitale"
    }
}

**Comment by amusarra** [comment]
Salve @biadanpad 
Il problema è descritto dalla issue #175 
In questo caso il valore per l'attributo `idStatoNascita` deve essere `90` (Italia) e non `100` (Libano)

Se non ci sono altri chiarimenti le chiedo di chiudere la issue.

Cordiali Saluti.
Supporto ANSC.

**Comment by biadanpad** [comment]
Grazie.

Potrebbe per sicurezza indicarmi la tabella dove trovo i codici di tutti i stati?

**Comment by amusarra** [comment]
Sulla issue #175 è stato indicato il link che riporto qui https://www.anagrafenazionale.interno.it/area-tecnica/tabelle-di-decodifica/

Se non ci sono ulteriori dubbi o chiarimenti le chiediamo di chiudere la issue.

Cordiali Saluti.
Supporto ANSC.
