### ISSUE TITLE
Richiesta informazioni tempistiche

### ISSUE THREAD

**Issue by SAlberto** [italia/ansc#18]
Buongiorno,
siamo a richiedere un chiarimento riguardo alla data di scadenza entro la quale i comuni devono effettuare l'adozione della piattaforma ANSC.
Ci è giunta voce che ci sia una proroga, al 31-12-**2024**, ma guardando la documentazione è ancora indicato 31-12-**2023**.

In attesa di una cortese risposta, ringraziamo anticipatamente.

**Comment by AlessandriniPCM** [comment]
Gentilissimi,
in conformità al c. 4 dell'art. 13 del D.M del 18 ottobre 2022 recante _Aggiornamento della piattaforma di funzionamento dell'Anagrafe nazionale della popolazione residente per l'erogazione dei servizi resi disponibili ai comuni per l'utilizzo dell'Archivio nazionale informatizzato dei registri dello stato civile_; i comuni aderiscono all'ANSC **entro diciotto mesi** dalla data della comunicazione da parte del Ministero dell'interno della messa a disposizione del servizio in ambito nazionale. 

Tra febbraio e marzo 2023, alcuni comuni con le rispettive software house, hanno avviato la fase di sperimentazione che si concluderà tra aprile e maggio. A quel punto i comuni che avranno portato a termine positivamente la suddetta fase di sperimentazione potranno avviare, a partire da maggio 2023, la successiva fase di adozione controllata, la quale, a sua volta, si concluderà nel mese di settembre 2023. 

Solo a questo punto, e a condizione che tutte le fasi precedenti abbiano avuto esito positivo, il Ministero dell'interno potrà predisporre la comunicazione in parola (c.4 art. 13 D.M 18 ottobre 2022) facendo iniziare il periodo di 18 mesi concesso per l'adesione ad ANSC da parte di tutti i comuni. Ipotizzando che tale comunicazione possa essere diffusa entro ottobre 2024, i comuni dovranno terminare il processo di adesione ai servizi centralizzati di ANSC, al massimo, nel mese di marzo 2025.

**Comment by SAlberto** [comment]
Chiarissimo, potrei chiedere la stessa informazione sulle tempistiche per quanto riguarda la parte Elettorale su ANPR?

Grazie

**Comment by mttfranci** [comment]
Buongiorno @SAlberto  ci permettiamo di rimandarvi al repository gemello di ANPR :
https://github.com/italia/anpr/issues

In linea di massima usiamo questo canale solo per le domande sullo Stato Civile 

Saluti
