### ISSUE TITLE
Atto di Matrimonio - UseCase 319999: Dati Pubblicazione da consolato

### ISSUE THREAD

**Issue by DiBellaDavide** [italia/ansc#180]
Salve,
Nel caso d'uso in oggetto il matrimonio può essere celebrato su delega di un consolato. In base al mapping la pubblicazione di un atto di matrimonio prevede obbligatoriamente i dati di provincia e comune che nella casistica in analisi sono esteri. Non essendo censite le province e i comuni esteri, come passare questi dati inerenti alla pubblicazione?
Attendo riscontro.

Distinti saluti.

**Comment by amusarra** [comment]
Salve @DiBellaDavide 
Nel payload di validazione, specificando come idStato il valore che fa riferimento a uno stato estero, il servizio non dovrebbe controllare l'obbligatorietà del comune e provincia. Sul portale di ANPR https://www.anagrafenazionale.interno.it/area-tecnica/tabelle-di-decodifica/ sono disponibili i CSV con le decodifiche degli stati.

Nel caso in cui dovesse risolvere il problema la invitiamo a chiudere la issue.

Cordiali Saluti.
Supporto ANSC

**Comment by amusarra** [comment]
Salve @DiBellaDavide 
Stando al model e mapping https://github.com/italia/ansc/blob/main/docs/Mapping_casi_uso/matrimoni/Matr_999_1.csv i dati da lei indicati non risultano essere obbligatori, non dovrebbe quindi avere problemi a eseguire la validazione del payload relativo.

<img width="1180" alt="image" src="https://github.com/italia/ansc/assets/708110/7f893771-f2ad-4c35-ba4b-7805e8f50685">

Chiudo la issue, nel caso sia necessario riapra la stessa.

Cordiali Saluti.
Supporto ANSC.
