### ISSUE TITLE
[R007] - Errore nella firma USC

### ISSUE THREAD

**Issue by ManuelDeMeo** [italia/ansc#181]
Buongiorno, segnaliamo un errore nel servizio R007 per la firma USC.

L'ambiente è preproduzione e l'invocazione è stata fatta oggi 09/06/2023.

L'idOperazione è 1599785; il dettaglio della risposta è il seguente:

```
{
   "errors":[
      {
         "code":"406004",
         "severity":"E",
         "text":"Stato evento non valido per l'operazione richiesta"
      }
   ],
   "testataRisposta":{
      "idComune":4559,
      "idOperazione":"1599785",
      "idOperazioneComune":"3a37b623-1950-43e7-9763-80d683b026c6"
   }
}

```
Abbiamo sbagliato qualcosa nella richiesta?

Grazie

**Comment by amusarra** [comment]
Buongiorno @ManuelDeMeo 
L'errore indicato è sollevato a causa dell'introduzione con la versione 1.9 della funzionalità **Recupero atto firmato dal dichiarante entro un tempo prestabilito (2 ore)**.

Da verifiche eseguite sul sistema, il tempo a disposizione (da quando è stato firmato dal dichiarante) di 2h è scaduto, ecco il motivo del messaggio di errore **"Stato evento non valido per l'operazione richiesta"**. In queste condizioni, l'evento può essere solo annullato.

Chiudiamo la issue. Nel caso fosse necessario riaprite pure.

Cordiali Saluti.
Supporto ANSC.
