### ISSUE TITLE
[R012] - Doppia email

### ISSUE THREAD

**Issue by ManuelDeMeo** [italia/ansc#182]
Ambiente: preprod
Data: 12/06/2023
IdOperazioneComune: a8fde81b-aecc-4774-8c58-3e0a68540187

Buongiorno,
segnaliamo che a seguito di invocazione del servizio R012  /firmadichiarante/invio-email/1 sono state ricevute due email.

**Comment by amusarra** [comment]
Salve @ManuelDeMeo 
Sappiamo del problema la cui risoluzione è in fase di analisi.

Cordiali Saluti.
Supporto ANSC.
