### ISSUE TITLE
Errore di connessione ai servizi ANSC

### ISSUE THREAD

**Issue by siscomanpr** [italia/ansc#183]
Buongiorno,
è da questa mattina, dalle 11 circa, che stiamo avendo problemi a chiamare i servizi ANSC. 
Ci sono problemi di carattere generale o è un problema solo nostro?

**Comment by gcuci** [comment]
buongiorno,

segnaliamo anche noi lo stesso problema.
Da qualche ora, tutti i tentativi di invocazione ai servizi, ritornano un 'Error: read ECONNRESET'.

**Comment by MichelaGarzoni** [comment]
Buongiorno, noi stesso problema da un paio di ore

**Comment by amusarra** [comment]
Salve a tutti.
Facciamo delle verifiche.

Cordiali Saluti.
Supporto ANSC.

**Comment by amusarra** [comment]
In attesa del completamento delle verifiche sui nostri sistemi, potreste provare a disabilitare sui vostri client REST l'estensione SNI? Per coloro che usano la piattaforma Java, basta impostare la system property `-Djsse.enableSNIExtension=false`

Cordiali Saluti.
Supporto ANSC.

**Comment by biadanpad** [comment]
impostando la system property -Djsse.enableSNIExtension=false sembra funzionare correttamente

**Comment by amusarra** [comment]
Salve a tutti. Per informarvi che il sistema è tornato a funzionare in modo regolare per la parte di connettività SSL/TLS.
Non è quindi più necessario applicare il workaround (@biadanpad).

Chiudiamo la issue.

Cordiali Saluti.
Supporto ANSC.
