### ISSUE TITLE
[3.2.1.3.1.1] Atto di Matrimonio - Indirizzo e Numero Civico

### ISSUE THREAD

**Issue by DiBellaDavide** [italia/ansc#184]
Salve,
nel caso d'uso in analisi, nel servizio di validazione vengono richiesti come obbligatori indirizzo e numero civico del luogo celebrazione nonostante questi dati siano considerati non obbligatori nel file del mapping associato. Nella WebApp inoltre, durante la fase di compilazione, questi campi non sono presenti.
Attendo vostro riscontro.

Distinti saluti.

**Comment by amusarra** [comment]
Salve @DiBellaDavide 
Al fine di condurre le analisi nel modo più adeguato anche per replicare il problema segnalato, potrebbe indicare l'idOperazione in modo tale da poter risalire al payload?

Grazie.
Supporto ANSC.

**Comment by amusarra** [comment]
Grazie @DiBellaDavide abbiamo recuperato il payload usato e presa in gestione la segnalazione come bug.

Cordiali Saluti.
Supporto ANSC.

**Comment by asqueglia** [comment]
Buonasera con la versione 1.11.0 è stata corretta la segnalazione. 
La issue viene chiusa nel caso si prega di riaprirla.
