### ISSUE TITLE
Errori gestione annotazione automatica da atto di matrimonio

### ISSUE THREAD

**Issue by antonioluberto** [italia/ansc#186]
Abbiamo creato l'atto di stato civile
**2023-953864-90-058046**
per il caso d'uso
**Matr_001**.
Abbiamo indicato per sposo e la sposa la presenza di atto di nascita cartaceo presente presso due Comuni diversi tra loro e diversi dell'Ente Gestore (Comune di Grottaferrata).

Condotto l'iter di formazione dell'atto digitale fino alla sottoscrizione da parte dell'usc, l'elenco delle comunicazioni ANSC risulta vuoto; in particolare, manca la comunicazione contenente l'identificativo dell'annotazione da apporre (in forma cartacea) sull'atto di nascita dello sposo e della sposa (comunicazione che dovrebbe esserci stanti le indicazioni contenute a pag. 6 di https://github.com/italia/ansc/blob/main/docs/Note/NotaProcessoAnnotazioniAndQuickCoopServiceFlow/NotaProcessoAnnotazioniAndQuickCoopServiceFlow.pdf).
Abbiamo provato a verificare se notizie in questo senso vi fosse tra le "notifiche" collegate all'evento principale (tramite il servizio R008), ma l'unica notifica disponibile contiene solo i dati:

![image](https://github.com/italia/ansc/assets/26415430/4576e124-d93a-4c16-8424-f38a93e80072)

che non consente in alcun modo all'Ente di sapere quale annotazione apporre su quale atto.

Per completezza: su WebApp troviamo 2 notifiche, rispettivamente per sposo e sposa
![image](https://github.com/italia/ansc/assets/26415430/e638f25b-4fe0-4e6c-af2f-02666a3c63c2)

ma le stesse contengono il solo testo da riportare in annotazione senza indicare quale sia il Comune che debba procedere all'annotazione in esame: se il Comune A invia al Comune B specifica "comunicazione" per richiedere, al Comune B, l'apposizione su specifico atto di specifica annotazione, la "comunicazione" in questione deve almeno contente:
- l'indicazione del Comune destinatario (il comune B)
- i riferimenti (anno/numero/parte/serie/anno/, ed eventualmente ufficio) dell'atto di nascita presente presso il Comune B (ed indicato in sede di redazione dell'atto di matrimonio) sula quale si chiede l'apposizione dell'annotazione

**Comment by asqueglia** [comment]
Buongiorno, il flusso delle annotazioni / notifiche annotazioni verso il comune di formazione dell'atto di nascita subirà delle modifiche richieste dal Ministero. Vi faremo sapere appena possibile.

**Comment by asqueglia** [comment]
Buongiorno, come condiviso nella call di avanzamento lavori con il DTD, inseriamo qui nella issue un breve recap sulla modellazione dei flussi previsti per le annotazioni.
Per quanto concerne gli atti cartacei, indipendentemente dal comune che li detiene se subentrato o meno, il flusso di invio delle proposte di annotazioni è demandato al comune di formazione dell'atto e sarà gestito extra flusso.
Per quanto concerne gli atti digitali, il sistema ANSC, a seguito della registrazione di un atto secondario, genererà automaticamente la proposta di annotazione che verrà notificata al comune di competenza; il comune dovrà provvedere alla conferma dell'annotazione; questo flusso è descritto nella issue del rilascio del 5/09 #323  insieme alla documentazione anticipata del servizio di notifica.
Per quanto concerne le annotazioni da registrare come evento, si confermano i casi d'uso previsti per le annotazioni modificative (per errore materiale e rettifica) per ogni registro; si conferma inoltre il caso d'uso di servizio, previsto per ogni registro, per la registrazione delle annotazioni integrative.
Per quanto riguarda le annotazioni contestuali, si conferma il modello già implementato che consente la registrazione di un evento con annotazioni contestuali; è attualmente in corso una analisi con ANUSCA, sul discorso della certificabilità delle annotazioni contestuali.

**Comment by asqueglia** [comment]
La issue viene chiusa; in caso di problemi si prega di aprirne una nuova.
