### ISSUE TITLE
Assenza notifiche per aggiornamento anagrafe

### ISSUE THREAD

**Issue by antonioluberto** [italia/ansc#187]
Nelle ultime settimane abbiamo creato gli atti di stato civile:
a) di nascita, tra i quali:
2023-951620-4-058046
2023-951708-10-058046
2023-951745-15-058046
2023-951914-27-058046
2023-952521-47-058046
2023-952544-48-058046
2023-952926-65-058046
2023-953620-72-058046

b) di morte, tra i quali:
2023-953850-84-058046

c) di matrimonio, tra i quali:
2023-953864-90-058046

Sono tutti casi d'uso per i quali l'anagrafe dell'Ente Gestore (Comune di Grottaferrata) avrebbe dovuto ricevere notifica per il necessario aggiornamento anagrafico, ma le notifiche in questo senso non sono disponibili con il servizio ANPR 4005; in allegato lo zip contenente il file di richiesta e quello di risposta relativi all'ultimo tentativo
[RequestResponse4005.zip](https://github.com/italia/ansc/files/11736970/RequestResponse4005.zip).

Notifiche nel senso atteso mancano anche sulla WebApp ANPR.

**Comment by asqueglia** [comment]
Buongiorno dott. Luberto, abbiamo verificato che per gli atti indicati non è stata impostata la data validità tramite invocazione del servizio {{R014}}/evento/data-validita/{version}. E' indispensabile invocare tale servizio a valle della registrazione di un atto per indicare la data di validità da inviare in anagrafiche altrimenti non vengono effettuate le predisposizioni anagrafiche e nè inviate le relative notifiche. Questo è il motivo per cui non sono state generate le comunicazioni anagrafiche per gli eventi indicati.

**Comment by asqueglia** [comment]
Buon pomeriggio, in realtà sono stati rilasciati solo i servizi per la consultazione delle notifiche; la web app ANPR non è ancora stata aggiornata per il recepimento e consultazione delle annotazioni; appena verrà rilasciata la web app aggiornata in tal senso ne daremo comunicazione.

**Comment by antonioluberto** [comment]
Buongiorno.
Abbiamo eseguito anche il tentativo di acquisizione delle notifiche per ANPR da servizio, sia su ambiente ANPR di test del Comune sperimentatore (Grottaferrata) sia su ambiente ANPR di test  di altro Comune, ma ancora non otteniamo risposta.

Allego:
a) il file _R014_Impostazione data validità_1.zip_ contenente richiesta e risposta relative all'impostazione della data validità mediante servizio ANSC R014 per atto di morte 
2023-954057-103-058046
il cui titolare è cittadino residente presso il Comune Gestore (Grottaferrata)
b) il file _R014_Impostazione data validità_2.zip_ contenente richiesta e risposta relative all'impostazione della data validità mediante servizio ANSC R014 per atto di morte 
2023-953950-101-058046
il cui titolare è cittadino residente presso comune italiano diverso dal Comune sperimentatore (Brentonico)
c) il file _[4005_Richiesta notifiche anagrafiche_2.zip](https://github.com/italia/ansc/files/11758714/4005_Richiesta.notifiche.anagrafiche_2.zip).zip_ contenente richiesta e risposta relative alla ricerca delle notifiche anagrafiche tramite il servizio ANPR 4005 su ambiente ANPR di test del Comune di Grottaferrata.
d) il file _4005_Richiesta notifiche anagrafiche_2.zip_ contenente richiesta e risposta relative alla ricerca delle notifiche anagrafiche tramite il servizio ANPR 4005 su ambiente ANPR di test del Comune di Brentonico.


Rimaniamo in attesa di vostre indicazioni.


[4005_Richiesta notifiche anagrafiche_1.zip](https://github.com/italia/ansc/files/11758715/4005_Richiesta.notifiche.anagrafiche_1.zip)
[R014_Impostazione data validità_2.zip](https://github.com/italia/ansc/files/11758716/R014_Impostazione.data.validita_2.zip)
[R014_Impostazione data validità_1.zip](https://github.com/italia/ansc/files/11758717/R014_Impostazione.data.validita_1.zip)

**Comment by gbuemi** [comment]
Buonasera, 
ci risulta che per entrambi gli atti, 2023-954057-103-058046 e 2023-953950-101-058046, sono disponibili le notifiche per il comune di Grottaferrata. Non risultano notifiche per il comune di Brentonico.

Le notifiche vengono create alcune ore dopo la registrazione, si consiglia di verificare la corretta generazione delle notifiche il giorno dopo la registrazione dell'evento. Ci risulta che la request _Grottaferrata-uat-Request4005-Prenotazione.xml_ sia stata effettuata subito dopo la registrazione dell'atto 2023-954057-103-058046, prima che la notifica fosse stata generata.

La request _Grottaferrata-uat-Request4005-Prenotazione.xml_, con il periodo di riferimento indicato, selezionerebbe adesso la notifica per l'atto 2023-954057-103-058046. Estendendo il periodo di riferimento dal 2023-06-14T00:00:00 al 2023-06-15T23:59:00 selezionerebbe invece entrambe le notifiche in questione.

Cordiali saluti,
Supporto ANSC.

**Comment by antonioluberto** [comment]
Buongiorno.
Abbiamo ora verificato la disponibilità, tramite servizio ANPR 4005 su ambiente del Comune di Grottaferrata:
a) della notifica riferita al procedimento anagrafico collegato all'atto di morte
2023-953950-101-058046
per il cui titolare (Bertesina Allegra) era indicata residenza presso il Comune Grottaferrata medesimo.
b) della notifica riferita al procedimento anagrafico collegato all'atto di morte
2023-954057-103-058046
per il cui titolare (Zampogno Battista) era indicata residenza presso Comune diverso da Grottaferrata (nello specifico, Comune di Brentonico).

Se pare corretto che l'anagrafe di Grottaferrata riceva la notifica di cui al punto a), non è chiaro perché riceva la notifica di cui al punto b): in questo secondo caso, infatti, il procedimento anagrafico che consegue alla conferma dell'atto (di morte) di stato civile è di competenza di un altro Comune (nel caso di specie, Comune di Brentonico, sul cui ambiente il servizio ANPR 4005 non restituisce alcuna notifica).

Com'è previsto che il Comune (di Brentonico in questo caso, ma in generale un Comune diverso dal Comune che ha prodotto l'atto digitale) sia informato della necessità di istruire un procedimento anagrafico a seguito di un adempimento di stato civile prodotto in ANSC da altro Comune italiano?

Aggiungo, per completezza, che l'elenco delle comunicazioni ANSC disponibili per entrambi i casi d'uso è vuoto.

Rimaniamo in attesa di vostre indicazioni.
Saluti

**Comment by gbuemi** [comment]
Buongiorno,
ci risulta che entrambi i soggetti Bertesina Allegra e Zampogno Battista abbiano residenza a Grottaferrata. Su ANPR il dato risulta coerente con quanto indicato, pertanto non risultano anomalie in termini di trasmissione della notifica di cui al punto b) del precedente messaggio.

Per quel che riguarda le comunicazioni le confermo che per le morti non sono previste in ANSC.

Restiamo a disposizione.

Cordiali saluti,
Supporto ANSC.
