### ISSUE TITLE
[web-service] Atti di Matrimonio - Payload di Test

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/ansc#188]
buongiorno 

si chiede di integrare la documentazione (https://github.com/italia/ansc/tree/main/docs/CasiTest/payload_test) con payload di test relativi alla validazione di eventi matrimonio / unione civile / cittadinanza.

gli esempi semplificherebbero il processo di produzione e verifica dei json prodotti dal gestionale.

grazie.
Alessandro Monopoli ADS

**Comment by asqueglia** [comment]
Buongiorno con il prossimo rilascio previsto al più inizio prossima settimana integreremo la documentazione con i payload di esempio richiesti.

**Comment by asqueglia** [comment]
Buongiorno confermiamo che con il rilascio della versione 1.9.1 sono stati aggiunti ulteriori payload di esempio in docs/CasiTest/payload_test/. Chiudiamo la issue, nel caso la preghiamo di riaprirla.
