### ISSUE TITLE
Errore caso d'uso Matr_999_2

### ISSUE THREAD

**Issue by antonioluberto** [italia/ansc#189]
La modellazione relativa al caso d'uso in oggetto non indica come obbligatori i dati relativi ai testimoni, correttamente in quanto dovrebbe trattarsi della trascrizione di un atto di matrimonio celebrato con rito religioso.
La creazione dell'atto fallisce segnalando però proprio la mancanza dei dati relative ai testimoni.

**Comment by DiBellaDavide** [comment]
Segnalo anch'io lo stesso errore all'invocazione del servizio di validazione. Se possono essere utili ecco i dati della nostra richiesta:
UseCase: 329999 ovvero Matr_999_2
Ambiente di pre-prod , data invio della richiesta 19/06/23, idOperazione = 1602299

**Comment by FTravagliniADS** [comment]
Buongiorno,
segnaliamo stesso errore in fase di validazione ( obbligatorietà sul numeroTestimoni ) su un atto il cui cdu ci risulta essere quello con codice "329999". Nel nostro caso l'idOperazione è 1603694.
Grazie

**Comment by amusarra** [comment]
Salve @FTravagliniADS come risposto a @DiBellaDavide il caso d'uso usato 329999 non è una trascrizione, motivo per cui è richiesto di specificare i testimoni.

Cordiali Saluti.
Supporto ANSC.

**Comment by amusarra** [comment]
> Salve @DiBellaDavide e @antonioluberto Analizzando il payload segnalato da @DiBellaDavide ho avuto modo di riscontrare che sul payload è indicato come valore per l'attributo `idUsecase` il valore `329999` che nella realtà corrisponde a ["329999","Caso d'uso di servizio (matrimoni con rito religioso)","Matr_999_2","III",""](https://github.com/italia/ansc/blob/6865d7cc81f8abbff7621855ad3119d6e7806292/docs/Mapping_casi_uso/3_dec_use_case.csv).
> 
> Il valore corretto per l'attributo `idUsecase` è [339999](https://github.com/italia/ansc/blob/6865d7cc81f8abbff7621855ad3119d6e7806292/docs/Mapping_casi_uso/3_dec_use_case.csv).
> 
> Inviando il vostro payload con il valore corretto per IdUsecase, questo andrà a buon fine. Abbiamo eseguito un test in ambiente di pre-produzione.
> 
> ![image](https://user-images.githubusercontent.com/708110/246855259-2579be96-5a5c-41ea-a1f7-b252a82cb370.png)
> 
> Dopo le vostre verifiche, vi chiediamo la cortesia di chiudere la issue.
> 
> Cordiali Saluti. Supporto ANSC.

@DiBellaDavide se la risposta è stata esauriente la preghiamo di chiudere la issue.

Grazie.
Supporto ANSC.

**Comment by AMonopoliADS** [comment]
@amusarra scusa l'insistenza, ma probabilmente stiamo fraintendendo noi il modo di gestire questo caso d'uso, per cui cerco di spiegare meglio la nostra interpretazione, x capire dove sbagliamo.

nel caso segnalato da @FTravagliniADS si tenta di inviare un matrimonio religioso (atto originale)
in questa fattispecie i casi d'uso previsti sembrerebbero essere i seguenti:
321311	Matrimonio con Rito Religioso Cattolico	
321321	Matrimonio con Rito Religioso Cattolico con Riconoscimento di uno o piu' figli	
321411	Matrimonio con Rito Religioso Acattolico
321421	Matrimonio con Rito Religioso Acattolico con riconoscimento di uno o piu' figli
329999	Caso d'uso di servizio (matrimoni con rito religioso)

se utilizziamo il caso d'uso 321311, il sistema valida l'atto senza indicazione dei testimoni (idAttoAnsc 2023-954467-175-039010)
se utilizziamo il caso d'uso 329999 (che ci sembra comunque adeguato per la casistica di matrimonio religioso - NON trascrizione), il sistema NON valida l'atto perchè richiede il numeroTestimoni (idOperazioneComune 2023000855 - idOperazioneAnsc 1603931)

quello che non capiamo è il perchè, nell'opzione di caso di servizio dovremmo utilizzare il caso d'uso 339999, che invece gestisce l'evento di trascrizione matrimonio.

grazie
Alessandro

**Comment by amusarra** [comment]
Salve @AMonopoliADS i casi d'uso che richiedono da configurazione il numero dei testimoni sono indicati a seguire https://github.com/search?q=repo%3Aitalia%2Fansc%20numeroTestimoni&type=code

Per quanto riguarda il caso d'uso di servizio 329999 verifichiamo perché sia configurato il numero di testimoni come obbligatorio.

Cordiali Saluti.
Supporto ANSC.

**Comment by amusarra** [comment]
Chiudiamo la issue per via del rilascio della versione 1.10.0 che risolve questa segnalazione.

Cordiali Saluti.
Supporto ANSC.
