### ISSUE TITLE
Possibili firme miste digitali/cartacea ?

### ISSUE THREAD

**Issue by migmar68** [italia/ansc#19]
Faccio l'esempio di un matrimonio dove devono firmare i 2 sposi, i 2 testimoni e ovviamente lo USC.
Dei 4 intervenuti, 3 sono in grado di firmare digitalmente, e uno no.
Lo USC potrebbe raccogliere la firma cartacea per tutti e risolvere il problema così.
E' una scelta obbligata, oppure ha anche l'opportunità di "accontentare" i cittadini e raccogliere prima le firme digitali possibili, e poi quella cartacea dove firma il solo cittadino mancante?

**Comment by mttfranci** [comment]
Salve, si il sistema permetterà qualsiasi combinazione di tipologie di firme.
Saluti.
