### ISSUE TITLE
[R012] Annulla Link

### ISSUE THREAD

**Issue by LoreL56** [italia/ansc#190]
Buonasera, 
stavamo provando l'invocazione del servizio di annullaLink.

Viene ritornato il seguente errore:
Non hai accesso alla risorsa (300) - "403300"

L'idOperazione è 1601353

Grazie

**Comment by amusarra** [comment]
Salve @LoreL56 potrebbe fare nuovamente la richiesta?

Grazie.
Supporto ANSC.

**Comment by amusarra** [comment]
Salve @LoreL56 
Abbiamo avuto modo di analizzare la sua utenza e risulta correttamente configurata. 
Il Codice 300 indicato sul messaggio di errore  `Non hai accesso alla risorsa (300) - "403300"`, significa che il payload di richiesta non contiene la testata.

Il sistema ANSC ha ricevuto come payload il seguente, dove manca la testata di richiesta.

```json
{"idPresaVisione":"1983359"}
```

La invitiamo a rifare la richiesta in modo corretto, inserendo anche la testata.
Chiudiamo la issue, in caso di necessità riapra pure.

Cordiali Saluti.
Supporto ANSC.

**Comment by LoreL56** [comment]
Grazie,
la vostra diagnosi è corretta.
