### ISSUE TITLE
UseCase : 2104 - Morte_004 - 500 Internal Server Error

### ISSUE THREAD

**Issue by DiBellaDavide** [italia/ansc#191]
Salve,
invocando il servizio di validazione per il caso d'uso indicato, viene restituito l'errore 500 Internal Server Error.
Potreste darmi delucidazioni in merito?
Ambiente di pre-produzione, data del test 16/06/23
IdOperazione: 1601948

**Comment by amusarra** [comment]
Salve @DiBellaDavide 
Abbiamo avuto modo di replicare il problema segnalato per cui abbiamo preso in carico la segnalazione.

Cordiali Saluti.
Supporto ANSC.

**Comment by amusarra** [comment]
Chiudiamo la issue per via del rilascio della versione 1.10.0 che risolve questa segnalazione.

Cordiali Saluti.
Supporto ANSC.
