### ISSUE TITLE
Errore Generazione Client con Swagger

### ISSUE THREAD

**Issue by ATropeano** [italia/ansc#192]
Buonasera. Nel generare il client con https://editor.swagger.io/ del servizio R009_validazione.yaml,
Swagger segnala questi 3 errori:

_Structural error at components.schemas.PrenotaEventoRequest.allOf.1.properties.numeroGemelliNatiVivi.required
should be an array of property names required within an object schema
Jump to line 190
Structural error at components.schemas.PrenotaEventoRequest.allOf.1.properties.listaNumeriComunali.items.required
should be an array of property names required within an object schema
Jump to line 196
Structural error at components.schemas.PrenotaEventoRequest.allOf.1.properties.idUsecase.required
should be an array of property names required within an object schema
Jump to line 201_

che si riferiscono alla key/tag:

    PrenotaEventoRequest:
      description: Richiesta di prenotazione id nazionali per il parto gemellare e plurigemellare
      allOf:
        - $ref: 'https://italia.github.io/ansc/docs/openapi/base_servizi.yaml#/components/schemas/AnscRequest'
        - type: object
          properties:
            numeroGemelliNatiVivi: 
             type: string
             description: Numero di gemelli nati vivi
             example: 2
             required: true
            listaNumeriComunali:
             type: array
             items:
              type: string
              description: Lista numero comunale univoco assegnato per ogni gemello
              required: true
            idUsecase: 
             type: string
             description: Id del caso d'uso cui si riferisce l'evento.
             example: 1170
             required: true   

Con la seguente modifica gli errori segnalati da Swagger scompaiono:

    PrenotaEventoRequest:
      description: Richiesta di prenotazione id nazionali per il parto gemellare e plurigemellare
      allOf:
        - $ref: 'https://italia.github.io/ansc/docs/openapi/base_servizi.yaml#/components/schemas/AnscRequest'
        - type: object
          required:
            - numeroGemelliNatiVivi
            - listaNumeriComunali
            - idUsecase
          properties:
            numeroGemelliNatiVivi: 
             type: string
             description: Numero di gemelli nati vivi
             example: 2
            listaNumeriComunali:
             type: array
             items:
              type: string
              description: Lista numero comunale univoco assegnato per ogni gemello
            idUsecase: 
             type: string
             description: Id del caso d'uso cui si riferisce l'evento.
             example: 1170

**Comment by amusarra** [comment]
Buongiorno @ATropeano 
Potrebbe verificare se con la versione rilasciata ieri è presente ancora il problema?

**Comment by ATropeano** [comment]
Buonasera. L'errore si genera anche sulla nuova versione - del resto facendo un confronto tra le due versioni sembra che sia stata cambiato solo la specificazione del formato della chiave/tag dataFormazioneEvento...

**Comment by amusarra** [comment]
Salve @ATropeano 
Sappiamo che c'è altro errore e abbiamo preso in carico e in fase di risoluzione.

**Comment by amusarra** [comment]
Chiudiamo la issue per via del rilascio della versione 1.10.0 che risolve questa segnalazione.

Cordiali Saluti.
Supporto ANSC.
