### ISSUE TITLE
Configurazione obbligatorietà allegati in usecase 11115200 motore Dic_Nasc_080

### ISSUE THREAD

**Issue by corradosacco** [italia/ansc#193]
Buongiorno,
 in merito allo usecase in oggetto non mi giustifico l'obbligatorietà dell'allegato "Attestazione di nascita" a prescindere dalla scelta effettuata nella casella Tipo accertamento. Mi sarei aspettato, come negli usecase analoghi, che diventasse obbligatorio se e solo se nella casella Tipo accertamento fosse stata scelta l'opzione "Attestazione di nascita".

Cordiali saluti

**Comment by asqueglia** [comment]
Buongiorno, è esattamente come si aspetta. 
Se tipoAccertamento =1 l'allegato obbligatorio è l'attestato di nascita
se tipoAccertamento = 2 l'allegato obbligatorio è la constatazione di avvenuto parto

se tipoAccertamento =3 l'allegato obbligatorio è la dichiarazione sostitutiva di nascita
se tipoAccertamento =4 il bambino viene presentato e non c'è bisogno di allegare documenti

Se il funzionamento non aderisce a quanto descritto, la preghiamo di fornirci l'id operazione effettuata per verificare meglio la problematica riscontrata.

**Comment by corradosacco** [comment]
Buongiorno, il problema l'ho riscontrato inserendo un atto sulla WebApp (Nr. ID provvisorio 954552)

![image](https://github.com/italia/ansc/assets/127946741/b075782c-00fc-454b-83e9-50b31d4047e3)

**Comment by asqueglia** [comment]
Buongiorno, con il rilascio della versione 1.12.0 la segnalazione è stata corretta; pertanto la issue viene chiusa. In caso vengano riscontrati ulteriori problemi si prega di riaprire l'issue
