### ISSUE TITLE
IdContenitore degli Atti gemellari, non presente.

### ISSUE THREAD

**Issue by gcuci** [italia/ansc#194]
buongiorno,

nell'aggiornamento del Changelog, per l'ultimo rilascio 1.9.0, è indicata l'aggiunta di un idContenitore per legare tra di loro gli atti dei gemelli, nel model_evento.yaml.

La proprietà non è però presente.  

 
In attesa di un riscontro,

cordiali saluti.

**Comment by asqueglia** [comment]
Buongiorno, il contenitore che lega logicamente gli atti dei gemelli, è un meccanismo interno del sistema; non dovete valorizzarlo voi ma è automaticamente gestito da sistema nel momento in cui viene invocato il servizio di prenotazioni numeri che crea le bozze degli atti di ogni gemello assegnando l'identificativo nazionale. Si consiglia di leggere la guida operativa e di verificare il payload di esempio per l'invocazione del servizio di prenotazione. 

Il flusso per gestire i parti gemellari e plurigemellari è il seguente:
- invocazione servizio di prenotazione {{R009}}/prenota/evento/v1
- completamento degli atti in bozza predisposti dal servizio di prenotazione, tramite invocazione del servizio di validazione R009, specificando per ogni atto l'identificativo nazionale restituito dal servizio di prenotazione.
