### ISSUE TITLE
Errore 401: Il certificato di postazione sembra non avere un CN valido

### ISSUE THREAD

**Issue by manny73** [italia/ansc#195]
Salve,
abbiamo ottenuto le credenziali di accesso per il sistema ANSC (Pre-Produzione)
Riusciamo ad usarle per entrare nella webapp ma non per i Servizi Cooperativi di ANSC: forse non valgono per entrambi gli ambienti?

Riceviamo l'errore riportato in oggetto e di seguito

`Call REST Service with JWS...
Service EndPoint: https://anscserviceval.anpr.interno.it/services/service/doc/allegato/upload/1
HttpResponse Code: 401
HttpResponse Body: {"operation":"/services/service/doc/allegato/upload/1","error":"401","error_description":"Il certificato di postazione sembra non avere un CN valido"}`

Grazie mille

Riccardo

**Comment by amusarra** [comment]
Salve @manny73 
Ricordo che l'ambiente è pre-produzione e non validazione come vedo dalla descrizione della issue: `https://anscserviceval.anpr.interno.it/services/service/doc/allegato/upload/1`

Cordiali Saluti.
Supporto ANSC.

**Comment by manny73** [comment]
Perdonami,
mi è era rimasto "in canna" un tentativo sull'ambiente di validazione.
Anche sulla pre-produzione ottengo lo stesso errore:

`Call REST Service with JWS...
Service EndPoint: https://anscservicepre.anpr.interno.it/services/service/doc/allegato/upload/1
HttpResponse Code: 401
HttpResponse Body: {"operation":"/services/service/doc/allegato/upload/1","error":"401","error_description":"Il certificato di postazione sembra non avere un CN valido"}
2023-06-19 14:54:29.587 ERROR 1495 --- [nio-8080-exec-6] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.AssertionError: Response code is not 200] with root cause`

Grazie

**Comment by amusarra** [comment]
Salve @manny73 
Per condurre l'analisi servono il jwt e il CN del certificato in questione. 

È davvero strano che la Web App funzioni correttamente mentre i servizi cooperativi no.

Cordiali saluti.
Supporto ANSC.

**Comment by manny73** [comment]
Salve Antonio,

ho riadattato il vostro esempio ma solo nel passaggio dei parametri, anch'io non mi sarei aspettato questo tipo di problema ma evidentemente non ho fatto tutto per bene!

Sotto riporto le informazioni richieste

RFC 2253 completo:  C=IT,O=Ministero dell'Interno,OU=Anagrafe Nazionale Popolazione Residente,OU=Postazioni di lavoro,CN=052032-CO-0001

`======================================== JWT,JWS and HTTP Header ========================================
JWT: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsIng1YyI6WyJNSUlFNnpDQ0F0T2dBd0lCQWdJSWRzQWFlckRLRHdnd0RRWUpLb1pJaHZjTkFRRUxCUUF3V2pFYk1Ca0dBMVVFQXd3U1EwRWdVRzl6ZEdGNmFXOXVhU0JUZG1sc01RMHdDd1lEVlFRTERBUkJUbEJTTVI4d0hRWURWUVFLREJaTmFXNXBjM1JsY204Z1pHVnNiQ2RKYm5SbGNtNXZNUXN3Q1FZRFZRUUdFd0pKVkRBZUZ3MHlNakE0TURVeE16QTBNVFZhRncweU5URXdNRFV4TVRBNU1qUmFNSUdaTVJjd0ZRWURWUVFEREE0d05USXdNekl0UTA4dE1EQXdNVEVkTUJzR0ExVUVDd3dVVUc5emRHRjZhVzl1YVNCa2FTQnNZWFp2Y204eE1UQXZCZ05WQkFzTUtFRnVZV2R5WVdabElFNWhlbWx2Ym1Gc1pTQlFiM0J2YkdGNmFXOXVaU0JTWlhOcFpHVnVkR1V4SHpBZEJnTlZCQW9NRmsxcGJtbHpkR1Z5YnlCa1pXeHNKMGx1ZEdWeWJtOHhDekFKQmdOVkJBWVRBa2xVTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFqY244WmUyc1FVdXNrNEJqRDRCUGxHbi9Za0xqSm42cU1JWS9NRVNnWUFrM3J1ZmpZZE5jUU5ycTA0ZkFzMHl6N3FnajFHNEFmUVp6ZWpyV1JvVDVxV1pYZzJPMHVaTnJCMVluMzFIS1VMOUdCVjFyQWMydDJnNDc0T2srd040NUJ3MXJRcHoyL3o0bGM2aGdUdnNYa1pORUFzOFFzT2taQ2pvOGxIbHV3TXFvOVFOUDU1Q3pjclJZVGM0QVNPSk9WWmhDZ3JKd1ZWOVpxMWd4T28zWitTV2d5Z1JZZ0Q5czRiOUU2MHFKMzc1OXNrRENEL3QvZ2Jnb3kvM2cvc0NQaVZtRUlRWUZZRjBTTDdFZXhISVBRWG5VZ3hpcVhna0ZxdGlGZTlSRW9BNGlHak0xMnc3S3FpSDlSV1VQMXZBVDM2aWJrQ3FsZUdzQk56N2UzdWtRL3dJREFRQUJvM1V3Y3pBTUJnTlZIUk1CQWY4RUFqQUFNQjhHQTFVZEl3UVlNQmFBRkFZTG44cWgxNW10MUNMdXM0dXhGSlBJVjV0K01CTUdBMVVkSlFRTU1Bb0dDQ3NHQVFVRkJ3TUNNQjBHQTFVZERnUVdCQlJza2FsYUJWaE1JYXhXL0ZZSGVjd21UOFBUN3pBT0JnTlZIUThCQWY4RUJBTUNCNEF3RFFZSktvWklodmNOQVFFTEJRQURnZ0lCQUJxaUNDVWNOYk5mR1p0QUxxNUhrQ1F4a3NZU21Qb1ZvM2huOHlrM09YNWgxeG0yWTFpU0IzckxUVTZsdXdLdVFQdmRZR01talY4bnZxYzZlcWlMeFF4VVhvL05uWG9raHJCQVkvaGhRcHFUcmtzbUJtYUhnb1hYbmkzSnQzOUNpWTliS0Fnb0NGZVBnNzdocDBlSmZxQyt1M21vT2dWaUxZV2RveW4yUXdKRXB5dFBnOFh2Y05URnhQSWFJemZiOVhVSUw4L0g1TXpnTGh0VDF4a2FYZjdZdk9xa2ZzblRtcXF4UFVTV0R6L25mYjZKeGZVTHV4WkE5c1V0OUVHZE1aSjJRYmtYZHpuTUV6TzNxTmM5S2pkS3BGQk56UXhiR0NXNnIyM0Qxc2RrNTRWSlBDZjFqampyTTRXZkdBcUdiY3JOTjR2aEtDMzl2UHpiYWtZSC9yeTlaWXVFUno3UnU4djBHbFdNWHRuaXc1UFIyQlBwdFV1ME5ka2t5ZXhoM2dSQ0VsbTBnREw3eUc0dGcrQjdwRXZ4aGxqclFmaS9BQ0NLZnY5TURwa2s1ZEtOR3dlemZsalBqdWNCdGZjenZLRFExUWtZY1JBTHUra2hVSk9lRVNUYmVGNHRDVnllY24yd1l2K1k3VXNBL0ViQjZRSkJxVUNQOHhoOFN6SW5mWWV5TjhaL0wrMTVOZmJ3N3RyZ1B4WTFyTGVXSnlURVdmN2hoK1RzcFB5Nms5ZzU4SllnY3lFeGZpRDd5aFFaekJCMFpPdDNtNUIzWlZ6NWR3S09ZWWsvdkpSc0NxL3d3Rm5nVUFzYzlRVFdMaUlIQlVRUlcrRHpEN0hscjZ4NnY1L25VNHg4anUrbG9HUDRsRkd1SldoSE1zTjhhNDVXOWdZKzg5UmN1bG9NIl19.eyJzdWIiOiJQUE5SQ1I2NkwxNkEzOTBGIiwiaWF0IjoxNjg3MjA1ODg4LCJleHAiOjE2ODc0MjE4ODgsIm5iZiI6MTY4NzQyMTg4OCwianRpIjoiaUlybDBnVW9KdmNHSU82cjFYbkpsUSIsInNlZGUiOiIwNTIwMzIiLCJwb3N0YXppb25lIjoiMDUyMDMyLUNPLTAwMDEiLCJvdHAiOiIxMjM0NTYifQ.TTQ4GdgqrBvSIvevJHxpxWgcx9Rx2-S_2huPAAwVkARxrM7vFy5MTTTR8rdhoHMXxRNVNYgIWtynZ1Djd8EhjIiGBdnVUrv_QCn_CwUe6EfU0wfAhPMwii15-bvdusv6paGQuHXiH1cnuIlDJRfaIDWwMKh42iQBTU6RFg36UNwN1sOxLL018rFLEnufpmZgldpPXn6qglnydX47fgSH2CtPuEagPnc3Oxbr52_sGSxF6a4NazpVO_qlU-AfHpYWtogtlkFjbo4y5vACiQhNNGMW25LuQkaoq1L5Z6HEniTT8Ikv_eyzntU0SlJMMUMHHJAsb1LXs7HM5xQcWdyYtg
JWS: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.ewogICJhbGxlZ2F0b0lucHV0IjogewogICAgImNvbnRlbnV0byI6ICJYWFhYWFgiLAogICAgIm5vbWVmaWxlIjogIlByb3ZhLnBkZiIsCiAgICAidGlwb0ZpbGUiOiAiMSIsCiAgICAidGlwb0FsbGVnYXRvIjogIjEiLAogICAgImRlc2NyaXppb25lIjogIkF0dGVzdGF6aW9uZSBkaSBuYXNjaXRhIgogIH0sCiAgInRlc3RhdGFSaWNoaWVzdGEiOiB7CiAgICAiaWRDb211bmUiOiA1NjQ2LAogICAgImlkT3BlcmF6aW9uZUNvbXVuZSI6ICJBUFAyMDIyMDMyMjEwMDAwIiwKICAgICJkYXRhT3JhUmljaGllc3RhIjogImdpdSAxLCAyMDIzIiwKICAgICJub21lQXBwbGljYXRpdm8iOiAiU0lEZSIsCiAgICAidmVyc2lvbmVBcHBsaWNhdGl2byI6ICIxLjAuMCIsCiAgICAiZm9ybml0b3JlQXBwbGljYXRpdm8iOiAiU2lzdGVtaUluZm9ybWF0aXZpIgogIH0KfQ.KIB30XnrZai9qGAVMoLwlMeX6nMXUsVbxt_K9jgQgaLtPKNRf0ZSO3FdUzWSgB-__4FJN5zBA3FWjuz9jrCyChg2F8lUUBBc-T8EoC21m6aXDbTKWW8rRd-pD2wNwCV51tuvHqLwBFEIWJ8c2cEos88Kp78SAD389ubSmf_vxpVFO8bBpBxN19mv8-zRIB6E7pmqVspkxtKJ-Kmy6i9B8-B0oMLtjh5JPi6Zq_TEI_KcxYK3PlpfhMuRJysxnBUiSUJRiCwmdFv3Js5ujh4qJY1Z_IQqCdIW-sREMiru-91KWAVv3gOl4ZEQU-a8baBA5UkG_NuO7iyn4qocoAlNcQ
JWS to HTTP Header: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9..KIB30XnrZai9qGAVMoLwlMeX6nMXUsVbxt_K9jgQgaLtPKNRf0ZSO3FdUzWSgB-__4FJN5zBA3FWjuz9jrCyChg2F8lUUBBc-T8EoC21m6aXDbTKWW8rRd-pD2wNwCV51tuvHqLwBFEIWJ8c2cEos88Kp78SAD389ubSmf_vxpVFO8bBpBxN19mv8-zRIB6E7pmqVspkxtKJ-Kmy6i9B8-B0oMLtjh5JPi6Zq_TEI_KcxYK3PlpfhMuRJysxnBUiSUJRiCwmdFv3Js5ujh4qJY1Z_IQqCdIW-sREMiru-91KWAVv3gOl4ZEQU-a8baBA5UkG_NuO7iyn4qocoAlNcQ
======================================== JWT,JWS and HTTP Header ========================================`


Grazie

Riccardo

**Comment by amusarra** [comment]
Faremo un test tramite il client Java fornito come esempio utilizzando il vostro stesso certificato e vedremo di sentire i colleghi che si occupano dell'infrastruttura di sicurezza per cercare di capire a cosa sia dovuto l'errore specifico.

**Comment by amusarra** [comment]
Salve @manny73 siamo riusciti a replicare il caso è stiamo in fase di analisi per capire il motivo per cui quel particolare CN non è accettato dal sistema di sicurezza dei servizi cooperativi.

Cordiali Saluti.
Supporto ANSC.

**Comment by manny73** [comment]
Ok,
rimango in attesa.

Grazie
Riccardo

**Comment by amusarra** [comment]
Buongiorno @manny73 
Le abbiamo inviato il certificato di postazione con il CN valido per i servizi cooperativi di ANSC.

Chiudiamo questa issue e nel caso di ulteriori problemi non esiti a riaprire la stessa.

Cordiali Saluti.
Supporto ANSC.
