### ISSUE TITLE
usecase 11111000	(Dichiarazione entro i 10 giorni - resa dal padre) : allegati

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#197]
Buongiorno,
prendo ad esempio il caso nell'oggetto.
Nel mapping DIC_NASC_001 tutti gli allegati sono indicati come NON obbligatori.
Ma non è vero, in base al campo "tipoaccertamento" uno degli allegati diventa obbligatorio.

Perché nella documentazione non si possa avere una colonna dove venga scritto "l'allegato diventa obbligatorio se il campo xy ha il valore xx". Questo vale anche per i tag del json.

Lo ripetiamo da tempo che la documentazione è poverissima di dettagli importanti. Adesso dobbiamo ripartire da zero per rendere obbligatorio o meno un allegato.
Vorrei avere un elenco di tutti quegli allegati, suddivisi per i mapping rilasciati (con urgenza quelli previsti per entrare in sperimentazione), che possono diventare obbligatori in base a quale tag e valore.

**Comment by asqueglia** [comment]
Buongiorno, 
si richiede di fare riferimento all'issue #130

**Comment by amusarra** [comment]
Chiudiamo la issue; nel caso fosse necessario procedete pure con la riapertura.

Cordiali Saluti.
Supporto ANSC.
