### ISSUE TITLE
atto di cittadinanza - notifiche verso anagrafe

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#198]
Con questi dati (in allegato)
![Cattura](https://github.com/italia/ansc/assets/127182190/b73a8bdb-ce4b-4feb-b531-9db0c0772e0b)
 è impossibile sapere se si tratta di un acquisto o perdita per creare un certo automatismo che aiuti l'utente.
Impensabile che l'utente vada a leggersi la descrizione dell'uso e vada a fare le opportune modifiche.

**Comment by annamaraspin** [comment]
grazie del suggerimento, Ne parlerò con i colleghi che si occupano della parte anagrafica.
Guardavo le varie descrizioni degli usi: se un Comune forma un atto con l'uso citt_999 resterebbe il problema. Se mi ricordo bene è un caso che verrà eliminato appena il progetto sarà pronto al 100% però potrebbe succedere che arrivi una notifica prima della fine progetto.

**Comment by asqueglia** [comment]
Buongiorno, si per i casi d'uso di servizio la notifica conterrà necessariamente tutta la minuta dell'atto, in quanto i metadati sono opzionali per definizione di caso d'uso di servizio quindi non è possibile automaticamente capire nel dettaglio che tipo di operazione anagrafica ne consegue.

**Comment by annamaraspin** [comment]
Quindi ritorniamo al punto di partenza... l'utente deve leggersi il testo.
Chiediamo che venga indicato un tag nell'xml che contenga l'informazione.

**Comment by gbuemi** [comment]
Buongiorno, per i casi d'uso di servizio è in corso un intervento che prevede l'inoltro di ulteriori informazioni. Essendo un caso d'uso libero, con strutture opzionali, dipenderà dalle informazioni inserite durante la registrazione dell'atto.
