### ISSUE TITLE
Descrizione casi d'uso - Riconoscimento

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#2]
Come da accordi con la Dott.ssa Rosati e il Dott. Coraci di Team Digitale riporto tutti i ticket aperti in Teams a cui è stata ricevuta solo la risposta "verificheremo" (o similari) e mai se è stata risolta o meno .

![Cattura_1](https://user-images.githubusercontent.com/127182190/223345386-309be145-f5c3-4471-af49-d447d6740863.PNG)

**Comment by mttfranci** [comment]
Buongiorno.

Con l'ultimo rilascio sono state corrette alcune descrizioni, tra qui quella che avevate segnalato : 

https://github.com/italia/ansc/blob/v1.5.0/docs/Mapping_casi_uso/3_dec_use_case.csv

![image](https://user-images.githubusercontent.com/29305782/223353215-eb05a53f-949e-461f-96de-7fe8d9347998.png)
