### ISSUE TITLE
[R005] Consultazione evento - Ricerca annotazioni

### ISSUE THREAD

**Issue by ManuelDeMeo** [italia/ansc#20]
Buongiorno,
su ambiente di preproduzione, abbiamo creato da webapp annotazione di rettifica con Id 949888 apposta sull'atto con Id 949886 con soggetto RANDAZZO MATTEA.

Dopo di che, tramite servizio cooperativo R005 /consultazione/ansc/evento/1 abbiamo consultato l'atto di nascita 949886 con la seguente richiesta:

`{"criteriRicercaEvento":{"idAnsc":"2023-949886-20-058046","idComunale":"","idTipoEvento":"","idTipoContenuto":"","dataDa":"","dataA":""},"testataRichiesta":{"idComune":4559,"idOperazioneComune":"2","dataOraRichiesta":"2023-03-13","nomeApplicativo":"testSC","versioneApplicativo":"1.0.0","fornitoreApplicativo":"Test"},"datiPaginazione":null}`

La risposta ottenuta è quella con idOperazione 1563217. All'interno della risposta non abbiamo trovato alcun riferimento all'annotazione.

Come facciamo a capire che è stata generata un'annotazione sull'atto consultato?
Ci aspettavamo la presenza di una lista di Id delle annotazioni associate all'atto. Stiamo sbagliando qualcosa?

Grazie

**Comment by amusarra** [comment]
Buongiorno @ManuelDeMeo abbiamo preso in carico la segnalazione.

**Comment by amusarra** [comment]
Buongiorno @ManuelDeMeo, su questo tema è stata aperta una segnalazione interna, per cui, dopo la risoluzione dovrebbe essere possibile ottenere quanto richiesto.

**Comment by amusarra** [comment]
Buongiorno @ManuelDeMeo 
Con il rilascio odierno il problema è stato risolto. Interrogando il servizio specificando il tipo evento e il tipo contenuto, si otterrà l'informazione richiesta.

```
    "criteriRicercaEvento": {
        "idAnsc": "2023-949886-20-058046",
        "idTipoEvento": "1",
        "idTipoContenuto": "2"
    }
```
Payload di richiesta

```
    "modelEventoDTO": [
        {
            "id": 949888,
            "idAnsc": "2023-949888--058046",
            "idTipoEvento": "1",
            "idtipocontenuto": "2",
            "idUsecase": "14100000",
            "descrizioneCasoUso": "Annotazione per rettifica",
            "stato": "FIRMATO DA USC",
            "dataformazione": "2023-03-13",
            "ora": "14",
            "minuto": "47",
            "annoAtto": "2023",
            "numeroatto": "",
            "idComuneRegistrazione": "4559",
            "nomeComuneRegistrazione": "GROTTAFERRATA",
            "idProvinciaRegistrazione": "58",
            "siglaProvinciaRegistrazione": "RM",
            "operatore": "LBRNTN77L24F537A",
            "ruoloOperatore": "2",
            "operatoreNome": "ANTONIO",
            "operatoreCognome": "LUBERTO",
            "redattoNellaCasaComunale": true,
            "enteDichiarante": {
                "idComuneEnte": "4559",
                "nomeComuneEnte": "GROTTAFERRATA",
                "idProvinciaEnte": "58",
                "siglaProvinciaEnte": "RM",
                "indirizzoEnte": "Via Test 2",
                "estremiDocumento": "Test"
            },
            "datiRettifica": {
                "eventoCollegato": {
                    "idAnsc": "2023-949886-20-058046",
                    "idComuneRegistrazione": "4559",
                    "nomeComuneRegistrazione": "GROTTAFERRATA",
                    "idProvinciaRegistrazione": "58",
                    "siglaProvinciaRegistrazione": "RM",
                    "idtipocontenuto": "1",
                    "dataformazione": "2023-03-13",
                    "numeroatto": "20",
                    "annoAtto": "2023",
                    "tipologia": "1",
                    "serie": "",
                    "parte": ""
                },
                "dettaglioRettifica": "Test annotazione",
                "idTipoRettifica": "1"
            },
            "composizioneCompleta": "Con provvedimento del Tribunale di GROTTAFERRATA (RM) Numero Test in data 13/03/2023 l'atto di cui sopra è stato così rettificato: Test annotazione",
            "datains": "2023-03-13T14:47:02.622972",
            "dataultimoagg": "2023-03-13T14:54:05.564442"
        }
    ]
```
Payload di risposta.

Chiudo questa segnalazione.

Saluti.
