### ISSUE TITLE
atto di matrimonio/divorzio - notifiche verso anagrafe

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#200]
Nel caso di un divorzio l'unica informazione che arriva è l'atto di divorzio, tutto il resto (data, luogo evento, comune, tribunale, etc...) non c'è nulla.
Per un matrimonio, se tutte e due le persone sono residenti nello stesso comune, arrivano due notifiche identiche.

**Comment by gbuemi** [comment]
Buonasera, vi chiederei gentilmente di separare le due segnalazioni e condividere i rispettivi id evento.

Cordiali Saluti,
Supporto ANSC.

**Comment by annamaraspin** [comment]
craeti 2 nuovi ticket come richiesto
