### ISSUE TITLE
atto di matrimonio - notifica anagrafica

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#202]
Per un matrimonio, se tutte e due le persone sono residenti nello stesso comune, arrivano due notifiche identiche.
id ansc  2023-953244-13-050028

**Comment by gbuemi** [comment]
Buongiorno,
la questione è da approfondire, ci saranno a seguire aggiornamenti in merito.

Cordiali saluti,
Supporto ANSC.

**Comment by asqueglia** [comment]
Buongiorno, il sistema prevede che vengano inviate due notifiche per i due soggetti intestatari; due saranno le corrispondenti notifiche anagrafiche  in quanto dovranno essere aggiornate le schede di entrambi i soggetti. Chiudiamo pertanto pertanto la issue. In caso di ulteriori dubbi o segnalzioni preghiamo di aprire una issue dedicata.
