### ISSUE TITLE
[ModelEvento] format date in ModelAttoCollegato -> dataAtto

### ISSUE THREAD

**Issue by siscomanpr** [italia/ansc#205]
Buongiorno,
Abbiamo aperto una nuova issue poiché non era possibile riaprire la issue originale da parte nostra

con riferimento alla issue #142 abbiamo verificato ed è stata aggiunta la format sui campi data, tranne che per il campo dataAtto di ModelAttoCollegato.

È possibile aggiungerla anche per quel campo?

**Comment by amusarra** [comment]
Buongiorno @siscomanpr 
Abbiamo preso il carico la segnalazione.

Cordiali Saluti.
Supporto ANSC.

**Comment by amusarra** [comment]
Chiudiamo la issue per via del rilascio della versione 1.10.0 che risolve questa segnalazione.

Cordiali Saluti.
Supporto ANSC.
