### ISSUE TITLE
Errore nel file docs/Mapping_casi_uso/3_dec_use_case.csv

### ISSUE THREAD

**Issue by siscomanpr** [italia/ansc#206]
Si segnala che nel file in oggetto, il caso d'uso 11127200 riporta parte I serie A invece che serie B (essendo una dichiarazione tardiva).

**Comment by amusarra** [comment]
Buongiorno @siscomanpr 
Abbiamo preso in carico la segnalazione.

Cordiali Saluti.
Supporto ANSC.

**Comment by amusarra** [comment]
Chiudiamo la issue per via del rilascio della versione 1.10.0 che risolve questa segnalazione.

Cordiali Saluti.
Supporto ANSC.
