### ISSUE TITLE
[R010] - Rico_013 e Rico_016 - Dati in Ingresso non corretti

### ISSUE THREAD

**Issue by DiBellaDavide** [italia/ansc#207]
Salve,
all'invocazione del servizio di anteprima, per i casi d'uso specificati mi viene ritornato l'errore di "Dati in Ingresso non corretti". 
Per entrambi i test effettuati i rispettivi atti vengono prima inviati ad ANSC correttamente sfruttando il servizio di validazione.
Richiedo delucidazioni sulle cause dell'errore, fornendo i dati del test:
Ambiente pre-prod
Data test: 22/06/2023
idOperazione: 1603960 (Rico_013)
idOperazione: 1603970 (Rico_016)

**Comment by amusarra** [comment]
Salve @DiBellaDavide 
Abbiamo preso in carico la segnalazione.

Cordiali Saluti.
Supporto ANSC.

**Comment by amusarra** [comment]
@DiBellaDavide la issue dovrebbe essere risolta con il prossimo rilascio che avverrà a breve.

Cordiali Saluti.
Supporto ANSC.

**Comment by asqueglia** [comment]
Buonasera con la versione 1.11.0 è stata corretta la segnalazione. 
La issue viene chiusa nel caso si prega di riaprirla.
