### ISSUE TITLE
errore servizio di certificazione

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#208]
Con l'ultima versione (1.9.1) il servizio di certificazione mi ritorna il seguente errore:

REQUEST:
{
    "idAnsc": "2023-954545-10-108028",
    "richiedente": {
        "codiceFiscale": "GROMTN86D46G999I",
        "cognome": "GORI",
        "nome": "MARTINA",
        "sesso": "F",
        "idComuneNascita": "7631",
        "nomeComuneNascita": "PRATO",
        "idProvinciaNascita": "48",
        "siglaProvinciaNascita": "FI",
        "idStatoNascita": "90",
        "nomeStatoNascita": "ITALIA",
        "idComuneResidenza": "7630",
        "nomeComuneResidenza": "PRATO",
        "idProvinciaResidenza": "100",
        "siglaProvinciaResidenza": "PO",
        "idStatoResidenza": "90",
        "nomeStatoResidenza": "ITALIA",
        "indirizzoResidenza": "",
        "idNazionalita": "90",
        "nazionalita": "ITALIANA"
    },
    "intestatario": {
        "id": "1985487"
    },
    "idEvento": "954545",
    "idTipoCertificato": "3",
    "testataRichiesta": {
        "idComune": 5000,
        "idOperazioneComune": "10",
        "dataOraRichiesta": "2023-06-23T12:25:13.138+02:00",
        "nomeApplicativo": "urbi",
        "versioneApplicativo": "0.1.0",
        "fornitoreApplicativo": "padigitale"
    }
}

RESPONSE:
{
    "testataRisposta": {
        "idComune": 5000,
        "idOperazioneComune": "10",
        "idOperazione": "1604217"
    },
    "errors": [{
            "code": "400001",
            "severity": "E",
            "text": "Soggetto richiedente non specificato correttamente"
        }
    ]
}

**Comment by biadanpad** [comment]
con la versione precedente (1.9.0) non avevo problemi

**Comment by amusarra** [comment]
Salve @biadanpad 
Nel payload sembra che non sia presente la data di nascita del richiedente.

Nel caso dovesse risolvere, le chiediamo di chiudere la issue. 

Cordiali Saluti.
Supporto ANSC.

**Comment by biadanpad** [comment]
risolto, 
grazie
