### ISSUE TITLE
Atto di cittadinanza: anomalie caso d'uso Citt_013

### ISSUE THREAD

**Issue by antonioluberto** [italia/ansc#209]
Il caso d'uso Citt_013 si riferisce alla _dichiarazione_ mediante la quale il cittadino straniero maggiorenne:

a) che sia stata riconosciuto da padre/madre cittadino/a italiano/a 
ovvero
b) per il quale sia stata dichiarata giudizialmente paternità/maternità di cittadino/a italiano/a
ovvero
b) per il quale non sia stato possibile dichiarare giudizialmente paternità/maternità di cittadino/a italiano/a, ma per il quale l'autorità giudiziaria riconosca, con proprio provvedimento, il diritto del figlio al mantenimento o agli alimenti
 
elegga, appunto, a propria la cittadinanza del genitore.

Laddove questa nostra interpretazione non sia corretta, vi chiediamo gentilmente chiarimenti su quale debba essere l'esatto perimetro funzionale del caso d'uso in oggetto.

Laddove, diversamente, la nostra interpretazione sia corretta, segnaliamo le anomalie di seguito riportate:
1) il campo obbligatorio:
![image](https://github.com/italia/ansc/assets/26415430/ec7ed076-84c2-4202-857a-e15c73079420)
risulta attualmente sempre obbligatorio, ma nel caso a) non esiste alcuna sentenza che possa esservi riportata

2) nel caso di dichiarazione a seguito di riconoscimento da parte del padre, il servizio richiede obbligatoriamente anche i dati della madre; ma se il riconoscimento in ragione del quale il titolare dell'atto elegge a propria la cittadinanza italiana è avvenuto solo ad opera del padre, i dati della madre non ci sono.
Si veda "idOperazione": "1603839"

3) nel caso di dichiarazione a seguito di riconoscimento da parte della madre, il servizio richiede obbligatoriamente anche i dati del padre; ma se il riconoscimento in ragione del quale il titolare dell'atto elegge a propria la cittadinanza italiana è avvenuto solo ad opera della madre, i dati del padre non ci sono.
Si veda "idOperazione": "1603874"

4) nel caso di dichiarazione a seguito di filiazione dichiarata giudizialmente per il padre, il servizio richiede obbligatoriamente anche i dati della madre; ma se la dichiarazione di filiazione in ragione della quale il titolare dell'atto elegge a propria la cittadinanza italiana è relativa al solo padre, i dati della madre non ci sono.
E non solo: il servizio richiede obbligatoriamente anche i dati
dell'atto di riconoscimento paterno (che chiaramente non ci sono)
dell'atto di riconoscimento materno (che chiaramente non ci sono)
Si veda "idOperazione": "1603875"

5) nel caso di dichiarazione a seguito di filiazione dichiarata giudizialmente per la madre, il servizio richiede obbligatoriamente anche i dati del padre; ma se la dichiarazione di filiazione in ragione della quale il titolare dell'atto elegge a propria la cittadinanza italiana è relativa alla sola madre, i dati del padre non ci sono.
E non solo: il servizio richiede obbligatoriamente anche i dati
dell'atto di riconoscimento paterno (che chiaramente non ci sono)
dell'atto di riconoscimento materno (che chiaramente non ci sono)
Si veda "idOperazione": "1603876".

Rimaniamo in attesa di vostre indicazioni.
Saluti

**Comment by asqueglia** [comment]
Buongiorno verifichiamo e le facciamo sapere

**Comment by asqueglia** [comment]
Buongiorno, confermiamo che con il prossimo rilascio previsto per luglio l'anomalia sarà corretta.

**Comment by FTravagliniADS** [comment]
Salve, 

mi aggiungo a questo thread in quanto e anomalie esposte nel messaggio di apertura risultano anche a noi: idOperazione - 1613791. Nel caso specifico non si ripropone il problema al punto 3, richiesta di entrambe le anagrafiche e non solo quella del soggetto che attua il riconoscimento, in quanto abbiamo valorizzato entrambi i soggetti padre e madre nonostante la prova sia su un riconoscimento materno.

Grazie

**Comment by amusarra** [comment]
Salve @antonioluberto
La issue dovrebbe essere stata chiusa con il rilascio di luglio. La invitiamo a fare un nuovo test sulla nuova release.

Cordiali Saluti.
Supporto ANSC.
