### ISSUE TITLE
[R005] - Lista soggetti sempre vuota su consultazione intestatario

### ISSUE THREAD

**Issue by ManuelDeMeo** [italia/ansc#21]
Buongiorno,
su ambiente di preproduzione, consultato il servizio R005 /consultazione/ansc/intestatario/1 con la seguente richiesta:

`{"criteriRicercaSoggetto":{"idAnpr":null,"idAnscSoggetto":"1854939","codiceFiscale":"RNDMTT23C48E204X","cognome":"RANDAZZO","nome":"MATTEA","sesso":"F","idComuneNascita":"4559","nomeComuneNascita":"GROTTAFERRATA","siglaProvinciaNascita":"RM","codiceStatoNascita":"100","nomeStatoNascita":"ITALIA","datanascita":"2023-03-08"},"testataRichiesta":{"idComune":4559,"idOperazioneComune":"2","dataOraRichiesta":"2023-03-13","nomeApplicativo":"testSC","versioneApplicativo":"1.0.0","fornitoreApplicativo":"Test"},"datiPaginazione":null}`

La risposta ottenuta è quella con Id operazione 1563243, ovvero la seguente:

`{"testataRisposta":{"idComune":4559,"idOperazioneComune":"2","idOperazione":"1563243","idEsito":0},"datiPaginazione":null,"errors":null,"success":null,"infos":null,"warnings":null,"soggetti":[]}`

Come si vede, la lista dei soggetti è vuota nonostante l'individuo sia intestatario di atti all'interno di ANSC.
Questo stesso esempio è stato ripetuto per altri individui, con lo stesso esito.

Grazie

**Comment by amusarra** [comment]
Buongiorno @ManuelDeMeo  abbiamo preso in carico la segnalazione.

**Comment by amusarra** [comment]
Buongiorno @ManuelDeMeo abbiamo in gestione questa segnalazione per cui è stato aperto un bug e corretto. Con la prossima release dovrebbe essere disponibile la fix.

**Comment by asqueglia** [comment]
Buonasera, è stata rilasciata la versione 1.5.2 che risolve la segnalazione. Si prega di riprovare.

**Comment by ManuelDeMeo** [comment]
Buonasera, scrivo qui ma se sbaglio (visto che la issue è closed) in caso ne apro un'altra.

A seguito di aggiornamento, è cambiata la risposta ma riceviamo un errore. Sempre ambiente di preproduzione, stesso servizio.

La seguente richiesta:

**Comment by ManuelDeMeo** [comment]
Buonasera, scrivo qui ma se sbaglio (visto che la issue è closed) in caso ne apro un'altra.

A seguito di aggiornamento, è cambiata la risposta ma riceviamo un errore. Sempre ambiente di preproduzione, stesso servizio.

La seguente richiesta:

`{"criteriRicercaSoggetto":{"idAnpr":null,"idAnscSoggetto":"1854939","codiceFiscale":null,"cognome":"RANDAZZO","nome":"MATTEA","sesso":"F","idComuneNascita":"4559","nomeComuneNascita":"GROTTAFERRATA","siglaProvinciaNascita":"RM","codiceStatoNascita":"100","nomeStatoNascita":"ITALIA","datanascita":"2023-03-08"},"testataRichiesta":{"idComune":4559,"idOperazioneComune":"2","dataOraRichiesta":"2023-03-20","nomeApplicativo":"testSC","versioneApplicativo":"1.0.0","fornitoreApplicativo":"Test"},"datiPaginazione":{"numPagina":1,"numRecordPagina":10,"numRecordTotali":null}}`

Produce la seguente risposta:
`{"testataRisposta":{"idComune":4559,"idOperazioneComune":"2","idOperazione":"1571447"},"datiPaginazione":null,"errors":[{"code":"500","severity":"E","text":"Errore interno"}],"success":null,"infos":null,"warnings":null}`

Ancora, la seguente richiesta(uguale alla prima ma con il codice fiscale popolato)

`{"criteriRicercaSoggetto":{"idAnpr":null,"idAnscSoggetto":"1854939","codiceFiscale":"RNDMTT23C48E204X","cognome":"RANDAZZO","nome":"MATTEA","sesso":"F","idComuneNascita":"4559","nomeComuneNascita":"GROTTAFERRATA","siglaProvinciaNascita":"RM","codiceStatoNascita":"100","nomeStatoNascita":"ITALIA","datanascita":"2023-03-08"},"testataRichiesta":{"idComune":4559,"idOperazioneComune":"2","dataOraRichiesta":"2023-03-20","nomeApplicativo":"testSC","versioneApplicativo":"1.0.0","fornitoreApplicativo":"Test"},"datiPaginazione":{"numPagina":1,"numRecordPagina":10,"numRecordTotali":null}}`

Produce la seguente risposta

`{"testataRisposta":{"idComune":4559,"idOperazioneComune":"2","idOperazione":"1571510"},"datiPaginazione":null,"errors":[{"code":"500","severity":"E","text":"Errore interno"}],"success":null,"infos":null,"warnings":null}`

Stiamo sbagliando qualcosa? 

Grazie
