### ISSUE TITLE
errore invio email per firma elettronica (caso di morte)

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#210]
Provando ad inviare la mail per la firma elettronica ricevo il seguente errore:

REQUEST:
{
    "emailDichiarante": "daniele.bianchini@padigitale.it",
    "idEvento": "954580",
    "idAnsc": "2023-954580-15-108028",
    "firmatario": {
        "cognome": "CAMPAGNI",
        "nome": "ALESSANDRO"
    },
    "testataRichiesta": {
        "idComune": 5000,
        "idOperazioneComune": "27",
        "dataOraRichiesta": "2023-06-23T16:38:41.685+02:00",
        "nomeApplicativo": "urbi",
        "versioneApplicativo": "0.1.0",
        "fornitoreApplicativo": "padigitale"
    }
}

RESPONSE:
{
    "errors": [{
            "code": "404001",
            "severity": "E",
            "text": "Dati non presenti"
        }
    ],
    "esito": {
        "codice": "404001",
        "descrizione": "Dati non presenti"
    },
    "testataRisposta": {
        "idComune": 5000,
        "idEsito": 1,
        "idOperazioneComune": "27"
    }
}

lo stesso payload, per un caso di nascita, non genera alcun errore:

REQUEST:
{
    "emailDichiarante": "daniele.bianchini@padigitale.it",
    "idEvento": "954582",
    "idAnsc": "2023-954582-14-108028",
    "firmatario": {
        "cognome": "ROBA",
        "nome": "BABBO"
    },
    "testataRichiesta": {
        "idComune": 5000,
        "idOperazioneComune": "16",
        "dataOraRichiesta": "2023-06-23T16:46:04.232+02:00",
        "nomeApplicativo": "urbi",
        "versioneApplicativo": "0.1.0",
        "fornitoreApplicativo": "padigitale"
    }
}

RESPONSE:
{
    "esito": {
        "codice": "200",
        "descrizione": "Ok"
    },
    "testataRisposta": {
        "idComune": 5000,
        "idEsito": 0,
        "idOperazioneComune": "16"
    },
    "idPresaVisione": "1985594"
}

**Comment by amusarra** [comment]
Salve @biadanpad 
Abbiamo preso in carico la risoluzione della segnalazione.

Cordiali Saluti.
Supporto ANSC.

**Comment by amusarra** [comment]
Salve @biadanpad 
Per il caso d'uso 2199 il firmatario è opzionale, infatti è stato impostato il `flagFirmatario` al valore `false` e in questo caso è solo necessaria la firma USC per chiudere l'evento.

Cordiali Saluti.
Supporto ANSC.

**Comment by amusarra** [comment]
Buongiorno @biadanpad 
Chiudiamo la segnalazione, in caso di dubbi o ulteriori chiarimenti, riapra pure.

Cordiali Saluti.
Supporto ANSC.
