### ISSUE TITLE
ANPR e ANSC - disallineamento dati atto

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#211]
Buongiorno,
in ANPR per registrare i nuovi atti digitali è stato anche previsto il campo UFFICIO
![Cattura](https://github.com/italia/ansc/assets/127182190/4ee54ed1-3987-456d-94b2-483f43109933)
mentre nel json di ANSC e nell'xml di notifica annotazione questo dato non esiste
![Cattura1](https://github.com/italia/ansc/assets/127182190/64d6408f-2a8b-4d40-9dd7-fb8ca4cf95ce)

**Comment by gbuemi** [comment]
Buongiorno, il campo ufficioMunicipio non è un dato che tratta ANSC e sui servizi ANPR il campo è opzionale.

Cordiali Saluti,
Supporto ANSC.
