### ISSUE TITLE
Numerazione nazionale e comunale degli atti

### ISSUE THREAD

**Issue by corradosacco** [italia/ansc#212]
Buongiorno, le numerazioni nazionali e comunali degli atti (secondo e terzo elemento dell'id_ansc) ricominciano da 1 ogni nuovo anno? Me lo faceva credere il fatto che nell'idAnsc ci fosse l'anno come primo elemento.

Cordiali saluti

**Comment by amusarra** [comment]
Buongiorno @corradosacco 
Può fare riferimento alla [Guida Operativa](https://github.com/italia/ansc/blob/main/docs/Guida_operativa_ANSC.pdf) disponibile su GitHub e in particolare al capitolo 5.6 Validazione e Conferma.

Chiudiamo la issue. Nel caso fosse necessario non esitate a riaprirla.

Cordiali Saluti.
Supporto ANSC.
