### ISSUE TITLE
(ws R009) Validazione - Nascita: msg. "La sezione null non dovrebbe essere valorizzata per il caso uso"

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/ansc#214]
ambiente PRE-PROD - comune di FAENZA (idComune 3743)

idOperazioneAnsc: 1605572
idUseCase 11111000 (Dichiarazione entro i 10 giorni - resa dal padre)

non capiamo come mai oggi la validazione risponda con questo messaggio di errore:
La sezione null non dovrebbe essere valorizzata per il caso uso "11111000"

"sembra" che il sistema non accetti più le sezioni non strettamente richieste dal caso d'uso specifico, anche se passate con valori nulli.
(ad esempio, in questo caso d'uso specifico, la sezione "trascrizioneNascita")

fino a due giorni fa, a parità di struttura del json, la comunicazione veniva validata.
è cambiato qualcosa?

l'altro aspetto che segnalo è che il messaggio di errore segnala "null" al posto del nome della sezione che manda in errore il processo.

sarebbe utile un riscontro sollecito.
grazie
Alessandro Monopoli ADS

**Comment by amusarra** [comment]
Salve @AMonopoliADS
Abbiamo preso in carico la segnalazione.

Cordiali Saluti.
Supporto ANSC.

**Comment by amusarra** [comment]
Chiudiamo la issue per via del rilascio della versione 1.10.0 che risolve questa segnalazione.

Cordiali Saluti.
Supporto ANSC.
