### ISSUE TITLE
[web-service] Unioni Civili - Anomalia nella gestione dello Stato dell'atto

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/ansc#216]
ambiente PRE-PROD - comune di FAENZA (id 3743)

è già la seconda volta che ci capita la situazione che vi descrivo di seguito:
- validazione di unione civile (ws R009): idAttoAnsc 2023-954937-194-039010
- firma Dichiaranti (ws R006): esito OK (rif. idOperazioneAnsc 1606442)
- firma USC (ws R007): esito OK (rif. idOperazioneAnsc 1606443)
- consultazione per evento (ws R005): l'atto risulta FIRMATO USC (rif. idOperazioneAnsc 1606444)
- richiesta certificato (ws R002): andata a buon fine (rif. idOperazioneAnsc 1606445)
- richiesta certificato (ws R002): errore "Impossibile richiedere un certificato per un'evento che non è in stato Firmato da USC" (rif. idOperazioneAnsc 1606446)
- consultazione per evento (ws R005): l'atto risulta FIRMATO DAL DICHIARANTE (rif. idOperazioneAnsc 1606448)

come è possibile che lo stato dell'atto sia passato (apparentemente da solo) dallo stato di FIRMATO USC allo stato di FIRMATO DAL DICHIARANTE?

se potete verificare...

grazie
Alessandro Monopoli ADS

**Comment by amusarra** [comment]
Buongiorno @AMonopoliADS 
Abbiamo preso in carico la sua segnalazione.

Cordiali Saluti.
Supporto ANSC.

**Comment by AMonopoliADS** [comment]
segnalo stesso problema anche su atto di matrimonio con idAttoAnsc 2023-954737-182-039010

**Comment by asqueglia** [comment]
Buonasera con la versione 1.11.0 è stata corretta la segnalazione. 
La issue viene chiusa nel caso si prega di riaprirla.
