### ISSUE TITLE
Indicazioni su caso d'uso Citt_09

### ISSUE THREAD

**Issue by antonioluberto** [italia/ansc#217]
Con riferimento al caso d'uso in oggetto, la modellazione richiede la valorizzazione del campo:

![image](https://github.com/italia/ansc/assets/26415430/9b2af36a-6c52-4168-8ec6-f2cb35ce4ce9)

Non ci è chiaro che tipo d'informazione sia attesa; potreste fornirci indicazioni di dettaglio in merito?

Grazie

**Comment by amusarra** [comment]
Salve @antonioluberto 
Stiamo facendo delle verifiche in merito.

Cordiali Saluti.
Supporto ANSC.

**Comment by amusarra** [comment]
Salve @antonioluberto 
Su quell'attributo andrebbe inserito un testo descrittivo liberamente inserito dall'USC che in qualche modo attesti la residenza biennale del soggetto.

Se non ci sono altri dubbi chiuderei la issue.

Cordiali Saluti.
Supporto ANSC.

**Comment by asqueglia** [comment]
Buongiorno, con il rilascio della versione 1.12.0 la segnalazione è stata corretta; pertanto la issue viene chiusa. In caso vengano riscontrati ulteriori problemi si prega di riaprire l'issue
