### ISSUE TITLE
Gestione impedimenti per atto di unione civile

### ISSUE THREAD

**Issue by antonioluberto** [italia/ansc#219]
La modellazione relativa agli atti di unione civile, si veda ad esempio UnCiv_001, prevede la gestione di due possibili tipi di impedimenti:
a) difetto di età, e collegata a questo impedimento la gestione degli eventuali assistenti legali che intervengano nella scelta del regime patrimoniale
b) parentela.

L'impedimento di cui al punto a) ci pare in effetti non poter sussistere; l'art. 1 comma 2 della legge 20 maggio 2016, n. 76 recita infatti:
_Due  persone  **maggiorenni**  dello  stesso  sesso   costituiscono un'unione civile mediante dichiarazione di  fronte  all'ufficiale  di stato civile ed alla presenza di due testimoni_.

Altro dubbio riguarda l' _imputabilità_ dell'impedimento. In dettaglio:
un impedimento del tipo di cui al punto b) certamente si riferisce ad entrambi gli uniti, ma può sussistere il caso in cui una delle persone da unire civilmente, ostando impedimento, abbia individualmente ottenuto l'autorizzazione alla costituzione dell'unione civile tra persone dello stesso sesso a termini delle disposizioni del codice civile (art. 70-quinquies del D.P.R. 3 novembre 2000, n. 396). Situazioni siffatte sono gestite oggi mediante il ricorso, in stampa atto, alla formula 73 - quater.
Non si vede attualmente in modellazione alcun campo mediante il quale poter indicare per quale dei due uniti civilmente lo specifico impedimenti sussista.

**Comment by asqueglia** [comment]
Buongiorno al riguardo richiediamo sicuramente una verifica normativa. La ringraziamo per la segnalazione.

**Comment by asqueglia** [comment]
Buongiorno, confermiamo quanto da lei riportato per il punto a, mentre per il punto b è stato introdotto nel data model il campo impedimentoGenerico che fa riferimento alla tabella di decodifica 95_dec_soggetto_impedimento_civile. Chiudiamo pertanto la issue pregando di aprirne una altra in caso di ulteriori problemi
