### ISSUE TITLE
Richiesta informazioni tempistiche

### ISSUE THREAD

**Issue by SAlberto** [italia/ansc#22]
In riferimento all'issue #18:

Chiarissimo, potrei chiedere la stessa informazione sulle tempistiche per quanto riguarda la parte Elettorale su ANPR?
Grazie

**Comment by mttfranci** [comment]
Buongiorno @SAlberto  ci permettiamo di rimandarvi al repository gemello di ANPR :
https://github.com/italia/anpr/issues

In linea di massima usiamo questo canale solo per le domande sullo Stato Civile 

Saluti
