### ISSUE TITLE
[ws R009] Validazione - Separazione / Divorzio: Modifica Condizioni e Mancata Conferma

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/ansc#220]
ambiente PRE-PROD - comune di FAENZA (id 3743)

due richieste di chiarimenti:

1. (modifica condizioni di separazione o divorzio)
idOperazioneAnsc 1607097
idUseCase 344000 - Accordo di modifica delle condizioni di separazione o divorzio
coerentemente con quanto indicato in tabella 53 (tipo accordo separazione) indichiamo nel campo tipoAccordo il valore '4' (Modifica delle condizioni di separazione), ma il web-service restitiuisce questi errori:
Il campo evento.separazione.tipoAccordo nella sezione Dettaglio accordo non corrisponde al pattern ^[1]$
Il campo evento.separazione.dataConfermaAccordo nella sezione Dettaglio accordo è obbligatorio
come se per questo caso d'uso il sistema si aspettasse il valore '1' invece che il '4'.

stiamo fraintendendo il senso del campo tipoAccordo?

2. (mancata conferma accordo)
idUseCase 343000 - Conferma o mancata conferma di accordo di separazione o divorzio
cosa definisce, all'interno del json, se siamo nel caso di "conferma" o di "mancata conferma"?
forse solo la valorizzazione del campo evento.separazione.dataConfermaAccordo?

nel caso dell'idOperazioneAnsc 1607109, ad esempio, l'atto è stato validato, senza l'invio della dataConfermaAccordo e per noi - lato gestionale -  è una Mancata Conferma (idAttoAnsc 2023-1010054-200-039010).

grazie
Alessandro Monopoli ADS

**Comment by siscomanpr** [comment]
Mi accodo a questa discussione, in particolare al punto 2 per ribadire una segnalazione già fatta mesi fa: per le unioni civili sono previsti 2 casi d'uso distinti per Conferma e Mancata conferma accordo, mentre per i matrimoni è disponibile un solo caso d'uso che scaturisce il problema segnalato da @AMonopoliADS per cui non si capisce se l'atto è una conferma o una mancata conferma.
Il nostro suggerimento sarebbe di prevedere 2 casi d'uso distinti anche per gli accordi relativi ai matrimoni.

**Comment by asqueglia** [comment]
Buongiorno verifichiamo e vi facciamo sapere appena possibile.

**Comment by asqueglia** [comment]
Buonasera con la versione 1.11.0 è stata corretta la segnalazione. 
La issue viene chiusa nel caso si prega di riaprirla.
