### ISSUE TITLE
[web-service] R010 (Anteprima) vs R002 (Certificazione): download pdf con i dettagli dell'atto

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/ansc#223]
ambiente di PRE-PROD - comune di FAENZA (id 3743)

sulla base delle informazioni acquisite fino ad oggi, per ottenere la preview (pdf) dell'atto sono previste queste due possibilità:
- finché l'atto è in stato CONFERMATO / FIRMATO DAL DICHIARANTE si può ottenere il documento utilizzando il ws R010 (anteprima)
- dal momento in cui l'atto viene firmato dall'USC, il servizio di anteprima (ws R010) non consente l'operazione rispondendo con l'errore "Lo stato dell'atto non e' CONFERMATO"; è possibile ottenere il documento con il ws R002 (certificazione), richiedendo l'Estratto Integrale (idTipoCertificato '3')

in linea generale questo processo viene sempre rispettato, ma - sulla base delle prove fatte fino ad oggi - si verificano alcune eccezioni:

. idUseCase 343000 - Conferma o mancata conferma di accordo di separazione o divorzio
con atto in stato FIRMATO USC, il servizio di anteprima (R010) non è più disponibile (coerente con quanto descritto sopra)
la richiesta di Estratto Integrale restituisce l'errore "Il Tipo di certificato ESTRATTO_INTEGRALE non può essere generato per l'atto xxxxx" (rif. idAttoAnsc 2023-1010054-200-039010 - idOperazioneAnsc 1607527)

. idUseCase 12216300 - Riconoscimento di nascituro da parte della madre con presenza del padre
con atto in stato FIRMATO USC, il servizio di anteprima (R010) non è più disponibile (coerente con quanto descritto sopra)
la richiesta di Estratto Integrale (R002) restituisce l'errore "Soggetto intestatario non specificato correttamente"
in effetti, nell'ambito dei riconoscimenti pre-natali, non esiste un intestatario ed in fase di validazione non viene assegnato l'idSoggettoAnsc, per cui non saprei come risolvere la causa di errore della richiesta di certificazione (rif. idAttoAnsc 2023-954995-198-039010 - idOperazioneAnsc 1607555)

vi chiederei di verificare per capire se il problema è nei dati di input o se si tratta di bug del sistema.

grazie
Alessandro Monopoli ADS

**Comment by amusarra** [comment]
Buongiorno @AMonopoliADS 
Abbiamo preso in carico la segnalazione per le verifiche del caso.

Cordiali Saluti.
Supporto ANSC.

**Comment by FTravagliniADS** [comment]
Salve,

segnalo che lo stesso problema sulla certificazione 

" idUseCase 12216300 - Riconoscimento di nascituro da parte della madre con presenza del padre
con atto in stato FIRMATO USC, il servizio di anteprima (R010) non è più disponibile (coerente con quanto descritto sopra)
la richiesta di Estratto Integrale (R002) restituisce l'errore "Soggetto intestatario non specificato correttamente"
in effetti, nell'ambito dei riconoscimenti pre-natali, non esiste un intestatario ed in fase di validazione non viene assegnato l'idSoggettoAnsc, per cui non saprei come risolvere la causa di errore della richiesta di certificazione (rif. idAttoAnsc 2023-954995-198-039010 - idOperazioneAnsc 1607555)"

si ripropone anche per il caso d'uso 2104 - Decesso relativo a cadavere rinvenuto non identificato.

Grazie
Francesco Travaglini ADS

**Comment by asqueglia** [comment]
Buongiorno, con il rilascio della versione 1.12.0 la segnalazione è stata corretta; pertanto la issue viene chiusa. In caso vengano riscontrati ulteriori problemi si prega di riaprire l'issue
