### ISSUE TITLE
[ws R002] Certificazione - Matrimonio / Morte: estremi atto di nascita

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/ansc#224]
si chiede di verificare le seguente segnalazione:

in presenza dei dati dell'atto di nascita (degli sposi o del deceduto), nei certificati viene indicato sempre e solo il numero dell'atto nella formula "atto n. xxx del comune di xxxxxx (xx)."
questo formato sarebbe corretto se l'atto di riferimento fosse digitale.
trattandosi invece di atti NON digitali, per i quali sono stati indicati anche parte, serie e anno, ci si aspetta che vengano stampati tutti gli estremi e non solo il numero.

si può fare riferimento agli atti con i seguenti idAnsc
- matrimonio: 2023-954707-188-039010 (per questo atto in particolare, aggiungo la segnalazione che la richiesta di "Estratto Integrale" risponde con il msg. "Errore interno" (rif. idOperazioneAnsc 1607578)
- morte: 2023-954796-191-039010

grazie
Alessandro Monopoli ADS

**Comment by amusarra** [comment]
Buongiorno @AMonopoliADS 
Abbiamo preso in carico la segnalazione e le opportune verifiche.

Cordiali Saluti.
Supporto ANSC.

**Comment by asqueglia** [comment]
Buonasera con la versione 1.11.0 è stata corretta la segnalazione. 
La issue viene chiusa nel caso si prega di riaprirla.
