### ISSUE TITLE
[ws R009] Validazione - Matrimonio Civile su Delega (312111): errore su campo siglaProvinciaComuneDelegante

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/ansc#225]
ambiente PRE-PROD - comune di FAENZA (id 3743)

idUseCase 312111 - Matrimonio con Rito Civile con Delega di altro Comune nella casa comunale
idOperazioneAnsc 1607580

la richiesta di validazione (ws R009 - endpoint: https://anscservicepre.anpr.interno.it/services/service/val/validazione/evento/1) va in errore e viene restituito questo messaggio: 
"Il campo evento.datiEventoMatrimonio.siglaProvinciaComuneDelegante nella sezione Delega da altro comune non corrisponde al pattern ^[0-9]*$"

in sostanza nel tag siglaProvinciaComuneDelegante viene indicata la sigla, ma il sistema si aspetta un valore numerico.

Alessandro Monopoli ADS

**Comment by amusarra** [comment]
Buongiorno @AMonopoliADS 
Abbiamo preso in carico la segnalazione.

Cordiali Saluti.
Supporto ANSC.

**Comment by asqueglia** [comment]
Buonasera con la versione 1.11.0 è stata corretta la segnalazione. 
La issue viene chiusa nel caso si prega di riaprirla.
