### ISSUE TITLE
[ws R009] Validazione - Manifestazione volontà di scioglimento (442000): msg. "internal error"

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/ansc#226]
ambiente PRE-PROD - comune di FAENZA (id3743)

idUseCase 442000 - Manifestazione di volontà di scioglimento dell'unione civile tra persone dello stesso sesso di una sola parte
idOperazioneComune 2023001059

la richiesta di validazione restituisce un generico "internal.error"
(endpoint: https://anscservicepre.anpr.interno.it/services/service/val/validazione/evento/1)

aggiungo un'altra segnalazione:
il caso d'uso citato prevede l'obbligatorietà di upload di due allegati
- LETTERA RACCOMANDATA
- ESTRATTO DELL'ATTO DI UNIONE CIVILE

al momento della validazione (wsR009), in presenza di allegati ancora in verifica, il servizio ha risposto con due messaggi identici:
"La verifica di almeno un allegato e' ancora in corso"
(immagino che i messaggi siano in rapporto 1:1 con il numero degli allegati inviati)

condivido una riflessione:
- se il messaggio deve essere "La verifica di almeno un allegato e' ancora in corso", penso possa bastare che compaia una sola volta.
- se il messaggio ha una relazione diretta con l'allegato a cui si riferisce, forse è più trasparente segnalare a quale allegato ci si riferisce così che si possa procedere alla verifica (wsR002) di quel singolo documento

attendo riscontro per capire l'origine del messaggio d'errore "internal.error"

grazie
Alessandro Monopoli ADS

**Comment by AMonopoliADS** [comment]
stesso errore con:
idUseCase 441000 - Manifestazione congiunta di volontà di scioglimento dell'unione civile tra persone dello stesso sesso
(rif. idOperazioneComune 2023001062)

**Comment by amusarra** [comment]
Buongiorno @AMonopoliADS 
Abbiamo preso in carico la segnalazione.

Cordiali Saluti.
Supporto ANSC

**Comment by asqueglia** [comment]
Buonasera con la versione 1.11.0 è stata corretta la segnalazione. 
La issue viene chiusa nel caso si prega di riaprirla.
