### ISSUE TITLE
[ws R009] Validazione - Negoziazione Assistita (345000): Allegati Obbligatori

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/ansc#227]
ambiente PRE-PROD - comune di FAENZA (id 3743)

idUseCase 345000 - Trascrizione della convenzione di negoziazione assistita ai sensi dell’art.6 Decreto-legge n.132/2014 convertito con Legge 10.11.2014 n.162

risultano obbligatori entrambi i seguenti documenti:
- ATTO DI MATRIMONIO
- ATTO DI MATRIMONIO STRANIERO, TRADOTTO E LEGALIZZATO

ci saremmo aspettati fossero alternativi, invece il servizio di validazione se li aspetta entrambi
(rif. idOperazioneAnsc 1607834)

c'è una spiegazione oppure è solo una cosa da correggere?

grazie
Alessandro Monopoli ADS

**Comment by amusarra** [comment]
Buongiorno @AMonopoliADS 
Abbiamo preso in carico la segnalazione.

Cordiali Saluti.
Supporto ANSC.

**Comment by asqueglia** [comment]
Buongiorno, con il rilascio della versione 1.12.0 la segnalazione è stata corretta; pertanto la issue viene chiusa. In caso vengano riscontrati ulteriori problemi si prega di riaprire l'issue
