### ISSUE TITLE
445000	Mancata conferma dell'accordo di scioglimento dell'unione civile (Sciogl_UnCiv_005)

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#230]
Buongiorno,
Il Ministero degli Interni quando aveva emanato la circolare delle formule inerenti alle Unioni Civili non aveva creato la formula di questa casistica.
Infatti fino ad oggi pensavo che per le UC non servisse redigere un atto per questo caso. Inoltre nessuno dei nostri Comuni è incappato in questa problematica.
Ho provato a vedere nel vostro file ansc_piano_test.xlsx se c'era l'esempio ma nulla.
Il Ministero vi ha fornito una formula ufficiale? potete passarmela per favore?
grazie

**Comment by asqueglia** [comment]
Buongiorno, verifichiamo anche con ANUSCA e le facciamo sapere.

**Comment by asqueglia** [comment]
Buongionro @annamaraspin, abbiamo condiviso la segnalazione con ANUSCA, Riportiamo di seguito la risposta ricevuta

per la formula relativa alla mancata conferma dell'accordo di scioglimento dell'unione civile, si dovrà utilizzare la formula n. 121-sexies che riguarda il matrimonio, adattandola al caso concreto dell'unione civile.

Chiudiamo pertanto la issue; nel caso in cui ci siano ulteriori segnalazioni si prega di riaprire la issue oppure di aprirne una nuova più specifica.
