### ISSUE TITLE
usecase MATR_007 e MATR_008

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#231]
Nel mapping di queste due casistiche abbiamo trovato i dati relativi agli Impedimenti (età, parentela, etc).

Noi come software house non li abbiamo mai gestiti nei matrimoni parte 2 serie A.
Sono state richieste informazioni presso un Comune per sicurezza che ci ha confermato che non dovrebbero esistere.
Sono state controllare le formule da 57 a 59 e sembrerebbe far riferimento solo agli atti di matrimonio di parte I;
nel  frontespizio degli atti di matrimonio di parte II A, nella spiegazioni dei richiami numerici, non sono trovate indicazioni in merito, 

Una nostra mancanza o sono dati che devono essere rivisti nel json?

**Comment by amusarra** [comment]
Buongiorno @annamaraspin 
Facciamo delle verifiche e le daremo riscontro quanto prima.

Cordiali Saluti.
Supporto ANSC.
