### ISSUE TITLE
usecase MATR_004 descrizione provincia

### ISSUE THREAD

**Issue by MichelaGarzoni** [italia/ansc#232]
Analizzando lo usecase MATR_004 abbiamo notato che manca la descrizione della provincia per "Delega da altro comune" ma è presente solamente il codice:
![image](https://github.com/italia/ansc/assets/128141738/fd1750cd-7c3e-4111-8203-73372bcaa67b)
mentre nel model relativo al matrimonio troviamo anche la descrizione:
![image](https://github.com/italia/ansc/assets/128141738/89dea2fe-6486-4256-9885-76f3484d607d)

E' corretto non sia presente tale descrizione o è una svista?
Grazie

**Comment by amusarra** [comment]
Buongiorno @annamaraspin
Facciamo delle verifiche e le daremo riscontro quanto prima.

Cordiali Saluti.
Supporto ANSC.

**Comment by amusarra** [comment]
Buonasera con la versione 1.11.0 è stata corretta la segnalazione.
La issue viene chiusa nel caso si prega di riaprirla.
