### ISSUE TITLE
casi d'uso 319999 e 329999 : numero testimoni e pubblicazioni

### ISSUE THREAD

**Issue by MichelaGarzoni** [italia/ansc#235]
Buongiorno, 
in merito ai casi d'uso di servizio in oggetto (matrimonio con rito civile e matrimonio con rito religioso) abbiamo notato  due comportamenti che non riteniamo corretti:

1. viene richiesto sempre un numero di testimoni diverso da "0" . 
Se i testimoni non sono presenti, in quanto non dovrebbero essere obbligatori, segnala errore nel qual caso:
- si imposti il valore a "0"
- si ometta completamente la voce del numero dei testimoni (indica che è una voce obbligatoria)

2. vengono richieste in modo obbligatorio le informazioni relative alle pubblicazioni, mentre queste non sempre sono note e quindi non dovrebbero essere impostate come obbligatorie.

**Comment by amusarra** [comment]
Buongiorno @MichelaGarzoni 
Questa segnalazione riguarda la Web Application o i Servizi Cooperativi?

Cordiali Saluti.
Supporto ANSC.

**Comment by amusarra** [comment]
Buongiorno @MichelaGarzoni 
Questa segnalazione riguarda la Web Application o i Servizi Cooperativi?

Cordiali Saluti.
Supporto ANSC.

**Comment by MichelaGarzoni** [comment]
Buongiorno @amusarra , 
questa segnalazione riguarda i test che stiamo eseguendo sui Servizi Cooperativi, non abbiamo replicato il test lato Web App per testare se il comportamento fosse diverso

**Comment by rvinzani** [comment]
Buongiorno @MichelaGarzoni,
nei matrimoni civili sia testimoni che pubblicazioni sono dati obbligatori. Per questo abbiamo fatto specifica richiesta agli esperti ANUSCA che ci supportano per la definizione dei requisiti
