### ISSUE TITLE
WebApp non raggiungibile

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#236]
![image](https://github.com/italia/ansc/assets/131870281/1020dad5-8c2f-4b1d-9e9e-b2efc1d753e3)

**Comment by gcuci** [comment]
buongiorno,

confermiamo anche noi la non raggiungibilità della Web Application da ieri pomeriggio, e segnaliamo anche delle risposte in timeout, di alcuni dei servizi cooperativi.

In particolare, il servizio di Certificazione (R002), ed il servizio di Gestione dei file Allegati (R001), restituiscono: '504 Gateway Time-out'.  

 
In attesa di un riscontro,

cordiali saluti.

**Comment by biadanpad** [comment]
confermo pure io il timeout dei servizi R001 e R002

**Comment by amusarra** [comment]
Salve @biadanpad @gcuci facciamo le verifiche del caso e vi aggiorneremo.

Cordiali Saluti.
Supporto ANSC

**Comment by amusarra** [comment]
Il sistema è nuovamente operativo.

Cordiali Saluti.
Supporto ANSC.
