### ISSUE TITLE
[R009] collegamento evento

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#237]
Sto provando ad utilizzare il servizio R009 per collegare un'annotazione ad un evento, ma non ci riesco. In entrami i casi riportati di seguito ricevo una RESPONSE vuota con codice 404

REQUEST_1:
{
    "collegamento": {
        "idEvento": "954576",
        "dataFormazioneEvento": "2023-06-23",
        "idAnnotazione": "1110031",
    },
    "testataRichiesta": {
        "idComune": 5000,
        "idOperazioneComune": "19",
        "dataOraRichiesta": "2023-07-12T14:45:52.416+02:00",
        "nomeApplicativo": "urbi",
        "versioneApplicativo": "0.1.0",
        "fornitoreApplicativo": "padigitale"
    }
}

REQUEST_2:
{
    "collegamento": {
        "idEvento": "954576",
        "dataFormazioneEvento": "2023-06-23",
        "idAnnotazione": "1110031",
        "idSoggetto": "1985575"
    },
    "testataRichiesta": {
        "idComune": 5000,
        "idOperazioneComune": "19",
        "dataOraRichiesta": "2023-07-12T14:45:52.416+02:00",
        "nomeApplicativo": "urbi",
        "versioneApplicativo": "0.1.0",
        "fornitoreApplicativo": "padigitale"
    }
}

**Comment by biadanpad** [comment]
come dovrebbe essere riempito il campo "idSoggetto"? E' obbligatorio? Io ho provato a metterci uno degli intestatari dell'atto

**Comment by biadanpad** [comment]
Sono riuscito a far funzionare il servizio R009 per il collegamento dell'atto all'evento.

Rimango in attesa di una risposta relativa all'altro quesito:
"come dovrebbe essere riempito il campo "idSoggetto"? E' obbligatorio? Io ho provato a metterci uno degli intestatari dell'atto"

**Comment by amusarra** [comment]
> Sono riuscito a far funzionare il servizio R009 per il collegamento dell'atto all'evento.
> 
> Rimango in attesa di una risposta relativa all'altro quesito: "come dovrebbe essere riempito il campo "idSoggetto"? E' obbligatorio? Io ho provato a metterci uno degli intestatari dell'atto"

@biadanpad e l’identificativo del soggetto intestatario

Cordiali Saluti. 
Supporto ANSC.

**Comment by amusarra** [comment]
@biadanpad se tutto è chiarito potrebbe chiudere la issue?


Grazie.
Supporto ANSC.

**Comment by biadanpad** [comment]
Non capisco perchè sia necessario specificarlo: se è l'id dell'intestatario, questo è già presente nell'atto stesso

**Comment by amusarra** [comment]
> Non capisco perchè sia necessario specificarlo: se è l'id dell'intestatario, questo è già presente nell'atto stesso

È previsto dall'interfaccia.

Cordiali Saluti.
Supporto ANSC.
