### ISSUE TITLE
[WebApp] Generazione Annotazioni

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#238]
Ho provato a creare 2 diversi tipi di annotazione per due atti di nascita. In entrambi i casi l'annotazione non viene riportata nell'atto originale.

Di seguito gli Id degli eventi e delle annotazioni:
1. Evento: 954686 <-> Annotazione: 1110046
2. Evento: 954979 <-> Annotazione: 1110047

**Comment by biadanpad** [comment]
Alcuni giorni fa avevo fatto una prova analoga (se non ricordo male con un atto di matrimonio) e non avevo riscontrato problemi!

**Comment by biadanpad** [comment]
Sono rientrato nella WebApp ed ho visto che adesso l'Annotazione è presente per l'Evento 954979, ma non per l'Evento 954686

**Comment by amusarra** [comment]
Buongiorno, @biadanpad  il flusso delle annotazioni / notifiche annotazioni subirà delle modifiche richieste dal Ministero. Vi faremo sapere appena possibile.

**Comment by amusarra** [comment]
Chiudiamo la issue in attesa del nuovo rilascio che prevederà un nuovo flusso a riguardo.

Cordiali Saluti.
Supporto ANSC.
