### ISSUE TITLE
Chiamenti su Annotazioni

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#239]
Per l'evento di nascita 954576 ho inserito tramite WebService due annotazioni con Caso d'uso 14400000.

Andando ad interrogare i metadati dell'evento tramite WebApp li vedo entrambi:
![image](https://github.com/italia/ansc/assets/131870281/be84a368-dd94-4704-826b-0a60b447fdfd)

Quando poi vado a rilasciare un estratto dell'evento ne compare uno solo:
[estratto.pdf](https://github.com/italia/ansc/files/12039701/estratto.pdf)

**Comment by amusarra** [comment]
Chiudiamo la issue in attesa del nuovo rilascio che prevederà un nuovo flusso a riguardo.

Cordiali Saluti.
Supporto ANSC.
