### ISSUE TITLE
[R011] cancellazione evento: campi obbligatori nell'evento

### ISSUE THREAD

**Issue by MichelaGarzoni** [italia/ansc#24]
Buongiorno,
stavo verificando i campi richiesti per il servizio di cancellazione ed è presente il solo model "evento". Del model "evento" però il dubbio è: quali sono i campi obbligatori necessari per la cancellazione? Sono legati al tipo atto per cui si sta richiedendo la cancellazione? Per tutti i servizi ho visto che non sono evidenziati i campi obbligatori richiesti, ma viene dato solo l'elenco e la relativa tipologia. Per alcuni i campi sono semplici e quindi è deducibile la loro obbligatorietà, mentre per i servizi in cui è presente il model "evento" non si riesce a definire quali parti del model evento siano vincolanti per il servizio richiesto e quali superflue.

**Comment by mttfranci** [comment]
Nel caso del servizio R011 indica è sufficiente inviare il solo campo **id** del model evento, corrispondente all' idEvento, ovvero quello che poi diventa il secondo blocco di un idANSC, (ad esempio **950254** in 2023-**950254**-4323432-999999). Tutte le altre proprietà possono essere ignorate.

Valuteremo come rendere più evidente caso per caso le proprietà obbligatorie.

Saluti

Assistenza ANSC
