### ISSUE TITLE
Chiarimenti Annotazioni

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#241]
Relativamente alle annotazioni: una volta validata e firmata, quale sevizio devo invocare per poterla scaricare in formato PDF?

**Comment by amusarra** [comment]
Buongiorno, @biadanpad  il flusso delle annotazioni / notifiche annotazioni dell'atto di nascita subirà delle modifiche richieste dal Ministero. Vi faremo sapere appena possibile.

**Comment by amusarra** [comment]
Chiudiamo la issue in attesa del nuovo rilascio che prevederà un nuovo flusso a riguardo.

Cordiali Saluti.
Supporto ANSC.
