### ISSUE TITLE
Acquisto cittadinanza italiana per concessione: indicazioni per casi d'uso

### ISSUE THREAD

**Issue by antonioluberto** [italia/ansc#242]
Buongiorno.
Ci pare non siano indicati casi d'uso specifici per i casi di _acquisto della cittadinanza italiana per concessione_, disciplinati da:

a) articolo 5 della legge 5 febbraio 1992, n.91
- straniero coniugato con cittadino italiano
b) articolo 9 della legge 5 febbraio 1992, n.91
- straniero con ascendente entro il 2° grado italiano per nascita
- straniero maggiorenne adottato da cittadino italiano e residente in Italia da almeno 5 anni successivamente all'adozione
- straniero che ha prestato servizio, anche all'estero, per almeno cinque anni alle dipendenze dello Stato
- cittadino di uno Stato UE e residente legalmente da almeno quattro anni nel territorio della Repubblica
- apolide che risiede legalmente da almeno cinque  anni  nel territorio della Repubblica
- straniero che risiede legalmente da almeno dieci anni nel territorio della Repubblica

con l'unica eccezione (Citt_017) del caso di cittadina straniera coniugato con cittadino italiano prima del 27/04/1983.

Al netto di quest'ultima eccezione, dunque, è corretto fare riferimento per tutti i casi in elenco ai punti a) e b) rispettivamente a :

1) Citt_043 ovvero Citt_044 per la procedura di _Giuramento_
2) Trascr_Citt_999 per la procedura di _Trascrizione del Decreto_

?

**Comment by amusarra** [comment]
Buongiorno @antonioluberto
Abbiamo preso in carico la segnalazione e faremo le opportune verifiche.

Cordiali Saluti.
Supporto ANSC.

**Comment by rvinzani** [comment]
Buongiorno @antonioluberto,
è corretto come lei dice fare riferimento per tutti i casi in elenco ai punti a) e b) rispettivamente a :
Citt_043 ovvero Citt_044 per la procedura di Giuramento
Trascr_Citt_999 per la procedura di Trascrizione del Decreto
