### ISSUE TITLE
Figlio minore riconosciuto da cittadino italiano (Citt_002)

### ISSUE THREAD

**Issue by antonioluberto** [italia/ansc#243]
Il caso d'uso in oggetto prevede attualmente l'indicazione obbligatoria sia del padre che della madre; il riconoscimento cui segue l'attribuzione della cittadinanza italiana può tuttavia avvenire (e nella gran parte dei casi effettivamente avviene) a seguito di riconoscimento da parte di uno solo dei genitori.
Riteniamo pertanto sia necessario aggiornare la modellazione in maniera tale che sia richiesta obbligatoriamente l'indicazione di uno solo dei genitori.

**Comment by amusarra** [comment]
Buongiorno @antonioluberto 
Abbiamo preso in carico la segnalazione e faremo le opportune verifiche.

Cordiali Saluti.
Supporto ANSC.

**Comment by antonioluberto** [comment]
Il problema si presenta negli stessi termini anche per Citt_004

**Comment by rvinzani** [comment]
Se il riconoscimento è effettuato da uno solo dei due genitori ma l'altro lo ha già riconosciuto, il dato dell'altro genitore è obbligatorio
