### ISSUE TITLE
[R009] - Indirizzo e Numero Civico su UseCase: 321311

### ISSUE THREAD

**Issue by DiBellaDavide** [italia/ansc#245]
Salve,
per i casi d'uso Matr_007 e Matr_008 secondo il file di mapping, i campi di l'indirizzo numero civico del luogo della celebrazione non risultano essere obbligatori. Invocando il servizio di validazione invece sembrano esserlo.
Potete darci delucidazioni in merito?
Ambiente pre-prod
idOperazione = 1609352
Data test: 17/07/2023

**Comment by asqueglia** [comment]
Buonasera con la versione 1.11.0 è stata corretta la segnalazione. 
La issue viene chiusa nel caso si prega di riaprirla.
