### ISSUE TITLE
[R901] errore download tabella decodifica 96

### ISSUE THREAD

**Issue by siscomanpr** [italia/ansc#247]
Come da oggetto richiamando il servizio 
https://anscservicepre.anpr.interno.it/services/service/val/config/decodifica/dettaglio/1
per scaricare la nuova tabella 96 viene restituito errore 500 - Errore interno.

idOperazione: 1610041

**Comment by mttfranci** [comment]
Grazie della segnalazione @siscomanpr .
Potreste riprovare?
Ora dovrebbe funzionare.
Saluti

Assistenza ANSC
