### ISSUE TITLE
[R009] validazione caso d'uso di servizio (trascrizioni nascita) - 1399

### ISSUE THREAD

**Issue by siscomanpr** [italia/ansc#248]
Cercando di validare un atto di nascita con il caso d'uso in oggetto riceviamo come errore
`Il campo evento.motivoRecupero nella sezione Dati generali è obbligatorio`
Nel mapping tali nuovi campi risultano non obbligatori:
![image](https://github.com/italia/ansc/assets/28776141/4fe2a4aa-3a0f-4006-bfdd-8355acb6312d)

idOperazione: 1610100

**Comment by amusarra** [comment]
Buongiorno @siscomanpr 
Abbiamo preso in carico la sua segnalazione.

Cordiali Saluti.
Supporto ANSC.

**Comment by biadanpad** [comment]
Anche per il caso d'uso 31999 (Matr_999_1), così come in altri casi d'uso, si riscontra lo stesso problema.

Questo problema blocca lo sviluppo.

**Comment by asqueglia** [comment]
Buongiorno, con il rilascio della versione 1.12.0 la segnalazione è stata corretta; pertanto la issue viene chiusa. In caso vengano riscontrati ulteriori problemi si prega di riaprire l'issue
