### ISSUE TITLE
[ModelEvento] modelDatiAnnotazione tracciato modificato

### ISSUE THREAD

**Issue by siscomanpr** [italia/ansc#249]
Con la nuova versione abbiamo notato che nel tracciato evento è stato nuovamente modificato per intero il ModelDatiAnnotazione (con la versione 1.7.0 era stato ridotto ai soli campi testoAnnotazione e tipoAnnotazione) senza nessun riferimento nel nuovo changelog.
Visto che i 2 campi rimossi venivano usati per registrare le annotazioni contestuali, come vengono gestite ora? 
Per esempio come possiamo inviare l'annotazione di separazione dei beni nei matrimoni?

**Comment by ManuelDeMeo** [comment]
Abbiamo riscontrato la stessa problematica, inoltre su ModelEvento non è più presente una lista di annotazioni contestuali ma solo il riferimento ad un oggetto.

**Comment by mttfranci** [comment]
Dovremmo aver corretto la segnalazione con il rilascio della patch 1.10.1 ( #254 )

Saluti 

Assistenza ANSC
