### ISSUE TITLE
Tabella decodifica ANSC_1: stato dell'atto

### ISSUE THREAD

**Issue by MichelaGarzoni** [italia/ansc#25]
Buongiorno,
il primo stato assumibile dall'atto è quello relativo a "BOZZA", ma questo viene segnalato come errore durante la richiesta del servizio di validazione dell'atto (anche per semplice caso Morte_001 dove non sono presenti allegati obbligatori). In quale servizio lo stato può assumere tale valore? Qual'è la logica utilizzata? Ora in validazione mi accetta lo stato "CONFERMATO". In teoria io dovrei poter richiedere un'anteprima di un evento in stato BOZZA, ma se per avere l'anteprima è richiesto l'ID_ANSC devo ovviamente aver già validato l'atto, o l'ID_ANSC in anteprima è obbligatorio solo nel caso di atto "CONFERMATO"?

**Comment by mttfranci** [comment]
Si lo stato BOZZA è uno stato interno del sistema, da gestionale potete ignorarlo. il primo stato utile che è possibile usare per i gestionali è "CONFERMATO", saluti.

Assistenza ANSC
