### ISSUE TITLE
[ModelSoggetto] campo dataNascita

### ISSUE THREAD

**Issue by siscomanpr** [italia/ansc#250]
Il campo dataNascita del modelSoggetto è nuovamente indicato come "datanascita" (tutto minuscolo) nonostante questa segnalazione fosse già stata risolta con la versione 1.5.3.
Vedasi issue #37

**Comment by mttfranci** [comment]
Dovremmo aver corretto la segnalazione con il rilascio della patch 1.10.1 ( #254 )

Saluti 

Assistenza ANSC
