### ISSUE TITLE
[R001] Verifica stato allegato

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#252]
Con la nuova release, nella tabella di decodifica 8_dec_stato_allegato avete aggiunto 3 stati: Validato, In Attesa di Validazione e Ritentare Validazione.

Qual'è la differenza tra Inserito e Validato?
Fino alla release precedente lo stato "finale" era Inserito, adesso è Validato?

Potreste descrivere meglio tutti i stati?

Grazie.

**Comment by mttfranci** [comment]
Salve, stiamo verificando la segnalazione in quanto alcuni stati non dovevano fare parte del workflow del servizio.

Nel frattempo, vi consigliamo di considerare solo gli stati finali dell'allegato, ovvero : 
3 - in caso di allegato accolto e verificato positivamente
4 - in caso di allegato rifiutato

![image](https://github.com/italia/ansc/assets/29305782/d18dab7a-8cee-41eb-af7b-012ab906a407)

Saluti

Assistenza ANSC

**Comment by biadanpad** [comment]
Ok, 
ma non ricevo ne 3, ne 4 come risposta, ma 7

REQUEST:
{
    "idAllegato": "2111759",
    "testataRichiesta": {
        "idComune": 5000,
        "idOperazioneComune": "35",
        "dataOraRichiesta": "2023-07-19T14:26:50.123+02:00",
        "nomeApplicativo": "urbi",
        "versioneApplicativo": "0.1.0",
        "fornitoreApplicativo": "padigitale"
    }
}

RESPONSE:
{
    "testataRisposta": {
        "idComune": 5000,
        "idOperazioneComune": "35",
        "idOperazione": "1610549",
        "idEsito": 0
    },
    "allegatoOutput": {
        "idAllegato": "2111759",
        "statoAllegato": "7",
        "idDocumentum": null
    }
}

**Comment by mttfranci** [comment]
Salve, si trattava di un upload firma dichiarante?
In tal caso dovremmo aver risolto l'anomalia come indicato nella issue #253
Saluti

Assistenza ANSC
