### ISSUE TITLE
[R006] firma dichiarante: stato allegato 7

### ISSUE THREAD

**Issue by MichelaGarzoni** [italia/ansc#253]
Buongiorno,
dopo il rilascio di ieri, con l'upload dell'atto firmato (servizio R006) ora lo stato dell'allegato viene restituito pari a 7. 
Ho visto che la tabella 8_dec_stato_allegato ha subito delle modifiche.
Precedentemente lo stato che veniva restituito era 1_ricezione.
Ora serve testare con il servizio R001 lo stato dell'allegato (upload dell'atto firmato R006)? 
Da quando ho inviato, con il servizio R006, l'atto firmato, questo non ha modificato nel tempo il suo stato: risulta sempre essere in stato 7 e non permette di procedere alla firma dell'USC.
es.
{"testataRisposta":{"idComune":3655,"idEsito":0,"idOperazione":"1610266","idOperazioneComune":"20230050000033"},"firmaDichiaranteOutput":{"contenuto":"...............","idAllegato":"2111719","nomefile":"pdf_atto_di_morteXXX.pdf","statoAllegato":"7","tipoAllegato":"999","tipoFile":"1"}}

**Comment by mttfranci** [comment]
Dovremmo aver rilasciato la correzione nell'ambito della patch 1.10.1 ( #254 )
Saluti

Assistenza ANSC

**Comment by mttfranci** [comment]
Si, stiamo verificando come procedere. intanto vi consigliamo di valutare solo gli stati finali : 
3 - accettato
4 - rifiutato

Come indicato nella issue #252

Saluti

Assistenza ANSC
