### ISSUE TITLE
[R001] Stato allegato

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#255]
Ok, 
ma non ricevo ne 3, ne 4 come risposta, ma 7

REQUEST:
{
    "idAllegato": "2111759",
    "testataRichiesta": {
        "idComune": 5000,
        "idOperazioneComune": "35",
        "dataOraRichiesta": "2023-07-19T14:26:50.123+02:00",
        "nomeApplicativo": "urbi",
        "versioneApplicativo": "0.1.0",
        "fornitoreApplicativo": "padigitale"
    }
}

RESPONSE:
{
    "testataRisposta": {
        "idComune": 5000,
        "idOperazioneComune": "35",
        "idOperazione": "1610549",
        "idEsito": 0
    },
    "allegatoOutput": {
        "idAllegato": "2111759",
        "statoAllegato": "7",
        "idDocumentum": null
    }
}

_Originally posted by @biadanpad in https://github.com/italia/ansc/issues/252#issuecomment-1641995648_

**Comment by biadanpad** [comment]
Adesso ricevo 3 come stato "finale".

Continuo però a ricevere 6 come stato intermedio. E' normale?

REQUEST:
{
    "idAllegato": "2112000",
    "testataRichiesta": {
        "idComune": 5000,
        "idOperazioneComune": "24",
        "dataOraRichiesta": "2023-07-19T16:02:26.494+02:00",
        "nomeApplicativo": "urbi",
        "versioneApplicativo": "0.1.0",
        "fornitoreApplicativo": "padigitale"
    }
}

RESPONSE:
{
    "testataRisposta": {
        "idComune": 5000,
        "idOperazioneComune": "24",
        "idOperazione": "1610799",
        "idEsito": 0
    },
    "allegatoOutput": {
        "idAllegato": "2112000",
        "statoAllegato": "6",
        "idDocumentum": null
    }
}

**Comment by mttfranci** [comment]
Salve.

Stiamo valutando come procedere su questa modifica allo stato iniziale.

Intanto, come già fatto nella issue #252 , vi suggeriamo di considerare solo gli stati finali 
3 - accettato
4 - rifiutato

Gli altri sono comunque stati intermedi.

Saluti
