### ISSUE TITLE
[web-service] Rilascio v1.10 - ModelEnteEstero: idAnagraficaConsolato / AnagraficaConsolato

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/ansc#256]
con il rilascio della v1.10 sono stati inseriti i due nuovi campi in oggetto

due segnalazioni:
1. i campi risultano obbligatori, invalidando così gli invii di tutte le trascrizioni da autorità estera che fino a ieri funzionavano
esempi di casi d'uso:
- x le nascite: 1311 - Trascrizione di atto di nascita avvenuta all'estero su richiesta dell'autorita' diplomatica o consolare
- x i matrimoni: 332000 - Trascrizione matrimoni dall'estero - richiesta di trascrizione da parte del Consolato/Ambasciata

si può evitare che siano obbligatori?

2. le specifiche documentano questi due campi in questo modo:
![image](https://github.com/italia/ansc/assets/26788199/a68d3636-4742-49c9-8726-091cf1d7e08e)

a quale tabella dobbiamo riferirci per valorizzarli?
pensavamo potesse essere la stessa tabella ANPR utilizzata per gli idStatoXxxx, ma - rifacendoci all'esempio - '190' indica UZBEKISTAN e non sarebbe coerente con la descrizione 'Berlino' (... da qui la richiesta di sapere a quale tabella dobbiamo riferirci...)

grazie
Alessandro Monopoli ADS

**Comment by mttfranci** [comment]
Salve, con la patch 1.10.2 #281 abbiamo rilasciato la tabella 97.
Saluti

Assistenza ANSC

**Comment by AMonopoliADS** [comment]
> Salve, con la patch 1.10.2 #281 abbiamo rilasciato la tabella 97. Saluti
> 
> Assistenza ANSC

con gli interventi della v1.10.2 è stata eliminata anche l'obbligatoriertà dei due campi?
perchè dagli ultimi test eseguiti sembrerebbe così, ma nel changelog non ho trovato riferimenti a questo specifico intervento.

grazie
Alessandro
