### ISSUE TITLE
[R009] Validazione atto di cittadinanza - "evento.motivoRecupero" obbligatorio

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#258]
Tentando di validare un atto di cittadinanza il servizio risponde con errore: "Il campo evento.motivoRecupero nella sezione Dati generali è obbligatorio"

REQUEST:
{
    "evento": {
        "idAnsc": "",
        "idTipoEvento": "5",
        "idtipocontenuto": "1",
        "idUsecase": "51999",
        "stato": "CONFERMATO",
        "dataformazione": "2023-07-20",
        "ora": "12",
        "minuto": "26",
        "operatore": "DLCNTN57L67A064W",
        "operatoreNome": "MARTINA",
        "operatoreCognome": "GORI",
        "idComuneRegistrazione": "5000",
        "nomeComuneRegistrazione": "LISSONE",
        "idProvinciaRegistrazione": "108",
        "siglaProvinciaRegistrazione": "MB",
        "dataDecorrenza": "2023-07-20",
        "numeroatto": "54",
        "intestatari": [{
                "cognome": "ABBATIELLO",
                "nome": "ALESSANDRO",
                "sesso": "M",
                "dataNascita": "1987-10-04",
                "idComuneNascita": "16508",
                "nomeComuneNascita": "FIRENZE",
                "idProvinciaNascita": "48",
                "siglaProvinciaNascita": "FI",
                "idStatoNascita": "90",
                "nomeStatoNascita": "ITALIA",
                "idComuneResidenza": "7630",
                "nomeComuneResidenza": "PRATO",
                "idProvinciaResidenza": "100",
                "siglaProvinciaResidenza": "PO",
                "idStatoResidenza": "90",
                "nomeStatoResidenza": "ITALIA",
                "idNazionalita": "129",
                "nazionalita": "NORVEGESE",
                "flagDichiarante": false,
                "flagComparente": false,
                "flagFirmatario": false
            }
        ],
        "composizioneCompleta": "                      -------------------------------------------------------------------------- "
    },
    "testataRichiesta": {
        "idComune": 5000,
        "idOperazioneComune": "1582",
        "dataOraRichiesta": "2023-07-20T12:26:38.058+02:00",
        "nomeApplicativo": "urbi",
        "versioneApplicativo": "0.1.0",
        "fornitoreApplicativo": "padigitale"
    }
}

RESPONSE:
{
    "testataRisposta": {
        "idComune": 5000,
        "idOperazioneComune": "1582",
        "idOperazione": "1611116",
        "idEsito": 1
    },
    "errors": [{
            "code": "400003",
            "severity": "E",
            "text": "Il campo evento.motivoRecupero nella sezione Dati generali è obbligatorio"
        }
    ]
}

**Comment by biadanpad** [comment]
Potreste inoltre spiegarmi il significato / uso di questo campo?

**Comment by asqueglia** [comment]
Buongiorno, il motivo di recupero è un dato obbligatorio quando viene espressamente indicata la data di decorrenza diversa dalla data di formazione. 
La data di decorrenza è una data da utilizzare quando un atto viene redatto in cartaceo temporaneamente per problemi di sistema ad esempio per indisponibilità del sistema, e successivamente viene digitalizzato ed acquisto a sistema.
Solo in questo caso è necessario specificare la data decorrenza come data in cui è stato registrato l'atto cartaceo e indicare obbligatoriamente il motivo per cui l'atto è stato formato in cartaceo.

**Comment by biadanpad** [comment]
Buongiorno, 
grazie per la spiegazione.

Dove posso trovare una documentazione analoga per i vari campi delle strutture previste?

Nel mio caso, però, la data di decorrenza e quella di formazione coincidono (2023-07-20)

**Comment by asqueglia** [comment]
Buongiorno, verifichiamo la segnalazione relativa alla data decorrenza che è uguale alla data formazione. 
Se ha necessità di completare il test consigliamo per il momento di non trasmettere la data decorrenza, qualora si stia provvedendo non ad un recupero ma ad una registrazione di un atto direttamente in digitale.
