### ISSUE TITLE
Chiarimento su ModelTrascrizioneCittadinanza

### ISSUE THREAD

**Issue by ManuelDeMeo** [italia/ansc#259]
Buongiorno, con il rilascio 1.10.1 è stato introdotto nell'oggetto ModelTrascrizioneCittadinanza il campo "genitoreConCittadinanza"

![image](https://github.com/italia/ansc/assets/126863582/732adf97-c2f4-4a62-8119-c21c940f1fec)

La descrizione indica "genitore con cittadinanza italiana" e l'esempio è "90". Fra l'altro, provando a valorizzarlo e ad inviarlo con R009 si ottiene l'errore seguente:

`•	400003 : Il campo evento.trascrizioneCittadinanza.genitoreConCittadinanza nella sezione Dettagli evento non corrisponde al pattern ^[0-9]*$`

Il che quindi dimostra che bisogna valorizzarlo con un numero.

A cosa corrisponde il 90 indicato nell'esempio? Come valorizzare in generale il campo? 
Grazie

**Comment by asqueglia** [comment]
Buon pomeriggio, i possibili valori che il campo può assumere sono
1 = Madre , 2= Padre , 3 = Entrambe
Provvederemo quanto prima a modificare la documentazione in maniera adeguata.

**Comment by asqueglia** [comment]
Buonasera con la versione 1.10.2 è stata corretta la documentazione relativa alla segnalazione; pertanto provvediamo a chiudere la issue, in caso si prega di riaprirla.
