### ISSUE TITLE
[R006]  firma del dichiarante: chiarimenti su alcuni campi

### ISSUE THREAD

**Issue by MichelaGarzoni** [italia/ansc#26]
Buongiorno,
nel json relativo al servizio di firma del dichiarante è richiesto il campo "idEvento" con che valore deve essere popolato? Mi sarei aspettata un "id_ANSC" in quanto l'atto che invio è già validato e presente su vostro archivio e quindi il suo numero di riconoscimento è l'"id_ansc" e non un id_evento legato ad un evento interno al mio applicativo.
Per il campo "tipoAllegato" si fa riferimento alla tabella di decodifica ANSC_09 ma, ad esempio, se invio un atto di morte firmato in modo autografo, quale valore in relazione a questo campo si aspetta il servizio tra quelli in elenco? Mi aspetterei un "atto firmato", una voce quindi generica tra i documenti da inviare, ma non lo trovo o non lo identifico tra quelli presenti.

**Comment by mttfranci** [comment]
Per la prima domanda, 
la proprietà **idEvento** (o **id** nel caso si trovi all'interno del modelEvento) è la parte nazionale dell'idAnsc completo. Ad esempio per l'idANSC 2023-950254-4323432-999999 il corrispondente idEvento è 950254. Vale a dire che, in generalequest'ultimo è sempre sufficiente da solo a identificare un evento.

Per la seconda domanda, 
Potete indicare come tipologia in questi casi la 999 - Processo verbale.

Saluti

Assistenza ANSC
