### ISSUE TITLE
Indirizzo padre/madre su Citt_004

### ISSUE THREAD

**Issue by antonioluberto** [italia/ansc#260]
Con riferimento al caso d'uso in oggetto, risulta obbligatorio il dato relativo all'indirizzo di residenza di padre/madre.
Oggi non è un dato previsto nella generazione dell'atto di stato civile in relazione a questo tipo di adempimento, il che comporta il fatto che le applicazioni locali non prevedono oggi su interfaccia l'inserimento dell'informazione corrispondente.
Non risultano peraltro modifiche normative tali da comportare la gestione obbligatoria del dato. 
E' possibile rivedere il controllo in maniera tale che il dato relativo all'indirizzo di residenza di padre/madre non obbligatorio?

**Comment by asqueglia** [comment]
Buongiorno, certamente provvediamo a rendere il controllo non obbligatorio. Faremo sapere quando disponibile la correzione

**Comment by asqueglia** [comment]
Buonasera con la versione 1.11.0 è stata corretta la segnalazione. 
La issue viene chiusa nel caso si prega di riaprirla.
