### ISSUE TITLE
Rinuncia alla cittadinanza da parte di cittadino maggiorenne (Citt_021, Citt_022)

### ISSUE THREAD

**Issue by antonioluberto** [italia/ansc#261]
Citt_021 - Rinuncia del maggiorenne che aveva acquistato la cittadinanza per convivenza con il genitore art. 14
e
Citt_022 -  Rinuncia del maggiorenne che aveva acquistato la cittadinanza per convivenza con il genitore art. 14

paiono far entrambi riferimento, almeno nella descrizione, al medesimo caso funzionale: il caso di cittadino maggiorenne che aveva acquisito la cittadinanza italiana quando era ancora (figlio) minorenne convivente con il genitore che era divenuto cittadino italiano, dichiari all'usc la volontà di rinuncia alla cittadinanza italiana medesima.

Il modello dati relativo a "Citt_021" indica come formula di riferimento la "88", il modello dati relativo a "Citt_022" indica come formula di riferimento la "193".

E' possibile, dunque:
a) tramite "Citt_021" debba gestirsi il caso funzionale:
_cittadino maggiorenne che aveva acquisito la cittadinanza italiana quando era ancora (figlio) minorenne convivente con il genitore che era divenuto cittadino italiano, dichiari all'usc la volontà di rinuncia alla cittadinanza italiana medesima_
b) tramite "Citt_021" debba gestirsi il caso funzionale:
_trascrizione dell'accertamento di altra autorità presso la quale il cittadino abbia reso la dichiarazione di rinuncia alla cittadinanza italiana_
?

E se la nostra valutazione è corretta: 
c) perché sia il modello dati relativo a "Citt_021" sia quello relativo a "Citt_022" prevedono obbligatoriamente la sezione "Atto collegato":

![image](https://github.com/italia/ansc/assets/26415430/021c44b6-a7ec-46ad-9727-3412a6a0cf9f)

?

Quali informazioni vi dovremmo riportare nei due casi?

d) perché il modello dati relativo a "Citt_022" prevede obbligatoriamente la sezione "Padre" e la sezione "Madre"?
Oggi non è prevista l'indicazione del dato di paternità/maternità nella generazione dell'atto di stato civile in relazione al tipo di adempimento:
_trascrizione dell'accertamento di altra autorità presso la quale il cittadino abbia reso la dichiarazione di rinuncia alla cittadinanza italiana_
il che comporta il fatto che le applicazioni locali non prevedono oggi su interfaccia l'inserimento dell'informazione corrispondente.
Non risultano peraltro modifiche normative tali da comportare la gestione obbligatoria del dato.

Si rimane in attesa di vostre indicazioni.

**Comment by asqueglia** [comment]
Buongionro, è corretta la sua interpretazione nel senso che Citt_021 è una dichiarazione e Citt_022 una trascrizione. Verifichiamo le obbligatorietà errate da lei indicate e provvediamo a correggere le segnalazioni appena possibile. Le faremo saper quando è possibile riprovare.

**Comment by asqueglia** [comment]
Buonasera con la versione 1.11.0 è stata corretta la segnalazione. 
La issue viene chiusa nel caso si prega di riaprirla.
