### ISSUE TITLE
Rinuncia alla cittadinanza  a seguito di revoca dell'adozione (Citt_023, Citt_025)

### ISSUE THREAD

**Issue by antonioluberto** [italia/ansc#262]
Citt_023 - Revoca dell'adozione per il fatto dell'adottato
e
Citt_025 - Revoca dell'adozione per il fatto dell'adottante, rinuncia espressa cittadinanza entro un anno dalla revoca adozione

paiono far entrambi riferimento, almeno nella descrizione, al medesimo caso funzionale: il caso di cittadino maggiorenne che a seguito di revoca dell'adozione, dichiari all'usc la volontà di rinuncia alla cittadinanza italiana medesima.

Il modello dati relativo a "Citt_023" indica come formula di riferimento la "193", così pure il modello dati relativo a "Citt_025"; se però effettivamente ci si intende riferire al caso funzionale
_cittadino maggiorenne che a seguito di revoca dell'adozione, dichiari all'usc la volontà di rinuncia alla cittadinanza italiana medesima_
allora la formula di riferimento dovrebbe essere la "76".

E se, al netto di eventuale errore nell'indicazione della formula di riferimento, il caso d'uso da gestirsi è effettivamente
_cittadino maggiorenne che a seguito di revoca dell'adozione, dichiari all'usc la volontà di rinuncia alla cittadinanza italiana medesima_

a) quando dovremmo fare riferimento a "Citt_023" e quando a "Citt_025"
b) perché il modello dati relativo a "Citt_025" prevede obbligatoriamente la sezione "Atto collegato":
![image](https://github.com/italia/ansc/assets/26415430/2c13fe69-c1a5-4f8a-a237-039309b5d411)

?

Quali informazioni vi dovremmo riportare ?

c) perché sia il modello dati relativo a "Citt_023" sia quello relativo a "Citt_025" prevedono obbligatoriamente la sezione "Autorità mittente":

![image](https://github.com/italia/ansc/assets/26415430/c41622de-6407-4c13-a1f5-ff18db052679)

Trattandosi di dichiarazione di rinuncia alla cittadinanza che il soggetto rende direttamente all'usc, non vi è alcuna autorità terza che dia comunicazione all'usc medesimo.

Si rimane in attesa di vostre indicazioni.

**Comment by asqueglia** [comment]
Buongiorno,
con Citt_023 (caso d'uso 52271) -> si tratta di una Trascrizione di perdita di cittadinanza per decreto del tribunale/attestazione sindaco che richiede di Revoca dell'adozione per il fatto dell'adottato.
con Citt_025 (caso d'uso 5.2.2.2.2) -> si tratta di una Trascrizione di perdita di cittadinanza su accertamento del Sindaco che richiede la Revoca dell'adozione per il fatto dell'adottante, rinuncia espressa cittadinanza entro un anno dalla revoca adozione.

Trattandosi di una trascrizione abbiamo reso obbligatoria la seione autorità mittente; per l'atto collegato facciamo una verifica.
Le torna che i casi siano trattati come trascrizioni ?

**Comment by antonioluberto** [comment]
Plausibile la rappresentazione di cui sopra circa le trascrizioni di provvedimenti che determinino la perdita della cittadinanza; rimane il dubbio:
qual è il caso d'uso cui fare riferimento per 
_cittadino maggiorenne che a seguito di revoca dell'adozione, dichiari (personalmente) all'usc la volontà di rinuncia alla cittadinanza italiana medesima_ ?

**Comment by asqueglia** [comment]
Buongiorno @antonioluberto non trovo la casistica da lei indicata, censita tra i casi d'uso condivisi e rilasciati; per cui provvediamo ad inserirla tra i casi da trattare e da configurare in un momento successivo.

**Comment by asqueglia** [comment]
Buonasera con la versione 1.11.0 è stata corretta la segnalazione. 
La issue viene chiusa nel caso si prega di riaprirla.
