### ISSUE TITLE
Modificati gli stati possibili degli Allegati.

### ISSUE THREAD

**Issue by gcuci** [italia/ansc#263]
buonasera,

con gli ultimi rilasci (1.10.0 e 1.10.1), è stata modificata la tabella di decodifica dei possibili stati degli allegati (8_dec_stato_allegato), con l'aggiunta di 3 nuovi stati:

6 - Validato;
7 - In attesa di Validazione;
8 - Ritentare Validazione.

Questi nuovi valori, sono da subito stati utilizzati nei servizi di Upload Allegato, e di Firma Dichiarante (ad un primo invio viene adesso restituito lo stato 6-Validato, invece del precedente 1-Ricevuto). Senza peraltro alcuna segnalazione nei Changelog dei rilasci.

Questa variazione ha fatto saltare i controlli che avevamo impostato sullo stato degli allegati, in base alla precedente decodifica, e dobbiamo adesso intervenire per adeguarci ai nuovi valori.

Avendo messo in piedi degli ambienti di integrazione di Test, per permettere ai nostri Comuni di poter fare le loro verifiche, vi chiediamo, nel caso siano necessarie variazioni di questo tipo, se sia possibile avvisarci con un minimo di anticipo, per predisporre le nostre modifiche.

Nel caso specifico la modifica che è stata introdotta, potrebbe in effetti, semplificarci il processo di verifica sullo stato degli allegati, se lo stato 6-Validato, che adesso viene subito restituito, è il nuovo stato definitivo. In precedenza, successivamente al primo invio (sia di Upload Allegato, che di Firma Dichiarante), chiamavamo più volte il servizio di Verifica Allegato per verificarne il passaggio allo stato 3-Inserito, che, nella maggior parte dei casi richiedeva più di un minuto. 

Potete darci conferma di questo, e farci un riepilogo degli stati in cui si può trovare un Allegato, ed in quali condizioni?

In attesa di un riscontro,

cordiali saluti.

**Comment by mttfranci** [comment]
Salve, stiamo valutando come procedere, intanto, come indicato nelal issue #252 vi suggeriamo di considerare per ora solo gli stati finali : 
3 per accettati
4 per rifiutato

Saluti

Assistenza ANSC
