### ISSUE TITLE
[use-case 341000 accordo di separazione personale dei coniugi]  - problemi dati "separazione" in validazione 

### ISSUE THREAD

**Issue by MichelaGarzoni** [italia/ansc#264]
Buongiorno, in fase di validazione ci vengono segnalati errori come se tutta la parte inerente la radice "separazione" non fosse corretto, ma non vediamo inesattezze in quanto inviamo.
Es utilizzato (id operazione 1611574):
{
"testataRichiesta":{
"idComune":3655
,"idOperazioneComune":"20230150000006"
,"dataOraRichiesta":"2023-07-24T12:02:31Z"
,"nomeApplicativo":"ASCOT Stato Civile"
,"versioneApplicativo":"21.99.0000"
,"fornitoreApplicativo":"Insiel S.p.A"
}
,"evento":{
"idTipoEvento":"3"
,"idtipocontenuto":"1"
,"idUsecase":"341000"
,"descrizioneCasoUso":"Accordo di separazione personale dei coniugi"
,"stato":"CONFERMATO"
,"secretato":"0"
,"dataformazione":"2023-07-14"
,"ora":"11"
,"minuto":"46"
,"numeroatto":"20230150000006"
,"idComuneRegistrazione":3655
,"nomeComuneRegistrazione":"DUINO AURISINA-DEVIN NABRE\u017DINA"
,"idProvinciaRegistrazione":"32"
,"siglaProvinciaRegistrazione":"TS"
,"certificabile":"1"
,"composizioneCompleta":"testo Il presente atto viene letto ai dichiaranti i quali, insieme con me e con l\u0027avvocato presente per assisterli, lo sottoscrivono.\r\n"
,"interprete":{
}
**,"Separazione":{
"tipoAccordo":"2"
,"presenzaAvvocatoConiuge1":"True"
,"avvocatoConiuge1":{
"cognome":"Fxxxxx"
,"nome":"Gyyyyyy"
}
,"foroAvvocatoConiuge1":"020030"
,"presenzaAvvocatoConiuge2":"True"
,"avvocatoConiuge2":{
"cognome":"XXXXXX"
,"nome":"FFFFFFFF"
}
,"foroAvvocatoConiuge2":"031007"
,"attoMatrimonio":{
"idAnsc":"2023-44444-5555"
,"idComuneRegistrazione":"006"
,"nomeComuneRegistrazione":"TRIESTE"
,"siglaProvinciaRegistrazione":"TS"
,"idProvinciaRegistrazione":"032"
,"idtipocontenuto":"1"
,"dataformazione":"1973-01-20"
,"numeroatto":"24"
,"annoAtto":"1973"
,"tipologia":"3"
,"parte":"I"
}
,"parteInGiudizioPendente":"False"
,"dataConfermaAccordo":"16\/08\/2023"
}**
,"intestatari":[
{
"cognome":"PXXXXXXXXX"
,"nome":"GYYYYYYYYYYY"
,"sesso":"M"
,"dataNascita":"1945-03-26"
,"idComuneNascita":"006"
,"nomeComuneNascita":"TRIESTE"
,"idProvinciaNascita":"032"
,"siglaProvinciaNascita":"TS"
,"idStatoNascita":"90"
,"nomeStatoNascita":"ITALIA"
,"idComuneResidenza":"3655"
,"nomeComuneResidenza":"DUINO AURISINA-DEVIN NABRE\u017DINA"
,"idProvinciaResidenza":"32"
,"siglaProvinciaResidenza":"TS"
,"idStatoResidenza":"90"
,"nomeStatoResidenza":"ITALIA"
,"idNazionalita":"100"
,"nazionalita":"ITALIANO"
,"flagDichiarante":"True"
,"flagComparente":"True"
,"flagFirmatario":"True"
}
,{
"cognome":"GYYYYYYYYYYY"
,"nome":"GXXXXXXXXX"
,"sesso":"F"
,"dataNascita":"1947-02-08"
,"idComuneNascita":"006"
,"nomeComuneNascita":"TRIESTE"
,"idProvinciaNascita":"032"
,"siglaProvinciaNascita":"TS"
,"idStatoNascita":"90"
,"nomeStatoNascita":"ITALIA"
,"idComuneResidenza":"3655"
,"nomeComuneResidenza":"DUINO AURISINA-DEVIN NABRE\u017DINA"
,"idProvinciaResidenza":"32"
,"siglaProvinciaResidenza":"TS"
,"idStatoResidenza":"90"
,"nomeStatoResidenza":"ITALIA"
,"idNazionalita":"100"
,"nazionalita":"ITALIANA"
,"flagDichiarante":"True"
,"flagComparente":"True"
,"flagFirmatario":"True"
}
]
}
}

in validazione ci segnala i seguenti errori:
{
    "testataRisposta": {
        "idComune": 3655,
        "idOperazioneComune": "20230150000006",
        "idOperazione": "1611574",
        "idEsito": 1
    },
    "errors": [
        {
            "code": "400003",
            "severity": "E",
            "text": "Il campo evento.separazione.attoMatrimonio.idProvinciaRegistrazione nella sezione Atto di Matrimonio è obbligatorio"
        },
        {
            "code": "400003",
            "severity": "E",
            "text": "Il campo evento.separazione.attoMatrimonio.siglaProvinciaRegistrazione nella sezione Atto di Matrimonio è obbligatorio"
        },
        {
            "code": "400003",
            "severity": "E",
            "text": "Il campo evento.separazione.attoMatrimonio.idComuneRegistrazione nella sezione Atto di Matrimonio è obbligatorio"
        },
        {
            "code": "400003",
            "severity": "E",
            "text": "Il campo evento.separazione.attoMatrimonio.nomeComuneRegistrazione nella sezione Atto di Matrimonio è obbligatorio"
        },
        {
            "code": "400003",
            "severity": "E",
            "text": "Il campo evento.separazione.attoMatrimonio.idtipocontenuto nella sezione Atto di Matrimonio è obbligatorio"
        },
        {
            "code": "400003",
            "severity": "E",
            "text": "Il campo evento.separazione.attoMatrimonio.numeroatto nella sezione Atto di Matrimonio è obbligatorio"
        },
        {
            "code": "400003",
            "severity": "E",
            "text": "Il campo evento.separazione.attoMatrimonio.annoAtto nella sezione Atto di Matrimonio è obbligatorio"
        },
        {
            "code": "400003",
            "severity": "E",
            "text": "Il campo evento.separazione.attoMatrimonio.dataformazione nella sezione Atto di Matrimonio è obbligatorio"
        },
        {
            "code": "400003",
            "severity": "E",
            "text": "Il campo evento.separazione.attoMatrimonio.tipologia nella sezione Atto di Matrimonio è obbligatorio"
        },
        {
            "code": "400003",
            "severity": "E",
            "text": "Il campo evento.separazione.tipoAccordo nella sezione Dettaglio accordo è obbligatorio"
        },
        {
            "code": "400003",
            "severity": "E",
            "text": "Il campo evento.separazione.parteInGiudizioPendente nella sezione Dettaglio accordo è obbligatorio"
        },
        {
            "code": "400003",
            "severity": "E",
            "text": "Il campo evento.separazione.dataConfermaAccordo nella sezione Dettaglio accordo è obbligatorio"
        },
        {
            "code": "400003",
            "severity": "E",
            "text": "Il campo evento.separazione.presenzaAvvocatoConiuge1 nella sezione Dettagli evento è obbligatorio"
        },
        {
            "code": "400003",
            "severity": "E",
            "text": "Il campo evento.separazione.presenzaAvvocatoConiuge2 nella sezione Dettagli evento è obbligatorio"
        }
    ]
}

se sostituiamo il tag "Separazione" con "separazione" (iniziale da maiuscolo a minuscolo, come sembrerebbe dovrebbe essere) l'intero json va in errore e non viene riconosciuto:
errore 500
{
    "message": "internal.error",
    "errors": null
}

**Comment by asqueglia** [comment]
Buongiorno, da una analisi del payload da voi utilizzato vediamo una serie di correzioni da apportare :
l'elemento 'Separazione' deve essere '**separazione**' con la s piccola
i flag 'True' e 'False' devono essere sostituiti con **true** e **false** non come stringhe ma come valori booleani
la data di conferma accordo è trasmessa con pattern errato, va sostituita da "16/08/2023" a **"2023-08-16"** come fatto su tutte le altre date; questo era il problema dell'internal error

Le invio in calce un esempio funzionante del payload 

  "evento": {
        "idTipoEvento": "3",
        "idtipocontenuto": "1",
        "idUsecase": "341000",
        "descrizioneCasoUso": "Accordo di separazione personale dei coniugi",
        "stato": "CONFERMATO",
        "secretato": "0",
        "dataformazione": "2023-07-14",
        "ora": "11",
        "minuto": "46",
        "numeroatto": "20230150000006",
        "idComuneRegistrazione": "1000000",
        "nomeComuneRegistrazione": "ANPR",
        "idProvinciaRegistrazione": "58",
        "siglaProvinciaRegistrazione": "RM",
        "operatore": "CRUMRA67S47Z127B",
        "ruoloOperatore": "3",
        "operatoreNome": "MARIE",
        "operatoreCognome": "CURIE",
        "certificabile": "1",
        "composizioneCompleta": "aaaa",
        "separazione": {
            "tipoAccordo": "1",
            "presenzaAvvocatoConiuge1": true,
            "avvocatoConiuge1": {
                "cognome": "Fxxxxx",
                "nome": "Gyyyyyy"
            },
            "foroAvvocatoConiuge1": "020030",
            "presenzaAvvocatoConiuge2": true,
            "avvocatoConiuge2": {
                "cognome": "XXXXXX",
                "nome": "FFFFFFFF"
            },
            "foroAvvocatoConiuge2": "031007",
            "attoMatrimonio": {
                "idAnsc": "2023-44444-5555",
                "idComuneRegistrazione": "006",
                "nomeComuneRegistrazione": "TRIESTE",
                "siglaProvinciaRegistrazione": "TS",
                "idProvinciaRegistrazione": "032",
                "idtipocontenuto": "1",
                "dataformazione": "1973-01-20",
                "numeroatto": "24",
                "annoAtto": "1973",
                "tipologia": "3",
                "parte": "I"
            },
            "parteInGiudizioPendente": false,
            "dataConfermaAccordo": "2023-08-26"
        },
        "intestatari": [
            {
                "cognome": "PXXXXXXXXX",
                "nome": "GYYYYYYYYYYY",
                "sesso": "M",
                "dataNascita": "1945-03-26",
                "idComuneNascita": "006",
                "nomeComuneNascita": "TRIESTE",
                "idProvinciaNascita": "032",
                "siglaProvinciaNascita": "TS",
                "idStatoNascita": "90",
                "nomeStatoNascita": "ITALIA",
                "idComuneResidenza": "3655",
                "nomeComuneResidenza": "DUINO AURISINA-DEVIN NABRE\u017DINA",
                "idProvinciaResidenza": "32",
                "siglaProvinciaResidenza": "TS",
                "idStatoResidenza": "90",
                "nomeStatoResidenza": "ITALIA",
                "idNazionalita": "100",
                "nazionalita": "ITALIANA",
                "flagDichiarante": true,
                "flagComparente": true,
                "flagFirmatario": true
            },
            {
                "cognome": "GYYYYYYYYYYY",
                "nome": "GXXXXXXXXX",
                "sesso": "F",
                "dataNascita": "1947-02-08",
                "idComuneNascita": "006",
                "nomeComuneNascita": "TRIESTE",
                "idProvinciaNascita": "032",
                "siglaProvinciaNascita": "TS",
                "idStatoNascita": "90",
                "nomeStatoNascita": "ITALIA",
                "idComuneResidenza": "3655",
                "nomeComuneResidenza": "DUINO AURISINA-DEVIN NABRE\u017DINA",
                "idProvinciaResidenza": "32",
                "siglaProvinciaResidenza": "TS",
                "idStatoResidenza": "90",
                "nomeStatoResidenza": "ITALIA",
                "idNazionalita": "100",
                "nazionalita": "ITALIANA",
                "flagDichiarante": true,
                "flagComparente": true,
                "flagFirmatario": true
            }
        ]
    }
}

**Comment by asqueglia** [comment]
perfetto chiuso la issua nel caso si prega di riaprirla
