### ISSUE TITLE
Ancora su figlio minore riconosciuto da cittadino italiano (Citt_002)

### ISSUE THREAD

**Issue by antonioluberto** [italia/ansc#265]
Nella nota di chiusura relativa alla https://github.com/italia/ansc/issues/243 si indica:

_Se il riconoscimento è effettuato da uno solo dei due genitori ma l'altro lo ha già riconosciuto, il dato dell'altro genitore è obbligatorio_

La issue https://github.com/italia/ansc/issues/243 aveva però lo scopo di evidenziare l'attuale impossibilità di gestire il caso in cui il figlio minore sia riconosciuto da uno solo dei due genitori (il padre ovvero la madre): in questi casi non può essere obbligatorio l'inserimento dell'altro genitore (che semplicemente non esiste).

**Comment by asqueglia** [comment]
Buongiorno, prendiamo in carico la segnalazione e le facciamo sapere appena corretta l'anomalia.

**Comment by asqueglia** [comment]
Buonasera con la versione 1.11.0 è stata corretta la segnalazione. 
La issue viene chiusa nel caso si prega di riaprirla.
