### ISSUE TITLE
[R009] Errore bloccante su caso 52143 atti di cittadinanza

### ISSUE THREAD

**Issue by siscomanpr** [italia/ansc#266]
Caso d'uso: 52143 - Figlio minore di chi ha acquista la cittadinanza italiana (trascrizione) - Citt_004 

Riceviamo come errori bloccanti:
- Stato estero nazioneEnte non conforme 
- Stato estero nomeNazioneEnte  non conforme 

Cosa significa "non conforme"? Cosa si aspetta? 
L'atto che viene trascritto è un'attestazione del sindaco, quindi i campi li stiamo popolando con 90 e ITALIA.
Se i 2 campi non li popoliamo ci da l'errore che segnala i campi come obbligatori.

idOperazione=1612976

Allego il json della richiesta: [req.json.txt](https://github.com/italia/ansc/files/12163346/req.json.txt)

**Comment by asqueglia** [comment]
Buongionro, provvediamo con le verifiche del caso e le faremo sapere non appena possibile.

**Comment by asqueglia** [comment]
Buongiorno, con il rilascio della versione 1.12.0 la segnalazione è stata corretta; pertanto la issue viene chiusa. In caso vengano riscontrati ulteriori problemi si prega di riaprire l'issue
