### ISSUE TITLE
[R009 validazione] chiarimenti su comportamento in fase di rivalidazione

### ISSUE THREAD

**Issue by MichelaGarzoni** [italia/ansc#269]
Buongiorno,
abbiamo un dubbio sull'errore che ci viene segnalato. I passi da noi seguiti attraverso i servizi richiamati dal gestionale sono:

1. l'usc esegue la formazione del json relativa al caso d'uso
2. viene richiesta la validazione del caso d'uso R009 ed in risposta si ottiene l'attribuzione da parte di ANSC dell'identificativo idAnsc univoco
3. l'usc si accorge di aver dimenticato di inviare un allegato: inserimento e invio dell'allegato tramite apposito servizio R001
4. validazione mediante servizio R009 al quale dove nel json precedente, all'interno dell'evento, vengono aggiunti: idAnsc (precedentemente attribuito: per poter andare in update) ed i riferimenti dell'allegato
5. validazione va a buon fine e restituisce il medesimo idAnsc
6. l'usc si accorge di aver popolato un dato (es. una data) con un valore errato e apporta la correzione. Il json che viene inviato con servizio R009 in validazione è identico a quello precedente, unica modifica presente è il dato corretto dall'usc --> otteniamo l'errore "400003 - Allegato con id 2119772 precedentemente associato ad un altro evento"

es json inviato con l'aggiunta dell'allegato (secondo invio):

{"testataRichiesta":{"idComune":3655,"idOperazioneComune":20230050000038,"dataOraRichiesta":"2023-07-26T17:00:43Z","nomeApplicativo":"ASCOT Stato Civile","versioneApplicativo":"21.99.0000","fornitoreApplicativo":"Insiel S.p.A"},"evento":{"idTipoEvento":2,**"idAnsc":"2023-1110606-20230050000038-032001",**"allegati":[{"id":**2119772**,"idTipoAllegato":32,"hashAllegato":"h5FnrWk4VQiCeJ6dx0kT1ustMMAsK0ske8wIs7FGUd8="}],"idtipocontenuto":1,"idUsecase":2101,"descrizioneCasoUso":"Decesso in abitazione o in luogo pubblico","stato":"CONFERMATO","dataformazione":"2023-07-26","ora":16,"minuto":12,"numeroatto":20230050000038,"ausilioInterprete":false,"idComuneRegistrazione":3655,"nomeComuneRegistrazione":"DUINO AURISINA-DEVIN NABREŽINA","idProvinciaRegistrazione":32,"siglaProvinciaRegistrazione":"TS","certificabile":1,"composizioneCompleta":"L'anno duemilaventitre addi' ventisei del mese di luglio alle ore sedici e minuti dodici nella Casa Comunale. Avanti a me, Garzoni Michela -, Ufficiale dello Stato Civile del Comune di Duino Aurisina-Devin Nabrežina,(1)  (2) e' comparso EEEEE EEEEE nato in Duino Aurisina li tre maggio millenovecentosessantotto, residente in San Dorligo Della Valle-Dolina il quale mi ha dichiarato quanto segue: Il giorno VENTICINQUE del mese di LUGLIO dell'anno DUEMILAVENTITRE  alle ore TREDICI e minuti DUE nel (3 bis)   è morto (4)EEEEE EEEEE (5) cittadino italiano , residente in Duino Aurisina-Devin Nabrežina nato in Trieste li ventisette maggio millenovecentocinquantadue e che era(8) coniugato con  EEEE EEEEEE. Il presente atto viene letto all' intervenuto, il quale, insieme con me, lo sottoscrive.","datiEventoMorte":{"numeroComparenti":1,"comparente1":{"cognome":"EEEEEEE","nome":"EEEEEEEEE","sesso":"M","dataNascita":"1968-05-03","idComuneNascita":3655,"nomeComuneNascita":"DUINO AURISINA-DEVIN NABREŽINA","idProvinciaNascita":32,"siglaProvinciaNascita":"TS","idStatoNascita":90,"nomeStatoNascita":"ITALIA","idComuneResidenza":"004","nomeComuneResidenza":"SAN DORLIGO DELLA VALLE-DOLINA","idProvinciaResidenza":"032","siglaProvinciaResidenza":"TS","idStatoResidenza":90,"nomeStatoResidenza":"ITALIA","idNazionalita":100,"nazionalita":"ITALIANO","flagDichiarante":true,"flagComparente":true,"flagFirmatario":true},"comparente2":null},"datiDichiarante":{"comprensione":0},"coniuge":{"cognome":"SSSSS","nome":"SSSSS","sesso":"F","dataNascita":"1962-06-25","idComuneNascita":"006","nomeComuneNascita":"TRIESTE","idProvinciaNascita":"032","siglaProvinciaNascita":"TS","idStatoNascita":90,"nomeStatoNascita":"ITALIA","idNazionalita":100,"nazionalita":"ITALIANA","flagDichiarante":false,"flagComparente":false,"flagFirmatario":false},"interprete":null,"datiDiMorte":{"idComuneMorte":3655,"nomeComuneMorte":"DUINO AURISINA-DEVIN NABREŽINA","idProvinciaMorte":32,"siglaProvinciaMorte":"TS","idStatoMorte":90,"nomeStatoMorte":"ITALIA","dataMorte":"2023-07-25","annoMorte":2023,"meseMorte":"07","giornoMorte":25,"minutoMorte":"  2"},"intestatari":[{"idSoggettoAnpr":83940418,"codiceFiscale":"SSSSSS","cognome":"SSSS","nome":"SSSSS","sesso":"M","dataNascita":"1952-05-27","idComuneNascita":"006","nomeComuneNascita":"TRIESTE","idProvinciaNascita":"032","siglaProvinciaNascita":"TS","idStatoNascita":90,"nomeStatoNascita":"ITALIA","idComuneResidenza":3655,"nomeComuneResidenza":"DUINO AURISINA-DEVIN NABREŽINA","idProvinciaResidenza":32,"siglaProvinciaResidenza":"TS","idStatoResidenza":90,"nomeStatoResidenza":"ITALIA","indirizzoResidenza":"FRAZIONE SISTIANA/SESLJAN 24/E","idstatocivile":2,"descrizionestatocivile":"Coniugato","idNazionalita":100,"nazionalita":"ITALIANO"}]}}

risposta del servizio di validazione :

{"testataRisposta":{"idComune":3655,"idOperazioneComune":"20230050000038","idOperazione":"1613592","idEsito":0},"idEvento":"1110606","idTipoEvento":"2",**"idAnsc":"2023-1110606-20230050000038-032001"**}

terzo json reinviato in validazione:

{"testataRichiesta":{"idComune":3655,"idOperazioneComune":20230050000038,"dataOraRichiesta":"2023-07-26T17:00:43Z","nomeApplicativo":"ASCOT Stato Civile","versioneApplicativo":"21.99.0000","fornitoreApplicativo":"Insiel S.p.A"},"evento":{"idTipoEvento":2,**"idAnsc":"2023-1110606-20230050000038-032001"**,"allegati":[{"id":**2119772**,"idTipoAllegato":32,"hashAllegato":"h5FnrWk4VQiCeJ6dx0kT1ustMMAsK0ske8wIs7FGUd8="}],"idtipocontenuto":1,"idUsecase":2101,"descrizioneCasoUso":"Decesso in abitazione o in luogo pubblico","stato":"CONFERMATO","dataformazione":"2023-07-26","ora":16,"minuto":12,"numeroatto":20230050000038,"ausilioInterprete":false,"idComuneRegistrazione":3655,"nomeComuneRegistrazione":"DUINO AURISINA-DEVIN NABREŽINA","idProvinciaRegistrazione":32,"siglaProvinciaRegistrazione":"TS","certificabile":1,"composizioneCompleta":"L'anno duemilaventitre addi' ventisei del mese di luglio alle ore sedici e minuti dodici nella Casa Comunale. Avanti a me, Garzoni Michela -, Ufficiale dello Stato Civile del Comune di Duino Aurisina-Devin Nabrežina,(1)  (2) e' comparso EEEEEE EEEEEE nato in Duino Aurisina li tre maggio millenovecentosessantotto, residente in San Dorligo Della Valle-Dolina il quale mi ha dichiarato quanto segue: Il giorno VENTICINQUE del mese di LUGLIO dell'anno DUEMILAVENTITRE  alle ore TREDICI e minuti DUE nel (3 bis)   è morto (4)EEEEEE EEEEE (5) cittadino italiano , residente in Duino Aurisina-Devin Nabrežina nato in Trieste li ventisette maggio millenovecentocinquantadue e che era(8) coniugato con  EEEEE EEEEE. Il presente atto viene letto all' intervenuto, il quale, insieme con me, lo sottoscrive.","datiEventoMorte":{"numeroComparenti":1,"comparente1":{"cognome":"EEEEEEE","nome":"EEEEEEEE","sesso":"M","dataNascita":"1968-05-03","idComuneNascita":3655,"nomeComuneNascita":"DUINO AURISINA-DEVIN NABREŽINA","idProvinciaNascita":32,"siglaProvinciaNascita":"TS","idStatoNascita":90,"nomeStatoNascita":"ITALIA","idComuneResidenza":"004","nomeComuneResidenza":"SAN DORLIGO DELLA VALLE-DOLINA","idProvinciaResidenza":"032","siglaProvinciaResidenza":"TS","idStatoResidenza":90,"nomeStatoResidenza":"ITALIA","idNazionalita":100,"nazionalita":"ITALIANO","flagDichiarante":true,"flagComparente":true,"flagFirmatario":true},"comparente2":null},"datiDichiarante":{"comprensione":0},"coniuge":{"cognome":"SSSSS","nome":"SSSSSSS","sesso":"F","dataNascita":"1962-06-25","idComuneNascita":"006","nomeComuneNascita":"TRIESTE","idProvinciaNascita":"032","siglaProvinciaNascita":"TS","idStatoNascita":90,"nomeStatoNascita":"ITALIA","idNazionalita":100,"nazionalita":"ITALIANA","flagDichiarante":false,"flagComparente":false,"flagFirmatario":false},"interprete":null,"datiDiMorte":{"idComuneMorte":3655,"nomeComuneMorte":"DUINO AURISINA-DEVIN NABREŽINA","idProvinciaMorte":32,"siglaProvinciaMorte":"TS","idStatoMorte":90,"nomeStatoMorte":"ITALIA","dataMorte":"2023-07-25","annoMorte":2023,"meseMorte":"07","giornoMorte":25,"minutoMorte":"  2"},"intestatari":[{"idSoggettoAnpr":83940418,"codiceFiscale":"SSSSSSS","cognome":"SSSSS","nome":"SSSSS","sesso":"M","dataNascita":"1952-05-27","idComuneNascita":"006","nomeComuneNascita":"TRIESTE","idProvinciaNascita":"032","siglaProvinciaNascita":"TS","idStatoNascita":90,"nomeStatoNascita":"ITALIA","idComuneResidenza":3655,"nomeComuneResidenza":"DUINO AURISINA-DEVIN NABREŽINA","idProvinciaResidenza":32,"siglaProvinciaResidenza":"TS","idStatoResidenza":90,"nomeStatoResidenza":"ITALIA","indirizzoResidenza":"FRAZIONE SISTIANA/SESLJAN 24/E","idstatocivile":2,"descrizionestatocivile":"Coniugato","idNazionalita":100,"nazionalita":"ITALIANO"}]}}

risposta del servizio:

"400003 - Allegato con id 2119772 precedentemente associato ad un altro evento"

Utilizzando il servizio R005- consultazione ANSC con idAnsc dell'atto abbiamo però che l'allegato risulta correttamente abbinato all'evento:
{
    "testataRisposta": {
        "idComune": 3655,
        "idOperazioneComune": "2534",
        "idOperazione": "1613607",
        "idEsito": 0
    },
    "modelEventoDTO": [
        {
            "id": 1110606,
            **"idAnsc": "2023-1110606-20230050000038-032001"**,
            "idTipoEvento": "2",
            "idtipocontenuto": "1",
            "idUsecase": "2101",
            "descrizioneCasoUso": "Decesso in abitazione o in luogo pubblico",
            "stato": "CONFERMATO",
            "dataformazione": "2023-07-26",
            "ora": "16",
            "minuto": "12",
            "annoAtto": "2023",
            "numeroatto": "20230050000038",
            "ausilioInterprete": "false",
            "idComuneRegistrazione": "3655",
            "nomeComuneRegistrazione": "DUINO AURISINA-DEVIN NABREŽINA",
            "idProvinciaRegistrazione": "32",
            "siglaProvinciaRegistrazione": "TS",
            "certificabile": "1",
            **"allegati": [
                {
                    "id": 2119772,
                    "idTipoAllegato": 32,
                    "hashAllegato": "h5FnrWk4VQiCeJ6dx0kT1ustMMAsK0ske8wIs7FGUd8=",
                    "descrizione": "Certificato necroscopico",
                    "idStatoAllegato": 3
                }
            ]**,
            "intestatari": [
                {
                    "id": "2119785",
                    "codiceFiscale": "SSSSSS",
                    "cognome": "SSSSS",
                    "nome": "SSSSSS",
                    "sesso": "M",
                    "dataNascita": "1952-05-27",
                    "idComuneNascita": "006",
                    "nomeComuneNascita": "TRIESTE",
                    "idProvinciaNascita": "032",
                    "siglaProvinciaNascita": "TS",
                    "idStatoNascita": "90",
                    "nomeStatoNascita": "ITALIA",
                    "idComuneResidenza": "3655",
                    "nomeComuneResidenza": "DUINO AURISINA-DEVIN NABREŽINA",
                    "idProvinciaResidenza": "32",
                    "siglaProvinciaResidenza": "TS",
                    "idStatoResidenza": "90",
                    "nomeStatoResidenza": "ITALIA",
                    "indirizzoResidenza": "FRAZIONE SISTIANA/SESLJAN 24/E",
                    "idstatocivile": "2",
                    "descrizionestatocivile": "Coniugato",
                    "idNazionalita": "100",
                    "nazionalita": "ITALIANO",
                    "documentoRiconoscimento": {}
                }
            ],
            "coniuge": {
                "cognome": "DDDDDDD",
                "nome": "DDDDDD",
                "sesso": "F",
                "dataNascita": "1962-06-25",
                "idComuneNascita": "006",
                "nomeComuneNascita": "TRIESTE",
                "idProvinciaNascita": "032",
                "siglaProvinciaNascita": "TS",
                "idStatoNascita": "90",
                "nomeStatoNascita": "ITALIA",
                "idNazionalita": "100",
                "nazionalita": "ITALIANA",
                "flagDichiarante": false,
                "flagComparente": false,
                "flagFirmatario": false,
                "documentoRiconoscimento": {}
            },
            "datiDichiarante": {
                "comprensione": "0"
            },
            "datiDiMorte": {
                "idComuneMorte": "3655",
                "nomeComuneMorte": "DUINO AURISINA-DEVIN NABREŽINA",
                "idProvinciaMorte": "32",
                "siglaProvinciaMorte": "TS",
                "idStatoMorte": "90",
                "nomeStatoMorte": "ITALIA",
                "dataMorte": "2023-07-25",
                "annoMorte": "2023",
                "meseMorte": "07",
                "giornoMorte": "25",
                "minutoMorte": "  2"
            },
            "datiEventoMorte": {
                "numeroComparenti": "1",
                "comparente1": {
                    "cognome": "FFFFFFF",
                    "nome": "FFFFFF",
                    "sesso": "M",
                    "dataNascita": "1968-05-03",
                    "idComuneNascita": "3655",
                    "nomeComuneNascita": "DUINO AURISINA-DEVIN NABREŽINA",
                    "idProvinciaNascita": "32",
                    "siglaProvinciaNascita": "TS",
                    "idStatoNascita": "90",
                    "nomeStatoNascita": "ITALIA",
                    "idComuneResidenza": "004",
                    "nomeComuneResidenza": "SAN DORLIGO DELLA VALLE-DOLINA",
                    "idProvinciaResidenza": "032",
                    "siglaProvinciaResidenza": "TS",
                    "idStatoResidenza": "90",
                    "nomeStatoResidenza": "ITALIA",
                    "idNazionalita": "100",
                    "nazionalita": "ITALIANO",
                    "flagDichiarante": true,
                    "flagComparente": true,
                    "flagFirmatario": true,
                    "documentoRiconoscimento": {}
                }
            },
            "composizioneCompleta": "L'anno duemilaventitre addi' ventisei del mese di luglio alle ore sedici e minuti dodici nella Casa Comunale. Avanti a me, Garzoni Michela -, Ufficiale dello Stato Civile del Comune di Duino Aurisina-Devin Nabrežina,(1)  (2) e' comparso EEEE EEEEE nato in Duino Aurisina li tre maggio millenovecentosessantotto, residente in San Dorligo Della Valle-Dolina il quale mi ha dichiarato quanto segue: Il giorno VENTICINQUE del mese di LUGLIO dell'anno DUEMILAVENTITRE  alle ore TREDICI e minuti DUE nel (3 bis)   è morto (4)WWWWW EEEEEE (5) cittadino italiano , residente in Duino Aurisina-Devin Nabrežina nato in Trieste li ventisette maggio millenovecentocinquantadue e che era(8) coniugato con  EEEE EEEEE . Il presente atto viene letto all' intervenuto, il quale, insieme con me, lo sottoscrive.",
            "datains": "2023-07-26T16:15:28.217175",
            "dataultimoagg": "2023-07-26T17:06:47.014103"
        }
    ],
    "datiPaginazione": {
        "numPagina": 1,
        "numRecordPagina": 30,
        "numRecordTotali": 1
    }
}

**Comment by amusarra** [comment]
Buongiorno @MichelaGarzoni 
Abbiamo preso in carico la segnalazione.

Cordiali Saluti.
Supporto ANSC.

**Comment by asqueglia** [comment]
Buonasera con la versione 1.11.0 è stata corretta la segnalazione. 
La issue viene chiusa nel caso si prega di riaprirla.
