### ISSUE TITLE
[R001] - Upload Allegato - Problemi nel nome file

### ISSUE THREAD

**Issue by LoreL56** [italia/ansc#270]
Buongiorno,
per quanto riguarda l'invio di allegati ci siamo accorti che la presenza del carattere '-' nel nome del file genera l'errore:
"Attenzione, ci sono stati degli errori: 400003 : Nome del File non corretto"

Vorremmo escludere i caratteri o le sequenze non ammissibili a priori.
Ci sapreste dire se ce ne sono altri (oltre a '-') ed in caso quali sono?

Un esempio di test che genera errore è:

Ambiente pre-prod
idOperazione = 1613830
Data test: 27/07/2023

**Comment by amusarra** [comment]
Buongiorno @LoreL56 
Il pattern per il nome del file è il seguente `^[ _a-zA-Z0-9_]*$`
Se non ci sono ulteriori dubbi e/o chiarimenti, vi chiederei di chiedere la issue.

Cordiali Saluti.
Supporto ANSC.

**Comment by LoreL56** [comment]
Grazie mille della risposta.
Non ci sono ulteriori dubbi.
