### ISSUE TITLE
Titolo: [R009] assistenzaMinori sempre obbligatoria per caso d'uso Matr_001.

### ISSUE THREAD

**Issue by gcuci** [italia/ansc#271]
buonasera,

con l'aggiunta della nuova proprietà, assistenzaMinori (classe ModelAssistenzaMinori), dalla versione 1.10.0, non riusciamo più a validare i Matrimoni (lo abbiamo verificato per il caso d'uso Matr_001), per i quali non è prevista l'assistezaMinori, in quanto il servizio restituisce sempre l'errore di dati obbligatori mancanti.

Per un'esempio di invocazione del servizio effettuata nel pomeriggio, potete far riferimento all'operazione con id: 1614096.

Di seguito, parte della Response:

{
    "testataRisposta": {
        "idComune": 595,
        "idOperazioneComune": "2954",
        "idOperazione": "1614096",
        "idEsito": 1
    },
    "errors": [
        {
            "code": "400003",
            "severity": "E",
            "text": "Il campo evento.datiEventoMatrimonio.regimePatrimoniale.assistenzaMinori[0].assistente[0].nome nella sezione Padre Sposo è obbligatorio"
        },
        {
            "code": "400003",
            "severity": "E",
            "text": "Il campo evento.datiEventoMatrimonio.regimePatrimoniale.assistenzaMinori[0].assistente[0].sesso nella sezione Padre Sposo è obbligatorio"
        },
        {
            "code": "400003",
            "severity": "E",
            "text": "Il campo evento.datiEventoMatrimonio.regimePatrimoniale.assistenzaMinori[0].assistente[0].dataNascita nella sezione Padre Sposo è obbligatorio"
        },
		
		....
		....
        {
            "code": "400003",
            "severity": "E",
            "text": "Il campo evento.datiEventoMatrimonio.regimePatrimoniale.assistenzaMinori[1].assistente[0].flagFirmatario nella sezione Curatore Sposa è obbligatorio"
        }
    ]
}

In attesa di un riscontro,

cordiali saluti.

**Comment by asqueglia** [comment]
Buongiorno abbiamo preso in carico la problematica segnalata. Non appena possibile le faremo sapere.

**Comment by asqueglia** [comment]
Buonasera con la versione 1.11.0 è stata corretta la segnalazione. E' necessario invocare il servizio specificando idVersion = 100002 come da documentazione.
La issue viene chiusa nel caso si prega di riaprirla.
