### ISSUE TITLE
[R012] Servizio di pooling: decodifica degli stati della presa visione, mancante.

### ISSUE THREAD

**Issue by gcuci** [italia/ansc#272]
buonasera,

il servizio di pooling di controllo della presa visione, associata al processo di firma di un dichiarante, restituisce un idState, che in base ai campi valorizzati nella Request, rappresenta lo stato dell'evento, o della presa visione.

Nel caso degli stati della presa visione, non abbiamo una tabella di decodifica di riferimento.

Vi riporto, in particolare, un esempio di richiesta in cui ci viene restituito un idState = 0, avendo passato al servizio, un idPresaVisione, associato ad un precedente invio-email, per il quale non si è poi proceduto all'effettiva presa visione. Lo stato dovrebbe quindi essere scaduto.

Questa è la Request:

{
  "idPresaVisione": "2111116",
  "idEvento": "952948",
  "testataRichiesta": {
    "idComune": 3913,
    "idOperazioneComune": "3",
    "dataOraRichiesta": "2023-07-20T14:42:38.739+02:00",
    "nomeApplicativo": "akropolis",
    "versioneApplicativo": "20.1",
    "fornitoreApplicativo": "datamanagementitaliaspa"
  },
  "datiPaginazione": {
    "numPagina": 1,
    "numRecordPagina": 10,
    "numRecordTotali": 0
  }
}

e questa la Response:

{
  "idState": 0,
  "esito": {
    "codice": "200",
    "descrizione": "Ok"
  },
  "testataRisposta": {
    "idComune": 3913,
    "idOperazioneComune": "3",
    "idOperazione": "1611151",
    "idEsito": 0
  }
}

Dalla seconda si evince l'idOperazione (1611151).

In attesa di riscontro,

cordiali saluti.

**Comment by amusarra** [comment]
Buongiorno @gcuci 
Lo stato della presa visione può essere:

- 0 da visionare
- 1 visionato
- 2 annullato

Effettivamente lo stato scaduto non è stato gestito come risposta.

Abbiamo preso in carico la segnalazione.

Cordiali Saluti.
Supporto ANSC.

**Comment by asqueglia** [comment]
Buongiorno, è stata appena rilasciata la versione 1.13.0 che corregge il bug segnalato. Chiudiamo pertanto la issue; in caso di ulteriori problematiche si prega di aprirne una nuova.
