### ISSUE TITLE
Numero atto per statistiche istat

### ISSUE THREAD

**Issue by antonioluberto** [italia/ansc#273]
Con il passaggio in ANSC, gli atti prodotti dal Comune avranno “numero” rappresentato dalla strniga:
<anno-n°nazionale-n°comunale-codIstat>
Le rilevazioni statistiche mensili
D3
SC6-12.SD
D3U
D4/D4Bis
dovranno continuare ad essere trasmesse dalle applicazioni locali mediante tracciato record che prevede, in tutti casi, l’obbligatorietà del campo corrispondente al “numero” atto nella formattazione stringa (5).
E’ prevista modifica dei tracciati Istat di riferimento?
Dovremo limitarci a riportare nel campo destinato a contenere il “numero” atto il solo n°comunale?
Altro?

**Comment by amusarra** [comment]
Buongiorno @antonioluberto 
Per la questione dovremo sentire il Dipartimento (DTD).
Non appena riceveremo risposta le risponderemo.

Cordiali Saluti.
Supporto ANSC.

**Comment by asqueglia** [comment]
Sull'argomento è stata condivisa opportuna documentazione sul portale pubblico di ANPR  e in riferimento alla issue #526 . Pertanto chiudiamo la issue. In caso di ulteriori dubbi o segnalzioni òla preghiamo di aprirne una altra dedicata.
