### ISSUE TITLE
Servizio R005 -- Ricerca di un atto di stato civile

### ISSUE THREAD

**Issue by LuigiManf** [italia/ansc#274]
Buongiorno,
abbiamo fatto  la ricerca per evento considerando tra i filtri anche l'IDComunale. L'abbiamo interpretato dalla documentazione come Comune di registrazione dell'atto. Dai risultati però sembra che venga filtrato il numero atto..
Allego payload.  

Esiste una modalità diretta attraverso il servizio R005 di filtrare il comune di registrazione dell'atto?
![RicercaIdComunale](https://github.com/italia/ansc/assets/141017754/0a1ee3be-6cfb-4f13-9655-1b1025d5f011)

**Comment by amusarra** [comment]
Buongiorno @LuigiManf 
Il comportamento del servizio è corretto, ovvero, il valore dell'attributo `idComunale` deve essere il numero comunale.
La descrizione del servizio riporta purtroppo l'informazione errata, a cui faremo una revisione in uno dei prossimi rilasci.

Cordiali Saluti.
Supporto ANSC.

**Comment by asqueglia** [comment]
Buongiorno, con il rilascio della versione 1.12.0 la segnalazione è stata corretta; pertanto la issue viene chiusa. In caso vengano riscontrati ulteriori problemi si prega di riaprire l'issue
