### ISSUE TITLE
[ws R002] Certificazione - Errore: msg. "Soggetto richiedente non specificato correttamente"

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/ansc#275]
ambiente PRE-PROD - comune di FAENZA (idComune 3743)

in presenza di soggetto "richiedente" nato all'estero, la richiesta di certificazione restituisce l'errore in oggetto.
la percezione è che il problema sia collegato ai campi idComuneNascita e idProvinciaNascita che non vengono valorizzati.
diversamente, in caso di richiedente nato in italia (con tutti i campi valorizzati), la richiesta di certificazione va a buon fine.

potete verificare la richiesta con idOperazioneAnsc 1615421

grazie
Alessandro Monopoli ADS

**Comment by amusarra** [comment]
Buongiorno @AMonopoliADS 
Abbiamo preso in carico la segnalazione.

Cordiali Saluti.
Supporto ANSC.

**Comment by asqueglia** [comment]
Buongiorno, con il rilascio della versione 1.12.0 la segnalazione è stata corretta; pertanto la issue viene chiusa. In caso vengano riscontrati ulteriori problemi si prega di riaprire l'issue
