### ISSUE TITLE
[R009] datiAnnotazione non viene più generato come array con la versione ANSC 1.10.1.

### ISSUE THREAD

**Issue by gcuci** [italia/ansc#276]
buongiorno,

con la versione 1.10.1, è stato corretto un refuso sulla proprietà datiAnnotazione, come indicato nel relativo Changelog.

C'è però un problema nel https://italia.github.io/ansc/docs/openapi/model_evento.yaml#/components/schemas/ModelEvento dove datiAnnotazioni è definito come array, ma il successivo $ref allo stesso livello, fa si che la definizione venga ignorata. Di conseguenza, generando il client, la proprietà non viene definita come array, ma direttamente come ModelDatiAnnotazione, impedendo di poter inviare più di un'Annotazione Contestuale.

Potete verificare? 

In attesa di riscontro,

cordiali saluti.

**Comment by amusarra** [comment]
@gcuci si abbiamo verificato e si tratta di un errore di cui abbiamo preso in carico la gestione.

<img width="1728" alt="image" src="https://github.com/italia/ansc/assets/708110/f87b091f-02c2-4694-b1fb-091f677820b0">

In attesa del rilascio della fix, potreste apportare la correzione così come indicato a seguire

```
        datiAnnotazione:
          description: Dati delle annotazioni contestuali 
          type: array
          items:
          	$ref: '#/components/schemas/ModelDatiAnnotazione'
```
Source Code 1 - Correzione indentazione elemento items della definizione ModelEvento

**Comment by amusarra** [comment]
@gcuci con la release 1.10.2 è stata risolta la issue.

Cordiali Saluti.
Supporto ANSC.
