### ISSUE TITLE
Servizio R005 -- dati di risposta nel ModelSoggetto

### ISSUE THREAD

**Issue by LuigiManf** [italia/ansc#279]
Buongiorno a seguito di una ricerca per soggetto, abbiamo notato che nella risposta, la descrizione del comiune di nascita e della provincia è sempre a Null. Vorremmo evitare di fare delle decodifiche per ottenere  queste informazioni. E' possibile reperirle dalla risposta?
Cordiali Saluti

Allego il payload di prova:

payload": {
        "testataRisposta": {
            "idComune": 5646,
            "idOperazioneComune": "APP2022032210000",
            "idOperazione": "1615760",
            "idEsito": 0
        },
        "datiPaginazione": {
            "numPagina": 1,
            "numRecordPagina": 10,
            "numRecordTotali": 93
        },
        "errors": null,
        "infos": null,
        "success": null,
        "warnings": null,
        "soggetti": [
            {
                "id": "1886844",
                "idsoggettoanpr": null,
                "codiceFiscale": null,
                "cognome": "ROBA",
                "nome": "MASSIMO",
                "sesso": "M",
                "descrizioneSesso": null,
                "dataNascita": "1955-12-06T23:00:00.000+00:00",
                "idComuneNascita": "16449",
                "nomeComuneNascita": null,
                "idProvinciaNascita": null,
                "siglaProvinciaNascita": null,
                "idStatoNascita": "100",
                "nomeStatoNascita": null,
                "idComuneResidenza": null,
                "nomeComuneResidenza": null,
                "idProvinciaResidenza": null,
                "siglaProvinciaResidenza": null,
                "idStatoResidenza": null,
                "nomeStatoResidenza": null,
                "indirizzoResidenza": null,
                "idstatocivile": null,
                "descrizionestatocivile": null,
                "tipoImpedimento": null,
                "idNazionalita": null,
                "nazionalita": null,
                "note": null,
                "flagDichiarante": null,
                "flagComparente": null,
                "flagFirmatario": null,
                "documentoRiconoscimento": null,
                "recapito": null
            },
            {
                "id": "1886852",
                "idsoggettoanpr": null,
                "codiceFiscale": null,
                "cognome": "ROBA",
                "nome": "MASSIMO",
                "sesso": "M",
                "descrizioneSesso": null,
                "dataNascita": "1955-12-06T23:00:00.000+00:00",
                "idComuneNascita": "16449",
                "nomeComuneNascita": null,
                "idProvinciaNascita": null,
                "siglaProvinciaNascita": null,
                "idStatoNascita": "100",
                "nomeStatoNascita": null,
                "idComuneResidenza": null,
                "nomeComuneResidenza": null,
                "idProvinciaResidenza": null,
                "siglaProvinciaResidenza": null,
                "idStatoResidenza": null,
                "nomeStatoResidenza": null,
                "indirizzoResidenza": null,
                "idstatocivile": null,
                "descrizionestatocivile": null,
                "tipoImpedimento": null,
                "idNazionalita": null,

**Comment by amusarra** [comment]
Buongiorno @LuigiManf 
La versione attuale dei servizi non prevede la funzionalità richiesta.

Cordiali Saluti.
Supporto ANSC.
