### ISSUE TITLE
[R012] Problema richiesta invio email per firma digitale

### ISSUE THREAD

**Issue by RaffaeleReale** [italia/ansc#28]
Invoncando il servizio in oggetto in ambiente di **preproduzione**
https://anscservicepre.anpr.interno.it/services/service/firma/firmadichiarante/invio-email/1

ottengo
`		"codice": "400002",
		"descrizione": "Dati in ingresso non completi"
`

Il json della richieta è

```json
{
	"testataRichiesta": {
		"idComune": 10288,
		"idOperazioneComune": 11,
		"dataOraRichiesta": "2023-03-20 14:21:05",
		"nomeApplicativo": "PEDemografici",
		"versioneApplicativo": "1",
		"fornitoreApplicativo": "Kibernetes srl"
	},
	"FirmaDichiaranteOnlineInvioEmailRequest": {
		"emailDichiarante": "rreale@kibernetes-rc.it",
		"idEvento": "950327",
		"idAnsc": "2023-950327-19-102044",
		"firmatario": {
			"codiceFiscale": "OMESSO PER SEGNALAZIONE",
			"cognome": "OMESSO PER SEGNALAZIONE",
			"nome": "OMESSO PER SEGNALAZIONE",
			"sesso": "M",
			"dataNascita": "1973-08-17",
			"idComuneNascita": "6024",
			"nomeComuneNascita": "VIBO VALENTIA",
			"idProvinciaNascita": "79",
			"siglaProvinciaNascita": "CZ",
			"idStatoNascita": "90",
			"nomeStatoNascita": "ITALIA",
			"idComuneResidenza": "10288",
			"nomeComuneResidenza": "TROPEA",
			"idProvinciaResidenza": "102",
			"siglaProvinciaResidenza": "VV",
			"idStatoResidenza": "90",
			"nomeStatoResidenza": "ITALIA",
			"indirizzoResidenza": "OMESSO PER SEGNALAZIONE",
			"idstatocivile": "2",
			"descrizionestatocivile": "CONIUGATO",
			"idNazionalita": "90",
			"nazionalita": "ITALIANA",
			"flagDichiarante": true,
			"flagComparente": true,
			"flagFirmatario": true
		}
	}
}
```

ottengo come risposta

```json
{
	"errors": [
		{
			"code": "400002",
			"severity": "E",
			"text": "Dati in ingresso non completi"
		}
	],
	"esito": {
		"codice": "400002",
		"descrizione": "Dati in ingresso non completi"
	},
	"testataRisposta": {
		"idComune": 10288,
		"idEsito": 1,
		"idOperazioneComune": "11"
	}
}
```

**Comment by RaffaeleReale** [comment]
Ho risolto impostato nel firmatario solo **Cognome** e **Nome**, (quindi **non** il **modelSoggeto** come da documentazione)

**Comment by MichelaGarzoni** [comment]
Ho eseguito lo stesso test con solo Cognome e Nome inseriti nella parte firmatario ma l'errore persiste: il codice json inviato nella request è il seguente: 
{
"testataRichiesta":{
"idComune":3655
,"idOperazioneComune":"2534"
,"dataOraRichiesta":"2023-03-13T11:09:23Z"
,"nomeApplicativo":"Stato Civile"
,"versioneApplicativo":"21.99.0000"
,"fornitoreApplicativo":"Fornitore"
},
"emailDichiarate":"nome.cognome@indirizzo.it",
"idEvento":"950289",
"idAnsc":"2023-950289-202300500006-032001",
"firmatario":{
    "cognome":"Cognome",
    "nome":"Nome"
    }
}

dove idEvento ed idAnsc sono corretti. Qual'è l'errore? Ho provato ad inserire diversi campi del modelSoggetto quale codiceFiscale o altri campi identificativi del firmatario ma l'errore persiste:

{
    "errors": [
        {
            "code": "400002",
            "severity": "E",
            "text": "Dati in ingresso non completi"
        }
    ],
    "esito": {
        "codice": "400002",
        "descrizione": "Dati in ingresso non completi"
    },
    "testataRisposta": {
        "idComune": 3655,
        "idEsito": 1,
        "idOperazioneComune": "2534"
    }
}

**Comment by amusarra** [comment]
> Ho risolto impostato nel firmatario solo **Cognome** e **Nome**, (quindi **non** il **modelSoggeto** come da documentazione)

Salve 

> Ho risolto impostato nel firmatario solo **Cognome** e **Nome**, (quindi **non** il **modelSoggeto** come da documentazione)

Salve @RaffaeleReale 
Quella a seguire è un esempio di risposta che segue l'OpenAPI https://github.com/italia/ansc/blob/main/docs/openapi/R012_firma_dichiarante_elettronica.yaml#L149 
La proprietà è firmatario è di tipo ModelSogetto e infatti contiene gli attributi Nome e Cognome che sono gli unici richiesti (al momento).

```
{
    "testataRichiesta": {
        "idComune": {{idComune}},
        "idOperazioneComune": "APP2022032210000",
        "dataOraRichiesta": "{{dataOraRichiesta}}",
        "nomeApplicativo": "{{nomeApplicativo}}",
        "versioneApplicativo": "{{versioneApplicativo}}",
        "fornitoreApplicativo": "{{fornitoreApplicativo}}"
    },
    "datiPaginazione": {
        "numPagina": 2,
        "numRecordPagina": 10,
        "numRecordTotali": 570
    },
    "emailDichiarante": "{{email}}",
    "idEvento": "{{idEventoTestFlusso01}}",
    "idAnsc": "{{idAnscTestFlusso01}}",
    "firmatario": {
        "nome": "{{nome}}",
        "cognome": "{{cognome}}"
    }
}
```
Payload 1 - Richiesta per il servizio di Firma per presa visione R012

A seguire l'esempio di risposta.

```
{
    "esito": {
        "codice": "200",
        "descrizione": "Ok"
    },
    "testataRisposta": {
        "idComune": 1000000,
        "idEsito": 0,
        "idOperazioneComune": "APP2022032210000"
    },
    "idPresaVisione": "1859241"
}
```
Payload 2 - Risposta del servizio di Firma per Presa Visione R012.

Stiamo lavorando per specificare sul documento delle OpenAPI circa l'obbligatorietà degli attributi.

**Comment by amusarra** [comment]
> 950289



> Ho eseguito lo stesso test con solo Cognome e Nome inseriti nella parte firmatario ma l'errore persiste: il codice json inviato nella request è il seguente: { "testataRichiesta":{ "idComune":3655 ,"idOperazioneComune":"2534" ,"dataOraRichiesta":"2023-03-13T11:09:23Z" ,"nomeApplicativo":"Stato Civile" ,"versioneApplicativo":"21.99.0000" ,"fornitoreApplicativo":"Fornitore" }, "emailDichiarate":"[nome.cognome@indirizzo.it](mailto:nome.cognome@indirizzo.it)", "idEvento":"950289", "idAnsc":"2023-950289-202300500006-032001", "firmatario":{ "cognome":"Cognome", "nome":"Nome" } }
> 
> dove idEvento ed idAnsc sono corretti. Qual'è l'errore? Ho provato ad inserire diversi campi del modelSoggetto quale codiceFiscale o altri campi identificativi del firmatario ma l'errore persiste:
> 
> { "errors": [ { "code": "400002", "severity": "E", "text": "Dati in ingresso non completi" } ], "esito": { "codice": "400002", "descrizione": "Dati in ingresso non completi" }, "testataRisposta": { "idComune": 3655, "idEsito": 1, "idOperazioneComune": "2534" } }

Salve @MichelaGarzoni 
Da analisi condotte al momento, l'evento in questione risulta già nello stato 4, ovvero, firmato dal dichiarante.
Le chiedo di fare un test con un nuovo evento.

Saluti.

**Comment by MichelaGarzoni** [comment]
Grazie!
Allora procedo con un nuovo evento in modo da testare il giro completo, Per sapere lo stato dell'atto posso usare il servizio R012 /firmadichiarante/pooling-statoatto o questo servizio indica solo la presa visione dell'atto ma non lo stato della firma dell'atto? cosa dovrei inserire all'interno del parametro "idPresaVisione" ?

**Comment by amusarra** [comment]
Salve @MichelaGarzoni 
Si esatto, occorre usare il servizio indicato che risponderà con lo stato dell'evento. A seguire un esempio di risposta del servizio.

```
{
    "esito": {
        "codice": "200",
        "descrizione": "Ok"
    },
    "testataRisposta": {
        "idComune": 1000000,
        "idEsito": 0,
        "idOperazione": "1014621",
        "idOperazioneComune": "APP2022032210000"
    },
    "idStateEvento": 4
}
```
Payload 1 - Risposta del servizio {{R012}}/firmadichiarante/pooling-statoatto/1

Il valore dell'attributo `idPresaVisione` è quello restituito dal servizio `{{R012}}/firmadichiarante/invio-email/1`

Saluti.
Supporto ANSC

**Comment by MichelaGarzoni** [comment]
Ok, grazie mille, ora mi è più chiaro il percorso,
saluti,
Michela
