### ISSUE TITLE
[ws R001] Upload - Errore non meglio specificato

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/ansc#280]
ambiente: PRE-PROD
comune: VALEGGIO SUL MINCIO (idComune 10420)
end-point: https://anscservicepre.anpr.interno.it/services/service/doc/allegato/upload/1

capita in maniera apparentemente casuale la situazione per cui a fronte di un invio di documento in upload (ws R001), il servizio risponda con un generico errore che contiene solamente l'endpoint.

il caso che segnaliamo (l'ultimo che ci è capitato) è di un allegato per atto di cittadinanza, inviato con idOperazioneComune 2023000124.
nella response troviamo solo: "operation: /services/service/doc/allegato/upload/1</operation>"

questo succede per invii successivi, fino a che ad un certo punto l'allegato viene accettato e l'operazione va a buon fine.

riuscite a verificare e capire cosa fa scattare l'errore?

grazie
Alessandro Monopoli ADS

**Comment by amusarra** [comment]
Buongiorno @AMonopoliADS, dai nostri controlli risulta che per l'operazione indicata il servizio ha risposto correttamente. Il payload è corretto dal punto di vista formale e la dimensione dell'allegato è conforme ai limiti.

Abbiamo provato a rifare la richiesta di upload in successione utilizzando il vostro payload senza riscontrare problemi da voi indicati.

Nel caso in cui dovreste riscontrare ulteriori problemi, segnalatelo in questa issue per attivare dei controlli anche sul resto dei componenti dell'infrastruttura.


![image](https://github.com/italia/ansc/assets/708110/e4fc8df5-3540-4ca7-9a67-5db5afaf1542)

Cordiali Saluti.
Supporto ANSC.

**Comment by AMonopoliADS** [comment]
La comunicazione 2023000124 (idOperazioneComune) dopo svariati tentativi è andata a buon fine, ma nella cronologia degli invii divreste trovare anche gli errori a cui mi riferisco.

In ogni caso, appena ricapita vi segnalo il nuovo caso senza tentare di finalizzarlo con nuovi tentativi.

Grazie

Inviato da IBM Verse


   Antonio Musarra --- Re: [italia/ansc] [ws R001] Upload - Errore non meglio specificato (Issue #280) --- 
    Da:"Antonio Musarra" ***@***.***>A:"italia/ansc" ***@***.***>Cc:"AMonopoliADS" ***@***.***>, "Mention" ***@***.***>Data:ven, 04 ago 2023 10:07Oggetto:Re: [italia/ansc] [ws R001] Upload - Errore non meglio specificato (Issue #280)
  
  Buongiorno @AMonopoliADS, dai nostri controlli risulta che per l'operazione indicata il servizio ha risposto correttamente. Il payload è corretto dal punto di vista formale e la dimensione dell'allegato è conforme ai limiti. Abbiamo provato a rifare la richiesta di upload in successione utilizzando il vostro payload senza riscontrare problemi da voi indicati. Nel caso in cui dovreste riscontrare ulteriori problemi, segnalatelo in questa issue per attivare dei controlli anche sul resto dei componenti dell'infrastruttura.  Cordiali Saluti.
  Supporto ANSC. —
 Reply to this email directly, view it on GitHub, or unsubscribe.
 You are receiving this because you were mentioned.Message ID: ***@***.***>  

Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto.

**Comment by AMonopoliADS** [comment]
salve @amusarra 

come d'accordo segnalo la lista di alcune comunicazioni dove si è manifestato lo stesso problema segnalato inizialmente con questa issue...

- idOperazioneComune: 2023000135 (dataOraRichiesta: 2023-09-11T08:26:34)
endpoint: https://anscservicepre.anpr.interno.it/services/service/doc/allegato/upload/1

- idOperazioneComune: 2023000138 (dataOraRichiesta: 2023-09-11T12:07:34)
endpoint: https://anscservicepre.anpr.interno.it/services/service/doc/allegato/upload/1

- idOperazioneComune: 2023000136 (dataOraRichiesta: 2023-09-11T11:57:05)
endpoint: https://anscservicepre.anpr.interno.it/services/service/val/validazione/evento/1

- idOperazioneComune: 2023000137 (dataOraRichiesta: 2023-09-11T11:57:58)
endpoint: https://anscservicepre.anpr.interno.it/services/service/val/validazione/evento/1

grazie
Alessandro

**Comment by amusarra** [comment]
Salve @AMonopoliADS 
Potreste indicarci l’indirizzo IP con cui uscite?

Grazie.
Supporto ANSC.

**Comment by amusarra** [comment]
Buongiorno @AMonopoliADS 
Abbiamo ricevuto l'indirizzo IP per cui è stato richiesto il tracciamento a fini delle operazioni di debug delle richieste.
È possibile che sia necessario rifare delle richieste. Vi faremo sapere qualora sia necessario.

Cordiali Saluti.
Supporto ANSC.

**Comment by amusarra** [comment]
@AMonopoliADS potreste rifare le richieste per cui ottenete gli errori?

Grazie.
Supporto ANSC.

**Comment by AMonopoliADS** [comment]
considerato che le chiamate le fa il cliente, non possiamo intervenire direttamente ma dobbiamo attendere la sua disponibilità.
stiamo provando a contattarlo, ma potrebbe non essere operativo in questo momento.
forse meglio organizzarci per domattina, assicurando la disponibilità di tutti.

nel frattempo, se può essere utile, l'ultima chiamata in errore di oggi ci risulta essere questa:
        "idComune": "10420",
        "idOperazioneComune": 2023000141,
        "dataOraRichiesta": "2023-09-13T13:45:10",

**Comment by amusarra** [comment]
@AMonopoliADS il trace è stato attivato verso le 15 di oggi, quindi, la chiamata indicata non può essere tracciata. Dovremo aspettare la disponibilità del cliente/comune per domani mattina.

Saluti.
Supporto ANSC.

**Comment by AMonopoliADS** [comment]
queste le prove che è riuscito a fare il cliente:
        "idComune": "10420",
        "idOperazioneComune": 2023000146,
        "dataOraRichiesta": "2023-09-13T16:54:09",
endpoint: https://anscservicepre.anpr.interno.it/services/service/val/validazione/evento/1

        "idComune": "10420",
        "idOperazioneComune": 2023000145,
        "dataOraRichiesta": "2023-09-13T16:53:30",
endpoint: https://anscservicepre.anpr.interno.it/services/service/doc/allegato/upload/1

**Comment by amusarra** [comment]
Buongiorno @AMonopoliADS 
Vi daremo un feedback non appena identificato il problema.

Cordiali Saluti.
Supporto ANSC.

**Comment by amusarra** [comment]
@AMonopoliADS potreste chiedere al comune degli ulteriori test?

Grazie.
Supporto ANSC.

**Comment by amusarra** [comment]
@AMonopoliADS da controlli eseguito sul tocken JWT, il valore dell'attributo `sub` risulta essere `null`. Una volta impostato correttamente il valore per l'attributo sub, le richieste andranno a buon fine.

Vi chiediamo di chiedere il ticket una volta eseguita la verifica e il test con esito positivo.

Cordiali Saluti.
Supporto ANSC.

**Comment by AMonopoliADS** [comment]
ok. grazie Antonio

non credo ci saremmo arrivati da soli.

anche in questo caso, però, devo rinnovare l'esigenza di un sistema di messaggistica più chiaro.

peraltro, in passato, altri errori di validazione del JWT, venivano segnati con messaggi specifici.
sulle prima comunicazioni di febbraio mi ritrovo, ad esempio, errori del tipo:
- "Claims sede mancante nel JWT"
- "Claims sub mancante nel JWT"
perchè non continuare a segnalare in maniera esplicita queste situazioni di errore, invece che restituire solo l'elemento "operation"?

intanto grazie
attendo comunque le nuove prove del cliente prima di confermarti che sia tutto a posto e chiudere la issue.

Alessandro

**Comment by AMonopoliADS** [comment]
> @AMonopoliADS da controlli eseguito sul tocken JWT, il valore dell'attributo `sub` risulta essere `null`. Una volta impostato correttamente il valore per l'attributo sub, le richieste andranno a buon fine.
> 
> Vi chiediamo di chiedere il ticket una volta eseguita la verifica e il test con esito positivo.
> 
> Cordiali Saluti. Supporto ANSC.

le prove dopo l'intervento suggerito hanno dato esito positivo.
grazie
