### ISSUE TITLE
Contributo ai Comuni per l'ingresso in ANSC

### ISSUE THREAD

**Issue by LETSIM22** [italia/ansc#282]
Buonasera
ho visto che è uscito il decreto di approvazione del contributo da assegnare ai comuni per l'ingresso in ANSC

https://www.padigitale.it/urbismart2020/anpr-integrazione-stato-civile-risorse-per-i-comuni-28-07-2023/

In cui ancora è riportata la scadenza del 31.12.2023

![image](https://github.com/italia/ansc/assets/47383691/76a3ca93-0630-461e-ba89-b5797dc3646b)

è confermata questa data?

Grazie

**Comment by amusarra** [comment]
Salve @LETSIM22 
Le risponderemo dopo delle verifiche con DTD.

Cordiali Saluti.
Supporto ANSC.

**Comment by SAlberto** [comment]
Buongiorno,
ci sono novità in merito a questa issue? 
Si sa quale sarà la data entro la quale i comuni saranno obbligati a subentrare in ANSC?
Ci sono possibilità che i contributi vengano prorogati oltre il 31/12/2023?

In attesa di un cortese riscontro
Ringrazio anticipatamente
Distinti saluti

**Comment by AlessandriniPCM** [comment]
Buongiorno,
ad oggi, la data del 31 dicembre 2023 costituisce la prima scadenza rispetto alla quale i comuni possono richiedere i contributi per l'adesione ad ANSC. Successivamente verranno ampliati i termini in modo da permettere anche agli altri comuni, di poter richiedere il contributo. Grazie, cordiali saluti.

**Comment by asqueglia** [comment]
Preghiamo di fare riferimento alla issue #492 . Chiudiamo pertanto la issue. In caso di ulteriori dubbi o segnalazioni preghiamo di aprirne una altra dedicata.
