### ISSUE TITLE
Mapping caso d'uso 12214300 (Rico_003)

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#283]
Il documento di mapping del caso d'uso riporta la formula 113 come sempre obbligatoria, a testando il caso d'uso tramite WebApp, questa viene riportata nella composizione del testo solo se è selezionato il flag "Sentenza Figlio Incestuoso", mentre se non attivo viene usata un'altra formula.

Nello stesso file di mapping risultano inoltre raddoppiate alcune voci e l'obbligatorietà di alcuni campi non rispecchia la WebApp.

Potreste verificare ed aggiornare il mapping con le formule da usare nei vari casi?

**Comment by amusarra** [comment]
Salve @biadanpad 
Abbiamo preso in carico la segnalazione.

Cordiali Saluti.
Supporto ANSC.

**Comment by amusarra** [comment]
Salve @biadanpad 
il caso d'uso con id **12214300 (Rico_003)** utilizza la formula 113 in ogni caso.

Ogni formula è stata codificata secondo le linee guida presenti sul "formulario", venendo gestita da condizioni che, in base alle scelte dell'utente, ne cambiano la composizione.

Nello specifico la formula 113 segue queste indicazioni:

"Oggi ... avanti a me ..., Ufficiale dello stato civile del Comune di ..., ... (indicare se nella funzione di sindaco o di chi lo sostituisce o per delega avuta), sono comparsi ... (indicare le complete generalità dei comparenti) i quali mi dichiarano che a seguito della loro unione naturale, la predetta ... ha concepito da mesi ... un figlio che sin da ora essi riconoscono come proprio. I medesimi, a provare lo stato di gravidanza, mi producono il certificato sanitario rilasciato da ... in data ... ; mi dichiarano poi che non esistono fra loro vincoli di parentela o di affinità che ostano al riconoscimento ai sensi dell'art. 251 del codice civile. 

N.B. - In caso di figlio incestuoso sostituire le parole da "mi dichiarano poi" a "codice civile" con le seguenti: "I comparenti mi producono il provvedimento del Tribunale di ... in data ... n. ... con il quale essi sono stati autorizzati al riconoscimento, documento che, munito del mio visto, inserisco nel volume degli allegati a questo registro)". 
A dimostrazione che nulla osta al presente riconoscimento i dichiaranti mi hanno prodotto (ovvero: e/o ho acquisito; ovvero: e/o ho visionato) i seguenti documenti ... (indicare i documenti). 
I documenti prodotti (e/o acquisiti), muniti del mio visto, inserisco nel volume degli allegati a questo registro."

In altre parole la formula utilizzata è sempre la 113 ma differenziata in caso di "sentenza figlio incestuoso".

![image](https://github.com/italia/ansc/assets/708110/45c04553-7120-42d8-8313-2fd63db420e0)

Se non ci sono ulteriori dubbi o chiarimenti chiediamo di chiudere la issue.

Cordiali Saluti.
Supporto ANSC.
