### ISSUE TITLE
Mapping caso d'uso 12221122 (Rico_004)

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#284]
Così come per il caso d'uso 12214300 (Rico_003), ticket #283, nella WebApp, al cambiare dei parametri selezionati quali "Tipologia consenso della madre" e "Tipo dichiarazione assenso", il testo che si compone è diverso nella forma mentre il file di mapping non riporta le formule adeguate da usare nei vari casi.

**Comment by amusarra** [comment]
Salve @biadanpad 
Il caso d'uso con id **12221122 (Rico_004)** utilizza la formula 109 in ogni caso.

Ogni formula è stata codificata secondo le linee guida presenti sul "formulario", venendo gestita da condizioni che,
in base alle scelte dell'utente, ne cambiano la composizione.

Nello specifico la formula 109 segue queste indicazioni:

"Oggi ... avanti a me ..., Ufficiale dello stato civile del Comune di ..., ... (indicare se nella funzione di sindaco o di chi lo sostituisce o per delega avuta), è comparso ... (indicare le complete generalità del comparente), il quale, mi dichiara di riconoscere come proprio figlio naturale ...
(nome e cognome) nato in ... il ... dalla sua unione con ... che già lo ebbe a riconoscere come proprio figlio.

Qualora il figlio abbia compiuto i 16 anni, inserire le seguenti parole: "Il figlio sopra indicato ha prestato l'assenso al proprio riconoscimento con dichiarazione orale resa, ai sensi dell'art. 250 del codice civile, in mia presenza (o: con dichiarazione resa dinanzi a ... che, munita del mio visto, inserisco nel volume degli allegati a questo registro)".

Per il consenso dell'altro genitore, se esso è prestato contestualmente, inserire le seguenti parole: "L'altro genitore dà il suo consenso al riconoscimento del figlio già da lui stesso riconosciuto"; se il consenso è stato prestato davanti all'ufficiale dello stato civile, anteriormente, inserire le seguenti parole: "L'altro genitore ha dato il suo consenso al riconoscimento del figlio già da lui stesso riconosciuto con dichiarazione resa all'ufficiale dello stato civile del Comune di ..., iscritta nei registri delle nascite, anno ... parte ... serie ... n. ..., atto che, munito del mio visto, inserisco nel volume degli allegati a questo registro (o di cui ho preso visione nel caso di atto iscritto nei registri dello stesso Comune)"; se il consenso è stato prestato davanti ad altro pubblico ufficiale, inserire le seguenti parole: " L'altro genitore ha prestato il suo consenso con atto ... (indicare gli estremi dell'atto) al riconoscimento del figlio già da lui stesso riconosciuto, atto che, munito del mio visto, inserisco nel volume degli allegati a questo registro";

se vi è stato rifiuto al consenso, inserire le seguenti parole: "L'altro genitore ha rifiutato il consenso al riconoscimento del figlio già da lui stesso riconosciuto, ma al riguardo è intervenuta sentenza del Tribunale per i minorenni di ... in data ... n. ... che, munita del mio visto, inserisco nel volume degli allegati a questo registro".

Se il figlio è maggiorenne e sia stato riconosciuto dal padre successivamente alla madre, indicare se egli intende mantenere il cognome materno od assumere il cognome paterno inserendo in questo caso le seguenti parole: "Ai sensi dell'art. 262 del codice civile, il figlio ha scelto di assumere il cognome del padre aggiungendolo (ovvero: sostituendolo) a quello della madre".
A dimostrazione che nulla osta al presente riconoscimento il (la) dichiarante mi ha prodotto (ovvero: e/o ho acquisito; ovvero: e/o ho visionato) i seguenti documenti: (elencarli; fra essi deve essere compresa la copia integrale dell'atto di nascita del figlio che si riconosce quando questi sia nato in altro Comune, ecc.) ... Detti documenti prodotti (e/o acquisiti), muniti del mio visto, inserisco nel volume degli allegati a questo registro.
Quando il figlio riconosciuto sia premorto (art. 255 del codice civile) integrare la formula con la seguente aggiunta: "Lo stesso comparente ha dichiarato altresì che l'anzidetto figlio da lui riconosciuto è morto in ... il giorno ... e che il presente riconoscimento ha luogo in favore dei suoi ... (indicare se discendenti legittimi o figli naturali riconosciuti, specificandone le generalità)".

Questa formula va utilizzata anche nel caso in cui il riconoscimento sia fatto successivamente al matrimonio dei genitori (articoli 280 e 283 del codice civile). "


In altre parole la formula utilizzata è sempre la 109 ma differenziata in caso di "Tipologia consenso della madre" e "Tipo dichiarazione assenso".

![image](https://github.com/italia/ansc/assets/708110/b26e0e13-efe6-4635-be49-4548968ff408)

![image](https://github.com/italia/ansc/assets/708110/76835c30-fe04-427d-a373-3775bc1f4463)

![image](https://github.com/italia/ansc/assets/708110/fb6fc5ff-a5a9-43a3-b9f7-e50a8f964992)

Se non ci sono ulteriori dubbi e/o chiarimenti, chiediamo di chiudere la issue.

Cordiali Saluti.
Supporto ANSC.
