### ISSUE TITLE
[ws R010] Anteprima - Errore "Dati in ingresso non corretti" (idUseCase 1312)

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/ansc#285]
ambiente: PRE-PROD
comune: San Lazzaro di Savena (idComune 8647)
end-point: https://anscservicepre.anpr.interno.it/services/service/anteprima/anteprima/evento/1
idOperazioneAnsc: 1616842

con la comunicazione indicata (ws R010) si richiede l'anteprima per l'atto validato con idAnsc 2023-1111118-250-037054
il servizio risponde con l'errore "Dati in ingresso non corretti"

se potete verificare...

grazie
Alessandro Monopoli ADS

**Comment by amusarra** [comment]
Salve @AMonopoliADS 
Abbiamo preso in carico la segnalazione.

Cordiali Saluti.
Supporto ANSC.

**Comment by asqueglia** [comment]
Buongiorno, con il rilascio della versione 1.12.0 la segnalazione è stata corretta; pertanto la issue viene chiusa. In caso vengano riscontrati ulteriori problemi si prega di riaprire l'issue
