### ISSUE TITLE
[R009] assistenzaMinori sempre obbligatoria

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#286]
Buongiorno.
in riferimento al ticket #271 abbiamo notato lo stesso errore anche nelle casistiche:
MATR_002,
MATR_003,
MATR_004,
MATR_005,
MATR_007,
MATR_008

**Comment by annamaraspin** [comment]
Buongiorno,
la mia collega ha appena riprovato ma va sempre in errore.
Vi allego sia il json di invio dati che quello di risposta. 
Sbagliamo noi qualcosa?
[tracciato_inviato.txt](https://github.com/italia/ansc/files/12319544/tracciato_inviato.txt)
[risposta.txt](https://github.com/italia/ansc/files/12319545/risposta.txt)

**Comment by amusarra** [comment]
Buongiorno @annamaraspin 
Con la nuova versione è stata rilasciata la gestione della retro compatibilità così come indicato nel changelog e nel documento https://github.com/italia/ansc/blob/main/docs/Note/NotaRetrocompatibilitaServizi/index.md

È necessario quindi indicare nel payload l'attributo `idVersion` con il valore `100002` per utilizzare il nuovo model.

Cordiali Saluti.
Supporto ANSC.

**Comment by annamaraspin** [comment]
Grazie, ci eravamo fissate sul campo dell'assistenza e non su altri.
 appena possibile riproviamo.
