### ISSUE TITLE
Decodifiche - tabella 95

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#289]
Buongiorno,
nell'elenco delle tabelle di decodifica della versione 1.11 rilasciata ieri, mi ritrovo due denominate con il 95:
- dec_tipo_impedimento
- dec_soggetto_impedimento

Quale delle due è la 95 corretta? L'altra deve essere associata ad altro numero o viene eliminata del tutto?
Grazie

**Comment by asqueglia** [comment]
Buongiorno, verifichiamo e le facciamo sapere appena possibile.

**Comment by asqueglia** [comment]
Avvisiamo che con la versione 1.11.1 è stata corretta la segnalzione. La tabella corretta è la 95_dec_soggetto_impedimento. Chiudiamo la issue nel caso si prega di riaprirla.
