### ISSUE TITLE
[R005] Response dei servizi di Consultazione ANSC, non coerenti con il file Swagger.

### ISSUE THREAD

**Issue by gcuci** [italia/ansc#29]
buonasera,

segnalo che i servizi di Consultazione ANSC (per Soggetto o per Evento), in ambiente di Preproduzione, restituiscono una proprietà non prevista dallo swagger condiviso (R005_consultazione_ansc.yaml).

I servizi dovrebbero restituire un'oggetto del tipo ConsultazioneANSCResponse, con la proprietà 'eventi', contenente un array di ModelEvento, con gli eventi risultato della ricerca. Al posto di 'eventi', viene invece restituita una proprietà 'modelEventoDTO', con gli stessi dati attesi.

Questo è evidentemente un problema, nella generazione automatica delle classi, a partire dallo swagger.

In attesa di un riscontro,

cordiali saluti.

**Comment by siscomanpr** [comment]
Rileviamo lo stesso problema.

Siscom SPA

**Comment by mttfranci** [comment]
Buongiorno, abbiamo pubblicato la patch 1.5.3 : 
https://github.com/italia/ansc/blob/main/docs/Changelog.md

E' stata allineata l'interfaccia openapi con il nome effettivamente restituito dal servizio.

Saluti

Assistenza ANSC
