### ISSUE TITLE
usecase 321321 e 321421 (matr_015 e matr_016)

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#290]
Buongiorno.
Chiedo giusto una conferma visto che non trovo traccia nel changelog: gli usecase in oggetto sono stati eliminati stando alla tabella 3 di decodifica. Corretto?

**Comment by asqueglia** [comment]
Buongiorno, si corretto sono stati eliminati i casi d'uso di matrimonio religioso con riconoscimento di figli per assenza di formule, come condiviso con gli esperti ANUSCA.

**Comment by asqueglia** [comment]
Avvisiamo che con la versione 1.11.1 è stata corretta la documentazione in merito specificando nel changelog quanto richiesto. Chiudiamo pertanto la issue nel caso si prega di riaprirla.
