### ISSUE TITLE
usecase 431000	Trascrizione Unione Civile dall'estero - Richiesta di trascrizione da parte dell'interessato

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#292]
Nel mapping sono riportate tra le formule da usare:
193 quater
193 quinquies

Guardando il formulario ministeriale mi ritrovo che
193 quater riguarda la trascrizione di atto di UNIONE CIVILE costituito all'estero
193 quinquies riguarda la trascrizione di atto di MATRIMONIO celebrato all'estero

Visto la descrizione del vostro usercase mi sarei aspettata solo la 193 quater. 
Con questo usecase trattiamo entrambe le trascrizioni?

**Comment by asqueglia** [comment]
Buonasera, si confermo che abbiamo trattato nello stesso caso d'uso entrambe le casistiche, differenziandole tramite parametro tipoTrascrizione (DEC_55) presente in ModelTrascrizioneUnioneCivile; questa scelta è stata fatta in quanto la 193-quinqiues si riferisce ad un **matrimonio tra persone dello stesso sesso** celebrato all'estero. Chiederemo comunque un approfondimento agli esperti ANUSCA, per confermare la correttezza dell'impostazione.

**Comment by asqueglia** [comment]
Buongiorno, @annamaraspin. Abbiamo posto la domanda ad ANUSCA e riportiamo di seguiro la risposta ricevuta

la formula 193 quater riguarda la trascrizione di atto di UNIONE CIVILE costituito all'estero: unione civile costituita all'estero che viene trascritta in Italia nei registri di unione civile.
La **193 quinquies** riguarda la trascrizione di atto di MATRIMONIO celebrato all'estero tra due persone dello stesso sesso delle quali almeno uno delle due sia cittadino italiano: in tal caso, la trascrizione non potrà avvenire nel registro di matrimonio, ma quel matrimonio "si converte" in unione civile, quindi dovrà essere trascritto nel registro delle unioni civili, come unione civile (artt. 32-bis e 32-quinquies della legge 218/1995 e sentenza della Corte di Cassazione 11696/2018).

Quindi confermiamo di lasciare entrambe le casistiche come fatto al momento.

Chiudiamo pertanto la issue. In caso di ulteriori segnalazioni preghiamo di riaprirla oppure di aprirne un'altra specififca.
