### ISSUE TITLE
usecase 432000	Trascrizione Unione Civile dall'estero - Richiesta di trascrizione da parte del Consolato/Ambasciata

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#293]
In questo usecase prevedete le formule
193-sexiesdecies
193-septiesdecies

Guardando il formulario ministeriale rilasciato con circolare 27 febbraio 2017 queste due formule non vengono menzionate.
Ricercato su internet ma nulla.
Potete inoltrarmele per favore?

**Comment by asqueglia** [comment]
Buonasera, ha ragione è stato un errore di nomenclatura formule; c'è stato un refuso nel titolo della formula.

la formula 193-sexiesdecies riportata nella documentazione è la 193-quater 
la formula 193-septiesdecies riportata nella documentazione è la 193-quinquies

Appena possibile provvediamo a correggere la documentazione.

**Comment by asqueglia** [comment]
Buongiorno, con il rilascio della versione 1.12.0 la segnalazione è stata corretta; pertanto la issue viene chiusa. In caso vengano riscontrati ulteriori problemi si prega di riaprire l'issue
