### ISSUE TITLE
[R901] errore download tabella decodifica 97

### ISSUE THREAD

**Issue by siscomanpr** [italia/ansc#294]
Come da oggetto richiamando il servizio
https://anscservicepre.anpr.interno.it/services/service/val/config/decodifica/dettaglio/1
per scaricare la nuova tabella 97 viene restituito errore 500 - Errore interno.

idOperazione=1617327

**Comment by amusarra** [comment]
Salve @siscomanpr 
Abbiamo replicato il problema e preso in carico.

Cordiali Saluti.
Supporto ANSC.

**Comment by mttfranci** [comment]
Salve @siscomanpr potreste riprovare?

Saluti
Assistenza ANSC

**Comment by siscomanpr** [comment]
Ora funziona, grazie.
