### ISSUE TITLE
[R009] errore validazione matrimonio per soggetto già presente

### ISSUE THREAD

**Issue by siscomanpr** [italia/ansc#295]
Tentando di validare un matrimonio con `idVersion=100002` riceviamo come errore 
`Il soggetto è già presente con id 1987428,2010811,2010406` per lo sposo 
e
`Il soggetto è già presente con id 1987432,2010814,2010409` per la sposa.
Il fatto è che prima di chiamare il servizio di validazione R009, come da vostre istruzioni, il nostro sistema provvede ad eseguire una consultazione per soggetto (R005) per i 2 sposi e la ricerca non restituisce nessun risultato. 
Anche provando a consultare per idsoggetto ansc dalla web app indicando gli ID che vengono segnalati nell'errore, oppure per codice fiscale, non otteniamo alcun risultato.

Di seguito gli idOperazione delle varie chiamate di consultazione e di validazione:
R005 per ricerca sposo: idOperazione=1617409
R005 per ricerca sposa: idOperazione=1617410
R009: idOperazione=1617411

**Comment by amusarra** [comment]
Salve @siscomanpr 
Abbiamo avuto modo di analizzare la problematica esposta e a seguire il risultato.

I due soggetti interrogati attraverso il servizio R005 non sono stati inseriti sul sistema ANSC in precedente con il codice fiscale, ecco il motivo per cui entrambe le interrogazioni non restituiscono alcun soggetto. Per esempio, eliminando dai criteri di ricerca il codice fiscale, i soggetti sono restituiti.

Per il servizio di validazione, il payload, nella sezione intestatari, sia per lo sposo sia per la sposa, contiene solo i dati anagrafici senza il codice fiscale, per questa ragione il servizio risponde come indicato a seguire.

```json
    "errors": [
        {
            "code": "400003",
            "severity": "E",
            "text": "Il soggetto è già presente con id 1987428,2010811,2010406"
        },
        {
            "code": "400003",
            "severity": "E",
            "text": "Il soggetto è già presente con id 1987432,2010814,2010409"
        }
    ],
    "forcingCode": "1692254437245_MCCMRA80T21B111E"
```
Payload JSON - Response servizio di validazione evento

Sulla risposta del servizio di validazione è indicato l'attributo `forcingCode` con cui è possibile forzare l'uso del soggetto indicato. 

Con la release 1.11.0 sono stati aggiunti dei controlli sui soggetti al fine di evitare l'inserimento di soggetti con anagrafica identica. Tramite l'introduzione del `forcingCode`  è quindi possibile forzare l'inserimento del soggetto. Fare riferimento al [changelog](https://github.com/italia/ansc/blob/1935887504b8d978486e6097ffb18c7a79727342/docs/Changelog.md?plain=1#L73)

In questo caso è possibile procedere:

- eseguire la ricerca del soggetto senza il codice fiscale, sarà puoi l'USC a scegliere quali dei soggetti è quello corretto tra quelli disponili;
- eseguire la validazione specificando il `forcingCode` il cui valore è disponibile sulla response;
- eseguire la validazione specificando per entrambe i soggetti intestatari il codice fiscale.

Nel caso in cui la risposta sia stata esaustiva le chiediamo la cortesia di chiudere la issue. Per ogni altro dubbio/chiarimento continui a scrivere qui.

Cordiali Saluti.
Supporto ANSC.

**Comment by siscomanpr** [comment]
Il problema era il codice fiscale, risolto, grazie.
