### ISSUE TITLE
[R009] validazione atti di nascita dichiarazione tardiva

### ISSUE THREAD

**Issue by siscomanpr** [italia/ansc#298]
Buongiorno,
cercando di validare un atto di nascita con dichiarazione tardiva riceviamo l'errore: 
`400003 - Per proseguire è necessario che la datanascita sia anteriore a 10 giorni`
Controllando il json inviato, la data di nascita è sicuramente anteriore a 10 giorni rispetto alla data di formazione. 
Facciamo presente che si tratta di un atto che avevamo già validato in passato, quindi l'errore lo da solo con le ultime versioni di ANSC.

idOperazione: 1617749
Ambiente: pre-prod

**Comment by amusarra** [comment]
Salve  @siscomanpr 
Abbiamo preso in carico la sua segnalazione.

Cordiali Saluti.
Supporto ANSC.

**Comment by siscomanpr** [comment]
Risolto, grazie.
