### ISSUE TITLE
[mapping] Morte 007

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#3]
![Cattura_2](https://user-images.githubusercontent.com/127182190/223345868-a84e9fec-b5f1-47af-b17e-a969d8b44251.PNG)

**Comment by asqueglia** [comment]
Buongiorno, prenderemo in carico la segnalazione e le faremo sapere quanto prima.

**Comment by asqueglia** [comment]
Buonasera, è stata rilasciata la versione 1.5.2 che risolve ala segnalazione. Si prega di riprovare.
