### ISSUE TITLE
accesso alla WebApp

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#300]
Buongiorno,
volevo accedere alla WebApp per vedere come trattavate alcune casistiche ma non ci riesco.
Accedo come CNS, clicco sul certificato relativo al mio Codice Fiscale e poi appare questo messaggio:

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<env:Envelope xmlns:env="http://schemas.xmlsoap.org/soap/envelope/">
<env:Body>
<env:Fault>
<faultcode>env:Client</faultcode>
<faultstring>Rejected by policy. (from client)</faultstring>
</env:Fault>
</env:Body>
</env:Envelope>

**Comment by amusarra** [comment]
Salve @annamaraspin 
Verifichiamo la segnalazione e le faremo sapere quanto prima.

Cordiali Saluti.
Supporto ANSC.

**Comment by annamaraspin** [comment]
Non so se avete fatto qualcosa o meno ma adesso funziona.
Grazie mille

**Comment by amusarra** [comment]
@annamaraspin a questo punto chiudiamo la issue.
Se riesce le chiediamo la cortesia di provare l'accesso via SPID.

Cordiali Saluti.
Supporto ANSC.

**Comment by annamaraspin** [comment]
@amusarra 
Buonasera,
provato accesso con SPID con Poste Italiane: esito positivo
