### ISSUE TITLE
[R009_validazione] chiarimenti su forcingCode

### ISSUE THREAD

**Issue by MichelaGarzoni** [italia/ansc#301]
Buongiorno,
dopo il rilascio della versione 1.11.x abbiamo inserito un atto di separazione-divorzio (usecase343000) e non ci risulta chiaro come interpretare ed intervenire per soddisfare l'errore segnalato relativo al soggetto già presente:
es.
{
"testataRichiesta":{
"idComune":3655
,"idOperazioneComune":"20230150000010"
,"dataOraRichiesta":"2023-08-10T17:18:45Z"
,"nomeApplicativo":"ASCOT Stato Civile"
,"versioneApplicativo":"21.99.0000"
,"fornitoreApplicativo":"Insiel S.p.A"
}
,"evento":{
"idTipoEvento":"3"
,"idtipocontenuto":"1"
,"idUsecase":"343000"
,"descrizioneCasoUso":"Conferma o mancata conferma di accordo di separazione o divorzio"
,"stato":"CONFERMATO"
,"secretato":"0"
,"dataformazione":"2023-08-08"
,"ora":"15"
,"minuto":"56"
,"numeroatto":"20230150000010"
,"idComuneRegistrazione":3655
,"nomeComuneRegistrazione":"DUINO AURISINA-DEVIN NABRE\u017DINA"
,"idProvinciaRegistrazione":"32"
,"siglaProvinciaRegistrazione":"TS"
,"certificabile":"1"
,"composizioneCompleta":"testo accordo Il presente atto viene letto ai dichiaranti i quali, insieme con me e con l\u0027avvocato presente per assisterli, lo sottoscrivono.\r\n"
,"interprete":{
}
,"separazione":{
"tipoAccordo":"2"
,"presenzaConiuge1":true
,"presenzaAvvocatoConiuge1":true
,"avvocatoConiuge1":{
"cognome":"GGGGGGG"
,"nome":"FFFFFFFFFFFFFFFA"
}
,"foroAvvocatoConiuge1":"CREMONA"
,"presenzaConiuge2":true
,"presenzaAvvocatoConiuge2":true
,"avvocatoConiuge2":{
"cognome":"TTTTTTTT"
,"nome":"PJJJJJJJJJJJJ"
}
,"foroAvvocatoConiuge2":"FIRENZE"
,"attoMatrimonio":{
"idComuneRegistrazione":"006"
,"nomeComuneRegistrazione":"TRIESTE"
,"siglaProvinciaRegistrazione":"TS"
,"idProvinciaRegistrazione":"032"
,"idtipocontenuto":"1"
,"dataformazione":"1972-08-12"
,"numeroatto":"739"
,"annoAtto":"1972"
,"tipologia":"3"
,"parte":"II"
,"serie":"A"
}
,"parteInGiudizioPendente":false
,"accordoSeparazione":{
"idComuneRegistrazione":"091"
,"nomeComuneRegistrazione":"ROMA"
,"siglaProvinciaRegistrazione":"RM"
,"idProvinciaRegistrazione":"058"
,"idtipocontenuto":"1"
,"dataformazione":"2000-08-10"
,"numeroatto":"2"
,"annoAtto":"2000"
,"tipologia":"4"
,"parte":"2"
,"serie":"C"
}
}
,"intestatari":[
{
"cognome":"DA DADADA"
,"nome":"FFFFFFFFF"
,"sesso":"M"
,"dataNascita":"19XX-SS-GG"
,"idComuneNascita":"006"
,"nomeComuneNascita":"TRIESTE"
,"idProvinciaNascita":"032"
,"siglaProvinciaNascita":"TS"
,"idStatoNascita":"90"
,"nomeStatoNascita":"ITALIA"
,"idComuneResidenza":"3655"
,"nomeComuneResidenza":"DUINO AURISINA-DEVIN NABRE\u017DINA"
,"idProvinciaResidenza":"32"
,"siglaProvinciaResidenza":"TS"
,"idStatoResidenza":"90"
,"nomeStatoResidenza":"ITALIA"
,"idNazionalita":"100"
,"nazionalita":"ITALIANO"
,"flagDichiarante":true
,"flagComparente":true
,"flagFirmatario":true
}
,{
"cognome":"TRTRTRTR"
,"nome":"CLCLCLCLC"
,"sesso":"F"
,"dataNascita":"1950-08-10"
,"idComuneNascita":"006"
,"nomeComuneNascita":"TRIESTE"
,"idProvinciaNascita":"032"
,"siglaProvinciaNascita":"TS"
,"idStatoNascita":"90"
,"nomeStatoNascita":"ITALIA"
,"idComuneResidenza":"3655"
,"nomeComuneResidenza":"DUINO AURISINA-DEVIN NABRE\u017DINA"
,"idProvinciaResidenza":"32"
,"siglaProvinciaResidenza":"TS"
,"idStatoResidenza":"90"
,"nomeStatoResidenza":"ITALIA"
,"idNazionalita":"100"
,"nazionalita":"ITALIANA"
,"flagDichiarante":true
,"flagComparente":true
,"flagFirmatario":true
}
]
}
}

e abbiamo ottenuto come risposta:
{
    "testataRisposta": {
        "idComune": 3655,
        "idOperazioneComune": "20230150000010",
        "idOperazione": "1616944",
        "idEsito": 1
    },
    "errors": [
        {
            "code": "400003",
            "severity": "E",
            "text": "Il soggetto è **già presente con id 2123214,2123345**"
        },
        {
            "code": "400003",
            "severity": "E",
            "text": "Il soggetto è **già presente con id 2123218,2123349**"
        }
    ],
    **"forcingCode": "1691737634337_XXXYYY77G66G24A"**
}

Per ovviare a questi errori, nella request di validazione, nella sottosezione relativa agli intestatari, dobbiamo recuperare ed inserire l'id (soggetto ANSC) per ogni soggetto?
Abbiamo visto che nel caso in cui noi non avessimo a disposizione l'id dell'intestatario lo potremmo dedurre mediante il servizio [R005 -consultazione]/ansc/soggetto inserendo campi di ricerca quali cognome, nome, e codice fiscale.
Nel caso relativo all'esempio fatto, ci vengono indicati ben 4 id (soggetto) presenti da definire sull'evento: deduciamo si riferiscano 2 a instestatario1 (id 2123214,2123345) e 2 intestatario2 (id 2123218,2123349). Come passiamo selezionare il soggetto in questione cioè: sarà l'USC che dovrà selezionare il soggetto a cui si fa riferimento tra quelli restituiti da R005 e attribuirlo al soggetto corretto?
Nel caso l'USC definisca che il soggetto non corrisponde a nessuno di quelli restituiti, viene utilizzato il forcingCode? Cosa comporta? Inserimento di un nuovo intestatario con nuovo codice? Questo forcingCode che valori può assumere (sembra composto da doppio valore "numero-cfis_USC" ma hi lo determina e con che logica viene determinato, è un progressivo)? Che significato ha il forcingCode nella response: restituisce un nuovo valore rispetto a quello inviato nella request o mantiene lo stesso valore e serve in altre situazioni relative ai servizi?

**Comment by amusarra** [comment]
Salve @MichelaGarzoni 
Consigliamo di leggere la #295 in merito che dovrebbe rispondere alle sue domande.
Il `forcingCode` può essere utilizzato una sola volta.

Le chiediamo di chiudere la issue qualora la risposta sia stata esaustiva.

Cordiali Saluti.
Supporto ANSC.

**Comment by MichelaGarzoni** [comment]
Grazie, non avevo visto tale issue. Ora la leggo per capire se abbiamo interpretato correttamente il nuovo rilascio.
Chiudo la segnalazione e al più se mi serviranno ulteriori chiarimenti ne aprirò una nuova.
