### ISSUE TITLE
usecase 51101 e 52112 di Cittadinanza

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#302]
Buongiorno,
per gli usecase in oggetto nella tabella di decodifica trovo la stessa descrizione per ambedue
"Straniero o apolide, del quale il padre o la madreo uno dei ascendenti in linea retta di secondo grado sono stati cittadiniper nascita: acquisto medianteprestazione del servizio militare per lo Stato italiano"

Quale dei due usecase è veramente associato a tale descrizione?
grazie

**Comment by amusarra** [comment]
Salve @annamaraspin 
Abbiamo preso in carico la segnalazione.

Cordiali Saluti.
Supporto ANSC.

**Comment by asqueglia** [comment]
Buongiorno, con il rilascio della versione 1.12.0 la segnalazione è stata corretta; pertanto la issue viene chiusa. In caso vengano riscontrati ulteriori problemi si prega di riaprire l'issue
