### ISSUE TITLE
[R009] - Gestione Assistenza Minori nei matrimoni

### ISSUE THREAD

**Issue by DiBellaDavide** [italia/ansc#303]
Buongiorno,
a seguito del rilascio 1.11.0 è stato deprecato il model AssistenzaMinori presente nel ModelRegimePatrimoniale.
Considerata la presenza di tale model in base al mapping di molti dei casi d'uso di Matrimonio, e il non riuscire a validare atti di matrimonio in cui non sono presenti assistenti minori, potreste darci delucidazioni in merito alla gestione degli assistenti minori? Su come gestire le obbligatorietà ed eventualmente a quale model occorre fare riferimento?
Allego un'operazione recente effettuata in ambiente di pre-prod:
idOperazione : 1619304
Distinti saluti.

**Comment by amusarra** [comment]
Buongiorno @DiBellaDavide 
Le consiglio di fare riferimento alla issue #286 dov'è stato trattato il tema e in particolare la nota sulla gestione della retro compatibilità.

Se non ci sono ulteriori dubbi e/o chiarimenti, vi chiediamo di chiudere la issue.

Cordiali Saluti.
Supporto ANSC.
