### ISSUE TITLE
Ancora su figlio minore riconosciuto da cittadino italiano (Citt_002)

### ISSUE THREAD

**Issue by antonioluberto** [italia/ansc#304]
Buongiorno.
Pur a seguito di quanto indicato in chiusura alla https://github.com/italia/ansc/issues/265, la documentazione indica ancora entrambi i genitori come obbligatori.

![image](https://github.com/italia/ansc/assets/26415430/3a3f06f2-6765-48e2-9dcc-f0e2a8bbcbec)

![image](https://github.com/italia/ansc/assets/26415430/e99ca8f3-3e7d-4a87-ac45-fdf7268b821f)

**Comment by asqueglia** [comment]
Buongiorno, gli screen shot riportati si riferiscono alle obbligatorietà dei singoli metadati della sezione, da rispettare nella eventualità che la sezione venga inviata. L'obbligatorietà o meno, della intera sezione (padre / madre), invece, è esplicitata dalla colonna 'Condizioni di obbligatorietà' presente nella documentazione di mapping (che non si vede dagli screen shot riportati).
Nel caso specifico la sezione madre è obbligatoria se {evento.trascrizioneCittadinanza.genitoreConCittadinanza,=,2} mentre la sezione padre è obbligatoria se {evento.trascrizioneCittadinanza.genitoreConCittadinanza,=,1} per cui l'obligatorietà delle sezioni madre e padre dipende dal parametro genitoreConCittadinanza trasmesso.

Abbiamo ritenuto di inserire la colonna aggiuntiva 'condizioni di obbligatorietà' nella documentazione di mapping, proprio per cercare di differenziare le obbligatorietà dei metadati contenuti all'interno di una sezione,  dall'obbligatorietà dell'intera sezione.

**Comment by asqueglia** [comment]
Bunasera,la issue viene chiusa; in caso di ulteriori problematiche si prega di aprire un'altra issue dedicata.
