### ISSUE TITLE
[R009] - Allegato mancante per caso d'uso Rico_013

### ISSUE THREAD

**Issue by DiBellaDavide** [italia/ansc#305]
Buongiorno,
nonostante invii l'allegato obbligatorio "Atto di riconoscimento" per il caso d'uso Rico_013, il servizio di validazione restituisce errore indicandone la mancanza. 
Ambiente di pre-prod.
idOperazione: 1619600
Data del test: 29/08/23

**Comment by asqueglia** [comment]
Buongiorno, abbiamo verificato l'operazione effettuata. 
Per il caso d'uso indicato l'allegato obbligatorio è il "idTipoAllegato": "14", Copia dell'atto di assenso del figlio ; nella operazione da voi indicata invece è stato trasmesso l'allegato con id 18.
Ci scusiamo per la documentazione di mapping non corretta che riporta impropriamente l'atto di riconoscimento anzichè l'atto di assenso. Provvederemo quanto prima a correggere la documentazione.

**Comment by asqueglia** [comment]
Buongiorno, con il rilascio della versione 1.12.0 la segnalazione è stata corretta; pertanto la issue viene chiusa. In caso vengano riscontrati ulteriori problemi si prega di riaprire l'issue
