### ISSUE TITLE
[R009] - Errore su intestatario atto Morte_004

### ISSUE THREAD

**Issue by DiBellaDavide** [italia/ansc#306]
Buongiorno,
per il caso d'uso Morte_004 "Decesso relativo a cadavere rinvenuto non identificato", invocando il servizio di validazione viene restituito l'errore che recita "Intestatari non valido".
Dato che al caso d'uso applicato l'intestatario evidentemente non può essere richiesto, chiedo delucidazioni in merito al corretto invio della richiesta del servizio di validazione.
Ambiente di pre-prod
idOperazione : 1619681
Data del test : 29/08/23

**Comment by asqueglia** [comment]
Buonasera la issue viene chiusa; in caso di ulteriori problematiche si prega di aprire un'altra issue dedicata.
