### ISSUE TITLE
Caso d'uso Citt_013: chiarimenti su "Condizioni obbligatorietà"

### ISSUE THREAD

**Issue by antonioluberto** [italia/ansc#307]
La documentazione relativa al caso d'uso in oggetto riporta l'indicazione

![image](https://github.com/italia/ansc/assets/26415430/1094bb52-d00d-42ef-a884-aced52e506d7)

Qual è effettivamente il valore da utilizzare tra i due possibili? 
Se eventualmente deve essere l'applicazione locale a definire se riportare l'uno o l'altro dei due valori, qual è la condizione funzionale da verificare?

In tutti gli altri casi d'uso, il campo "Condizioni obbligatorietà" presenta il riferimento ad un solo valore.

**Comment by asqueglia** [comment]
Buongiorno, verifichiamo e le facciamo sapere appena possibile.

**Comment by asqueglia** [comment]
Buongiorno, stiamo verificando  la documentazione. Appena possibile provvederemo a fornire il riferimento della tabella di decodifica necessaria.

**Comment by asqueglia** [comment]
Buongiorno, con il rilascio della versione 1.12.0 la segnalazione è stata corretta; pertanto la issue viene chiusa. In caso vengano riscontrati ulteriori problemi si prega di riaprire l'issue
