### ISSUE TITLE
usecase 51103 -straniero nato in Italia che vi abbia risieduto legalmente senza interruzioni fino alla maggiore età (Citt_011)

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#308]
Buongiorno,
nel mapping ho visto che è obbligatorio il campo

Dettagli evento | Indirizzo posta autorità | SI | evento.datiEventoCittadinanza | indirizzoPostaAutorità

L'e-mail di quale autorità? Nel testo dell'atto non viene menzionata nessuna autorità, non è una trascrizione.
grazie

**Comment by asqueglia** [comment]
Buongiorno, verifichiamo e le facciamo sapere appena possibile

**Comment by asqueglia** [comment]
Buongiorno, con il rilascio della versione 1.12.0 la segnalazione è stata corretta; pertanto la issue viene chiusa. In caso vengano riscontrati ulteriori problemi si prega di riaprire l'issue
