### ISSUE TITLE
Tabella 3 Casi d'uso, dubbi su descrizioni duplicate

### ISSUE THREAD

**Issue by migmar68** [italia/ansc#31]
Segnalo questi casi. Immagino siano troppi per essere refusi. Potete specificare  la differenza tra queste righe con doppio codice, e quando dobbiamo usare un codice, quando l'altro?

2112	Richiesta trascrizione atto di morte all estero richiesto da privati Morte Trascrizione (atto) Morte_006
2212	Richiesta trascrizione atto di morte all'estero richiesto da privati

2113	Richiesta trascrizione atto di morte all estero richiesto da pubblica autorità Morte Trascrizione (atto) Morte_007
2213	Richiesta trascrizione atto di morte all'estero richiesto da pubblica autorità

51101	straniero o apolide, del quale il padre o la madre o uno dei ascendenti in linea retta di secondo grado sono stati cittadini per nascita: acquisto mediante prestazione del servizio militare per lo Stato italiano
52112	"straniero o apolide, del quale il padre o la madre o uno dei ascendenti in linea retta di secondo grado sono stati cittadini per nascita: acquisto mediante prestazione del servizio militare per lo Stato italiano"

51102	straniero o dall'apolide, del quale il padre o la madre o uno degli ascendenti in linea retta di secondo grado sono stati cittadini per nascita, il quale, al raggiungimento della maggiore età, risiede legalmente da almeno due anni nel territorio della Repubblica
52121	straniero o dall'apolide, del quale il padre o la madre o uno degli ascendenti in linea retta di secondo grado sono stati cittadini per nascita, il quale, al raggiungimento della maggiore età, risiede legalmente da almeno due anni nel territorio della Repubblica

52113	straniero o dell'apolide, del quale il padre o la madre o uno degli ascendenti in linea retta di secondo grado sono stati cittadini per nascita: acquisto assunzione di pubblico impiego alle dipendenze dello Stato
52114	straniero o dell'apolide, del quale il padre o la madre o uno degli ascendenti in linea retta di secondo grado sono stati cittadini per nascita: acquisto assunzione di pubblico impiego alle dipendenze dello Stato

51103	straniero nato in Italia che vi abbia risieduto legalmente senza interruzioni fino alla maggiore età 
52122	straniero nato in Italia che vi abbia risieduto legalmente senza interruzioni fino alla maggiore età 

51306	 donna che, avendo perduto, anteriormente al 1° gennaio 1948, la cittadinanza italiana per effetto di matrimonio con uno straniero o di mutamento di cittadinanza da parte del marito, intende riacquistarla
52324	 donna che, avendo perduto, anteriormente al 1° gennaio 1948, la cittadinanza italiana per effetto di matrimonio con uno straniero o di mutamento di cittadinanza da parte del marito, intende riacquistarla

51304	riacquisto per abbandono dei servigi allo stato estero
52322	riacquisto per abbandono dei servigi allo stato estero

Questa forse ha una descrizione troncata?

51108	straniero o dell apolide, del quale il padre o la madre

**Comment by migmar68** [comment]
Aggiungo richiesta di chiarimento : considerata la prima di queste tre casistiche (e le successive che non riporto qui), immagino che la seconda e terza che elenco qui sotto siano sempre riferite a dichiarazione del padre.

11121000	Dichiarazione tardiva di filiazione nel matrimonio resa all'USC dal padre

11121100	Dichiarazione tardiva di filiazione nel matrimonio resa all'USC di filiazione di bimbo nato morto

11121200	Dichiarazione tardiva di filiazione nel matrimonio resa all'USC di bimbo nato vivo ma morto prima della denuncia di nascita

**Comment by mttfranci** [comment]
@migmar68  stiamo verificando la segnalazione, intando il motivo per cui le tabelle sono due, è perchè : ansc/docs/Decodifiche/ - contiene l'elenco completo dei casi d'uso al momento censiti
ansc/docs/Mapping_casi_uso/ - contiene solo quelli al momento rilasciati ufficialmente e per cui è presente il mapping (per questo non è stata aggiornata l'ultima volta, non abbiamo aggiunto documentazione di mapping nel rialscio 1.5.2)

**Comment by asqueglia** [comment]
Buongiorno, avvisiamo che con il rilascio odierno è stata aggiornata la tabella di decodifica dei casi d'uso risolvendo le problematiche segnalate.
