### ISSUE TITLE
usecase 51104	- straniero riconosciuto durante la maggiore età da cittadino italiano	(Citt_013)

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#311]
Buongiorno,
il campo idriconoscimentosentenza è obbligatorio e condiziona anche l'obbligatorietà di altri dati.
Cercando sia sul file tracciato-evento che sul changelog non ho trovato a quale tabella di decodifica si riferisca.
Ho guardato anche tutte le tabelle di decodifica finora rilasciate ma nulla.

**Comment by asqueglia** [comment]
Buongiorno, stiamo verificando  la documentazione. Appena possibile provvederemo a fornire il riferimento della tabella di decodifica necessaria.

**Comment by asqueglia** [comment]
Buongiorno, con il rilascio della versione 1.12.0 la segnalazione è stata corretta; pertanto la issue viene chiusa. In caso vengano riscontrati ulteriori problemi si prega di riaprire l'issue
