### ISSUE TITLE
usecase 2102 - Decesso in ospedale o casa di cura

### ISSUE THREAD

**Issue by LucaBonini64** [italia/ansc#312]
Buongiorno,
in ambiente di pre-produzione di Novi Ligure inviando un atto di morte con usecase 2102 ("idOperazione":"1620289") viene restituito l'errore [{"code":"Evento non modificabile","severity":"E","text":"Evento sconosciuto"}].
Inoltre nelle condizioni di obbligatorietà viene indicata come obbligatoria la presenza del coniuge o dell'unito civilmente quando l'intestatario ha come IdStatoCivile=1 mentre non dovrebbe in quanto la decodifica corrisponde a celibe/nubile.
Potete verificare a cosa è dovuto il problema?
Grazie.
Luca Bonini

**Comment by asqueglia** [comment]
Buongiorno, abbiamo verificato la richiesta inviata e abbiamo riscontrato che avete inviato alcuni nomi di elementi errati che hanno causato l'errore restituito.
Nello specifico avete inviato idUseCase anzichè **idUsecase**  e composizionecompleta anzichè **composizioneCompleta**.
Consigliamo di riprovare l'operazione correggendo il nome degli elementi indicati.

**Comment by asqueglia** [comment]
Buonasera, la issue viene chiusa; in caso di ulteriori problematiche si prega di aprire un'altra issue dedicata.
