### ISSUE TITLE
Dati officiante su atti di matrimonio religiosi

### ISSUE THREAD

**Issue by LucaBonini64** [italia/ansc#313]
Buongiorno,
nella issue  #162 è stato indicato che i dati dell'officiante contengono i dati dell'USC che celebra il matrimonio, però anche negli usecase 321311 e 321411, che sono relativi a matrimoni celebrati da ministri di culto, vengono indicati come obbligatori i dati dell'officiante.
E' un refuso e quindi i dati non sono obbligatori, oppure bisogna indicare le generalità del Parroco/Ministro di Culto che celebra il matrimonio?
Grazie
Luca Bonini

**Comment by asqueglia** [comment]
Buongiorno, si vanno indicate le generalità di colui che celebra il matrimonio.

**Comment by asqueglia** [comment]
Buonasera provvediamo a chiudere questa issue, in caso di ulteriori problematiche si prega di riaprirla o aprirne un'altra dedicata.
