### ISSUE TITLE
Use case citt_002 errore validazione 400003 

### ISSUE THREAD

**Issue by FrankCer** [italia/ansc#314]
Buongiorno,
durante l'invio dello use case in oggetto abbiamo come risposta **Attenzione, ci sono stati degli errori: 400003 : Il campo evento.datiEventoCittadinanza.tipoEventoCittadinanza nella sezione Dati generali è obbligatorio - 400003 : Il campo evento.padre.indirizzoResidenza nella sezione Padre è obbligatorio**

L'errore era stato risolto con l'issue #260 però su altro use case.

ambiente pre-prod,
data del test 01/09/2023

I dati per l'identificazione della risposta:
IdVersion = "100002";
IdOperazioneComune = "1e16c8c4-ac92-4de7-851a-e8faf2dae678"
IdOperazione = "1620512"

**Comment by asqueglia** [comment]
Buongiorno, le faremo sapere appena apportata la correzione.

**Comment by asqueglia** [comment]
Buongiorno, è stata appena rilasciata la versione 1.13.0 che corregge il bug segnalato. Chiudiamo pertanto la issue; in caso di ulteriori problematiche si prega di aprirne una nuova.
