### ISSUE TITLE
Use case citt_011 persiste errore validazione 400003

### ISSUE THREAD

**Issue by FrankCer** [italia/ansc#315]
Buongiorno,
durante l'invio dello use case in oggetto abbiamo come risposta **Attenzione, ci sono stati degli errori: 400003 : Il campo evento.intestatari[0].documentoRiconoscimento.rilasciatoDa nella sezione Documento di riconoscimento non corrisponde al pattern ^[0-9]*$**

L'errore era stato risolto con l'issue https://github.com/italia/ansc/issues/244.

ambiente pre-prod,
data del test 01/09/2023

I dati per l'identificazione della risposta:
IdVersion = "100002";
"idOperazioneComune": "e4d6b427-4c4a-4ac6-8ca5-3bfd18cc56a1", 
"idOperazione": "1620327"

**Comment by amusarra** [comment]
Buongiorno @FrankCer 
Abbiamo preso in carico la segnalazione.

Cordiali Saluti.
Supporto ANSC.

**Comment by asqueglia** [comment]
Buongiorno, è stata appena rilasciata la versione 1.13.0 che corregge il bug segnalato. Chiudiamo pertanto la issue; in caso di ulteriori problematiche si prega di aprirne una nuova.
