### ISSUE TITLE
Trascr_morte_999: indicazioni su campo "Motivo recupero"

### ISSUE THREAD

**Issue by antonioluberto** [italia/ansc#316]
Il caso d'uso Trascr_morte_999 indica come obbligatori il campo:

![image](https://github.com/italia/ansc/assets/26415430/ac574128-39c3-4615-a9d7-e1270ef4d31e)

Non è chiaro a quale condizione funzionale faccia riferimento; potreste fornirci chiarimenti in merito?

**Comment by asqueglia** [comment]
Buongiorno il motivo recupero è obbligatorio solo se data decorrenza è valorizzata ed è diversa dalla data formazione. Quando si registra in digitale un atto temporaneamente formato su carta (ad esempio per indisponibilità temporanea del sistema), è obbligatorio trasmettere la data decorrenza; in tal caso è obbligatorio trasmettere anche ora e minuto decorrenza  e il motivo  di recupero; la data decorrenza è la data in cui è stato formato l'atto cartaceo mentre la data formazione è la data in cui viene digitalizzato l'atto.

**Comment by antonioluberto** [comment]
Con riferimento al caso d'uso in esame (atto temporaneamente formato su carta ,ad esempio per indisponibilità temporanea del sistema), il "foglio" di carta sul quale l'atto dovrà essere inizialmente stampato potrà essere un foglio (A4) qualunque? Oppure il Comune dovrà comunque prevedere, seppure in numero contenuto, l'acquisto di modelli cartacei specifici da utilizzare allo scopo?

**Comment by asqueglia** [comment]
Buongiorno, il Dipartimento conferma che gli atti filigranati, numerati e vidimati verranno mantenuti solamente per i casi di malfunzionamento di ANSC.

**Comment by asqueglia** [comment]
Buonasera la issue viene chiusa; nel caso di ulteriori chiarimenti si prega di aprirne un'altra dedicata.
