### ISSUE TITLE
Atti di morte: gestione data/ora/minuti evento

### ISSUE THREAD

**Issue by antonioluberto** [italia/ansc#317]
In tutti i casi d'uso relativi agli atti di morte ci pare siano sempre obbligatorie le informazioni relative a:

![image](https://github.com/italia/ansc/assets/26415430/7613ac10-8574-480f-bfa5-6496ea496a35)

Vi sono casi in cui una o più delle informazioni in questione non siano disponibili; si pensi ad esempio al ritrovamento di cadavere di cui non possa essere esattamente determinato il giorno (ovvero l'ora ovvero i minuti) della morte.

Come è possibile gestire casi di questo tipo?

**Comment by asqueglia** [comment]
Buongiorno, il sistema consente la trasmissione di una data di morte presunta nei casi ad esempio di cadavere rinvenuto non identificato; si faccia riferimento all'issue #306 che riporta un esempio funzionante del caso d'uso menzionato.

**Comment by antonioluberto** [comment]
Con la issue https://github.com/italia/ansc/issues/306 chiedevamo indicazioni su come gestire il caso in cui non fosse possibile indicare le generalità del titolare dell'atto di morte.

Con la presente issue, diversamente, chiediamo indicazioni su come debba essere comunicata una data di morte che non sia "certa".
Esempio:
se l'usc riceve dal Tribunale notifica per la formazioni di un atto di morte di soggetto il cui decesso sia avvenuto tra il 2 settembre ed il 3 settembre, che data di morte dovremo indicare nella creazione dell'atto digitale?
Oggi, in casi di questo tipo, l'applicazione locale da la possibilità di specificare, in fase di redazione dell'atto, la consistenza della data di morte (completa, mese anno, solo anno) nonché la disponibilità o meno di ora/minuti della morte; quindi gestisce di conseguenza la stampa dell'atto e l'emissione della relativa certificazione.

Rimaniamo in attesa di vostre indicazioni.

**Comment by asqueglia** [comment]
Buongiorno, i campi da popolare in caso di morte non certa sono dataPresuntaMorteDa e dataPresuntaMorteA; ho segnalato la issue #306 perchè è riportato un esempio in cui viene trattato il caso di morte non certa
Riportoinfatti lo stralcio dell'esempio riportato nella issue indicata

....
"datiDiMorte": {
"idComuneMorte": "99",
"nomeComuneMorte": "AGRIGENTO",
"idProvinciaMorte": "84",
"siglaProvinciaMorte": "AG",
"idStatoMorte": "90",
"nomeStatoMorte": "ITALIA",
"luogoMorte": "luogo di ritrovamento",
"indirizzoMorte": "",
"oraMorte": "",
"minutoMorte": "",
**"dataPresuntaMorteDa": "2023-08-22",
"dataPresuntaMorteA": "2023-08-25",**
"testoDataPresuntaMorte": ""
},
....

**Comment by asqueglia** [comment]
Buonasera, la issue viene chiusa; in caso di ulteriori problemi si prega di riaprirla o di aprirne un'altra dedicata.
