### ISSUE TITLE
Informazioni campi AnagraficaConsolato

### ISSUE THREAD

**Issue by DiBellaDavide** [italia/ansc#318]
Salve,
a seguito dei rilasci dalla 1.10 in poi sono stati aggiunti i campi idAnagraficaConsolato e nomeAnagraficaConsolato obbligatori in molti casi d'uso che prevedono per l'appunto la presenza di un consolato negli atti.
Potreste darci delucidazioni in merito a quale id passare nel campo idAnagraficaConsolato e la differenza tra nomeAnagraficaConsolato e nomeEnte dell'autorità mittente?

**Comment by asqueglia** [comment]
Buongiorno, la tabella di decodifica a cui fare riferimento per trasmettere il consolato è la 97_dec_consolato in cui sono specificati gli id da trasmettere. La differenza tra il consolato e l'ente è che l'ente è una qualsiasi autorità di terze parti non censita nel sistema a differenza dei consolati.

**Comment by asqueglia** [comment]
Buonasera la issue viene chiusa; in caso di ulteriori problematiche si prega di riaprirla o di aprirne un'altra dedicata.
