### ISSUE TITLE
[WebApp] Caso d'Uso 2212 - testo composizione vuoto

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#319]
Anche compilando tutti i dati richiesti, il testo della composizione dell'atto è sempre vuoto

**Comment by asqueglia** [comment]
Provvederemo a correggere quanto prima. Grazie per la segnalazione

**Comment by asqueglia** [comment]
Buongiorno, è stata appena rilasciata la versione 1.13.0 che corregge il bug segnalato. Chiudiamo pertanto la issue; in caso di ulteriori problematiche si prega di aprirne una nuova.
