### ISSUE TITLE
[R009] Validazione caso d'uso 11214000

### ISSUE THREAD

**Issue by siscomanpr** [italia/ansc#32]
Caso d'uso : 11214000 - Dichiarazione entro i 10 giorni – resa dal procuratore del padre - Filiazione fuori dal matrimonio con consenso della madre a essere nominata

Riceviamo l'errore: `Allegato obbligatorio mancante: [Procura]` nonostante nella richiesta l'allegato viene trasmesso.

Ambiente: preproduzione
idOperazione: 1571672

Siscom SPA

**Comment by asqueglia** [comment]
Buongiorno, con il rilascio odierno abbiamo risolto l'anomalia segnalata.

**Comment by siscomanpr** [comment]
Grazie @asqueglia, questo caso d'uso in particolare in effetti ora funziona, ma provandone un altro a caso che richiede sempre quell'allegato (Procura), il problema persiste. Potete sistemare anche gli altri casi d'uso?
