### ISSUE TITLE
[R006] - errore "Non sono stati recuperati firmatari per i dati inseriti"

### ISSUE THREAD

**Issue by siscomanpr** [italia/ansc#321]
Buongiorno,
tendando di firmare un atto di matrimonio nella fase di firma dichiaranti in modalità cartacea, ci viene restituito questo errore:
`400003 | Non sono stati recuperati firmatari per i dati inseriti`
Da una verifica ci risulta che questo atto, precedentemente validato con R009, contiene esattamente gli stessi nominativi indicati come firmatari che trasmettiamo poi con il servizio R006.

Allego la request e la response del servizio R006
[202300000000000000000000003779_Request.log](https://github.com/italia/ansc/files/12521803/202300000000000000000000003779_Request.log)
[202300000000000000000000003779_Response.log](https://github.com/italia/ansc/files/12521804/202300000000000000000000003779_Response.log)

Mentre l' idOperazione della validazione dello stesso atto è : 1621018

Potete dirci da cosa è dovuto questo errore?

**Comment by amusarra** [comment]
Salve @siscomanpr 
Abbiamo preso in carico la segnalazione.

Cordiali Saluti.
Supporto ANSC.

**Comment by asqueglia** [comment]
Buongiorno, è stata appena rilasciata la versione 1.13.0 che corregge il bug segnalato. Chiudiamo pertanto la issue; in caso di ulteriori problematiche si prega di aprirne una nuova.
