### ISSUE TITLE
[R007] - Errore nella firma USC

### ISSUE THREAD

**Issue by LucaBonini64** [italia/ansc#322]
Buongiorno,
in ambiente di preproduzione abbiamo provato la firma remota per l'IdEvento 1111766 dopo aver verificato, anche tramite WebApp, che la firma del dichiarante fosse stata apposta correttamente, la risposta del sistema è stata però:
{"errors":[{"code":"406004","severity":"E","text":"Firma non avvenuta con successo"}],"testataRisposta":{"idComune":6498,"idEsito":1,"idOperazione":"1621610","idOperazioneComune":"LB20230905165400"}}

Nella issue #172 si ipotizza che tale messaggio sia dovuto al mancato invio del servizio [R006] che nel nostro caso non c'è stato perché la firma del dichiarante è avvenuta elettronicamente con il servizio [R012], mi sapete indicare dove abbiamo eventualmente sbagliato nell'invocare il servizio R007?

Mi associo ovviamente alla richiesta di Alessandro Monopoli di avere messaggi di errore relativi alla firma più semplici da interpretare.

Grazie

Luca Bonini APKAPPA

**Comment by amusarra** [comment]
Buongiorno @LucaBonini64 
Abbiamo provato a replicare il caso/flusso per lo stesso usecase ma senza riscontrare alcun errore nella fase di firma USC.
Ieri pomeriggio, proprio verso l'ora della richiesta, erano in corso le procedure di rilascio della nuova versione del sistema ANSC.

La invitiamo pertanto, a eseguire nuovamente la firma USC; in caso di errori lo segnali che provvederemo a controlli più approfonditi, in caso contrario le chiediamo di chiudere la issue.

Cordiali Saluti.
Supporto ANSC.

**Comment by amusarra** [comment]
@LucaBonini64 le ricordiamo che non sarò possibile più firmare USC trascorse due ore dalla firma dichiarante, dovrebbe quindi ripetere il processo.

Cordiali Saluti.
Supporto ANSC.

**Comment by LucaBonini64** [comment]
Buongiorno @amusarra 
stamattina ho riprovato e mi ha dato però il messaggio vecchio: "Stato evento non valido per l'operazione richiesta" e non il messaggio nuovo che sarebbe perfetto.
Ho quindi annullato l'evento 1111766 e inserito un nuovo atto con idEvento 1111798 ma anche in questo caso inviando il servizio R007 l'errore restituito è:
{"errors":[{"code":"406004","severity":"E","text":"Firma non avvenuta con successo"}],"testataRisposta":{"idComune":6498,"idEsito":1,"idOperazione":"1621762","idOperazioneComune":"LB20230906102600"}}

Negli inputFirma sto passando i dati per la firma di test che mi avete comunicato:
inputFirma1: CosignAS0021
inputFirma2: password
inputFirma3: 123456
sono corretti?

Cordiali saluti

**Comment by amusarra** [comment]
Buongiorno @LucaBonini64 sulla documentazione delle [OpenAPI di firma R007](https://italia.github.io/ansc/docs/openapi/R007_firma_usc.yaml) sono indicati i valori per gli attributi. A seguire un esempio di payload. Dovrebbe sostituire `{{idEvento}}` con il valore dell'idEvento.

```
    "firmaInput": {
        "idEvento": "{{idEvento}}",
        "parametriFirma": {
            "idTipoFirma": "1",
            "idModalitaInput": "2",
            "inputFirma1": "VGVzdFVzZXI=",
            "inputFirma2": "VGVzdFBhc3N3b3Jk",
            "inputFirma3": "VGVzdE90cA=="
        }
    }
```
**Source 1 - Elemento firmaInput per il payload di Firma USC**

In questo modo dovrebbe risolvere.

Cordiali Saluti.
Supporto ANSC.

**Comment by LucaBonini64** [comment]
Mettendo i parametri di input indicati come esempi nel payload di test ho risolto.
Grazie.

**Comment by mttfranci** [comment]
Bene.

Saluti.

Assistenza ANSC
