### ISSUE TITLE
R005 - Consultazione ANSC Intestatario - Dati Mancanti

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#324]
Buongiorno, 
il servizio in oggetto non restituisce, per i soggetti interessati, i seguenti dati:
 - nomeStatoNascita
 - idProvinciaNascita
 - siglaProvinciaNascita
 - nomeComuneNascita
 - nomeStatoResidenza
 - idProvinciaResidenza
 - siglaProvinciaResidenza
 - nomeComuneResidenza
 - indirizzoResidenza
 - idNazionalita

REQUEST:
{
    "criteriRicercaSoggetto": {
        "cognome": "GUIDI",
        "nome": "LIDIA",
        "sesso": "F",
        "idComuneNascita": "427",
        "nomeComuneNascita": "AREZZO",
        "siglaProvinciaNascita": "AR",
        "codiceStatoNascita": "90",
        "nomeStatoNascita": "ITALIA",
        "datanascita": "1948-01-29"
    },
    "testataRichiesta": {
        "idComune": 5000,
        "idOperazioneComune": "4324",
        "dataOraRichiesta": "2023-09-06T10:24:51.511+02:00",
        "nomeApplicativo": "urbi",
        "versioneApplicativo": "0.1.0",
        "fornitoreApplicativo": "padigitale"
    }
}

RESPONSE:
{
    "testataRisposta": {
        "idComune": 5000,
        "idOperazioneComune": "4324",
        "idOperazione": "1621759",
        "idEsito": 0
    },
    "datiPaginazione": {
        "numPagina": 1,
        "numRecordPagina": 30,
        "numRecordTotali": 1
    },
    "soggetti": [{
            "id": 2211208,
            "cognome": "GUIDI",
            "nome": "LIDIA",
            "sesso": "F",
            "datains": "2023-09-04T10:41:01.000+00:00",
            "dataultimoagg": "2023-09-04T10:41:01.000+00:00",
            "codicefiscale": "",
            "idstato": null,
            "nazionalita": "ITALIANA",
            "dataNascita": "1948-01-28T23:00:00.000+00:00",
            "idComuneResidenza": 427,
            "idStatoNascita": "90",
            "idStatoResidenza": "90",
            "idComuneNascita": 427
        }
    ]
}

**Comment by amusarra** [comment]
Salve @biadanpad 
Riguardo i dati mancanti avevamo risposto #279
In definitiva, sono restituiti solo gli identificativi e non le corrispondenti decodifiche.

L'indirizzo di residenza dovrebbe essere restituito all'interno dell'evento qualora questo sia stato inserito.

Se non ci sono ulteriori dubbi e/o chiarimenti invitiamo a chiudere la issue.

Cordiali Saluti.
Supporto ANSC.

**Comment by biadanpad** [comment]
Buongiorno, 
 - per la provincia di nascita e di residenza non viene restituito nemmeno l'id
 - per la nazionalità viene restituita la decodifica e non l'id

visto che in fase di inserimento dati viene richiesto sia l'id che la relativa decodifica sarebbe ci aspettavamo che anche come ritorno avessimo entrambi i dati.

Il servizio "Consultazione ANSC Soggetto", inoltre, risponde con entrambi i dati (id e decodifica, come da json di risposta sotto).

Servirebbe quindi uniformare le cose.

{
    "testataRisposta": {
        "idComune": 5000,
        "idOperazioneComune": "4324",
        "idOperazione": "1621755",
        "idEsito": 0
    },
    "modelEventoDTO": [{
            "id": 1111725,
            "idAnsc": "2023-1111725-1-108028",
            "idTipoEvento": "3",
            "idtipocontenuto": "1",
            "idUsecase": "311111",
            "stato": "FIRMATO DA USC",
            "dataformazione": "2023-09-04",
            "ora": "12",
            "minuto": "20",
            "annoAtto": "2023",
            "numeroatto": "1",
            "ausilioInterprete": "false",
            "idComuneRegistrazione": "5000",
            "nomeComuneRegistrazione": "LISSONE",
            "idProvinciaRegistrazione": "108",
            "siglaProvinciaRegistrazione": "MB",
            "operatore": "DLCNTN57L67A064W",
            "operatoreNome": "MARTINA",
            "operatoreCognome": "GORI",
            "allegati": [{
                    "id": 2211225,
                    "idTipoAllegato": 999,
                    "hashAllegato": "kNYDvFimmQjjMhobd63N8lXP9CLtscUSgUrDd1Qp8Vc=",
                    "descrizione": "Processo verbale",
                    "idStatoAllegato": 3
                }
            ],
            "intestatari": [{
                    "id": "2211204",
                    "codiceFiscale": "",
                    "cognome": "BIANCHINI",
                    "nome": "ARMANDO",
                    "sesso": "M",
                    "dataNascita": "1940-07-02",
                    "idComuneNascita": "427",
                    "nomeComuneNascita": "AREZZO",
                    "idProvinciaNascita": "51",
                    "siglaProvinciaNascita": "AR",
                    "idStatoNascita": "90",
                    "nomeStatoNascita": "ITALIA",
                    "idComuneResidenza": "427",
                    "nomeComuneResidenza": "AREZZO",
                    "idProvinciaResidenza": "51",
                    "siglaProvinciaResidenza": "AR",
                    "idStatoResidenza": "90",
                    "nomeStatoResidenza": "ITALIA",
                    "idNazionalita": "90",
                    "nazionalita": "ITALIANA",
                    "flagDichiarante": false,
                    "flagComparente": false,
                    "flagFirmatario": true,
                    "documentoRiconoscimento": {}
                }, {
                    "id": "2211208",
                    "codiceFiscale": "",
                    "cognome": "GUIDI",
                    "nome": "LIDIA",
                    "sesso": "F",
                    "dataNascita": "1948-01-29",
                    "idComuneNascita": "427",
                    "nomeComuneNascita": "AREZZO",
                    "idProvinciaNascita": "51",
                    "siglaProvinciaNascita": "AR",
                    "idStatoNascita": "90",
                    "nomeStatoNascita": "ITALIA",
                    "idComuneResidenza": "427",
                    "nomeComuneResidenza": "AREZZO",
                    "idProvinciaResidenza": "51",
                    "siglaProvinciaResidenza": "AR",
                    "idStatoResidenza": "90",
                    "nomeStatoResidenza": "ITALIA",
                    "idNazionalita": "90",
                    "nazionalita": "ITALIANA",
                    "flagDichiarante": false,
                    "flagComparente": false,
                    "flagFirmatario": true,
                    "documentoRiconoscimento": {}
                }
            ],
            "datiEventoMatrimonio": {
                "luogoCelebrazione": {},
                "dataEvento": "2023-09-04",
                "oraEvento": "10",
                "minutoEvento": "30",
                "officiante": "1",
                "cognomeOfficiante": "cittadino",
                "nomeOfficiante": "primo",
                "comprensioneSposo": "0",
                "comprensioneSposa": "0",
                "numeroTestimoni": "2",
                "testimone1": {
                    "cognome": "SALI",
                    "nome": "LEONARDO",
                    "sesso": "M",
                    "dataNascita": "2010-05-11",
                    "idComuneNascita": "20052",
                    "nomeComuneNascita": "PISTOIA",
                    "idProvinciaNascita": "47",
                    "siglaProvinciaNascita": "PT",
                    "idStatoNascita": "90",
                    "nomeStatoNascita": "ITALIA",
                    "idComuneResidenza": "2328",
                    "nomeComuneResidenza": "CASTELLEONE",
                    "idProvinciaResidenza": "19",
                    "siglaProvinciaResidenza": "CR",
                    "idStatoResidenza": "90",
                    "nomeStatoResidenza": "ITALIA",
                    "idNazionalita": "90",
                    "nazionalita": "ITALIANA",
                    "flagDichiarante": false,
                    "flagComparente": false,
                    "flagFirmatario": true,
                    "documentoRiconoscimento": {}
                },
                "testimone2": {
                    "cognome": "PENG",
                    "nome": "FIONA",
                    "sesso": "F",
                    "dataNascita": "2008-03-05",
                    "idComuneNascita": "4310",
                    "nomeComuneNascita": "LOCRI",
                    "idProvinciaNascita": "80",
                    "siglaProvinciaNascita": "RC",
                    "idStatoNascita": "90",
                    "nomeStatoNascita": "ITALIA",
                    "idComuneResidenza": "2328",
                    "nomeComuneResidenza": "CASTELLEONE",
                    "idProvinciaResidenza": "19",
                    "siglaProvinciaResidenza": "CR",
                    "idStatoResidenza": "90",
                    "nomeStatoResidenza": "ITALIA",
                    "idNazionalita": "36",
                    "nazionalita": "CINESE",
                    "flagDichiarante": false,
                    "flagComparente": false,
                    "flagFirmatario": true,
                    "documentoRiconoscimento": {}
                },
                "testimone3": {
                    "documentoRiconoscimento": {}
                },
                "testimone4": {
                    "documentoRiconoscimento": {}
                },
                "segretarioComunale": {
                    "documentoRiconoscimento": {}
                },
                "pubblicazioneInPiuComuni": false,
                "pubblicazione1": {
                    "idProvincia": "51",
                    "provincia": "AR",
                    "idComune": "427",
                    "comune": "AREZZO",
                    "dataInizio": "2023-01-01",
                    "dataFine": "2023-03-01"
                },
                "pubblicazione2": {},
                "omissionePubblicazione": false,
                "sentenzaOmissionePubblicazione": {},
                "rigettoOpposizione": false,
                "provvedimentoRigettoOpposizione": {},
                "estintaOpposizione": false,
                "provvedimentoEstinzioneOpposizione": {},
                "difettoEta": "1",
                "impedimentoParentela": "0",
                "divietoTemporaneo": false,
                "autorizzazioneDifettoEta": {},
                "autorizzazioneParentela": {},
                "autorizzazioneDivietoTemporaneo": {},
                "regimePatrimoniale": {
                    "tipo": "2",
                    "attoNotarile": false,
                    "assistenzaMinori": []
                },
                "figli": [],
                "datiRiconoscimento": [],
                "consensoRiconoscimento": {
                    "atto": {},
                    "altroUfficiale": {},
                    "sentenzaTribunale": {}
                },
                "impedimentoSposo": {},
                "impedimentoSposa": {}
            },
            "composizioneCompleta": "          L'anno DUEMILAVENTITRE addi' QUATTRO del mese di SETTEMBRE alle ore DIECI e minuti          TRENTA nella Casa Comunale in una sala aperta al pubblico. Avanti a me, GORI MARTINA,           Ufficiale dello Stato Civile del Comune di CASTELLEONE  vestito in forma ufficiale,          sono personalmente comparsi:                                                                                                           BIANCHINI ARMANDO  nato in AREZZO li 02.07.1940 (0/n.0/p./s.) residente in AREZZO          cittadino          --------------------------------------------------------------------------------------           GUIDI LIDIA  nata in AREZZO li 29.01.1948 (0/n.0/p./s.)residente in AREZZO cittadina                                                                                                           i quali mi hanno chiesto di unirli in matrimonio e a questo effetto mi hanno          presentato il documento sotto descritto che, munito del mio visto, inserisco nel          volume degli allegati a questo registro, insieme con quelli gia' prodotti all'atto          della richiesta della pubblicazione.          Dall'esame di tutti gli anzidetti documenti risultandomi nulla ostare alla          celebrazione del matrimonio, ho letto agli sposi gli articoli 143,144 e 147 del          Codice civile, quindi ho domandato allo sposo se intende di prendere in moglie la qui          presente GUIDI LIDIA e a questa se intende di prendere in marito il qui presente          BIANCHINI ARMANDO ; ed avendomi ciascuno risposto affermativamente a piena          intelligenza anche dei testimoni sottoindicati, ho dichiarato che i medesimi sono          uniti in matrimonio.          A quest'atto sono stati presenti quali testimoni: SABATINI RENATA nat in  li          residente in  e REALI PIERO nat in  li  residente in PALAIA. Il documento presentato          Il presente atto viene letto agli intervenuti, i quali tutti, insieme con me, lo          sottoscrivono.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 !L'UFFICIALE DI STATO CIVILE:",
            "datains": "2023-09-04T12:41:01.548186",
            "dataultimoagg": "2023-09-04T12:47:31.989104",
            "datiAnnotazione": [{
                    "tipoAnnotazione": "1",
                    "testoAnnotazione": "Il presente atto di matrimonio e' stato trascritto nei registri di stato civile del Comune di AREZZO al n._____p.II s.B anno 2023 come da comunicazione del ________\nCASTELLEONE, li'\n          L'UFFICIALE DI STATO CIVILE\n          GORI MARTINA\n"
                }, {
                    "tipoAnnotazione": "2",
                    "testoAnnotazione": "Con dichiarazione resa nell'atto di matrimonio controscritto, gli sposi hanno scelto il regime della separazione dei beni.\nCASTELLEONE, li' 04-09-2023\n          L'UFFICIALE DI STATO CIVILE:\n"
                }
            ],
            "idVersion": 100002
        }
    ],
    "datiPaginazione": {
        "numPagina": 1,
        "numRecordPagina": 30,
        "numRecordTotali": 1
    }
}

**Comment by amusarra** [comment]
Salve @biadanpad. Anche se servizi della stessa classe R005, sono due servizi diversi (contesto diverso). Il servizio di consultazione evento restituisce anche i valori delle decodifiche al contrario, il servizio di consultazione soggetti no.

Cordiali Saluti.
Supporto ANSC.

**Comment by biadanpad** [comment]
Buongiorno, 
sono ancora in attesa di risposta ai seguenti punti:

* per la provincia di nascita e di residenza non viene restituito nemmeno l'id
* per la nazionalità viene restituita la decodifica e non l'id

**Comment by amusarra** [comment]
Buongiorno @biadanpad 
Sono in corso le verifiche.
