### ISSUE TITLE
[R009] Quesito allegati su caso 345000 - Trascrizione della convenzione di negoziazione assistita

### ISSUE THREAD

**Issue by siscomanpr** [italia/ansc#326]
Caso d’uso 345000  - Trascrizione della convenzione di negoziazione assistita ai sensi dell’art.6 Decreto-legge n.132/2014 convertito con Legge 10.11.2014 n.162

Nel file di mapping vengono richiesti come allegati obbligatori questi documenti: 
- Certificazione come da articolo 5 del Decreto Legge n. 132/2014 convertito con Legge 10.11.2014 n.162
- Certificazione acquisita dall'avvocato dello sposo
- Certificazione acquisita dall'avvocato dello sposa

Per quanto riguarda l’allegato relativo alla ‘Certificazione come da articolo 5 del Decreto Legge n. 132/2014 convertito con Legge 10.11.2014 n.162’, si fa riferimento al comma 2 del citato articolo che dispone 'Gli avvocati certificano l'autografia delle firme e la conformità dell'accordo alle norme imperative e all'ordine pubblico': nei provvedimenti che in genere riceve il comune , tale certificazione è sempre inserita in calce all’accordo, prima delle firme, quindi si richiede se il documento da allegare sia l’accordo stesso che contiene anche tale certificazione. L’accordo solitamente viene trasmesso a mezzo PEC in un unico file che contiene anche l’autorizzazione del Procuratore alla trascrizione. 

Cosa si intende per ‘Certificazione acquisita dall'avvocato dello sposo’ e ‘Certificazione acquisita dall'avvocato della sposa’ visto che l’Ufficiale dello Stato Civile in genere ricevere dall'avvocato una copia dell'accordo autenticata (oppure un originale) e che allegata alla convenzione vi sia il NULLA OSTA o AUTORIZZAZIONE del Procuratore. 

Vedasi idOperazione: 1622020

**Comment by asqueglia** [comment]
Buongiorno, verifichiamo e non appena possibile ne daremo riscontro.

**Comment by asqueglia** [comment]
Buongiorno, è stata appena rilasciata la versione 1.13.0 che corregge il bug segnalato. Chiudiamo pertanto la issue; in caso di ulteriori problematiche si prega di aprirne una nuova.
