### ISSUE TITLE
segnalazione su "Condizioni obbligatorietà"

### ISSUE THREAD

**Issue by LucaBonini64** [italia/ansc#327]
Buongiorno,
faccio riferimento al caso d'uso Matr_007 ma la segnalazione vale un po' per tutte le condizioni obbligatorietà:
![condizioniobbligo](https://github.com/italia/ansc/assets/26867161/4d739caf-0258-4ef8-a417-93f9129dc405)
Nella descrizione di cui sopra il decreto del tribunale per l'autorizzazione, come allegato, non è obbligatorio ma diventa obbligatorio se il campo difettoEta è diverso da 1 e direi che è chiaro.
Scendiamo ai dati dello stesso documento e questi sono sempre obbligatori NO ma diventano obbligatori se il campo difettoEta è uguale a 1 e mi sembra strano in quanto il valore 1 equivale a 'nessun difetto d'età' ed è in evidente contrasto con quanto indicato nell'allegato.
Se scendiamo ancora ai dati richiesti per l'impedimento per parentela invece questi diventano obbligatori SI ma con la condizione che l'impedimento sia uguale a 0 che equivale a 'nessun impedimento'.
Sicuramente ci saranno dei refusi nella documentazione ma attualmente non mi è molto chiaro come legare i campi Obbligatorio e Condizioni obbligatorietà, potrei suggerire di togliere il campo obbligatorio e lasciare nel campo condizione obbligatorietà solo le condizioni che portano all'obbligatorietà del campo, ma ovviamente questo è semplicemente un suggerimento che vorrei condividere con voi.
Grazie
Luca Bonini APKAPPA

**Comment by asqueglia** [comment]
Buongiorno, sicuramente sono dei refusi che verificheremo. Non appena possibile le faremo sapere.

**Comment by asqueglia** [comment]
Buongiorno con la versione già rilasciata 1.13.0 è stata corretta la documentazione indicando la condizione di opzionalità relativa alla sezione dati; pertanto chiudiamo questa issue e nel caso di ulteriori richieste preghiamo di riaprirla.
