### ISSUE TITLE
[R005] ricerca intestatario attraverso idAnpr

### ISSUE THREAD

**Issue by MichelaGarzoni** [italia/ansc#328]
Buongiorno,
testando la ricerca dell'idAnsc del soggetto mediante il servizio R005 attraverso il solo codice idAnpr abbiamo visto che otteniamo un'anagrafica non corrispondente all'anagrafica attesa. Inoltre, per qualsiasi ricerca son solo idAnpr otteniamo sempre la stessa anagrafica dove i dati popolati sono anche esigui.

es.:
{"testataRichiesta":{"idComune":3655,"idOperazioneComune":2534,"dataOraRichiesta":"2023-05-29T08:20:47Z","nomeApplicativo":"ASCOT Stato Civile","versioneApplicativo":"21.99.0000","fornitoreApplicativo":"Insiel S.p.A"},
  "criteriRicercaSoggetto": {
"idAnpr":"83939334"
  }
}

risposta che otteniamo:
{
    "testataRisposta": {
        "idComune": 3655,
        "idOperazioneComune": "2534",
        "idOperazione": "1623343",
        "idEsito": 0
    },
    "datiPaginazione": {
        "numPagina": 1,
        "numRecordPagina": 30,
        "numRecordTotali": 0
    },
    "soggetti": [
        {
            "id": 2118484,
            "cognome": "ZITO DELL'AQUILA",
            "nome": "MARIA",
            "sesso": "F",
            "datains": null,
            "dataultimoagg": null,
            "codicefiscale": "",
            "idstato": null,
            "nazionalita": "ITALIANA",
            "dataNascita": "2020-12-31T23:00:00.000+00:00",
            "idComuneResidenza": 1819,
            "idStatoNascita": "90",
            "idStatoResidenza": "90",
            "idComuneNascita": null
        }
    ]
}

**Comment by amusarra** [comment]
Salve @MichelaGarzoni 
Potrebbe indicare quali siano i dati attesi?
Chiediamo al fine di eseguire delle veriche.

Cordiali Saluti.
Supporto ANSC.

**Comment by amusarra** [comment]
@MichelaGarzoni potrebbe indicarmi l'idEvento a cui il soggetto intestatario è collegato?

Grazie.
Supporto ANSC.

**Comment by MichelaGarzoni** [comment]
Ok, un esempio è questo appena generato:
idANSC = 2023-1111984-20230050000040-032001
idEvento = 1111984

R005 request:
{
"testataRichiesta":{
"idComune":3655
,"idOperazioneComune":"20230050000040"
,"dataOraRichiesta":"2023-09-11T15:38:38Z"
,"nomeApplicativo":"ASCOT Stato Civile"
,"versioneApplicativo":"21.99.0000"
,"fornitoreApplicativo":"Insiel S.p.A"
}
,"criteriRicercaSoggetto":{
"idAnpr":"83947824"
}
}

R005 response:
{"testataRisposta":{"idComune":3655,"idOperazioneComune":"20230050000040","idOperazione":"1623411","idEsito":0},
"datiPaginazione":{"numPagina":1,"numRecordPagina":30,"numRecordTotali":0},
"soggetti":[{"id":2118484,"cognome":"ZITO DELL'AQUILA","nome":"MARIA","sesso":"F","datains":null,"dataultimoagg":null,"codicefiscale":"","idstato":null,"nazionalita":"ITALIANA","dataNascita":"2021-01-01T00:00:00.000+00:00","idStatoNascita":"90","idStatoResidenza":"90","idComuneResidenza":1819,"idComuneNascita":null}]}

**Comment by amusarra** [comment]
Buongiorno @MichelaGarzoni 
Si, confermiamo l'evento con ID 1111984 è stato validato utilizzando  `idSoggettoAnpr=83947824` e che effettivamente non viene mappato correttamente con il soggetto ANSC e infatti il servizio di ricerca non restituisce i dati corretti.

Sono in corso le opportune verifiche.


```
{
    "testataRichiesta": {
        "idComune": 3655,
        "idOperazioneComune": "20230050000040",
        "dataOraRichiesta": "2023-09-11T15:38:27Z",
        "nomeApplicativo": "ASCOT Stato Civile",
        "versioneApplicativo": "21.99.0000",
        "fornitoreApplicativo": "Insiel S.p.A"
    },
    "evento": {
        "idVersion": "100002",
        "idTipoEvento": "2",
        "idtipocontenuto": "1",
        "idUsecase": "2101",
        "descrizioneCasoUso": "Decesso in abitazione o in luogo pubblico",
        "stato": "CONFERMATO",
        "dataformazione": "2023-09-11",
        "ora": "14",
        "minuto": "28",
        "numeroatto": "20230050000040",
        "ausilioInterprete": "FALSE",
        "idComuneRegistrazione": 3655,
        "nomeComuneRegistrazione": "DUINO AURISINA-DEVIN NABRE\u017DINA",
        "idProvinciaRegistrazione": "32",
        "siglaProvinciaRegistrazione": "TS",
        "certificabile": "1",
        "composizioneCompleta": "L\u0027anno duemilaventitre addi\u0027 undici del mese di settembre alle ore quattordici e minuti ventotto nella Casa Comunale. Avanti a me, Garzoni Michela -, Ufficiale dello Stato Civile del Comune di Duino Aurisina-Devin Nabre\u017Eina,(1)  (2) e\u0027 comparso Rossi Edoardo nato in Duino Aurisina li tre maggio millenovecentosessantotto, residente in San Dorligo Della Valle-Dolina il quale mi ha dichiarato quanto segue: Il giorno DIECI del mese di SETTEMBRE dell\u0027anno DUEMILAVENTITRE  alle ore DIECI e minuti QUARANTACINQUE Il presente atto viene letto all\u0027 intervenuto, il quale, insieme con me, lo sottoscrive.",
        "datiEventoMorte": {
            "numeroComparenti": "1",
            "comparente1": {
                "cognome": "Rossi",
                "nome": "Edoardo",
                "sesso": "M",
                "dataNascita": "1968-05-03",
                "idComuneNascita": "3655",
                "nomeComuneNascita": "DUINO AURISINA-DEVIN NABRE\u017DINA",
                "idProvinciaNascita": "32",
                "siglaProvinciaNascita": "TS",
                "idStatoNascita": "90",
                "nomeStatoNascita": "ITALIA",
                "idComuneResidenza": "004",
                "nomeComuneResidenza": "SAN DORLIGO DELLA VALLE-DOLINA",
                "idProvinciaResidenza": "032",
                "siglaProvinciaResidenza": "TS",
                "idStatoResidenza": "90",
                "nomeStatoResidenza": "ITALIA",
                "idNazionalita": "90",
                "nazionalita": "ITALIANO",
                "flagDichiarante": true,
                "flagComparente": true,
                "flagFirmatario": true
            },
            "comparente2": {}
        },
        "datiDichiarante": {
            "comprensione": "0"
        },
        "coniuge": {},
        "interprete": {},
        "datiDiMorte": {
            "idComuneMorte": "3655",
            "nomeComuneMorte": "DUINO AURISINA-DEVIN NABRE\u017DINA",
            "idProvinciaMorte": "32",
            "siglaProvinciaMorte": "TS",
            "idStatoMorte": "90",
            "nomeStatoMorte": "ITALIA",
            "dataMorte": "2023-09-10",
            "annoMorte": "2023",
            "meseMorte": "09",
            "giornoMorte": "10",
            "minutoMorte": " 45"
        },
        "intestatari": [
            {
                "idSoggettoAnpr": "83947824",
                "codiceFiscale": "GBBNDR85T24E098F",
                "cognome": "GABBI",
                "nome": "ANDREA",
                "sesso": "M",
                "dataNascita": "1985-12-24",
                "idComuneNascita": "007",
                "nomeComuneNascita": "GORIZIA",
                "idProvinciaNascita": "031",
                "siglaProvinciaNascita": "GO",
                "idStatoNascita": "90",
                "nomeStatoNascita": "ITALIA",
                "idComuneResidenza": "3655",
                "nomeComuneResidenza": "DUINO AURISINA-DEVIN NABRE\u017DINA",
                "idProvinciaResidenza": "32",
                "siglaProvinciaResidenza": "TS",
                "idStatoResidenza": "90",
                "nomeStatoResidenza": "ITALIA",
                "indirizzoResidenza": "FRAZIONE DUINO\/DEVIN 72\/P",
                "idstatocivile": "1",
                "descrizionestatocivile": "Celibe\/Nubile",
                "idNazionalita": "90",
                "nazionalita": "ITALIANO"
            }
        ]
    }
}
```
Payload - Servizio di validazione

Cordiali Saluti.
Supporto ANSC.
