### ISSUE TITLE
[R009] Internal server error in Usecase 1311

### ISSUE THREAD

**Issue by LucaBonini64** [italia/ansc#329]
Buongiorno,
non riesco a validare un evento di nascita all'estero, purtroppo mi viene restituito solamente un internal server error e non il dato errato o sbagliato, potete verificare per cortesia?
Riporto di seguito errore e json trasmesso.
Grazie
Luca Bonini APKAPPA

2023-09-11 10:17:57,613 ERROR [ANSCTestClient.Main][1][anonymous][ANSCTestClient]: 
[500 - Internal Server Error]APS.Net.REST.ServiceException: {"message":"internal.error","errors":null} ---> System.Net.WebException: Errore del server remoto: (500) Errore interno del server.

{
	"testataRichiesta": {
		"idComune": 6498,
		"idOperazioneComune": "LB20230908130600",
		"dataOraRichiesta": "2023-09-08",
		"nomeApplicativo": "StatoCivile.NET",
		"versioneApplicativo": "Test",
		"fornitoreApplicativo": "APKAPPA s.r.l."
	},
	"evento": {
		"idTipoEvento": "1",
		"idtipocontenuto": "1",
		"idVersion": "100002",
		"idUsecase": "1311",
		"descrizioneCasoUso": "Trascrizione di atto di nascita avvenuta all'estero su richiesta dell'autorita' diplomatica o consolare",
		"stato": "CONFERMATO",
		"flagSecretato": false,
		"dataformazione": "2023-09-08",
		"annoAtto": "2023",
		"meseAtto": "09",
		"giornoAtto": "08",
		"ora": "10",
		"minuto": "09",
		"idComuneRegistrazione": "6498",
		"nomeComuneRegistrazione": "NOVI LIGURE",
		"idProvinciaRegistrazione": "6",
		"siglaProvinciaRegistrazione": "AL",
		"operatore": "BNNLCU64B18L219Q",
		"ruoloOperatore": "2",
		"operatoreNome": "LUCA",
		"operatoreCognome": "BONINI",
		"redattoNellaCasaComunale": true,
		"composizioneCompleta": "L'anno duemilaventitre addì otto del mese di settembre alle ore dieci e minuti trenta nel la Casa Comunale. Io, Bonini Luca, istruttore amministrativo ed, Ufficiale dello Stato Civile del Comune di NOVI LIGURE, per delega avuta ho ricevuto da CONSOLATO GENERALE in SYDNEY (AUSTRALIA) ai sensi del Decreto Legislativo 7/3/2005, n. 82, tramite posta elettronica certificata, la richiesta in data 06/04/2023 di trascrivere ATTO DI NASCITA relativo a GELORMINO FRANCK, di cui mi ha trasmesso copia in versione elettronica. Aderendo a tale richiesta, provvedo alla trascrizione per riassunto del documento suddetto, come segue: SERVIZIO DELLO STATO CIVILE DI X (X) ATTO DI NASCITA n. X DATA E LUOGO DI NASCITA: 05/06/1999 - MELBOURNE (AUSTRALIA) - COGNOME: GELORMINO - NOME: FRANCK - SESSO: maschile PADRE: COGNOME/NOME: GELORMINO / SIMONE MADRE: COGNOME/NOME: APPLERED / MEREDITH DICHIARAZIONE DI CONFORMITA' DEI DOCUMENTI INFORMATICI CON GLI ORIGINALI CARTACEI Nel trasmettere la versione elettronica degli atti elencati di seguito (omissis) si dichiara che essi sono conformi agli originali cartacei conservati nei fascicoli personali degli interessati presso l'archivio dello scrivente ufficio. ELENCO ATTI ALLEGATI - ATTO di NASCITA di GELORMINO FRANCK MELBOURNE (AUSTRALIA) 05/06/1999. Come previsto dalla normativa vigente, ho provveduto alla stampa della documentazione ricevuta per posta elettronica, inclusa la certificazione di conformità consolare, e vi ho apposto una dichiarazione di conformità del documento stampato rispetto a quanto ricevuto per via telematica. Dopo di che ho munito del mio visto ed inserita nel volume degli allegati a questo registro la richiesta di trascrizione e la copia del documento trascritto. L'UFFICIALE DELLO STATO CIVILE: f.to Luca Bonini",
		"ausilioInterprete": false,
		"numeroatto": "20231220000000000034",
		"datiDiNascita": {
			"precisazioneCognome": "",
			"luogoFiliazione": "MELBOURNE",
			"minutoNascita": "",
			"oraNascita": "",
			"sceltaCognome": "3",
			},
		"intestatari": [
			{
			"cognome": "GELORMINO",
			"dataNascita": "1999-06-05",
			"nome": "FRANCK",
			"nomeComuneNascita": "MELBOURNE",
			"idComuneNascita": "",
			"siglaProvinciaNascita": "",
			"idProvinciaNascita": "",
			"nomeStatoNascita": "AUSTRALIA",
			"idStatoNascita": "10",
			"sesso": "M",
			}
		],
		"madre": {
			"cognome": "APPLERED",
			"dataNascita": "",
			"flagComparente": false,
			"flagDichiarante": false,
			"flagFirmatario": false,
			"nome": "MEREDITH",
			"nazionalita": "",
			"idNazionalita": "",
			"idComuneNascita": "",
			"siglaProvinciaNascita": "",
			"idProvinciaNascita": "",
			"nomeStatoNascita": "",
			"idStatoNascita": "",
			"nomeComuneNascita": "",
			"idStatoResidenza": "10",
			"nomeStatoResidenza": "AUSTRALIA",
			"idProvinciaResidenza": "",
			"siglaProvinciaResidenza": "",
			"idComuneResidenza": "",
			"nomeComuneResidenza": "RYDE",
			"sesso": "F",
		},
		"padre": {
			"cognome": "GELORMINO",
			"dataNascita": "1978-02-24",
			"flagComparente": false,
			"flagDichiarante": false,
			"flagFirmatario": false,
			"nome": "SIMONE",
			"nazionalita": "ITALIANA",
			"idNazionalita": "90",
			"idComuneNascita": "6498",
			"siglaProvinciaNascita": "AL",
			"idProvinciaNascita": "6",
			"nomeStatoNascita": "ITALIA",
			"idStatoNascita": "90",
			"nomeComuneNascita": "NOVI LIGURE",
			"idStatoResidenza": "10",
			"nomeStatoResidenza": "AUSTRALIA",
			"idProvinciaResidenza": "",
			"siglaProvinciaResidenza": "",
			"idComuneResidenza": "",
			"nomeComuneResidenza": "RYDE",
			"sesso": "M",
		},
		"trascrizioneNascita": {
			"testoLibero": "Trascrizione atto di nascita",
			"dataComunicazione": "2023-04-06",
			"atto": {
				"enteEstero": {
					"nomeAnagraficaConsolato": "SYDNEY",
					"idAnagraficaConsolato": "173",
					"nomeEnte": "CONSOLATO GENERALE SYDNEY",
					"nomeComuneEnte": "SYDNEY",
					"idComuneEnte": "",
					"siglaProvinciaEnte": "",
					"idProvinciaEnte": "",
					"nomeNazioneEnte": "AUSTRALIA",
					"nazioneEnte": "10",
				},
			},
			"attoEstero": {
				"enteEstero": {
					"dataTrascrizione": "2020-31-09",
					"descrizione": "ATTO DI NASCITA",
					"nomeEnte": "SERVIZIO DELLO STATO CIVILE",
					"estremiDocumento": "ATTO 35KY8",
					"nomeNazioneEnte": "AUSTRALIA",
					"nazioneEnte": "10",
				},
			},
		},
	"allegati": [
		{
			"id": "2212543",
			"idTipoAllegato": 26,
			"hashAllegato": "LLy9DFhX9ActuReJGM+hivF918OzO/zVWEecshY/w2I="
		},
		{
			"id": "2212540",
			"idTipoAllegato": 27,
			"hashAllegato": "FVdCSED978v7kPZKDPEwXopK5QTIEjKXsuZUCHnNP58="
		}
	]
	}
}

**Comment by amusarra** [comment]
Buongiorno @LucaBonini64 
Abbiamo preso in carico la sua segnalazione.

Cordiali Saluti.
Supporto ANSC.

**Comment by amusarra** [comment]
@LucaBonini64 validando il payload, l'attributo `dataTrascrizione` contiene un valore errato: `2020-31-09`. Mettendo la data nel formato corretto, la validazione dovrebbe andare a buon fine.

Nel caso in cui la validazione dovesse passare, le chiediamo di chiudere la issue.

Cordiali Saluti.
Supporto ANSC.

**Comment by LucaBonini64** [comment]
Buongiorno @amusarra,
la scorrettezza di quel campo mi era proprio sfuggita, adesso l'evento è stato validato, grazie.
