### ISSUE TITLE
ModelUnioneCivile - nome campi errati

### ISSUE THREAD

**Issue by siscomanpr** [italia/ansc#33]
Nel ModelUnioneCivile (model_evento.yaml) sono errati i nomi di campi impedimentoSposo e impedimentoSposa (che dovrebbero al limite essere impedimentoConiuge1/impedimentoConiuge2).
E' errato anche il PDF di Tracciato-Evento.pdf

**Comment by mttfranci** [comment]
Salve.
Si tratta del nome della proprietà (ovvero del metadato).
Anche per non impattare su chi già magari ha implementato su questa struttura, il nostro orientamento è di non modificare tali proprietà.
