### ISSUE TITLE
[R005] ricerca intestatario: data di nascita restituita non corretta

### ISSUE THREAD

**Issue by MichelaGarzoni** [italia/ansc#330]
Buongiorno,
ricercando l'anagrafica attraverso i filtri: nome, cognome, codice fiscale otteniamo l'anagrafica corretta che abbiamo inserito, ma non risulta corretta la data di nascita restituita. Abbiamo eseguito questa prova per diverse persone e la data di nascita che ci viene restituita è sempre antecedente di una gg e questo si evince anche dal codice fiscale.

Es.  request:
 {"testataRichiesta":{"idComune":3655,"idOperazioneComune":2534,"dataOraRichiesta":"2023-05-29T08:20:47Z","nomeApplicativo":"ASCOT Stato Civile","versioneApplicativo":"21.99.0000","fornitoreApplicativo":"Insiel S.p.A"},
  "criteriRicercaSoggetto": {
"codiceFiscale": "BTARFL65H27F352J"
  }
}

response:
{
    "testataRisposta": {
        "idComune": 3655,
        "idOperazioneComune": "2534",
        "idOperazione": "1623347",
        "idEsito": 0
    },
    "datiPaginazione": {
        "numPagina": 1,
        "numRecordPagina": 30,
        "numRecordTotali": 1
    },
    "soggetti": [
        {
            "id": 1983404,
            "cognome": "ABATE",
            "nome": "RAFFAELE",
            "sesso": "M",
            "datains": "2023-06-15T07:26:09.000+00:00",
            "dataultimoagg": "2023-06-15T07:26:09.000+00:00",
            "codicefiscale": "BTARFL65H27F352J",
            "idstato": null,
            "nazionalita": "LIBANESE",
            "dataNascita": "1965-06-26T23:00:00.000+00:00",
            "idComuneResidenza": 3655,
            "idStatoNascita": "90",
            "idStatoResidenza": "90",
            "idComuneNascita": 52
        }
    ]
}****

**Comment by amusarra** [comment]
Salve @MichelaGarzoni abbiamo preso in carico la segnalazione.

Cordiali Saluti.
Supporto ANSC.

**Comment by amusarra** [comment]
Salve @MichelaGarzoni 
Il problema è stato identificato e corretto. Potrebbe seguire una nuova interrogazione?
In caso positivo le chiediamo di chiudere la issue.

Cordiali Saluti.
Supporto ANSC.

**Comment by MichelaGarzoni** [comment]
Grazie @amusarra , eseguito un test di verifica ed ora la data risulta corretta.

Saluti
