### ISSUE TITLE
[R005] - Richiesta informazioni su RicercaSoggetto

### ISSUE THREAD

**Issue by DiBellaDavide** [italia/ansc#332]
Salve,
invocando il servizio /consultazione/ansc/intestatario/1 , capita alcune volte che non viene restituito nessun risultato. 
Potreste indicare cosa occorre modificare nella richiesta da noi mandata affinché vengano correttamente restituite le informazioni richieste?
Su WebApp il soggetto è presente:
![image](https://github.com/italia/ansc/assets/80926270/b7d91ed7-f67f-4248-8c14-70f3c5a9fce1)

Ambiente pre-prod
idOperazione : 1623522
idOperazione: 1623536
Data del test: 11/09/23

**Comment by amusarra** [comment]
Buongiorno @DiBellaDavide 
Analizzando i payload inviati, la risposta del servizio è corretta in quanto la data di nascita specificata è errata `"datanascita": "1966-05-31"`. Per ottenere il risultato atteso, la data di nascita deve essere `"datanascita": "1966-06-01"`.

Chiudiamo la issue.

Cordiali Saluti.
Supporto ANSC.
