### ISSUE TITLE
[R005] - IdAnpr Richiesta consultazione Intestatario

### ISSUE THREAD

**Issue by DiBellaDavide** [italia/ansc#334]
Salve,
richiamando i servizi di
/consultazione/ansc/intestatario/1
/consultazione/ansc/soggetto/1
nel caso in cui non venga passato l'idANPR i servizi rispondono correttamente, restituendo il soggetto.
Vedi idOperazione: 1624796 (soggetto), idOperazione : 1624795 (Intestatario)
Inviando invece la richiesta valorizzando l'idANPR la richiesta non va a buon fine, vedasi:
idOperazione: 1624803 (intestatario)
idOperazione: 1624804(soggetto)

Il soggetto in questione è stato inviato come titolare di un atto,valorizzando il campo idsoggettoanpr con il servizio R009, vedasi:
idOperazione: 1624744

**Comment by amusarra** [comment]
Salve @DiBellaDavide 
Abbiamo preso in carico la segnalazione, legata a quella già esistente #328 

Cordiali Saluti.
Supporto ANSC.

**Comment by asqueglia** [comment]
Buonasera, con il rilascio della versione 1.15.0 è stata corretta la segnalazione in oggetto. Chiudiamo pertanto la presente issue; in caso di ulteriori richieste di prega di aprire una issue dedicata.
