### ISSUE TITLE
Problemi con accesso alla WebApp

### ISSUE THREAD

**Issue by LucaBonini64** [italia/ansc#335]
Buongiorno,
ho problemi ad accedere alla WebApp del comune di Novi Ligure utilizzando la CNS, cliccando sul certificato con il mio codice fiscale esce:
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<env:Envelope xmlns:env="[http://schemas.xmlsoap.org/soap/envelope/">](http://schemas.xmlsoap.org/soap/envelope/%22%3E)
env:Body
env:Fault
env:Client
Rejected by policy. (from client)
</env:Fault>
</env:Body>
</env:Envelope>

L'accesso con lo SPID invece funziona regolarmente, vuol dire che non è più utilizzabile la CNS con il certificato?
Grazie

Luca Bonini APKAPPA

**Comment by amusarra** [comment]
Salve @LucaBonini64 
Abbiamo appena eseguito una prova di accesso via CNS (tramite certificato) senza alcun problema.
Potreste riprovare?

Grazie.
Supporto ANSC.

**Comment by LucaBonini64** [comment]
Buongiorno @amusarra ,
continua a darmi lo stesso messaggio, allego la schermata:
![accessoWebApp](https://github.com/italia/ansc/assets/26867161/e9bdc46c-b3cb-4a25-b070-365a00aba73a)

Cordiali Saluti

**Comment by LucaBonini64** [comment]
Mi ha dato il problema la prima volta ieri ma non accedevo alla WebApp da inizio settimana scorsa quindi non so esattamente da quando si verifica.
Per accedere in modalità anonima che cosa intendete?
Grazie.

**Comment by amusarra** [comment]
Buongiorno @LucaBonini64 
Abbiamo recuperato i certificati a lei assegnati non riscontrando problemi di accesso alla Web Application.
Ha avuto modo di riprovare?
Solitamente quel tipo di errore capita quando uno dei due certificati non arriva al componente di sicurezza di ANSC.
Controlli che i certificati siano installati correttamente sulla postazione che usa per accedere alla Web Application di ANSC.

Se dovesse risolvere la invitiamo a chiudere la issue.

<img width="1471" alt="image" src="https://github.com/italia/ansc/assets/708110/5ff82127-da70-418d-be66-8604eb5d8b1f">

Cordiali Saluti.
Supporto ANSC.

**Comment by LucaBonini64** [comment]
Buongiorno,
non ho fatto nessuna modifica ma adesso il sistema funziona e sembra leggere in automatico il certificato personale
