### ISSUE TITLE
[R009] validazione caso d'uso 1365

### ISSUE THREAD

**Issue by siscomanpr** [italia/ansc#336]
Buongiorno, 
segnaliamo che per il caso 1335 - Trascrizione della comunicazione scritta trasmessa dal direttore dell'istituto che accoglie un minore abbandonato,
riceviamo come errore di validazione:
400003  -  Il campo evento.intestatari[0].siglaProvinciaNascita nella sezione Minore ritrovato non corrisponde al pattern ^[0-9]*$

idOperazione: 1626658

**Comment by amusarra** [comment]
Salve @siscomanpr
Abbiamo preso in carico la segnalazione.

Cordiali Saluti.
Supporto ANSC.

**Comment by asqueglia** [comment]
Buongiorno, è stata appena rilasciata la versione 1.13.0 che corregge il bug segnalato. Chiudiamo pertanto la issue; in caso di ulteriori problematiche si prega di aprirne una nuova.
