### ISSUE TITLE
[R006] - errore: l'atto non è in stato CONFERMATO

### ISSUE THREAD

**Issue by LucaBonini64** [italia/ansc#337]
Buongiorno,
abbiamo fatto un atto di matrimonio con Usecase 311111 (IdEvento=1112106) e per quest'atto abbiamo previsto un set di firme miste come consentito dalla #19.
Quindi un testimone ha firmato digitalmente sul link inviato mentre gli sposi e l'altro testimone hanno firmato in maniera cartacea.
Nell'inviare il servizio R006 però il sistema restituisce un errore in quanto l'atto non è nello stato confermato:
{"errors":[{"code":"400003","severity":"E","text":"Non è possibile firmare l'atto, perchè non è in stato = CONFERMATO"}],"testataRisposta":{"idComune":6498,"idEsito":1,"idOperazione":"1626687","idOperazioneComune":"LB20230914164800"}}
Anche guardando dalla WebApp in effetti l'atto è in stato "firmato dal Dichiarante", mentre è stato firmato da uno solo dei dichiaranti, quindi forse l'errore è l'errato passaggio di stato?
Cordiali saluti.
Luca Bonini APKAPPA

**Comment by amusarra** [comment]
Buongiorno @LucaBonini64 
Abbiamo preso in carico la segnalazione.

Cordiali Saluti.
Supporto ANSC.

**Comment by LucaBonini64** [comment]
Buongiorno @amusarra.
mi spiace segnalarvi che il problema continua a persistere, escludo di aver richiamato più volte il servizio e riprovando a fare le stesse operazioni (in questo caso invertendo le firme a causa dell'errore segnalato nella isse #378) dopo aver inserito la firma cartacea di parte dei dichiaranti (in questo caso sposa e testimoni) con "idOperazione": "1644177", l'atto di matrimonio passa subito nello stato FIRMATO DAL DICHIARANTE:
![Immagine 2023-10-03 124937](https://github.com/italia/ansc/assets/26867161/eecc4a7a-bc0c-44ce-bc0b-cbaabc059d1e)
inibendo altre attività legate alla firma.

Ad esempio visto che il servizio di firma elettronica del dichiarante è temporaneamente inutilizzabile abbiamo annullato il link con "idOperazione": "1644216" senza problemi, poi però quando riproviamo a richiedere una nuova anteprima per far firmare in maniera cartacea anche lo sposo il sistema restituisce il solito errore:
{"testataRisposta":{"idComune":6498,"idOperazioneComune":"LB20231003114400","idOperazione":"1644218","idEsito":1},"errors":[{"code":"400003","severity":"E","text":"Lo stato dell'atto non e' CONFERMATO e non consente l'operazione"}]}

**Comment by amusarra** [comment]
@LucaBonini64 
Stiamo cercando di riprodurre il caso con le informazioni estratte dai nostri sistemi.
Potrebbe indicarci esattamente gli step eseguiti in termini di servizi chiamati?
In questo modo per noi sarà più agevole cercare di replicare il problema.

Grazie.
Supporto ANSC.

**Comment by amusarra** [comment]
Salve @LucaBonini64 
Seguendo la cronologia delle chiamate da voi eseguite, non siamo ancora riusciti a replicare il problema.
Voi riuscite a replicarlo in modo sistematico?

Grazie.
Supporto ANSC.

**Comment by amusarra** [comment]
Salve @LucaBonini64 
Il servizio di anteprima `{{R010}}/anteprima/evento/1` per presa visione (flag `presaVisione=true`), restituisce il PDF se e solo se lo stato dell'evento è `CONFERMATO`. In tutti gli altri casi restituisce l'errore a seguire.

```
{
    "testataRisposta": {
        "idComune": 580,
        "idOperazioneComune": "APP2022032210000",
        "idOperazione": "1649730",
        "idEsito": 1
    },
    "errors": [
        {
            "code": "400003",
            "severity": "E",
            "text": "Lo stato dell'atto non e' CONFERMATO e non consente l'operazione"
        }
    ]
}
```
Payload di risposta servizio {{R010}}/anteprima/evento/1 

Segnaliamo inoltre, che l'anteprima per presa visione, può essere ottenuta, specificando i soli parametri a seguire.

```
    [...]
    "evento": {
        "idEvento": "{{idEvento}}",
        "idAnsc": "{{idAnsc}}"
    },
    "presaVisione": true
    [...]
```
Payload richiesta anteprima per presa visione in modalità short

Se non ci sono ulteriori dubbi e/o chiarimenti, vi chiediamo di chiudere la issue.

Cordiali Saluti.
Supporto ANSC.

**Comment by amusarra** [comment]
Salve @LucaBonini64 
Ha avuto modo di leggere la mia risposta?
Qualora fosse esaustiva le chiederei di chiudere la issue.

Cordiali Saluti.
Supporto ANSC.

**Comment by amusarra** [comment]
Buongiorno @LucaBonini64 
Purtroppo l'unica via è l'annullamento dell'evento e poi presentare tutti i firmatari nella modalità cartacea.
Le chiediamo di chiudere la issue qualore non ci fossero ulteriori dubbi.

Cordiali Saluti.
Supporto ANSC.

**Comment by amusarra** [comment]
> Prendo atto e mi chiedo a cosa serva il servizio R012 per l'annullamento del link inviato al dichiarante se comunque la soluzione è annullare l'evento, comunque l'indicazione è chiara quindi chiudo la issue. Grazie.

@LucaBonini64 l'operazione di annullamento può essere usato per esempio, nel caso in cui per qualche motivo la mail non sia arrivata al destinarlo, quindi, si annulla per poi risottomettere la richiesta al fine di tentare un nuovo invio della mail contenente il link di presa visione.

Cordiali Saluti.
Supporto ANSC.
