### ISSUE TITLE
usecase 444000	Conferma dell'accordo di scioglimento dell'unione civile tra persone dello stesso sesso	(Sciogl_UnCiv_004)

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#340]
Buongiorno,
nel mapping  il campo "serie" relativamente all'atto di accordo risulta essere obbligatorio

Accordo scioglimento | Serie | SI | evento.scioglimentoUnioneCivile.accordoScioglimento | serie |   | obbligatoria

Il Ministero ha previsto che gli atti di Unione Civile avessero solo la Parte, senza nessuna Serie.
Al momento il json viene validato anche se metto un qualsiasi carattere (ad esempio un trattino). 
Va bene valorizzarlo con un dato non veritiero o è un bug?

**Comment by asqueglia** [comment]
Prendiamo in carico la verifica per valutare se rendere serie opzionale. Grazie per la segnalzione

**Comment by asqueglia** [comment]
Buongiorno con il rilascio della versione 1.13 è stata corretta la segnalazione. Chiudiamo pertanto la issue; in caso ci fossero ulteriori problemi si prega di aprire una altra issue dedicata.
