### ISSUE TITLE
[R009] validazione caso 1343 - allegati richiesti mancanti in tabella

### ISSUE THREAD

**Issue by siscomanpr** [italia/ansc#341]
Caso d'uso 1343   -   Trascrizione della sentenza di revoca della adozione di minore in casi particolari

Il file di mapping del caso d'uso in oggetto (Trascr_015), prevede come allegati obbligatori:
- Copia integrale dell'atto di nascita intestatario 
- Sentenza del tribunale 

Ma questi 2 allegati non esisto nella tabella di decodifica 9_dec_tipo_allegato.
Anche provando con dei tipi di allegato simili viene restituito errore di allegato obbligatorio mancate (esempio idOperazione: 1627657)

In merito a questo problema di non corrispondenza tra le descrizioni degli allegati richiesti nei files di magging e quanto presente in tabella allegati, avevamo già aperto la issue https://github.com/italia/ansc/issues/75 che è stata chiusa come risolta, ma ci rendiamo conto solo ora che il problema persiste. In quella issue avevo già segnalato lo stesso caso d'uso come esempio di mancata corrispondenza tra le descrizioni e per questo avevamo proposto/richiesto di aggiungere anche il codice dell'allegato nei files di mapping.
Rinnovo quindi la segnalazione, o perlomeno che vengano corrette le descrizioni errate degli allegati richiesti per tutti i casi d'uso che soffrono di questo problema.

Ringrazio per l'attenzione.

Siscom SPA

**Comment by amusarra** [comment]
Salve @siscomanpr 
Abbiamo preso in carico la segnalazione.

Cordiali Saluti.
Supporto ANSC.

**Comment by asqueglia** [comment]
Buongiorno, è stata appena rilasciata la versione 1.13.0 che corregge il bug segnalato. Chiudiamo pertanto la issue; in caso di ulteriori problematiche si prega di aprirne una nuova.
