### ISSUE TITLE
[R009] Caso 12226203 - Riconoscimento infraquattordicenne

### ISSUE THREAD

**Issue by siscomanpr** [italia/ansc#342]
12226203 - Riconoscimento di figlio di ignoti infraquattordicenne da parte della madre con presenza padre 

Per il caso d'uso in oggetto il sistema richiede l'indicazione dell'atto di assenso del figlio anche se non si compila il campo `evento.datiEventoRiconoscimento.assensoFiglio` (tra l'altro non obbligatorio).
Inoltre ci chiedevamo se è normale che, trattandosi di figlio infraquattordicenne, vengano richiesti i dati dell'assenso per questo caso d'uso.

idOperazione: 1627954

Siscom SPA

**Comment by asqueglia** [comment]
Buongiorno verifichiamo. Grazie per la segnalazione provvederemo a correggere.

**Comment by asqueglia** [comment]
Buonasera con la versione 1.14, la segnalazione è stata corretta. Pertanto l'issue viene chiusa; nel caso di ulteriori segnalazioni si prega di aprirne una altra.
