### ISSUE TITLE
[R009]: decodifiche non presenti per il ModelDocumentoRiconoscimento.

### ISSUE THREAD

**Issue by gcuci** [italia/ansc#343]
buongiorno,

segnaliamo la mancanza delle decodifiche per 2 delle proprietà del ModelDocumentoRiconoscimento.

Nello swagger, è indicata la decodifica ANSC_20, per la proprietà 'rilasciatoDa', che non è però presente nell'elenco dei file di decodifica.

Sempre nello swagger, invece, per la proprietà 'tipologiaDocumento', non è indicata alcuna decodifica, mentre ad un tentativo di inviare i dati con una richiesta, il servizio restituisce la mancanza di rispetto di un pattern numerico, aspettandosi un codice.

Di seguito, la parte del json di Request, con il dettaglio del ModelDocumentoRiconoscimento, obbligatorio per il caso d'uso Citt_011:

        "documentoRiconoscimento": {
          "numeroDocumento": "AX7139606",
          "tipologiaDocumento": "Carta di identita",
          "dataScadenza": "2033-08-06",
          "rilasciatoDa": "Comune",
          "dataRilascio": "2023-08-16"
        }
		
ed il json di Response:

{
  "testataRisposta": {
    "idComune": 595,
    "idOperazioneComune": "5099",
    "idOperazione": "1628522",
    "idEsito": 1
  },
  "errors": [
    {
      "code": "400003",
      "severity": "E",
      "text": "Il campo evento.intestatari[0].documentoRiconoscimento.tipologiaDocumento nella sezione Documento di riconoscimento non corrisponde al pattern ^[0-9]*$"
    },
    {
      "code": "400003",
      "severity": "E",
      "text": "Il campo evento.intestatari[0].documentoRiconoscimento.rilasciatoDa nella sezione Documento di riconoscimento non corrisponde al pattern ^[0-9]*$"
    }
  ]
}

da cui si evince il numero dell'operazione, eseguita questa mattina, nell'ambiente di pre-produzione.

In attesa di riscontro,

cordiali saluti.

**Comment by amusarra** [comment]
Buongiorno @gcuci 
Con il prossimo rilascio saranno rilasciate le due decodifiche mancanti.
Nel frattempo i valori previste che potreste già usare sono:

Rilasciato Da:
1. valore 1 => Ministero degli Interni
2. valore 2 => Comune

Tipologia Documento Riconoscimento:
1. valore 1 => Patente
2. valore 2 => Passaporto
3. valore 3 => Carta Identita

Cordiali Saluti.
Supporto ANSC.

**Comment by asqueglia** [comment]
Buongiorno, è stata appena rilasciata la versione 1.13.0 che corregge il bug segnalato. Chiudiamo pertanto la issue; in caso di ulteriori problematiche si prega di aprirne una nuova.

**Comment by AMonopoliADS** [comment]
in riferimento a questa issue (e alla stessa segnalazione fatta con issue #229 ) segnalo che con la versione appena rilasciata è stata pubblicata solo la tabella con le codifiche degli enti di rilascio (tabella '20') e non anche quella con le decodifiche delle tipologie di documento.
