### ISSUE TITLE
Web App oggi non funzionante

### ISSUE THREAD

**Issue by migmar68** [italia/ansc#344]
Buongiorno
Non riusciamo a usare la Web App di preproduzione : dopo aver scelto "entra con CNS" e il codice fiscale del certificato.

```
<env:Envelope xmlns:env="http://schemas.xmlsoap.org/soap/envelope/">
<env:Body>
<env:Fault>
<faultcode>env:Client</faultcode>
<faultstring>Rejected by policy. (from client)</faultstring>
</env:Fault>
</env:Body>
</env:Envelope>
```

**Comment by amusarra** [comment]
Salve @migmar68 
Al momento non risultano malfunzionamenti a riguardo.
Potrebbe riprovare l'accesso?
Consiglio di eseguire l'accesso con il browser in modalità anonima verificando che i certificati necessari siano installati correttamente.

Grazie.
Supporto ANSC.

**Comment by migmar68** [comment]
Grazie, sì è da 1 o 2 ore che  riusciamo a utilizzarla.
