### ISSUE TITLE
[R001] verifica stato allegato - ritorna sempre 2 (In corso di verifica)

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#345]
Sto tentando di collegare 3 allegati ad un atto di morte (caso d'uso 2213), ma per 2 di essi lo stato di verifica risulta sempre 2 (In corso di verifica).

Di seguito i relativi payload:

*** Nota di trasmissione da parte dell'autorità consolare o diplomatica
REQUEST:
{
    "idAllegato": "2215345",
    "testataRichiesta": {
        "idComune": 5000,
        "idOperazioneComune": "",
        "dataOraRichiesta": "2023-09-19T12:53:29.187+02:00",
        "nomeApplicativo": "urbi",
        "versioneApplicativo": "0.1.0",
        "fornitoreApplicativo": "padigitale"
    }
}

RESPONSE:
{
    "testataRisposta": {
        "idComune": 5000,
        "idOperazioneComune": "",
        "idOperazione": "1628838",
        "idEsito": 0
    },
    "allegatoOutput": {
        "idAllegato": "2215345",
        "statoAllegato": "2",
        "idDocumentum": null
    }
}

*** Atto di morte (in originale)
REQUEST:
{
    "idAllegato": "2215346",
    "testataRichiesta": {
        "idComune": 5000,
        "idOperazioneComune": "",
        "dataOraRichiesta": "2023-09-19T12:53:32.898+02:00",
        "nomeApplicativo": "urbi",
        "versioneApplicativo": "0.1.0",
        "fornitoreApplicativo": "padigitale"
    }
}

RESPONSE:
{
    "testataRisposta": {
        "idComune": 5000,
        "idOperazioneComune": "",
        "idOperazione": "1628839",
        "idEsito": 0
    },
    "allegatoOutput": {
        "idAllegato": "2215346",
        "statoAllegato": "2",
        "idDocumentum": null
    }
}

**Comment by amusarra** [comment]
Buongiorno @biadanpad 
Abbiamo preso in carica la vostra segnalazione.

Cordiali Saluti.
Supporto ANSC.

**Comment by amusarra** [comment]
@biadanpad potreste fornire l'idOperazione relativa all'upload del file per cui lo stato è rimasto pari a 2?
Al momento non riusciamo a replicare il problema.

Cordiali Saluti.
Supporto ANSC.

**Comment by biadanpad** [comment]
Purtroppo l'idOperazione dell'upload non ce l'ho più: era salvato su un file temporaneo che è stato eliminato.

Ho appena rifatto un test, ma adeso sembra funzionare tutto regolarmente.

**Comment by amusarra** [comment]
@biadanpad noi non siamo riusciti a replicarlo su diversi upload. 
In ogni caso cercheremo di capire la problematica.

Cordiali Saluti.
Supporto ANSC.

**Comment by asqueglia** [comment]
Buongiorno, è stata appena rilasciata la versione 1.13.0 che corregge il bug segnalato. Chiudiamo pertanto la issue; in caso di ulteriori problematiche si prega di aprirne una nuova.
