### ISSUE TITLE
[R009]: ufficialeStatoCivile nel ModelEvento.

### ISSUE THREAD

**Issue by gcuci** [italia/ansc#348]
buonasera,

nella Request del servizio di validazione, valorizziamo i dati dell'operatore (nome, cognome, CF, ...), che vengono interpretati come dati dell'USC.

Sempre nel ModelEvento, però, c'è la proprietà ufficialeStatoCivile (un ModelSoggetto), il cui significato non è chiaro.

Abbiamo provato a valorizzarla (vd, operazione num: 1629031), in una validazione effettuata correttamente, ma sembra che questa informazione non venga utilizzata in alcun modo.

Potete darci un riscontro?

Cordiali saluti.

**Comment by asqueglia** [comment]
Buongiorno, confermiamo che l'elemento ufficialeStatoCivile  presente nel data model è un refuso. Provvederemo a renderlo deprecato con il prossimo rilascio. L'operatore è l'elemento del data model che deve essere valorizzato con i dato dell'USC responsabile dell'atto.
