### ISSUE TITLE
Caso d'uso Citt_013: ancora chiarimenti su "Condizioni obbligatorietà"

### ISSUE THREAD

**Issue by antonioluberto** [italia/ansc#349]
Pur a valle delle indicazioni contenute in https://github.com/italia/ansc/issues/307, le indicazioni relative alle generalità di padre/madre continuano a non essere chiare:

![image](https://github.com/italia/ansc/assets/26415430/65c7675d-599d-4748-a886-c62a33f2f6c6)

Qual è effettivamente il valore da utilizzare tra i due possibili che vengono indicati?
Se eventualmente deve essere l'applicazione locale a definire se riportare l'uno o l'altro dei due valori, qual è la condizione funzionale da verificare?

In tutti gli altri casi d'uso, il campo "Condizioni obbligatorietà" presenta il riferimento ad un solo valore.

**Comment by asqueglia** [comment]
Buongiorno, è stata appena rilasciata la versione 1.13.0 che corregge la documentazione come anticipato. Chiudiamo pertanto la issue; in caso di ulteriori problematiche si prega di aprirne una nuova.
