### ISSUE TITLE
[R006] firma dichiarante: protocollo, stato e firmatari

### ISSUE THREAD

**Issue by MichelaGarzoni** [italia/ansc#35]
Buongiorno, ho alcuni dubbi relativi al servizio R006 sulla firma del dichiarante:

- **protocollo**: dovrei avere un numero di protocollo relativo all'atto? Ho appena inviato l'atto al servizio di validazione, ho quindi  richiesto il servizio di anteprima e lo stampo per far apporre le firme autografe ai vari firmatari: che numero dovrei inserire per poi inviarlo con questo servizio?
- **stato**: fa riferimento alla tabella di dizionario ANSC_8 ma, nell'inviare l'atto firmato con modalità autografa, quale di queste voci devo utilizzare? Sembrano più stati di risposta al mio invio che non stati relativi all'invio dell'atto firmato
- **listaFirmatari**: nello yaml è presente mentre nell'esempio dei servizi questa voce non è presente: è necessaria la sua compilazione? Essendo un array mi aspetto quindi di inserire i dati di tutti i firmatari autografi dell'atto. Mi permane un dubbio: posso avere situazioni miste di firmatari sia digitali che autografe (come mi sembra di aver capito avvenga nella vostra web-app)? In quel caso sarebbe auspicabile far firmare prima chi utilizza la firma digitale e poi successivamente chi utilizza la firma autografa (questo considerando il caso in cui la firma digitale non vada a buon fine: se ho preinviato quelle autografe dovrei annullare l'invio ed eseguire un nuovo reinvio con la persona aggiuntiva..)?

**Comment by amusarra** [comment]
Salve @MichelaGarzoni.

- il protocollo se non disponibile può mettere qualque stringa != empty (esempio: N/A);
- lo stato deve essere impostato al valore uno, che assume il significato di allegato ricevuto/inviato (poi questo sarà scansionato come ogni altro tipo di allegato);
- la listaFirmatari è opzionale. Nel caso in cui non è specificato, il processo di firma sarà applicato a tutti firmatari dell'evento. Nel caso in cui listaFirmatari sia presente, il processso di firma sarà applicato ai soli firmatari specificati.

È necessario specificare la listaFirmatari nel caso in cui per l'evento oggetto di firma, ci sono due firmatari di cui uno firma per via autografa e l'altro per in forma digitale o per presa visione. 

A seguire un esempio dell'elemento listaFirmatari.

```
        "listaFirmatari": [
            {
                "nome": "MARIO",
                "cognome": "ROSSI",
                "codiceFiscale": "MRORSS89H28H501Y"
            }
        ] 
```
Source Code 1 - Esempio dell'elemento listaFirmatari

Per altri dubbi e/o chiarimenti restiamo a disposizione.

Saluti.
Supporto ANSC.
