### ISSUE TITLE
[web-service] Matrimoni (idUseCase 331000): Firma Dic / Firma Usc / Messaggi

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/ansc#350]
ambiente PRE - comune di Valeggio sul Mincio (idComune 10420)

alcune segnalazioni / richieste chiarimenti nell'ambito dei test effettuati sul caso d'uso:
331000 - Trascrizione matrimoni dall'estero - Richiesta di trascrizione da parte dell'interessato

1. il cliente ci segnala che non gli risulta ci siano dichiarazioni firmate dal dichiarante in questa fattispecie di evento, per cui non si spiega la necessità dell'invio del servizio di firma R006, e si chiede cosa inviare come allegato.

2. per andare avanti nel processo, è stato inviato sia il servizio R006 (Firma Dic) sia il servizio R007 (Firma USC).
il servizio R007 ha risposto con l'errore "Stato evento non valido per l'operazione richiesta".
grazie ad una stessa situazione segnalata con issue #181, abbiamo capito che l'errore era causato dal fatto che la Firma USC è stata richiesta oltre le 2 ore previste dall'avvenuta Firma Dic.
mi chiedo: se il problema è legato al "recupero dell'atto firmato dal dichiarante entro un tempo prestabilito (2 ore)", perchè non segnalare esattamente che il problema è quello? "stato evento non valido per l'operazione richiesta" non fa capire qual è il problema, soprattutto tenuto conto che lo stato dell'evento, in quel momento, era "FIRMATO DAL DICHIARANTE".

3. come suggerito dalla issue citata, abbiamo annullato l'atto con servizio R011 e abbiamo ripetuto tutte le operazioni.
è emersa un'altra situazione anomala: una volta inviato il servizio di Firma Dic (R006), lo stato dell'atto è rimasto CONFERMATO senza passare allo stato FIRMATO DAL DICHIARANTE. nonostante questo, l'invio del servizio di Firma USC (R007) è andato a buon fine.
potete verificare l'atto con idAnsc 2023-1112398-123-023089. 
dalla sequenza di operazioni eseguite dovreste vedere che i servizi di consultazione (R005) eseguiti dopo l'invio della Firma Dic (R006) hanno restituito lo stato CONFERMATO
ws R009 (validazione) - idOperazioneComune 2023000204 (20/09/2023 12:10:12)
ws R006 (firma dic) - idOperazioneComune 2023000210 (20/09/2023 12:13:28)
ws R005 (consultazione) - idOperazioneComune 2023000208 (20/09/2023 12:13:53) - stato CONFERMATO
ws R005 (consultazione) - idOperazioneComune 2023000211 (20/09/2023 12:14:28) - stato CONFERMATO
ws R007 (firma usc) - idOperazioneComune 2023000203 (20/09/2023 12:14:51)
ws R005 (consultazione) - idOperazioneComune 2023000212 (20/09/2023 12:15:12) - stato FIRMATO DA USC

grazie
Alessandro Monopoli ADS

**Comment by amusarra** [comment]
Salve @AMonopoliADS 
Abbiamo preso in carico la segnalazione.

Cordiali Saluti.
Supporto ANSC.

**Comment by asqueglia** [comment]
Buonasera con la versione 1.14, la segnalazione è stata corretta. Pertanto l'issue viene chiusa; nel caso di ulteriori segnalazioni si prega di aprirne una altra.
