### ISSUE TITLE
[Tutti i servizi]: Mancanza di dettaglio nell'eventuale errore restituito.

### ISSUE THREAD

**Issue by gcuci** [italia/ansc#351]
buongiorno,

segnaliamo la necessità di avere un maggior dettaglio in alcune anomalie che vengono restituite e che risultano essere troppo generiche.

Riportiamo un paio di esempi, ma la segnalazione vale in generale su tutti i servizi.

Il servizio di validazione evento (R009), restituisce, in diverse circostanze l'errore 'Dati in ingresso non corretti'. Di seguito un esempio di Response, con relativo idOperazione:

{
  "testataRisposta": {
    "idComune": 595,
    "idOperazioneComune": "5269",
    "idOperazione": "1629489"
  },
  "errors": [
    {
      "code": "400003",
      "severity": "E",
      "text": "Dati in ingresso non corretti"
    }
  ]
}

In questo caso si trattava di un evento di Matrimonio (caso d'uso Matr_001), ed è probabile che l'anomalia dipenda da qualche obbligatorietà condizionata su cui stiamo indagando. Ma soprattutto per i servizi di validazione, che prevedono numerosissimi metadati da inviare, risulta molto complicato risalire alla causa dell'anomalia, senza avere alcuna indicazione dalla sua descrizione.

Un altro esempio è relativo al servizio di Firma USC (R007). Di seguito la Response con relativo idOperazione, di un errore generico che spesso viene restituito:

{
  "errors": [
    {
      "code": "406004",
      "severity": "E",
      "text": "Stato evento non valido per l'operazione richiesta"
    }
  ],
  "testataRisposta": {
    "idComune": 595,
    "idOperazione": "1629412",
    "idOperazioneComune": "5247"
  }
}

In questo caso, molto probabilmente dipende dal tempo trascorso dopo la firma del dichiarante. E l'evento andrebbe annullato (è un caso d'uso Sep_Div_005). Ma la mancanza di dettaglio nella descrizione, non permette di essere certi della causa.

Chiediamo se è possibile aggiungere, al messaggio generico, l'informazione puntuale della causa dell'anomalia.

In attesa di riscontro,

cordiali saluti.

**Comment by amusarra** [comment]
Salve @gcuci 
Abbiamo preso in carico la segnalazione.

Cordiali Saluti.
Supporto ANSC.

**Comment by asqueglia** [comment]
Buonasera con la versione 1.14, la segnalazione è stata corretta. Pertanto l'issue viene chiusa; nel caso di ulteriori segnalazioni si prega di aprirne una altra.
