### ISSUE TITLE
Composizione del certificato e dell’estratto di morte.

### ISSUE THREAD

**Issue by gcuci** [italia/ansc#355]
Buonasera,

Trasmettiamo le segnalazioni del Comune di Bagnacavallo relativamente ai documenti in oggetto:

1. Generalità. Mancano data e luogo di nascita della persona, che costituiscono parti essenziali del concetto di generalità. La normativa parla solo di generalità ma è palese, e possiamo trovare decine e decine di orientamenti in tal senso degli esperti in materia, che le generalità sono quegli elementi che consentono di identificare la persona e, pertanto, oltre a nome e cognome vanno ritenuti essenziali anche luogo e data di nascita.

2. Generalità. Una vecchia circolare del Ministero dell'Interno (n. 15 del 9/12/1994) specificava che in tutti i certificati, stato civile incluso, nelle generalità dovesse anche essere incluso il codice fiscale. Sarebbe quindi opportuno inserirlo anche nei certificati ed estratti di stato civile, o in alternativa il codice univoco Anpr.

3. L'estratto riporta nelle annotazioni quella degli estremi di registrazione dell'atto di nascita, ma tale annotazione è da sempre NON certificabile in quanto non modifica elementi sostanziali dell'atto, al pari dell'avvenuta trascrizione negli atti di nascita e matrimonio che non si riportano.

in attesa di riscontro,

cordiali saluti.

**Comment by asqueglia** [comment]
Buongiorno verificheremo le prime due richieste con ANUSCA in quanto i certificati generati dal sistema erano stati già validati così come prodotti. Per la terza segnalazione, invece, comunichiamo che è previsto un ulteriore rilascio per la gestione della certificabilità delle annotazioni. Comunicheremo quando disponibili.

**Comment by asqueglia** [comment]
Buongiorno , per la prima richiesta prenderemo in carico la segnalazione provvedendo ad aggiungere nei certificati ed estratti data e luogo di nascita, se presente, all'intestatario in alto a sinistra; per la seconda segnalazione invece le indicazioni ricevute sono
le generalità risultanti nella certificazione devono riportare quanto indicato nell'atto di nascita, dove non è previsto né il codice fiscale né il codice ANPR.

**Comment by asqueglia** [comment]
Buonasera con la versione 1.14, la segnalazione è stata corretta. Pertanto l'issue viene chiusa; nel caso di ulteriori segnalazioni si prega di aprirne una altra.
