### ISSUE TITLE
[R009]: chiarimenti mapping casi d'uso Matrimonio.

### ISSUE THREAD

**Issue by gcuci** [italia/ansc#356]
buongiorno,

per i casi d'uso di Matrimonio (lo abbiamo riscontrato per Matr_001 ed il Matr_007, ma abbiamo lo stesso dubbio anche per gli altri), non ci è chiara l'obbligatorietà condizionata delle proprietà 'rigettoOpposizione' e 'estintaOpposizione', del datiEventoMatrimonio (ModelMatrimonio).

Per gli allegati è indicato che se rigettoOpposizione=true, è obbligatorio il 'Rigetto del Tribunale all'opposizione', e se estintaOpposizione=true, è obbligatoria la 'Ordinanza che dichiara estinto il giudizio di opposizione'.

Nei metadati, invece (ci sembra che le condizioni di obbligatorietà, siano da considerare al contrario, rispetto agli allegati), se rigettoOpposizione=true, dovrebbe essere obbligatorio il 'provvedimentoRigettoOpposizione' (ModelEnteDichiarante). Ma anche se estintaOpposizione=true, è indicato come obbligatorio, sempre il 'provvedimentoRigettoOpposizione', mentre ci aspettavamo l'obbligatorietà del 'provvedimentoEstinzioneOpposizione'.

Pensavamo fosse un refuso di copia/incolla, ma provando ad invocare il servizio di validazione, risponde come impostato nel file di mapping.

Di seguito, parte del json di Request, con estintaOpposizione=true e rigettoOpposizione=false, per un caso d'uso Matr_007: 

...
      "omissionePubblicazione": false,
      "rigettoOpposizione": false,
      "estintaOpposizione": true,
      "provvedimentoEstinzioneOpposizione": {
        "nomeEnte": "Tribunale",
        "idComuneEnte": "595",
        "nomeComuneEnte": "BAGNACAVALLO",
        "idProvinciaEnte": "39",
        "siglaProvinciaEnte": "RA",
        "dataTrascrizione": "2023-09-06",
        "estremiDocumento": "Sentenza"
      },
...

e la Response del servizio:

{
  "testataRisposta": {
    "idComune": 595,
    "idOperazioneComune": "5361",
    "idOperazione": "1631542",
    "idEsito": 1
  },
  "errors": [
    {
      "code": "400003",
      "severity": "E",
      "text": "Il campo evento.datiEventoMatrimonio.provvedimentoRigettoOpposizione.dataTrascrizione nella sezione Opposizione - Estinzione giudizio è obbligatorio"
    },
    {
      "code": "400003",
      "severity": "E",
      "text": "Il campo evento.datiEventoMatrimonio.provvedimentoRigettoOpposizione.estremiDocumento nella sezione Opposizione - Estinzione giudizio è obbligatorio"
    },
    {
      "code": "400003",
      "severity": "E",
      "text": "Il campo evento.datiEventoMatrimonio.provvedimentoRigettoOpposizione.nomeEnte nella sezione Opposizione - Estinzione giudizio è obbligatorio"
    },
    {
      "code": "400003",
      "severity": "E",
      "text": "Il campo evento.datiEventoMatrimonio.provvedimentoRigettoOpposizione.idProvinciaEnte nella sezione Opposizione - Estinzione giudizio è obbligatorio"
    },
    {
      "code": "400003",
      "severity": "E",
      "text": "Il campo evento.datiEventoMatrimonio.provvedimentoRigettoOpposizione.siglaProvinciaEnte nella sezione Opposizione - Estinzione giudizio è obbligatorio"
    },
    {
      "code": "400003",
      "severity": "E",
      "text": "Il campo evento.datiEventoMatrimonio.provvedimentoRigettoOpposizione.idComuneEnte nella sezione Opposizione - Estinzione giudizio è obbligatorio"
    },
    {
      "code": "400003",
      "severity": "E",
      "text": "Il campo evento.datiEventoMatrimonio.provvedimentoRigettoOpposizione.nomeComuneEnte nella sezione Opposizione - Estinzione giudizio è obbligatorio"
    }
  ]
}

da cui si evince l'idOperazione (1631542), e come il servizio richieda il 'provvedimentoRigettoOpposizione'.

Volevamo avere conferma, sulla corretta interpretazione che abbiamo dato della nuova colonna che è stata aggiunta nei file di mapping, sulle condizioni di obbligatorietà (logica opposta tra allegati e metadati), e se è così, vi chiediamo se possibile utilizzare per entrambi la stessa. E chiarimenti sulle obbligatorietà conseguenti alla valorizzazione delle due proprietà 'rigettoOpposizione' e 'estintaOpposizione'.

In attesa di riscontro,

cordiali saluti.

**Comment by asqueglia** [comment]
Buongiorno facciamo una verifica e faremo sapere non appena possibile
