### ISSUE TITLE
"Data atto" per atto digitale: richiesta aggiornamento controllo

### ISSUE THREAD

**Issue by antonioluberto** [italia/ansc#357]
Con particolare riferimento al caso d'uso Citt_014 (ma verosimilmente l'impostazione è di carattere generale), laddove si  
debba indicare nella sezione:

![image](https://github.com/italia/ansc/assets/26415430/c3e457d5-fc53-4384-b973-b3106925219d)

il riferimento ad un atto (di nascita in questo caso), è sempre obbligatoria, tra le altre informazioni, la "data dell'atto".

Nel caso in cui l'atto collegato sia digitale (e, quindi, identificato univocamente dall'identificativo nazionale) è possibile rimuovere l'obbligatorietà sul campo "data dell'atto"?

**Comment by asqueglia** [comment]
Buongiorno, la data dell'atto è la data di formazione dell'atto collegato. Sia che si tratti di un atto digitale che di un atto cartaceo, è una informazione che si dovrebbe avere a disposizione indipendentemente dall'identificativo univoco dell'atto. Comunque verificheremo la semplificazione richiesta

**Comment by asqueglia** [comment]
Buongiorno con la versione 1.21.0 è stata resa opzionale la data formazione dell'atto collegato in citt_014. In valutazione se estendere anche asd altri casi d'uso di tipo trascrizione. Pertanto al momento provvediamo a chiudere la issue. Se ci fossero ukteriori segnalzioni la preghiamo di aprire una issue dedicata.
