### ISSUE TITLE
[R005] consultazione intestatario: risultati diversi in relazione ai campi di ricerca inseriti

### ISSUE THREAD

**Issue by MichelaGarzoni** [italia/ansc#358]
Buongiorno,
abbiamo provato ad eseguire delle ricerche di intestatari utilizzando diversi criteri (idANPR per residente: riteniamo sia quello più corretto; codice fiscale ; dati minimali per identificarne la persona) ma otteniamo risultati diversi. Utilizzando codice fiscale e dati anagrafici abbiamo lo stesso risultato (unica anagrafica) mentre ne otteniamo uno diverso quando effettuiamo la ricerca attraverso idANPR. Questo risultato inoltre è privo dell'idANSC del soggetto e quindi di poca utilità se pensato da utilizzare per recuperare l'idANSC del soggetto: contiene solo con i dati anagrafici principali del soggetto. 
A questo punto abbiamo il dubbio su quali sono i corretti filtri da impostare per effettuare una ricerca degli intestatari nel caso si voglia recuperarne l'idANSCsoggetto.

Nell'atto validato ("idEvento":"1112347", "idAnsc":"2023-1112347-20230050000046-032001" ) che ha inserito il soggetto avevamo anche, tra i dati inviati, l'"idSoggettoAnpr":"83944569" e per questo motivo non riusciamo a capire perchè abbiamo esiti diversi.

Prove eseguite:
1.  se eseguiamo la ricerca dell'intestatario (servizio R005) per idANPR:

{"testataRichiesta":{"idComune":3655,"idOperazioneComune":2534,"dataOraRichiesta":"2023-09-22T08:20:47Z","nomeApplicativo":"ASCOT Stato Civile","versioneApplicativo":"21.99.0000","fornitoreApplicativo":"Insiel S.p.A"},
  "criteriRicercaSoggetto": {
"idAnpr":"83944569"
  }
}

-- risposta
{
    "testataRisposta": {
        "idComune": 3655,
        "idOperazioneComune": "2534",
        "idOperazione": "1631567",
        "idEsito": 0
    },
    "datiPaginazione": {
        "numPagina": 1,
        "numRecordPagina": 30,
        "numRecordTotali": 0
    },
    "soggetti": [
        {
            "id": **null,**
            "cognome": "BABBINI",
            "nome": "FRANCESCA",
            "sesso": "F",
            "datains": **null,**
            "dataultimoagg": **null,**
            "codicefiscale": "BBBFNC71E59L424I",
            "idstato": null,
            "nazionalita": null,
            "dataNascita": "1971-05-19T00:00:00.000+00:00",
            "idComuneNascita": 10255,
            "idComuneResidenza": 3655,
            "idStatoNascita": "90",
            "idStatoResidenza": "90"
        }
    ]
}

2. ricerca intestatario (R005) per codice fiscale

{"testataRichiesta":{"idComune":3655,"idOperazioneComune":2534,"dataOraRichiesta":"2023-09-22T08:20:47Z","nomeApplicativo":"ASCOT Stato Civile","versioneApplicativo":"21.99.0000","fornitoreApplicativo":"Insiel S.p.A"},
  "criteriRicercaSoggetto": {
"codiceFiscale":"BBBFNC71E59L424I"
  }
}

-- risposta
{
    "testataRisposta": {
        "idComune": 3655,
        "idOperazioneComune": "2534",
        "idOperazione": "1631571",
        "idEsito": 0
    },
    "datiPaginazione": {
        "numPagina": 1,
        "numRecordPagina": 30,
        "numRecordTotali": 1
    },
    "soggetti": [
        {
            "id": 2215456,
            "cognome": "BABBINI",
            "nome": "FRANCESCA",
            "sesso": "F",
            "datains": "2023-09-19T14:44:59.000+00:00",
            "dataultimoagg": "2023-09-20T17:00:07.000+00:00",
            "codicefiscale": "BBBFNC71E59L424I",
            "idstato": null,
            "nazionalita": "ITALIANA",
            "dataNascita": "1971-05-19T00:00:00.000+00:00",
            "idComuneNascita": 6,
            "idComuneResidenza": 3655,
            "idStatoNascita": "90",
            "idStatoResidenza": "90"
        }
    ]
}

3.  ricerca intestatario (R005) per cognome, nome...

{"testataRichiesta":{"idComune":3655,"idOperazioneComune":2534,"dataOraRichiesta":"2023-09-22T08:20:47Z","nomeApplicativo":"ASCOT Stato Civile","versioneApplicativo":"21.99.0000","fornitoreApplicativo":"Insiel S.p.A"},
  "criteriRicercaSoggetto": {
"cognome":"BABBINI","nome":"FRANCESCA","sesso":"F","dataNascita":"1971-05-19"
  }
}

-- risposta:
{
    "testataRisposta": {
        "idComune": 3655,
        "idOperazioneComune": "2534",
        "idOperazione": "1631572",
        "idEsito": 0
    },
    "datiPaginazione": {
        "numPagina": 1,
        "numRecordPagina": 30,
        "numRecordTotali": 1
    },
    "soggetti": [
        {
            "id": 2215456,
            "cognome": "BABBINI",
            "nome": "FRANCESCA",
            "sesso": "F",
            "datains": "2023-09-19T14:44:59.000+00:00",
            "dataultimoagg": "2023-09-20T17:00:07.000+00:00",
            "codicefiscale": "BBBFNC71E59L424I",
            "idstato": null,
            "nazionalita": "ITALIANA",
            "dataNascita": "1971-05-19T00:00:00.000+00:00",
            "idComuneNascita": 6,
            "idComuneResidenza": 3655,
            "idStatoNascita": "90",
            "idStatoResidenza": "90"
        }
    ]
}

**Comment by amusarra** [comment]
Salve @MichelaGarzoni 
Il servizio `{{R005}}/consultazione/ansc/intestatario` restituisce i soggetti ANSC che sono collegati ad atti/eventi digitali. 

Nel caso in cui sia specificato l'attributo idAnpr, può accadere:
1. Nel caso in cui l'idAnpr sia presente solo sul sistema ANPR, il servizio restituirà solo i dati presenti su ANPR, ragion per cui è corretto che nella risposta l'attributo `soggetti[].id` (che corrisponde all'idSoggettoAnsc) sia null;
2. Nel caso in cui l'idAnpr sia associato a un soggetto ANSC, il servizio restituirà i dati completi del soggetto ANSC.

Nel suo caso specifico, controllando il payload dell'evento validato, abbiamo notato che l'attributo `idSoggettoAnpr` è stato trasmesso in modo errato, secondo le specifiche OpenAPI, deve essere `idsoggettoanpr`, quindi, non è stata creato il collegamento tra soggetto ANPR e soggetto ANSC.

Nel caso di ulteriori dubbi e/o chiarimenti non esitate a scrivere, in caso contrario vi invitiamo a chiudere la issue.

Saluti.
Supporto ANSC.

**Comment by MichelaGarzoni** [comment]
Grazie @amusarra , 
il tag non ci ha mai dato errore e per quello non ci siamo accorti della sua scorretta definizione. Ora provvediamo a correggere e a fare delle ulteriori prove.
