### ISSUE TITLE
[ws R001] Upload - Errore generico

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/ansc#359]
ambiente PRE - comune di Valeggio sul Mincio (idComune 10420)

```
        "idOperazioneComune": 2023000213,
        "dataOraRichiesta": "2023-09-22T08:43:57",
```
si tenta di inviare in upload l'attestazione di nascita richiesta per il caso d'uso.
il servizio risponde con errore, indicando solo l'elemento "operation" con questo valore: "/services/service/doc/allegato/upload/1"

lo stesso problema si presentava in passato, nelle circostanze in cui nel JWT non veniva inviato il claim "sub".

in questo caso il JWT è completo, quindi non capiamo xchè la comunicazione vada in errore.

grazie.
Alessandro Monopoli ADS

**Comment by amusarra** [comment]
Salve @AMonopoliADS 
Immagino che abbiate verificato anche che la firma JWS detached sia corretta.

Al fine di poter eseguire le verifiche, è necessario che forniate:
1. indirizzo IP pubblico con cui uscite in rete;
2. JWT;
3. JWS;
4. Payload.

Cordiali Saluti.
Supporto ANSC.

**Comment by AMonopoliADS** [comment]
buongiorno Antonio.

onestamente, ieri non ho verificato il JWS perchè mi aspetto - in presenza di anomalie - una segnalazione del tipo: "Errore nella validazione del JWS". 
ho comunque verificato questa mattina e non ho trovato anomalie.

ho inviato tutto quanto richiesto alla tua mail personale.

attendo riscontro.
grazie
Alessandro

**Comment by AMonopoliADS** [comment]
c'è qualche aggiornamento su questa segnalazione?
grazie

**Comment by amusarra** [comment]
Buongiorno @AMonopoliADS 
Sono state adeguate le configurazioni per accettare file di dimensioni <= 5MByte.

Vi chiediamo di eseguire un test e nel caso chiudere la issue.

Cordiali Saluti.
Supporto ANSC.

**Comment by AMonopoliADS** [comment]
con gli interventi effettuati, l'errore è stato risolto. chiudo la issue. grazie
