### ISSUE TITLE
[R005] - consultazione

### ISSUE THREAD

**Issue by siscomanpr** [italia/ansc#36]
Interrogando il servizio R005 con la funzione `/consultazione/ansc/intestatario/{version}` riceviamo il seguente errore: 
> {"testataRisposta":{"idComune":9419,"idOperazioneComune":"202300000000000000000000004767","idOperazione":"1571757"},"datiPaginazione":null,"errors":[{"code":"500","severity":"E","text":"Errore interno"}],"success":null,"infos":null,"warnings":null}

Ambiente di preproduzione
idOperazione 1571757

Allego la richiesta: 
[Request.log](https://github.com/italia/ansc/files/11027643/Request.log)

**Comment by asqueglia** [comment]
Buongiorno abbiamo preso in carico il problema riscontrato sul servizio /consultazione/ansc/intestatario/{version}. Avvisiamo non appena rilasceremo la correzione.

**Comment by amusarra** [comment]
> Segnalo inoltre che la funzione `/consultazione/ansc/soggetto/{version}` se come parametri di ricerca del soggetto si indica solo il campo idAnpr del soggetto (presumendo che sia un'opzione valida, visto l'univocità del codice anpr del soggetto a livello nazionale), restituisce errore `HTTP/1.1 500 Internal Server Error` idOperazione=1571904
> 
> Sempre con la funzione `/consultazione/ansc/soggetto/{version}`, indicando i parametri completi per la ricerca del soggetto, ricevo una risposta positiva (200), ma l'array di modelEventoDTO è popolato con N eventi tutti uguali. idOperazione=1571781 Allego la risposta che ricevo: [Response.log](https://github.com/italia/ansc/files/11029292/Response.log)

Anche per questo problema abbiamo preso in carico la risoluzione. Avvisiamo non appena rilasceremo la correzione.

**Comment by asqueglia** [comment]
Buongiorno, con il rilascio odierno 1.6.0 abbiamo risolto la problematica.
