### ISSUE TITLE
[R002] request timed out

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#360]
Tentando di ottenere l'estratto per copia integrale, il servizio va in timeout (10 secondi).

Di seguito il payload della richiesta:

{
    "idAnsc": "2023-1112770-2-108028",
    "idEvento": "1112770",
    "richiedente": {
        "codiceFiscale": "GROMTN86D46G999I",
        "cognome": "GORI",
        "nome": "MARTINA",
        "sesso": "F",
        "dataNascita": "1986-04-06",
        "idComuneNascita": "7631",
        "nomeComuneNascita": "PRATO",
        "idProvinciaNascita": "48",
        "siglaProvinciaNascita": "FI",
        "idStatoNascita": "90",
        "nomeStatoNascita": "ITALIA",
        "idComuneResidenza": "7630",
        "nomeComuneResidenza": "PRATO",
        "idProvinciaResidenza": "100",
        "siglaProvinciaResidenza": "PO",
        "idStatoResidenza": "90",
        "nomeStatoResidenza": "ITALIA",
        "indirizzoResidenza": "",
        "idNazionalita": "90",
        "nazionalita": "ITALIANA"
    },
    "intestatario": {
        "id": "2212336"
    },
    "idTipoCertificato": "3",
    "conPaternitaMaternita": false,
    "testataRichiesta": {
        "idComune": 5000,
        "idOperazioneComune": "4338",
        "dataOraRichiesta": "2023-09-25T17:03:50.293+02:00",
        "nomeApplicativo": "urbi",
        "versioneApplicativo": "0.1.0",
        "fornitoreApplicativo": "padigitale"
    }
}

**Comment by amusarra** [comment]
Buongiorno @biadanpad 
Abbiamo preso in carico la sua segnalazione.

Cordiali Saluti.
Supporto ANSC.

**Comment by amusarra** [comment]
Salve @biadanpad 
Il problema dovrebbe essere rientrato. Potrebbe verificare?
Nel caso le chiediamo di chiudere la issue.

Cordiali Saluti.
Supporto ANSC.

**Comment by biadanpad** [comment]
Il problema sembra essere risolto
