### ISSUE TITLE
[ws R009] Validazione - Unione Civile [idUseCase 411211]: ImpedimentoSposo / impedimentoSposa

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/ansc#362]
nell'ambito dei test sul caso d'uso 411211 - Unione Civile fuori dalla casa comunale, abbiamo verificato (come da documentazione) che in base al valore del campo SoggettoImpedimentoCivile diventano obbligatorie le sezioni impedimentoSposo e/o impedimentoSposa.

contestualmente, abbiamo visto che risultano obbligatori tutti gli elementi di identificazione del comune (idComune, nomeComune, idProvincia, siglaProvincia) che però ci pare non vengano utilizzati nel testo dell'atto (abbiamo fatto una prova anche nella web-app).

è possibile evitarne l'obbligatorietà se non ne viene fatto un uso specifico?

grazie

**Comment by amusarra** [comment]
Salve @AMonopoliADS 
Faremo delle verifiche.

Cordiali Saluti.
Supporto ANSC.

**Comment by amusarra** [comment]
Salve @AMonopoliADS 
Anche se i dati "visivamente" non sono utilizzati, sono in ogni caso necessari per il sistema ANSC.
Chiudiamo la issue. In caso di ulteriori dubbi e/o chiarimenti non esitate a riaprire la issue.

Cordiali Saluti.
Supporto ANSC.
