### ISSUE TITLE
[R009] ID UseCase 2213 (Morte_007) errata segnalazione

### ISSUE THREAD

**Issue by DorianoP** [italia/ansc#363]
Nella response ad una request per lo UseCase in oggetto, il sistema segnala un errore con la seguente dicitura:
"Per proseguire é necessario che la La data dataNascita sia successiva alla dataTrascrizione."

Presumo sia un errore in quanto la dataNascita di un deceduto non può essere successiva a quella dell'atto trascritto, vi chiedo pertanto di effettuare le dovute verifiche, grazie.

{"testataRisposta":{
"idComune":10288,
"idOperazioneComune":"12",
"idOperazione":"1635884",
"idEsito":1},
"errors":[{
"code":"400003",
"severity":"E",
"text":"Per proseguire é necessario che la La data dataNascita sia successiva alla dataTrascrizione."}]

**Comment by amusarra** [comment]
Salve @DorianoP 
Abbiamo preso in carico la segnalazione.

Cordiali Saluti.
Supporto ANSC.

**Comment by amusarra** [comment]
Salve @DorianoP 
Com'è possibile evincere dal payload JSON di richiesta del servizio, l'intestatario nato il **"1930-08-05"** presenta una data di morte successiva (**2023-09-13**) ma una **dataTrascrizione** (in questo caso la dataComunicazione della trascrizione), valorizzata come **"0001-01-01"** _dunque precedente alla data di nascita_.

Essendo lo UseCase 2213 una trascrizione, viene considerata come maggiormente prioritaria la data inserita nella trascrizione (evento.trascrizioneMorte.dataEvento o evento.trascrizioneMorte.dataComunicazione) rispetto a quella inserita in dati di morte.

Occorre quindi inserire dei dati coerenti in **"trascrizioneMorte"**, una **"dataComunicazione"** _successiva alla data di nascita dell'intestatario_

Con il prossimo rilascio, nel messaggio di risposta sarà più evidente il campo preso in considerazione.

Cordiali Saluti.
Supporto ANSC.

**Comment by DorianoP** [comment]
Ho capito, faccio le opportune verifiche e modifiche, grazie.
