### ISSUE TITLE
Mancato aggiornamento changelog per "Morte_007"

### ISSUE THREAD

**Issue by antonioluberto** [italia/ansc#364]
Ci siamo accorti che sulla documentazione di riferimento per il caso d'uso in oggetto non sono più presenti i campi:

![image](https://github.com/italia/ansc/assets/26415430/c54cdb7f-0a5d-4b30-ac07-8acef400a0a3)

![image](https://github.com/italia/ansc/assets/26415430/ecf778eb-7a17-4ddd-8888-b988e08dc50b)

Questi erano certamente documentati fino alla versione 1.9.0, versione valida al momento della nostra implementazione applicativa.

Dal rilascio 1.10.0 i campi effettivamente non si trovano più sui modelli di riferimento, ma nessuna indicazione a riguardo è presente sul relativo changelog (né in alcuno dei changelog riferiti ad aggiornamenti successivi).

Ci sfugge qualcosa o effettivamente si è avuto un mancato aggiornamento della documentazione?
Se si, potreste verificare quali altre modifiche siano eventualmente state introdotte senza la necessaria indicazione sui changelog?

Grazie,
Antonio

**Comment by asqueglia** [comment]
Buongiorno, provvederemo a verificare e ad aggiornare il changelog li dove necessario. Grazi per la segnalzione

**Comment by asqueglia** [comment]
Abbiamo verificato che le modifiche sopra menzionate erano presenti nel changelog di dettaglio, tra la 1.9 e la 1.10 di cui allego il link

https://github.com/italia/ansc/blob/v1.10.0/docs/Mapping_casi_uso/changelog_mapping.md

**Comment by asqueglia** [comment]
Buonasera chiudiamo la issue; in caso ci siano ulteriori richieste preghiamo di aprirne una altra dedicata.
