### ISSUE TITLE
usecase matr_999_1 e matr_999_2 incongruenza tra colonne

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#365]
Buongiorno,
ho notato un'incongruenza di informazioni tra due colonne (vedi selezione in giallo e in rosso con due tag di esempio).
Visto i messaggi che ho ricevuto, per l'ora e i minuti di decorrenza, durante il tentativo di Valida Atto mi pare di capire che la colonna da prendere in considerazione sia quella in rosso. Per gli altri tag dichiarati nella colonna gialla a NO e in quella rossa OBBLIGATORIO, come devo comportarmi? A quale delle due colonne è quella corretta?
![Cattura](https://github.com/italia/ansc/assets/127182190/baa6507b-73b3-4ebc-b837-3a711666e8f3)

**Comment by asqueglia** [comment]
Buonasera chiudiamo la issue; in caso ci siano ulteriori richieste la preghiamo di aprire una altra issue dedicata.
