### ISSUE TITLE
[R009] - Trascr_UnCiv_999: Campi obbligatori di provincia e comune

### ISSUE THREAD

**Issue by DiBellaDavide** [italia/ansc#366]
Salve,
invocando il servizio di validazione per il caso d'uso in esame vengono richiesti come obbligatori i dati su provincia e comune, indicati come non obbligatori nel file di mapping associato.
![image](https://github.com/italia/ansc/assets/80926270/ec40263a-ea54-4b17-8e71-b8cb627cee3e)

idOperazione: 1638010
Data del test: 28/09/2023
Ambiente di pre-prod

**Comment by asqueglia** [comment]
Buonasera chiudiamo la issue; in caso ci siano ulteriori richieste preghiamo di aprirne una altra dedicata.
