### ISSUE TITLE
Changelog 1.13 - Cambio nome colonna 'condizioni obbligatorietà'

### ISSUE THREAD

**Issue by LucaBonini64** [italia/ansc#367]
Buongiorno,
nella versione 1.13 è stato cambiato il nome della colonna 'condizioni obbligatorietà' in 'Si puo' ignorare la sezione per' come preannunciato nella issue #349.
Quindi adesso tale colonna è riferita all'intera sezione e contiene la casistica per cui tutta la sezione può essere omessa dal flusso, volevo quindi sapere se per i singoli campi ci saranno delle condizioni di obbligatorietà oppure se vale semplicemente la colonna 'Obbligatorio' senza alcun tipo di condizione.
Vi segnalo inoltre che cambiando il nome della colonna adesso per gli allegati la descrizione è esattamente al'opposto, ad esempio nel caso di Matr_007 l'allegato 'Decreto del tribunale per autorizzazione omesse pubblicazioni' si può ignorare se {evento.datiEventoMatrimonio.omissionePubblicazione,=,true} mentre presumo che l'allegato sarà obbligatorio se esiste una omissione della pubblicazione.
Cordiali saluti

Luca Bonini APKAPPA

**Comment by asqueglia** [comment]
Buongiorno, confermiamo tutte le sue osservazioni; ringraziamo per la segnalazione in merito agli allegati. Provvederemo a verificare la documentazione correggendola appena possibile.

**Comment by asqueglia** [comment]
Buongiorno abbiamo appena rilasciato la versione 1.13.1 che corregge la segnalazione indicata. Pertanto provvediamo a chiudere la issue. In caso di ulteriori approfondimenti si prega di riaprirne una altra dedicata.
