### ISSUE TITLE
[R009] IDUseCase 339999 - Trasc_Matr_999 - comuneEstero obbligatorio

### ISSUE THREAD

**Issue by DorianoP** [italia/ansc#368]
Nel tracciato Trasc_Matr_999 vieni indicato il campo comuneEstero nell'oggetto evento.datiEventoMatrimonio.luogoCelebrazione
ma luogoCelebrazione ha lo schema ModelLuogo nel quale non è definito il campo comuneEstero.

In effetti se nella request viene indicato uno stato estero, la response segnala l'errore:
"Il campo evento.datiEventoMatrimonio.luogoCelebrazione.comuneEstero nella sezione Dati generali è obbligatorio"
Nonostante abbiamo aggiunto il campo comuneEstero, di tipo stringa, nello schema ModelLuogo l'errore rimane.
Estratto della request:
"datiEventoMatrimonio":{
"luogoCelebrazione":{"
idComune":"0",
"nomeComune":"BERNA",
"idProvincia":"0",
"siglaProvincia":"EE",
"idStato":"173",
"nomeStato":"SVIZZERA",
"comuneEstero":"BERNA"}

**Comment by asqueglia** [comment]
Buongiornro verifichiamo. Ringraziamo per la segnalazione
