### ISSUE TITLE
Segnalazione su model_evento.yaml - modelSoggetto

### ISSUE THREAD

**Issue by siscomanpr** [italia/ansc#37]
Nel file yaml, sotto il modelSoggetto è presente il campo "datanascita", quando viene importato da swagger viene indicato così com'è, ma i controlli di validazione dei servizi ansc impongono che sia scritto "dataNascita", costringendo ogni volta che si reimporta per intero il modello a modificare manualmente il codice auto-generato da swagger.
Potete correggere voi il file yaml?

**Comment by mttfranci** [comment]
Salve @siscomanpr  abbiamo allineato l'openapi all'implementazione (da datanascita a dataNascita).
Saluti

Assistenza ANSC
