### ISSUE TITLE
[R009] caso d'uso 12214300 Riconoscimento di nascituro da parte del padre con presenza della madre

### ISSUE THREAD

**Issue by SandroDeFlorio** [italia/ansc#370]
Buonasera sono Sandro De Florio sviluppatore della KIBERNETES. Vorrei segnalarvi questa anomalia ; nela caso d'uso in oggetto inviando l'atto di riconoscimento mi viene ritornato un errore del tipo
{"testataRisposta":{"idComune":10288,"idOperazioneComune":"12","idOperazione":"1641326","idEsito":1},"errors":[{"code":"400003","severity":"E","text":"Per proseguire è necessario che la data di nascita del soggetto sia antecedente alla data di nascita del Padre"},{"code":"400003","severity":"E","text":"Per proseguire è necessario che la data di nascita del soggetto sia antecedente alla data di nascita della Madre"}]}

Il caso in esame è la fattispecie di riconoscimento di figlio nascituro da parte di entrambi dichiarato ante nascita al tempo della gestazione della madre (per il neonato non è ancora nato). Nello schema Rico003 viene formata la parte relativa all'intestatario al cui interno non valorizzata la data di nascita (giustamente perchè deve ancora nascere). Vorrei sapereperchè è generato l'errore.
Allego la testata gson della trasmissione con i riferimenti dell'operazione. Grazie per la collaborazione.

	"testataRichiesta": {
		"idComune": 10288,
		"idOperazioneComune": 12,
		"dataOraRichiesta": "2023-09-29 16:29:03",
		"nomeApplicativo": "PEDemografici",
		"versioneApplicativo": "1",
		"fornitoreApplicativo": "Kibernetes srl"
	},

**Comment by asqueglia** [comment]
Buongiorno, abbiamo analizzato la richiesta da voi inviata e ci siamo accorti che inviate in maniera errata una data di nascita dell'intestatario nello specifico 0001-01-01, che il sistema non riesce ad interpretare e da ciò l'errore.
Per il caso d'uso in oggetto non deve essere inviato l'intestatario proprio perchè si tratta di riconoscimento ante nascita, come giustamente avete indicato.
Di seguito per utilità vi invio un payload di esempio corretto

  "evento": {
        "id": 575330,
        "idTipoEvento": "1",
        "idtipocontenuto": "1",
        "idUsecase": "12214300",
        "descrizioneCasoUso": "Riconoscimento di nascituro da parte del padre con presenza della madre",
        "stato": "CONFERMATO",
        "dataformazione": "2023-10-02",
        "ora": "06",
        "minuto": "50",
        "annoAtto": "2023",
        "numeroatto": "1232",
        "tipoDichiarante": "3",
        "ausilioInterprete": "false",
        "idComuneRegistrazione": "1000000",
        "nomeComuneRegistrazione": "ANPR",
        "idProvinciaRegistrazione": "58",
        "siglaProvinciaRegistrazione": "RM",
        "operatore": "CRUMRA67S47Z127B",
        "ruoloOperatore": "3",
        "operatoreNome": "MARIE",
        "operatoreCognome": "CURIE",
        "redattoNellaCasaComunale": true,
        "sentenzaFiglioIncestuoso": false,
        "datiProdotti": "",
        "allegati": [
            {
                "id": 559104,
                "idTipoAllegato": 12,
                "hashAllegato": "kuuyGfA/k6bmtOSe31s3PtsA87HBTKyKIW8Ll8nCg3k=",
                "descrizione": "Certificato medico attestante lo stato di gravidanza"
            }
        ],
        "madre": {
            "id": "XXXXX",
            "idsoggettoanpr": "XXXX",
            "codiceFiscale": "XXXXXXX",
            "cognome": "XXXXX",
            "nome": "Angela",
            "sesso": "F",
            "dataNascita": "2020-05-01",
            "idComuneNascita": "8165",
            "nomeComuneNascita": "ROMA",
            "idProvinciaNascita": "58",
            "siglaProvinciaNascita": "RM",
            "idStatoNascita": "90",
            "nomeStatoNascita": "ITALIA",
            "idComuneResidenza": "2780",
            "nomeComuneResidenza": "CESENA",
            "idProvinciaResidenza": "40",
            "siglaProvinciaResidenza": "FC",
            "idStatoResidenza": "90",
            "nomeStatoResidenza": "ITALIA",
            "indirizzoResidenza": "",
            "idNazionalita": "90",
            "nazionalita": "ITALIANA",
            "flagDichiarante": false,
            "flagComparente": true,
            "flagFirmatario": true,
            "documentoRiconoscimento": {}
        },
        "padre": {
            "id": "43500",
            "idsoggettoanpr": "XXXX",
            "codiceFiscale": "XXXXX",
            "cognome": "XXXX",
            "nome": "ANDREA",
            "sesso": "M",
            "dataNascita": "1989-06-28",
            "idComuneNascita": "18345",
            "nomeComuneNascita": "ROMA",
            "idProvinciaNascita": "58",
            "siglaProvinciaNascita": "RM",
            "idStatoNascita": "90",
            "nomeStatoNascita": "ITALIA",
            "idComuneResidenza": "2780",
            "nomeComuneResidenza": "CESENA",
            "idProvinciaResidenza": "40",
            "siglaProvinciaResidenza": "FC",
            "idStatoResidenza": "90",
            "nomeStatoResidenza": "ITALIA",
            "indirizzoResidenza": "",
            "idNazionalita": "11",
            "nazionalita": "AUSTRIACA",
            "flagDichiarante": true,
            "flagComparente": false,
            "flagFirmatario": true,
            "documentoRiconoscimento": {}
        },
        "datiDichiarante": {
            "comprensione": "0",
            "motivoImpedimentoScrittura": ""
        },
        "datiEventoRiconoscimento": {
            "mesiDalConcepimento": "3",
            "discendenti": [],
            "attoNascita": {}
        },
        "riconoscimento": {
            "autorizzazione": {},
            "certificato": {
                "autorita": "ospedale",
                "data": "2023-10-01"
            },
            "atto": {}
        },
        "composizioneCompleta": "XXXXXXXX.",
        "datains": "2023-10-02T06:51:02.093658",
        "dataultimoagg": "2023-10-02T06:53:05.697823",
        "flagsecretato": 0,
        "idVersion": 100002
    }

**Comment by asqueglia** [comment]
Buonasera chiudiamo la issue; in caso ci siano ulteriori richieste preghiamo di aprirne una altra dedicata.
