### ISSUE TITLE
[R005] consultazione evento annotazione 

### ISSUE THREAD

**Issue by siscomanpr** [italia/ansc#371]
Buongiorno,
tentando di consultare un evento di annotazione con il servizio R005 per ottenere l'oggetto modelEvento (comprensivo del testo dell'annotazione), il sistema restituisce sempre un modelEventoDTO vuoto. 
L'url chiamato è : https://anscservicepre.anpr.interno.it/services/service/ricerca/consultazione/ansc/evento/1

**idOperazione: 1641722**

Attualmente come parametro stiamo passando solo l'IDANSC dell'evento da consultare.
Cosa sbagliamo?
Faccio presente che l'IDANSC che stiamo cercando di consultare è riferito ad un'annotazione ricevuta con il servizio R008 di ricerca notifiche.

Siscom SPA

**Comment by amusarra** [comment]
Buongiorno @siscomanpr 
Abbiamo preso in carico la segnalazione e sono in corso le verifiche.

Cordiali Saluti.
Supporto ANSC.

**Comment by siscomanpr** [comment]
Buongiorno, 
avete novità in merito a questa segnalazione? 
Ci interessa sapere almeno se è un problema lato ANSC o siamo noi che stiamo chiamando nel modo errato il servizio.
In particolare, vorremmo poter consultare il dettaglio dell'annotazione automatica di cui abbiamo ricevuto la notifica. 
Il procedimento corretto è usare il servizio "R005 / consultazione per evento" passando come parametro l'idANSC dell'annotazione automatica?

Grazie per l'attenzione.

**Comment by asqueglia** [comment]
Buonasera, con il rilascio della versione 1.15.0 è stata corretta la segnalazione in oggetto. Chiudiamo pertanto la presente issue; in caso di ulteriori richieste di prega di aprire una issue dedicata.
