### ISSUE TITLE
[R009] caso d'uso 12999999 Caso d'uso di servizio (riconoscimenti)

### ISSUE THREAD

**Issue by SandroDeFlorio** [italia/ansc#372]
buongiorno sono sandro de florio della kibernetes ; nel caso d'uso in oggetto mi viene restituito il seguente errore
HTTP Status 400 
{"testataRisposta":{"idComune":10288,"idOperazioneComune":"12","idOperazione":"1641761","idEsito":1},"errors":[{"code":"400003","severity":"E","text":"Per proseguire è necessario che la data di nascita del soggetto sia antecedente alla data di nascita del Padre"},{"code":"400003","severity":"E","text":"Per proseguire è necessario che la data di nascita del soggetto sia antecedente alla data di nascita della Madre"}]}
le date dell'intestatario e del padre e della madre rispettano la condizione che invece viene segnalata anomala. Mi potreste spiegare perchè? Grazie per la collaborazione

**Comment by asqueglia** [comment]
Buongiorno, abbiamo analizzato la richiesta da voi inviata e abbiamo notato che state trasmettendo una data di nascita del soggetto intestatario precedente alla data di nascita dei genitori; nello specifico il soggetto intestatario ha come data nascita "**1966-01-10**" mentre i genitori hanno come data nascita madre 1967-05-04 e padre 1967-11-19, da ciò l'errore ricevuto.
E' necessario che il figlio ossia l'intestatario abbia una data di nascita successiva a quella dei genitori.
