### ISSUE TITLE
[Documentazione] Casi d'uso mancanti

### ISSUE THREAD

**Issue by siscomanpr** [italia/ansc#374]
Nel piano di test è richiesto il caso d'uso `359999 - Caso d'uso di servizio riconciliazioni` ma non lo troviamo nel file di mapping. 
Potete aggiungerlo?

Grazie
Siscom SPA

**Comment by asqueglia** [comment]
Verifichiamo   provvediamo quanto prima.

**Comment by asqueglia** [comment]
Buongiorno con il rilascio della versione 1.14.1 è stata aggiunta la documentazione del caso d'uso mancante in Mapping_casi_uso/matrimoni/Rico_Matr_999. 
Chiudiamo pertanto la issue; in caso di ulteriori segnalazioni si prega di aprirne una altra specifica.
