### ISSUE TITLE
[R009] IDUseCase 342000 - Sep_Div_002 - La verifica su tipoAccordo non è corretta

### ISSUE THREAD

**Issue by DorianoP** [italia/ansc#375]
Nella response  viene segnalato il seguente errore:
{
	"testataRisposta": {
		"idComune": XXXXX,
		"idOperazioneComune": "12",
		"idOperazione": "1643662",
		"idEsito": 1
	},
	"errors": [
		{
			"code": "400003",
			"severity": "E",
			"text": "Il campo evento.separazione.tipoAccordo nella sezione Dettaglio accordo non corrisponde al pattern ^[1]$"
		}
	]
}

Ma il valore da assegnare al campo tipoAccordo in questo UseCase è 2 o 3 come da tabella di decodifica "53_dec_tipo_accordo_separazione" che corrispondono a "Accordo di scioglimento del matrimonio" e "Cessazione degli effetti civili", mentre il valore 1 corrisponde a "Accordo di separazione" gestito nello UseCase 341000.

Saluti.

**Comment by asqueglia** [comment]
Buongiorno verifichiamo e le facciamo sapere

**Comment by asqueglia** [comment]
Buonasera con la versione 1.14, è stata corretta la segnalazione in oggetto. Provvediamo quindi a chiudere la issue; in caso di ulteriori segnalazioni si prega di aprirne una altra.
