### ISSUE TITLE
[R009] UseCase 11117000 problemi con l'allegato della Procura della madre

### ISSUE THREAD

**Issue by corradosacco** [italia/ansc#376]
Buongiorno,
 risulta incoerente la codifica dell'allegato della  Procura della madre nello UseCase 11117000; nel dominio ANSC_9 il documento Procura corrisponde al codice 6 ma verificando anche sulla webapp, il codice richiesto dallo usecase è il 4.
Impostando l'allegato errato (codice 4) sono riuscito a validare l'atto 2023-1113502-457-015146 ma con il codice dell'atto corretto (6) non riesco a validare l'atto (numero atto comunale 461 che va in errore).

allegati=[
	ModelAllegatoRif(
		id=2221711, 
		idTipoAllegato=1, 
		hashAllegato=on/HhwUUzcKtlAtCAfBq/oFbsXFiOP8OvVwEOSp4mbY=, 
		descrizione=Attestazione di nascita), 
	ModelAllegatoRif(
		id=2221712, 
		idTipoAllegato=6, 
		hashAllegato=on/HhwUUzcKtlAtCAfBq/oFbsXFiOP8OvVwEOSp4mbY=, 
		descrizione=Procura)
	]

Cordiali saluti,
 Corrado Sacco

**Comment by asqueglia** [comment]
Buongiorno verifichiamo e prendiamo in carico la segnalazione. Grazie

**Comment by asqueglia** [comment]
Buonasera con la versione 1.14, la segnalazione è stata corretta. Pertanto l'issue viene chiusa; nel caso di ulteriori segnalazioni si prega di aprirne una altra.
