### ISSUE TITLE
[R010] - [R006] Firma officiante modalità cartacea su atti di matrimonio

### ISSUE THREAD

**Issue by siscomanpr** [italia/ansc#380]
Buongiorno,
abbiamo rilevato che scaricando l'anteprima dell'atto con il servizio R010 (presaVisione=true), in fondo al PDF dove compaiono i firmatari, non è presente "lo spazio" per la firma dell'officiante. Sono presenti solo gli sposi e gli eventuali testimoni.
![image](https://github.com/italia/ansc/assets/28776141/6d68ee99-1e81-4863-bbb8-cc5d221ab707)

Crediamo che sia un errore, visto che nel caso dei matrimoni civili in cui l'officiante è il sindaco, o una terza persona diversa dall'USC, l'atto deve essere firmato sicuramente anche dall'officiante.

Inoltre se con il servizio R006 proviamo ad inviare il PDF firmato aggiungendo all'elenco dei firmatari anche l'officiante, viene restituito errore "Non sono stati recuperati firmatari per i dati inseriti".

Presumiamo che questo problema si sta verificando in seguito alla versione 1.13 con la quale è stato deprecato l'oggetto ufficiale di stato civile nel modelEvento. Con la precedente versione infatti veniva validato l'atto inviando anche l'ufficiale di stato civile con flagFirmatario=true, e questo faceva sì che poi comparisse anche tra i firmatari il nome dell'officiante (che corrispondeva con l'USC).

Nel modelMatrimonio i campi relativi all'officiante sono campi stringa semplici e non si punta ad un modelSoggetto
![image](https://github.com/italia/ansc/assets/28776141/c87dc3d4-2f1c-4033-80ff-430876b55735)
quindi l'indicazione flagFirmatario=true non è possibile impostarla. 

Lo stesso problema lo rileviamo anche nella web app, dove provando a caricare un matrimonio civile, l'officiante compare nel testo dell'atto, ma non nell'elenco dei firmatari nella fase di firma o nel PDF per la firma cartacea.

Richiediamo quindi una verifica su tutti i casi d'uso di matrimonio con rito civile al fine di capire come far comparire nel PDF anche il nome dell'officiante come firmatario.

Di seguito un esempio di validazione di un atto di matrimonio civile dove è possibile constatare il problema.
idOperazione: 1644744

**Comment by asqueglia** [comment]
Buongionro provvediamo a verificare quanto indicato. Le facciamo sapere appena possibile

**Comment by asqueglia** [comment]
Con la versione 1.14.0  #394  abbiamo anticipato la modalità di risoluzione della presente segnalazione; la correzione verrà rilasciata con la prossima versione disponibile indicativamente dal 16/10.

**Comment by asqueglia** [comment]
Buonasera, con il rilascio della versione 1.15.0 è stata corretta la segnalazione in oggetto. Chiudiamo pertanto la presente issue; in caso di ulteriori richieste di prega di aprire una issue dedicata.
