### ISSUE TITLE
Mancata notifica anagrafica per atto di nascita

### ISSUE THREAD

**Issue by antonioluberto** [italia/ansc#381]
Buongiorno.
Su ambiente di pre-prod del Comune di Grottaferrata abbiamo creato atto di nascita

![image](https://github.com/italia/ansc/assets/26415430/f97dac6b-9b04-4057-95cb-cc67f3f8f76c)

relativo a soggetto nato (a Roma) da genitori entrambi residenti a Grottaferrata.

Abbiamo quindi impostato - ieri - la "data validità" per l'evento corrispondente mediante operazione con Id: 1643953.

Non rileviamo la presenza di alcuna notifica anagrafica né su WebApp:

![image](https://github.com/italia/ansc/assets/26415430/3c12f341-e1f2-43da-bf09-2bf1b3998036)

né da servizio ANPR 4005.

Potreste verificare e farci sapere?

Grazie

**Comment by gbuemi** [comment]
Buon pomeriggio, la segnalazione è stata presa in carico. Grazie.
