### ISSUE TITLE
[R009] IDUseCase 51103 - Citt_011- Errata validazione campo Citt_011 tipologiaDocumento

### ISSUE THREAD

**Issue by DorianoP** [italia/ansc#382]
Nella verifica del campo tipologiaDocumento del ModelDocumentoRiconoscimento nello UseCase indicato viene segnalato l'errore:
	"testataRisposta": {
		"idComune": XXXXX,
		"idOperazioneComune": "12",
		"idOperazione": "1646472",
		"idEsito": 1
	},
	"errors": [
		{
			"code": "400003",
			"severity": "E",
			"text": "Il campo evento.intestatari[0].documentoRiconoscimento.tipologiaDocumento nella sezione Documento di riconoscimento non corrisponde al pattern ^[0-9]*$"
		}
	]

Ma la definizione del campo è:
        tipologiaDocumento: 
          type: string
          description: Tipologia di documento utilizzato per il riconoscimento.
          example: "Carta d'identità"

E' stata implementata la decodifica del campo tipologiaDocumento? Eventualmente quale è il file per la sua decodifica?

Grazie.

**Comment by asqueglia** [comment]
Buongiorno prendiamo in carico la segnalazione e facciamo sapere

**Comment by asqueglia** [comment]
Buonasera, con il rilascio della versione 1.15.0 è stata corretta la segnalazione in oggetto. Chiudiamo pertanto la presente issue; in caso di ulteriori richieste di prega di aprire una issue dedicata.
