### ISSUE TITLE
[R002] Estratto per copia Integrale - Errore interno

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#383]
Tentando di scaricare l'estratto per copia Integrale il servizio risponde con un errore interno:

REQUEST:
{
  "idAnsc": "2023-1113752-12364-108028",
  "idEvento": "1113752",
  "richiedente": {
    "codiceFiscale": "CTTMGH68B41E617G",
    "cognome": "CITTERIO",
    "nome": "MARGHERITA",
    "sesso": "F",
    "dataNascita": "1968-02-01",
    "idComuneNascita": "5001",
    "nomeComuneNascita": "LISSONE",
    "idProvinciaNascita": "15",
    "siglaProvinciaNascita": "MI",
    "idStatoNascita": "90",
    "nomeStatoNascita": "ITALIA",
    "idComuneResidenza": "5000",
    "nomeComuneResidenza": "LISSONE",
    "idProvinciaResidenza": "108",
    "siglaProvinciaResidenza": "MB",
    "idStatoResidenza": "90",
    "nomeStatoResidenza": "ITALIA",
    "indirizzoResidenza": "VIA MAMELI GOFFREDO,52 SC.C INT.0",
    "idNazionalita": "90",
    "nazionalita": "ITALIANA"
  },
  "intestatario": {
    "id": "2222766"
  },
  "idTipoCertificato": "3",
  "conPaternitaMaternita": false,
  "testataRichiesta": {
    "idComune": 5000,
    "idOperazioneComune": "5569",
    "dataOraRichiesta": "2023-10-05T09:36:09.691+02:00",
    "nomeApplicativo": "urbi",
    "versioneApplicativo": "0.1.0",
    "fornitoreApplicativo": "padigitale"
  }
}

RESPONSE:
{
  "testataRisposta": {
    "idComune": 5000,
    "idOperazioneComune": "5569",
    "idOperazione": "1647114"
  },
  "errors": [
    {
      "code": "500",
      "severity": "E",
      "text": "Errore interno"
    }
  ]
}

**Comment by amusarra** [comment]
Salve @biadanpad 
Abbiamo appena eseguito la sua stessa richiesta non riscontrando il problema. A seguire la nostra richiesta e risposta eseguita in ambiente di pre-produzione.

```
{
    "testataRichiesta": {
        "idComune": 580,
        "idOperazioneComune": "APP2022032210000",
        "dataOraRichiesta": "1",
        "nomeApplicativo": "Applicativo Demografico",
        "versioneApplicativo": "1.0.0",
        "fornitoreApplicativo": "Nome Fornitore"
    },
    "idAnsc": "2023-1113752-12364-108028",
    "idEvento": "1113752",
    "richiedente": {
        "codiceFiscale": "CTTMGH68B41E617G",
        "cognome": "CITTERIO",
        "nome": "MARGHERITA",
        "sesso": "F",
        "dataNascita": "1968-02-01",
        "idComuneNascita": "5001",
        "nomeComuneNascita": "LISSONE",
        "idProvinciaNascita": "15",
        "siglaProvinciaNascita": "MI",
        "idStatoNascita": "90",
        "nomeStatoNascita": "ITALIA",
        "idComuneResidenza": "5000",
        "nomeComuneResidenza": "LISSONE",
        "idProvinciaResidenza": "108",
        "siglaProvinciaResidenza": "MB",
        "idStatoResidenza": "90",
        "nomeStatoResidenza": "ITALIA",
        "indirizzoResidenza": "VIA MAMELI GOFFREDO,52 SC.C INT.0",
        "idNazionalita": "90",
        "nazionalita": "ITALIANA"
    },
    "intestatario": {
        "id": "2222766"
    },
    "idTipoCertificato": "3",
    "conPaternitaMaternita": false
}
```

![image](https://github.com/italia/ansc/assets/708110/348e65ff-7b58-4cb7-b83f-6cadf82d7684)

Potreste riprovare?

Grazie.
Supporto ANSC.

**Comment by biadanpad** [comment]
Abbiamo riprovato, ma otteniamo sempre lo stesso errore anche con un altro atto:

REQUEST:
{
  "idAnsc": "2023-1113788-22-108028",
  "idEvento": "1113788",
  "richiedente": {
    "codiceFiscale": "CTTMGH68B41E617G",
    "cognome": "CITTERIO",
    "nome": "MARGHERITA",
    "sesso": "F",
    "dataNascita": "1968-02-01",
    "idComuneNascita": "5001",
    "nomeComuneNascita": "LISSONE",
    "idProvinciaNascita": "15",
    "siglaProvinciaNascita": "MI",
    "idStatoNascita": "90",
    "nomeStatoNascita": "ITALIA",
    "idComuneResidenza": "5000",
    "nomeComuneResidenza": "LISSONE",
    "idProvinciaResidenza": "108",
    "siglaProvinciaResidenza": "MB",
    "idStatoResidenza": "90",
    "nomeStatoResidenza": "ITALIA",
    "indirizzoResidenza": "VIA MAMELI GOFFREDO,52 SC.C INT.0",
    "idNazionalita": "90",
    "nazionalita": "ITALIANA"
  },
  "intestatario": {
    "id": "2222970"
  },
  "idTipoCertificato": "3",
  "conPaternitaMaternita": false,
  "testataRichiesta": {
    "idComune": 5000,
    "idOperazioneComune": "2834",
    "dataOraRichiesta": "2023-10-05T12:07:04.107+02:00",
    "nomeApplicativo": "urbi",
    "versioneApplicativo": "0.1.0",
    "fornitoreApplicativo": "padigitale"
  }
}

RESPONSE:
{
  "testataRisposta": {
    "idComune": 5000,
    "idOperazioneComune": "2834",
    "idOperazione": "1647446"
  },
  "errors": [
    {
      "code": "500",
      "severity": "E",
      "text": "Errore interno"
    }
  ]
}

**Comment by amusarra** [comment]
Grazie @biadanpad 
Proveremo a capire le differenze di request.

Cordiali Saluti.
Supporto ANSC.

**Comment by amusarra** [comment]
@biadanpad capito il problema. C'è uno spazio di troppo sul sub.

```
{
  "sub": " DLCNTN57L67A064W",
  "iat": 1696500424,
  "exp": 1696716424,
  "nbf": 1696716424,
  "jti": "njW3YO8cqUiLYZkQQHX_lQ",
  "sede": "108028",
  "postazione": "108028-PC-0002",
  "otp": "123456"
}
```

**Comment by biadanpad** [comment]
Perfetto, adesso funzione.
Grazie!
