### ISSUE TITLE
[R009] usercase 1331 Trascrizione del decreto prefettizio di cambiamento del nome e cognome

### ISSUE THREAD

**Issue by SandroDeFlorio** [italia/ansc#386]
Buongiorno,
nel caso d'uso in oggetto la trasmissione restituisce una serie di errori sui campi madre padre e riconoscimento genitori.
HTTP Status 400 
{"testataRisposta":{"idComune":10288,"idOperazioneComune":"12","idOperazione":"1648091","idEsito":1},"errors":[{"code":"400003","severity":"E","text":"Il campo evento.madre.nome nella sezione Madre è obbligatorio"},{"code":"400003","severity":"E","text":"Il campo evento.madre.sesso nella sezione Madre è obbligatorio"},{"code":"400003","severity":"E","text":"Il campo evento.madre.idStatoNascita nella sezione Madre è obbligatorio"},{"code":"400003","severity":"E","text":"Il campo evento.madre.nomeStatoNascita nella sezione Madre è obbligatorio"},{"code":"400003","severity":"E","text":"Il campo evento.madre.idNazionalita nella sezione Madre è obbligatorio"},{"code":"400003","severity":"E","text":"Il campo evento.madre.nazionalita nella sezione Madre è obbligatorio"},{"code":"400003","severity":"E","text":"Il campo evento.madre.idStatoResidenza nella sezione Madre è obbligatorio"},{"code":"400003","severity":"E","text":"Il campo evento.madre.nomeStatoResidenza nella sezione Madre è obbligatorio"},{"code":"400003","severity":"E","text":"Il campo evento.padre.nome nella sezione Padre è obbligatorio"},{"code":"400003","severity":"E","text":"Il campo evento.padre.sesso nella sezione Padre è obbligatorio"},{"code":"400003","severity":"E","text":"Il campo evento.padre.idStatoNascita nella sezione Padre è obbligatorio"},{"code":"400003","severity":"E","text":"Il campo evento.padre.nomeStatoNascita nella sezione Padre è obbligatorio"},{"code":"400003","severity":"E","text":"Il campo evento.padre.idNazionalita nella sezione Padre è obbligatorio"},{"code":"400003","severity":"E","text":"Il campo evento.padre.nazionalita nella sezione Padre è obbligatorio"},{"code":"400003","severity":"E","text":"Il campo evento.padre.idStatoResidenza nella sezione Padre è obbligatorio"},{"code":"400003","severity":"E","text":"Il campo evento.padre.nomeStatoResidenza nella sezione Padre è obbligatorio"},{"code":"400003","severity":"E","text":"Il campo evento.riconoscimentoPadre.atto.idProvinciaRegistrazione nella sezione Riconoscimento padre è obbligatorio"},{"code":"400003","severity":"E","text":"Il campo evento.riconoscimentoPadre.atto.siglaProvinciaRegistrazione nella sezione Riconoscimento padre è obbligatorio"},{"code":"400003","severity":"E","text":"Il campo evento.riconoscimentoPadre.atto.idComuneRegistrazione nella sezione Riconoscimento padre è obbligatorio"},{"code":"400003","severity":"E","text":"Il campo evento.riconoscimentoPadre.atto.nomeComuneRegistrazione nella sezione Riconoscimento padre è obbligatorio"},{"code":"400003","severity":"E","text":"Il campo evento.riconoscimentoPadre.atto.idtipocontenuto nella sezione Riconoscimento padre è obbligatorio"},{"code":"400003","severity":"E","text":"Il campo evento.riconoscimentoPadre.atto.numeroatto nella sezione Riconoscimento padre è obbligatorio"},{"code":"400003","severity":"E","text":"Il campo evento.riconoscimentoPadre.atto.annoAtto nella sezione Riconoscimento padre è obbligatorio"},{"code":"400003","severity":"E","text":"Il campo evento.riconoscimentoPadre.atto.dataformazione nella sezione Riconoscimento padre è obbligatorio"},{"code":"400003","severity":"E","text":"Il campo evento.riconoscimentoPadre.atto.tipologia nella sezione Riconoscimento padre è obbligatorio"},{"code":"400003","severity":"E","text":"Il campo evento.riconoscimentoMadre.atto.idProvinciaRegistrazione nella sezione Riconoscimento madre è obbligatorio"},{"code":"400003","severity":"E","text":"Il campo evento.riconoscimentoMadre.atto.siglaProvinciaRegistrazione nella sezione Riconoscimento madre è obbligatorio"},{"code":"400003","severity":"E","text":"Il campo evento.riconoscimentoMadre.atto.idComuneRegistrazione nella sezione Riconoscimento madre è obbligatorio"},{"code":"400003","severity":"E","text":"Il campo evento.riconoscimentoMadre.atto.nomeComuneRegistrazione nella sezione Riconoscimento madre è obbligatorio"},{"code":"400003","severity":"E","text":"Il campo evento.riconoscimentoMadre.atto.idtipocontenuto nella sezione Riconoscimento madre è obbligatorio"},{"code":"400003","severity":"E","text":"Il campo evento.riconoscimentoMadre.atto.numeroatto nella sezione Riconoscimento madre è obbligatorio"},{"code":"400003","severity":"E","text":"Il campo evento.riconoscimentoMadre.atto.annoAtto nella sezione Riconoscimento madre è obbligatorio"},{"code":"400003","severity":"E","text":"Il campo evento.riconoscimentoMadre.atto.dataformazione nella sezione Riconoscimento madre è obbligatorio"},{"code":"400003","severity":"E","text":"Il campo evento.riconoscimentoMadre.atto.tipologia nella sezione Riconoscimento madre è obbligatorio"},{"code":"400003","severity":"E","text":"Il campo evento.riconoscimento.atto.idProvinciaRegistrazione nella sezione Riconoscimento entrambi è obbligatorio"},{"code":"400003","severity":"E","text":"Il campo evento.riconoscimento.atto.siglaProvinciaRegistrazione nella sezione Riconoscimento entrambi è obbligatorio"},{"code":"400003","severity":"E","text":"Il campo evento.riconoscimento.atto.idComuneRegistrazione nella sezione Riconoscimento entrambi è obbligatorio"},{"code":"400003","severity":"E","text":"Il campo evento.riconoscimento.atto.nomeComuneRegistrazione nella sezione Riconoscimento entrambi è obbligatorio"},{"code":"400003","severity":"E","text":"Il campo evento.riconoscimento.atto.idtipocontenuto nella sezione Riconoscimento entrambi è obbligatorio"},{"code":"400003","severity":"E","text":"Il campo evento.riconoscimento.atto.numeroatto nella sezione Riconoscimento entrambi è obbligatorio"},{"code":"400003","severity":"E","text":"Il campo evento.riconoscimento.atto.annoAtto nella sezione Riconoscimento entrambi è obbligatorio"},{"code":"400003","severity":"E","text":"Il campo evento.riconoscimento.atto.dataformazione nella sezione Riconoscimento entrambi è obbligatorio"},{"code":"400003","severity":"E","text":"Il campo evento.riconoscimento.atto.tipologia nella sezione Riconoscimento entrambi è obbligatorio"},{"code":"400003","severity":"E","text":"Il campo evento.trascrizioneNascita.tipoRiconoscimento nella sezione Dettaglio evento è obbligatorio"}]}

il tracciato del caso d'uso non contempla la presenza dei campi madre e padre per cui le segnalazioni di obbligatorietà non dovrebbero sussistere.
Potreste verificare. Grazie per la collaborazione.
Kibernetes srl

**Comment by asqueglia** [comment]
Buongiorno provvediamo a verificare e le facciamo sapere. Grazie per la segnalazione

**Comment by asqueglia** [comment]
Buongiorno, abbiamo verificato il caso d'uso segnalato e non riusciamo a replicare l'errore segnalato. Di seguito un payload di esempio.
La preghiamo di riprovare. Restiamo in attesa di un suo riscontro in merito.

 "evento": {
        "idTipoEvento": "1",
        "idtipocontenuto": "3",
        "idUsecase": "1331",
        "descrizioneCasoUso": "Trascrizione del decreto prefettizio di cambiamento del nome e cognome",
        "stato": "CONFERMATO",
        "dataformazione": "2023-10-23",
        "ora": "08",
        "minuto": "57",
        "annoAtto": "2023",
        "numeroatto": "123213",
        "idComuneRegistrazione": "1000000",
        "nomeComuneRegistrazione": "ANPR",
        "idProvinciaRegistrazione": "58",
        "siglaProvinciaRegistrazione": "RM",
        "operatore": "CRUMRA67S47Z127B",
        "ruoloOperatore": "3",
        "operatoreNome": "MARIE",
        "operatoreCognome": "CURIE",
        "redattoNellaCasaComunale": true,
        "allegati": [
            {
                "id": 563977,
                "idTipoAllegato": 30,
                "hashAllegato": "oeAYUrRzqVnj1SNO6pyjSJrOyd+4KTjVHxpF2YCiP+U=",
                "descrizione": "Decreto Prefettizio"
            }
        ],
        "intestatari": [
            {
                "cognome": "XXXX",
                "nome": "XXXXXXXXXX",
                "sesso": "M",
                "dataNascita": "2023-02-15",
                "idComuneNascita": "",
                "nomeComuneNascita": "",
                "idProvinciaNascita": "",
                "siglaProvinciaNascita": "",
                "idStatoNascita": "13",
                "nomeStatoNascita": "BAHAMAS",
                "idComuneResidenza": "",
                "nomeComuneResidenza": "",
                "idProvinciaResidenza": "",
                "siglaProvinciaResidenza": "",
                "idStatoResidenza": "12",
                "nomeStatoResidenza": "AZERBAIGIAN",
                "indirizzoResidenza": "",
                "idstatocivile": "1",
                "descrizionestatocivile": "Celibe/Nubile",
                "idNazionalita": "17",
                "nazionalita": "BELGA",
                "documentoRiconoscimento": {}
            }
        ],
        "datiEventoRiconoscimento": {
            "attoNascita": {
                "idAnsc": "",
                "idComuneRegistrazione": "99",
                "nomeComuneRegistrazione": "AGRIGENTO",
                "idProvinciaRegistrazione": "84",
                "siglaProvinciaRegistrazione": "AG",
                "idtipocontenuto": "1",
                "dataformazione": "2023-10-23",
                "numeroatto": "13232",
                "annoAtto": "2020",
                "tipologia": "1",
                "serie": "A",
                "parte": "I"
            }
        },
        "trascrizioneNascita": {
            "tipoDichiarazione": "3",
            "dataComunicazione": "2023-10-23",
            "testoLibero": "<<<<esempio riassunto>>>>",
            "atto": {
                "enteEstero": {
                    "nomeEnte": "BBB",
                    "idComuneEnte": "8165",
                    "nomeComuneEnte": "ROMA",
                    "idProvinciaEnte": "58",
                    "siglaProvinciaEnte": "RM",
                    "dataTrascrizione": "2023-10-23",
                    "estremiDocumento": "AAA",
                    "nazioneEnte": "90",
                    "nomeNazioneEnte": "ITALIA"
                }
            },
            "sceltaCognome": "6",
            "nuovoCognome": "Rossi",
            "istituto": {},
            "nuovoNome": "",
            "cognomeAggiunto": "",
            "nomeAggiunto": ""
        },
        "composizioneCompleta": "Oggi 23/10/2023 io sottoscritto MARIE CURIE Ufficiale dello stato civile del Comune di ANPR (RM), nella funzione di sostituto del sindaco, ho ricevuto da GAETANINO SPOSO, nato in BAHAMAS il 15/02/2023, con cittadinanza BELGA, residente in AZERBAIGIAN la richiesta Scritta in data 23/10/2023 di trascrivere l'atto con estremi Numero AAA redatto in data 23/10/2023 emesso da BBB in ROMA (RM) di cui mi consegna copia.\nAderendo a tale richiesta, provvedo alla trascrizione integrale del documento come segue: <<<<esempio riassunto>>>>.\nDopo di che, ho munito del mio visto ed inserito nel volume degli allegati a questo registro copia della richiesta di trascrizione.",
        "datains": "2023-10-23T08:57:40.562476",
        "dataultimoagg": "2023-10-23T09:01:28.131758",
        "flagsecretato": 0,
        "idVersion": 100003
    }
}

**Comment by asqueglia** [comment]
Buongiorno non avendo ricevuto feddback in merito, provvediamo a chiudere la issue. In caso di ulteriori segnalazioni la preghiamo di aprire una altra issue dedicata
