### ISSUE TITLE
[R009] IDUseCase 433000 e 434000 - probabili tracciati invertiti

### ISSUE THREAD

**Issue by DorianoP** [italia/ansc#387]
Buongiorno,
in merito ai due UseCase in oggetto probabilmente i tracciati Trascr_UnCiv_003 (UseCase 433000) e Trascr_UnCiv_004 (UseCase 433000) sono stati invertiti, in quanto nel Trascr_UnCiv_004 è presente la sezione richiedente che dovrebbe fare riferimento al UseCase 433000 e non al 434000 che è "Richiesta di trascrizione da parte del Consolato/Ambasciata".

Inoltre, considerando che il tracciato Trascr_UnCiv_004 sia per lo UseCase 433000, dovrebbe essere tolta la sezione "autorità mittente", perchè richiesta da privato, mentre considerando che il tracciato Trascr_UnCiv_003 sia per lo UseCase 434000, la sezione "autorità mittente" andrebbe presa da evento.trascrizioneUnioneCivile.atto.enteEstero  e non da evento.trascrizioneUnioneCivile.autoritaMittente in quanto autorità estera.

Nel caso le mie supposizioni siano errate vi chiedo se cortesemente potete chiarire come vadano valorizzati i campi che ritengo errati.

Saluti.

**Comment by asqueglia** [comment]
Buongiorno verifichiamo e facciamo sapere. Grazie per la segnalazione

**Comment by asqueglia** [comment]
Buonasera, con il rilascio della versione 1.15.0 è stata corretta la segnalazione in oggetto. Chiudiamo pertanto la presente issue; in caso di ulteriori richieste di prega di aprire una issue dedicata.
