### ISSUE TITLE
[R009] IDUseCase 439999 - Trascr_UnCiv_999 - Refuso nel tracciato

### ISSUE THREAD

**Issue by DorianoP** [italia/ansc#388]
Buongiorno,
vi è un probabile refuso nel tracciato e nelle verifiche per lo UseCase in oggetto, in quanto lo UseCase riguarda le trascrizioni di unioni civili mentre nel tracciato e nella validazione è richiesto come obbligatorio il campo evento.**trascrizioneMatrimonio**.attoEstero.enteEstero.comuneEstero, che fa riferimento alle trascrizioni di matrimonio.

Saluti.

**Comment by asqueglia** [comment]
Buongiornoo, verifichiamo e facciamo sapere. Grazie per la segnalazione

**Comment by asqueglia** [comment]
Buonasera, con il rilascio della versione 1.15.0 è stata corretta la segnalazione in oggetto. Chiudiamo pertanto la presente issue; in caso di ulteriori richieste di prega di aprire una issue dedicata.
