### ISSUE TITLE
[R009] IDUseCase 412111 - UnCiv_004 - il sistema ritorna internal.error

### ISSUE THREAD

**Issue by DorianoP** [italia/ansc#389]
Buongiorno,
nel eseguire una request per lo UseCase in oggetto il sistema ritorno sempre un internal.error.
HTTP Status 500 
{"message":"internal.error","errors":null}

Payload di esempio:
{
	"testataRichiesta": {
		"idComune": 10288,
		"idOperazioneComune": 11,
		"dataOraRichiesta": "2023-10-06 12:38:49",
		"nomeApplicativo": "PEDemografici",
		"versioneApplicativo": "1",
		"fornitoreApplicativo": "XXXXXXX"
	},
	"presaVisione": false,
	"evento": {
		"idTipoEvento": "4",
		"idtipocontenuto": "1",
		"idUsecase": "412111",
		"descrizioneCasoUso": "Unione Civile con Delega di altro Comune nella casa comunale",
		"stato": "CONFERMATO",
		"idVersion": "100002",
		"dataformazione": "2023-10-06",
		"annoAtto": "2023",
		"ora": "12",
		"minuto": "22",
		"operatore": "XXXXXXXX",
		"operatoreNome": "XYXYXYX",
		"operatoreCognome": "XYXYXXX",
		"redattoNellaCasaComunale": true,
		"idComuneRegistrazione": "10288",
		"nomeComuneRegistrazione": "TROPEA",
		"idProvinciaRegistrazione": "102",
		"siglaProvinciaRegistrazione": "VV",
		"dataDecorrenza": "2023-10-06",
		"numeroatto": "1",
		"ausilioInterprete": "no",
		"conTestimoni": "si",
		"certificabile": "1",
		"sentenzaFiglioIncestuoso": false,
		"propostaAnnotazione": false,
		"datiProdotti": "1",
		"allegati": [],
		"intestatari": [
			{
				"codiceFiscale": "XXXXXXXXXX",
				"cognome": "XXXXX",
				"nome": "XXXXXX",
				"sesso": "M",
				"dataNascita": "1998-01-17",
				"idComuneNascita": "2923",
				"nomeComuneNascita": "CINQUEFRONDI",
				"idProvinciaNascita": "80",
				"siglaProvinciaNascita": "RC",
				"idStatoNascita": "90",
				"nomeStatoNascita": "ITALIA",
				"idComuneResidenza": "10288",
				"nomeComuneResidenza": "TROPEA",
				"idProvinciaResidenza": "102",
				"siglaProvinciaResidenza": "VV",
				"idStatoResidenza": "90",
				"nomeStatoResidenza": "ITALIA",
				"indirizzoResidenza": "XXXXXXX",
				"idstatocivile": "1",
				"descrizionestatocivile": "CELIBE",
				"idNazionalita": "90",
				"nazionalita": "ITALIANA",
				"flagDichiarante": true,
				"flagComparente": true,
				"flagFirmatario": true
			},
			{
				"codiceFiscale": "YYYYYYYYYYYY",
				"cognome": "YYYYYY",
				"nome": "YYYYY",
				"sesso": "M",
				"dataNascita": "1988-01-28",
				"idComuneNascita": "2544",
				"nomeComuneNascita": "CATTOLICA",
				"idProvinciaNascita": "600",
				"siglaProvinciaNascita": "FO",
				"idStatoNascita": "90",
				"nomeStatoNascita": "ITALIA",
				"idComuneResidenza": "10675",
				"nomeComuneResidenza": "VERUCCHIO",
				"idProvinciaResidenza": "600",
				"siglaProvinciaResidenza": "FO",
				"idStatoResidenza": "90",
				"nomeStatoResidenza": "ITALIA",
				"indirizzoResidenza": "XXXXXXX",
				"idstatocivile": "1",
				"descrizionestatocivile": "CELIBE",
				"idNazionalita": "90",
				"nazionalita": "ITALIANA",
				"flagDichiarante": true,
				"flagComparente": true,
				"flagFirmatario": true
			}
		],
		"variazioni": [],
		"datiDichiarante": {
			"comprensione": "0"
		},
		"datiEventoUnioneCivile": {
			"dataEvento": "2023-10-06",
			"oraEvento": "12",
			"minutoEvento": "10",
			"officiante": "3",
			"cognomeOfficiante": "XYXYXYXYX",
			"nomeOfficiante": "XYXYXYXY",
			"dataCertificatoCostituzione": "0001-01-01",
			"comprensioneConiuge1": "0",
			"comprensioneConiuge2": "0",
			"numeroTestimoni": "2",
			"certificatoCostituzione1": {
				"idProvinciaCertificatoCostituzione": "52",
				"siglaProvinciaCertificatoCostituzione": "SI",
				"comuneCertificatoCostituzione": "510",
				"nomeComuneCertificatoCostituzione": "SINALUNGA",
				"dataCertificatoCostituzione": "2023-09-08"
			},
			"testimone1": {
				"codiceFiscale": "XXXXXXXXXX",
				"cognome": "XXXXXX",
				"nome": "XXXXXX",
				"sesso": "F",
				"dataNascita": "1978-02-17",
				"idComuneNascita": "10289",
				"nomeComuneNascita": "TROPEA",
				"idProvinciaNascita": "79",
				"siglaProvinciaNascita": "CZ",
				"idStatoNascita": "90",
				"nomeStatoNascita": "ITALIA",
				"idComuneResidenza": "10288",
				"nomeComuneResidenza": "TROPEA",
				"idProvinciaResidenza": "102",
				"siglaProvinciaResidenza": "VV",
				"idStatoResidenza": "90",
				"nomeStatoResidenza": "ITALIA",
				"indirizzoResidenza": "XXXXXX",
				"idstatocivile": "2",
				"descrizionestatocivile": "CONIUGATA   ",
				"idNazionalita": "90",
				"nazionalita": "ITALIANA",
				"flagDichiarante": true,
				"flagComparente": true,
				"flagFirmatario": true
			},
			"testimone2": {
				"codiceFiscale": "YYYYYYYY",
				"cognome": "YYYYY",
				"nome": "YYYYYYYYY",
				"sesso": "M",
				"dataNascita": "2000-05-17",
				"idComuneNascita": "10288",
				"nomeComuneNascita": "TROPEA",
				"idProvinciaNascita": "102",
				"siglaProvinciaNascita": "VV",
				"idStatoNascita": "90",
				"nomeStatoNascita": "ITALIA",
				"idComuneResidenza": "7919",
				"nomeComuneResidenza": "RICADI",
				"idProvinciaResidenza": "102",
				"siglaProvinciaResidenza": "VV",
				"idStatoResidenza": "90",
				"nomeStatoResidenza": "ITALIA",
				"indirizzoResidenza": "YYYYYYYYYYY",
				"idstatocivile": "1",
				"descrizionestatocivile": "CELIBE",
				"idNazionalita": "90",
				"nazionalita": "ITALIANA",
				"flagDichiarante": true,
				"flagComparente": true,
				"flagFirmatario": true
			},
			"rigettoOpposizione": false,
			"estintaOpposizione": false,
			"regimePatrimoniale": {
				"tipo": "1",
				"attoNotarile": false,
				"dataAttoNotarile": "0001-01-01"
			},
			"coniuge1InPericoloVita": false,
			"coniuge2InPericoloVita": false,
			"comuneDelegante": "510",
			"nomeComuneDelegante": "SINALUNGA",
			"idProvinciaComuneDelegante": "52",
			"siglaProvinciaComuneDelegante": "SI",
			"dataDelega": "08/09/2023",
			"testoDelega": "SDFSDF",
			"impedimentoGenerico": "0"
		},
		"composizioneCompleta": "L'anno duemilaventitre addì sei del mese di ottobre alle ore dodici e minuti ventidue avanti di me, XXXXXXXXXXXXX ISTRUTTORE AMMINISTRATIVO, Ufficiale dello stato civile del Comune di TROPEA PER DELEGA AVUTA vestito in forma ufficiale\n"
	}
}

**Comment by amusarra** [comment]
Salve @DorianoP 
Il problema è dovuto al fatto che `dataDelega` è valorizzato con una data (`08/09/2023`) nel formato non previsto dalle specifiche OpenAPI (https://github.com/italia/ansc/blob/639338d0fa0f3dab4ec008e2323d8a35b391d37d/docs/openapi/model_evento.yaml#L1764)

Mettendo la data nel formato previsto, la validazione dell'evento dovrebbe andare a buon fine.

Se non ci sono ulteriori dubbi e/o chiarimenti, invitiamo alla chiusura della issue.

Cordiali Saluti.
Supporto ANSC.

**Comment by DorianoP** [comment]
Buongiorno @amusarra ,
abbiamo modificato il nostro codice, come indicato, e la validazione è andata a buon fine.
La ringrazio per il supporto.

Cordiali saluti.
