### ISSUE TITLE
Segnalazione anomalia yaml

### ISSUE THREAD

**Issue by siscomanpr** [italia/ansc#39]
Segnaliamo che nel file model_evento.yaml, ModelTrascrizioneCittadinanza il campo "numeroProtocollo" è indicato erroneamente come formato date

Siscom SPA

**Comment by siscomanpr** [comment]
Ci sono novità sul problema segnalato?

**Comment by asqueglia** [comment]
Buongiorno, con il rilascio odierno versione 1.6.0 è stata risolta la problematica segnalata.
