### ISSUE TITLE
Contributo ai Comuni per l'ingresso in ANSC

### ISSUE THREAD

**Issue by SAlberto** [italia/ansc#390]
Buongiorno,
ci sono novità in merito a questa issue? 
#282 
Si sa quale sarà la data entro la quale i comuni saranno obbligati a subentrare in ANSC?
Ci sono possibilità che i contributi vengano prorogati oltre il 31/12/2023?

In attesa di un cortese riscontro
Ringrazio anticipatamente
Distinti saluti

**Comment by SAlberto** [comment]
Buongiorno,
avremmo bisogno di sapere la **data ultima** entro la quale tutti i comuni italiani dovranno **obbligatoriamente** essere subentrati in ANSC.

In attesa di un cortese riscontro
Ringrazio anticipatamente
Distinti saluti

**Comment by asqueglia** [comment]
Si faccia riferimento alla issue #492 . Chiudiamo pertanto la presente
