### ISSUE TITLE
[R009] caso d'uso 11117000 Dichiarazione entro i 10 giorni - resa dal procuratore della Madre

### ISSUE THREAD

**Issue by SandroDeFlorio** [italia/ansc#392]
Buongiorno, 
vi segnalo che nella trasmissione del caso d'uso in oggetto nonostante venga fornito l'allegato obbligatorio "Procura" , è generato il seguente messaggio di errore:
idComune":10288,"idOperazioneComune":"12","idOperazione":"1650182","idEsito":1},"errors":[{"code":"400003","severity":"E","text":"Allegato obbligatorio mancante: [Procura]"}]}
Potreste controllare? Grazie per la collaborazione.

Kibernetes srl

**Comment by asqueglia** [comment]
Buonasera con la versione 1.14, la segnalazione è stata corretta. Pertanto l'issue viene chiusa; nel caso di ulteriori segnalazioni si prega di aprirne una altra.
