### ISSUE TITLE
Guida all’utilizzo del sistema ANSC nel periodo di adesione progressiva

### ISSUE THREAD

**Issue by migmar68** [italia/ansc#395]
Buonasera
La recente [circolare 97/2023](https://dait.interno.gov.it/servizi-demografici/circolari/circolare-dait-n97-del-6-ottobre-2023) dice:

_In secondo luogo, coerentemente con quanto stabilito dall’art. 7 del richiamato decreto, che delinea le modalità di comunicazione da utilizzare nella fase di adesione progressiva da parte dei Comuni all’ANSC, sono stati definiti i flussi di azioni e di comunicazioni riportati nella “**Guida all’utilizzo del sistema ANSC nel periodo di adesione progressiva**”, predisposta da Sogei S.p.A., nella quale sono individuate alcune casistiche riguardanti possibili scenari._

Mi è sfuggita questa guida. Dove la possiamo trovare?

**Comment by asqueglia** [comment]
Buongiorno, la guida verrà resa disponibile a stretto giro sul sito pubblico di ANPR. La informiamo tempestivamente non appena verrà pubblicata

**Comment by asqueglia** [comment]
Buongiorno comunichiamo che la guida è disponibile sul sito portale pubblico ANPR, sezione Documentazione tecnica, nel paragrafo dedicato a Archivio Nazionale dello Stato Civile (ANSC).
https://www.anagrafenazionale.interno.it/area-tecnica/documentazione-tecnica/

**Comment by asqueglia** [comment]
Buongiorno provvediamo a chiudere la issue. In caso di ulteriori segnalazioni la preghiamo di aprire una altra issue dedicata
