### ISSUE TITLE
Ancora sulla generazione delle notifiche anagrafiche in ambiente di pre-produzione;

### ISSUE THREAD

**Issue by antonioluberto** [italia/ansc#396]
Con riferimento alle note di chiusura riportate sulla issue https://github.com/italia/ansc/issues/381, ci aspettiamo in effetti che tutti gli Enti per i quali esista area ANPR di test siano abilitati alla ricezione delle notifiche di variazioni anagrafiche originate da atti di stato civile; diversamente come potremo verificare che l'atto prodotto dal Comune A (attivo in ANSC) per soggetto residente nel Comune B (non attivo in ANSC), dia effettivamente luogo a notifica di variazioni anagrafiche disponibile per il Comune B?

Potete darci conferma?

Grazie,
Antonio

**Comment by asqueglia** [comment]
Buongiorno @antonioluberto, per simulare una situazione reale in ambiente di test, appositamente non abbiamo configurato tutti gli enti come aderenti ad ANSC; altrimenti non si potrebbero verificare i flussi da utilizzare nelle situazioni ibride. Per situazioni ibride, o transitorie,  si intende le situazioni di comunicazioni tra comuni digitali e comuni analogici. Al momento abbiamo considerato abilitati ad ANSC solo i comuni che effettivamente hanno iniziato la sperimentazione. A breve dovrebbe essere emanata dal Ministero la circolare relativa alla gestione del transitorio. 
Nello specifico quando un comune è analogico la gestione resta quella con le attuali modalità operative, invio pec ecc..
Con la versione 1.14.0 è stato rilasciato tra le altre cose, anche il servizio che consente di verificare quali sono i comuni aderenti.

**Comment by asqueglia** [comment]
Buongiorno comunichiamo che la guida per la gestione delle situazioni transitorie, è disponibile sul sito del portale pubblico ANPR, sezione Documentazione tecnica, nel paragrafo dedicato a Archivio Nazionale dello Stato Civile (ANSC).

https://www.anagrafenazionale.interno.it/area-tecnica/documentazione-tecnica/

**Comment by asqueglia** [comment]
Buongiorno non avendo ricevuto feddback in merito, provvediamo a chiudere la issue. In caso di ulteriori segnalazioni la preghiamo di aprire una altra issue dedicata
