### ISSUE TITLE
Ancora su mancata notifica anagrafica

### ISSUE THREAD

**Issue by antonioluberto** [italia/ansc#397]
A seguito della chiusura della https://github.com/italia/ansc/issues/381 abbiamo eseguito la creazione di nuovi casi di test

![image](https://github.com/italia/ansc/assets/26415430/216a1013-fe14-4462-a7f1-7e83de41cadf)

![image](https://github.com/italia/ansc/assets/26415430/a3ece7fb-ce4b-4c26-8ae3-e191141775a5)

![image](https://github.com/italia/ansc/assets/26415430/29ea1ea3-53b2-482d-b86a-297a3a33ee73)

![image](https://github.com/italia/ansc/assets/26415430/ea2d0d66-92f7-4964-a4c5-ec990457ce3a)

![image](https://github.com/italia/ansc/assets/26415430/31ee284c-63e3-4ab8-97a2-de0406842243)

ma continuiamo a non ricevere alcuna notifica né su WebApp né da servizio ANPR 4005.

Potreste verificare e farci sapere?

Grazie

**Comment by asqueglia** [comment]
Buongionro @antonioluberto abbiamo verificato che questi eventi sono stati registrati prima del rilascio di ieri.. quindi sicuramente le notifiche non sono state generate per questo. Potreste rifare un test ex novo registrando un  nuovo evento con soggetto residente a Grottaferrata e verificando la notifica ?  Restiamo in attesa di un suo riscontro.
Grazie mille

**Comment by RBiasi** [comment]
Buongiorno,

caricato caso di test ex nove Id atto ANSC 2023-1114198-1011-058046 tipo evento Nascita.

Ancora non vedo alcuna notifica.

Rimango in attesa.

Grazie

**Comment by asqueglia** [comment]
Stiamo vedendo che la notifica per presa visione relativa all'evento 1114198, è stata generata per Grottaferrata.. se accedete alla Web Application di ANSC, con la vostra utenza di Grottaferrata dovreste vedere nella sezione notifiche, la notifica corrispondente all'evento 1114198 da approvare. Una volta approvata la notifica, partirà la predisposizione anagrafica. 

![image](https://github.com/italia/ansc/assets/29303629/450be281-d970-475c-95f6-dad0dbfde296)


Da servizio cooperativo per scaricare la notifica da confermare potete utilizzare il servizio R008 {{R008}}/notifiche/ricerca/1 con il payload

 "criteriRicercaNotifiche": {
        "dataInizio": "2023-10-10",
        "dataFine": "2023-10-10",
        "idStatoFlussoNotifiche": "1",
        "idGenereNotifiche": "2" 
    }

per confermare la notifica è necessario utilizzare il servizio R008 {{R008}}/notifiche/conferma/1 con payload trasmettendo in input l'id della notifica.
Fateci sapere se funziona il giro.

**Comment by antonioluberto** [comment]
Ci scusiamo ma qualcosa non ci è chiaro.
Quello con Id 
**2023-1114198-1011-058046**
è atto di nascita riferito al caso d'uso
_Dic_Nasc_001 - "Dichiarazione entro i 10 giorni - resa dal padre"_
il cui titolare (per il quale è indicato Comune di nascita e Comune di residenza pari a "Grottaferrata") è figlio di padre/madre residenti entrambi a Grottaferrata.
Qual è la ragione per la quale in questo caso lo stesso Comune di Grottaferrata dovrebbe ricevere una notifica di tipo "trascrizione" per l'atto (che ha redatto esso stesso)?
E, ancora di più quindi, per quale ragione la disponibilità della notifica destinata all'anagrafe deve essere bloccata dalla validazione di una notifica di stato civile che non dovrebbe aversi?

**Comment by asqueglia** [comment]
Buongiorno @antonioluberto, questo è il comportamento che è stato condiviso con il Ministero e con il dipartimento; ossia la conferma esplicita di eventi formati dal comune per soggetti residenti.

**Comment by antonioluberto** [comment]
Ci permettiamo di suggerire ulteriore valutazione circa l'opportunità escludere la gestione della notifica di tipo "trascrizione" sopra rappresentata  nel caso in cui i due Comuni (quello che redige l'atto e quello di residenza del titolare) coincidano.

**Comment by asqueglia** [comment]
Buongiorno, provvediamo a chiudere la issue. In caso di ulteriori segnalazioni la preghiamo di aprire una altra issue dedicata
