### ISSUE TITLE
[R001] upload allegato - internal error

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#398]
tentando di caricare un allegato di dimensioni inferiori ai 2 MB ricevo in risposta "internal error".

Di seguito request e response (il contenuto del file è troncato perchè troppo grande da caricare su github):

REQUEST:
{
    "allegatoInput": {
        "contenuto": "JVBERi0xLjQKJcfsj6IKNyAwIG9iago8PC9MZW5ndGggOCAwIFIvRmlsdGVyIC9GbGF0ZURlY29kZT4+CnN0cmVhbQp4nK1bW48dxREW2F7ba2SzvmF8y4EYOAezQ98vr1HyEvFCtG+QJxKQEpHI5P9L+aov09UzPXvWNlhCs3Oqq6uqq7+uS8+bnZik2gn6Vx9++vX027/F3S//O32zM8rY9FJLsVPa75xVYXI+E+Hdn/97+v2p2P1y+uY0TJr+S+T8+adfd3+6IGq5wwwXP5+KKcZoZPpR7qz2UzA7H/RkzO7i19P9B4eLf53+5QKMSQCbhNsZ45MA0pnJuVgE0FmA95g80KwyTt4JtZgdFoH2GAjbCOj876vMY4bzGDW5nXduCoEm+QGz4E3wUu8/PJzrSUsV5P7a4VxOxiuj99cP5xZvtYz7G+3xhAiktlHtb4KBtzL4/S16qYKWcn+bSJV2yoA0TMHFGOYJLOf0438OfvJSBLu/czg3YOrM/qP0u7Ne0e/nalLRCrf/8beZFxPg7kFOXhvT095LwsBafv8xSaiNVvuzg528dxDwfpOAUTYJHxywulF5yQ3w9lp5KPX3i7/SeriyHjKISSmH1bj4R7I/hhsHAxIn/GSNsA4r4CYvjKHpwV4IFTNpfrxxsMIXxnWhtZ1sWufENxlTQFQHXbhcyUJOBW7NOwdItJBTiclqNfPLAlmnyPQkhoQVb6ZJNNT8gIuZRA/s12vt1+sznyPqWDtFq/P0ELDtBYtNjtXcOW0kIYBRHrsx7H775+nPV0UAKCknYdr+EKrbIAZ+4vIGuQX3ckH7tPyG9kqU/BEmjZMBGmlIiSXw5Eh3kqfEqOtwY+HUsEYMWFNYHqugo8fzXSyCVkJb8kO4v4nWwmPxO6wkQnJZ4RU43ceTcVL5QmmFUuxn8ljhNd49JH8XApt3nsjr/aPB748bo8e0LspiG34CQmihYzf8yQGWj9DD7z+dObU5034yEv/eQTqY4Sl5JjBHaWyuZyBRwoL4+TyssXpBfhNFhO1f0hihcTh0spbXChRZGQ8g+cNQ/6o0s0T5OZj9rjBVWgdmv0/SllbkoFHX/cEYcFHqSnrDpm3G+Gx+6ozxOSFBAKZgyzYNjqjV3v0xYYo0vjc2Thgcbmb/ikS11mGLZltKCQOeHSQUMnDeL9JamuDckNMLGC06G3rzPB+Yl3Fn09/rLFXffnk4d5N0FnyZKe+tlqUz30tsvWC0dAumA6e/Ny91/R2Qs/+KDB3hVRbj9sDsIL30HQlfi8wkWOz6QzKisaHObTxguywRjMuW43H2F5zwQc3+8vAgNX6PSd4GvZZBUuggSfkCSTQAaJigMmIl5hE6uG4E1tOqdspbixM1H1cGB47L5xU9SsIrUGOlsvkQZliH4zfQma5xXBmsEKO530beI2qgkozpdNGwj8Dh8hDbVeFQlfwlm/ARmBka5yqBFIpP0RiccHkYBePGlHpEKwf7K1UHIkagNTinAMu62L2+CXQWsEvcULT9/kmbjaCKThUcjzMtHOVBoxgze0LOEQ3w/XojvdHxrZZivD5l4jJmT4HHMInEfn3WHs8OFFwInF/YkPPb50MCxgEbFeehBryDNjmrxJwiVmdlMzCFq6ck0YrKKnQkj6ERwi3gQ1HZCl1VpsfbyQ3CvCgq+uAHPkq0zDx1Bp12HGgDNhqgEBCigsCe2oGgeimNZRy5wxZn8VhfJjSBMqLEKLlSnw8F6UzQ/1GItC4gmkTELNjHkNAXB0cIy2fhwr0aWpRTcE++Rj7p1RzFZmXbJMPp1t5L+jGCTiVGzWbr9nf1HeyY6jtfNMaMAVu2j+BcSKaAjXxmtjTlrQ2KrwJ723Qb+Agm+xK7GHEVQmxuvQ8TgYlwl68YbsGHcB6pjlcdZkyk1SRgNU6X2P7cIFTWPuzOJcIWk7UeICQQ7P0QsmilCQxt6HGxx/JKgiNNp13VKV6NCNsvsXUeOJyxKAWsHhmHbSjXAIEwsNeqEjA3ZXOMUX2s3sqnTQ4vlluo4PBCDWLGd9AXwzkejIk3jj2m3tgU10CqdQ8iddsAgefwgLn/ei0sUq+GrFwUhrJcWqy49JMVyItPjgFWP80YFk56VKjEN4aA21aJKbUFY4xbO3s7OU/GMrO52TQdMUI2SRqkYzvt3GLztnFzoln+/O704usfKjzRsV0soGNb6OiWfhyJwnAn29grXw/HbUUcfG1iVoLJwDysj99GI012HmRQbiMSuU2cgYK695fxhhxP8Xr08voQCDZdkv/ARGKPTO/xfmPmGsdnS+dbLcNY6ebUTKcSySsB3BZzheetnLSKgGTjwXgvM4pvKKDUUSH/OT/AaXUI3e/sZOUcJrwOSCNN/3p94q4igMFSyxVArcVnBBuarMy5wJDjBtgIophS41CSEzPOPfEc7m/HewMU6PS6e6DsWpkuA+s4TCkIhwqEr+RHMjrQsQrcOOYaudRYmvGSbOvEQiy+3IUkBGdnvbVTy+CqvmZDGcMiLLJm/njCWWeTWR3714z8VeP3LT1K56LlE77mmZpSDkmNzDGboPqfS9BP9cackteIbI2sl2P+OlZg9m1Q0kVbbbajzLaitGJwSbHoOIjsJZptsRG9HA97mj/f7+I0iohFn5OXYdndPh+zOxKAkCBjWL/CwHrGyXc643y0l5xxs2wZ7gGnYY7cuG0ZKKXAT4FuibkpyNfL9LYGQeO0mRFsHpiMXKS9IXX0G6HduvKwPHVWhZJFjsZ8eLETy2yMoEFhe9pA5Nm15ByyFWsvY7bSHAgWieeU62BXapOFS2toDvBbCmgQynuETAZC6bRzEwwE8qFIgT2STadjOsGAM9YrWjI3KQeoyk0TvNQyP1pjY26QqCCU6fgnCwdtg+S88qzSkONG+tklq80n/J1ZgNw908blAwZ2jSqDaJpXUgQF48myd+jUCVGEnoOZgnEiN9osNhIes4o2N9r6nB3iIM++ezD01qvsttYLqeq0ugb9gGtI8HEqnwoJWibuWarxOq35qPvtd2aOB6mw7mPuwMzSML5lNuc0hWsU+gNGyGmpB+idWhlX5n7NrA4hCBYkUkuE3C1EaUeqAw+heu0JeOtZ5LcUrDQcZ8H4M0ikg5Ah7J+QqQVmpl4LcB/SPCUzYFuE/bPkNr53teKKpOHzeRnupGpGFDJV+gXNr3CQFYvrFKAggoK9BFXSZEpNLRXSZMBRqVMSIpIvBsdVuIJmjHOzLh/HpHhCckbj5BF927vGkkrugkr7VPXDjCbAvYq2VInngpzlreM0Z/AsmR0Ho9x/RgvqnE8HFj1JQ90U6y2soWiFM8xcqcmoxBa0WCMIuwq4dI3+Hr8g/g7ndUxtTmn8zr5Nl3NbgIxtyk9uvgVAvVhLrfsPcuwJ69QM+EOq/uIkjXQxgFIb2gfXk9kRTjn28gY16Syy6gQbZvIBx8hNSjdCkCqdHXipjKOGsfKmWfStgXtbuWCnsMPKTaYod7scKFTehgNKHEMq+2J9PElgooyn+w4qHXQpFgMyYkOF1LolxE83E6hfS34FbFWpKq7KIGMqI42j6245x7TzaWcnCSS5YKW4mSaQDtHr3Wwkr2MRMWrgJJ/tCtywfb1N2xuQr1Uu9tSf2aCyCjTXfXpLiqcFjROUCbEwgDtQEOEJCEzk6jJhHyRklEEpNuph+z1bRpoU5QuYGzlBggxJ2yvMVqTWVJkMQQBzqbuzo5XDKlnBcCUek70MsBdoRbGLEldQlxHUtF37KXtRAm+Spji0tjlLisg1JWCIofOcSVM3xVpy0wQoFCanRk9xjOps1NKeZSirZ43LrdIcVVW3cJ6Z4WWyM6aXqeOLOa0hcHZkjVx6qGbsNZuFHlq3icVGMQGOa0qhXoTPPM27RSjNmL6kNdd0LSBQS0YQylL+8aLlbddILMSFhu7cdFlJ4VGtqVyGZ0xhQsbn/Ah81vH3xOYOPF4dqJthoqNolU434ShIzSg5xC4vAdpSpNtp2gf7+4K2oJVpx0bXBS65bEZtSYIHLOKwAEnNCP48rpQPqrQ5CR1WKTsKnm5ellgvZhzVHxYk4w4BF3Uusr9dxsio+0JlStHkXEyV3m20NI62lt+nsLqWkiXp66YPopxR12eZgrOBalS97LuFNZtr2ey4FLUuaeSKPmEEoHx2G4LqceI7ZjbOgVtVYqOVsNWpZuxWVZolj43c+m1ydda9HNTKSL/UiJR912S7WFn7mxsF3VfDpWPqM4HH/abj9Wru5dl7kDiEMGhjMS013YlL7Qfqh08xSKs2ahBHzbuoURbaVjpkhci+cMnKiB2PrkoIRHXRdJ1dJmcrMbHrJYNuYHT8kWHLoH2xWVyc+zoGAeHepPwEoOM5k7YarHnGW865uR3joPpoPF+NTeQ8js9vV3ijM0vKrXtJYwg8WjY63gPe6j9uHWxVzFUDn/U1V62nQRF/bZJFa3UMgeOuSLPDrRwk+WA3dky3buPNvmWSjUN2DNv3h0qxWxXNau3SxcYMYxhgMxQRaD8s2zhr4vUdsUv0Z+DKxq2nXo7b6EJlaomMaKM6WtwuGj7dtXIvIE5IJQbdxOF5zIrxRxvv43bMonWzrhZ33ZjhMcyDv3w4DW4mrGCYQ/Uh3e93yBbmWzZUhox2XPh9s1POqPJ9RthR3cQobeYPRJS68vcZm5cqtY2TMzuLE65E4Gn+cy39hBR9h0zLdXcIWixebv65dsVJx9HNmsWZ0EC6PeUIgS6JX75rFkHhkctCNnSel9dMUgmxdiWNHJ1s/T2XrSYA/7igGjfSbVgxl0q/JHqc2EiVv061Y0EfnzxMZSlNcuRKdlbm9YEaoSLE7u2LlA07H8kehgoQim5rVTdivBjlNweVNFW50qnwLl0rV8mclr/lc20I9qCJftYK0ewtJ340JG4CFSkpqjtfS0EbLqsZvKtTiJhK/pH/zURtxmhPnzbKnsk8S1kal66dz3I0DmesLPwbR4NL510vRxwveBahXiw0Yb5YeHbw8DtyzI+JgQ9UFx6r0wy1VsZRnaOsOEHPYMVJBPa6cdsw0+OZoJEyzZhgbN5GOh0AyfPXMHXDBHDXcs7LWKz2enQiXOFy7mV4nZKJ68PzbpwUMAJLRSflkccU7E4QLaUPOyN0KmYjZlG1LvI+mJxqIsabqdxzL1ahYhH/8Mry0Qbs8mjl/KQx3jocnplBrhBqkb5xAyukqKnx4SehotTAtfryLEXgUJLORuxZSxv5g7QXfFCOXes/Ij3+b7fE726i1cReeY7g4wPl0usm+RS4vBbTcsnVmTG8uXovxciOquUnR2YRnit66VXTS74wmIs840tlfRJVb827g04tzABIpWokYvr07VpMlUtVv5MA+3yZ3Mf04dbcs/I5LPGVkTSDgM4lILukJEEEG1nbXCAZfwywEXZ2mX5OwyPVZVdFnCvc9lkkIVs3+Ot90itXtNZX+GeoGr49UtQ5Htpv36UvHN4tsg9Dh9SaI3J3e7CG413NjH9Ash1ib1+JHdt3eI1uHbYtyjE12PbOzKjJytDn1ZmoZ2Ny5F1rz+OPmTOuCfhFK1RLk763/I7+/Ir9T5oUTZf37/y5s9KbX3RqZOBupzW1WtrXUFiyEEtrU3lLKRTkVVYRoGBe7HZJN9fn309g+6Cok3GzfV92ix4Bs+lmY/399syJDW8vafUFfUAQu/nZYxlGX5HdPLxlZ+OyJdEyfWTe95y/P/0/5ETkLwplbmRzdHJlYW0KZW5kb2JqCjggMCBvYmoKNDIyOQplbmRvYmoKNiAwIG9iago8PC9UeXBlL1BhZ2UvTWVkaWFCb3ggWzAgMCA1OTUgODQyXQovUm90YXRlIDAvUGFyZW50IDMgMCBSCi9SZXNvdXJjZXM8PC9Qcm9jU2V0Wy9QREYgL0ltYWdlQyAvVGV4dF0KL0V4dEdTdGF0ZSAyNSAwIFIKL1hPYmplY3QgMjYgMCBSCi9Gb250IDI3IDAgUgo+PgovQ29udGVudHMgNyAwIFIKPj4KZW5kb2JqCjMgMCBvYmoKPDwgL1R5cGUgL1BhZ2VzIC9LaWRzIFsKNiAwIFIKXSAvQ291bnQgMQo+PgplbmRvYmoKMSAwIG9iago8PC9UeXBlIC9DYXRhbG9nIC9QYWdlcyAzIDAgUgovT3V0cHV0SW50ZW50cyBbIDUgMCBSIF0KL1BhZ2VMYXlvdXQvU2luZ2xlUGFnZQovUGFnZU1vZGUvVXNlTm9uZQovUGFnZSAxCi9NZXRhZGF0YSA2MCAwIFIKPj4KZW5kb2JqCjkgMCBvYmoKPDwvVHlwZS9FeHRHU3RhdGUKL09QTSAxPj4KZW5kb2JqCjI1IDAgb2JqCjw8L1I5CjkgMCBSPj4KZW5kb2JqCjI2IDAgb2JqCjw8L1IyMgoyMiAwIFIvUjEzCjEzIDAgUi9SMTAKMTAgMCBSPj4KZW5kb2JqCjIyIDAgb2JqCjw8L1N1YnR5cGUvSW1hZ2UKL0NvbG9yU3BhY2UvRGV2aWNlQ01ZSwovV2lkdGggMTIzOAovSGVpZ2h0IDIwOQovQml0c1BlckNvbXBvbmVudCA4L0xlbmd0aCAxMDM0OTY4Pj5zdHJlYW0K..................................NTcxMjk3Njg1MUQ+PDAyRkQyREFCOEM1RThCQTdGNzE2MzU3MTI5NzY4NTFEPl0KPj4Kc3RhcnR4cmVmCjE5ODcyNDAKJSVFT0YK",
        "nomefile": "exporttabelle.pdf",
        "tipoFile": "1",
        "tipoAllegato": "33",
        "descrizione": "Atto di morte (in originale)"
    },
    "testataRichiesta": {
        "idComune": 5000,
        "idOperazioneComune": "2766",
        "dataOraRichiesta": "2023-10-10T17:23:12.757+02:00",
        "nomeApplicativo": "urbi",
        "versioneApplicativo": "0.1.0",
        "fornitoreApplicativo": "padigitale"
    }
}

RESPONSE:
{
    "message": "internal.error",
    "errors": null
}

**Comment by amusarra** [comment]
Buongiorno @biadanpad 
Potrebbe ripetere l'operazione e inviare il payload completo all'indirizzo email di supporto (supporto-ansc[at]sogei.it)?

Cordiali Saluti.
Supporto ANSC.

**Comment by biadanpad** [comment]
inviata, grazie.

**Comment by AMonopoliADS** [comment]
buongiorno 

abbiamo rilevato la stessa anomalia.
(comune di San Lazzaro di Savena; "idComune": "8647" / "idOperazioneComune": 2023000469)

seguiamo x sapere se il problema verrà risolto in assoluto o se sarà necessario fornire gli elementi per le verifiche.

grazie
Alessandro Monopoli ADS

**Comment by amusarra** [comment]
Grazie @AMonopoliADS 
Abbiamo ricevuto quanto richiesto. Faremo delle verifiche e vi terremo aggiornati.

Cordiali Saluti.
Supporto ANSC.

**Comment by amusarra** [comment]
@AMonopoliADS  e @biadanpad abbiamo replicato il problema e sono in corso le opportune analisi.

Cordiali Saluti.
Supporto ANSC.

**Comment by amusarra** [comment]
@AMonopoliADS e @biadanpad il problema è stato risolto.
Potreste eseguire un test e in caso di esisto positivo chiudere la issue?

Grazie.
Supporro ANSC.

**Comment by biadanpad** [comment]
Ho appena fatto il test.
Su 4 tentativi 3 volte è andato a buon fine e 1 volta è andato in timeout

**Comment by amusarra** [comment]
> Ho appena fatto il test. Su 4 tentativi 3 volte è andato a buon fine e 1 volta è andato in timeout

Per l'oggetto della issue è importate che il problema segnalato è stato risolto, e dalla risposta l'esisto del test è positivo.
Per quanto riguarda il problema del timeout, potrebbe essere di diversa natura e non è oggetto di questa specifica issue.

Nel caso in cui anche il test di @AMonopoliADS dovesse avere esito positivo (sempre per l'oggetto dalla issue), chiudermo la issue.

Cordiali Saluti.
Supporto ANSC.

**Comment by AMonopoliADS** [comment]
> Nel caso in cui anche il test di @AMonopoliADS dovesse avere esito positivo (sempre per l'oggetto dalla issue), chiuderemo la issue.

il nostro test ha avuto esito positivo.
grazie
