### ISSUE TITLE
Nascita - Data dell'intestatario atto

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#4]
![Cattura_3](https://user-images.githubusercontent.com/127182190/223346030-9c65a979-30f3-4817-ac5e-f0e5efd0df46.PNG)

**Comment by asqueglia** [comment]
Buongiorno confermiamo che con il rilascio della versione 1.9.1 la segnalazione è stata corretta (ora e minuto nascita sono stati resi campi opzionali). E' possibile riprovare. Chiudiamo la issue, nel caso la preghiamo di riaprirla.
