### ISSUE TITLE
[R006] - errore su firma dichiaranti

### ISSUE THREAD

**Issue by siscomanpr** [italia/ansc#40]
Utilizzando il servizio R006 includendo la lista dei firmatari ci restituisce degli errori:
fatta prova con lista firmatari con solo cognome e nome restituisce errore http 500
idOperazione=1572225
[1572225_Response.log](https://github.com/italia/ansc/files/11039028/1572225_Response.log)
[1572225_Request.log](https://github.com/italia/ansc/files/11039030/1572225_Request.log)

indicando invece anche un codice fiscale (uno a caso) da errore: code=400003 text=Dati in ingresso non corretti
idOperazione=1572232
[1572232_Response.log](https://github.com/italia/ansc/files/11039060/1572232_Response.log)
[1572232_Request.log](https://github.com/italia/ansc/files/11039061/1572232_Request.log)

Sbagliamo qualcosa noi nella compilazione del json?

**Comment by amusarra** [comment]
Salve @siscomanpr 
Abbiamo analizzato la problematica e presa in carico. Si tratta di un bug che siamo riusciti a replicare. Non appena avremo qualche novità sulla data di risoluzione, le faremo sapere.

La informiamo che la richiesta corretta prevede anche il codice fiscale. Nel frattempo, per andare avanti, potrebbe applicare il processo di firma senza specificare la lista.

**Comment by amusarra** [comment]
Buongiorno @siscomanpr 
Al momento i placeholder per la firma dei dichiaranti sul modello scaricato dal servizio di presa visione non è disponibile ma stiamo cercando di lavorare su questo punto per renderla disponibile.

Saluti.
Supporto ANSC.

**Comment by amusarra** [comment]
> Salve @siscomanpr Abbiamo analizzato la problematica e presa in carico. Si tratta di un bug che siamo riusciti a replicare. Non appena avremo qualche novità sulla data di risoluzione, le faremo sapere.
> 
> La informiamo che la richiesta corretta prevede anche il codice fiscale. Nel frattempo, per andare avanti, potrebbe applicare il processo di firma senza specificare la lista.

Buongiorno.
Il problema è stato risolto con il rilascio odierno.
La segnalazione sarà quindi chiusa.

Saluti.
