### ISSUE TITLE
Dati su notifica per annotazione automatica

### ISSUE THREAD

**Issue by antonioluberto** [italia/ansc#400]
Buongiorno.
Abbiamo creato l'atto di stato civile
**2023-1114194-143-058046**
per il caso d'uso
Morte_001.
Abbiamo indicato per il titolare la presenza di atto di nascita digitale:
**2023-951684-7-058046**.

La notifica relativa all'annotazione automatica che otteniamo mediante il servizio **_R008_** contiene le sole informazioni:

![image](https://github.com/italia/ansc/assets/26415430/fd940288-66e5-4c1b-bc7b-b7b5553ebace)

Per confermare l'apposizione dell'annotazione automatica sull'atto, l'usc dovrebbe però trovare nella relativa notifica - in forma esplicita - almeno le informazioni relative a:
- gli estremi dell'atto "primario" (sul quale andrebbe apposta l'annotazione), incluse le generalità del/i soggetto/i titolare/i
- gli estremi dell'atto "secondario" (in ragione del quale è stata generata l'annotazione automatica notificata) 
- il testo dell'annotazione da apporre sull'atto "primario"

in qualche modo analogamente a quanto avviene su WebApp.

I soli "identificativi" che attualmente il servizio **_R008_** non sono sufficienti perché l'usc comprenda il tipo di validazione che gli viene richiesta.

**Comment by asqueglia** [comment]
Buongiorno @antonioluberto , il servizio da utilizzare per ricevere le informazioni richieste sulla annotazione è l'R005 invocato trasmettendo in input l'idAnsc dell'evento annotazione. Però al momento il servizio R005 presenta un bug; c'è una issue aperta sull'argormento #371.
Provvederemo a correggere quanto prima.
