### ISSUE TITLE
[R009] - errore su flagSecretato

### ISSUE THREAD

**Issue by LucaBonini64** [italia/ansc#402]
Buongiorno, 
fino alla versione 100002 all'interno dell'evento doveva essere presente nell'evento il campo flagSecretato, con la versione 100003 invece nella validazione di un evento legato all'usecase 311111 la risposta contiene:
{"testataRisposta":{"idEsito":-1},"errors":[{"code":"400","severity":"E","text":"La proprietà 'evento.flagSecretato' non è prevista."}]}
Nel Model_evento vediamo che il flagSecretato continua ad essere presente e negli Usecase invece non è mai indicato, ci potete quindi indicare quando è possibile/necessario indicare tale campo?
Grazie
Luca Bonini APKAPPA

**Comment by asqueglia** [comment]
Buongiorno, verifichiamo e le facciamo sapere

**Comment by asqueglia** [comment]
Buongionro con il rilascio della versione 1.15.0 è stata corretta la segnalazione; chiudiamo pertanto la issue. In caso di ulteriori segnalzioni preghiamo di aprire una altra issue dedicata.
