### ISSUE TITLE
firma elettronica non funzionante

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#405]
La firma elettronica degli eventi non funziona:

![image](https://github.com/italia/ansc/assets/131870281/ba570433-03ef-4be0-beb6-beef135721ce)

**Comment by amusarra** [comment]
Buongiorno @biadanpad 
Da controlli eseguiti sul sistema, risulta che i firmatari per presa visione sono due:
1. risulta che uno dei firmatari (Valentina) ha già preso visione, invece Barbara non ancora.

Dallo screen non risulta chiaro per quale firmatario ha ottenuto l'errore.
Potrebbe indicare la dinamica?
Ottiene l'errore nel momento che esegue il clic sul pulsante di "Conferma visione"?

Cordiali Saluti.
Supporto ANSC.

**Comment by biadanpad** [comment]
Si, confermo che per Valentina la firma è andata a buon fine, mentre per Barbara no.
L'errore si ottiene al momento in cui si clicca sul pulsante "Conferma visione".

**Comment by amusarra** [comment]
Grazie per la conferma @biadanpad 
Il problema dovrebbe essere dovuto al fatto che, al momento della prima presa visione, l'evento ha subito erroneamente il cambio di stato a FIRMATO DAL DICHIARANTE, stato a cui dovrebbe passare se e solo se tutti i firmatari hanno apposto la firma.

Abbiamo preso in carico la segnalazione.

Cordiali Saluti.
Supporto ANSC.

**Comment by asqueglia** [comment]
Buon pomeriggio, abbiamo corretto la segnalazione con la versione 1.18. Pertanto chiudiamo la issue; in caso di anomalie o ulteriori approfondimenti la preghiamo di aprirne una altra dedicata.
