### ISSUE TITLE
Composizione annotazione matrimonio

### ISSUE THREAD

**Issue by LucaBonini64** [italia/ansc#406]
Buongiorno,
ho visto che l'annotazione per matrimonio sull'atto di nascita degli sposi è formata per entrambi nello stile:
"SPOSO ha contratto matrimonio con SPOSA il..."
mi risulta invece che solo l'annotazione sull'atto di nascita dello sposo sia formattata in quella maniera, mentre sull'atto di nascita della sposa dev'essere:
"SPOSA ha contratto matrimonio con SPOSO il..."
Cordiali saluti
Luca Bonini APKAPPA

**Comment by asqueglia** [comment]
Buongiorno, verifichiamo e le facciamo sapere.

**Comment by asqueglia** [comment]
Buongiorno, con il rilascio della versione 1.20.0 dovremmo aver risolto la problematica. Chiudiamo pertanto la issue; in caso di ulteriori segnalazioni, vi preghiamo di aprire una issue una dedicata.
