### ISSUE TITLE
Mapping caso d'uso CITT_017

### ISSUE THREAD

**Issue by MichelaGarzoni** [italia/ansc#407]
Buongiorno,
nel mapping relativo al caso d'uso CITT_017 troviamo questa definizione:
![image](https://github.com/italia/ansc/assets/128141738/128a6fa7-86a0-483d-93b7-091601830907)
dove i dati relativi alla provincia e al comune risultano obbligatori. 
Ma se stiamo trattando un comune che fa riferimento ad uno stato estero, come ci comportiamo?
In tutte le altre situazioni in cui si tratta i dati relativi ad uno stato estero, se non abbiamo capito male, il comune e la provincia non sono obbligatori e non vengono richiesti.

**Comment by asqueglia** [comment]
Buongionro abbiamo verificato. Provvederemo a correggere la segnalazione il prima possibile.

**Comment by asqueglia** [comment]
Buongiorno con la versione 1.15.2 è stata corretta la segnalazione. Chiudiamo pertanto la issue; in caso di malfunzionamenti o dubbi preghiamo di aprire una issue dedicata.
