### ISSUE TITLE
Dichiarazioni multiple per ModelEnteEstero in ModelEvento.yaml.

### ISSUE THREAD

**Issue by gcuci** [italia/ansc#41]
buongiorno,

con la versione 1.5.2 dei servizi, sono stati aggiunti i campi 'nazioneEnte' e 'nomeNazioneEnte', al ModelEnteDichiarante.

Questo però è causa di un'anomalia, che si verifica in fase di utilizzo delle classi generate dallo swagger, di 'generator declares multiple JSON fields' per il ModelEnteEstero, quando il ModelEvento viene restituito dal servizio (es. Consultazione ANSC per Soggetto o per Evento). Questo perchè il ModelEnteEstero, estende il ModelEnteDichiarante, ma ha anche lui le proprietà 'nazioneEnte' e 'nomeNazioneEnte'.

Per continuare ad utilizzare i servizi, abbiamo ripreso il ModelEnteDichiarante generato con la versione precedente (senza 'nazioneEnte' e 'nomeNazioneEnte'), che non è però allineato. Bisognerebbe correggere il ModelEvento.yaml, eliminando le proprietà duplicate in ModelEnteEstero.

In attesa di un riscontro,

cordiali saluti.

**Comment by mttfranci** [comment]
Salve, 
Stiamo valutando la vostra segnalazione e stiamo valutando le possibili azioni da intraprendere.
Saluti

Assistenza ANSC

**Comment by asqueglia** [comment]
Buongiorno, con il rilascio odierno versione 1.6.0, l'anomalia è stata risolta.
