### ISSUE TITLE
Indicazioni su notifica annotazione su atto di nascita post atto di morte

### ISSUE THREAD

**Issue by antonioluberto** [italia/ansc#410]
Su ambiente di pre-produzione del Comune di Grottaferrata, abbiamo creato l'atto di morte:
**2023-1114204-145-058046**
il cui titolare è soggetto residente presso un secondo Comune (non in ANSC) ed ha atto di nascita (caratceo) presso un terzo Comune.

Su ambiente di pre-produzione del Comune di Grottaferrata riceviamo notifica 
Id: 2224704
tipo: "Annotazione"
riferita all'evento ANSC: 2023-1114201-00000-058046.

La stessa notifica è presente anche su WebApp:

![image](https://github.com/italia/ansc/assets/26415430/74ad3f71-2ef9-4b59-ab21-74af7b2d2a1d)

e contiene l'annotazione che dovrebbe apporsi su atto di nascita del titolare:

![image](https://github.com/italia/ansc/assets/26415430/bd9fcef1-ce22-4245-9caf-82baad7fb705)

Questa notifica dovrebbe essere acquisita dal Comune di Grottaferrata per essere poi trasmessa al Comune presso il quale si trova l'atto (cartaceo) di nascita del soggetto titolare?

In caso affermativo, è necessario che la notifica in questione contenga i riferimenti (anno/numero/parte/serie/Comune) all'atto di nascita cartaceo del soggetto titolare.

In caso negativo, si chiedono indicazioni circa l'utilizzo previsto per la notifica in esame.

**Comment by asqueglia** [comment]
Buongiorno @antonioluberto la risposta alla sua domanda è si, il comune di Grottaferrata può scaricare l'annotazione automaticamente generata da sistema come ausilio,  e deve inviare l'annotazione al comune che detiene l'atto cartaceo, tramite PEC  o tramite le attuali modalità operative previste dalla normativa, ; è cura e responsabilità dell'USC verificare chi è il comune che detiene l'atto cartaceo; il sistema non ha questa informazione in quanto il comune di formazione dell'atto cartaceo di nascita non è detto che coincida con il comune di nascita del soggetto. Come descritto nella guida operativa della gestione del transitorio, gli atti cartacei devono essere gestiti extra flusso, compresa l'individuazione del comune che detiene l'atto cartaceo. Si precisa che non appena il comune di formazione (quindi Grottaferrata) riceve, sempre extra flusso, la comunicazione di avvenuta apposizione della annotazione sull'atto cartaceo, il comune deve confermare la proposta di annotazione per sbloccacre il flusso di invio della predisposizione anagrafica.

**Comment by asqueglia** [comment]
Buongiorno , provvediamo a chiudere la issue. In caso di ulteriori segnalazioni la preghiamo di aprire una altra issue dedicata
