### ISSUE TITLE
[R002] - Estratto integrale - Errore interno

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#411]
Cercando di scaricare l'estratto integrale, il servizio R002 risponde con "Errore interno"

Di seguito request e response:

REQUEST:
{
    "idAnsc": "2023-1114537-15-108028",
    "idEvento": "1114537",
    "richiedente": {
        "codiceFiscale": "CTTMGH68B41E617G",
        "cognome": "CITTERIO",
        "nome": "MARGHERITA",
        "sesso": "F",
        "dataNascita": "1968-02-01",
        "idComuneNascita": "5001",
        "nomeComuneNascita": "LISSONE",
        "idProvinciaNascita": "15",
        "siglaProvinciaNascita": "MI",
        "idStatoNascita": "90",
        "nomeStatoNascita": "ITALIA",
        "idComuneResidenza": "5000",
        "nomeComuneResidenza": "LISSONE",
        "idProvinciaResidenza": "108",
        "siglaProvinciaResidenza": "MB",
        "idStatoResidenza": "90",
        "nomeStatoResidenza": "ITALIA",
        "indirizzoResidenza": "VIA MAMELI GOFFREDO,52 sc.C int.0",
        "idNazionalita": "null"
    },
    "intestatario": {
        "id": "2226369"
    },
    "idTipoCertificato": "3",
    "conPaternitaMaternita": false,
    "testataRichiesta": {
        "idComune": 5000,
        "idOperazioneComune": "2838",
        "dataOraRichiesta": "2023-10-13T09:10:12.064+02:00",
        "nomeApplicativo": "urbi",
        "versioneApplicativo": "0.1.0",
        "fornitoreApplicativo": "padigitale"
    }
}

RESPONSE:
{
    "testataRisposta": {
        "idComune": 5000,
        "idOperazioneComune": "2838",
        "idOperazione": "1659004"
    },
    "errors": [{
            "code": "500",
            "severity": "E",
            "text": "Errore interno"
        }
    ]
}

**Comment by mttfranci** [comment]
Buongiorno, l'idNazionalità (come gli altri campi), se non presente, andrebbe non trasmesso oppure trasmesso come null : 

`"idNazionalita": null`

In quanto:

`"idNazionalita": "null"`

Viene interpretato come valore stringa "null" e al momento provoca un errore.

Saluti

PS: verificheremo se è possibile gestire in modo più parlante queste situazioni.

**Comment by biadanpad** [comment]
mi permetto di farvi notare che fino a ieri non avevamo mai riscontrato questo problema

**Comment by mttfranci** [comment]
@biadanpad  abbiamo trovato diverse operazioni, inviate dallo stesso comune per cui si è verificato lo stesso comportamento.
Ad esempio l'operazione id 1638481 del 28 Settembre 2023.

Saluti
