### ISSUE TITLE
[R009] - Valorizzazione del campo 'testoLibero' per i campi trascrizione<tipoRegistro>

### ISSUE THREAD

**Issue by gcuci** [italia/ansc#413]
buonasera,

per alcuni casi d'uso, nel ModelEvento, è prevista la valorizzazione di campi di trascrizione tipo trascrizione<tipoRegistro>.

Per esempio per il caso d'uso Citt_045 è previsto il campo 'trascrizioneCittadinanza' di tipo ModelTrascrizioneCittadinanza. Queste strutture dati prevedono sempre il campo 'testoLibero', che attualmente noi valorizziamo con una stringa statica descrittiva. 

Ci sono indicazioni più specifiche su come deve essere valorizzato questo campo?

In attesa di riscontro,

cordiali saluti.

**Comment by asqueglia** [comment]
Buongiorno non avendo ricevuto feddback in merito, provvediamo a chiudere la issue. In caso di ulteriori segnalazioni la preghiamo di aprire una altra issue dedicata
