### ISSUE TITLE
[R009] - Caso d'Uso Sep_Div_005: obbligatorietà su protocolloAttoConiuge.

### ISSUE THREAD

**Issue by gcuci** [italia/ansc#414]
buongiorno,

riportiamo una richiesta del Comune di Firenze, relativamente ai controlli di obbligatorietà dei campi protocolloAttoConiuge, per il Caso d'Uso Sep_Div_005.

In particolare nel caso in cui siano presenti entrambi gli avvocati (coniuge1 e coniuge2), è richiesta l'obbligatorietà di dataRicezione e protocollo di 2 Atti (coniuge1 e coniuge2).

Fermo restando la presenza dei 2 avvocati, spesso accade che solo uno di loro invii l'atto al Comune.

Si chiede quindi se possibile limitare l'obbligatorietà a dataRicezione e protocollo di un solo Atto (coniuge1 o coniuge2), anche in presenza di entrambi gli avvocati.

In attesa di riscontro,

cordiali saluti.

**Comment by asqueglia** [comment]
Buongiorno, verifichiamo e le faremo sapere.

**Comment by asqueglia** [comment]
Buon pomeriggio, abbiamo corretto la segnalazione. Pertanto chiudiamo la issue; in caso di anomalie o ulteriori
approfondimenti la preghiamo di aprirne una altra dedicata.
