### ISSUE TITLE
Chiarimento: scaricamento atto dopo la firma USC (segue #178 e #141)

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#418]
Buongiorno, 
con il rilascio della versione 1.15.0 non è più possibile ottenere estratti per copia integrale per alcuni casi d'uso come ad esempio il 341000.
Vi rivolgo quindi nuovamente la stessa domanda: come posso ottenere, utilizzando i WebService, l'atto registrato così come posso fare attraverso la WebApp cliccando sul pulsante "Ottieni atto regisrato"?

![7d091536-a73f-4947-bd8f-c2530407e1b8](https://github.com/italia/ansc/assets/131870281/0703f206-f522-428d-ba62-a537ae7eda5f)

Cliccando sul pulsante "Ottieni atto regisrato", la webapp produce proprio l'estratto per copia integrale (allegato) che, per questo caso d'uso, non è più possibile ottenere in alcun modo:
![image](https://github.com/italia/ansc/assets/131870281/71597f3d-21a6-4fb6-ad71-0ddc658ffd9c)

[estratto_copia_integrale.pdf](https://github.com/italia/ansc/files/12926842/estratto_copia_integrale.pdf)

**Comment by asqueglia** [comment]
Buongiorno, per ottenere l'atto registrato è possibile utilizzare il servizio R005 di consultazione evento che restituisce tutto il model evento con tutti i dati trasmessi per quell'evento; in alternativa è possibile utilizzare il servizio di certificazione R002 con "idTipoCertificato": "3"  per ottenere l'estratto integrale in formato pdf.

**Comment by biadanpad** [comment]
Il problema è proprio che il servizio R002, dopo l'ultimo aggiornamento, fallkisce con messaggio di errore: "Il Tipo di certificato ESTRATTO_INTEGRALE non può essere generato per l'atto 1114484"

Di seguito request e response:

REQUEST:
{
  "idAnsc": "2023-1114484-183-108028",
  "idEvento": "1114484",
  "richiedente": {
    "codiceFiscale": "CTTMGH68B41E617G",
    "cognome": "CITTERIO",
    "nome": "MARGHERITA",
    "sesso": "F",
    "dataNascita": "1968-02-01",
    "idComuneNascita": "5001",
    "nomeComuneNascita": "LISSONE",
    "idProvinciaNascita": "15",
    "siglaProvinciaNascita": "MI",
    "idStatoNascita": "90",
    "nomeStatoNascita": "ITALIA",
    "idComuneResidenza": "5000",
    "nomeComuneResidenza": "LISSONE",
    "idProvinciaResidenza": "108",
    "siglaProvinciaResidenza": "MB",
    "idStatoResidenza": "90",
    "nomeStatoResidenza": "ITALIA",
    "indirizzoResidenza": "VIA MAMELI GOFFREDO,52 SC.C INT.0",
    "idNazionalita": "90",
    "nazionalita": "ITALIANA"
  },
  "intestatario": {
    "id": "2225961"
  },
  "idTipoCertificato": "3",
  "conPaternitaMaternita": false,
  "testataRichiesta": {
    "idComune": 5000,
    "idOperazioneComune": "4320",
    "dataOraRichiesta": "2023-10-17T10:10:22.06+02:00",
    "nomeApplicativo": "urbi",
    "versioneApplicativo": "0.1.0",
    "fornitoreApplicativo": "padigitale"
  }
}

RESPONSE:
{
  "testataRisposta": {
    "idComune": 5000,
    "idOperazioneComune": "4320",
    "idOperazione": "1664157"
  },
  "errors": [
    {
      "code": "400003",
      "severity": "E",
      "text": "Il Tipo di certificato ESTRATTO_INTEGRALE non può essere generato per l'atto 1114484"
    }
  ]
}

**Comment by asqueglia** [comment]
Buongiorno, @biadanpad potete riprovare ? abbiamo apportato una fix che dovrebbe risolvere il problema del servizio R002.
