### ISSUE TITLE
[R009] Errore Interno

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#419]
invocando il servizio nel caso sotto descritto si ottiene l'errore in oggetto come risposta:

REQUEST:
{
    "evento": {
        "idAnsc": "",
        "idTipoEvento": "1",
        "idtipocontenuto": "1",
        "idUsecase": "12221212",
        "stato": "CONFERMATO",
        "idVersion": "100003",
        "dataformazione": "2023-10-17",
        "ora": "12",
        "minuto": "12",
        "operatore": "DLCNTN57L67A064W",
        "operatoreNome": "MARGHERITA",
        "operatoreCognome": "CITTERIO",
        "idComuneRegistrazione": "5000",
        "nomeComuneRegistrazione": "LISSONE",
        "idProvinciaRegistrazione": "108",
        "siglaProvinciaRegistrazione": "MB",
        "numeroatto": "123",
        "ausilioInterprete": "false",
        "datiProdotti": "1",
        "allegati": [{
                "id": "2227521",
                "idTipoAllegato": "16",
                "hashAllegato": "kNYDvFimmQjjMhobd63N8lXP9CLtscUSgUrDd1Qp8Vc\u003d",
                "descrizione": "Copia integrale dell\\\u0027atto di nascita del dichiarante"
            }
        ],
        "intestatari": [{
                "id": "2227100",
                "cognome": "NATO",
                "nome": "SECONDO",
                "sesso": "M",
                "dataNascita": "2023-10-15",
                "idComuneNascita": "5000",
                "nomeComuneNascita": "LISSONE",
                "idProvinciaNascita": "108",
                "siglaProvinciaNascita": "MB",
                "idStatoNascita": "90",
                "nomeStatoNascita": "ITALIA",
                "idComuneResidenza": "5000",
                "nomeComuneResidenza": "LISSONE",
                "idProvinciaResidenza": "108",
                "siglaProvinciaResidenza": "MB",
                "idStatoResidenza": "90",
                "nomeStatoResidenza": "ITALIA",
                "idNazionalita": "90",
                "nazionalita": "ITALIANA",
                "flagDichiarante": false,
                "flagComparente": false,
                "flagFirmatario": false
            }
        ],
        "madre": {
            "cognome": "NATA",
            "nome": "MADRE",
            "sesso": "F",
            "dataNascita": "2000-01-01",
            "idComuneNascita": "5001",
            "nomeComuneNascita": "LISSONE",
            "idProvinciaNascita": "15",
            "siglaProvinciaNascita": "MI",
            "idStatoNascita": "90",
            "nomeStatoNascita": "ITALIA",
            "idComuneResidenza": "5000",
            "nomeComuneResidenza": "LISSONE",
            "idProvinciaResidenza": "108",
            "siglaProvinciaResidenza": "MB",
            "idStatoResidenza": "90",
            "nomeStatoResidenza": "ITALIA",
            "idNazionalita": "90",
            "nazionalita": "ITALIANA",
            "flagDichiarante": false,
            "flagComparente": false,
            "flagFirmatario": false
        },
        "padre": {
            "cognome": "NATO",
            "nome": "PADRE",
            "sesso": "M",
            "dataNascita": "2000-01-01",
            "idComuneNascita": "5001",
            "nomeComuneNascita": "LISSONE",
            "idProvinciaNascita": "15",
            "siglaProvinciaNascita": "MI",
            "idStatoNascita": "90",
            "nomeStatoNascita": "ITALIA",
            "idComuneResidenza": "5000",
            "nomeComuneResidenza": "LISSONE",
            "idProvinciaResidenza": "108",
            "siglaProvinciaResidenza": "MB",
            "idStatoResidenza": "90",
            "nomeStatoResidenza": "ITALIA",
            "idNazionalita": "90",
            "nazionalita": "ITALIANO",
            "flagDichiarante": true,
            "flagComparente": false,
            "flagFirmatario": true
        },
        "dichiarante": {
            "cognome": "NATO",
            "nome": "PADRE",
            "dataNascita": "2000-01-01",
            "nomeComuneNascita": "LISSONE",
            "nomeComuneResidenza": "LISSONE"
        },
        "datiDichiarante": {
            "comprensione": "0"
        },
        "datiEventoRiconoscimento": {
            "preMorto": false,
            "attoNascita": {
                "idAnsc": "0",
                "idComuneRegistrazione": "5000",
                "nomeComuneRegistrazione": "LISSONE (MB)",
                "idProvinciaRegistrazione": "108",
                "siglaProvinciaRegistrazione": "MB",
                "idtipocontenuto": "1",
                "numeroatto": "12365",
                "dataformazione": "2023-10-10",
                "annoAtto": "2023",
                "tipologia": "3",
                "parte": "2",
                "serie": "B"
            }
        },
        "consensoMadre": {
            "tipoConsenso": "4",
            "sentenzaTribunale": {
                "nomeEnte": "tribunale",
                "idComuneEnte": "5000",
                "nomeComuneEnte": "LISSONE (MB)",
                "idProvinciaEnte": "108",
                "siglaProvinciaEnte": "MB",
                "dataTrascrizione": "2023-10-15",
                "estremiDocumento": "as34fg"
            }
        },
        "composizioneCompleta": "    Oggi diciassette del mese di ottobre dell\u0027anno duemilaventitre alle ore dodici e minuti dodici nel__ _______________ avanti a me CITTERIO MARGHERITA, Istruttore, Ufficiale dello stato civile del Comune di LISSONE, per delega avuta, è comparso NATO PADRE nato in LISSONE il 01.01.2000 residente in LISSONE, il quale mi dichiara di riconoscere come proprio figlio naturale NATO SECONDO nato in LISSONE il il quindici ottobre duemilaventitre dalla sua unione con _______________ _______________ nat_ in _______________ il _______________ che già lo ebbe a riconoscere come proprio figlio.     L\u0027altro genitore ha rifiutato il consenso al riconoscimento del figlio già da lui stesso riconosciuto, ma al riguardo è intervenuta sentenza del Tribunale per i minorenni di _______________ in data _______________ n._______________ che, munita del mio visto, inserisco nel volume degli allegati a questo registro.     A dimostrazione che nulla osta al presente riconoscimento il dichiarante mi ha prodotto (ovvero: e/o ho acquisito; ovvero: e/o ho visionato) i seguenti documenti: _______________.    Detti documenti prodotti (e/o acquisiti), muniti del mio visto, inserisco nel volume degli allegati a questo registro.   Il presente atto viene letto agli intervenuti, i quali tutti, insieme con me, lo sottoscrivono."
    },
    "testataRichiesta": {
        "idComune": 5000,
        "idOperazioneComune": "5575",
        "dataOraRichiesta": "2023-10-17T15:17:09.853+02:00",
        "nomeApplicativo": "urbi",
        "versioneApplicativo": "0.1.0",
        "fornitoreApplicativo": "padigitale"
    }
}

RESPONSE:
{
    "testataRisposta": {
        "idComune": 5000,
        "idOperazioneComune": "5575",
        "idOperazione": "1665536",
        "idEsito": 1
    },
    "errors": [{
            "code": "500",
            "severity": "E",
            "text": "Errore interno"
        }
    ]
}

**Comment by asqueglia** [comment]
Verifichiamo e facciamo sapere appena possibile

**Comment by asqueglia** [comment]
Il problema è stato risolto. Potete riprovare ? Restiamo in attesa di un vostro riscontro

**Comment by biadanpad** [comment]
continuo ad ottenere lo stesso errore

**Comment by asqueglia** [comment]
Ci scusiamo per il disguido. Abbiamo risolto il disallineamento. Potete gentilmente riprovare ? Ci aspettiamo che adesso non ci sia più il problema. Restiamo in attesa di un vostro riscontro.

**Comment by biadanpad** [comment]
Adesso funzione, grazie.
