### ISSUE TITLE
Test chiamata servizio di decodifica 403 Forbidden

### ISSUE THREAD

**Issue by davidePanettieri** [italia/ansc#42]
Buongiorno, stiamo effettuando un test di chiamata verso il servizio di decodifica
**URL** : https://anscservicepre.anpr.interno.it/services/service/val/config/decodifica/dettaglio/1
ma riceviamo come risposta 403 Forbidden.
Vi allego la risposta e la richiesta utilizzata per analizzare il problema: 
**Request**:
```json
{
    "testataRichiesta": {
        "idComune": 15146,
        "idOperazioneComune": "APP2022032210000",
        "dataOraRichiesta": "2023-03-23",
        "nomeApplicativo": "SIDe",
        "versioneApplicativo": "1.0.0",
        "fornitoreApplicativo": "SistemiInformativi"
    },
    "datiPaginazione": {
        "numPagina": 1,
        "numRecordPagina": 10,
        "numRecordTotali": 570
    },
    "idDecodifica": "1",
    "formato": "csv",
    "compressione": "true"
}
``` 

**Response**:
```json
{
    "testataRisposta": {
        "idOperazione": "1572573"
    },
    "datiPaginazione": null,
    "errors": [
        {
            "code": "403412",
            "severity": "E",
            "text": "Non hai accesso alla risorsa (412)"
        }
    ],
    "success": null,
    "infos": null,
    "warnings": null
}
```
*Data e ora del test : 2023-03-23 11:50:53 
*Ambiente: pre-produzione
* Il sistema risponde con il messeggio "Non hai accesso alla risorsa (412)", c'è un problema di autorizzazione dell'operatore?
* Operatore: Giuliano Caloni CF: CLNGLN69M04I976F  Comune: Milano

Nel caso fosse necessario possiamo fornire i dettagli completi di request e response ( Headers della chiamata).
Grazie

**Comment by mttfranci** [comment]
Salve,
nel claim jwt va inserito il cod istat del comune, mentre nella testata l'id del comune, come da [archivio anpr dei comuni](https://www.anagrafenazionale.interno.it/wp-content/uploads/ANPR_archivio_comuni.csv), potete verificare se questi due dati sono impostati in questo modo?

Per la documentazione completa potete fare anche riferimento alla sezione https://github.com/italia/ansc/tree/main/docs/Note/SpecificheTecnicheServiziCooperativiJWT

Saluti

Assistenza ANSC

**Comment by davidePanettieri** [comment]
Buongiorno, grazie mille per la risposta. 
L'errore era nella richiesta, grazie al file csv che ci avete fornito abbiamo visto che l'idComune da passare nella richiesta deve essere "5646" per il comune di Milano e non "15146" (codice Istat).
Adesso il servizio risponde correttamente.

**Comment by mttfranci** [comment]
Prego.
Siamo a disposizione per ogni ulteriore chiarimento.
Saluti

Assistenza ANSC
