### ISSUE TITLE
[R901] Errore tabella decodifica 9_dec_tipo_allegato

### ISSUE THREAD

**Issue by siscomanpr** [italia/ansc#420]
Il problema segnalato nella issue https://github.com/italia/ansc/issues/404 è stato risolto nella documentazione qui su github, ma il file csv scaricabile con il servizio R901 continua a scaricare la tabella 9 dei tipi allegati con la descrizione sbagliata.

**Comment by asqueglia** [comment]
Buongiorno stiamo provvedendo a risolvere il problema. Le facciamo sapere appena possibile

**Comment by asqueglia** [comment]
Abbiamo risolto il problema. Potete riprovare. Chiudiamo la issue in caso di ulteriori problematiche la preghiamo riaprirla
