### ISSUE TITLE
Dati obbligatori in Model Soggetto per officianteEvento

### ISSUE THREAD

**Issue by LucaBonini64** [italia/ansc#422]
Buongiorno,
nella precedente issue #313 avete indicato che era necessario indicare i dati dell'officiante anche per i matrimoni religiosi, adesso con la versione 1.15 per l'officiante è stato previsto l'utilizzo del ModelSoggetto che rende obbligatori la presenza dei campi relativi a data e luogo di nascita, cittadinanza e stato di residenza dell'officiante.
Vorrei segnalarvi che questi dati non sono previsti nell'atto di matrimonio (credo previsto dal concordato) che il parroco trasmette al comune per la trascrizione, inoltre il parroco che celebra l'atto può tranquillamente essere residente in altro comune ed essere totalmente sconosciuto all'ufficiale di stato civile, quindi può diventare difficile poter compilare questi campi.
Cordiali saluti
Luca Bonini APKAPPA

**Comment by asqueglia** [comment]
Buongiorno, salvo imprevisti entro venerdì rilasceremo una fix per rendere opzionali tutti i dati dell'anagrafica dell'officiante tranne nome e cognome obbligatori.
La scelta di aver reso l'officiante un ModelSoggetto è dipesa dalla necessità di rendere l'officiante un firmatario, dando quindi la possibilità di trasmettere lo specifico flagFirmatario a true.

Un saluto

**Comment by asqueglia** [comment]
Buongiorno con la versione 1.15.2 è stata corretta la segnalazione. Chiudiamo pertanto la issue; in caso di malfunzionamenti o dubbi preghiamo di aprire una issue dedicata.
