### ISSUE TITLE
[ws R009] Validazione Atto di Matrimonio - Intestatari: controllo conformità con dati ANPR

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/ansc#423]
ambiente PRE-PROD - comune di Faenza (idComune 3743)

endpoint: https://anscservicepre.anpr.interno.it/services/service/val/validazione/evento/1
idOperazioneComune: 2023002410
idOperazioneAnsc: 1671747

l'atto non viene validato a motivo di questi errori:
1. Attenzione! I dati del soggetto intestatario con idANPR=133940448 inseriti non sono conformi ai dati anagrafici registrati
2. Attenzione! I dati del soggetto intestatario con idANPR=133940449 inseriti non sono conformi ai dati anagrafici registrati

è la prima volta che vediamo un messaggio del genere e non capiamo cosa generi questa non conformità.

potete farci sapere con una certa urgenza?

grazie
Alessandro Monopoli ADS

**Comment by amusarra** [comment]
Salve @siscomanpr se ha notato, sulla issue è stata apposta ieri la label bug.
La segnalazione è in fase di risoluzione.

Cordiali Saluti.
Supporto ANSC.

**Comment by siscomanpr** [comment]
Non avevo notato, grazie.

**Comment by asqueglia** [comment]
Buongiorno con la versione 1.15.2 è stata corretta la segnalazione. Chiudiamo pertanto la issue; in caso di malfunzionamenti o dubbi preghiamo di aprire una issue dedicata.
