### ISSUE TITLE
[R009] Internal Error Validazione Nascita

### ISSUE THREAD

**Issue by Sem98** [italia/ansc#424]
Buonasera, ho provato ad inviare questa richiesta di test R009 Validazione per atto di nascita tuttavia il servizio mi risponde sempre errore 500.
Riccardo Papini
Municipia

{
	"testataRichiesta": {
		"versioneApplicativo": "1.0.0",
		"idOperazioneComune": "entedev",
		"idComune": 9493,
		"dataOraRichiesta": "2023-10-19",
		"nomeApplicativo": "SIDe",
		"fornitoreApplicativo": "SistemiInformativi"
	},
	"evento": {
		"datains": "2023-10-19",
		"operatoreNome": "MARIE",
		"idTipoEvento": "1",
		"composizioneCompleta": "Oggi sei del mese ottobre dell'anno duemilaventitre alle ore dodici e minuti dodici nella Casa Comunale.\r\nIo sottoscritto Ufficiale JENTE Ufficiale dello Stato Civile del Comune di Siena per delegazione avuta ho ricevuto dalla Direzione dell'Azienda Ospedaliera Universitaria Senese la dichiarazione di nascita n. ... pervenuta al protocollo di questo Comune in data 06/10/2023 prot. ......  relativa a:   PAPINI MIRCO\r\ndi cui mi ha trasmesso copia.\r\nAderendo a tale richiesta provvedo alla trascrizione per intero del documento come segue:\r\nATTO DI DICHIARAZIONE DI NASCITA\r\nL'anno duemilaventitre addi' sei del mese di ottobre alle ore dodici e minuti dodici\r\npresso l'Azienda Ospedaliera Universitaria Senese, sita nel Comune di Siena, innanzi al sottoscritto addetto alla Direzione Sanitaria, a cio' espressamente autorizzato dal Direttore Sanitario, con delega conservata in atti, e' comparso il Signor:\r\n\r\nnato a\r\nil\r\nresidente in\r\ncittadino\r\n-\r\nil quale nella sua veste di padre dichiara quanto segue:\r\n-\r\nIl giorno  del mese di  dell'anno\r\nalle ore  e minuti\r\n-\r\nin questo Centro di nascita e' nato un bambino di sesso MASCHILE\r\nal quale viene attribuito il nome di MIRCO\r\n-\r\nDetto bambino, la cui nascita e' comprovata dall'allegata attestazione  di nascita, e' nato dalla Signora:\r\n\r\nnata a\r\nil\r\ncittadina\r\nresidente in\r\n-\r\nconiugata con il Signor\r\nnato a\r\nil\r\ncittadino\r\nresidente a\r\n-\r\nIl bambino medesimo e' gemello con altro al quale si riferisce il precedente/seguente atto n.=== ed e' il PRIMO/SECONDO nato come mi ha attestato il dichiarante.\r\n-\r\nIl presente atto, dopo essere stato letto, viene insieme con me sottoscritto dal dichiarante ed inviato, per sua espressa volonta', al Comune di: SIENA.\r\nIl dichiarante f.to\r\nL'Addetto della Direzione Sanitaria firma autografa omessa (art.3 D.L.39/1993)\r\n(\r\n-\r\n-\r\n-\r\n-\r\n-\r\n-\r\n-\r\n-\r\n-\r\n-\r\n-\r\n-\r\n-\r\n-\r\n-\r\nDopo di che ho munito del mio visto ed inserito nel volume degli allegati a questo registro la copia dell'attestazione di nascita e del documento trascritto.\r\nL'UFFICIALE DELLO STATO CIVILE",
		"annoAtto": "2023",
		"tipoDichiarante": "1",
		"intestatari": [
			{
				"nomeStatoNascita": "ITALIA",
				"dataNascita": "2023-10-06",
				"idProvinciaNascita": "051",
				"idStatoNascita": "90",
				"cognome": "PAPINI",
				"nomeComuneNascita": "AREZZO",
				"sesso": "M",
				"nome": "MIRCO",
				"idComuneNascita": "427",
				"siglaProvinciaNascita": "AR"
			}
		],
		"allegati": [
			{
				"hashAllegato": "e07248a4f15f11b17cbd5eda859cdae5fb0f5f483e8d5275bb92276326455e98",
				"idStatoAllegato": "3",
				"id": "2227098",
				"idTipoAllegato": "1"
			}
		],
		"datiDichiarante": {
			"motivoImpedimentoScrittura": "",
			"comprensione": "0"
		},
		"dataDecorrenza": "2023-10-06",
		"stato": "CONFERMATO",
		"padre": {
			"siglaProvinciaResidenza": "AR",
			"nomeStatoNascita": "ITALIA",
			"dataNascita": "1997-01-01",
			"cognome": "PAPINI",
			"nazionalita": "ITALIANA",
			"codiceFiscale": "PPNRCR97A01I726S",
			"idStatoResidenza": "90",
			"idStatoNascita": "90",
			"nomeComuneResidenza": "SIENA",
			"flagComparente": false,
			"nomeComuneNascita": "SIENA",
			"flagFirmatario": true,
			"flagDichiarante": true,
			"id": "43500",
			"idComuneNascita": "9493",
			"idNazionalita": "11",
			"idProvinciaNascita": "052",
			"indirizzoResidenza": "",
			"idComuneResidenza": "427",
			"idsoggettoanpr": "265097",
			"idProvinciaResidenza": "051",
			"nome": "RICCARDO",
			"siglaProvinciaNascita": "SI",
			"nomeStatoResidenza": "ITALIA",
			"sesso": "M"
		},
		"descrizioneCasoUso": "Caso d'uso di servizio dichiarazioni nascita",
		"numeroatto": "22738",
		"ausilioInterprete": false,
		"operatore": "CRUMRA67S47Z127B",
		"dataformazione": "2023-10-06",
		"ora": "15",
		"minuto": "32",
		"operatoreCognome": "CURIE",
		"datiDiNascita": {
			"sceltaCognome": "3",
			"minutoNascita": "32",
			"natoVivoMaDeceduto": "NO",
			"luogoFiliazione": "",
			"oraNascita": "15",
			"natoMorto": "NO",
			"tipoAccertamento": "1",
			"precisazioneCognome": ""
		},
		"idComuneRegistrazione": "427",
		"madre": {
			"siglaProvinciaResidenza": "RM",
			"nomeStatoNascita": "ITALIA",
			"dataNascita": "2023-03-06",
			"cognome": "DE MEO",
			"nazionalita": "ITALIANA",
			"codiceFiscale": "DMEMTT73A41H501O",
			"idStatoResidenza": "90",
			"idStatoNascita": "90",
			"nomeComuneResidenza": "GROTTAFERRATA",
			"flagComparente": false,
			"nomeComuneNascita": "GROTTAFERRATA",
			"flagFirmatario": false,
			"flagDichiarante": false,
			"id": "45686",
			"idComuneNascita": "4559",
			"idNazionalita": "11",
			"idProvinciaNascita": "058",
			"indirizzoResidenza": "",
			"idComuneResidenza": "4559",
			"idsoggettoanpr": "266044",
			"idProvinciaResidenza": "058",
			"nome": "MATTEA",
			"siglaProvinciaNascita": "RM",
			"nomeStatoResidenza": "ITALIA",
			"sesso": "F"
		},
		"idUsecase": "11999999",
		"idProvinciaRegistrazione": "SIENA",
		"siglaProvinciaRegistrazione": "SI",
		"idtipocontenuto": "1",
		"redattoNellaCasaComunale": true,
		"ruoloOperatore": "2",
		"nomeComuneRegistrazione": "AREZZO"
	}
}

**Comment by amusarra** [comment]
Salve @Sem98 
Il payload contiene il valore errato per l'attributo `datains` a cui manca la parte oraria nel formato ISO (esempio: `"datains": "2023-10-19T15:38:03.002"`).

La invitiamo a riprovare e in caso di successo di chiudere la issue.

Cordiali Saluti.
Supporto ANSC.

**Comment by Sem98** [comment]
Salve abbiamo seguito le sue indicaioni e con il JSON presente ora risponde con errore 400 : 

{
	"testataRichiesta": {
		"versioneApplicativo": "1.0.0",
		"idOperazioneComune": "entedev",
		"idComune": 9493,
		"dataOraRichiesta": "2023-10-20",
		"nomeApplicativo": "SIDe",
		"fornitoreApplicativo": "SistemiInformativi"
	},
	"evento": {
		"datains": "2023-10-19T15:38:03.002",
		"operatoreNome": "MARIE",
		"idTipoEvento": "1",
		"dataultimoagg": "2023-10-19T15:38:03.002",
		"composizioneCompleta": "Oggi sei del mese ottobre dell'anno duemilaventitre alle ore dodici e minuti dodici nella Casa Comunale.\r\nIo sottoscritto Ufficiale JENTE Ufficiale dello Stato Civile del Comune di Siena per delegazione avuta ho ricevuto dalla Direzione dell'Azienda Ospedaliera Universitaria Senese la dichiarazione di nascita n. ... pervenuta al protocollo di questo Comune in data 06/10/2023 prot. ......  relativa a:   PAPINI MIRCO\r\ndi cui mi ha trasmesso copia.\r\nAderendo a tale richiesta provvedo alla trascrizione per intero del documento come segue:\r\nATTO DI DICHIARAZIONE DI NASCITA\r\nL'anno duemilaventitre addi' sei del mese di ottobre alle ore dodici e minuti dodici\r\npresso l'Azienda Ospedaliera Universitaria Senese, sita nel Comune di Siena, innanzi al sottoscritto addetto alla Direzione Sanitaria, a cio' espressamente autorizzato dal Direttore Sanitario, con delega conservata in atti, e' comparso il Signor:\r\n\r\nnato a\r\nil\r\nresidente in\r\ncittadino\r\n-\r\nil quale nella sua veste di padre dichiara quanto segue:\r\n-\r\nIl giorno  del mese di  dell'anno\r\nalle ore  e minuti\r\n-\r\nin questo Centro di nascita e' nato un bambino di sesso MASCHILE\r\nal quale viene attribuito il nome di MIRCO\r\n-\r\nDetto bambino, la cui nascita e' comprovata dall'allegata attestazione  di nascita, e' nato dalla Signora:\r\n\r\nnata a\r\nil\r\ncittadina\r\nresidente in\r\n-\r\nconiugata con il Signor\r\nnato a\r\nil\r\ncittadino\r\nresidente a\r\n-\r\nIl bambino medesimo e' gemello con altro al quale si riferisce il precedente/seguente atto n.=== ed e' il PRIMO/SECONDO nato come mi ha attestato il dichiarante.\r\n-\r\nIl presente atto, dopo essere stato letto, viene insieme con me sottoscritto dal dichiarante ed inviato, per sua espressa volonta', al Comune di: SIENA.\r\nIl dichiarante f.to\r\nL'Addetto della Direzione Sanitaria firma autografa omessa (art.3 D.L.39/1993)\r\n(\r\n-\r\n-\r\n-\r\n-\r\n-\r\n-\r\n-\r\n-\r\n-\r\n-\r\n-\r\n-\r\n-\r\n-\r\n-\r\nDopo di che ho munito del mio visto ed inserito nel volume degli allegati a questo registro la copia dell'attestazione di nascita e del documento trascritto.\r\nL'UFFICIALE DELLO STATO CIVILE",
		"annoAtto": "2023",
		"tipoDichiarante": "1",
		"intestatari": [
			{
				"nomeStatoNascita": "ITALIA",
				"dataNascita": "2023-10-06",
				"idProvinciaNascita": "051",
				"idStatoNascita": "90",
				"cognome": "PAPINI",
				"nomeComuneNascita": "AREZZO",
				"documentoRiconoscimento": {},
				"sesso": "M",
				"nome": "MIRCO",
				"idComuneNascita": "427",
				"siglaProvinciaNascita": "AR"
			}
		],
		"allegati": [
			{
				"hashAllegato": "e07248a4f15f11b17cbd5eda859cdae5fb0f5f483e8d5275bb92276326455e98",
				"idStatoAllegato": "3",
				"id": "2227098",
				"idTipoAllegato": "1"
			}
		],
		"datiDichiarante": {
			"motivoImpedimentoScrittura": "",
			"comprensione": "0"
		},
		"dataDecorrenza": "2023-10-06",
		"stato": "CONFERMATO",
		"padre": {
			"siglaProvinciaResidenza": "AR",
			"nomeStatoNascita": "ITALIA",
			"dataNascita": "1997-01-01",
			"cognome": "PAPINI",
			"nazionalita": "ITALIANA",
			"codiceFiscale": "PPNRCR97A01I726S",
			"idStatoResidenza": "90",
			"idStatoNascita": "90",
			"nomeComuneResidenza": "SIENA",
			"flagComparente": false,
			"nomeComuneNascita": "SIENA",
			"flagFirmatario": true,
			"flagDichiarante": true,
			"id": "43500",
			"idComuneNascita": "9493",
			"idNazionalita": "11",
			"idProvinciaNascita": "052",
			"indirizzoResidenza": "",
			"idComuneResidenza": "427",
			"idsoggettoanpr": "265097",
			"idProvinciaResidenza": "051",
			"documentoRiconoscimento": {},
			"nome": "RICCARDO",
			"siglaProvinciaNascita": "SI",
			"nomeStatoResidenza": "ITALIA",
			"sesso": "M"
		},
		"descrizioneCasoUso": "Caso d'uso di servizio dichiarazioni nascita",
		"numeroatto": "22738",
		"ausilioInterprete": "false",
		"operatore": "CRUMRA67S47Z127B",
		"dataformazione": "2023-10-06",
		"ora": "15",
		"minuto": "32",
		"operatoreCognome": "CURIE",
		"datiDiNascita": {
			"sceltaCognome": "3",
			"minutoNascita": "32",
			"natoVivoMaDeceduto": "NO",
			"luogoFiliazione": "",
			"oraNascita": "15",
			"natoMorto": "NO",
			"tipoAccertamento": "1",
			"precisazioneCognome": ""
		},
		"idComuneRegistrazione": "427",
		"madre": {
			"siglaProvinciaResidenza": "RM",
			"nomeStatoNascita": "ITALIA",
			"dataNascita": "2023-03-06",
			"cognome": "DE MEO",
			"nazionalita": "ITALIANA",
			"codiceFiscale": "DMEMTT73A41H501O",
			"idStatoResidenza": "90",
			"idStatoNascita": "90",
			"nomeComuneResidenza": "GROTTAFERRATA",
			"flagComparente": false,
			"nomeComuneNascita": "GROTTAFERRATA",
			"flagFirmatario": false,
			"flagDichiarante": false,
			"id": "45686",
			"idComuneNascita": "4559",
			"idNazionalita": "11",
			"idProvinciaNascita": "058",
			"indirizzoResidenza": "",
			"idComuneResidenza": "4559",
			"idsoggettoanpr": "266044",
			"idProvinciaResidenza": "058",
			"documentoRiconoscimento": {},
			"nome": "MATTEA",
			"siglaProvinciaNascita": "RM",
			"nomeStatoResidenza": "ITALIA",
			"sesso": "F"
		},
		"idUsecase": "11999999",
		"idProvinciaRegistrazione": "051",
		"siglaProvinciaRegistrazione": "AR",
		"idtipocontenuto": "1",
		"redattoNellaCasaComunale": true,
		"ruoloOperatore": "2",
		"nomeComuneRegistrazione": "AREZZO"
	}
}

**Comment by amusarra** [comment]
Salve @Sem98 
Potrebbe indicare l'idOperazione del messaggio di risposta?
Ha restituito HTTP/400 senza alcun descrizione dell'errore?

Cordiali Saluti.
Supporto ANSC.

**Comment by Sem98** [comment]
Salve, segue il JSON di risposta

{
	"testataRisposta": {
		"idComune": 9493,
		"idOperazioneComune": "entedev",
		"idOperazione": "1676104",
		"idEsito": 1
	},
	"errors": [
		{
			"code": "403003",
			"severity": "E",
			"text": "Provincia non corrispondente"
		},
		{
			"code": "403003",
			"severity": "E",
			"text": "Comune non corrispondente"
		},
		{
			"code": "400001",
			"severity": "E",
			"text": "Hash allegato diverso da quello a sistema per l'id allegato fornito: 2227098"
		}
	]
}

**Comment by amusarra** [comment]
Salve @Sem98 
L'errore è in genere dovuto al fatto che il comune di registrazione e la provincia di registrazione non sono coerenti.

Cordiali Saluti.
Supporto ANSC.
