### ISSUE TITLE
[R009] - Internal error in validazione evento di morte

### ISSUE THREAD

**Issue by LucaBonini64** [italia/ansc#425]
Buongiorno,
stiamo provando a fare l'invio di un evento di morte use case 2102 ma ci viene risposto internal error senza idComunicazione.
Le variazioni che abbiamo fatto rispetto ad una precedente trasmissione positiva sono:
- dataOraRichiesta in testata trasformata in date-time
- nell'intestatario aggiunto il campo idsoggettoanpr riferito a un cittadino in ambiente di test di un altro comune
- nelle annotazioni contestuali aggiunto il campo flagAnnotazioneNonCertificabile
a meno che non siano presenti altri errori che non riesco a vedere, 
questo il payload dell'evento:
{
	"testataRichiesta": {
		"idComune": 6498,
		"idOperazioneComune": "LB20231020094212",
		"dataOraRichiesta": "2023-10-20T09:42:12.011",
		"nomeApplicativo": "StatoCivile.NET",
		"versioneApplicativo": "TestAppoggio",
		"fornitoreApplicativo": "APKAPPA s.r.l."
	},
		"evento": {
		"idTipoEvento": "2",
		"idtipocontenuto": "1",
		"idVersion": "100003",
		"idUsecase": "2102",
		"descrizioneCasoUso": "Decesso in ospedale o casa di cura",
		"propostaAnnotazione": true,
		"stato": "CONFERMATO",
		"flagsecretato": false,
		"dataformazione": "2023-10-19",
		"annoAtto": "2023",
		"meseAtto": "10",
		"giornoAtto": "19",
		"ora": "15",
		"minuto": "10",
		"idComuneRegistrazione": "6498",
		"nomeComuneRegistrazione": "NOVI LIGURE",
		"idProvinciaRegistrazione": "6",
		"siglaProvinciaRegistrazione": "AL",
		"operatore": "BNNLCU64B18L219Q",
		"ruoloOperatore": "2",
		"operatoreNome": "LUCA",
		"operatoreCognome": "BONINI",
		"redattoNellaCasaComunale": true,
		"composizioneCompleta": "L'anno duemilaventitre addì diciannove del mese di ottobre alle ore quindici e minuti diciassette nella Casa Comunale. Io, Bonini Luca, istruttore amministrativo ed, Ufficiale dello Stato Civile del Comune di NOVI LIGURE, per delega avuta avendo ricevuto dal Funzionario incaricato dal Direttore  Sanitario dell'A.S.L. AL un avviso di morte con la data 19 ottobre 2023 che munito del mio visto, inserisco nel volume degli allegati a questo registro, do atto che: Il giorno diciotto del mese di ottobre dell'anno duemilaventitre alle ore venti e minuti trenta nell'Ospedale San Giacomo Via E. Raggio, 12 è morta BARDELLI ORIETTA cittadina ITALIANA residente in PISA (PI) nata in PISA (PI) li quattro febbraio millenovecentoventuno e che era coniugata con SABBATINI GAVINO. L'UFFICIALE DELLO STATO CIVILE: Luca Bonini",
		"ausilioInterprete": false,
		"numeroatto": "20232220000000000058",
		"coniuge": {
			"cognome": "SABBATINI",
			"flagComparente": false,
			"flagDichiarante": false,
			"flagFirmatario": false,
			"nome": "GAVINO",
		},
		"datiDiMorte": {
			"dataMorte": "2023-10-18",
			"luogoMorte": "l'Ospedale San Giacomo Via E. Raggio, 12",
			"minutoMorte": "30",
			"oraMorte": "20",
			"nomeComuneMorte": "NOVI LIGURE",
			"idComuneMorte": "6498",
			"siglaProvinciaMorte": "AL",
			"idProvinciaMorte": "6",
			"nomeStatoMorte": "ITALIA",
			"idStatoMorte": "90",
		},
		"datiEventoMorte": {
			"dataTrasmissione": "2023-10-19",
			"descrizioneTrasmissione": "Funzionario incaricato dal Direttore  Sanitario dell'A.S.L. AL",
			"tipoTrasmissione": "1",
		},
		"intestatari": [
			{
			"idsoggettoanpr": "8217106",
			"codiceFiscale": "BRDRTT21B44G702R",
			"cognome": "BARDELLI",
			"dataNascita": "1921-02-04",
			"nome": "ORIETTA",
			"idNazionalita": "90",
			"nazionalita": "ITALIANA",
			"idStatoNascita": "90",
			"nomeStatoNascita": "ITALIA",
			"idProvinciaNascita": "50",
			"siglaProvinciaNascita": "PI",
			"nomeComuneNascita": "PISA",
			"idComuneNascita": "7308",
			"idStatoResidenza": "90",
			"nomeStatoResidenza": "ITALIA",
			"idProvinciaResidenza": "50",
			"siglaProvinciaResidenza": "PI",
			"idComuneResidenza": "7308",
			"nomeComuneResidenza": "PISA",
			"sesso": "F",
			"descrizionestatocivile": "coniugata",
			"idstatocivile": "2",
			"flagComparente": false,
			"flagDichiarante": false,
			"flagFirmatario": false,
			}
		],
		"datiAnnotazione": [
			{
			"testoAnnotazione": "L'atto di nascita del di contro è iscritto nei registri di Stato Civile del Comune di PISA (PI) al N. 183 p. I s. A uff.  anno 1921 NOVI LIGURE li 19/10/2023 L'UFFICIALE DELLO STATO CIVILE Luca Bonini",
			"tipoAnnotazione": "1",
			"flagAnnotazioneNonCertificabile": true,
			}
		],
		"allegati": [
			{
			"id": "2228493",
			"idTipoAllegato": "35",
			"hashAllegato": "KR/Xn3FWuWbuD5fjNvSy8fulxp5lduudZxX2vSWhjio="
			}
		]
	}
}

Grazie

**Comment by amusarra** [comment]
Buongiorno @LucaBonini64 
Il problema è l'attributo `flagsecretato`  che da documentazione OpenAPI https://github.com/italia/ansc/blob/4950d39a417ba2794b4f01eb76994d6871a69a29/docs/openapi/model_evento.yaml#L45 prevede un tipo stringa i cui valori possono essere `0` o `1`.

Le chiediamo di rifare il test dopo aver effettuato la correzione al payload.
In caso di successo, le chiediamo di chiudere la issue.

Cordiali Saluti.
Supporto ANSC.

**Comment by LucaBonini64** [comment]
Buongiorno, vi ringrazio adesso il caricamento funziona
