### ISSUE TITLE
Errore - i dati del soggetto intestatario non sono conformi ai dati anagrafici registrati

### ISSUE THREAD

**Issue by LucaBonini64** [italia/ansc#426]
Buongiorno,
facendo l'invio di un evento di morte di viene restituito il seguente errore:
{"idComune":6498,"idOperazioneComune":"LB20231020094212","idOperazione":"1676013","idEsito":1},"errors":[{"code":"400003","severity":"E","text":"Attenzione! I dati del soggetto intestatario con idANPR=8217106 inseriti non sono conformi ai dati anagrafici registrati"}]}

Facendo un interrogazione con il servizio R005 per codice ANPR ("idOperazione": "1675908") noto alcune differenze, non so se possono essere la causa dell'errore:
"dataNascita": "1921-02-04T01:00:00+01:00",
ovviamente se provo ad inserire la data di nascita in questo formato nel modelSoggetto restituisce errore.
"idNazionalita" e "nazionalita": null,
dati che sono obbligatori per l'intestatario dell'atto e che quindi inserisco nell'evento.

Per quanto riguarda la cittadinanza non capisco inoltre perché venga restituito un valore null nel servizio R005 dato che se interrogo la medesima persona con un servizio 3002 di ANPR ottengo:
```xml
...<cittadinanza><descrizioneStato>ITALIA</descrizioneStato><codiceStato>100</codiceStato></cittadinanza>...
```

Potete verificare? 
Grazie.

**Comment by amusarra** [comment]
Salve @LucaBonini64 è lo stesso problema segnalato con la issue #423 che abbiamo preso in carico ed è in fase di risoluzione.

Cordiali Saluti.
Supporto ANSC.

**Comment by LucaBonini64** [comment]
Buongiorno,
confermo che con la versione 1.15.2 il problema si è risolto.
Grazie.
