### ISSUE TITLE
Segnalazione tipo di dati in file yaml

### ISSUE THREAD

**Issue by siscomanpr** [italia/ansc#43]
Nei vari file yaml i tipi di dato numerici sono indicati sempre come type: number, quando viene auto-generato il codice questi campi vengono automaticamente importati come tipo di dati double, questo porta il problema che quando viene serializzato l'oggetto in JSON per effettuare la chiamata il dato viene scritto con le cifre decimali (es: 1.0).
Premesso che siamo comunque riusciti a impostare delle regole di serializzazione personalizzate per questa casistica, ma l'ideale sarebbe che lo yaml venga impostato in modo che sia automaticamente convertito come tipo int/integer, indicandolo come type: integer così come indicato sulla documentazione ufficiale di Swagger/OpenAPI: https://swagger.io/docs/specification/data-models/data-types/#numbers

**Comment by mttfranci** [comment]
Salve, abbiamo preso in carico la segnalazione, e stiamo valutando di modificare il tipo dato come suggerito in uno dei prossimi rilasci.

Saluti

Assistenza ANSC

**Comment by mttfranci** [comment]
Salve, la segnalazione dovrebbe essere stata rilsolta con il rilascio della minor version 1.6 #58

**Comment by asqueglia** [comment]
Buongiorno, con il rilascio odierno della versione 1.6.0 è stata risolta la problematica indicata.
