### ISSUE TITLE
[R009] Chiarimento dati mancanti UseCase 342000 - Sep_Div_002

### ISSUE THREAD

**Issue by MarcoSalaPad** [italia/ansc#430]
Buongiorno,
in questo caso d'uso ci siamo accorti di una modifica al DataModel che non abbiamo visto nei vari changelog, ma non ci risulta corretta come dati obbligatori richiesti. A differenza del vecchio DataModel per questo caso d'uso è stata aggiunta tutta la sezione relativa al legame tra accordo di scioglimento e conferma accordo di scioglimento.

La response è la seguente:

RESPONSE:
{
    "testataRisposta": {
        "idComune": 5000,
        "idOperazioneComune": "4328",
        "idOperazione": "1681646",
        "idEsito": 1
    },
    "errors": [{
            "code": "400003",
            "severity": "E",
            "text": "Il campo evento.separazione.accordoSeparazione.idProvinciaRegistrazione nella sezione Accordo Separazione è obbligatorio"
        }, {
            "code": "400003",
            "severity": "E",
            "text": "Il campo evento.separazione.accordoSeparazione.siglaProvinciaRegistrazione nella sezione Accordo Separazione è obbligatorio"
        }, {
            "code": "400003",
            "severity": "E",
            "text": "Il campo evento.separazione.accordoSeparazione.idComuneRegistrazione nella sezione Accordo Separazione è obbligatorio"
        }, {
            "code": "400003",
            "severity": "E",
            "text": "Il campo evento.separazione.accordoSeparazione.nomeComuneRegistrazione nella sezione Accordo Separazione è obbligatorio"
        }, {
            "code": "400003",
            "severity": "E",
            "text": "Il campo evento.separazione.accordoSeparazione.idtipocontenuto nella sezione Accordo Separazione è obbligatorio"
        }, {
            "code": "400003",
            "severity": "E",
            "text": "Il campo evento.separazione.accordoSeparazione.numeroatto nella sezione Accordo Separazione è obbligatorio"
        }, {
            "code": "400003",
            "severity": "E",
            "text": "Il campo evento.separazione.accordoSeparazione.annoAtto nella sezione Accordo Separazione è obbligatorio"
        }, {
            "code": "400003",
            "severity": "E",
            "text": "Il campo evento.separazione.accordoSeparazione.dataformazione nella sezione Accordo Separazione è obbligatorio"
        }, {
            "code": "400003",
            "severity": "E",
            "text": "Il campo evento.separazione.accordoSeparazione.tipologia nella sezione Accordo Separazione è obbligatorio"
        }
    ]
}

Se sto facendo la tipologia di caso d'uso per l'Accordo di scioglimento, come mai è presente e obbligatoria questa sezione relativa ai dati dell'accordo (in questo caso d'uso non confermo un precedente accordo, perchè lo sto facendo ora), che in realtà è richiesta (correttamente) nel caso d'uso 343000 - Sep_Div_003.

Non è che per caso questa sezione è finita erroneamente in questo caso d'uso e doveva essere presente solo nel Usecase 343000?

Grazie
Marco

**Comment by biadanpad** [comment]
Buongiorno, 
il mapping del caso d'uso, però prevede che vengano immessi i dati di un atto e non di un provvedimento del tribunale o altro.

Di seguito riporto lo stralcio di un atto realmente formato:
 - di essere legalmente separati a seguito di **omologa del Tribunale di XXXXXX n. XXX/XXXX in data XX/XX/XXXX** e di trovarsi in uno dei casi di cui all'articolo 3, primo comma, numero 2), letter b), legge 10 dicembre 1970, n. 898

**Comment by asqueglia** [comment]
Quindi se abbiamo capito bene è necessario inserire una ulteriore tipologia di accordo 'omologa tribunale'/Altra autorità giudiziale' consentendo di inserire in tal caso i dati  dell'ente (es. il tribunale come da lei descritto). Procediamo con l'aggiunta di questa fattispecie se è d'accordo

**Comment by biadanpad** [comment]
Per me può andare bene, ma a questo punto tutti i campi aggiunti delle sezione "Accordo Separazione" dovranno diventare opzionali e non più obbligatori (così come i campi della nuova eventuale sezione).

Facendo riferimento al mapping attuale, potrebbe indicarmi che genere di atto dovrebbe essere specificato per la sezione "Accordo Separazione" (indicandomi ad esempio un possibile id use case)?

**Comment by asqueglia** [comment]
Abbiamo ricevuto una conferma anche da ANUSCA in merito a quanto segnalato; procederemo quanto prima a fornire la possibilità di acquisire un eventuale autorità giudiziaria (tribunale o altro) che abbia attestato il provvedimento di separazione. Faremo sapere.

**Comment by asqueglia** [comment]
Buon pomeriggio, abbiamo corretto la segnalazione con la versione 1.18. Pertanto chiudiamo la issue; in caso di anomalie o ulteriori approfondimenti la preghiamo di aprirne una altra dedicata.
