### ISSUE TITLE
[R005] Problemi consultazione annotazioni automatiche

### ISSUE THREAD

**Issue by siscomanpr** [italia/ansc#431]
Buongiorno,
durante la fase di test tra 2 comuni (in questo caso SERRAVALLE SESIA e  VALEGGIO SUL MINCIO), per Serravalle si sta ripresentando lo stesso problema già segnalato e poi risolto della issue https://github.com/italia/ansc/issues/371
La consultazione dell'annotazione con il servizio R005, passando come parametro di ricerca solo l'idANSC, non restituisce alcun risultato.
Allego i json di richiesta e risposta:
[16852_Request.log](https://github.com/italia/ansc/files/13120336/16852_Request.log)
[16852_Response.log](https://github.com/italia/ansc/files/13120337/16852_Response.log)
idOperazione : 1684592

Se può servire sembra che la consultazione di annotazioni generate da eventi secondari fatti da SERRAVALLE per atti primari dello stesso comune si riescano a consultare. Mentre tra 2 comuni diversi no.

Siscom SPA per Serravalle Sesia

**Comment by amusarra** [comment]
Salve @siscomanpr 
Abbiamo preso in carico la segnalazione.

Cordiali Saluti.
Supporto ANSC.

**Comment by asqueglia** [comment]
Buongiorno, con il rilascio della versione 1.21.0 la segnalazione dovrebbe essere risolta. Chiudiamo pertanto la issue. In caso di ulteriori segnalazioni si prega di aprire una issue dedicata.
