### ISSUE TITLE
Mancata notifica presa visione evento digitale

### ISSUE THREAD

**Issue by LucaBonini64** [italia/ansc#432]
Buongiorno,
in riferimento alla issue #415 vi segnalo che anche noi non riusciamo a ricevere notifiche ANSC che invece dovrebbero pervenire.

Vi riporto le operazioni eseguite:
1) Comune di NOVI LIGURE redige l'atto di morte di un soggetto nato e residente a PISA, nella sezione intestatari viene correttamente inserito l'idsoggettoanpr (8217106),
2) L'atto viene correttamente inserito ("idOperazione": "1683493", "idEvento": "1212093") e successivamente firmato.
3) Sulla WebApp del comune di NOVI LIGURE viene creata la comunicazione per l'invio via PEC al comune di nascita dell'annotazione di morte (2023-1212094-00000-006114)
4) Sulla WebApp del comune di PISA non compare nessuna comunicazione, abbiamo anche provato a confermare la presa visione dell'annotazione di cui al punto 3 (che non dovrebbe essere vincolante per la trasmissione della trascrizione a Pisa) ma continua a non essere presente nessuna notifica.

Anche stamattina abbiamo provato a richiedere con il servizio R008 le notifiche presenti per PISA ma senza risultato (idOperazione: 1685323) e ovviamente non sono presenti neanche notifiche per ANPR (idOperazione: 1685559) ma in questo caso è normale non avendo potuto confermare la notifica di trascrizione. Potete verificare?

Grazie
Luca Bonini APKAPPA

**Comment by asqueglia** [comment]
Buongiorno, Pisa non è tra i comuni censiti come aderenti ad ANSC, quindi ecco perchè la notifica non gli è arrivata.  E' corretto che sia arrivata la sola notifica di proposta di annotazione al comune di formazione dell'atto di morte 'Novi Ligure' che deve provvedere agli adempimenti descritti al punto 3. Pisa essendo non censito come comune aderente, è trattato come un comune ancora analogico per cui Novi Ligure deve procedere alla richiesta trascrizione dell'atto di morte, con le attuali modalità operative; Pisa provvederà alla registrazione anagrafica con le attuali modalità operative. Questo flusso è descritto nella guida per la gestione dell'adesione progressiva pubblicata sul sito pubblico ANPR
https://www.anagrafenazionale.interno.it/area-tecnica/documentazione-tecnica/

**Comment by asqueglia** [comment]
@LucaBonini64 abbiamo censito Pisa come comune in ansc. Potete procedere al test completo per verificare il flusso di notifiche. Chiudiamo pertanto la issue; in caso di malfunzionamento la preghiamo di riaprirla.
