### ISSUE TITLE
Firma Officiante Matrimonio per Unioni Civili

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#433]
Buongiorno, 
nei casi d'uso relativi alle unioni civili non ritroviamo lo stesso schema introdotto per i matrimoni. L'officiante, quindi, non può firmare l'atto

**Comment by asqueglia** [comment]
Buonasera con il rilascio della versione 1.16.0 la segnalazione dovrebbe essere corretta. 
Chiudiamo pertanto la issue; in caso di ulteriori richieste preghiamo di aprirne una altra dedicata o riaprire la presente.
Grazie
