### ISSUE TITLE
[R008] Notifiche a seguito di divorzio

### ISSUE THREAD

**Issue by siscomanpr** [italia/ansc#434]
Buongiorno,
abbiamo registrato un evento di divorzio con il caso d'uso 345000 - Trascrizione della convenzione di negoziazione assistita ... relativo ad un atto di matrimonio analogico.
A fronte di questo evento sono state generate solo le 2 annotazioni automatiche per gli atti di nascita (analogici) dei 2 coniugi, ma non quella per l'atto di matrimonio (formula 175-sexies). Anche da webapp non vediamo questa notifica di annotazione. 
Vorremmo capire se abbiamo sbagliato qualcosa nella compilazione dell'evento o se è un problema del sistema.
L'atto di divorzio in oggetto ha come idansc 2023-953690-240-002137 (SERRAVALLE SESIA)
Grazie.

**Comment by asqueglia** [comment]
Verifichiamo e le facciamo sapere
