### ISSUE TITLE
tabella 100 - data fine validità

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#437]
Buongiorno,
la data della fine validità delle ultime due versioni sono entrambe 31/12/9999. E' corretto?
![image](https://github.com/italia/ansc/assets/127182190/b4d39a10-df1d-492b-bff5-b35527f097ea)

**Comment by asqueglia** [comment]
Buonasera @annamaraspin,  stiamo rivedendo le date di fine validità delle versioni. 
Comunque la 1.14 sarà disponibile per tre mesi, a partire dalla data di rilascio (i nizio validità) per gestione della retro compatibilità, per consentirvi l'integrazione nei tempi dovuti. 
L'ultima invece 1.16 è quella attualmente senza una data di fine validità

**Comment by asqueglia** [comment]
Buonasera abbiamo corretto la tabella con le giuste date di validità. Pertanto chiudiamo la issue; in caso di ulteriori segnalazioni preghiamo di aprirne una altra dedicata.
