### ISSUE TITLE
[ANPR - ws 5008] CodDestinatario 'ANPR05' - Rettifica dati dell'Atto di Nascita (tipoMutazione '15')

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/ansc#438]
ambiente PROD - comune di Valeggio sul Mincio (023089)

idOperazioneComune: 2023004117
idOperazioneANPR: 1494578717

attivando il codDestinatario ANPR05 (per adeguamento con ANSC) la mutazione di atto di nascita restituisce il seguente errore:

```
      <errore>
        <codiceErroreAnomalia>EN409</codiceErroreAnomalia>
        <tipoErroreAnomalia>E</tipoErroreAnomalia>
        <testoErroreAnomalia>Per tipo mutazione = 15 inserire l'oggetto Atto di Nascita </testoErroreAnomalia>
      </errore>
      <errore>
        <codiceErroreAnomalia>EN527</codiceErroreAnomalia>
        <tipoErroreAnomalia>E</tipoErroreAnomalia>
        <testoErroreAnomalia>Informazioni sull'operazione da fornire in caso di assistenza : data 2023-10-30 10:21:47 , idOperazioneANPR 1494578717</testoErroreAnomalia>
      </errore>
```

verificando la request, l'oggetto "Atto di Nascita" è presente, ma - come previsto dagli schemi - è contenuto all'interno del tag <attoNascitaANPR>".

```
  <attoNascitaANPR>
    <atto>
      <comuneRegistrazione>
        <nomeComune>VALEGGIO SUL MINCIO</nomeComune>
        <codiceIstat>023089</codiceIstat>
        <siglaProvinciaIstat>VR</siglaProvinciaIstat>
      </comuneRegistrazione>
      <anno>2023</anno>
      <parte>2</parte>
      <serie>B</serie>
      <numeroAtto>76</numeroAtto>
    </atto>
  </attoNascitaANPR>
```

potete verificare se è un problema della request o del sistema ANPR che magari si aspetta ancora il vecchio oggetto?

per risolvere nell'immediato abbiamo re-inoltrato la comunicazione con codDestinatario 'ANPR02', ma da domani potrebbe presentarsi comunque la necessità di una rettifica di questo tipo su dati di atto analogici.

grazie

Alessandro Monopoli ADS

**Comment by asqueglia** [comment]
Buongiorno verifichiamo e le facciamo sapere.

**Comment by mttfranci** [comment]
@AMonopoliADS  buongiorno, abbiamo verificato che per quanto riguarda la richiesta 1498946672 non sembra essere pervenuto nella richiesta l'elemento `attoNascitaANPR`.

Invece ad esempio per la richiesta 1496819677 dello stesso comune l'elemento è presente.

Saluti

**Comment by AMonopoliADS** [comment]
ok. grazie Matteo.

abbiamo fatto nuovi test e sembra che la mutazione di atto funzioni correttamente.

Alessandro
