### ISSUE TITLE
[Casi d'uso Registro Morte] Obbligatorietà dati del coniuge.

### ISSUE THREAD

**Issue by gcuci** [italia/ansc#44]
buongiorno,

per i casi d'uso del Registro di Morte, per quelli per i quali ne è prevista la gestione, se il deceduto era 'coniugato', o 'unito civilmente', risultano obbligatori i seguenti campi del ModelSoggetto coniuge: nome, sesso, dataNascita, idStatoNascita, nomeStatoNascita, idNazionalita, nazionalita. E nel caso di 'unito civilmente' anche idStatoResidenza e nomeStatoResidenza.

Sono controlli più stringenti di quanto riportato nell'art.73 del DPR 396/2000 di riferimento (ne riporto la parte relativa: "...L'atto di morte deve enunciare il luogo, il giorno e l'ora della morte, il nome e il cognome, il luogo e la data di nascita, la residenza e la cittadinanza del defunto, il nome e il cognome del coniuge, se il defunto era coniugato, vedovo o divorziato; ...")
L'obbligatorietà è quindi limitata ai soli nome e cognome.

E' possibile rivedere i controlli dei servizi, rendendo obbligatori i soli campi nome e cognome? 

Segnalo anche, che, viceversa, non c'è alcun controllo di obbligatorietà sul cognome. Questo è probabile che dipenda dall'indicazione che c'è sugli excel di mapping, in cui, in tutti i ModelSoggetto (compreso l'intestatario), è indicato il campo cognome come non obbligatorio. Probabilmente è un refuso negli excel, ma sembra aver comportato la mancanza del controllo nei servizi.

In attesa di un riscontro,

cordiali saluti.

**Comment by mttfranci** [comment]
Salve,
Grazie della segnalazione, al fine di poter verificare più velocemente, potreste indicarci un caso specifico?
Magari per un caso d'uso e se la avete un id operazione per la quale il comportamento non è stato quello atteso?
Grazie in anticipo.

Assistenza ANSC

**Comment by gcuci** [comment]
Un caso d'uso di esempio che abbiamo testato è "idUsecase": "2101" (Morte_001), con stato civile dell'intestatario "descrizionestatocivile": "Unito civilmente".

La richiesta non aveva i dati del coniuge, ed il servizio ha risposto con un elenco di errori 400003, da cui si evidenziano le obbligatorietà indicate, e la mancanza di controllo sul 'cognome'.

L'ambiente di test è preproduzione, la data è oggi, e "idOperazione": "1573070".

**Comment by mttfranci** [comment]
Salve.

Riguardo la mancata obbligatorietà del cognome, stiamo valutando di procedere come in ANPR, ovvero gestendo come obbligatorio solo uno tra il nome e il cognome (per gestire i soggetti senza nome o cognome).

Riguardo l'obbligatorietà degli altri campi, stiamo verificando il rilassamento di tali vincoli.
Ricordiamo però, come più volte dette, che è opportuno inviare tutti i dati identificativi del soggetto laddove disponibili, anche se non necessari alle formule.
Questo al fine di poter gestire l'aggancio dei soggetti e gli automatismi del sistema.
Saluti

Assistenza ANSC

**Comment by asqueglia** [comment]
Buonasera, è stata rilasciata la versione 1.8.1 che dovrebbe risolvere la presente segnalazione. E' possibile riprovare.
