### ISSUE TITLE
Annotazione in formato PDF

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#441]
Buongiorno, 
quale servizio posso richiamare per ottenere le annotazioni in formato PDF (in modo da poterle per esempio stampare)?
In sostanza vorrei poter scaricare il PDF che genera la WebApp cliccando su "Visualizza Pdf":
![image](https://github.com/italia/ansc/assets/131870281/0c71212d-d8d0-4cbd-aec2-3d33a573cc15)

Di seguito il file PDF in questione:
[206a338c-4d7d-47ca-85f0-d13911b9eb11.pdf](https://github.com/italia/ansc/files/13214466/206a338c-4d7d-47ca-85f0-d13911b9eb11.pdf)

**Comment by asqueglia** [comment]
Buongiorno il servizio da utilizzare per ricevere le informazioni richieste sulla annotazione è l'R005 invocato trasmettendo in input l'idAnsc dell'evento annotazione.  Viene restituito il json dell'annotazione e non il pdf, in modo da poter gestire la stampa come più opportuno sui vostri gestionali

**Comment by asqueglia** [comment]
Buongiorno non avendo ricevuto feddback in merito, provvediamo a chiudere la issue. In caso di ulteriori segnalazioni la preghiamo di aprire una altra issue dedicata
