### ISSUE TITLE
[ws R002] Certificazione - Errore: msg. "Nessun dato associato all'utente"

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/ansc#442]
ambiente PROD - comune di Valeggio sul Mincio (idComune 10420)

endpoint: https://anscservice.anpr.interno.it/services/service/certificazione/certificato/1

tutte le richieste di certificazione restituiscono l'errore "Nessun dato associato all'utente".

uno degli ultimi tentativi:
idOperazioneComune: 2023000017
idOperazioneAnsc: 11315

attendiamo riscontro urgente.
grazie
Alessandro Monopoli ADS

**Comment by mttfranci** [comment]
Buongiorno, stiamo verificando, ma intanto potreste controllare se state usando un OTP valido e non scaduto?
Per intenderci quello che gli Ufficiali di Stato Civile possono ottenere dall'url : 
https://anscweb.anpr.interno.it/ansc/login/otp
Grazie in anticipo.

Assistenza ANSC

**Comment by AMonopoliADS** [comment]
ciao Matteo.

ti confermo che gli otp che sono stati utilizzati sono stati recuperati tramite l'url di produzione, con autenticazione spid dell'operatore.

**Comment by siscomanpr** [comment]
Mi inserisco nella discussione, anche noi abbiamo rilevato questo errore poco fa. 
Sembra che la durata dell' OTP sia di pochi minuti invece che 4 ore come si era detto. Infatti dopo aver inserito un nuovo OTP siamo riusciti a validare un atto.

Siscom SPA

**Comment by mttfranci** [comment]
Ok grazie stiamo verificando.

**Comment by mttfranci** [comment]
@AMonopoliADS @siscomanpr  dovremmo aver individuato e corretto l'anomalia.
Potreste verificare se ora funziona?

NOTA: se lo stesso usc genera un nuovo OTP quello precedente viene invalidato anche se ancora non scaduto.

**Comment by AMonopoliADS** [comment]
da Valeggio sul Mincio mi confermano che adesso il servizio è funzionante. 

grazie

**Comment by mttfranci** [comment]
Perfetto grazie @AMonopoliADS 
Buon lavoro
