### ISSUE TITLE
[R009] - Variazioni delle generalità del cittadino, per i casi d'uso Citt_043, Citt_044 e Citt_045.

### ISSUE THREAD

**Issue by gcuci** [italia/ansc#443]
buongiorno,

come da accordi presi nell'ultima call di aggiornamento, riportiamo di seguito una segnalazione del Comune di Firenze, relativa ai casi d'uso in oggetto.

Si segnala l’impossibilità di rappresentare alcune particolari casistiche in cui le generalità presenti in anagrafe (ANPR) di neo cittadini italiani risultano discordanti con le generalità riportate nel Decreto (D.p.R. o D.P.) di concessione/conferimento della cittadinanza italiana.
 
Tali casistiche sono rappresentate per il tramite dei seguenti casi d’uso: 
- **Citt_043 o  Citt_044: prestazione di giuramento a seguito di decreto**
- **Citt_045: Trascrizione del decreto per matrimonio-unione civile-naturalizzazione-presentazione cittadino**

Nei casi in cui le generalità presenti in anagrafe (ANPR) siano discordanti da quelle presenti in Decreto (D.p.R. o D.P) le nuove generalità attribuite al cittadino sono quelle con  cui è identificato nel Decreto.
Di conseguenza la registrazione di atti di cittadinanza nei casi d’uso sopra riportati possono portare al contestuale cambiamento delle generalità del cittadino.
Le generalità devono essere modificate sia nell’archivio di Stato Civile ANSC, sia nell’archivio di anagrafe (ANPR).
Nella prima pagina dell’atto, in alto, devono comparire sia le generalità con cui il cittadino è identificato prima dell’acquisto della cittadinanza (generalità presenti in anagrafe (ANPR), sia le nuove generalità presenti nel Decreto con indicazione chiara di quali siano le precedenti e nuove generalità assunte dal cittadino.
 
Questo in quanto il Ministero dell’Interno tramite l’**allegata** Circolare avente ad oggetto “Cittadinanza italiana_revisione del procedimento”  ha dato precise indicazioni alle Prefetture circa l’applicazione delle generalità riportate nei D.p.R. o D.P. ancorchè discordanti con l’atto di nascita e quindi in alcuni casi con le generalità registrate in ANPR.

Pertanto, in applicazione della circolare “Cittadinanza italiana_revisione del procedimento” la Prefettura di Firenze, dopo aver condiviso,  in un incontro aperto a tutti i comuni le nuove procedure per l’acquisto della cittadinanza italiana” diramate dal Ministero dell’Interno,  ha tramesso una propria  circolare (qui in allegato) con la quale ha ribadito che “sulla base delle nuove direttive fornite dal Ministero dell’Interno, le generalità del neo-cittadino non saranno più estrapolate dall’atto di nascita del medesimo ma attribuite sulla  base della sua identità SPID che, **salvo eccezioni**, dovrebbero coincidere con quelle con le quali l’interessato è già noto in anagrafe.

Pertanto, in quelle particolari eccezioni in cui le generalità del neo italiano **certificate nel  D.p.R. o D.P**,  sulla base della sua IDENTITA’ SPID **non coincidono** con l’atto di nascita ovvero **con le generalità con  le quali l’interessato è già noto in anagrafe**  si rende necessario **ricondurre le generalità del neo-italiano con le generalità certificate nel D.p.R. o D.P** in concomitanza con l’evento “acquisto della cittadinanza” e quindi per il tramite dell’iscrizione del giuramento e della (coerente) trascrizione del decreto sui cui si basa tale giuramento.

In attesa di riscontro,

cordiali saluti.

[CIRCOLARE MINISTERO dell'INTERNO_Cittadinanza italiana_revisione del procedimento.pdf](https://github.com/italia/ansc/files/13215419/CIRCOLARE.MINISTERO.dell.INTERNO_Cittadinanza.italiana_revisione.del.procedimento.pdf)
[CITTADINANZA_circolareaiComunidel15giugno2021(inv)-signed.pdf](https://github.com/italia/ansc/files/13215423/CITTADINANZA_circolareaiComunidel15giugno2021.inv.-signed.pdf)

**Comment by asqueglia** [comment]
Buongiorno, come concordato verificheremo anche con ANUSCA per approfondire l'argomento. Al momento il sistema non consente di acquisire nuove generalità del cittadino contestualmente la registrazione dell'atto di cittadinanza.

**Comment by asqueglia** [comment]
Buongiorno, il caso d'uso di decreto prefettizio di cittadinanza con le generalità già modificate del cittadino, verrà preso in carico nel 2024.

**Comment by asqueglia** [comment]
Buongiorno con la versione 1.27.0 è stato rilasciato il caso d'uso specifico di decreto di acquisto di cittadinanza con modifica di generalità intestatario.
