### ISSUE TITLE
[R009] Validazione IdUseCase 346000 - pattern sigla provincia ente

### ISSUE THREAD

**Issue by MichelaGarzoni** [italia/ansc#444]
Buongiorno, abbiamo richiesto la validazione del seguente json:

_reguest:_
{
"testataRichiesta":{
"idComune":3655
,"idOperazioneComune":"20230150000005"
,"dataOraRichiesta":"2023-10-31T16:03:09Z"
,"nomeApplicativo":"ASCOT Stato Civile"
,"versioneApplicativo":"21.99.0000"
,"fornitoreApplicativo":"Insiel S.p.A"
}
,"evento":{
"idVersion":"100004"
,"idTipoEvento":"3"
,"idtipocontenuto":"1"
,"idUsecase":"346000"
,"descrizioneCasoUso":"Trascrizione delle sentenze di deliberazione, da parte della Corte d\u2019Appello, delle sentenze di nullit\u00E0 del matrimonio pronunciate dai Tribunali Ecclesiastici"
,"stato":"CONFERMATO"
,"flagsecretato":"0"
,"dataformazione":"2023-07-10"
,"ora":"12"
,"minuto":"05"
,"numeroatto":"20230150000005"
,"idComuneRegistrazione":3655
,"nomeComuneRegistrazione":"DUINO AURISINA-DEVIN NABRE\u017DINA"
,"idProvinciaRegistrazione":"32"
,"siglaProvinciaRegistrazione":"TS"
,"certificabile":"1"
,"composizioneCompleta":"Oggi dieci, del mese di luglio dell\u0027anno duemilaventitre, alle ore dodici e minuti cinque io sottoscritto XXXXXXXXXXXX, -, Ufficiale dello stato civile del Comune di Duino Aurisina-Devin Nabre\u017Eina, , ho ricevuto da  XXXXXXXXX nato in Duino Aurisina  il tre maggio millenovecentosessantotto, residente in San Dorligo Della Valle-Dolina, la richiesta con atto scritto in data 18\/10\/2023 n.445588 di trascrivere numero 49658 in data 08\/07\/2023 da Consolato in STRASBURGO  (FRANCIA), di cui mi consegna copia.\nAderendo a tale richiesta, provvedo alla trascrizione del documento, come segue: \nsentenza di annullamento.\nDopo di che, ho munito del mio visto ed inserito nel volume degli allegati a questo registro copia del documento scritto e copia della richiesta di trascrizione.\n"
,"separazione":{
"tipoAccordo":"2"
,"attoMatrimonio":{
"idComuneRegistrazione":"006"
,"nomeComuneRegistrazione":"BARI"
,"siglaProvinciaRegistrazione":"BA"
,"idProvinciaRegistrazione":"072"
,"idtipocontenuto":"1"
,"dataformazione":"2020-07-10"
,"numeroatto":"3"
,"annoAtto":"2020"
,"tipologia":"3"
,"parte":"I"
}
,"parteInGiudizioPendente":false
,"dataConfermaAccordo":"2023-12-28"
}
,"trascrizioneSeparazione":{
"tipoDichiarazione":"3"
,"dataComunicazione":"2023-10-18"
,"testoLibero":"sentenza di annullamento"
,"atto":{
"enteEstero":{
"nomeEnte":"xxx"
,"idComuneEnte":"006"
**,"siglaProvinciaEnte":"TS"**
,"indirizzoEnte":"via Genova 43"
,"estremiDocumento":"6445"
,"nazioneEnte":"90"
,"nomeNazioneEnte":"ITALIA"
}
}
,"attoEstero":{
}
,"ricevutaDaPrivatoCittadino":true
,"sentenzaEcclesiastica":{
"nomeEnte":"xxx"
,"idComuneEnte":"006"
,"nomeComuneEnte":"TRIESTE"
,"idProvinciaEnte":"032"
,"siglaProvinciaEnte":"TS"
,"indirizzoEnte":"via Genova 43"
,"dataTrascrizione":"2023-10-19"
,"estremiDocumento":"6445"
}
}
,"dichiarante":{
"cognome":"XXXXX"
,"nome":"XXXXXX"
,"sesso":"M"
,"descrizioneSesso":"Maschile"
,"dataNascita":"1968-05-03"
,"idComuneNascita":"3655"
,"nomeComuneNascita":"DUINO AURISINA-DEVIN NABRE\u017DINA"
,"idProvinciaNascita":"32"
,"siglaProvinciaNascita":"TS"
,"idStatoNascita":"90"
,"nomeStatoNascita":"ITALIA"
,"idComuneResidenza":"004"
,"nomeComuneResidenza":"SAN DORLIGO DELLA VALLE-DOLINA"
,"idProvinciaResidenza":"032"
,"siglaProvinciaResidenza":"TS"
,"idStatoResidenza":"90"
,"nomeStatoResidenza":"ITALIA"
,"idNazionalita":"90"
,"nazionalita":"ITALIANO"
,"flagDichiarante":true
,"flagComparente":false
,"flagFirmatario":true
}
,"intestatari":[
{
"idsoggettoanpr":"83941987"
,"codiceFiscale":"BXXXXXXXXX4L424Z"
,"cognome":"XXXXXX"
,"nome":"XXXX"
,"sesso":"M"
,"dataNascita":"1976-09-14"
,"idComuneNascita":"006"
,"nomeComuneNascita":"TRIESTE"
,"idProvinciaNascita":"032"
,"siglaProvinciaNascita":"TS"
,"idStatoNascita":"90"
,"nomeStatoNascita":"ITALIA"
,"idComuneResidenza":"3655"
,"nomeComuneResidenza":"DUINO AURISINA-DEVIN NABRE\u017DINA"
,"idProvinciaResidenza":"32"
,"siglaProvinciaResidenza":"TS"
,"idStatoResidenza":"90"
,"nomeStatoResidenza":"ITALIA"
,"idNazionalita":"90"
,"nazionalita":"ITALIANO"
,"flagDichiarante":true
,"flagComparente":true
,"flagFirmatario":true
}
,{
"idsoggettoanpr":"83945538"
,"codiceFiscale":"VCXSTRXXX6XXXX4E"
,"cognome":"VECCHIET"
,"nome":"ESTER"
,"sesso":"F"
,"dataNascita":"1968-09-22"
,"idComuneNascita":"006"
,"nomeComuneNascita":"TRIESTE"
,"idProvinciaNascita":"032"
,"siglaProvinciaNascita":"TS"
,"idStatoNascita":"90"
,"nomeStatoNascita":"ITALIA"
,"idComuneResidenza":"3655"
,"nomeComuneResidenza":"DUINO AURISINA-DEVIN NABRE\u017DINA"
,"idProvinciaResidenza":"32"
,"siglaProvinciaResidenza":"TS"
,"idStatoResidenza":"90"
,"nomeStatoResidenza":"ITALIA"
,"idNazionalita":"90"
,"nazionalita":"ITALIANA"
,"flagDichiarante":true
,"flagComparente":true
,"flagFirmatario":true
}
]
}
}

_abbiamo ottenuto la seguente risposta:_
{
    "testataRisposta": {
        "idComune": 3655,
        "idOperazioneComune": "20230150000005",
        "idOperazione": "1692107",
        "idEsito": 1
    },
    "errors": [
       .....,
        {
            "code": "400003",
            "severity": "E",
            "text": "Il campo **evento.trascrizioneSeparazione.atto.enteEstero.siglaProvinciaEnte** nella sezione Autorità mittente non corrisponde al pattern **^[0-9]*$"**
        }
    ]
}

e non riusciamo a capire l'errore in quanto la siglaProvinciaEnte non dovrebbe essere un numerico, come invece evidenziato dal pattern indicato

**Comment by asqueglia** [comment]
Buongiorno, abbiamo verificato che avete trasmesso un comune con id=006 che ci risulta corrispondere ad 'ABBADIA LARIANA' la cui provincia è CO; sono state trasmesse invece provincie diverse in corrispondenza del suddetto comune. Consigliamo quindi di riprovare trasmettendo le giuste informazioni di comune e provincia sia in separazione che in trascrizioneSeparazione

**Comment by asqueglia** [comment]
Buongiorno non avendo ricevuto feddback in merito, provvediamo a chiudere la issue. In caso di ulteriori segnalazioni la preghiamo di aprire una altra issue dedicata
