### ISSUE TITLE
[R009] Validazione: request timed out

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#446]
Il servizio di validazione va in errore: request timed out oppure Bad Gateway

**Comment by mttfranci** [comment]
Salve, potreste riprovare?

Saluti

Assistenza ANSC

**Comment by biadanpad** [comment]
Ricevo ancora lo stesso errore: request timed out

**Comment by mttfranci** [comment]
@biadanpad  si scusate, potreste provare ancora una volta?

Saluti

Assistenza ANSC

**Comment by biadanpad** [comment]
Ricevo ancora lo stesso errore: request timed out

**Comment by gcuci** [comment]
buongiorno,

segnaliamo anche noi il persistere del problema. Per effettuare una validazione dobbiamo ripetere l'operazione 3, 4 volte, in quanto viene restituito più volte un errore di timed out, prima di darci un esito positivo.

In attesa di riscontro,

cordiali saluti.

**Comment by biadanpad** [comment]
Adesso l'errore che ricevo è il seguente:

HttpResponse Code: 502
HttpResponse Body: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>openresty</center>
</body>
</html>

Ci sono previsioni per la risoluzione del problema?

**Comment by mttfranci** [comment]
Salve @biadanpad stiamo verificando, vi facciamo sapere appena abbiamo novità.

Saluti

Assistenza ANSC

**Comment by mttfranci** [comment]
@biadanpad @gcuci  potreste provare nuovamente?

Grazie in anticipo.

**Comment by gcuci** [comment]
Ok, adesso risponde correttamente. Abbiamo effettuato 3 successive validazioni, tutte con esito positivo.

**Comment by mttfranci** [comment]
Perfetto, grazie del riscontro.
Saluti

Assistenza ANSC
