### ISSUE TITLE
[ANSC vs ANPR] ANPR: Non riceviamo la notifica di predisposizione evento digitale

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/ansc#447]
ambiente PROD - comune di Valeggio sul  Mincio (idComune 10420)

idAttoAnsc: 2023-3-1-023089

servizio di validazione data inviato (ws R014) 
notifica automatica scaricata e confermata (ws R008)

lato ANPR non arriva la notifica di predisposizione evento digitale.

potete verificare per piacere?

Alessandro Monopoli ADS

**Comment by asqueglia** [comment]
Abbimao preso in carico la verifica.. vi facciamo sapere a breve quando poter consultare la notifica anagrafica

**Comment by asqueglia** [comment]
Comunichiamo che la notifica anagrafica è stata generata. Potete visionarla lato ANPR.

**Comment by AMonopoliADS** [comment]
buongiorno

via web-service continuiamo a non ricevere le notifiche.

idOperazioneANPR della richiesta: 1499241863
la verifica di stato eseguita questa mattina alle 7:00, ha rinviato al disponibilità alle 8:00.
la verifica di stato eseguita alle 8:22, ha rinviato la disponibilità alle 9:22

potete verificare nuovamente?

grazie

**Comment by asqueglia** [comment]
verifichiamo e le facciamo sapere

**Comment by asqueglia** [comment]
Abbiamo rigenerato la notifica, potete riprovare a scaricarla ? non dovrebbe più verificarsi il problema.

**Comment by asqueglia** [comment]
Buongiorno non avendo ricevuto feddback in merito, provvediamo a chiudere la issue. In caso di ulteriori segnalazioni la preghiamo di aprire una altra issue dedicata
