### ISSUE TITLE
[R009] - Validazione caso d'uso Citt_046, Stato Ente e Anagrafica Consolato non visualizzate.

### ISSUE THREAD

**Issue by gcuci** [italia/ansc#448]
buongiorno,

segnaliamo che per il caso d'uso in oggetto, nonostante vengano correttamente passate le informazioni della 'trascrizioneCittadinanza', nella maschera della Web Application, non vengono visualizzati i valori dello Stato ente, e dell' Anagrafica Consolato.

Di seguito parte del json inviato per la validazione:

...
    "trascrizioneCittadinanza": {
      "dataComunicazione": "2023-10-16",
      "testoLibero": "do' atto che con il predetto decreto e' conferita la CITTADINANZA ITALIANA",
      "atto": {
        "enteEstero": {
          "nazioneEnte": "602",
          "nomeNazioneEnte": "ARGENTINA",
          "idAnagraficaConsolato": "35",
          "nomeAnagraficaConsolato": "BUENOS AIRES",
          "nomeEnte": "CONSOLATO GENERALE",
          "dataTrascrizione": "2023-10-03",
          "estremiDocumento": "Decreto n.5930"
        }
      }
    },
...

Questa la risposta con esito positivo, restituita dal servizio:

{
  "idEvento": "1212688",
  "idAnsc": "2023-1212688-30533-039002",
  "idTipoEvento": "5",
  "testataRisposta": {
    "idComune": 595,
    "idOperazioneComune": "6477",
    "idOperazione": "1691257",
    "idEsito": 0
  }
}

L'operazione è stata effettuata il 30/10/2023, in ambiente di Preproduzione, il suo idOperazione è '1691257'.

Questo invece quello che viene visualizzato nella maschera della Web Application:

![image](https://github.com/italia/ansc/assets/128400400/14f6954e-6a7c-4add-9aed-fb7911029eb1)

In attesa di riscontro,

cordiali saluti.

**Comment by asqueglia** [comment]
Buongiorno grazie per la segnalazione. Verifichiamo e avvisiamo non appena abbiamo risolto.

**Comment by asqueglia** [comment]
Abbiamo verificato che viene trasmesso un id stato non coerente, e da ciò l'errore sulla web app.
nello specifico è stato trasmesso  il valore "602" anziché "8" che è il valore corretto per ARGENTINA.
Inoltre essendo 602 non presente sulla tabella AMM_STATO, non viene trovata corrispondenza e di conseguenza non viene inserito il nome.
La combo lato Webapp che fa riferimento ai campi "idAnagraficaConsolato" e "nomeAnagraficaConsolato", essendo dipendente dal valore inserito in nome nazione ente viene anch'essa sbiancata non trovando corrispondenza con la nazione ente.

Riassumendo, il payload corretto sarebbe: 

**"trascrizioneCittadinanza": {
"dataComunicazione": "2023-10-16",
"testoLibero": "do' atto che con il predetto decreto e' conferita la CITTADINANZA ITALIANA",
"atto": {
"enteEstero": {
"nazioneEnte": "8",
"nomeNazioneEnte": "ARGENTINA",
"idAnagraficaConsolato": "35",
"nomeAnagraficaConsolato": "BUENOS AIRES",
"nomeEnte": "CONSOLATO GENERALE",
"dataTrascrizione": "2023-10-03",
"estremiDocumento": "Decreto n.5930"
}**

**Comment by gcuci** [comment]
Perfetto, grazie.
In effetti, non avendo una segnalazione di errore, non ci eravamo accorti che veniva passato il codice Istat della nazione, e non il corretto id stato, secondo la codifica ANPR di riferimento.

Chiudiamo la issue.
