### ISSUE TITLE
evento.datiEventoRiconoscimento

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#45]
Buongiorno,
nel campo del model in oggetto bisogna mettere il numero di mesi del concepimento.
A suo tempo i nostri Comuni ci avevano chiesto di poter indicare anche in settimane per riportare esattamente quanto veniva scritto nel certificato medico.
Per il json convertiamo le settimane in mesi e lasciando nel testo dell'atto le settimane? Oppure dovremmo obbligare i Comuni a scrivere direttamente solo in mesi (quindi non riportando tale e quale come scritto nel certificato)?

**Comment by asqueglia** [comment]
La issue viene chiusa in caso si prega di riaprirla.
