### ISSUE TITLE
[R002] Estratto per copia integrale - timeout

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#451]
Il servizio in oggetto fallisce spesso restituendo il mesaggio di timeout

**Comment by amusarra** [comment]
Salve @biadanpad 
Il problema persiste ancora?

Cordiali Saluti.
Supporto ANSC.

**Comment by biadanpad** [comment]
3 volte su 2 è andato in timeout

**Comment by amusarra** [comment]
@biadanpad sull'ambiente di pre-produzione c'erano delle attività in corso per cui è plausibile aver ricevuto dei timeout ma adesso non dovreste averli.

Vi chiediamo pertanto di riprovare nuovamente. Se non dovesse ripetersi il timeout, vi chiediamo di chiudere la issue.

Cordiali Saluti.
Supporto ANSC.

**Comment by biadanpad** [comment]
Buonasera, sembra che il problema sia risolto.
