### ISSUE TITLE
Atto di Matrimonio - UseCase 319999: Dati Pubblicazione da consolato

### ISSUE THREAD

**Issue by KibMcris** [italia/ansc#452]
Nel mapping del caso d'uso  https://github.com/italia/ansc/blob/main/docs/Mapping_casi_uso/matrimoni/Matr_999_1.csv i dati relativi alla pubblicazione non risultano essere obbligatori a meno non tracciato non sia valorizzato l'oggetto evento.datiEventoMatrimonio.omissionePubblicazione,=,true.

Il caso d'uso in oggetto richiede obbligatori i dati di provincia e comune di pubblicazione. Nei casi di celebrazione di matrimonio civile  su delega del consolato la pubblicazione è stata effettuata dal consolato e non da comune italiano.

Abbiamo provato in ambiente di preproduzione a non valorizzare i dati relativi alla pubblicazione ma ANSC ha risposto con errore.

L'idoperazione della request e la data e l'ora della richiesta:
Idoperazionecomune=12 
dataOraRichiesta": "2023-11-03 10:17:59

Mentre, questa è la risposta ottenuta da ANSC:

{"testataRisposta":{"idComune":10288,"idOperazioneComune":"12","idOperazione":"1693327","idEsito":1},"errors":[{"code":"400003","severity":"E","text":"Il campo evento.datiEventoMatrimonio.pubblicazione1.idProvincia nella sezione Pubblicazioni è obbligatorio"},{"code":"400003","severity":"E","text":"Il campo evento.datiEventoMatrimonio.pubblicazione1.provincia nella sezione Pubblicazioni è obbligatorio"},{"code":"400003","severity":"E","text":"Il campo evento.datiEventoMatrimonio.pubblicazione1.idComune nella sezione Pubblicazioni è obbligatorio"},{"code":"400003","severity":"E","text":"Il campo evento.datiEventoMatrimonio.pubblicazione1.comune nella sezione Pubblicazioni è obbligatorio"},{"code":"400003","severity":"E","text":"Il campo evento.datiEventoMatrimonio.pubblicazione1.dataInizio nella sezione Pubblicazioni è obbligatorio"},{"code":"400003","severity":"E","text":"Il campo evento.datiEventoMatrimonio.pubblicazione1.dataFine nella sezione Pubblicazioni è obbligatorio"}]}

Restiamo in attesa di riscontro. Si precisa che l'atto deve essere registrato anche in ambiente di produzione.

**Comment by asqueglia** [comment]
Buon pomeriggio, volevamo capire se il caso che state citando è una trascrizione di matrimonio richiesta da consolato. In tal caso esiste il caso d'uso di servizio 339999. Restiamo in attesa di un vostro riscontro.

**Comment by KibMcris** [comment]
Buon pomeriggio, abbiamo la necessità di redigere un atto di matrimonio civile su delega del consolato. Non dobbiamo trascrivere l'atto, ma celebrare il matrimonio di due cittadini residente all'AIRE.
Perciò, non essendo presente un caso d'uso specifico, stiamo utilizzando quello di servizio 319999-Caso d'uso di servizio (matrimoni con rito civile).

**Comment by asqueglia** [comment]
Buongiorno, il caso da lei indicato non è presente e non è stato contemplato. Provvederemo a parlarne con gli esperti  ANUSCA e le faremo sapere

**Comment by asqueglia** [comment]
Con il rilascio della versione 1.20.0, come da accordi, è stata resa opzionale la pubblicazione di matrimonio per il caso d'uso di servizio per matrimonio con rito civile per sopperire alla mancanza del caso d'uso di matrimonio su delega del consolato. Il caso d'uso che prevede la delega da consolato verrà pianificato in uno dei successivi rilasci. Provvediamo quindi a chiudere la issue. In caso di ulteriori segnalazioni si prega di aprire una issue dedicata.
