### ISSUE TITLE
Conferma Accordo- Caso d'Uso 343000- Conferma o mancata conferma di accordo di separazione o divorzio

### ISSUE THREAD

**Issue by KibMcris** [italia/ansc#454]
In ambiente di preproduzione stiamo riscontrando un errore per il caso d'uso in oggetto.
Dopo aver validato l'atto IDAnsc 2023-1212902-9-102044 al momento di visualizzare l'anteprima dell'atto otteniamo un errore "Dati ingresso non Corretti".
Andando comunque avanti siamo riusciti a caricare le firme dei coniugi e la firma dell'Ufficiale di Stato Civile.

Entrando nella WEBApp di ANSC però  non riusciamo a consultare comunque l'atto redatto e firmato in quanto appare un messaggio di errore 500.
![image](https://github.com/italia/ansc/assets/133867680/71c9844e-3b8c-4158-bd98-bb1c3cea53d2)

Abbiamo tentato di registrare un altro atto dopo circa due ore per lo stesso caso d'uso, ipotizzando un errore temporaneo, ma abbiamo ottenuto la stessa sequenza di errori.

L'atto deve essere registrato nei prossimi giorni anche in produzione.
Restiamo in attesa di riscontro.
Grazie

**Comment by gbuemi** [comment]
Buongiorno verifichiamo e le facciamo sapere.

**Comment by mttfranci** [comment]
Buongiorno, l'anomalia dovrebbe essere risolta con la patch 1.18.1 appena rilasciata.

Saluti

Assistenza ANSC
