### ISSUE TITLE
Processo Verbale Firme- Caricamento Allegato

### ISSUE THREAD

**Issue by KibMcris** [italia/ansc#456]
Buongiorno, segnaliamo che dopo il rilascio della versione 1.18.1 dopo aver validato e visualizzato l'atto, scaricando il processo verbale con le firme dei dichiaranti, ANSC risponde con il seguente errore:

HTTP Status 400 
{"errors":[{"code":"413102","severity":"E","text":"Tipo File non consentito"}],"testataRisposta":{"idComune":10288,"idEsito":1,"idOperazione":"1694158","idOperazioneComune":"11"}}

Si veda ad esempio l'atto con idAnsc 1212969.

Abbiamo notato che lo stesso comportamento si ottiene compilando l'atto da WEBAPP e caricando il processo verbale delle firme, l'allegato rimane nello status di caricamento e non si riesce a proseguire.

Si veda atto id ANSC 1212968.

Aggiungo che non sembra un comportamento del caso d'uso specifico. Infatti anche per l'atto idANSC 1212966 abbiamo riscontrato lo stesso problema.

Restiamo in attesa di riscontro

**Comment by mttfranci** [comment]
Buongiorno, stiamo verificando.
Vi facciamo sapere a breve.

Saluti

Assistenza ANSC

**Comment by mttfranci** [comment]
Buongiorno, riguardo alla risposta del 1694158 in preproduzione.
Con la 1.18.1 abbiamo esteso il controllo di congruità tra tipo file e contenuto anche al servizio di caricamento degli allegati, quindi il tipo inviato deve essere coerente con quello presente nella tabella dec tipo file : 
https://github.com/italia/ansc/blob/main/docs/Decodifiche/10_dec_tipo_file.csv
Nel caso specifico è stato inviato un pdf ed è stato indicato tipoFile: 2 quando per i pdf dovrebbe essere tipoFile: 1.

L'anomalia legata alla web app è di altra origine (la web app non è stata toccata) e la stiamo verificando.

**Comment by mttfranci** [comment]
@KibMcris  in produzione l'anomalia sugli allegati dovrebbe essere risolta. In preproduzione stiamo ancora termiando le operazioni.

Saluti

Assistenza ANSC

**Comment by mttfranci** [comment]
Ora dovrebbe essere tutto a posto anche in collaudo.
Da tenere presente la verifica di congruenza tra il tipo file e il file inviato da servizio cooperativo.
