### ISSUE TITLE
[R901] Errore Servizi di decodifica: "La proprietà 'datiPaginazione' non è prevista"

### ISSUE THREAD

**Issue by davidePanettieri** [italia/ansc#457]
Buongiorno, stiamo effettuando un test di chiamata verso il servizio di decodifica elenco
**URL** : https://anscservicepre.anpr.interno.it/services/service/val/config/decodifica/elenco/1
ma riceviamo in risposta l'errore  "Errore chiamata al servizio ANSC: code=400, severity=E, text=La proprietà 'datiPaginazione' non è prevista."

**Request**:
```json
{
    "testataRichiesta": {
        "idComune": 5646,
        "idOperazioneComune": "APP2022032210000",
        "dataOraRichiesta": "2023-11-06",
        "nomeApplicativo": "SIDe",
        "versioneApplicativo": "1.0.0",
        "fornitoreApplicativo": "SistemiInformativi"
    }
}
``` 

**Response**:
```json
{
    "testataRisposta": {
        "idEsito": -1
    },
    "errors": [
        {
            "code": "400",
            "severity": "E",
            "text": "La proprietà 'datiPaginazione' non è prevista."
        }
    ]
}
```
C'è stata una modifica sull'oggetto AnscRequest che riguarda i datiPaginazione? la chiamata funziona solo se si elimina datiPaginazione dall'oggetto.
Nel changelog non vediamo questo cambiamento, è un bug o è una modifica dell'oggetto base ANSCRequest che va ad alterare tutti i servizi?
I dati paginazione di AnscRequest vengono usati da noi in altri servizi come ad esempio R005 Consultazione evento per ricevere la risposta paginata.

**Comment by mttfranci** [comment]
Salve tale controllo è stata introdotto nella release [1.4.0](https://github.com/italia/ansc/blob/main/docs/Changelog.md#added-6) e da allora non è cambiato.

Non riguarda tutti i servizi ma solo quelli dove la paginazione non è necessaria (l'elelenco decodifiche, visto che i dati restituiti sono minimi, restituisce sempre tutte le decodifiche presenti).

In generale tale controllo non è stato aggiunto a tappeto, la ricerca in particolare non ne dovrebbe essere influenzata nè ora nè in futuro.

Saluti

**Comment by davidePanettieri** [comment]
Grazie per la risposta, abbiamo riscontrato questo problema perchè si presenta anche quando l'oggetto datiPaginazione è null nella request. Abbiamo risolto escludendo il campo dalla serializzazione quando è null.
