### ISSUE TITLE
[R009] - Errore Interno ANSC 500

### ISSUE THREAD

**Issue by DiBellaDavide** [italia/ansc#458]
Salve,
stiamo provando ad invocare il servizio di validazione evento, con idVersion : 100004 ,su più casi d'uso senza successo. 
La risposta del servizio è la seguente:
`{"message":"internal.error","errors":null}`
per cui non è possibile indicare l'idOperazione.
Riporto in questa issue l'idOperazioneComune dalla nostra richiesta al servizio :
`"idOperazioneComune":"ac9fc192-e32d-4235-9b34-c705fa271ff0"`

Attendo vostre notizie,
distinti saluti.

**Comment by mttfranci** [comment]
Salve @DiBellaDavide , ora verifichiamo, intanto possiamo chiedervi se parliamo di preproduzione e/o produzione?

Grazie in anticipo.

Assistenza ANSC

**Comment by DiBellaDavide** [comment]
L'ambiente dei test è di pre-prod

**Comment by mttfranci** [comment]
Per caso potreste riprovare?
Grazie in anticipo.

**Comment by DiBellaDavide** [comment]
adesso tutto sembra funzionare correttamente, grazie mille

**Comment by mttfranci** [comment]
Grazie a voi.
Buona giornata.

**Comment by DiBellaDavide** [comment]
Buonasera, purtroppo i servizi sono tornati a non funzionare con le stesse modalità del primo commento, attendo vostre notizie.
Sempre ambiente di preproduzione

**Comment by DiBellaDavide** [comment]
Buongiorno, dai test effettuati ieri in serata e stamattina, confermiamo che i servizi sono tornati a funzionare regolarmente, grazie.

**Comment by DiBellaDavide** [comment]
Buongiorno, mi ritrovo a riaprire la issue sempre per le stesse problematiche, attendo vostre notizie

**Comment by siscomanpr** [comment]
Anche noi riceviamo lo stesso errore con il servizio R009

**Comment by mttfranci** [comment]
Salve, questa issue è legata alla #464 e #463 (per ora lasciamo aperta solo la 458 per tracciare la questione) stiamo verificando i disservizi temporanei di questi giorni. 

Da notare comunque che l'ambiente di preproduzione non ha la stessa affidabilità di quello di produzione.

Saluti

**Comment by gcuci** [comment]
Buongiorno,

segnaliamo anche noi il ripresentarsi dell'anomalia (per noi 'timeout', vd. issue #463).

In particolare è bloccante per il servizio di Validazione (viene restituito ad ogni invocazione), mentre si è verificato saltuariamente per quello di Certificazione.
Per gli altri servizi che stiamo utilizzando, Ricerca ANSC (per Evento e per Soggetto), ed Anteprima, non si sta invece verificando.

Chiaramente, essendo il servizio di Validazione, centrale, nel processo di gestione degli Eventi, siamo bloccati nell'esecuzione dei test di verifica dei vari Casi d'Uso, con i nostri Comuni.

In attesa di riscontro,

cordiali saluti.

**Comment by davidePanettieri** [comment]
Buongiorno, 
mi accodo a questa issue per non aprirne altre relative allo stesso problema.
Oltre ai problemi già segnalati sul servizio di validazione **[R009]** , stiamo riscontrando l'errore
 `{"message":"internal.error","errors":null}` 
anche sul servizio di decodifica dettaglio **[R901]** https://anscservicepre.anpr.interno.it/services/service/val/config/decodifica/dettaglio/1

**Comment by davidePanettieri** [comment]
Buonasera, si il problema sembra essere risolto.
Grazie,
Saluti

**Comment by biadanpad** [comment]
Stiamo continuando ad avere problemi di timeout. Questa volta con il servizio con il servizio di certificazione

**Comment by mttfranci** [comment]
Salve @biadanpad  oggi in particolare i disservizi non dovrebbero essere legati a quelli dell'altro giorno (per cui è stata eseguita una correttiva), è in corso una manutenzione straordinaria dell'ambiente di pre produzione #471.
La situazione dovrebbe essere limitata alla giornata di oggi.
Saluti

**Comment by biadanpad** [comment]
Buongiorno, 
il servizio di certificazione va ancora in timeout

**Comment by DiBellaDavide** [comment]
Buongiorno,
confermiamo anche noi disservizi al sistema di validazione evento

**Comment by mttfranci** [comment]
@biadanpad  @DiBellaDavide noi vediamo ogni tanto qualche errore su cui stiamo provando ad intervenire, però non ci sembra che stiamo nella situazione della settimana scorsa. Voi avete molti timeout al momento?
Grazie in anticipo.

**Comment by biadanpad** [comment]
Buongiorno, al momento non stiamo riscontrando il problema

**Comment by asqueglia** [comment]
Buongiorno , provvediamo a chiudere la issue. In caso di ulteriori segnalazioni la preghiamo di aprire una altra issue dedicata
