### ISSUE TITLE
Caso d'uso Sep_Div_005: ancora indicazioni su campi data

### ISSUE THREAD

**Issue by antonioluberto** [italia/ansc#459]
Buongiorno.
Riprendo la questione già sottoposta con https://github.com/italia/ansc/issues/436.
La issue è stata chiusa con l'indicazione di "soluzione" avvenuta con il rilascio 1.18.
Sulla documentazione relativa a quest'ultimo rilascio non vediamo però nulla che risponda ai quesiti funzionali che avevamo sottoposto e che nuovamente riporto qui di seguito:

Per il caso d'uso in oggetto, devono certamente essere gestite:
a) la data in corrispondenza della quale il Tribunale trasmette agli avvocati di parte il nulla osta (ovvero l'autorizzazione) alla negoziazione assistita.
**_Domanda_**:
questa data deve essere usata per la valorizzazione del campo:

![image](https://github.com/italia/ansc/assets/26415430/1cc216af-015a-4f02-bd66-f1b043c9879d)

?

b) la data in corrispondenza della quale l'avvocato di ciascuna delle due parti trasmette all'ufficio di stato civile competente alla trascrizione copia autentica dell'accordo. Questa seconda data deve essere successiva di non più di 10 giorni a quella di cui ap punto a).

**_Domanda_**:
queste date devono essere usate per la valorizzazione del campi:

![image](https://github.com/italia/ansc/assets/26415430/4528ee76-a045-4572-9af2-c42301b334f2)

?

Rimangono infine i due quesiti:
c) quale data dovremmo riportare in corrispondenza del campo:

![image](https://github.com/italia/ansc/assets/26415430/6428e730-608c-4355-8883-34f46793ce49)

?

Nella corrispondente colonna "Binding Field" si trova l'indicazione "dataTrascrizione", ma non è chiaro a quale trascrizione si faccia riferimento.
Si tratta magari, diversamente, della data in cui viene stipulato l'accordo di negoziazione assistita tra le parti?
 
d) per quanto relativo al campo "Data deposito":

![image](https://github.com/italia/ansc/assets/26415430/9eba9f97-fd70-4018-8106-d53ceb0ec1c8)

 possiamo assumere che rappresenti la data in cui il Tribunale abbia emesso il nulla osta (ovvero l'autorizzazione) alla negoziazione assistita?

**Comment by asqueglia** [comment]
Buon pomeriggio @antonioluberto, la riposta è si a tutte le domande poste; nello specifico
a) la data in corrispondenza della quale il Tribunale trasmette agli avvocati di parte il nulla osta (ovvero l'autorizzazione) alla negoziazione assistita è il campo evento.negoziazioneAssistita.dataComunicazioneProvvedimento 
b) la data in corrispondenza della quale l'avvocato di ciascuna delle due parti trasmette all'ufficio di stato civile competente alla trascrizione copia autentica dell'accordo, è il campo evento.negoziazioneAssistita.dataRicezioneAttoConiuge a seconda dell'avvocato delle due parti
c) quale data dovremmo riportare in corrispondenza del campo dataTrascrizione ? si è la data in cui viene stipulato l'accordo di negoziazione assistita tra le parti
d) per quanto relativo al campo "Data deposito", si corretto si può assumere che rappresenti la data in cui il Tribunale abbia emesso il nulla osta (ovvero l'autorizzazione) alla negoziazione assistita

Se c'è qualcosa che non torna, ci faccia sapere.

**Comment by asqueglia** [comment]
Buongiorno non avendo ricevuto feddback in merito, provvediamo a chiudere la issue. In caso di ulteriori segnalazioni la preghiamo di aprire una altra issue dedicata
