### ISSUE TITLE
usecase 12323100	Assenso al riconoscimento da parte del figlio ultraquattordicenne	(Rico_013)

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#46]
Nel mapping del caso in oggetto i campi relativi a
 evento.padre, evento.madre, evento.riconoscimentoPadre.atto, evento.riconoscimentoMadre.atto
sono dichiarati non obbligatori.
Mandando il json per la convalida dell'atto , l'atto viene rifiutato perché questi campi sono vuoti e risultano obbligatori.
E' corretto quanto dichiarato nel mapping o il risultato del json?

**Comment by asqueglia** [comment]
Buongiorno, in base al genitore che ha reso il riconoscimento, risulta obbligatorio inserire sia l'anagrafica del suddetto genitore (padre o madre) e sia il relativo atto di riconoscimento.
Di seguito un esempio di payload di assenso del figlio al riconoscimento reso dalla madre
 "evento": {
        "idTipoEvento": "1",
        "idtipocontenuto": "1",
        "idUsecase": "12323100",
        "descrizioneCasoUso": "Assenso al riconoscimento da parte del figlio ultraquattordicenne",
        "stato": "CONFERMATO",
        "dataformazione": "2023-04-13",
        "ora": "09",
        "minuto": "53",
        "annoAtto": "2023",
        "numeroatto": "2323",
        "tipoDichiarante": "8",
        "ausilioInterprete": "false",
        "idComuneRegistrazione": "1000000",
        "nomeComuneRegistrazione": "ANPR",
        "idProvinciaRegistrazione": "58",
        "siglaProvinciaRegistrazione": "RM",
        "operatore": "CRUMRA67S47Z127B",
        "ruoloOperatore": "2",
        "operatoreNome": "MARIE",
        "operatoreCognome": "CURIE",
        "redattoNellaCasaComunale": true,
        "datiProdotti": "1",
        "allegati": [
            {
                "id": XXX,
                "idTipoAllegato": 13,
                "hashAllegato": "XXX",
                "descrizione": "Copia integrale dell'atto di nascita del figlio che viene riconosciuto"
            }
        ],
        "intestatari": [
            {
                "cognome": "XX",
                "nome": "XXX",
                "sesso": "M",
                "dataNascita": "1989-06-28",
                "idComuneNascita": "1709",
                "nomeComuneNascita": "CAMUGNANO",
                "idProvinciaNascita": "37",
                "siglaProvinciaNascita": "BO",
                "idStatoNascita": "90",
                "nomeStatoNascita": "ITALIA",
                "idComuneResidenza": "6748",
                "nomeComuneResidenza": "OSTUNI",
                "idProvinciaResidenza": "74",
                "siglaProvinciaResidenza": "BR",
                "idStatoResidenza": "90",
                "nomeStatoResidenza": "ITALIA",
                "indirizzoResidenza": "",
                "idNazionalita": "90",
                "nazionalita": "ITALIANA",
                "flagDichiarante": false,
                "flagComparente": false,
                "flagFirmatario": false
            }
        ],
        "madre": {
            "cognome": "XX",
            "nome": "XXXX",
            "sesso": "F",
            "dataNascita": "2020-05-01",
            "idComuneNascita": "8165",
            "nomeComuneNascita": "ROMA",
            "idProvinciaNascita": "58",
            "siglaProvinciaNascita": "RM",
            "idStatoNascita": "90",
            "nomeStatoNascita": "ITALIA",
            "idComuneResidenza": "2780",
            "nomeComuneResidenza": "CESENA",
            "idProvinciaResidenza": "40",
            "siglaProvinciaResidenza": "FC",
            "idStatoResidenza": "90",
            "nomeStatoResidenza": "ITALIA",
            "indirizzoResidenza": "",
            "idNazionalita": "90",
            "nazionalita": "ITALIANA",
            "flagDichiarante": false,
            "flagComparente": false,
            "flagFirmatario": false
        },
        "datiDichiarante": {
            "comprensione": "0",
            "motivoImpedimentoScrittura": ""
        },
        "datiEventoRiconoscimento": {
            "attoNascita": {
                "idComuneRegistrazione": "99",
                "nomeComuneRegistrazione": "AGRIGENTO",
                "idProvinciaRegistrazione": "84",
                "siglaProvinciaRegistrazione": "AG",
                "idtipocontenuto": "1",
                "dataformazione": "1980-04-11",
                "numeroatto": "12321",
                "annoAtto": "1980",
                "tipologia": "1",
                "serie": "A",
                "parte": "I"
            }
        },
        "riconoscimentoMadre": {
            "avvenuto": true,
            "atto": {
                "idComuneRegistrazione": "99",
                "nomeComuneRegistrazione": "AGRIGENTO",
                "idProvinciaRegistrazione": "84",
                "siglaProvinciaRegistrazione": "AG",
                "idtipocontenuto": "1",
                "dataformazione": "2023-04-03",
                "numeroatto": "343243",
                "annoAtto": "2023",
                "tipologia": "1",
                "serie": "B",
                "parte": "II"
            }
        },
        "datiAssenso": {
            "tipoAssenso": "1"
        },
        "composizioneCompleta": "XXXX",
        "dataultimoagg": "2023-04-13T09:56:30.761103"
    }

**Comment by asqueglia** [comment]
La issue viene chiusa in caso si prega di riaprirla.
