### ISSUE TITLE
[R009] validazione caso d'uso 342000 - accordo di scioglimento (Sep_Div_002)

### ISSUE THREAD

**Issue by siscomanpr** [italia/ansc#461]
Con la nuova versione 1.18 è stato introdotto il nuovo campo tipoProvvedimentoSeparazione che fa riferimento alla tabella di decodifica 104 che contiene i seguenti valori:
1 - Provvedimento 
2 - Convenzione di negoziazione assistita 
3 - Accordo che ha determinato la separazione

Analizzando i campi richiesti nel mapping Sep_Div_002.csv del caso d'uso in oggetto, vengono richiesti i dati del Provvedimento della separazione con la condizione `evento.separazione.tipoProvvedimentoSeparazione,!=,1` mentre i dati Accordo Separazione con `evento.separazione.tipoProvvedimentoSeparazione,=,1`.
Queste condizioni ci sembrano errate (vanno in contrasto con la tabella 104), infatti la validazione dell'evento fallisce se indichiamo tipoProvvedimentoSeparazione=1 e compiliamo i dati del provvedimento. Riceviamo errore di dati obbligatori mancanti perché il sistema richiede invece i dati dell'accordo.

Potete controllare l'idOperazione=1695356 dell'ambiente di pre-prod.

Grazie
Siscom SPA

**Comment by asqueglia** [comment]
Buongionro, le condizioni specificate in documentazione sono condizioni di opzinalità non di obbligatorietà infatti la colonna riporta 'Si puo' ignorare la sezione per'

![image](https://github.com/italia/ansc/assets/29303629/29774f13-f697-434f-b6e3-6082b27a3332)


quindi nello specifico le condizioni da lei indicate vanno interpretate in logica inversa

**Comment by siscomanpr** [comment]
Vero, non avevo notato l'intestazione di colonna.
Resta però il problema che popolando il campo tipoProvvedimentoSeparazione=1 richiede obbligatori i dati dell'atto di accordo.
Potete verificare l'idOperazione 1695356 e farci sapere se sbagliamo qualcosa nella compilazione dei campi?

**Comment by siscomanpr** [comment]
Chiudo la issue perché ho capito dov'era il problema.
