### ISSUE TITLE
Trascr_Matr_001, Trascr_Matr_002, Trascr_Unciv_001. Trascr_Unciv_002: indicazioni su Comune Ente estero

### ISSUE THREAD

**Issue by antonioluberto** [italia/ansc#462]
In tutti i casi d'uso indicati in oggetto è presente il campo:

![image](https://github.com/italia/ansc/assets/26415430/3db6f4d9-976d-4657-92ce-be9f4fef35a6)

per il quale "non" è indicata obbligatorietà.

Tuttavia l'invio di ciascuno dei casi d'uso indicati in oggetto fallisce nel caso in cui non sia valorizzato il Comune medesimo.

Dobbiamo ritenere sia errato il controllo del servizio? Ovvero sia errata la documentazione?

Laddove il dato sia da classificarsi effettivamente come obbligatorio, possiamo valorizzarlo con il Comune estero presso il quale è avvenuto l'evento (Comune che "dovrebbe" coincidere con quello presso il quale sia stato redatto l'atto originale)?

**Comment by asqueglia** [comment]
Buongiorno @antonioluberto , verifichiamo la segnalazione sull'obbligatorietà e le facciamo sapere. Per la domanda si il comune estero è il comune presso cui è avvenuto l'evento

**Comment by asqueglia** [comment]
Buongiorno @antonioluberto abbiamo verificato la documentazione e in effetti il campo comuneEstero è indicato come obbligatorio

![image](https://github.com/italia/ansc/assets/29303629/7ad9f206-2ae9-4bda-bddc-fc8760999c0d)

Quindi ci sembra che corrisponda alla logica implementata. Ci faccia sapere se ci sono problemi

**Comment by antonioluberto** [comment]
Buongiorno.
Gentilmente, un chiarimento ulteriore:
per il campo "Comune estero" è indicato:
- il valore "No" in corrispondenza della colonna C "Obbligatorio"
- il valore "obbligatoria" in corrispondenza della colonna G "Si può ignorare la sezione per"

L'interpretazione che noi abbiamo sempre dato per rappresentazioni di questo tipo è quella per cui certamente è obbligatorio compilare la sezione "Atto da trascrivere", ma all'interno di questa non è obbligatoria la valorizzazione del campo "Comune estero". Se diversamente, l'obbligatorietà del singolo dato è univocamente determinata dalla colonna G "Si può ignorare la sezione per", allora:
a) qual è la funzione della colonna C "Obbligatorio"?
b) con particolare riferimento ai casi d'uso indicati in oggetto, cosa dovremmo riportare, ad esempio, in corrispondenza dei campi
"Provincia ente"
"Provincia ente - Descrizione"
che evidentemente non possono esistere trattandosi di Comune estero?


![image](https://github.com/italia/ansc/assets/26415430/7205101d-49f2-4e10-a15d-dd334aa90aa7)

**Comment by asqueglia** [comment]
Buongionro @antonioluberto, la colonna C si riferisce al singolo campo di una sezione mentre la colonna G all'intera sezione (anche se è ripetuto su tutti i campi della sezione ci si riferisce all'intera sezione); quindi nello specifico la sezione trascrizione è obbligatoria, il campo comuneEstero, in essa contenuto, è non obbligatorio.

**Comment by asqueglia** [comment]
Buongiorno , provvediamo a chiudere la issue. In caso di ulteriori segnalazioni la preghiamo di aprire una altra issue dedicata
