### ISSUE TITLE
Internal server error R009 validazione nascita

### ISSUE THREAD

**Issue by Sem98** [italia/ansc#464]
Buonasera, dopo gli ultimi aggiornamenti inviando il seguente payload il servizio mi risponde con questo errore:{"message":"internal.error","errors":null}. 
Come possiamo risolvere?

{
	"testataRichiesta": {
		"versioneApplicativo": "1.18.0",
		"idOperazioneComune": "441",
		"idComune": 9493,
		"dataOraRichiesta": "2023-11-07T12:08:20.079",
		"nomeApplicativo": "SIDe",
		"fornitoreApplicativo": "SistemiInformativi"
	},
	"evento": {
		"datains": "2023-11-07T12:08:20.079",
		"operatoreNome": "Alessandro",
		"idTipoEvento": "1",
		"dataultimoagg": "2023-11-07T12:08:20.079",
		"composizioneCompleta": "L'anno DUEMILAVENTIDUE addi' TRE del mese di FEBBRAIO alle ore SEDICI e minuti TRENTATRE nella Casa Comunale. Avanti a me, MUNICIPIA ......, Ufficiale dello stato civile del comune di SIENA, DELEGA AVUTA DAL SINDACO. E' comparso PAPINI RICCARDO nato in MONTECATINI-TERME il 22 luglio 1969, residente in SIENA il \nMi ha dichiarato quanto segue:\n Il giorno DUEdel mese di FEBBRAIOdell'anno DUEMILAVENTIDUEalle ore DUEe minuti VENTIDUEnell'Ospedale sito in Viale Mario Bracci n.16 - Siena da MARIA ROSA VELEZ MIRANDA nata in CALI VALLE il 15 agosto 1963 cittadina COLOMBIANA residente in SIENA moglie del dichiarante, cittadino Italiano e' nato un bambino di sesso MASCHILE. A detto bambino che non mi viene presentato, ma della cui nascita mi sono accertato mediante l'attestazione di nascita rilasciata dall'ostetrica ================ assistente al parto il dichiarante da'  il nome di e.  Mi e' stato prodotto il provvedimento del tribunale di =============== in data  n. =============== con il quale ai sensi dell'art.251, secondo comma, del codice civile e' stato autorizzato il riconoscimento del bambino, atto che, munito del mio visto, inserisco nel volume degli allegati a questo registro Il presente atto dopo essere stato letto, viene insieme con me sottoscritto dal dichiarante.",
		"annoAtto": "2022",
		"tipoDichiarante": "1",
		"intestatari": [
			{
				"nomeStatoNascita": "ITALIA",
				"dataNascita": "2022-02-02",
				"idProvinciaNascita": "052",
				"idStatoNascita": "90",
				"cognome": "PAPINI",
				"nomeComuneNascita": "SIENA",
				"documentoRiconoscimento": {},
				"sesso": "M",
				"nome": "GOLOSONE",
				"idComuneNascita": "9493",
				"siglaProvinciaNascita": "SI"
			}
		],
		"allegati": [
			{
				"hashAllegato": "vj+a278ugW6a3b2KRo8Zz26hwWKHZvwwKy65ovmqzpg=",
				"idStatoAllegato": "1",
				"id": "2232197",
				"idTipoAllegato": "998"
			},
			{
				"hashAllegato": "EfdCOsRG47a8HAJpHDCIpDCWoTv6lUXgJfiJdNE/mqk=",
				"idStatoAllegato": "1",
				"id": "2232474",
				"idTipoAllegato": "998"
			}
		],
		"datiDichiarante": {
			"motivoImpedimentoScrittura": "",
			"comprensione": "0"
		},
		"dataDecorrenza": "",
		"stato": "CONFERMATO",
		"padre": {
			"siglaProvinciaResidenza": "SI",
			"nomeStatoNascita": "ITALIA",
			"dataNascita": "1969-07-22",
			"cognome": "PAPINI",
			"nazionalita": "ITALIANA",
			"codiceFiscale": "PPNRCR69L22A561B",
			"idStatoResidenza": "90",
			"idStatoNascita": "90",
			"nomeComuneResidenza": "MONTECATINI-TERME",
			"flagComparente": false,
			"nomeComuneNascita": "MONTECATINI-TERME",
			"flagFirmatario": true,
			"flagDichiarante": true,
			"id": "43500",
			"idComuneNascita": "609",
			"idNazionalita": "11",
			"idProvinciaNascita": "047",
			"indirizzoResidenza": "",
			"idComuneResidenza": "9493",
			"idsoggettoanpr": "265097",
			"idProvinciaResidenza": "052",
			"documentoRiconoscimento": {},
			"nome": "RICCARDO",
			"siglaProvinciaNascita": "PT",
			"nomeStatoResidenza": "ITALIA",
			"sesso": "M"
		},
		"descrizioneCasoUso": "Caso d'uso di servizio dichiarazioni nascita",
		"numeroatto": "22403",
		"ausilioInterprete": "false",
		"operatore": "PTTRNZ66L13C661Y",
		"dataformazione": "2022-02-02",
		"ora": "02",
		"minuto": "22",
		"operatoreCognome": "Ghinelli",
		"datiDiNascita": {
			"sceltaCognome": "3",
			"minutoNascita": "22",
			"natoVivoMaDeceduto": "NO",
			"luogoFiliazione": "",
			"oraNascita": "02",
			"natoMorto": "NO",
			"tipoAccertamento": "1",
			"precisazioneCognome": ""
		},
		"idComuneRegistrazione": "9493",
		"madre": {
			"siglaProvinciaResidenza": "SI",
			"nomeStatoNascita": "ITALIA",
			"dataNascita": "1963-08-15",
			"cognome": "VELEZ MIRANDA",
			"nazionalita": "ITALIANA",
			"codiceFiscale": "VLZMRS63M55Z604D",
			"idStatoResidenza": "90",
			"idStatoNascita": "90",
			"nomeComuneResidenza": "SIENA",
			"flagComparente": false,
			"nomeComuneNascita": "CALI VALLE",
			"flagFirmatario": false,
			"flagDichiarante": false,
			"id": "45686",
			"idComuneNascita": "9493",
			"idNazionalita": "11",
			"idProvinciaNascita": "052",
			"indirizzoResidenza": "",
			"idComuneResidenza": "9493",
			"idsoggettoanpr": "266044",
			"idProvinciaResidenza": "052",
			"documentoRiconoscimento": {},
			"nome": "MARIA ROSA",
			"siglaProvinciaNascita": "SI",
			"nomeStatoResidenza": "ITALIA",
			"sesso": "F"
		},
		"idUsecase": "11999999",
		"idProvinciaRegistrazione": "052",
		"siglaProvinciaRegistrazione": "SI",
		"idtipocontenuto": "1",
		"redattoNellaCasaComunale": true,
		"ruoloOperatore": "1",
		"nomeComuneRegistrazione": "SIENA"
	}
}

**Comment by mttfranci** [comment]
State provando in preproduzione e/o produzione?

Saluti

Assistenza ANSC

**Comment by Sem98** [comment]
Buonasera, stiamo provando in preproduzione

**Comment by Sem98** [comment]
Buonasera, abbiamo apena riprovato e adesso non risponde pù con errore  500 {"message":"internal.error","errors":null} ma con:

400
{"testataRisposta":{"idComune":9493,"idOperazioneComune":"449","idOperazione":"1696254"},"errors":[{"code":"400307","severity":"E","text":"idVersion non valida: scaduta"}]}

**Comment by mttfranci** [comment]
@Sem98  per gli errori 500 che sono capitati in alcuni momenti stiamo verificando (da tenere presente che in generale l'affidabilità dell'ambiente di preproduzione non è la stessa di produzione).

Per l'errore 400 in realtà dal 3 novembre sono stati deprecate le versioni che hanno superato i 3 mesi : 
https://github.com/italia/ansc/blob/main/docs/Decodifiche/100_dec_versione.csv

Quindi andrebbe passata esplicitamente una versione valida (al momento l'ultima è la 100005)

Saluti

Assistenza ANSC

**Comment by Sem98** [comment]
Ciao grazie per la risposta, ho provato a fare un test con questo endpoint: "https://anscservicepre.anpr.interno.it/services/service/val/validazione/evento/100005" ma mi risponde con errore 400 e con questo messaggio:
{"testataRisposta":{"idOperazione":"1696579"},"errors":[{"code":"400000","severity":"E","text":"Parametro version non valido, (le versioni accettate sono : '1')"}]}

**Comment by mttfranci** [comment]
@Sem98  allora, in realtà abbiamo due versionamenti, uno è quello generale del sistema, e corrisponde alla Major Version di ANSC, quindi '1' al momento. Pertanto va invocata sempre l'endpoint : 

/services/service/val/validazione/evento/1

Preso in particolare dal servizio di validazione e che fa parte del payload e che va indicato espressamente nell'oggetto 'evento' : 

```
{
"testataRichiesta": {
"versioneApplicativo": "1.18.0",
"idOperazioneComune": "441",
"idComune": 9493,
"dataOraRichiesta": "2023-11-07T12:08:20.079",
"nomeApplicativo": "SIDe",
"fornitoreApplicativo": "SistemiInformativi"
},
"evento": {
"idVersion": 100005,
"datains": "2023-11-07T12:08:20.079",
[...]
```

Potete fare riferimento alla definizione del modello dell' [evento](https://github.com/italia/ansc/blob/main/docs/openapi/model_evento.yaml) : 

```
        idVersion:
          type: string
          description: Id della versione utilizzato per la creazione dell'evento (decodifica ANSC_100)
```

Siamo a disposizione per qualsiasi chiarimento.

Saluti

Assistenza ANSC

**Comment by Sem98** [comment]
Grazie per la spiegazione, siamo riusciti a risolvere l'errore sull'id version tuttavia ricompare l'errore 500 {"message":"internal.error","errors":null}. 
Rimaniamo in attesa per la risoluzione del problema.
