### ISSUE TITLE
[R013] problema invio annotazioni - Internal server error

### ISSUE THREAD

**Issue by LoreL56** [italia/ansc#466]
Buongiorno,
Provando ad inviare un'annotazione per rettifica il servizio R013 ritorna un errore non gestito. (500)

Ambiente - **Preproduzione**
Data - 8/11/2023

E' possibile che l'errore sia correlato alla issue #458  (anche questa restituisce errore 500)

Dato che l'errore 500 non ritorna una risposta gestita non posso fornirvi il codice della risposta.
Tuttavia ho quello della richiesta: 
"idOperazioneComune":"2792e4fb-c125-497e-8fde-3356235ddf74"

Grazie

**Comment by mttfranci** [comment]
@LoreL56  abbiamo provato a fare un tuning delle risorse intorno alle 12.00 potreste riprovare?
Grazie in anticipo.

**Comment by LoreL56** [comment]
Grazie al momento sembra funzionare!

**Comment by mttfranci** [comment]
Grazie del riscontro, chiudiamo questa issue e usiamo solo la #458 per monitorare la questione ancora un pò.
Saluti
