### ISSUE TITLE
caso 1322 (trascr_024) Trascrizione della sentenza straniera di dichiarazione giudiziale di paternità richiesta dall’interessato

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#467]
Buongiorno,
vi chiedo una curiosità che mi è sorta provando questa casistica sulla webapp (id bozza 1213161).
Alcuni dati del padre sono obbligatori da introdurre ma non compaiono nel testo dell'atto.
La mia curiosità è questa: se sbaglio uno dei dati del Padre e me ne accorgo dopo aver finito tutto l'iter (per esser precisi dopo l'invio firma Ufficiale s.c.), che succede? 
Devo comunicare ad ANSC in qualche modo anche se sono dati che non compaiono nel testo dell'atto e nemmeno serviranno per una certificazione?
Grazie

**Comment by asqueglia** [comment]
Buongiorno, la rappresentazione digitale dell'evento registrato comprende la minuta dell'atto e tutti i metadati spacchettati richiesti; l'estratto per copia integrale infatti, riporta tutto ciò che viene acquisito e firmato. Nel caso specifico se viene richiesto il padre, sebbene non risulti nella minuta, è perchè l'informazione è utilizzata  nell' annotazione automaticamente generata oppure in caso di certificato con menzione paternità/maternità. 
Nel caso quindi ci si sbaglia sullle generalità del padre, è necessario registrare una annotazione correttiva per correggere l'errore

**Comment by annamaraspin** [comment]
Giusto, scusi del disturbo: mi ero scordata della paternità/maternità nei certificati.
Grazie

**Comment by asqueglia** [comment]
Chiudiamo pertanto la issue. Le chiediamo di aprirne una altra dedicata in caso di ulteriori chiarimenti
