### ISSUE TITLE
Caso d'uso 342000-accordo di scioglimento (Sep_Div_002)

### ISSUE THREAD

**Issue by KibMcris** [italia/ansc#468]
Per il caso d'uso in oggetto, con la nuova versione 1.18 è stato introdotto il nuovo campo tipoProvvedimentoSeparazione che fa riferimento alla tabella di decodifica 104.

Nel mapping Sep_Div_002.csv del caso d'uso in oggetto, vengono richiesti i dati del Provvedimento della separazione con la condizione evento.separazione.tipoProvvedimentoSeparazione=1 mentre i dati Accordo Separazione con evento.separazione.tipoProvvedimentoSeparazione,!=,1.

Pur seguendo questa la validazione dell'evento fallisce se indichiamo tipoProvvedimentoSeparazione=1 e compiliamo i dati del provvedimento.
Infatti, vengono richiesti obbligatori comunque i dati dell'accordo.

I riferimenti della request in ambiente di pre-produzione sono:
`		"idComune": 10288,
		"idOperazioneComune": 12,
		"dataOraRichiesta": "2023-11-08 17:30:38",`

Mentre la response in pre-produzione di ANSC è 

`{"testataRisposta":{"idComune":10288,"idOperazioneComune":"12","idOperazione":"1697280","idEsito":1},"errors":[{"code":"400003","severity":"E","text":"Il campo evento.separazione.accordoSeparazione.idProvinciaRegistrazione nella sezione Accordo Separazione è obbligatorio"},{"code":"400003","severity":"E","text":"Il campo evento.separazione.accordoSeparazione.siglaProvinciaRegistrazione nella sezione Accordo Separazione è obbligatorio"},{"code":"400003","severity":"E","text":"Il campo evento.separazione.accordoSeparazione.idComuneRegistrazione nella sezione Accordo Separazione è obbligatorio"},{"code":"400003","severity":"E","text":"Il campo evento.separazione.accordoSeparazione.nomeComuneRegistrazione nella sezione Accordo Separazione è obbligatorio"},{"code":"400003","severity":"E","text":"Il campo evento.separazione.accordoSeparazione.idtipocontenuto nella sezione Accordo Separazione è obbligatorio"},{"code":"400003","severity":"E","text":"Il campo evento.separazione.accordoSeparazione.numeroatto nella sezione Accordo Separazione è obbligatorio"},{"code":"400003","severity":"E","text":"Il campo evento.separazione.accordoSeparazione.annoAtto nella sezione Accordo Separazione è obbligatorio"},{"code":"400003","severity":"E","text":"Il campo evento.separazione.accordoSeparazione.tipologia nella sezione Accordo Separazione è obbligatorio"}]}`

Restiamo in attesa di un riscontro

**Comment by asqueglia** [comment]
Buongionro , verifichiamo e le facciamo sapere

**Comment by asqueglia** [comment]
Buongiorno abbiamo verificato la richiesta da voi trasmessa e abbiamo notato che trasmettete il campo "tipoAccordo": "3", ossia 3=Accordo che ha determinato la separazione e la sezione provvedimentoSeparazione ; in tal caso è corretto l'errore che richiede venga trasmesso un accordo di separazione e non un provvedimentoSeparazione.

**Comment by KibMcris** [comment]
Buongiorno @asqueglia , grazie per il chiarimento.
Facciamo le opportune verifiche del caso.
Chiudo la issue

**Comment by KibMcris** [comment]
Buongiorno @asqueglia , abbiamo fatto anche noi le verifiche del caso.
Abbiamo notato che, da documentazione del caso d'uso, il tipoAccordo è un dato obbligatorio. Come riportato nel file model_evento.yaml, nel ModelSeparazione il campo TipoAccordo deve essere decodificato con la tabella 53 di ANSC.
Controllando la tabella, abbiamo notato che le valorizzazioni fanno riferimenti agli accordi consensuali e non giudiziali. 
Infatti, noi interpretiamo che il TipoAccordo faccia riferimento alla tipologia di accordo di cessazione/scioglimento del matrimonio che viene gestito con l'atto in redazione.
Restiamo in attesa di riscontro
Buona giornata

**Comment by asqueglia** [comment]
Buongiorno, facciamo una verifica sulla obbligatorietà di tipoAccordo. Nella risposta che avevo dato prima, mi riferivo al campo tipoProccedimentoSeparazione, che come condiviso, implica la presenza o meno della sezione accordo piuttosto che della sezione provvedimento.

**Comment by asqueglia** [comment]
Buongiorno, di seguito le verifiche effettuate

Il tipoAccordo ci sembra essere obbligatorio ai fini di una corretta composizione della formula 121-quater. 
Questo campo è associato alla decodifica ANSC_53, ma per il caso d'uso SEP_DIV_002 viene preso in considerazione il sottoinsieme:
2 = Accordo di scioglimento del matrimonio
3 = Cessazione degli effetti civili

Seguendo quanto indicato sulla formula, tipoAccordo e tipoProvvedimentoSeparazione sono due valori che "controllano" due parti differenti e scollegate della formula;

Aggiungo quanto riportato sul formulario, in grassetto le parti condizionate dal **tipoAccordo**: ed in corsivo le parti condizionate dal _tipoProvvedimentoSeparazione_ :
"Oggi ... avanti a me ..........., Ufficiale dello stato civile del Comune di ..., ... (indicare se nella funzione di sindaco o di chi lo sostituisce o per delega avuta), sono comparsi i coniugi ... ... (indicare le complete generalità del primo coniuge), con l'assistenza dell'avvocato ... (indicare le generalità dell'avvocato, se presente per assistere la parte), e ... ... (indicare le complete generalità del secondo coniuge), con l'assistenza dell'avvocato ... (indicare le generalità dell'avvocato, se presente per assistere la parte, anche se è lo stesso dell'altra parte), i quali mi dichiarano: 
- di avere contratto matrimonio in data ..., in ........, dinanzi a ..., di cui all'atto iscritto/trascritto nei registri dello stato civile del Comune di ..., n... parte ... serie .... anno .....); 
- di essere/non essere parti in giudizio pendente, concernente **lo scioglimento (o la cessazione degli effetti civili)** del matrimonio tra gli stessi (in caso affermativo, indicare l'autorità giudiziaria); - di essere legalmente separati a seguito di ... _(indicare il provvedimento/la convenzione di negoziazione assistita/l'accordo che ha determinato la separazione, con tutti i dati per identificarlo)_ e di trovarsi in uno dei casi di cui all'articolo 3, primo comma, numero 2), lettera b), legge 10 dicembre 1970, n. 898; 
- di non essere genitori di figli minori; 
- di non essere genitori di figli maggiorenni incapaci; 
- di non essere genitori di figli maggiorenni portatori di handicap grave ai sensi dell'articolo 3, comma 3, della legge 5 febbraio 1992, n. 104; 
- di non essere genitori di figli maggiorenni economicamente non autosufficienti; - di non concordare tra di loro alcun patto di trasferimento patrimoniale; - **di volere lo scioglimento (o la cessazione degli effetti civili) del matrimonio.** 
A tal fine mi hanno prodotto i seguenti documenti: (elencarli) che, muniti del mio visto, inserisco nel volume degli allegati a questo registro. 
Ho invitato le parti a comparire nuovamente davanti a questo Ufficio per la conferma dell'accordo nel giorno .... (indicare una data non inferiore a trenta giorni da quella dell'accordo) e li ho informati che la mancata comparizione equivale a mancata conferma dell'accordo. 
Il presente atto viene letto ai dichiaranti i quali, insieme con me e con gli avvocati presenti per assisterli, lo sottoscrivono. `(1)"`


Fateci sapere in caso abbiamo inteso male.

**Comment by KibMcris** [comment]
Buongiorno @asqueglia, esatto sono d'accordo che il tipoAccordo ed il TipoProvvedimentoSeparazione controllano due formule diverse dell'atto.
Continuo però a non capire l'errore che segnala ANSC quando valorizziamo TipoProvvedimentoSeparazione=1. Infatti, anche con IDOperazioneComune=12 e IdOperazione ANSC=1700802, stiamo tentando di registrare un evento riferito al caso d'uso in oggetto in cui valorizziamo tipoAccordo=3 e tipoProvvedimentoTribunale=1, che come da voi indicato sono due oggetti che controllano due formule diverse.
Continuiamo ad ottenere in risposta:
`{"testataRisposta":{"idComune":10288,"idOperazioneComune":"12","idOperazione":"1700802","idEsito":1},"errors":[{"code":"400003","severity":"E","text":"Il campo evento.separazione.accordoSeparazione.idProvinciaRegistrazione nella sezione Accordo Separazione è obbligatorio"},{"code":"400003","severity":"E","text":"Il campo evento.separazione.accordoSeparazione.siglaProvinciaRegistrazione nella sezione Accordo Separazione è obbligatorio"},{"code":"400003","severity":"E","text":"Il campo evento.separazione.accordoSeparazione.idComuneRegistrazione nella sezione Accordo Separazione è obbligatorio"},{"code":"400003","severity":"E","text":"Il campo evento.separazione.accordoSeparazione.nomeComuneRegistrazione nella sezione Accordo Separazione è obbligatorio"},{"code":"400003","severity":"E","text":"Il campo evento.separazione.accordoSeparazione.idtipocontenuto nella sezione Accordo Separazione è obbligatorio"},{"code":"400003","severity":"E","text":"Il campo evento.separazione.accordoSeparazione.numeroatto nella sezione Accordo Separazione è obbligatorio"},{"code":"400003","severity":"E","text":"Il campo evento.separazione.accordoSeparazione.annoAtto nella sezione Accordo Separazione è obbligatorio"},{"code":"400003","severity":"E","text":"Il campo evento.separazione.accordoSeparazione.dataformazione nella sezione Accordo Separazione è obbligatorio"},{"code":"400003","severity":"E","text":"Il campo evento.separazione.accordoSeparazione.tipologia nella sezione Accordo Separazione è obbligatorio"}]}`

Se necessario posso fornire anche la request effettuata.
Grazie

**Comment by gcuci** [comment]
buongiorno,

anche noi avevamo segnalato l'anomalia dell'accordoSeparazione richiesto obbligatoriamente anche con 'tipoProvvedimentoSeparazione' = '1'.

Per noi si è risolto, passando 'idVersion' = '100005' (versione dalla quale è stata introdotta la proprietà tipoProvvedimentoSeparazione). Con questa versione, e con 'tipoProvvedimentoSeparazione' = '1', l'obbligatorietà è sul 'provvedimentoSeparazione', come indicato nel file di mapping.

Consideriamo quindi risolta la nostra richiesta.


Grazie.

**Comment by KibMcris** [comment]
Confermo che anche noi abbiamo risolto passando ad idVersion=100005.
Chiudo la issue e ringrazio per il supporto.
