### ISSUE TITLE
Dati notifica ANPR collegata ad evento ANSC

### ISSUE THREAD

**Issue by antonioluberto** [italia/ansc#470]
Come condiviso nel corso degli ultimi incontri, è certamente necessario che l'ufficiale di stato civile del Comune attivo in ANSC abbia riscontro certo circa la notifica ANPR che un proprio atto (ovvero che una propria annotazione) abbia determinato.
Al momento, il servizio R008 prevede si possano richiedere informazioni relative alle notifiche ANPR collegate a specifico evento di stato civile

![image](https://github.com/italia/ansc/assets/26415430/a5a76361-4c0d-40ba-b1e9-ecee1ae5eefa)
 
restituendo, però, al servizio chiamante:

![image](https://github.com/italia/ansc/assets/26415430/2dffa5d2-aa20-4ad6-b93c-c426ef1ba391)

![image](https://github.com/italia/ansc/assets/26415430/f22f76af-51ff-41f4-8b2e-846ae90ee553)

e, quindi, il solo "id" della notifica ANPR.
Questo dato, da solo, non è evidentemente significativo per l'ufficiale di stato civile.
All'usc occorrono gli estremi complessivi della notifica medesima:
a) quando sia stata generata
b) quale ne sia la tipologia ed il contenuto
c) quale sia il comune al quale sia stata inoltrata per competenza 
d) in quale data sia avvenuto l'inoltro

Non ci pare ci sia al momento un modo per ottenere le informazioni di cui ai punti a), b), c), d).

Rimaniamo in attesa di vostro riscontro in merito.

**Comment by mttfranci** [comment]
Salve.

Stiamo valutando la vostra richiesta.
Una precisazione sulla data di inoltro, al momento tali notifiche, una volta generate, sono subito consumabili dal comune destintario con una richiesta 4005, ma non c'è un vero e proprio inoltro.
Invece il contenuto intendete la tipologia oppure l'effettivo contenuto informativo inviato?

Saluti

Assistenza ANSC

**Comment by mttfranci** [comment]
L'esigenza è chiara.
Stiamo valutando se è possibile procedere in tal senso.
Saluti

Assistenza ANSC

**Comment by asqueglia** [comment]
Buongiorno la segnalazione è stata corretta con il rilascio odierno della versione 1.30.0
