### ISSUE TITLE
Differenziazione notifiche di tipo "annotazione"

### ISSUE THREAD

**Issue by antonioluberto** [italia/ansc#472]
A seguito delle indicazioni ottenute in risposta alla https://github.com/italia/ansc/issues/410 chiediamo che, per notifica di tipo "annotazione", sia possibile distinguere:

a) se si tratti di notifica confermando la quale il Comune Gestore conferma l'apposizione di annotazione digitale su atto digitale di propria competenza (annotazione originata dalla conferma di altro atto digitale da parte di altro Comune in ANSC)

oppure

b) se si tratti di notifica confermando la quale il Comune Gestore conferma che un _Comune terzo_ abbia apposto _annotazione_ su atto che si trovi presso il _Comune terzo_ medesimo e per il quale la necessita della aspecifica _annotazione_ sia determinata da atto digitale prodotto dal Comune Gestore
 
Ci pare che tale distinzione non sia disponibile e ne chiediamo l'implementazione in maniera tale che:
1) alla conferma di notifica che rientri nella classificazione di cui al punto a), si possa aggiornare l'archivio locale con i dati dell'annotazione; il tutto per garantire quindi che non si interrompa l'allineamento fra ANSC e la base dati comunale (di servizio), secondo principio condiviso sin dall'avvio del progetto

2) si possano isolare applicativamente le due tipologie di notifiche e rendere disponibile all'utente strumenti di controllo/monitoraggio distinti e specifici , in particolare per quanto relativo alle notifiche ANPR originate nei due casi.

**Comment by mttfranci** [comment]
Stiamo valutando la vostra segnalazione.

Saluti

AAssistenza ANSC
