### ISSUE TITLE
[WebApp] e [WebService] - errore firma elettronica officiante

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#473]
Atto di matrimonio con IdEvento=1213459.

Al momento in cui seleziono il tipo di firma per tutti i soggetti firmatari (di cui 4 cartacei e 1 elettronico), il sistema va in crash:

![image](https://github.com/italia/ansc/assets/131870281/3c1bfa06-fb43-45b2-abe3-899e4a73f2f8)

con il seguente messaggio di errore:

![image](https://github.com/italia/ansc/assets/131870281/67ed278c-30ce-4860-89a7-63126acc3d38)

**Comment by biadanpad** [comment]
facendo ulteriori test, il problema deriva dal fatto che per l'officiante di matrimonio è stato selezionato il tipo di firma elettronico.

Lo stesso problema lo abbiamo riscontrato anche lato WebServices: al momento in cui si invia la mail per la fìrma elettronica all'officiante il sistema restituisce il seguente errore:

REQUEST: {
    "emailDichiarante": "andrea.cangi@padigitale.it",
    "idEvento": "1213453",
    "idAnsc": "2023-1213453-16-108028",
    "firmatario": {
        "cognome": "",
        "nome": ""
    },
    "testataRichiesta": {
        "idComune": 5000,
        "idOperazioneComune": "4352",
        "dataOraRichiesta": "2023-11-10T16:21:30.516+01:00",
        "nomeApplicativo": "urbi",
        "versioneApplicativo": "0.1.0",
        "fornitoreApplicativo": "padigitale"
    }
}

RESPONSE: {
    "errors": [{
            "code": "400002",
            "severity": "E",
            "text": "Soggetto firmatario non inserito correttamente"
        }
    ],
    "esito": {
        "codice": "400002",
        "descrizione": "Dati in ingresso non completi"
    },
    "testataRisposta": {
        "idComune": 5000,
        "idEsito": 1,
        "idOperazioneComune": "4352"
    }
}

**Comment by mttfranci** [comment]
Stiamo verificando la segnalazione

Saluti

Assistenza ANSC

**Comment by mttfranci** [comment]
Buongiorno @biadanpad 

Per quanto cencerne il servizio per il firmatario andrebbero indicati almeno il codice fiscale o nome e cognome. (il valore vuote non è sufficiente in questo caso). Questo il motivo del messaggio "Soggetto firmatario non inserito correttamente".

Per la web application stiamo ancora verificando.

Saluti

**Comment by biadanpad** [comment]
Grazie per le indicazioni riguardo il WebService. Rimettendo apposto i parametri funziona

**Comment by asqueglia** [comment]
Buongiorno, provvediamo a chiudere la issue. In caso di ulteriori segnalazioni la preghiamo di aprire una altra issue dedicata
