### ISSUE TITLE
[R006] Errore corrispondenza firmatari

### ISSUE THREAD

**Issue by DiBellaDavide** [italia/ansc#475]
Salve,
stiamo provando a far firmare tramite firma autografa dei componenti dell'atto per il caso d'uso Matr_001 senza successo. A quanto pare l'errore restituito indica la mancata corrispondenza di uno o più firmatari della lista. Abbiamo ricontrollato i dati della validazione (correttamente effettuata tramite servizio R009) e i dati inviati al servizio di firma R006 e ci viene restituito:
` 400003 : Non è stata trovata corrispondenza per uno o più firmatari nella lista, assicurasi di aver inserito solo i parametri forniti in validazione`
Potreste indicarci se ci sono errori o se si tratta di un bug?

**idOperazione R009 :** 1699737
**idOperazione R006:** 1699775

**Comment by asqueglia** [comment]
Buongiorno stiamo verificando. Appena possibile le faremo sapere

**Comment by amusarra** [comment]
Buongiorno.
Come indicato nel [Changelog(https://github.com/italia/ansc/blob/main/docs/Changelog.md#1152---23-10-2023) della versione 1.15.2, è necessario passare i dati del firmatario indicati in fase di validazione; si prega pertanto di apportare le modifiche al payload e risottomettere la richiesta.

Nel caso di esito positivo vi chiediamo di chiudere la issue.

Grazie.
Supporto ANSC.

**Comment by asqueglia** [comment]
Buongiorno abbiamo verificato la richiesta inviata; nello specifico per il servizio R006 di firma dichiarante, avete inviato una anagrafica non completa dei soggetti firmatari. Riporto quanto descritto nel changelog relativo alla versione 1.15.2 del 23-10-2023, 

_**R006 firma dichiarante con lista firmatari: il servizio richiede necessariamente i dati anagrafici  con cui il soggetto è stato registrato (es. se il coniuge è stato registrato con nome, cognome, sesso e data di nascita, questi campi devono essere trasmessi anche nel servizio R006; se l'officiante è stato registrato solo con nome e cognome, il servizio R006 dovrà essere invocato tramsettendo solo nome e cognome)**_
	
Si richiede pertanto di riprovare trasmettendo tutti i dati anagrafici dei soggetti firmatari, trasmessi durante la registrazione dell'evento con il servizio R009.

**Comment by DiBellaDavide** [comment]
Salve, abbiamo integrato i dati come da voi suggerito, adesso tutto funziona correttamente, chiudo la issue. Grazie mille!
