### ISSUE TITLE
[R010] - anteprima per presa visione - Caso d'uso 348000 - errore Use Case non valido

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#479]
Tentando di generare l'anteprima per presa visione viene restituito l'errore in oggetto

REQUEST:
{
    "presaVisione": true,
    "evento": {
        "idAnsc": "2023-1213696-188-108028",
        "idVersion": "100005",
        "operatore": "DLCNTN57L67A064W",
        "operatoreNome": "MARGHERITA",
        "operatoreCognome": "CITTERIO"
    },
    "testataRichiesta": {
        "idComune": 5000,
        "idOperazioneComune": "4349",
        "dataOraRichiesta": "2023-11-14T16:28:08.769+01:00",
        "nomeApplicativo": "urbi",
        "versioneApplicativo": "0.1.0",
        "fornitoreApplicativo": "padigitale"
    }
}

RESPONSE:
{
    "testataRisposta": {
        "idComune": 5000,
        "idOperazioneComune": "4349",
        "idOperazione": "1700811",
        "idEsito": 1
    },
    "errors": [{
            "code": "400001",
            "severity": "E",
            "text": "Use Case non valido"
        }
    ]
}

**Comment by amusarra** [comment]
Salve @biadanpad 
Abbiamo preso in carico la sua segnalazione.

Cordiali Saluti.
Supporto ANSC.

**Comment by amusarra** [comment]
Salve @biadanpad 
Il problema dovrebbe essere rientrato. Potreste riprovare?

Cordiali Saluti.
Supporto ANSC.

**Comment by biadanpad** [comment]
Buonasera, 
confermo che adesso funziona.
