### ISSUE TITLE
[ws R008] Notifiche ANSC che non sono arrivate

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/ansc#480]
ambiente PROD - comune di Valeggio sul Mincio (idComune 10420)

segnalo che non sono arrivate le notifiche ANSC per i seguenti atti:
- nascita: 2023-108-2-023089, 2023-132-3-023089, 2023-133-4-023089
si tratta di tutti casi d'uso 1311 (Trascrizione di nascita: Trascrizione di atto di nascita avvenuta all'estero su richiesta dell'autorita' diplomatica o consolare)
a parità di caso d'uso, per l'atto 2023-3-1-023089 invece la notifica di tipo "trascrizione" è arrivata
- matrimonio: 2023-144-5-023089
si tratta di un caso d'uso 332000 (Trascrizione matrimoni dall'estero - richiesta di trascrizione da parte del Consolato/Ambasciata)

vi chiedo di verificare.

ovviamente la mancanza della notifica ANSC pregiudica la produzione della corrispondente notifica ANPR.

grazie
Alessandro ADS

**Comment by gbuemi** [comment]
Abbiamo preso in carico la vostra segnalazione.

Saluti
Assistenza ANSC

**Comment by AMonopoliADS** [comment]
buongiorno

per ulteriori accertamenti (e per non inserire nuova issue), indico la lista degli atti del comune di San Lazzaro di Savena (idComune 8647) per i quali abbiamo riscontrato la stessa problematica (notifica ansc non pervenuta):
atto N. 2023-106-6-037054 (2102 - Dichiarazione di morte: Decesso in ospedale o casa di cura)
atto N. 2023-290-25-037054 (2102 - Dichiarazione di morte: Decesso in ospedale o casa di cura)
atto N. 2023-323-31-037054 (2101 - Dichiarazione di morte: Decesso in abitazione o in luogo pubblico)
atto N. 2023-110-7-037054 (343000 - Separazioni e divorzi: Conferma di accordo di separazione o divorzio)

grazie
Alessandro ADS

**Comment by gbuemi** [comment]
Buongiorno, 
prendiamo in carico anche questi altri casi.

Grazie e saluti
Assistenza ANSC

**Comment by gbuemi** [comment]
Buongiorno,
comunichiamo che le notifiche ANPR per gli 8 atti segnalati sono state generate.

Saluti
Assistenza ANSC

**Comment by asqueglia** [comment]
Buongiorno, necessitiamo di ulteriori approfondimenti circa il trattamento dei soggetti aire; al momento il servizio di registrazione evento non prevede di acquisire l'informazione del comune aire di iscrizione fondamentale per l'invio corretto delle notifiche anagrafiche.
Appena abbiamo riscontri in merito le faremo sapere.

**Comment by AMonopoliADS** [comment]
grazie @asqueglia  per questa integrazione.
sottolineo però che in questo caso il problema segnalato riguarda unicamente le notifiche ANSC (che non mi risulta siano ancora arrivate).

ho fatto caso solo adesso che @gbuemi nella sua risposta si riferisce alle notifiche ANPR.
per queste ultime ci aspettiamo di riceverle - a conferma di notifica ANSC avvenuta - solo per i comuni in ANSC.

grazie

**Comment by asqueglia** [comment]
Le notifiche lato ANSC per gli eventi indicati ci risultano correttamente generate ed approvate. Pertanto chiudiamo la issue; in caso di malfunzionamenti si prega di aprirne una altra dedicata.
