### ISSUE TITLE
[ws R010] Anteprima: segnalazioni in merito alle diciture riportate nel documento

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/ansc#481]
come d'accordo, riepilogo quanto condiviso verbalmente in occasione della call di ieri.

nei documenti di anteprima compaiono alternativamente queste due diciture:
- "questo documento è emesso solamente allo scopo di presa visione"
- "questo documento sarà digitalizzato"

dall'esperienza fatta fino ad oggi, non è chiaro quali circostanze producano l'indicazione di una dicitura o dell'altra, e ci si chiede perché l'indicazione che l'atto "sarà digitalizzato" non valga per tutti gli atti in generale.

faccio alcuni esempi pratici per cercare di spiegarmi meglio e permettere a voi di fare le verifiche del caso:
1.1. atto N. 2023-320-8-023089 (311111 - Dichiarazione: Matrimonio con Rito Civile nella casa comunale)
sono presenti i firmatari "per presa visione", lo spazio per le firme dei dichiaranti, e la dicitura "questo documento sarà digitalizzato"
1.2. atto N. 2023-276-9-023089 (11213000 - Dichiarazione nascita: Dichiarazione nei termini di filiazione fuori dal matrimonio resa all'USC dal padre con presenza madre)
sono presenti i firmatari "per presa visione", lo spazio per le firme dei dichiaranti, e la dicitura "questo documento è emesso solamente allo scopo di presa visione". cosa cambia rispetto all'esempio numero '1.', per cui non è presente la dicitura che "questo documento verrà digitalizzato"? 
1.3. atto N. 2023-403-17-023089 (1314 - Trascrizione di nascita: Trascrizione atto di nascita resa alla direzione sanitaria)
NON sono presenti firmatari "per presa visione", ma è presente la dicitura "questo documento è emesso solamente allo scopo di presa visione".

altre segnalazioni, sempre collegate al documento di anteprima:
2.1. atto N. 2023-320-8-023089 (311111 - Dichiarazione: Matrimonio con Rito Civile nella casa comunale)
l'atto prevede 5 firmatari in quest'ordine: i 2 sposi, l'officiante e i 2 testimoni
ci si chiede se questo ordine sia voluto, perché invece ci si aspetta che l'officiante sia l'ultimo a firmare.
2.2. atto N. 2023-351-10-023089 (331000 - Trascrizione matrimoni dall'estero - richiesta di trascrizione da parte dell'interessato)
compare la dicitura "questo documento sarà digitalizzato" e l'indicazione della firma dell'ufficiale dello stato civile, come se dovesse firmare autografo
![image](https://github.com/italia/ansc/assets/26788199/203791d9-0828-42f9-8b00-e44f7da46881)
2.3 in generale, come condiviso al tavolo, si chiede più spazio tra un nominativo e l'altro, nel punto del documento in cui le persone devono firmare.
2.4 ultimo: è stato richiesto di togliere l'indicazione di data e ora dal riepilogo dei firmatari per presa visione.

grazie
Alessandro ADS

**Comment by mttfranci** [comment]
@AMonopoliADS sulla prima richiesta, dai tavoli di analisi e condivisione era emerso di usare la dicitura "questo documento sarà digitalizzato" solo per i matirmoni.

Per gli altri punti li abbiamo inseriti nella coda di lavorazione.

Saluti

Assistenza ANSC

**Comment by mttfranci** [comment]
Salve @AMonopoliADS con la patch 1.19.1 abbiamo rimosso la data e ora dal riepilogo firmatari per presa visione.

Saluti
