### ISSUE TITLE
[R009 - R013] Timeout servizi

### ISSUE THREAD

**Issue by DiBellaDavide** [italia/ansc#483]
Salve,
stiamo riscontrando problemi di timeout nei servizi R009 e R013.
Attendo vostre notizie,
distinti saluti.

**Comment by mttfranci** [comment]
@DiBellaDavide  potreste riprovare?
Grazie in anticipo.

**Comment by DiBellaDavide** [comment]
@mttfranci purtroppo riscontriamo ancora lo stesso messaggio d'errore. I test sono stati effettuati in questo modo:
- R009 idVersion: 100006 
- R013 idVersion: 100004

**Comment by mttfranci** [comment]
Ci dispiace per il problema, potreste provare nuovamente?
Grazie in anticipo.

Saluti

Assistenza ANSC

**Comment by DiBellaDavide** [comment]
Buongiorno, dai primi test effettuati stamattina non sembrano essere emerse irregolarità, le richieste partono correttamente.
Grazie mille, chiudo la issue.

**Comment by mttfranci** [comment]
Grazie a voi @DiBellaDavide 
Buona giornata.
