### ISSUE TITLE
[R013] - Errore 500 per invio di annotazioni di rettifica per ANNULLAMENTO atto

### ISSUE THREAD

**Issue by LoreL56** [italia/ansc#484]
[Ambiente] = PREPROD
[IdOperazione] = 1702967

Buongiorno,

stavamo provando a creare un'annotazione che permetta l'annullamento dell'atto a cui si riferisce.
Per farlo abbiamo seguito le indicazioni presenti sul documento NotaProcessoAnnotazioniAndQuickCoopServiceFlow.pdf

Per cui, rispetto alle altre annotazioni di rettifica

1. Il tipo IdTipoRettifica è impostato a "0"
2. Non è presente la sezione evento modificato (ma abbiamo anche provato ad includerlo in alcune prove - senza notare differenze)
3. I campi dell'ente dichiarante sono popolati (come per le altre annotazioni di rettifica che mandiamo correttamente).

La risposta è sempre un errore 500.

Volevamo capire se c'era un problema con la costruzione della richiesta, oppure se è un problema applicativo.

Grazie 

L

**Comment by gbuemi** [comment]
Buongiorno,
la request inviata sembra coerente e sui nostri ambienti non risultano anomalie. Vi invitiamo ad effettuare un nuovo test, negli ultimi giorni sono stati effettuati dei rilasci.

Grazie e saluti
Assistenza ANSC
