### ISSUE TITLE
Errore di connessione - Richiesta fallita codice errore 504

### ISSUE THREAD

**Issue by ServiziDemograficiCori** [italia/ansc#485]
Ho iniziato ad usare l'ambiente di TEST da qualche giorno. 
Fino a ieri entravo tranquillamente con le mie credenziali SPID. 
Da questa mattina mi da Errore di connessione - Richiesta fallita codice errore 504.

Qualcuno mi può aiutare

Federica Calicchia
Comune di Cori (LT)

**Comment by mttfranci** [comment]
Buongiorno, potreste cortesemente riprovare?

Grazie in anticipo.

Saluti

Assistenza ANSC

**Comment by ServiziDemograficiCori** [comment]
Adesso funziona. Grazie

**Comment by mttfranci** [comment]
Prego
