### ISSUE TITLE
Errore "presa visione" con accesso tramite SPID

### ISSUE THREAD

**Issue by antonioluberto** [italia/ansc#488]
Nel corso dei test appena condotti presso il Comune di Grottaferrata, per atto di nascita "2023-1214003-207-058046" si è tentato di apporre firma elettronica da parte del dichiarante (la firma autografa al momento non si può utilizzare stante il problema evidenziato in https://github.com/italia/ansc/issues/475 ed ancora aperto): il link al quale accedere per confermare la presa visione del documento viene regolarmente inviato, ma è impossibile accedere mediante utenza SPID.
Tramite SPID, peraltro, il dipendente comunale che esegue il test esegue regolarmente _accesso_ alla WebApp
Al dipendente comunale che esegue il test è stato abilitato il solo accesso tramite SPID alla WebApp.

Rimaniamo in attesa di vostra indicazione.

**Comment by amusarra** [comment]
Buongiorno @antonioluberto 
Al fine di poter intraprendere delle attività di analisi, abbiamo necessità di sapere quale errore ottiene l'utente accedendo via SPID all'applicazione di presa visione. 

Cordiali Saluti.
Supporto ANSC.

**Comment by antonioluberto** [comment]
L'utente riceve regolarmente e-mail contenente il link cui accedere per confermare la presa visione; al click sul link medesimo si apre correttamente la pagina della WebApp per il login ma una volta selezionata la sezione "Spid" e selezionato il provider (PosteID) 

![image](https://github.com/italia/ansc/assets/26415430/f15c104f-021b-41ab-aa32-74c94644c724)


il tentativo di accesso produce errore:

![image](https://github.com/italia/ansc/assets/26415430/b232b42e-0dda-41fa-afa1-537d9ec4903c)

**Comment by amusarra** [comment]
@antonioluberto grazie per il dettaglio per cui è stato identificato il problema.
È un problema di configurazione, ovvero, nell'indirizzo dell'IDP manca la porta TCP/IP che in questo caso è 9443.

Cordiali Saluti.
Supporto ANSC.

**Comment by antonioluberto** [comment]
Buonasera.
Ci occorre qualche chiarimento in più
A quale "configurazione" esattamente deve essere ricondotto il problema?
Alla rete comunale? Se si, quale intervento si deve richiedere in merito all'Ente?

Per completezza, comunque: abbiamo il medesimo problema anche noi (Dedanext) con l'utenza del collega Antonio Carcea per la quale ieri è stata abilitato l'accesso alla WebApp tramite propria utenza Spid. Anche il collega, così come l'utente comunale, accede correttamente alla WebApp di test mediante la propria utenza Spid, mentre non riesce ad accedere alla pagina di presa visione atto per l'eventuale sottoscrizione elettronica dell'atto.

**Comment by antonioluberto** [comment]
In aggiunta a quanto indicato al post precedente, abbiamo provato ad editare manualmente la url:
https://spidpre.anpr.interno.it/rp/ansc/poste/cit
su cui l'utente viene indirizzato al click su

![image](https://github.com/italia/ansc/assets/26415430/459dbab5-2a44-436e-83d8-e04b0f4749c6)
 modificandola in:

https://spidpre.anpr.interno.it:9443/rp/ansc/poste/cit

A questo punto l'utente viene correttamente indirizzato sulla pagina di login Spid, il login avviene correttamente ma a questo punto la pagina che dovrebbe visualizzare l'evento di cui prendere visione rimane indefinitamente in caricamento:

![image](https://github.com/italia/ansc/assets/26415430/26b637e1-0788-4af9-8835-fa9890abe2c7)

**Comment by antonioluberto** [comment]
Buonasera.
Credo che il workaround suggerito coincida con l'operazione indicata al post delle 18:22 (successivo a quello cui fa diretto riferimento la sua ultima risposta), ma che porta all'ulteriore anomalia li evidenziata.
Laddove, doversamente, la nota
_indicare la porta 9443 sull’indirizzo dell’IDP_
faccia riferimento ad intervento di tipo diverso, potrebbe gentilmente indicarmi esattamente gli step operativi da seguire?
Grazie,
Antonio

**Comment by mttfranci** [comment]
Buona serata, potreste riprovare?
Ora la configurazione dovrebbe essere corretta.

NOTA: una parte degli host ha un certificato emesso da CA Postazioni Svil che potrebbe non essere risconosciuto se già non trastato.

Saluti

**Comment by antonioluberto** [comment]
Buongiorno.
Ora pare corretta la generazione del link da:

![image](https://github.com/italia/ansc/assets/26415430/dbe4ffc2-7ba3-48dc-86fb-ed50daaaddbb)


ma, come scrivevamo già ieri, a pagina che dovrebbe visualizzare l'evento di cui prendere visione rimane indefinitamente in caricamento:

![image](https://github.com/italia/ansc/assets/26415430/075f1965-ee9f-4bf2-967b-279b5255e3aa)

**Comment by mttfranci** [comment]
Si stiamo verificando.
Saluti
