### ISSUE TITLE
[ws R011] Cancellazione Atto - Eliminazione fisica o annullamento?

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/ansc#489]
in occasione della call di martedì scorso, abbiamo approfondito il tema in oggetto, arrivando a queste conclusioni:
1. l'atto in stato CONFERMATO può essere cancellato con ws R011 e viene eliminato fisicamente
2. l'atto in stato FIRMATO DICHIARANTE può essere cancellato con ws R011 e NON viene eliminato fisicamente, ma passa in stato ANNULLATO
3. l'atto in stato FIRMATO USC non può essere cancellato con servizio ws R011

avendo avuto esperienze di test che andavano in conflitto con queste conclusioni ho riprovato oggi, e mi trovo questa situazione:
1. l'atto in stato CONFERMATO, una volta cancellato con ws R011, risulta in stato ANNULLATO (idEventoAnsc: 1214041 - pre-produzione)
2. l'atto in stato FIRMATO DICHIARANTE, una volta cancellato con ws R011, risulta ANNULLATO (idEventoAnsc: 1214040 - pre-produzione)
3. l'atto in stato FIRMATO USC, non è stato possibile cancellarlo con ws R011, il servizio va in errore con il messaggio "1. Evento firmato o annullato"

per cui la situazione di cui al punto '1.' non mi torna con quanto ci siamo detti.

probabilmente ho capito male io, per cui vi chiedo di chiarirmi la situazione oppure di verificare se ritenete che il sistema non risponda come dovrebbe.

grazie
Alessandro Monopoli ADS

**Comment by asqueglia** [comment]
Buongiorno, confermiamo da vostri test il punto 2 e il punto 3. Verifichiamo il punto 1 e le facciamo sapere

**Comment by asqueglia** [comment]
Abbiamo preso in carico il punto 1 nel senso che un atto in stato 'CONFERMATO', se cancellato verrà eliminato logicamente. Un atto cancellato logicamente non sarà più consultabile.

**Comment by asqueglia** [comment]
Buongiorno comunichiamo che con il rilascio odierno della versione 1.23.0 la segnalazione in oggetto è stata corretta; provvediamo quindi a chiudere la issue. In caso di ulteriori malfunzionamenti si prega di aprire una issue dedicata.
