### ISSUE TITLE
tabella di decodifica 64_dec_richiedente_nascita

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#49]
La differenza tra il valore "soggetto" (codice 3) ed "altro" (codice 4) quale sarebbe?

**Comment by asqueglia** [comment]
Buonasera, la tabella  di decodifica indicata viene utilizzata nel caso d'uso di trascrizione nascita richiesta da chi ha interesse alla trascrizione; abbiamo indicato come possibili interessati la madre, il padre, il soggetto intestatario oppure altra persona.
