### ISSUE TITLE
[ws R002] Certificazione - Matrimoni estero: luogo di matrimonio sbagliato (idUseCase 331000 e 332000)

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/ansc#490]
nella certificazione di atti matrimonio trascritti dall'estero, compare come luogo di matrimonio il comune che sta trascrivendo l'atto.
![image](https://github.com/italia/ansc/assets/26788199/8c7f6d03-96d7-43c4-9ed6-329ced58a30c)

es. atto inviato via web-service: 2023‐1214049‐322‐039010 
es. atto registrato su web-app (che abbiamo provato per analizzare a fondo il problema): 2023‐1214004‐420‐039010 
(entrambi registrati in ambiente PRE - comune di FAENZA)

in generale abbiamo notato che nella preview dell'atto non viene proprio riportato il comune di matrimonio.

lato web-service abbiamo verificato, per tentativi, che un modo per risolvere è quello di inviare il comune di matrimonio all'interno dei dati "luogoCelebrazione", anche se questa sezione non è prevista per questi casi d'uso.

preciso che il problema è anche in produzione.

attendiamo verifiche e riscontri.

grazie.
Alessandro Monopoli ADS

**Comment by asqueglia** [comment]
Buongiorno verifichiamo e le facciamo sapere

**Comment by AMonopoliADS** [comment]
segnalo due cose, applicando la modalità che suggerite:
1. nella preview dell'atto continua a non comparire il luogo di celebrazione (presumo verrà sistemato insieme alla correttiva prevista per la web-app, ma x sicurezza lo segnalo)
2. nei certificati il luogo di matrimonio viene stampato senza indicazione dello stato (come se si aspettasse comunque una provincia italiana)

![image](https://github.com/italia/ansc/assets/26788199/7bfee816-4931-417b-87e6-303f022412af)
(idAttoAnsc: 2023‐1214255‐317‐039010 - ambiente PRE - comune di FAENZA)

**Comment by asqueglia** [comment]
Buon pomeriggio, è stata appena rilasciata la fix sulla web app che dovrebbe risolvere il problema. Fateci sapere se riscontrate eventuali problemi.
