### ISSUE TITLE
Notifiche anomale ricevute 

### ISSUE THREAD

**Issue by siscomanpr** [italia/ansc#491]
Sull'ambiente pre-produzione di Serravalle Sesia, continuano ad arrivare tutti i giorni delle notifiche riferite sempre allo stesso evento/soggetto di un atto redatto ad aprile 2023. 

Rileviamo l'anomalia sia da ws che da webapp:

![image](https://github.com/italia/ansc/assets/28776141/694d2d8e-3490-42d9-9cfe-cc1dad915118)

**Comment by asqueglia** [comment]
Buonasera, si tratta di eventi inviati da nostri test interni. Ce ne accorgiamo dal codIstat del comune registrazione che corrisponde ad un comune fittizio che utilizziamo appunto per test interni. Ci scusiamo per il disguido.
Provvediamo pertanto a chiudere la issue.
