### ISSUE TITLE
Accesso Web App ambiente pre-produzione - Errore di connessione

### ISSUE THREAD

**Issue by MarcoSalaPad** [italia/ansc#493]
Buongiorno,

questa mattina ci sono problemi di collegamento alla Web App dell'ambiente di pre-produzione.
Ci sono dei momenti dove funziona e dei momenti dove, alla login viene restituito il seguente messaggio:

Errore di connessione
Richiesta fallita codice errore 504

Rimango in attesa per poter riprendere le attività con il comune pilota.

Grazie
Marco Sala

**Comment by antonioluberto** [comment]
Buongiorno.
Confermiamo lo stesso problema anche da Grottaferrata.

**Comment by mttfranci** [comment]
@MarcoSalaPad @antonioluberto potreste riprovare?

**Comment by antonioluberto** [comment]
Anche dal tentativo di eliminazione di un atto "Confermato" si ottiene errore:

![image](https://github.com/italia/ansc/assets/26415430/aec580e5-9deb-4c91-8d79-725e2cec65aa)

**Comment by asqueglia** [comment]
Buongionro, potete farci sapere se i problemi persistono ? ci risultano risolti ma volevamo sapere anche da voi
