### ISSUE TITLE
Timeout in trasmissione validazione evento

### ISSUE THREAD

**Issue by LucaBonini64** [italia/ansc#494]
Buongiorno,
stamattina facendo l'invio di un evento nell'ambiente di test di Novi Ligure (https://anscservicepre.anpr.interno.it/services/service/val/validazione/evento/1) 
ci viene restituito l'errore:
Errore del server remoto: (504) Timeout gateway.

potete verificare per cortesia?

Grazie.

**Comment by MarcoSalaPad** [comment]
Buongiorno,

confermiamo anche noi (Pa Digitale Spa) gli stessi problemi di timeout nei servizi di validazione, oltre alla problematica indicata nella issues #493 che restituisce sempre errore 504.

Grazie

**Comment by antonioluberto** [comment]
Buongiorno.
Mi aggiungo per segnalare il medesimo problema anche sul Comune di Grottaferrata; qui, in particolare, lo abbiamo appena verificato al tentativo di apporre sottoscrizione da parte dell'usc.

**Comment by gbuemi** [comment]
Buongiorno, 
abbiamo preso in carico la segnalazione.

Un saluto
Supporto ANSC
