### ISSUE TITLE
Mancata ricezione notifica matrimonio

### ISSUE THREAD

**Issue by siscomanpr** [italia/ansc#496]
Abbiamo registrato un atto di nascita con il caso d'uso 1311 (trascrizione nascita all'estero - da consolato) e subito dopo un matrimonio dello stesso soggetto con caso uso 332000 (trascrizione matrimonio estero - da consolato). 
Mi sarei aspettato di ricevere una notifica di proposta di annotazione di matrimonio per l'atto di nascita del soggetto (o l'annotazione registrata automaticamente sull'atto di nascita), ma la notifica non è arrivata e anche consultando l'atto di nascita sul portale web di ANSC l'annotazione non è presente.
E' un'anomalia del sistema oppure abbiamo sbagliato qualcosa nella registrazione degli eventi? 
Secondo le nostre verifiche sembra tutto corretto visto che nella validazione del matrimonio l'id del soggetto era presente.

Allego i json delle chiamate e relativo idOperazione
[nascita.json](https://github.com/italia/ansc/files/13415407/nascita.json)  idOperazione: 1704523
[matrimonio.json](https://github.com/italia/ansc/files/13415405/matrimonio.json)  idOperazione: 1704553

**Comment by amusarra** [comment]
Salve @siscomanpr 
Abbiamo preso in carico la segnalazione.

Cordiali Saluti.
ANSC.

**Comment by asqueglia** [comment]
La segnalazione è stata risolta. Si prega di rifare il test ex novo. Chiudiamo pertanto la issue. In caso di ulteriori segnalazioni si prega di aprirne una altra dedicata.
