### ISSUE TITLE
Permangono i problemi di Time Out nella validazione evento

### ISSUE THREAD

**Issue by LucaBonini64** [italia/ansc#497]
Buonasera,
in ambiente di test del Comune di Novi Ligure permangono i problemi di Timeout nella richiesta di validazione di un evento [R009].

Alcuni eventi siamo riusciti a trasmetterli, poi dalla Web Application abbiamo eseguito il comando di eliminazione di un atto di morte (id 1214136) ed il sistema ha risposto (504) Gateway Timeout. Da quel momento in avanti qualsiasi richiesta di inserimento di un nuovo evento restituisce: The remote server returned an error: (504) Gateway Timeout, mentre ad esempio il servizio di anteprima [R010] funziona correttamente.

Ovviamente non sappiamo se gli eventi sono collegati ma preferisco segnalarvelo.

Cordiali Saluti.

**Comment by mttfranci** [comment]
@LucaBonini64  buongiorno, stiamo verificando il problema.

Saluti

**Comment by amusarra** [comment]
Buongiorno @LucaBonini64  ci scusiamo per il disservizio, al momento dovrebbe essere nuovamente disponibile. Stiamo lavorando per indagare e risolvere tempestivamente le problematiche. Se potete riprovare e farci sapere se ci sono problemi.

Cordiali Saluti.
Supporto ANSC.

**Comment by mttfranci** [comment]
Con l'analisi del sistema negli ultimi due giorni, a noi risulta che, salvo casi sporadici, gli ultimi interventi hanno risolto i problemi di timeout. 
Chiudiamo intanto la issue.
