### ISSUE TITLE
Errore invio annotazione

### ISSUE THREAD

**Issue by antonioluberto** [italia/ansc#498]
Abbiamo provato l'invio di annotazione su atto di morte, ma il servizio restituisce errore segnalando l'assenza dell' identificativo ANSC ("text":"IdAnsc non valido") che però è correttamente riportato nella richiesta ("idAnsc":"2022-12000-1510223-058046"). 
Di seguito il riferimento allo specifico test appena eseguito:
"idOperazione":"1703855"

**Comment by asqueglia** [comment]
Buongiorno @antonioluberto , da verifiche effettuate in ambiente di pre produzione non ci risulta un evento registrato per l'id ansc indicato; per cui l'errore ricevuto ci sembra corretto. Potete fornirci maggiori informazioni ?

**Comment by antonioluberto** [comment]
Buonasera.
Abbiamo intercettato nostro errore nell'esecuzione della richiesta di cui sopra, correggendo per quanto necessario.
Grazie,
Antonio

**Comment by asqueglia** [comment]
Buongiorno perfetto, provvediamo a chiudere la issue. In caso di ulteriori segnalazioni la preghiamo di aprire una altra issue dedicata
