### ISSUE TITLE
Ancora timeout in trasmissione validazione evento

### ISSUE THREAD

**Issue by antonioluberto** [italia/ansc#500]
Buongiorno.
Abbiamo visto che è stata chiusa la https://github.com/italia/ansc/issues/494 ma abbiamo appena provato l'invio di un atto di morte riscontrando ancora il medesimo problema di timeout

**Comment by asqueglia** [comment]
Buongiorno ci scusiamo per il disservizio, al momento dovrebbe essere nuovamente disponibile. Stiamo lavorando per indagare e risolvere tempestivamente le problematiche.  Se potte riprovare  farci sapere se ci sono problemi.

**Comment by mttfranci** [comment]
A seguito della risposta della issue #497 chiudiamo la issue.

Saluti
Assistenza ANSC
