### ISSUE TITLE
Errore validazione notifiche anagrafiche

### ISSUE THREAD

**Issue by antonioluberto** [italia/ansc#501]
Con riferimento alle notifiche ANPR generate da evento ANSC, si riscontra che nella testata delle notifiche medesime è presente come primo campo il tag "IdNotifica" che però non figura nell'xsd pubblicato.
Questo ci impedisce la validazione della notifica.
E' previsto un rilascio a breve della versione aggiornata dell'xsd?

**Comment by asqueglia** [comment]
Buongiorno, @antonioluberto abbiamo appena aggiornato la documentazione sul portale pubblico ANPR. Potete verificare ?
