### ISSUE TITLE
[R009] validazione caso 1312 - Trascrizione di atto di nascita avvenuta all estero su richiesta di chi ha interesse alla trascrizione

### ISSUE THREAD

**Issue by siscomanpr** [italia/ansc#502]
Comune di Serravalle Sesia - Ambiente di Produzione

Come anticipato nella call di oggi, cercando di validare il caso d'uso in oggetto senza indicare il comune di residenza e la nazionalità dell'intestatario (come da specifiche mapping sono campi non obbligatori) , riceviamo gli errori bloccanti: 
```
Il campo evento.intestatari[0].idNazionalita nella sezione Figlio è obbligatorio
Il campo evento.intestatari[0].nazionalita nella sezione Figlio è obbligatorio
Il campo evento.intestatari[0].idStatoResidenza nella sezione Figlio è obbligatorio
Il campo evento.intestatari[0].nomeStatoResidenza nella sezione Figlio è obbligatorio
```

Allego i json di richiesta e risposta:
[request.json](https://github.com/italia/ansc/files/13427037/request.json)
[response.json](https://github.com/italia/ansc/files/13427039/response.json)

idOperazione: 15361

Si fa inoltre presente che assieme al comune abbiamo provato a validare l'atto tramite la webapp come da voi suggerito ma anche in quella modalità vengono richiesti obbligatori i dati di residenza e cittadinanza (allego screenshot).

![image](https://github.com/italia/ansc/assets/28776141/6c912349-b467-4f18-948a-6687cbf860f6)

Siscom SPA

**Comment by siscomanpr** [comment]
Aggiungo che successivamente abbiamo provato a modificare il campo tipoRichiedente indicando "4. altro" (invece di "3. soggetto"), e l'atto è stato correttamente validato tramite il nostro gestionale. 
Vista l'urgenza, e visto il ritardo accumulato nella trascrizione di questo atto dovuto ai suddetti problemi, l'operatrice di Serravalle ha ritenuto opportuno proseguire con la registrazione dell'atto indicando questo campo "tipoRichiedente" non proprio corretto per bypassare il problema, ma sicuramente è un caso da analizzare per trovare una soluzione al più presto essendo queste casistiche frequenti.

**Comment by asqueglia** [comment]
Buongiorno, dalle verifiche che abbiamo fatto lato Web Application non ci risulta quanto indicato. Stiamo provando quindi a contattare direttamente il comune per capire. Di seguito lo screen shot per dimostrarvi quanto detto

![image](https://github.com/italia/ansc/assets/29303629/1db5b7df-e841-446e-9de7-814a8e913845)

Potrebbe essere la cache del browser dell'operatore comunale ?
Lato servizi cooperativi invece abbiamo notato che invocate il servizio con una versione precedete la correttiva effettuata il giorno 14/11; potreste riprovare trasmettendo la versione corretta ossia la 100006 ?

**Comment by siscomanpr** [comment]
Buongiorno, per quanto riguarda la web app di produzione non posso darvi riscontro in questo momento, ma noto che ieri il pannello del dati del soggetto aveva come titolo nell'intestazione "Figlio", mentre nel vostro screenshot vedo "Soggetto". Da una verifica nella webapp di pre-produzione in effetti oggi vediamo Soggetto e i dati di residenza e cittadinanza non sono più obbligatori per quel caso d'uso.
Per quanto riguarda i servizi cooperativi faremo delle prove con l'ultima versione sull'ambiente di pre-produzione. 
Su quello di produzione ormai l'atto è firmato.
Grazie.
