### ISSUE TITLE
Anomalie notifiche ANSC in ambiente di pre-produzione

### ISSUE THREAD

**Issue by antonioluberto** [italia/ansc#504]
In considerazione di quanto indicato nella risposta alle issue
https://github.com/italia/ansc/issues/397
https://github.com/italia/ansc/issues/410, 
per atto di morte il cui titolare sia soggetto residente presso il Comune Gestore (in ANSC) ed il cui atto di di nascita sia presente, in formato analogico, presso altro Comune italiano ci aspettiamo di ricevere:
a) una notifica di tipo "Trascrizione" con la quale il Comune Gestore venga informato della necessità di confermare la presa visione dell'atto in esame (ancorché prodotto dal Comune medesimo)
b) una notifica di tipo "Annotazione" che il Comune Gestore dovrebbe confermare per indicare di aver ricevuto, dal Comune che detiene l'atto di nascita cartaceo del titolare, notizia dell'avvenuta apposizione dell'annotazione di morte sull'atto di nascita cartaceo medesimo.

Le notifiche ANSC in questione dovrebbero essere immediatamente disponibili.
La "conferma" delle suddette notifiche è propedeutica alla generazione della notifica anagrafica ANPR.

Su ambiente di pre-produzione del Comune di Grottaferrata abbiamo generato negli ultimi tre giorni tre atti di morte distinti tutti afferenti alla situazione funzionale sopra descritta:

1) atto di morte 
2023-1213739-202-058046
(titolare residente a Grottaferrata, presente nella relativa area ANPR di test) con atto di nascita in altro Comune italiano.
Ricevute due notifiche, una di tipo "trascrizione", una di tipo "annotazione"

2) atto di morte 
2023-1214223-213-058046.
(titolare residente a Grottaferrata, presente nella relativa area ANPR di test) con atto di nascita in altro Comune italiano.
Ricevute una sola notifiche di tipo "trascrizione" (non prima di quaranta minuti dalla firma dell'atto da parte dell'usc)

3) atto  di morte 
2023-1214235-214-058046.
(titolare residente a Grottaferrata, presente nella relativa area ANPR di test) con atto di nascita in altro Comune italiano.
Ricevuta nessuna notifica (trascorse più di 5 ore firma dell'atto da parte dell'usc).

Potete gentilmente verificare se vi siano anomalie nella generazione delle notifiche ANSC su ambiente di pre-produzione (ovvero indicarci se e quali errori eventualmente ci siano da parte nostra nell'operazione di acquisizione delle medesime)?

**Comment by antonioluberto** [comment]
Buongiorno.
A parziale rettifica del punto 3. quanto indicato ieri:

3. atto di morte
2023-1214235-214-058046.
(titolare residente a Grottaferrata, presente nella relativa area ANPR di test) con atto di nascita in altro Comune italiano.
Ricevuta una sola notifiche di tipo "trascrizione" (non prima di 2 ore dalla firma dell'atto da parte dell'usc).

Si rimane in attesa dei chiarimenti richiesti.

**Comment by gbuemi** [comment]
Buonasera @antonioluberto,
vi comunichiamo che l'anomalia presente in preproduzione è stata risolta ed è possibile effettuare dei nuovi test creando nuovi atti di morte.

Un saluto
Assistenza ANSC
