### ISSUE TITLE
[ws R009] Validazione Annotazione Automatica - Errore: msg. "Caso uso non abilitato : 10000000"

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/ansc#505]
ambiente PRE - comune di FAENZA (idComune 3743)
endpoint: https://anscservicepre.anpr.interno.it/services/service/val/validazione/evento/1

si tenta di inviare via web-service un'annotazione automatica su atto di nascita.
la validazione ritorna l'errore in oggetto ("Caso d'uso non abilitato: 10000000")
"idOperazioneComune": 2023004044,

cosa ci sfugge nel tentare di inviare questo caso d'uso?

grazie
Alessandro Monopoli ADS

**Comment by asqueglia** [comment]
Buongiorno, le annotazioni automatiche sono gestite automaticamente dal sistema e non possono essere registrate come eventi. Se l'intento è registrare una annotazione è possibile utilizzare il caso d'uso di servizio specifico, relativo al registro a cui afferisce l'atto su cui apporre l'annotazione.
Ad esempio se si desidera registrare una annotazione (integrativa) su un atto di nascita è possibile utilizzare i casi d'uso seguenti in base a quanto più opportuno

[1.4.4.0.0.0.0.0] Caso d'uso di servizio (comunicazione da altri comuni) 
[1.4.5.0.0.0.0.0] Caso d'uso di servizio (comunicazioni da altre amministrazioni)

**Comment by AMonopoliADS** [comment]
l'intento è quello di registrare un annotazione che non è partita automaticamente perchè - ad esempio - l'evento secondario è stato inviato come caso d'uso di servizio.
chiarito che il caso d'uso di servizio non produce l'invio automatico dell'annotazione sull'atto primario, l'intenzione era di registrarla utilizzando il caso d'uso 10000000 (ci sembrava quello più coerente con la situazione)
se dobbiamo utilizzare il caso d'uso di servizio (14400000), faccio presente che la sua definizione è fuorviante perchè si riferisce a "comunicazione da altri comuni" (mentre in questo caso il flusso parte dal mio comune).

**Comment by asqueglia** [comment]
Verificheremo se opportuno modificare la descrizione del caso d'uso 14400000. Provvediamo a chiudere la issue. In caso di ulteriori segnalazioni la preghiamo di riaprire la issue oppure di aprirne una altra dedicata.
