### ISSUE TITLE
[web-service vs web-app] Annotazioni

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/ansc#507]
ambiente PRE - comune di FAENZA (idComune 3743)

alcune segnalazioni / richieste chiarimenti in merito alla gestione delle annotazioni.

1. sulla web-app, l'evento "annotazione" è visibile nella lista degli eventi solo fino a quanto risulta in stato "CONFERMATO"
nel momento in cui l'annotazione passa in stato "FIRMATO USC" non è più visibile nella lista degli eventi registrati dal comune.
il risultato è il medesimo sia che l'annotazione venga inviata da web-service sia che venga registrata da web-app
es. 
annotazione inviata da web-service: idAnsc 2023-1214361-429-039010
annotazione registrata su web-app: idAnsc 2023‐1214365‐309‐039010
c'è una spiegazione oppure si tratta di un bug?

2. nell'intenzione di ottenere il pdf con l'anteprima dell'annotazione, il documento prodotto da web-app è strutturato in maniera coerente con il tipo di evento che si sta registrando:
![image](https://github.com/italia/ansc/assets/26788199/b6be63a7-9dd2-47e3-a4eb-b1de28e41e90)
la stessa richiesta effettuata da web-service - utilizzando il ws R010 - invece produce un documento non congruente, perchè tratta l'evento come se fosse un atto e non un annotazione:
![image](https://github.com/italia/ansc/assets/26788199/632405fe-82d4-4cea-8af8-c922f6db9d00)
posso ipotizzare che il problema sia su qualche dato mancante nella request, anche se l'idtipocontenuto viene inviato correttamente e non abbiamo esempi o errori di validazione che ci facciano capire quali altri dati possono servire.

grazie
Alessandro Monopoli ADS

**Comment by asqueglia** [comment]
Buongiorno, per quanto riguarda la prima richiesta il comportamento del sistema è quello da lei verificato; è possibile recuperare l'annotazione al fine di completarla. Una volta che l'annotazione è stata completata e firmata, può essere consultata in relazione all'atto su cui viene apposta.

Per la seconda domanda, la modalità attualmente prevista per consultare l' annotazione è tramite  servizio cooperativo  R005; Il servizio consente di consultare il JSON rappresentativo dell'annotazione e può essere invocato in vari modi come ad esempio per identificativo dell'annotazione, oppure per identificativo dell'evento su cui è apposta l'annotazione.

Verifichiamo invece la questione dell'anteprima come estratto integrale, che ci sembra effettivamente un errore.

**Comment by asqueglia** [comment]
Buongiorno comunichiamo che con il rilascio odierno della versione 1.23.0 la segnalazione in oggetto è stata corretta; provvediamo quindi a chiudere la issue. In caso di ulteriori malfunzionamenti si prega di aprire una issue dedicata.
