### ISSUE TITLE
Sep_div_002: richiesta indicazione compilazione dati separazione giudiziale

### ISSUE THREAD

**Issue by antonioluberto** [italia/ansc#509]
All'interno del modello relativo al caso d'uso in oggetto, è presente la sezione:

![image](https://github.com/italia/ansc/assets/26415430/4f8e485a-8dcd-40f0-8a68-af61d46efef0)

Nel caso in cui la separazione sia avvenuta presso Tribunale:
a) quale valore dovrebbe contenere il campo obbligatorio "Tipo evento".
L'enumerato di riferimento ammette i soli valori:
_atto
trascrizione
annotazione_

b) quale valore dovrebbero contenere, rispettivamente, i campi obbligatori:
Numero comunale
Anno atto
Data atto
Tipo registro ?

La sentenza giudiziaria di separazione viene tipicamente solo "annotata" sull'atto di matrimonio originario.

**Comment by asqueglia** [comment]
Buongiorno @antonioluberto,
se l'esigenza è solo annotare l'atto di matrimonio, è opportuno utilizzare il caso d'uso di servizio delle annotazioni [3.6.7.9.9.9] Caso d'uso di servizio (comunicazioni da altre amministrazioni).
Ci riserviamo di richiedere un approfondimento ad ANUSCA per la casistica della separazione giudiziale.

**Comment by antonioluberto** [comment]
Buongiorno.
Formulo diversamente la domanda.
Il caso d'uso "Sep_div_002" viene utilizzato in relazione all'accordo di scioglimento (o di cessazione degli effetti civili) del matrimonio (divorzio) che due coniugi concludono di fronte all'ufficiale di stato civile.
Perché i due coniugi possano concludere di fronte all'usc accordo siffatto, è necessario siano legalmente "separati" (da almeno 6 mesi).
Nel produrre - oggi - l'atto riferito all'accordo di scioglimento (o di cessazione degli effetti civili) del matrimonio in riferimento alla "separazione" l'usc è tenuto a
[...]
_indicare il provvedimento/la convenzione di negoziazione assistita/l'accordo che ha determinato la separazione, con tutti i dati per identificarlo_
[...].

La "separazione" (antecedente all'accordo di cessazione/scioglimento del matrimonio) può essersi avuta 
a) in forma giudiziale
b) in forma extra-giudiziale (di fronte all'usc oppure mediante accordo di negoziazione assistita dagli avvocati)

Nel caso a), quali informazioni devono essere riportate in corrispondenza dei campi obbligatori

Numero comunale
Anno atto
Data atto
Tipo registro 

presenti nella sezione

![image](https://github.com/italia/ansc/assets/26415430/e280dab4-5a68-4752-b1ae-edbd490f6904)


?

**Comment by asqueglia** [comment]
Buonasera @antonioluberto, confermiamo da una verifica con ANUSCA che la sentenza di separazione giudiziale italiana (non estera) non deve essere registrata come evento me solo annotata sull'atto di matrimonio con il caso d'uso di servizio delle annotazioni [3.6.7.9.9.9] Caso d'uso di servizio (comunicazioni da altre amministrazioni).

**Comment by asqueglia** [comment]
Buongiorno, non avendo ricevuto risposta, provvediamo a chiudere la presente issue. Se ci fossero ulteriori dubi o perplessità la preghiamo di arpire una altra issue dedicata.

**Comment by antonioluberto** [comment]
Buongiorno.
In effetti siamo noi ad attendere vostra risposta rispetto alla nostra richiesta di chiarimento dello scorso 27 novembre.
Ripeto:

Il caso d'uso "Sep_div_002" viene utilizzato per gestire il caso di accordo di scioglimento (o di cessazione degli effetti civili) del matrimonio (divorzio) che due coniugi concludono di fronte all'ufficiale di stato civile.
Perché i due coniugi possano concludere di fronte all'usc accordo siffatto, è necessario che gli stessi siano legalmente "separati" (da almeno 6 mesi).
Nel produrre - oggi - l'atto riferito all'accordo di scioglimento (o di cessazione degli effetti civili) del matrimonio in riferimento alla "separazione" l'usc è tenuto a
[...]
_indicare il provvedimento/la convenzione di negoziazione assistita/l'accordo che ha determinato la separazione, con tutti i dati per identificarlo_
[...]

come da contenuto della formula 121 -  quater.

La "separazione" (antecedente all'accordo di cessazione/scioglimento del matrimonio) può essersi avuta :
a) in forma giudiziale
b) in forma extra-giudiziale (di fronte all'usc oppure mediante accordo di negoziazione assistita dagli avvocati)

Nel caso a), quali informazioni devono essere riportate in corrispondenza dei campi obbligatori

Numero comunale
Anno atto
Data atto
Tipo registro 

presenti nella sezione

![image](https://github.com/italia/ansc/assets/26415430/e280dab4-5a68-4752-b1ae-edbd490f6904)


?

**Comment by asqueglia** [comment]
Buongiorno @antonioluberto, come scritto sopra, abbiamo verificato con ANUSCA che la sentenza di separazione giudiziale italiana (non estera) non deve essere registrata come evento ma solo annotata sull'atto di matrimonio con il caso d'uso di servizio delle annotazioni [3.6.7.9.9.9] Caso d'uso di servizio (comunicazioni da altre amministrazioni). Quindi la sua domanda è come registrare un accordo di separazione a seguito di una separazione giudiziale ?

**Comment by antonioluberto** [comment]
Buonasera.
La mia domanda è semplice, ma faccio ora il tentativo di renderla mediante un esempio:

i signori
_Rossi Giovanni
Verdi Martina_
hanno contratto matrimonio il 10/10/2010.
Quindi, si separano legalmente in forma giudiziale il 10/10/2015: esiste quindi una sentenza 
del Tribunale di XXXXX, emessa in data 10/10/2015 con numero yyyy
che sancisce la separazione legale fra i due soggetti di cui sopra.
Nota:  ci è assolutamente chiaro che questa sentenza venga in seguito trascritta nei registri di stato civile del comune competente (non è questo l'oggetto della nostra domanda)

Il 10/10/2020 i due soggetti di cui sopra concludono l'accordo di divorzio (scioglimento del matrimonio oppure cessazione degli effetti civili del matrimonio) dinanzi all'usc,

Per trasmettere ad ANSC quest'ultimo accordo di divorzio (scioglimento del matrimonio oppure cessazione degli effetti civili del matrimonio) dinanzi all'usc usiamo il caso d'uso Sep_Div_002; quali informazioni dovremmo riportare in corrispondenza dei campi obbligatori

Numero comunale
Anno atto
Data atto
Tipo registro 

presenti nella sezione

![image](https://github.com/italia/ansc/assets/26415430/e280dab4-5a68-4752-b1ae-edbd490f6904)

?

I campi in questione paiono riferirsi ad un "atto" di separazione; ma i due soggetti si sono separati mediante sentenza del tribunale XXXXX?

**Comment by asqueglia** [comment]
La domanda era già chiara.. ciò che intendevamo specificare è che da un incontro con ANUSCA è stato confermato che non deve essere registrata la sentenza di separazione giudiziale, ma solo l'annotazione corrispondente. Ciò detto non c'è un atto a cui fare riferimento. Quindi un successivo accordo di separazione relativo ad una sentenza giudiziale di separazione, al momento non è previsto. Provvederemo ad aggiungere la casistica.

**Comment by antonioluberto** [comment]
Buonasera.
Non si tratta di "_successivo_ accordo di separazione relativo ad una sentenza giudiziale di separazione".
Si tratta di accordo di **_divorzio_** (cessazione oppure scioglimento) che necessariamente è successivo ad accordo/provvedimento di **_separazione_**: due soggetti possono divorziare solo dopo che siano trascorsi almeno sei mesi dalla separazione legale tra i medesimi.

**Comment by asqueglia** [comment]
ok si va bene. Provvederemo ad aggiungere la casistica. Grazie

**Comment by asqueglia** [comment]
Buongiorno @antonioluberto, abbiamo fatto un approfondimento con ANUSCA in merito alla casistica da lei riportata.
Per registrare un accordo di divorzio a seguito di una separazione giudiziale è possibile utilizzare il caso d'uso [3.4.2.0.0.0] Accordo di scioglimento (o di cessazione degli effetti civili) del matrimonio (divorzio) in cui viene è possibile acquisire il provvedimento della separazione indicando i dati dell'ente che ha emesso il provvedimento.
Di seguito un esempio di payload, ci faccia sapere se le torna.

"evento": {
        "id": 577139,
        "idTipoEvento": "3",
        "idtipocontenuto": "1",
        "idUsecase": "342000",
        "descrizioneCasoUso": "Accordo di scioglimento (o di cessazione degli effetti civili) del matrimonio (divorzio)",
        "stato": "CONFERMATO",
        "dataformazione": "2023-12-19",
        "ora": "10",
        "minuto": "31",
        "annoAtto": "2023",
        "numeroatto": "122",
        "idComuneRegistrazione": "1000000",
        "nomeComuneRegistrazione": "ANPR",
        "idProvinciaRegistrazione": "58",
        "siglaProvinciaRegistrazione": "RM",
        "operatore": "CRUMRA67S47Z127B",
        "ruoloOperatore": "2",
        "operatoreNome": "MARIE",
        "operatoreCognome": "CURIE",
        "redattoNellaCasaComunale": true,
        "intestatari": [
            {
                "id": "567751",
                "idsoggettoanpr": "",
                "codiceFiscale": "",
                "cognome": "VERDI",
                "nome": "ANDREA",
                "sesso": "M",
                "dataNascita": "1970-01-01",
                "idComuneNascita": "99",
                "nomeComuneNascita": "AGRIGENTO",
                "idProvinciaNascita": "84",
                "siglaProvinciaNascita": "AG",
                "idStatoNascita": "90",
                "nomeStatoNascita": "ITALIA",
                "idComuneResidenza": "8165",
                "nomeComuneResidenza": "ROMA",
                "idProvinciaResidenza": "58",
                "siglaProvinciaResidenza": "RM",
                "idStatoResidenza": "90",
                "nomeStatoResidenza": "ITALIA",
                "indirizzoResidenza": "",
                "idNazionalita": "90",
                "nazionalita": "ITALIANA",
                "flagDichiarante": false,
                "flagComparente": false,
                "flagFirmatario": true,
                "documentoRiconoscimento": {}
            },
            {
                "id": "567753",
                "idsoggettoanpr": "",
                "codiceFiscale": "",
                "cognome": "BIANCHI",
                "nome": "PAOLA",
                "sesso": "F",
                "dataNascita": "1977-01-01",
                "idComuneNascita": "99",
                "nomeComuneNascita": "AGRIGENTO",
                "idProvinciaNascita": "84",
                "siglaProvinciaNascita": "AG",
                "idStatoNascita": "90",
                "nomeStatoNascita": "ITALIA",
                "idComuneResidenza": "8165",
                "nomeComuneResidenza": "ROMA",
                "idProvinciaResidenza": "58",
                "siglaProvinciaResidenza": "RM",
                "idStatoResidenza": "90",
                "nomeStatoResidenza": "ITALIA",
                "indirizzoResidenza": "",
                "idNazionalita": "90",
                "nazionalita": "ITALIANA",
                "flagDichiarante": false,
                "flagComparente": false,
                "flagFirmatario": true,
                "documentoRiconoscimento": {}
            }
        ],
        "separazione": {
            "tipoAccordo": "2",
            "presenzaAvvocatoConiuge1": false,
            "presenzaAvvocatoConiuge2": false,
            "attoMatrimonio": {
                "idAnsc": "",
                "idComuneRegistrazione": "99",
                "nomeComuneRegistrazione": "AGRIGENTO",
                "idProvinciaRegistrazione": "84",
                "siglaProvinciaRegistrazione": "AG",
                "idtipocontenuto": "1",
                "dataformazione": "2020-12-12",
                "numeroatto": "123",
                "annoAtto": "2020",
                "tipologia": "3",
                "serie": "A",
                "parte": "I"
            },
            "parteInGiudizioPendente": false,
            "autoritaGiudiziaria": "",
            "dataConfermaAccordo": "2024-01-19",
            "provvedimentoSeparazione": {
                "nomeEnte": "Tribunale",
                "idComuneEnte": "99",
                "nomeComuneEnte": "AGRIGENTO",
                "idProvinciaEnte": "84",
                "siglaProvinciaEnte": "AG",
                "indirizzoEnte": "",
                "dataTrascrizione": "2023-12-18",
                "estremiDocumento": "AAAAA"
            },
            "dataEventoMatrimonio": "2020-12-12",
            "tipoProvvedimentoSeparazione": "1",
            "luogoEventoMatrimonio": {
                "idComune": "99",
                "nomeComune": "AGRIGENTO",
                "idProvincia": "84",
                "siglaProvincia": "AG",
                "idStato": "90",
                "nomeStato": "ITALIA"
            },
            "officianteEventoMatrimonio": "Mario Rossi"
        },
        "composizioneCompleta": "Oggi 19/12/2023 avanti a me MARIE CURIE, Ufficiale dello stato civile del Comune di ANPR (RM), nella funzione di delegato del sindaco sono comparsi i coniugi ANDREA VERDI e PAOLA BIANCHI, i quali mi dichiarano:\n- di avere contratto matrimonio in data 12/12/2020, in AGRIGENTO, dinanzi a Mario Rossi, di cui all'atto iscritto/trascritto nei registri dello stato civile con estremi numero 123 parte I serie A anno 2020 del comune AGRIGENTO (AG);\n- di non essere parti in giudizio pendente, concernente lo scioglimento del matrimonio tra gli stessi;\n- di essere legalmente separati a seguito di Tribunale, AGRIGENTO (AG) Numero AAAAA in data 18/12/2023 e di trovarsi in uno dei casi di cui all'articolo 3, primo comma, numero 2), lettera b), legge 10 dicembre 1970, n. 898;\n- di non essere genitori di figli minori;\n- di non essere genitori di figli maggiorenni incapaci;\n- di non essere genitori di figli maggiorenni portatori di handicap grave ai sensi dell'articolo 3, comma 3, della legge 5 febbraio 1992, n. 104;\n- di non essere genitori di figli maggiorenni economicamente non autosufficienti;\n- di non concordare tra di loro alcun patto di trasferimento patrimoniale;\n- di volere lo scioglimento del matrimonio. Ho invitato le parti a comparire nuovamente davanti a questo Ufficio per la conferma dell'accordo nel giorno 19/01/2024 e li ho informati che la mancata comparizione equivale a mancata conferma dell'accordo.\nIl presente atto viene letto ai dichiaranti i quali, insieme con me, lo sottoscrivono.",
        "datains": "2023-12-19T09:31:12.859196",
        "dataultimoagg": "2023-12-19T10:11:48.197887",
        "flagsecretato": 0,
        "idVersion": 100006
    }

**Comment by asqueglia** [comment]
Buongiorno, provvediamo a chiudere la issue. In caso di ulteriori chiarimenti si prega di riaprirla oppure di aprirne una dedicata al problema riscontrato.
