### ISSUE TITLE
[ws R010] Anteprima - Matrimonio estero: luogo di matrimonio (idUseCase 331000 e 332000)

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/ansc#510]
in riferimento alla issue #490 , gestita con il rilascio della v1.19.5, segnalo che è ancora presente il problema che il luogo di matrimonio non campare tra i metaDati nella preview dell'atto e nell'estratto per copia integrale.

prove effettuate in ambiente di pre-produzione

**Comment by mttfranci** [comment]
@AMonopoliADS avete provato da web app o da servizi in questo caso?
Avete un atto o meglio ancora idoperazione di riferimento da verificare?
Grazie in anticipo.

Assistenza ANSC

**Comment by COlivatoADS** [comment]
Riportiamo di seguito le info richieste:
Id atto 1214378  (web app)
Id atto 1214389  (servizi cooperativi) con id operazione 2023004102

Grazie
Saluti

**Comment by mttfranci** [comment]
Grazie stiamo verificando.

Saluti

**Comment by asqueglia** [comment]
Buongiorno, con il rilascio della versione 1.21.0 la segnalazione dovrebbe essere risolta. Chiudiamo pertanto la issue. In caso di ulteriori segnalazioni si prega di aprire una issue dedicata.
