### ISSUE TITLE
[R006] - Errore interno in trasmissione file per firma dichiarante

### ISSUE THREAD

**Issue by LucaBonini64** [italia/ansc#512]
Buongiorno,
nell'ambiente di preproduzione di Novi Ligure inviando un servizio R006 per l'inserimento del file di firma cartacea del dichiarante ci viene risposto:
{"errors":[{"code":"500","severity":"E","text":"Errore interno"}],"testataRisposta":{"idComune":6498,"idEsito":999,"idOperazione":"1709064","idOperazioneComune":"564"}}
Potete aiutarci a capire quale sia il problema?

Grazie.

**Comment by gbuemi** [comment]
Buongiorno abbiamo verificato la richiesta inviata; nello specifico per il servizio R006 di firma dichiarante, avete inviato una anagrafica non completa dei soggetti firmatari. Riporto quanto descritto nel changelog relativo alla versione 1.15.2 del 23-10-2023,

**R006 firma dichiarante con lista firmatari: il servizio richiede necessariamente i dati anagrafici con cui il soggetto è stato registrato (es. se il coniuge è stato registrato con nome, cognome, sesso e data di nascita, questi campi devono essere trasmessi anche nel servizio R006; se l'officiante è stato registrato solo con nome e cognome, il servizio R006 dovrà essere invocato tramsettendo solo nome e cognome)**

Si richiede pertanto di riprovare trasmettendo tutti i dati anagrafici dei soggetti firmatari, trasmessi durante la registrazione dell'evento con il servizio R009.

Nello specifico è stato inviato il cf del soggetto che non era stato trasmesso nel servizio di validazione evento
 #475 issue di riferimento

**Comment by LucaBonini64** [comment]
Buongiorno,
abbiamo effettuato la modifica al servizio R006 omettendo il codice fiscale del firmatario visto che non l'avevamo trasmesso nella validazione dell'evento e quindi adesso trasmettiamo solo nome, cognome, sesso e dataNascita che erano stati trasmessi nella validazione evento ma il servizio continua a rispondere:
{"errors":[{"code":"500","severity":"E","text":"Errore interno"}],"testataRisposta":{"idComune":6498,"idEsito":999,"idOperazione":"1710284","idOperazioneComune":"564"}}

Grazie.

**Comment by LucaBonini64** [comment]
Anche per questi casi comunque vi chiediamo cortesemente di implementare dei messaggi d'errore più significativi di "Errore Interno"
Grazie.

**Comment by gbuemi** [comment]
Buonasera,
la request inviata non è formalmente corretta, non è presente la struttura **firmaDichiaranteInput** si rimanda alla documentazione https://github.com/italia/ansc/blob/main/docs/openapi/R006_firma_dichiarante.yaml. 

A seguire la request corretta per l'evento in questione (a meno del contenuto non incollato per comodità)
`{
	"testataRichiesta": {
        "dataOraRichiesta": "2023-11-27T15:56:00.5063765+01:00",
        "fornitoreApplicativo": "APKAPPA S.r.l.",
        "idComune": 6498,
        "idOperazioneComune": "564",
        "nomeApplicativo": "hyperSIC.StatoCivile",
        "versioneApplicativo": "9.23.15.00.1M02"
    },
	"firmaDichiaranteInput": {
		"contenuto": "...",
		"idEvento": "1214551",
		"listaFirmatari": [
			{
				"cognome": "CAPRA",
				"dataNascita": "1980-06-04",
				"nome": "LUCA",
				"sesso": "M"
			}
		],
		"nomefile": "MO_000023789_98_000_000_00.pdf",
		"tipoAllegato": "999",
		"tipoFile": "1"
	}
}`
