### ISSUE TITLE
Sovrapposizione righe in estratto per firma cartacea

### ISSUE THREAD

**Issue by LucaBonini64** [italia/ansc#513]
Buongiorno,
vi segnalo che, nel caso in cui il numero di Atto ANSC sia molto lungo, il numero di atto si sovrappone ai dati anagrafici dell'intestatario.

Allego un esempio
[anteprima.pdf](https://github.com/italia/ansc/files/13477390/anteprima.pdf)

Cordiali saluti

**Comment by LucaBonini64** [comment]
Buongiorno,
non riesco a capire come possa essere in un formato non previsto quando Sogei ha indicato che l'id di ANSC era una stringa di 80 caratteri e il numero comunale una stringa che poteva arrivare a 20 caratteri, per questo motivo abbiamo fatto un progressivo unico ma che ci consentisse di mantenere una struttura congrua con gli atti cartacei che il comune gestirà ancora per decenni.
Anche la lunghezza a 5 cifre con un sequenziale mi sembra riduttiva in quanto il comune di Genova crea ogni anno più di 27.000 atti di stati civile, con il tempo spariranno le trascrizioni ma nel giro di qualche anno il sequenziale di Genova arriverà alla sesta cifra e quindi il sequenziale dovrà essere annuale. 
Non vi sembra una modifica un po' pesante da fare dopo un anno di sviluppo solo perché chi ha sviluppato il report segnalato non ha tenuto conto della lunghezza delle stringhe?

Cordiali saluti

Luca Bonini APKAPPA

**Comment by mttfranci** [comment]
Salve. 

I limiti di 80 e di 20 a cui fate riferimento, sono relativi alle [specifiche degli eventi digitali di stato civile in ANPR](https://github.com/italia/anpr/issues/3625) pubblicate oltre un anno quando per l'anagrafe abbiamo deciso di mantenere il limite più alto di quello definitivo, visto che non è l'anagrafe l'owner dell'informazione.

Quello da tenere in considerazione è il [limite pubblicato per ANSC](https://www.anagrafenazionale.interno.it/wp-content/uploads/Gestione-della-nuova-numerazione-degli-atti-digitali-per-comuni-che-non-hanno-ancora-aderito-1.pdf) con il rilascio del sistema.

Una nota magari non chiara : 
* Il numero nazionale (a 10 cifre) è assegnato dal sistema ANSC e non viene mai resettato.
* Il numero comunale (a 5 cifre) è assegnato dal comune, è valido solo nell'anno, e secondo una indicazione condivisa anche con ANUSCA dovrebbe essere usato analogamente al numero atto comunale degli atti cartacei e qindi ripartire da 1 ogni anno.

Questo anche perchè tali identificativi nascono nello stato civile e vengono solo recepiti dall'anagrafe.

Potete fare riferimento anche alla issue #526.

Saluti 

Assistenza ANSC
