### ISSUE TITLE
Errore firma digitale con credenziali reali

### ISSUE THREAD

**Issue by antonioluberto** [italia/ansc#514]
Buongiorno.
Dal Comune di Grottaferrata abbiamo appena provato ad eseguire la sottoscrizione di un atto digitale con credenziali reali (Aruba).
Il tentativo però fallisce con errore
"406007 : Firma Remota non avvenuta con successo"
Il riferimento al test appena eseguito è:
"idOperazione":"1709762".

Rimaniamo in attesa di vostro riscontro.

**Comment by amusarra** [comment]
Salve @antonioluberto 
Analizzando i log dei sistemi, il servizio di Aruba restituisce l'errore: `Errore servizio firma remota: 0003: Invalid User Credentials`

Consiglio quindi di verificare che le credenziali fornite siano corrette, OTP compreso.

Cordiali Saluti.
Supporto ANSC.

**Comment by amusarra** [comment]
Buongiorno @antonioluberto 
Chiudiamo questa issue.

Cordiali Saluti.
Supporto ANSC.
