### ISSUE TITLE
[R010] Anteprima riconoscimenti prenatali (12214300) - Segnalazione firmatari

### ISSUE THREAD

**Issue by COlivatoADS** [italia/ansc#516]
Ambiente di produzione Valeggio sul Mincio.
Id atto 2023-934-50-023089
Il cliente segnala che a fronte di due firmatari viene riportato lo spazio per la firma di un solo dichiarante.
Problema riscontrato anche in ambiente di pre-produzioe (Id atto 2023‐1214714‐1000000396‐039010).

Grazie

**Comment by asqueglia** [comment]
Buongiorno, verifichiamo e le facciamo sapere

**Comment by asqueglia** [comment]
Buongiorno, comunichiamo che abbiamo preso in carico la segnalazione e provvederemo a correggere quanto prima il modulo per presa visione.
Durante la verifica però ci siamo accorti che in merito all'atto registrato in ambiente di pre-produzione 2023‐1214714‐1000000396‐039010, è stato allegato come processo verbale, un modulo che non ha nulla a che fare con l'atto in questione; è stato allegato un file diverso da quello generato dal sistema per l'atto stesso.
Abbiamo effettuato la verifica anche in ambiente di produzione, per l'atto 2023-934-50-023089, e abbiamo notato che i file che sono stati allegati, sia come processo verbale e sia come certificato, pur essendo dei pdf che hanno passato la verifica di formato, presentano un contenuto assolutamente non leggibile. Forse qualche errore di scannerizzazione ? Questa cosa ci preoccupa non poco. Vi preghiamo di controllare.

**Comment by COlivatoADS** [comment]
Buongiorno, per quanto riguarda l'atto in pre-produzione confermiamo di aver allegato un documento diverso, non relativo all'atto indicato (questo al solo fine di velocizzare il processo di test).
Per quanto riguarda invece l'atto in ambiente di produzione (2023-934-50-023089) abbiamo verificato che i file allegati risultano .p7m  e che anche nella richiesta sono stati passati con tipo file 4, coerentemente con il valore indicato nei file di decodifica.  Grazie
