### ISSUE TITLE
[ws R009] Validazione Evento - Annotazione: modifica composizioneCompleta / flagSecretato

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/ansc#517]
ambiente PRE - comune di FAENZA (idComune 3743)

due segnalazioni:

1. idAttoAnsc: 2023-1214696-444-039010
. ad una prima richiesta di validazione (idOperazioneAnsc: 1711364) è stata inviata l'annotazione con questa caratteristica:
"composizioneCompleta": "DA MODIFICARE - annotazione da altro comune"
. ad una seconda richiesta (idOperazioneAnsc: 1711366) - prima di firmare l'annotazione - è stata inviata la seguente modifica:
"composizioneCompleta": "MODIFICATA - annotazione da altro comune"
la variazione della "composizioneCompleta" non viene quindi recepita dal sistema e rimane il vecchio testo dell'annotazione.
verificato da servizio di anteprima (ws R010), servizio di consultazione (ws R005) e servizio di certificazione (ws R002)

2. idAttoAnsc: 2023-1214597-437-039010
siamo riusciti ad inviare un'annotazione con queste caratteristiche:
. flagsecretato '1' (attivo)
. flagAnnotazioneNonCertificabile 'false' (annotazione certificabile)
l'annotazione risulta presente sull'estratto.
ci saremmo aspettati che la caratteristica di "secretato" superasse qualsiasi altra opzione ai fini della certificazione.
potete chiarirci come gestisce il sistema questa combinazione di metaDati?

grazie
Alessandro Monopoli ADS

**Comment by asqueglia** [comment]
Buongiorno, verifichiamo e le facciamo sapere

**Comment by asqueglia** [comment]
Buonasera, per quanto riguarda il primo punto abbiamo preso in carico la segnalazione e apporteremo la correttiva il prima possibile,.
Per quanto riguarda il secondo punto invece, comunichiamo che il dato flagsecretato è un dato di sistema; viene assegnato automaticamente dal sistema per i soli casi d'uso di eventi o annotazioni che prevedono la secretazione delle informazioni; per cui il dato trasmesso non viene preso in considerazione. Per rendere più chiaro il funzionamento, nel caso in cui venga trasmesso il dato flagsecretato, provvederemo a restituire un messaggio di warning esplicativo del tipo 'Il dato flagsecretato trasmesso non verrà preso in considerazione, in quanto è un dato gestito automaticamente da sistema'.

**Comment by asqueglia** [comment]
@AMonopoliADS  avete ragione e ringraziamo per la riflessione. Faremo opportune verifiche e approfondimento del caso

**Comment by asqueglia** [comment]
Buongiorno, con il rilascio della versione 1.21.0 la segnalazione dovrebbe essere risolta. Chiudiamo pertanto la issue. In caso di ulteriori segnalazioni si prega di aprire una issue dedicata.
