### ISSUE TITLE
[R005] - ricerca intestatario - Nessun risultato trovato tramite ricerca con dati anagrafici

### ISSUE THREAD

**Issue by LucaBonini64** [italia/ansc#518]
Buongiorno,
la ricerca degli intestatari su ANPR utilizzando i soli dati anagrafici non trova nessun risultato anche se la persona risulta presente su ANPR con gli stessi identici dati, la response restituita è:
{
  "testataRisposta": {
    "idComune": 6498,
    "idOperazioneComune": "LB20231129125600",
    "idOperazione": "1711695",
    "idEsito": 0
  },
  "datiPaginazione": {
    "numPagina": 1,
    "numRecordPagina": 30,
    "numRecordTotali": 0
  },
  "soggetti": []
}
Mentre la ricerca della stessa persona passando nei criteri di ricerca l'ID ANPR restituisce il risultato (vedi  "idOperazione": "1711696").

Anche dalla Web Application il risultato è medesimo, cioè se si utilizza la ricerca per dati anagrafici non trova nessuna corrispondenza mentre la ricerca per identificativo restituisce la persona.

Potete verificare per cortesia?

Grazie.

**Comment by amusarra** [comment]
Salve @LucaBonini64 
Abbiamo preso in carico la sua segnalazione.

Cordiali Saluti.
Supporto ANSC.

**Comment by asqueglia** [comment]
Buongiorno, con il rilascio della versione 1.21.0 la segnalazione dovrebbe essere risolta. Chiudiamo pertanto la issue. In caso di ulteriori segnalazioni si prega di aprire una issue dedicata.
