### ISSUE TITLE
[R013] rettifica evento di tipo Annotazione

### ISSUE THREAD

**Issue by siscomanpr** [italia/ansc#519]
Buongiorno,
abbiamo registrato un'annotazione a fronte di un atto di nascita e successivamente provato a modificare la stessa annotazione con una rettifica con il servizio R013 e il caso d'uso 14640000 (errore materiale). Il sistema ha accettato e validato l'annotazione di rettifica (l'abbiamo poi anche firmata); quindi fin qui tutto bene.
Il problema che abbiamo rilevato è che se poi andiamo a rilasciare un estratto dell'atto di nascita su cui era stata registrata la prima annotazione (che poi è stata rettificata), questa non risulta aggiornata con quanto inviato con la rettifica.

Invio i riferimenti delle operazioni svolte:

Ambiente pre-produzione - Serravalle Sesia
idANSC dell'atto di nascita: 2023-1212586-348-002137
idANSC della prima annotazione: 2023-1214856-389-002137 
idOperazione della rettifica: 1712486 (fatta con servizio R013)

il paypload della rettifica è il seguente:

{
    "evento": {
        "idTipoEvento": "1",
        "idtipocontenuto": "2",
        "idUsecase": "14640000",
        "descrizioneCasoUso": "Annotazione per errore materiale",
        "stato": "CONFERMATO",
        "idVersion": "100006",
        "dataformazione": "2023-11-30",
        "annoAtto": "2023",
        "ora": "14",
        "minuto": "45",
        "operatore": "MCCMRA80T21B111E",
        "operatoreNome": "ANNA",
        "operatoreCognome": "URBAN",
        "idComuneRegistrazione": "9419",
        "nomeComuneRegistrazione": "SERRAVALLE SESIA",
        "idProvinciaRegistrazione": "2",
        "siglaProvinciaRegistrazione": "VC",
        "numeroatto": "390",
        "datiRettifica": {
            "eventoCollegato": {
                "id": "1214856",
                "idAnsc": "2023-1214856-389-002137",
                "idComuneRegistrazione": "9419",
                "nomeComuneRegistrazione": "SERRAVALLE SESIA",
                "idProvinciaRegistrazione": "2",
                "siglaProvinciaRegistrazione": "VC",
                "numeroatto": "389",
                "dataformazione": "2023-11-30",
                "annoAtto": "2023",
                "tipologia": "1"
            },
            "idTipoRettifica": "1"
        },
        "composizioneCompleta": "Si provvede alla correzione dell'errore materiale sull'atto controscritto, là dove si legge: PROVA deve invece leggersi: ROMA",
        "flagAnnotazioneNonCertificabile": false
    },
    "eventoModificato": {
        "idAnsc": "2023-1214856-389-002137",
        "idTipoEvento": "1",
        "idtipocontenuto": "2",
        "idUsecase": "14400000",
        "dataformazione": "2023-11-30",
        "ora": "14",
        "minuto": "42",
        "numeroatto": "389",
        "eventoCollegato": {
            "id": "1212586",
            "idAnsc": "2023-1212586-348-002137",
            "idComuneRegistrazione": "9419",
            "nomeComuneRegistrazione": "SERRAVALLE SESIA",
            "idProvinciaRegistrazione": "2",
            "siglaProvinciaRegistrazione": "VC",
            "idtipocontenuto": "1",
            "numeroatto": "348",
            "dataformazione": "2023-10-27",
            "annoAtto": "2023",
            "tipologia": "1"
        },
        "composizioneCompleta": "Con atto in data …, QUARANTANOVE MATTIA, nato a SERRAVALLE SESIA (VC), il 24/10/2023, mi ha dichiarato che gli elementi del nome attribuiti allo stesso alla nascita devono essere riportati negli estratti per riassunto e nei certificati rilasciati dagli ufficiali dello stato civile e d’anagrafe, nel modo seguente: ROMA"
    },
    "testataRichiesta": {
        "idComune": 9419,
        "idOperazioneComune": "202300000000000000000000034201",
        "dataOraRichiesta": "2023-11-30T14:45:25.6695931+01:00",
        "nomeApplicativo": "SESAMOWEB",
        "versioneApplicativo": "1.0.1.0",
        "fornitoreApplicativo": "SISCOM"
    }
}

Potete controllare se c'è un errore nella chiamata o per quale motivo l'annotazione non viene rettificata?
Grazie.

**Comment by amusarra** [comment]
Salve @siscomanpr 
Abbiamo preso in carico la segnalazione per le verifiche.

Cordiali Saluti.
Supporto ANSC.

**Comment by amusarra** [comment]
Salve @siscomanpr 
Non è possibile fare un annotazione su altra annotazione ma sull'evento.
Nei prossimi rilasci sarà inserito un controllo che bloccherà quest'operazione non consentita.

Cordiali Saluti.
Supporto ANSC.

**Comment by siscomanpr** [comment]
Salve @amusarra 
Nella scorsa riunione è stato detto che per modificare un'annotazione errata (es. errore ortografico o altro errore), la strada era quella di fare una nuova annotazione (caso d'uso per correzione errore materiale), quindi abbiamo pensato che fosse sufficiente indicare nell'eventoModificato l'evento di tipo Annotazione che si intende correggere.
Se questa non è la procedura corretta, potete indicarci come correggere un'annotazione errata?
Grazie.

**Comment by amusarra** [comment]
Buongiorno @siscomanpr 
Dovreste registrare un nuovo evento di tipo **Annotazione Per Errore Materiale** specificando come evento collegato, l'evento originale e non la prima rettifica fatta.

Cordiali Saluti.
Supporto ANSC.

**Comment by siscomanpr** [comment]
Ho fatto una prova compilando come evento collegato l'atto originale ma ricevo un errore bloccante:
`L'idAnsc dell'Evento collegato non corrisponde all'eventoModificato`

Il problema è che l'eventoModificato non può corrispondere all'evento collegato perché a noi interessa modificare l'evento di tipo "Annotazione" (2023-1214856-389-002137) e non l'evento dell'atto originale. Ed è per questo che inizialmente avevamo compilato il json in quel modo.

Questo è il json con la modifica come da voi indicato:
{
    "evento": {
        "idTipoEvento": "1",
        "idtipocontenuto": "2",
        "idUsecase": "14640000",
        "descrizioneCasoUso": "Annotazione per errore materiale",
        "stato": "CONFERMATO",
        "idVersion": "100006",
        "dataformazione": "2023-12-05",
        "annoAtto": "2023",
        "ora": "11",
        "minuto": "22",
        "operatore": "MCCMRA80T21B111E",
        "operatoreNome": "ANNA",
        "operatoreCognome": "URBAN",
        "idComuneRegistrazione": "9419",
        "nomeComuneRegistrazione": "SERRAVALLE SESIA",
        "idProvinciaRegistrazione": "2",
        "siglaProvinciaRegistrazione": "VC",
        "numeroatto": "392",
        "datiRettifica": {
            "eventoCollegato": {
                "id": "1212586",
                "idAnsc": "2023-1212586-348-002137",
                "idComuneRegistrazione": "9419",
                "nomeComuneRegistrazione": "SERRAVALLE SESIA",
                "idProvinciaRegistrazione": "2",
                "siglaProvinciaRegistrazione": "VC",
                "idtipocontenuto": "1",
                "numeroatto": "348",
                "dataformazione": "2023-10-27",
                "annoAtto": "2023",
                "tipologia": "1"
            },
            "idTipoRettifica": "1"
        },
        "composizioneCompleta": "Si provvede alla correzione dell'errore materiale sull'atto controscritto, là dove si legge: ROMA deve invece leggersi: PROVAAA",
        "flagAnnotazioneNonCertificabile": false
    },
    "eventoModificato": {
        "idAnsc": "2023-1214856-389-002137",
        "idTipoEvento": "1",
        "idtipocontenuto": "2",
        "idUsecase": "14400000",
        "dataformazione": "2023-11-30",
        "ora": "14",
        "minuto": "42",
        "numeroatto": "389",
        "eventoCollegato": {
            "id": "1212586",
            "idAnsc": "2023-1212586-348-002137",
            "idComuneRegistrazione": "9419",
            "nomeComuneRegistrazione": "SERRAVALLE SESIA",
            "idProvinciaRegistrazione": "2",
            "siglaProvinciaRegistrazione": "VC",
            "idtipocontenuto": "1",
            "numeroatto": "348",
            "dataformazione": "2023-10-27",
            "annoAtto": "2023",
            "tipologia": "1"
        },
        "composizioneCompleta": "Con atto in data …, QUARANTANOVE MATTIA, nato a SERRAVALLE SESIA (VC), il 24/10/2023, mi ha dichiarato che gli elementi del nome attribuiti allo stesso alla nascita devono essere riportati negli estratti per riassunto e nei certificati rilasciati dagli ufficiali dello stato civile e d’anagrafe, nel modo seguente: ROMA"
    },
    "testataRichiesta": {
        "idComune": 9419,
        "idOperazioneComune": "202300000000000000000000034330",
        "dataOraRichiesta": "2023-12-05T11:22:40.6160064+01:00",
        "nomeApplicativo": "SESAMOWEB",
        "versioneApplicativo": "1.0.1.0",
        "fornitoreApplicativo": "SISCOM"
    }
}

idOperazione:1715578

Sarebbe possibile avere un esempio di come deve essere compilato il payload di una rettifica di un'annotazione per correggere un errore materiale?

**Comment by asqueglia** [comment]
Buongiorno, il sistema non prevede la rettifica di una annotazione ma solo di un evento. Inoltre abbiamo verificato l'annotazione da voi inviata con id 1214856 e non riusciamo a capire a quale formula si riferisca nel formulario vigente. Con ANUSCA è stato espressamente indicato che le solo formule da utilizzare sono quelle del formulario previsto dal dpr 396/2000. La formula da voi utilizzata in composizione ci fa pensare ad una annotazione rettificativa con cui modificare l'anagrafica del soggetto intestatario. Vogliamo chiarire che il caso d'uso di servizio per annotazione (da altro comune) oppure da altra amministrazione, si riferisce solo ed esclusivamente ad annotazioni integrative e non ad annotazioni modificative. Verificheremo comunque con ANUSCA / Dipartimento, quanto riportato.

**Comment by asqueglia** [comment]
Può essere che ci siamo capiti male nella scorsa riunione. Non è prevista nel sistema, la rettifica di una annotazione. E' possibile solo rettificare un atto ma non una annotazione.

**Comment by asqueglia** [comment]
Buongiorno da un approfondimento con ANUSCA, confermiamo che sarà prevista nel corso del 2024, la funzionalità che consentirà di rettificare una annotazione.

**Comment by siscomanpr** [comment]
Grazie per aver approfondito. 
Facciamo solo presente che il comune di Serravalle Sesia ha già un paio di casi di annotazioni da correggere per errori di battitura, quindi, onde evitare il rilascio di estratti errati, riteniamo che questa implementazione debba avere una priorità alta.
