### ISSUE TITLE
R010 - Errore anteprima per caso d'uso 311111 - Matr_001

### ISSUE THREAD

**Issue by ManuelDeMeo** [italia/ansc#52]
- Ambiente preprod
- Data test: 04/04/2023

Buongiorno, dopo aver regolarmente inviato un atto di matrimonio (caso d'uso Matr_001 Id: 311111) con servizio R009 ("idOperazione":"1575271"), la richiesta anteprima (R010 /anteprima/evento/1) da errore.

Allego richiesta e risposta:

Richiesta:
`{"presaVisione":false,"evento":{"id":"950787","idAnsc":"2023-950787-9-058046","idTipoEvento":null,"idtipocontenuto":null,"idUsecase":"311111","descrizioneCasoUso":null,"stato":null,"dataformazione":null,"annoAtto":null,"meseAtto":null,"giornoAtto":null,"ora":null,"minuto":null,"operatore":null,"ruoloOperatore":null,"operatoreNome":null,"operatoreCognome":null,"redattoNellaCasaComunale":null,"luogoRedazione":null,"idComuneRegistrazione":null,"nomeComuneRegistrazione":null,"idProvinciaRegistrazione":null,"siglaProvinciaRegistrazione":null,"dataDecorrenza":null,"numeroatto":null,"tipoDichiarante":null,"ausilioInterprete":null,"conTestimoni":null,"noteRitardo":null,"motivoAnnullamento":null,"tipoConsenso":null,"certificabile":null,"datiRiconoscimento":null,"sentenzaFiglioIncestuoso":null,"propostaAnnotazione":null,"datiProdotti":null,"allegati":null,"intestatari":null,"variazioni":null,"enteDichiarante":null,"ufficialeStatoCivile":null,"madre":null,"padre":null,"coniuge":null,"dichiarante":null,"interprete":null,"datiDichiarante":null,"datiDiNascita":null,"datiDiMorte":null,"datiRinvenuto":null,"datiEventoRiconoscimento":null,"datiEventoCittadinanza":null,"datiEventoMatrimonio":null,"datiEventoUnioneCivile":null,"riconoscimentoMadre":null,"riconoscimentoPadre":null,"riconoscimento":null,"consenso":null,"consensoMadre":null,"consensoPadre":null,"attoNotarileConsensoMadre":null,"attoNotarileConsensoPadre":null,"trascrizioneNascita":null,"trascrizioneCittadinanza":null,"trascrizioneMorte":null,"trascrizioneMatrimonio":null,"trascrizioneUnioneCivile":null,"trascrizioneSeparazione":null,"riconciliazione":null,"separazione":null,"negoziazioneAssistita":null,"scioglimentoUnioneCivile":null,"tribunale":null,"eventoCollegato":null,"datiAnnotazione":null,"datiEventoMorte":null,"datiAssenso":null,"datiRettifica":null,"datiLingua":null,"composizioneCompleta":null,"idRiconoscimentoSentenza":null},"testataRichiesta":{"idComune":4559,"idOperazioneComune":"2","dataOraRichiesta":"1","nomeApplicativo":"testSC","versioneApplicativo":"1.0.0","fornitoreApplicativo":"Test"},"datiPaginazione":null}`

Risposta:
`{"testataRisposta":{"idComune":4559,"idOperazioneComune":"2","idOperazione":"1575273","idEsito":1},"errors":[{"code":"400003","severity":"E","text":"Dati in ingresso non corretti"}]}`

**Comment by amusarra** [comment]
Buongiorno @ManuelDeMeo 
La segnalazione è stata presa in carico e segnata come bug.

Saluti.

**Comment by asqueglia** [comment]
Buongiorno, la segnalazione è stata corretta con la versione 1.8.0 appena rilasciata.
