### ISSUE TITLE
Usecase 1351	Trascrizione provvedimento straniero di adozione	(Trascr_018)

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#520]
Buongiorno,
in riferimento alle modifiche elencate nella versione 1.19.5 : i dati del padre e della madre sono stati resi obbligatori o meno in base al valore di evento.trascrizioneNascita.tipoRiconoscimento.
Mi aspettavo che nel mapping ci fosse anche un tag con questo valore e non c'è.
Sono andata a controllare sulla webapp e non esiste nessun campo per fare tale scelta e i dati sia del padre che della madre sono sempre obbligatori.

A questo punto direi che il mapping sia errato con l'indicazione di obbligatorietà in base a evento.trascrizioneNascita.tipoRiconoscimento.

Attendo Vostra conferma per non fare modifiche al software inutili.
Grazie

**Comment by asqueglia** [comment]
Buongiorno comunichiamo che con il rilascio odierno della versione 1.23.0 la segnalazione in oggetto è stata corretta; provvediamo quindi a chiudere la issue. In caso di ulteriori malfunzionamenti si prega di aprire una issue dedicata.
