### ISSUE TITLE
Usecase 1352	Trascrizione del provvedimento straniero di adozione di minore riconosciuto valido dal Tribunale dei minori (convenzione Aja 29.5.1993)	(Trascr_019)

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#521]
Stesso problema esposto nel ticket #520

**Comment by asqueglia** [comment]
Buongiorno comunichiamo che con il rilascio odierno della versione 1.23.0 la segnalazione in oggetto è stata corretta; provvediamo quindi a chiudere la issue. In caso di ulteriori malfunzionamenti si prega di aprire una issue dedicata.
