### ISSUE TITLE
[R008] Campo "descrizione" versione 1.20.0 mancante nello yaml

### ISSUE THREAD

**Issue by siscomanpr** [italia/ansc#523]
Stavamo implementando la versione 1.12.0 e notavamo che nel changelog è indicato:

- Aggiunto campo "descrizione" nella response NotificheRicercaResponse servizio /notifiche/ricerca/{version}

ma nel file yaml del servizio R008 non è presente alcun riferimento a quel campo nell'oggetto NotificheRicercaResponse, ne tantomeno negli altri oggetti del servizio, è corretto?

**Comment by asqueglia** [comment]
Buongiorno, il campo che viene restituito e valorizzato nella resposnse del servizio R008 è 'descrizione' all'interno del ModelNotifica

![image](https://github.com/italia/ansc/assets/29303629/e50b6edd-7bf0-4c50-8874-0ce1d93ee968)

**Comment by siscomanpr** [comment]
ok, grazie
