### ISSUE TITLE
versione 1.20   Limite lunghezza numeroatto comunale a 5 

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#526]
Buongiorno,
una volta la numerazione non era univoca quindi per ogni registro/parte/serie gli atti partivano da 1 e potevano arrivare a 99.999  al massimo. Estremamente difficile, ad esempio, 100milla nascite in p.1 s.A.
Adesso che la numerazione è univoca per qualsiasi registro, non è che sarà possibile lo sforamento dei 99.999 atti? Penso soprattutto ai Comuni più grandi: come Roma per citarne il più grande.
Non essendo un nostro cliente non ho modo per capire se è il mio dubbio è fondato o meno.

**Comment by mttfranci** [comment]
Buongiorno, Grazie della considerazione, 

Al momento le [specifiche](https://www.anagrafenazionale.interno.it/wp-content/uploads/Gestione-della-nuova-numerazione-degli-atti-digitali-per-comuni-che-non-hanno-ancora-aderito-1.pdf) condivise prevedono tale limite.

Se dovessero esserci delle ulteriori esigenze valuteremo come procedere. 

Saluti

Assistenza ANSC

**Comment by asqueglia** [comment]
Chiudiamo la issue
