### ISSUE TITLE
[R009] Validazione atto di morte con caso d'uso 2299 - flagDichiarante obbligatorio per soggetto Deceduto

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#529]
REQUEST:
{
    "evento": {
        "idAnsc": "",
        "idTipoEvento": "2",
        "idtipocontenuto": "3",
        "idUsecase": "2299",
        "stato": "CONFERMATO",
        "idVersion": "100006",
        "dataformazione": "2023-12-06",
        "ora": "12",
        "minuto": "37",
        "operatore": "DLCNTN57L67A064W",
        "operatoreNome": "MARGHERITA",
        "operatoreCognome": "CITTERIO",
        "idComuneRegistrazione": "5000",
        "nomeComuneRegistrazione":
        "LISSONE",
        "idProvinciaRegistrazione": "108",
        "siglaProvinciaRegistrazione": "MB",
        "dataDecorrenza": "2023-12-06",
        "oraDecorrenza": "12",
        "minutoDecorrenza": "37",
        "numeroatto": "15",
        "allegati": [{
                "id": "2243263",
                "idTipoAllegato": "998",
                "hashAllegato": "nL3ZkIm1N+AMXwp1FMAYZ2ba8aLktw4W5sRVP9sCqns\u003d",
                "descrizione": "ATTO N.1728 P.II S.B 2023"
            }
        ],
        "intestatari": [{
                "cognome": "BINOTTO",
                "nome": "GUGLIELMA",
                "sesso": "F",
                "dataNascita": "1929-11-13",
                "idComuneNascita": "1323",
                "nomeComuneNascita": "BRUGINE",
                "idProvinciaNascita": "28",
                "siglaProvinciaNascita": "PD",
                "idStatoNascita": "90",
                "nomeStatoNascita": "ITALIA",
                "idComuneResidenza": "5000",
                "nomeComuneResidenza": "LISSONE",
                "idProvinciaResidenza": "108",
                "siglaProvinciaResidenza": "MB",
                "idStatoResidenza": "90",
                "nomeStatoResidenza": "ITALIA",
                "idNazionalita": "90",
                "nazionalita": "ITALIANA"
            }
        ],
        "datiDiMorte": {
            "idComuneMorte": "6217",
            "nomeComuneMorte": "MONZA",
            "idProvinciaMorte": "108",
            "siglaProvinciaMorte": "MB",
            "idStatoMorte": "90",
            "nomeStatoMorte": "ITALIA",
            "luogoMorte": "Presidio Ospedaliero Fondazione IRCCS San Gerardo dei Tintori",
            "indirizzoMorte": "Presidio Ospedaliero Fondazione IRCCS San Gerardo dei Tintori",
            "dataMorte": "2023-12-04",
            "oraMorte": "21",
            "minutoMorte": "30"
        },
        "composizioneCompleta": " Oggi ............"
    },
    "testataRichiesta": {
        "idComune": 5000,
        "idOperazioneComune": "2880",
        "dataOraRichiesta": "2023-12-06T13:02:07.893+01:00",
        "nomeApplicativo": "urbi",
        "versioneApplicativo": "0.1.0",
        "fornitoreApplicativo": "padigitale"
    }
}

RESPONSE:
{
    "testataRisposta": {
        "idComune": 5000,
        "idOperazioneComune": "2880",
        "idOperazione": "1716656",
        "idEsito": 1
    },
    "errors": [{
            "code": "400003",
            "severity": "E",
            "text":
            "Il campo evento.intestatari[0].flagDichiarante nella sezione Deceduto è obbligatorio"
        }
    ],
    "infos": [{
            "code": "110527",
            "severity": "I",
            "text": "Informazioni sull'operazione da fornire in caso di assistenza : data:2023-12-06 12:02:09 , idOperazione:1716656"
        }
    ]
}

**Comment by asqueglia** [comment]
Buongiorno sicuramente prendiamo in carico la correttiva. 
Se comunque volete andare avanti con i test è sufficiente inserire i seguenti dati nella sezione intestatario, del payload indicato,
"flagComparente": false" 
"flagDichiarante": false,
 "flagFirmatario": false

**Comment by asqueglia** [comment]
Con la versione 1.22.0 è stata corretta la segnalazione. Chiudiamo pertanto la issue. In caso di ulteriori segnalazioni preghiamo di aprire una issue dedicata
