### ISSUE TITLE
R009 - Errore allegato obbligatorio - Casi d'uso Dic_Nasc_033 e Dic_Nasc_076

### ISSUE THREAD

**Issue by ManuelDeMeo** [italia/ansc#53]
- Ambiente: preprod
- Data test: 05/04/2023

Buongiorno, segnaliamo un errore che riceviamo invocando il servizio R009 /validazione/evento/1 per due casi d'uso: Dic_Nasc_033 (Id: 11214000 ) e Dic_Nasc_076 (Id: 11424020).

In entrambi i casi otteniamo in risposta un errore che indica che c'è un allegato obbligatorio mancante [Procura]. In entrambi i casi questa tipologia di allegato è stata inviata.

Allego le due coppie di richieste e risposte (nelle richieste ho rimosso i dati relativi ai soggetti):

Richiesta1:
`{"evento":{"id":null,"idAnsc":null,"idTipoEvento":"1","idtipocontenuto":"1","idUsecase":"11424020","descrizioneCasoUso":"Dichiarazione tardiva di filiazione fuori del matrimonio, resa dal procuratore del padre di bimbo riconosciuto dalla madre prima della nascita","stato":"CONFERMATO","dataformazione":"2023-03-31","annoAtto":null,"meseAtto":null,"giornoAtto":null,"ora":"12","minuto":"23","operatore":"DMEMNL86C26C351C","ruoloOperatore":"SOSTITUTOSINDACO","operatoreNome":"Manuel","operatoreCognome":"De Meo","redattoNellaCasaComunale":null,"luogoRedazione":null,"idComuneRegistrazione":null,"nomeComuneRegistrazione":"GROTTAFERRATA","idProvinciaRegistrazione":null,"siglaProvinciaRegistrazione":"RM","dataDecorrenza":null,"numeroatto":"2","tipoDichiarante":"4","ausilioInterprete":"NO","conTestimoni":null,"noteRitardo":"Indicazione motivo ritardo","motivoAnnullamento":null,"tipoConsenso":null,"certificabile":"1","datiRiconoscimento":null,"sentenzaFiglioIncestuoso":null,"propostaAnnotazione":null,"datiProdotti":"2","allegati":[{"id":"1860555","idTipoAllegato":"6","hashAllegato":"tN1YkA/GzKHv0DKGpKtSWYPD5ofQT/gMxPcJ3Oigk6M=","descrizione":"Procura"}],"intestatari":[{***, "flagDichiarante":false,"flagComparente":false,"flagFirmatario":false}],"variazioni":null,"enteDichiarante":null,"ufficialeStatoCivile":null,"madre":{"flagDichiarante":false,"flagComparente":false,"flagFirmatario":false},"padre":{"flagDichiarante":false,"flagComparente":false,"flagFirmatario":true},"coniuge":null,"dichiarante":{"flagDichiarante":true,"flagComparente":true,"flagFirmatario":false},"interprete":null,"datiDichiarante":{"ruolo":null,"tipoProcura":"2","datiEssenzialiProcura":"Descrizione Procura","titoloDichiarante":null,"dichiarazioneCongiunta":null,"comprensione":"0","motivoImpedimentoScrittura":null},"datiDiNascita":{"luogoFiliazione":null,"indirizzoEvento":null,"sceltaCognome":"3","oraNascita":"00","minutoNascita":"00","precisazioneCognome":null,"natoMorto":"NO","natoVivoMaDeceduto":"NO","numeroGemelli":null,"partoGemellare":null,"progressivoGemello":null,"attiGemelliPrec":null,"attiGemelliSucc":null,"tipoAccertamento":"3"},"datiDiMorte":null,"datiRinvenuto":null,"datiEventoRiconoscimento":null,"datiEventoCittadinanza":null,"datiEventoMatrimonio":null,"datiEventoUnioneCivile":null,"riconoscimentoMadre":{"avvenuto":true,"autorizzazione":null,"certificato":null,"atto":{"idAnsc":null,"idComuneRegistrazione":"8183","nomeComuneRegistrazione":"ROMETTA","idProvinciaRegistrazione":"83","siglaProvinciaRegistrazione":"ME","ente":null,"idtipocontenuto":"Atto","redattoNellaCasaComunale":null,"luogoRedazione":null,"numeroatto":"22","dataformazione":"2023-03-23","annoAtto":"2023","meseAtto":null,"giornoAtto":null,"oraAtto":null,"minutoAtto":null,"dataAtto":null,"tipologia":"Nascita","parte":"Parte I","serie":"Serie A","estremi":null,"operatoreNome":null,"operatoreCognome":null,"ruoloOperatore":null}},"riconoscimentoPadre":null,"riconoscimento":null,"consenso":null,"consensoMadre":null,"consensoPadre":null,"attoNotarileConsensoMadre":null,"attoNotarileConsensoPadre":null,"trascrizioneNascita":null,"trascrizioneCittadinanza":null,"trascrizioneMorte":null,"trascrizioneMatrimonio":null,"trascrizioneUnioneCivile":null,"trascrizioneSeparazione":null,"riconciliazione":null,"separazione":null,"negoziazioneAssistita":null,"scioglimentoUnioneCivile":null,"tribunale":null,"eventoCollegato":null,"datiAnnotazione":null,"datiEventoMorte":null,"datiAssenso":null,"datiRettifica":null,"datiLingua":null,"composizioneCompleta":"*** ","idRiconoscimentoSentenza":null},"testataRichiesta":{"idComune":4559,"idOperazioneComune":"2","dataOraRichiesta":"1","nomeApplicativo":"testSC","versioneApplicativo":"1.0.0","fornitoreApplicativo":"Test"},"datiPaginazione":null}`

Risposta1: 
`{"testataRisposta":{"idComune":4559,"idOperazioneComune":"2","idOperazione":"1575530","idEsito":1},"errors":[{"code":"400003","severity":"E","text":"Allegato obbligatorio mancante: [Procura]"}]}`

Richiesta2:

`{"evento":{"id":null,"idAnsc":null,"idTipoEvento":"1","idtipocontenuto":"1","idUsecase":"11214000","descrizioneCasoUso":"Dichiarazione entro i 10 giorni â€“ resa dal procuratore del padre - Filiazione fuori dal matrimonio con consenso della madre a essere nominata","stato":"CONFERMATO","dataformazione":"2023-03-21","annoAtto":null,"meseAtto":null,"giornoAtto":null,"ora":"13","minuto":"09","operatore":"LNGLNZ86A27C351R","ruoloOperatore":"SOSTITUTOSINDACO","operatoreNome":"LORENZO","operatoreCognome":"LONGHITANO","redattoNellaCasaComunale":null,"luogoRedazione":null,"idComuneRegistrazione":null,"nomeComuneRegistrazione":"GROTTAFERRATA","idProvinciaRegistrazione":null,"siglaProvinciaRegistrazione":"RM","dataDecorrenza":null,"numeroatto":"33","tipoDichiarante":"4","ausilioInterprete":"NO","conTestimoni":null,"noteRitardo":null,"motivoAnnullamento":null,"tipoConsenso":null,"certificabile":"1","datiRiconoscimento":null,"sentenzaFiglioIncestuoso":null,"propostaAnnotazione":null,"datiProdotti":null,"allegati":[{"id":"1858969","idTipoAllegato":"1","hashAllegato":"tN1YkA/GzKHv0DKGpKtSWYPD5ofQT/gMxPcJ3Oigk6M=","descrizione":"Attestazione di nascita"},{"id":"1858977","idTipoAllegato":"2","hashAllegato":"tN1YkA/GzKHv0DKGpKtSWYPD5ofQT/gMxPcJ3Oigk6M=","descrizione":"Constatazione di avvenuto parto"},{"id":"1858979","idTipoAllegato":"3","hashAllegato":"tN1YkA/GzKHv0DKGpKtSWYPD5ofQT/gMxPcJ3Oigk6M=","descrizione":"Dichiarazione di nascita sostitutiva resa da dichiarante"},{"id":"1858890","idTipoAllegato":"6","hashAllegato":"tN1YkA/GzKHv0DKGpKtSWYPD5ofQT/gMxPcJ3Oigk6M=","descrizione":"Procura"}],"intestatari":[{"flagDichiarante":false,"flagComparente":false,"flagFirmatario":false}],"variazioni":null,"enteDichiarante":null,"ufficialeStatoCivile":null,"madre":{"flagDichiarante":false,"flagComparente":false,"flagFirmatario":false},"padre":{"flagDichiarante":false,"flagComparente":false,"flagFirmatario":true},"coniuge":null,"dichiarante":{"flagDichiarante":true,"flagComparente":true,"flagFirmatario":false},"interprete":null,"datiDichiarante":{"ruolo":null,"tipoProcura":"2","datiEssenzialiProcura":"Descrizione Procura aa","titoloDichiarante":null,"dichiarazioneCongiunta":null,"comprensione":"0","motivoImpedimentoScrittura":null},"datiDiNascita":{"luogoFiliazione":null,"indirizzoEvento":null,"sceltaCognome":"3","oraNascita":"00","minutoNascita":"00","precisazioneCognome":null,"natoMorto":"NO","natoVivoMaDeceduto":"NO","numeroGemelli":null,"partoGemellare":null,"progressivoGemello":null,"attiGemelliPrec":null,"attiGemelliSucc":null,"tipoAccertamento":"3"},"datiDiMorte":null,"datiRinvenuto":null,"datiEventoRiconoscimento":null,"datiEventoCittadinanza":null,"datiEventoMatrimonio":null,"datiEventoUnioneCivile":null,"riconoscimentoMadre":null,"riconoscimentoPadre":null,"riconoscimento":null,"consenso":null,"consensoMadre":null,"consensoPadre":null,"attoNotarileConsensoMadre":{"tipologiaTrascrizione":null,"ruoloEnteDichiarante":null,"nomeEnte":"Nome ente","idComuneEnte":"2780","nomeComuneEnte":"CESENA","idProvinciaEnte":"40","siglaProvinciaEnte":"FC","indirizzoEnte":null,"dataTrascrizione":"2023-03-21","descrizione":null,"estremiDocumento":"123","nazioneEnte":null,"nomeNazioneEnte":null},"attoNotarileConsensoPadre":null,"trascrizioneNascita":null,"trascrizioneCittadinanza":null,"trascrizioneMorte":null,"trascrizioneMatrimonio":null,"trascrizioneUnioneCivile":null,"trascrizioneSeparazione":null,"riconciliazione":null,"separazione":null,"negoziazioneAssistita":null,"scioglimentoUnioneCivile":null,"tribunale":null,"eventoCollegato":null,"datiAnnotazione":null,"datiEventoMorte":null,"datiAssenso":null,"datiRettifica":null,"datiLingua":null,"composizioneCompleta":"***","idRiconoscimentoSentenza":null},"testataRichiesta":{"idComune":4559,"idOperazioneComune":"2","dataOraRichiesta":"1","nomeApplicativo":"testSC","versioneApplicativo":"1.0.0","fornitoreApplicativo":"Test"},"datiPaginazione":null}`

Risposta2:
`{"testataRisposta":{"idComune":4559,"idOperazioneComune":"2","idOperazione":"1575534","idEsito":1},"errors":[{"code":"400003","severity":"E","text":"Allegato obbligatorio mancante: [Procura]"}]`

**Comment by asqueglia** [comment]
Buongiorno, con il rilascio della versione 1.6.0 previsto per oggi al massimo domani, la segnalazione da lei indicata sarà risolta. Le faremo sapere quando possibile riprovare.

**Comment by asqueglia** [comment]
Buongiorno, con il rilascio odierno abbiamo risolto la problematica.
