### ISSUE TITLE
Caso d'uso 1312 - TRASCRIZIONE ATTO DI NASCITA AVVENUTA ALL'ESTERO SU RICHIESA DI CHI HA INTERESSE ALLA TRASCRIZIONE

### ISSUE THREAD

**Issue by MarcoSalaPad** [italia/ansc#530]
Buongiorno, la segnalazione riguarda sia la web app che la gestione tramite servizi.

Se viene impostata come tipo richiesta la scelta "VERBALE"

![image](https://github.com/italia/ansc/assets/52407655/11c990fa-5279-4254-82ad-2e5cad9dbc35)

nella sezione degli allegati viene comunque chiesto obbligatoriamente il documento "Richiesta di Trascrizione".

![image](https://github.com/italia/ansc/assets/52407655/0f808103-bcc2-4c7a-9e84-1b03fc441b9e)

Se la richiesta è verbale questo documento in teoria non dovrebbe esserlo.
O c'è qualche motivo che sia noi che il nostro comune di test non stiamo considerando per il quale questo documento è sempre considerato obbligatorio?

Grazie
Pa Digitale Spa

**Comment by asqueglia** [comment]
Buongionro, verifichiamo e le facciamo sapere

**Comment by asqueglia** [comment]
Con la versione 1.22.0 è stata corretta la segnalazione. Chiudiamo pertanto la issue. In caso di ulteriori segnalazioni preghiamo di aprire una issue dedicata
