### ISSUE TITLE
[ANSC vs ANPR] ANPR: Notifica di Predisposizione Anagrafica

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/ansc#533]
ambiente PRE - comune di FAENZA (idComune 3743)

idAttoAnsc: 2023-1215636-491-039010

atto di morte con dataEvento: 10/12/2023
data formazione atto: 11/12/2023

il servizio di validazione data (ws R014) è stato inviato.

le notifiche ANSC associate all'atto (trascrizione: idNotifica 2244396 - annotazione: idNotifica 2244398) sono state confermate.

non riceviamo la notifica ANPR collegata all'atto.
se potete verificare per piacere.

grazie
Alessandro Monopoli ADS

**Comment by RBiasi** [comment]
Confermo che riscontriamo la medesima anomalia.

Grazie
Roberta Biasi
Deda Next

**Comment by gbuemi** [comment]
Buongiorno, 
abbiamo preso in carico la segnalazione, verifichiamo.

Grazie.
Supporto ANSC

**Comment by gbuemi** [comment]
Buongiorno, 
@AMonopoliADS abbiamo trovato una elaborazione successiva (3 minuti dopo) all'apertura della segnalazione evasa correttamente, idOperazioneComune 2023410308, request al 4005 effettuata alle 14:55 contenente la notifica anpr relativa all'atto 2023-1215636-491-039010.

Invito @RBiasi ad aprire per favore una segnalazione con il riferimento all'atto ANSC e la request effettuata al 4005 per il reperimento della notifica.

Grazie e saluti.
Supporto ANSC
