### ISSUE TITLE
usecase mancanti

### ISSUE THREAD

**Issue by migmar68** [italia/ansc#534]
Buongiorno, solo una conferma, almeno immagino io.
Rilevo ancora l'assenza di alcune casistiche certamente rare, ma d'altra parte è imprevedibile quando si presentano certe situazioni allo sportello: forse domani, forse tra 10 anni.
Già nella issue #85 sono state segnalate alcune ipotetiche mancanze della tabella, rilevate per casi previsti in una situazione (es. dich. in termini di legge) ma assenti nella situazione opposta (es. dich.tardiva).
A tutt'oggi rilevo che i seguenti ipotizzati codici mancano:
**11211204** Dichiarazione entro i 10 giorni - resa dal padre con il consenso della madre reso mediante atto notarile - bambino nato vivo e morto prima della dichiarazione di nascita - filiazione fuori dal matrimonio
**11424010** Dichiarazione tardiva di filiazione fuori del matrimonio, resa dal procuratore del padre, di bimbo riconosciuto da parte di entrambi i genitori prima della nascita
**11427010** Dichiarazione tardiva di filiazione fuori del matrimonio, resa dal procuratore speciale della madre, di bimbo riconosciuto da parte di entrambi i genitori prima della nascita

E' corretto pensare che verranno prima o poi aggiunti in futuro, e qualora si dovesse presentare nel frattempo il caso, lo USC ricorre al
**11999999**	Caso d'uso di servizio (dichiarazioni nascita)
formando manualmente l'atto?

Grazie in anticipo
Marco Migliori

**Comment by asqueglia** [comment]
Buongiorno, è prevista l'implementazione dei casi d'uso mancanti nel piano operativo del 2024. Se dovesse capitare una delle casistiche mancanti, confermiamo che si può procedere con il caso d'uso di servizio.

**Comment by migmar68** [comment]
Grazie
