### ISSUE TITLE
[R002] Estratto per copia integrale - ERRORE INTERNO

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#535]
REQUEST:
{
    "idAnsc": "2023-1215767-12378-108028",
    "idEvento": "1215767",
    "richiedente": {
        "codiceFiscale": "CTTMGH68B41E617G",
        "cognome": "CITTERIO",
        "nome": "MARGHERITA",
        "sesso": "F",
        "dataNascita": "1968-02-01",
        "idComuneNascita": "5001",
        "nomeComuneNascita": "LISSONE",
        "idProvinciaNascita": "15",
        "siglaProvinciaNascita": "MI",
        "idStatoNascita": "90",
        "nomeStatoNascita": "ITALIA",
        "idComuneResidenza": "5000",
        "nomeComuneResidenza": "LISSONE",
        "idProvinciaResidenza": "108",
        "siglaProvinciaResidenza": "MB",
        "idStatoResidenza": "90",
        "nomeStatoResidenza": "ITALIA",
        "indirizzoResidenza": "VIA MAMELI GOFFREDO,52 sc.C int.0"
    },
    "intestatario": {
        "id": "2244801"
    },
    "idTipoCertificato": "3",
    "conPaternitaMaternita": false,
    "testataRichiesta": {
        "idComune": 5000,
        "idOperazioneComune": "5605",
        "dataOraRichiesta": "2023-12-12T10:13:53.595+01:00",
        "nomeApplicativo": "urbi",
        "versioneApplicativo": "1.0.0",
        "fornitoreApplicativo": "padigitale"
    }
}

RESPONSE:
{
    "testataRisposta": {
        "idComune": 5000,
        "idOperazioneComune": "5605",
        "idOperazione": "1719070"
    },
    "errors": [{
            "code": "500",
            "severity": "E",
            "text": "Errore interno"
        }
    ],
    "infos": [{
            "code": "110527",
            "severity": "I",
            "text": "Informazioni sull'operazione da fornire in caso di assistenza : data:2023-12-12 09:13:57 , idOperazione:1719070"
        }
    ]
}

**Comment by amusarra** [comment]
Buongiorno @biadanpad 
Siamo a conoscenza del problema in fase di emissioni dei certificati che stiamo gestendo.
Non appena avremo risolto le daremo notifica.

Cordiali Saluti.
Supporto ANSC.

**Comment by asqueglia** [comment]
E' un problema limitato al solo ambiente di pre produzione non legato al software bensì al servizio di sigillo di test su cui stiamo lavorando.

**Comment by asqueglia** [comment]
Con la versione 1.22.0 è stata corretta la segnalazione. Chiudiamo pertanto la issue. In caso di ulteriori segnalazioni preghiamo di aprire una issue dedicata
