### ISSUE TITLE
[R010] - Richiesta Info

### ISSUE THREAD

**Issue by ManuelDeMeo** [italia/ansc#537]
Su ambiente produzione il servizio di anteprima atto ci sta andando in errore e non riceviamo risposta.
Il comune è Grottaferrata, vi fornisco gli IdOperazioneComune (non potendovi fornire l'idOperazione):
- "idOperazioneComune":"8ff54032-878f-431a-8d9b-e1c82a51f544"
- "idOperazioneComune":"ce754264-fe7f-49ad-ba11-0f944d5120c1"

Potete verificare per favore e farci sapere se c'è qualcosa di sbagliato nella richiesta? In ambiente pre-produzione invece sembra funzionare tutto.

Grazie

**Comment by amusarra** [comment]
Buongiorno @ManuelDeMeo 
Potresti inviarmi il payload usato?

Grazie.
Supporto ANSC.

**Comment by LoreL56** [comment]
Abbiamo fatto un'altra richiesta dello stesso tipo, sempre con esito negativo.
Questa la richiesta completa:

`{
   "presaVisione":false,
   "evento":{
      "id":"1242",
      "idAnsc":"2023-1242-1206-058046",
      "idUsecase":"11999999"
   },
   "testataRichiesta":{
      "idComune":4559,
      "idOperazioneComune":"32c970cc-6376-45e3-9538-850beb6efc04",
      "dataOraRichiesta":"2023-12-13",
      "nomeApplicativo":"CIVILIANEXT",
      "versioneApplicativo":"3.3.8",
      "fornitoreApplicativo":"DEDA NEXT"
   }
}`

**Comment by amusarra** [comment]
Salve @ManuelDeMeo  e @LoreL56 
Da quello che abbiamo rilevato sui log, il payload specifico è stato inviato verso l'endpoint `/` e non `/anteprima/evento/1`, vi chiediamo pertanto di verificare.

Cordiali Saluti.
Supporto ANSC.

**Comment by ManuelDeMeo** [comment]
Grazie @amusarra del supporto, abbiamo verificato e risolto il problema! Chiudo la issue.
