### ISSUE TITLE
inserimento tipo documento "VARIE" in altri allegati

### ISSUE THREAD

**Issue by robertopalombo** [italia/ansc#538]
si richiede per tutti i tipi di atti l'inserimento di un tipo documento "VARIE" utilizzabile in altri allegati per poter allegare documenti che non sono specificatamente indicati nelle tipologie di documenti definiti.

Esempio: delega dell'incaricato dell'onoranza funebre alla presentazione della documentazione di atto di morte.

firmato Roberto Palombo - Comune di Grottaferrata

**Comment by asqueglia** [comment]
Verificheremo e le faremo sapere.. gli allegati erano stati concordati con ANUSCA proprio per evitare di allegare documentazione varia che finisse in conservazione. Facciamo un passaggio con ANUSCA e le faremo sapere

**Comment by asqueglia** [comment]
Buongiorno da un approfondimento con ANUSCA è emerso che 
_l'art.72 dice che la dichiarazione di morte è fatta da un congiunto o da un loro delegato o da una persona informata sul decesso e non richiede alcuna documentazione, neanche la delega. E’ una dichiarazione di parte che non necessita di ulteriore documentazione._ 

Non è stata approvata la richiesta di inserire in maniera arbitraria la documentazione da allegare.

Chiudiamo pertanto la issue. In caso di ulteriori dubbi si prega di aprire una altra issue dedicata.
