### ISSUE TITLE
R002 - Richiesta modifica input

### ISSUE THREAD

**Issue by ManuelDeMeo** [italia/ansc#54]
Buongiorno, parlando del servizio R002 /certificato/ sussiste l’eventualità per la quale un certificato/estratto di stato civile debba essere rilasciato a fronte di richiesta proveniente da soggetto non censito in ANPR; esempi:
- certificato/estratto di nascita richiesto da genitore straniero per figlio (straniero) nato in Italia
- certificato/estratto di matrimonio richiesto da soggetto straniero che ha contratto matrimonio in Italia
 - certificato/estratto di morte richiesto da parente straniero per cittadino straniero deceduto in Italia
 
Domanda:
può essere introdotta una modifica alla modellazione per la quale:
- il campo idAnprRichiedente diventi non obbligatorio?  
- sia possibile specificare il richiedente mediante le sole generalità?

**Comment by asqueglia** [comment]
Buongiorno, è prevista la modifica del servizio di certificazione in uno dei prossimi rilasci. Anticipiamo che il richiedente verrà gestito attraverso le generalità anagrafiche complete, come da lei indicato.
