### ISSUE TITLE
Caso d'uso 1312 genera tipo notifica NOTIFICA DI ISCRIZIONE AIRE per cittadino residente

### ISSUE THREAD

**Issue by RBiasi** [italia/ansc#540]
Buongiorno,

la presente per segnalarvi che il caso d'uso 1312 Trascrizione di atto di nascita avvenuta all estero su richiesta di chi ha interesse alla trascrizione di cittadino residente genera una notifica di tipo SC02 - NOTIFICA DI ISCRIZIONE AIRE.

Se il cittadino è residente non si dovrebbe generare una notifica di iscrizione bensì una notifica di mutazione (estremi atto nascita, padre, madre...)

Caso di test per verifica ID Atto ANSC 2023-1215755-1232-058046 Id notifica 310326.

Rimango a disposizione.

Roberta Biasi 
Deda Next

**Comment by gbuemi** [comment]
Buonasera,
vi confermiamo che la fix è stata rilasciata, è possibile efettuare un test creando un nuovo evento.

Un saluto.
Supporto ANSC

**Comment by RBiasi** [comment]
Confermo che ora non viene più creata la notifica di tipo SC02 - NOTIFICA DI ISCRIZIONE AIRE bensì viene generata la notifica di tipo SC03 NOTIFICA DI MUTAZIONE_ANAGRAFICA.

Domanda: non essendo presenti all'interno della notifica NOTIFICA DI MUTAZIONE_ANAGRAFICA i dati riferiti a paternità e maternità come procederà l'anagrafe all'aggiornamento di tali dati che vengono aggiornati/inseriti contestualmente alla trascrizione dell'evento di nascita avvenuto all'estero?

Grazie 

Roberta Biasi
Deda Next
