### ISSUE TITLE
Richiesta OTP - Login error

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#546]
Buongiorno, 
ci segnalano dal comune di Lissone che non riescono ad ottenere l'OTP per accedere ai servizi.
Hanno provato adaccedere con 2 SPID diversi.

![9142be2e-4275-4dd7-8269-9b82b837d9b4](https://github.com/italia/ansc/assets/131870281/1fdcda2b-f6ad-4de8-b90a-fc10b9a7c3e4)

**Comment by mttfranci** [comment]
Salve @biadanpad  potreste riprovare?
Il problema dovrebbe essere risolto

**Comment by biadanpad** [comment]
adesso ha funzionato
