### ISSUE TITLE
casi e mapping

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#547]
nella tabella 3 di decodifica ho trovato questi casi ma non trovo da nessuna parte  a quale mapping fanno riferimento:

312222	Dichiarazione: Matrimonio con Rito Civile con Delega di altro Comune fuori dalla casa comunale in Imminente Pericolo di Vita con Riconoscimento di uno o piu' figli

412212	Dichiarazione: Unione civile con delega di altro Comune fuori dalla casa comunale in imminente pericolo di vita

52481	Trascrizione: Cittadino straniero discendente da avo italiano iure sanguinis

52151	Trascrizione: Straniero coniugato o unito civilmente con cittadino italiano

52152	Trascrizione: Straniero che acquista per naturalizzazione

**Comment by annamaraspin** [comment]
Ho visto la patch 
https://github.com/italia/ansc/blob/main/docs/Mapping_casi_uso/3_dec_use_case.csv (adesso contiene solo il mapping tra l'idusecase e il cod ansc del caso d'uso). (https://github.com/italia/ansc/issues/557)

Ho cercato i codici che avevo segnalato nel ticket sopra e non li trovo. Sono casistiche eliminate? o sono state dimenticate?
grazie

**Comment by mttfranci** [comment]
Salve, stiamo verificando

**Comment by mttfranci** [comment]
Salve @annamaraspin  i casi d'uso segnalati sono stati rimossi in quanto obsoleti con la patch [1.21.4](https://github.com/italia/ansc/issues/564).

Saluti

Assistenza ANSC
