### ISSUE TITLE
[R001] Errore nella consultazione degli allegati di un atto redatto da altro comune

### ISSUE THREAD

**Issue by corradosacco** [italia/ansc#549]
Mentre tramite la webapp è possibile visualizzare gli allegati di un atto redatto da un comune diverso da quello dell'USC, con il servizio R001 non è permesso. L'errore riscontrato è: L'utente loggato non ha accesso alla risorsa

Un esempio di test è l'operazione:

`{"testataRichiesta":{"idComune":5646,"idOperazioneComune":"APP2022032210000","dataOraRichiesta":"2023-12-14","nomeApplicativo":"SIDe","versioneApplicativo":"1.0.0","fornitoreApplicativo":"SistemiInformativi"},"idAllegato":"2243969"} `

`{"testataRisposta":{"idComune":5646,"idOperazioneComune":"APP2022032210000","idOperazione":"1720406","idEsito":1},"errors":[{"code":"403001","severity":"E","text":"L'utente loggato non ha accesso alla risorsa"}],"infos":[{"code":"110527","severity":"I","text":"Informazioni sull'operazione da fornire in caso di assistenza : data:2023-12-14 11:00:08 , idOperazione:1720406"}]}`

**Comment by asqueglia** [comment]
Dall'incontro con ANUSCA del 28/12 emerge che la visibilità degli allegati deve essere territoriale a differenza della visibilità dell'atto che è nazionale. Provvederemo a correggere la web app in tal senso.

**Comment by asqueglia** [comment]
Buongiorno comunichiamo che con il rilascio odierno della versione 1.23.0 la segnalazione in oggetto è stata corretta; provvediamo quindi a chiudere la issue. In caso di ulteriori malfunzionamenti si prega di aprire una issue dedicata.
