### ISSUE TITLE
R003 - Errore formato output

### ISSUE THREAD

**Issue by ManuelDeMeo** [italia/ansc#55]
- Ambiente preprod
- Data test: 05/04/2023

Buongiorno,
la chiamata al servizio R003 /comunicazione/1 va a buon fine, ma all'interno della risposta, il campo contenuto non è in formato base64 come descritto da documentazione.

Allego richiesta e risposta (la risposta la allego in un txt per comodità, vista la grandezza del file)

Richiesta:
`{"idAnsc":"2023-950730-48-058046","testataRichiesta":{"idComune":4559,"idOperazioneComune":"2","dataOraRichiesta":"1","nomeApplicativo":"testSC","versioneApplicativo":"1.0.0","fornitoreApplicativo":"Test"},"datiPaginazione":{"numPagina":1,"numRecordPagina":10,"numRecordTotali":null}}`

Risposta:
[4896_risposta_comunicazioni.txt](https://github.com/italia/ansc/files/11160566/4896_risposta_comunicazioni.txt)

**Comment by amusarra** [comment]
Salve @ManuelDeMeo 
Con il prossimo rilascio che dovrebbe avvenire nella giornata odierna, questo problema è stato risolto.

Saluti.

**Comment by amusarra** [comment]
Buongiorno @ManuelDeMeo 
Il rilascio della nuova versione è stato eseguito e il problema segnalato è stato risolto.
Chiudiamo la segnalazione.

Saluti.
