### ISSUE TITLE
Usecase 51107 prestazione di giuramento (con impedimento) 

### ISSUE THREAD

**Issue by corradosacco** [italia/ansc#550]
Non è chiaro l'utilizzo della variabile 'Interessato presente' per cui se l'interessato non è presente e c'è un delegato (concorde con la descrizione dello usecase) ma se l'interessato è presente non si comprende in che senso ci sia un impedimento, non essendoci più un delegato. Lo usecase 51107, quando l'interessato è presente, sembra ricadere nello usecase 51106 prestazione di giuramento (abile).

**Comment by asqueglia** [comment]
Buonasera verifichiamo e facciamo sapere

**Comment by asqueglia** [comment]
Buongiorno comunichiamo che con il rilascio odierno della versione 1.23.0 la segnalazione in oggetto è stata corretta; provvediamo quindi a chiudere la issue. In caso di ulteriori malfunzionamenti si prega di aprire una issue dedicata.
