### ISSUE TITLE
[R005] errore interno su ambiente di produzione e preproduzione - urgente

### ISSUE THREAD

**Issue by siscomanpr** [italia/ansc#551]
Il servizio R005 da alcune ore ci restituisce Errore Interno.
In fase di validazione atto effettuiamo prima una ricerca del soggetto (come da vostre indicazioni), quindi ricevendo questo errore si blocca tutto il processo di validazione e firma dell'atto.
Il comune di Serravalle ha urgenza di chiudere questo atto di morte per poi registrarlo in anagrafe.
Potete controllare?

idOperazione: 19160

**Comment by mttfranci** [comment]
Salve @siscomanpr , ci eravamo accorti del problema e avevamo rilasciato una correzione circa 20 minuti fa.

L'operazione 19160 che indicat è di circa 10 minuti prima della patch.

Potete verificare di nuovo?
Vi risulta che l'anomalia persista?

Saluti

**Comment by mttfranci** [comment]
@siscomanpr  potreste riprovare?

**Comment by mttfranci** [comment]
@siscomanpr  perfetto grazie, comunque siamo confidenti che l'anomalia sia superata.

Saluti

Assistenza ANSC
