### ISSUE TITLE
[Documentazione] Rimozione /Mapping_casi_uso/3_dec_use_case.csv

### ISSUE THREAD

**Issue by siscomanpr** [italia/ansc#557]
Come avete riportato nel changelog, è stato rimosso il file /docs/Mapping_casi_uso/3_dec_use_case.csv
```
Documentazione
    - Rimosso https://github.com/italia/ansc/blob/main/docs/Mapping_casi_uso/3_dec_use_case.csv (era usato solo fino a quando non tutti i casi d'uso erano stato rilasciati), fare riferimento adesso alla sola tabella 3 completa : https://github.com/italia/ansc/blob/main/docs/Decodifiche/3_dec_use_case.csv
```
Per noi questo file era utile perché per ogni caso d'uso c'era il riferimento al relativo file di mapping. 
Potete aggiornare il file /Decodifiche/3_dec_use_case.csv con lo stesso csv che avete rimosso nell'altra sezione? o riattivarlo? Oppure c'è un altro modo per collegare i casi d'uso ai file di mapping?

Siscom SPA

**Comment by mttfranci** [comment]
Buongiorno, abbiamo ripristinato il precedente file ma con le sole colonne per l'associazione idusecase e cod ansc.

Per l'aggiornamento del file delle decodifiche, stiamo valutando se procedere in quanto andrebbe aggiornata anche la versione del relativo servizio, e questa associazione serve solo a livello di documentazione ma non è necessaria per l'uso dei servizi.

Saluti

Assistenza ANSC
