### ISSUE TITLE
[R001] Errore invio allegati firmati p7m - Nome del File non corretto

### ISSUE THREAD

**Issue by siscomanpr** [italia/ansc#559]
Nel tentativo di trasmettere un allegato firmato in p7m riceviamo l'errore "Nome del File non corretto".
Abbiamo notato che il problema sembra essere dovuto dal fatto che nel nome del file ci sono 2 estensioni (prova.pdf.p7m), perché se invece proviamo a trasmettere il file rinominato solo con .p7m (prova.p7m) viene accettato regolarmente.

Ambiente di pre-produzione:
idOperazione con il file prova.pdf.p7m, quindi che da errore: 1720829
idOperazione con il file prova.p7m, quindi accettato: 1720833

Lo stesso problema l'abbiamo rilevato anche sull'ambiente di produzione ma non abbiamo l'idOperazione.

Precisiamo che i comuni ricevono da altri enti (es. Consolati) i file firmati già nominati con la doppia estensione.

Siscom SPA

**Comment by mttfranci** [comment]
Buongiorno, renderemo la validazione meno stringente come proposto.

Saluti

Assistenza ANSC

**Comment by asqueglia** [comment]
Con la versione 1.22.0 è stata corretta la segnalazione. Chiudiamo pertanto la issue. In caso di ulteriori segnalazioni preghiamo di aprire una issue dedicata
