### ISSUE TITLE
[R007] Firma USC: Esito 1 - (Firma non avvenuta con successo) per casi d'uso di Morte 2102.

### ISSUE THREAD

**Issue by gcuci** [italia/ansc#56]
Buongiorno,

segnaliamo una risposta sempre negativa (come da titolo) per l'esecuzione del servizio, per eventi relativi al caso d'uso 2102.

Abbiamo sinora utilizzato il servizio per il caso d'uso 2101, utilizzando le credenziali di test come da esempio nello swagger (TestUser, TestPassword e TestOtp), ed ha sempre risposto correttamente.
Passando invece al caso d'uso 2102, con gli stessi dati impostati nella Request, eccetto chiaramente, l'idEvento, il servizio restituisce sempre una risposta negativa, con errore: "Firma non avvenuta con successo".

Stiamo eseguendo i test in preproduzione. Per un caso di esempio, potete verificare la risposta, ad un'invocazione del servizio, effettuata oggi, con "idOperazione":"1575809".

In attesa di un riscontro,

cordiali saluti.

**Comment by amusarra** [comment]
Salve @gcuci 
Il valore dell'idOperazione indicato non corrisponde alla chiamata del servizio di firma USC ma a quello di validazione.
Potrebbe fornire il payload di richiesta e risposta compreso l'endpoint?

A meno dei placeholder, questo è un payload di esempio:

```
{
    "testataRichiesta": {
        "idComune": {{idComune}},
        "idOperazioneComune": "APP2022032210000",
        "dataOraRichiesta": "{{dataOraRichiesta}}",
        "nomeApplicativo": "{{nomeApplicativo}}",
        "versioneApplicativo": "{{versioneApplicativo}}",
        "fornitoreApplicativo": "{{fornitoreApplicativo}}"
    },
    "firmaInput": {
        "idEvento": "{{idEventoTestFlusso01}}",
        "parametriFirma": {
            "idTipoFirma": "1",
            "idModalitaInput": "2",
            "inputFirma1": "VGVzdFVzZXI=",
            "inputFirma2": "VGVzdFBhc3N3b3Jk",
            "inputFirma3": "VGVzdE90cA=="
        }
    }
}
```
Payload esempio richiesta Firma USC

Ricordiamo che il servizio di firmaUSC può essere chiamato dopo che l'evento sia passato in stato 4 - FIRMATO DAL DICHIARANTE.

Saluti.

**Comment by gcuci** [comment]
L'invocazione del servizio, relativo all'idOperazione segnalato, è stata fatta all'esterno del nostro applicativo, e non abbiamo mantenuto la Request.

Abbiamo rieseguito adesso l'operazione, con questa Request:

{
  "firmaInput": {
    "idEvento": "950836",
    "parametriFirma": {
      "idTipoFirma": "1",
      "idModalitaInput": "2",
      "inputFirma1": "VGVzdFVzZXI=",
      "inputFirma2": "VGVzdFBhc3N3b3Jk",
      "inputFirma3": "VGVzdE90cA=="
    }
  },
  "testataRichiesta": {
    "idComune": 3913,
    "idOperazioneComune": "473",
    "dataOraRichiesta": "2023-04-07T11:42:23.44+02:00",
    "nomeApplicativo": "Akropolis",
    "versioneApplicativo": "20.1",
    "fornitoreApplicativo": "datamanagementitaliaspa"
  },
  "datiPaginazione": {
    "numPagina": 1,
    "numRecordPagina": 10,
    "numRecordTotali": 10
  },
  "": "FirmaRequest"
}

Ottenendo nella Response:
{
  "errors": [
    {
      "code": "406004",
      "severity": "E",
      "text": "Firma non avvenuta con successo"
    }
  ],
  "testataRisposta": {
    "idComune": 3913,
    "idEsito": 1,
    "idOperazione": "1576142",
    "idOperazioneComune": "473"
  }
}

**Comment by amusarra** [comment]
@gcuci lw posso chiedere di creare un nuovo evento, con le stesse caratteristiche precedenti, e riprovare a eseguire nuovamente la firma USC?

Sulla request ho visto che c'è un elemento che non dovrebbe esserci: `"": "FirmaRequest"`

Grazie.

**Comment by gcuci** [comment]
Abbiamo generato un nuovo evento della stessa tipologia (caso d'uso 2102), eseguita la validazione con Allegato, e la firma del dichiarante. La successiva firma USC, ha risposto con il solito esito negativo. Di seguito il dettaglio della Request:

{
  "firmaInput": {
    "idEvento": "950890",
    "parametriFirma": {
      "idTipoFirma": "1",
      "idModalitaInput": "2",
      "inputFirma1": "VGVzdFVzZXI=",
      "inputFirma2": "VGVzdFBhc3N3b3Jk",
      "inputFirma3": "VGVzdE90cA=="
    }
  },
  "testataRichiesta": {
    "idComune": 3913,
    "idOperazioneComune": "490",
    "dataOraRichiesta": "2023-04-07T15:22:25.49+02:00",
    "nomeApplicativo": "Akropolis",
    "versioneApplicativo": "20.1",
    "fornitoreApplicativo": "datamanagementitaliaspa"
  },
  "datiPaginazione": {
    "numPagina": 1,
    "numRecordPagina": 10,
    "numRecordTotali": 10
  },
  "": "FirmaRequest"
}
*[L'elemento "": "FirmaRequest", viene aggiunto dalla libreria che utilizziamo per creare il client dallo swagger, ma sinora non ha dato problemi, in nessuno degli altri servizi utilizzati, compreso questo di firma USC, per l'altro caso d'uso 2101]

e della Response:

{
  "errors": [
    {
      "code": "406004",
      "severity": "E",
      "text": "Firma non avvenuta con successo"
    }
  ],
  "testataRisposta": {
    "idComune": 3913,
    "idEsito": 1,
    "idOperazione": "1576251",
    "idOperazioneComune": "490"
  }
}

**Comment by amusarra** [comment]
Salve @gcuci la sua issue è un bug che abbiamo preso in carico. La terremo informato non appena sarà sistemato. 

Una curiosità. Quale tool utilizzate per la generazione del client a partire dalle OpenAPI?

Saluti.

**Comment by gcuci** [comment]
Swagger CodeGen for Java.

**Comment by amusarra** [comment]
Salve @amusarra 
Abbiamo gestito la segnalazione come bug che attualmente è in fase di analisi.

Saluti.

**Comment by amusarra** [comment]
Salve @gcuci 
Il problema segnalato è stato risolto con uno dei rilasci.

Cordiali Saluti.
Supporto ANSC.
