### ISSUE TITLE
Rico_016: aggiornamento stato atto bloccato in produzione

### ISSUE THREAD

**Issue by antonioluberto** [italia/ansc#561]
Presso il Comune di Grottaferrata è stato creato l'atto 
2023-1355-1218-058046.
E' avvenuta senza segnalazione di anomalia sia la creazione dell'atto in ANSC sia l'inserimento del file corrispondente alla copia sottoscritta da padre e madre: lo stato dell'atto non viene però aggiornato in "Firmato dal dichiarante" e non è pertanto possibile procedere alla conclusione del procedimento.

**Comment by antonioluberto** [comment]
Riscontriamo lo stesso problema anche in ambiente pre-produzione su atto
2023-1216129-293-058046

**Comment by asqueglia** [comment]
Buongiorno, abbiamo sistemato il caso specifico e il comune è andato avanti. 
Abbiamo verificato che il problema si è verificato perchè è stato trasmesso il soggetto padre due volte come soggetto firmatario, sia nella sezione padre e sia nella sezione dichiarante. Quando il dichiarante è un genitore è sufficiente e necessario trasmetterlo solo nella sezione del genitore, valorizzando gli appositi flag:
flagDichiarante = true
flagFirmatario=true

**Comment by asqueglia** [comment]
Buongiorno, chiudiamo la issue, nel caso di ulteriori segnalazioni si prega di riaprire l'issue o di aprirne una altra dedicata
