### ISSUE TITLE
Caso d'uso 1312 genera tipo notifica SC03 NOTIFICA DI MUTAZIONE ANAGRAFICA

### ISSUE THREAD

**Issue by RBiasi** [italia/ansc#562]
Seguito della issue #540

Confermo che ora non viene più creata la notifica di tipo SC02 - NOTIFICA DI ISCRIZIONE AIRE bensì viene generata la notifica di tipo SC03 NOTIFICA DI MUTAZIONE_ANAGRAFICA.

Domanda: non essendo presenti all'interno della notifica NOTIFICA DI MUTAZIONE_ANAGRAFICA i dati riferiti a paternità e maternità come procederà l'anagrafe all'aggiornamento di tali dati che vengono aggiornati/inseriti contestualmente alla trascrizione dell'evento di nascita avvenuto all'estero?

Caso di test 2023-1216079-1246-058046 id notifica 310333

Grazie

Roberta Biasi
Deda Next

**Comment by gbuemi** [comment]
Buonasera,
se in fase di registrazione dell'atto vengono inviati i dati di padre e madre, la notifica SC03 NOTIFICA DI MUTAZIONE ANAGRAFICA conterrà anche tali informazioni.

Grazie e saluti.
Supporto ANSC
