### ISSUE TITLE
Dichiarazione entro i 10 giorni - resa dal padre con il consenso della madre reso mediante atto notarile – filiazione fuori dal matrimonio 

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#563]
Buongiorno,
relativamente alla descrizione in oggetto nel file delle casistiche trovo:
usecase 11211004 DIC_NASC_020 (il caso classico)
usecase 11211104 DIC_NASC_022 (da usare se l'intestatario atto è nato morto)
ma non trovo la casistica da usare nel caso in cui l'intestatario nasca vivo ma muore prima della dichiarazione.

**Comment by amusarra** [comment]
Buongiorno @annamaraspin 
Verificheremo e le faremo sapere.

Cordiali Saluti.
Supporto ANSC

**Comment by amusarra** [comment]
Salve @annamaraspin 
Non esiste il caso specifico e in questo caso deve usare il caso DIC_NASC_020 secondo la normativa vigente che riporto a seguire e che l'USC dovrebbe conoscere.

> Per la legge italiana, i bambini sono considerati “nati morti” solo quando abbiano superato le 28 settimane di gestazione al momento del parto; pertanto se un bambino nasce morto dopo la 28° settimana dovrà essere registrato presso l’anagrafe e, solo successivamente, si potrà procedere alla sua sepoltura.
>  
> In questi casi vige l’obbligo di registrazione presso l’anagrafe, come previsto dall’art. 74 del Regio Decreto 09.07.1939 n. 1238 che cita testualmente:
>  
> Art. 74
>  
> Quando al momento della dichiarazione di nascita il bambino non è vivo, il dichiarante deve far conoscere se il bambino è nato morto o è morto posteriormente alla nascita, indicando in questo secondo caso la causa di morte. Tali circostanze devono essere comprovate dal dichiarante con il certificato di assistenza al parto di cui all’art. 70, comma quarto, ovvero con certificato medico. L’ufficiale dello stato civile forma il solo atto di nascita, se trattasi di bambino nato morto, e fa ciò risultare a margine dell’atto stesso; egli forma anche quello di morte, se trattasi di bambino morto posteriormente alla nascita.

Se non ci sono ulteriori questioni, le chiediamo di chiudere la issue.

Cordiali Saluti.
Supporto ANSC.
