### ISSUE TITLE
[R008] Ricerca notifiche - canale comunicazione - valori invertiti

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#568]
Sembra che la tabella di decodifica 105_dec_canale_com_notifica abbia i valori invertiti

![image](https://github.com/italia/ansc/assets/131870281/70700d15-62ca-47a1-bf78-245fc493de97)

**Comment by amusarra** [comment]
Salve @biadanpad 
Potrebbe essere più precis* nella richiesta? A quali valori si fa riferimento?
Si faccia anche riferimento a https://github.com/italia/ansc/blob/a98daac151e1d5a84cd9cebac64755bb88424bfd/docs/openapi/R008_notifiche.yaml#L341

**Comment by biadanpad** [comment]
Secondo la tabella 105_dec_canale_com_notifica:
idcanalenotifica = 0 -> PEC
idcanalenotifica = 1 -> Digitale

ma dai test che ho fatto mi sembra di capire che sia il contrario:
idcanalenotifica = 0 -> Digitale
idcanalenotifica = 1 -> PEC

**Comment by amusarra** [comment]
Salve @biadanpad 
Abbiamo verificato e constato il comportamento da voi rilevato.

Cordiali Saluti.
Supporto ANSC.

**Comment by amusarra** [comment]
Buongiorno @biadanpad 
Il problema è stato risolto. Chiudiamo quindi la issue. 

Cordiali Saluti.
Supporto ANSC.
