### ISSUE TITLE
tabella decodifica 36_dec_produzione_documenti

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#57]
Nel caso di situazioni miste (ad esempio documenti prodotti + visionati , già acquisiti+visionati, già acquisiti+prodotti+visionati, etc) come dobbiamo comportarci con la valorizzazione del campo del json?

**Comment by asqueglia** [comment]
Buongiorno, la tabella di decodifica 36 prevista, rispecchia quanto richiesto dalle formule ministeriali in termini di documentazione prodotta, acquisita oppure visionata. Abbiamo verificato, infatti, che tutte le formule che fanno menzione della documentazione, richiedono la seguente dicitura:  
mi ha prodotto (ovvero: e/o ho acquisito; ovvero: e/o ho visionato) i seguenti documenti 
(elencarli): … . (es. formula 114, 112, 111, quelle dei matrimoni,  ecc...)
Non ci sembra che ci siano formule che contemplino  situazioni miste.

**Comment by asqueglia** [comment]
La issue viene chiusa in caso si prega di riaprirla.
