### ISSUE TITLE
[R009] problemi validazione caso d'uso 1312 - Trascrizione di nascita: Trascrizione di atto di nascita avvenuta all estero su richiesta di chi ha interesse alla trascrizione

### ISSUE THREAD

**Issue by siscomanpr** [italia/ansc#572]
Per il caso d'uso in oggetto si segnalano 2 anomalie rilevate:
- se impostiamo il campo Tipo richiesta (evento.trascrizioneNascita.tipoDichiarazione) su "Verbale", il sistema richiede come obbligatorio l'allegato "Richiesta di trascrizione";

- l'altro problema riguarda un'anomalia simile a quella già riscontrata e segnalata nella issue https://github.com/italia/ansc/issues/502
In pratica se il richiedente è la madre (o il padre), il sistema ansc non richiede la compilazione dei dati del blocco richiedente, ma in compenso richiede come obbligatori i dati di nascita della madre (o del padre). Sicuramente ragiona così in modo da poter reperire contemporaneamente i dati della madre e del richiedente essendo la stessa persona. E' vero che sono dati conosciuti (perché sono del soggetto che sta richiedendo la trascrizione), ma il comune di Serravalle Sesia segnala che nella sezione padre e madre deve compilare solo il cognome e nome perché sull'atto estero che sta trascrivendo i dati di nascita dei genitori non sono presenti. 
Stesso ragionamento è stato previsto sulla web app, infatti quando il richiedente è diverso da "Altro" non vengono richiesti i dati del richiedente, ma sono obbligatori i dati di nascita del soggetto che è stato impostato come richiedente.
L'ideale sarebbe richiedere sempre obbligatori i dati del richiedente compresi i dati di nascita (per la compilazione della parte "ho ricevuto da ... "), e nella sezione padre e madre richiedere solo cognome e nome.

Potete fare riferimento a:
Ambiente: pre-produzione
idOperazione: 1723217

**Comment by siscomanpr** [comment]
Aggiungo che per i matrimoni (caso d'uso 331000), caso analogo di trascrizione dall'estero su richiesta dell'interessato, viene richiesto (correttamente) sempre il Richiedente e poi i dati di Sposo e Sposa, come dovrebbe essere a nostro avviso anche sugli atti di nascita.

**Comment by gbuemi** [comment]
Buongiorno,
abbiamo preso in carico la segnalazione.

Un saluto.
Supporto ANSC

**Comment by gbuemi** [comment]
Salve,
per il primo punto della issue si comunica che, con la versione 1.22.0, è stato corretto il comportamento. Si ricorda di inviare la request specificando nel campo idVersion il valore "100007".

**Comment by asqueglia** [comment]
Buongiorno, per il secondo punto da lei indicato, confermiamo che il sistema richiede i dati del richiedente solo se il soggetto richiedente è diverso da madre o padre; in caso per il richiedente si tratti di madre o padre, il sistema richiede di specificare tutti i dati necessari una sola volta nella sezione opportuna. Al momento non sono previste modifiche in merito a tale comportamento. Chiudiamo pertanto la issue; in caso di ulteriori segnalazioni si prega di aprirne una altra dedicata
