### ISSUE TITLE
Prenotazione Eventi e conseguente Validazione - Errore Interno

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#575]
Abbiamo chiamato con successo il servizio di prenotazione eventi. Di seguito la lista degli eventi prenotati:

2023-1216668-12383-108028
2023-1216669-12384-108028
2023-1216670-12385-108028
2023-1216671-12386-108028
2023-1216672-12387-108028

Quando però proviamo a validare l'evento il sistema ci risponde con "Errore interno"

Di seguito request e response del servizio di validazione:

REQUEST:
{
    "evento": {
        "idAnsc": "2023-1216668-12383-108028",
        "idTipoEvento": "1",
        "idtipocontenuto": "1",
        "idUsecase": "11111000",
        "descrizioneCasoUso": "Dichiarazione entro i 10 giorni - resa dal padre",
        "stato": "CONFERMATO",
        "idVersion": "100006",
        "dataformazione": "2023-12-21",
        "ora": "17",
        "minuto": "27",
        "operatore": "DLCNTN57L67A064W",
        "operatoreNome": "MARGHERITA",
        "operatoreCognome": "CITTERIO",
        "idComuneRegistrazione": "5000",
        "nomeComuneRegistrazione": "LISSONE",
        "idProvinciaRegistrazione": "108",
        "siglaProvinciaRegistrazione": "MB",
        "numeroatto": "12383",
        "tipoDichiarante": "1",
        "ausilioInterprete": "false",
        "allegati": [{
                "id": "2247906",
                "idTipoAllegato": "1",
                "hashAllegato": "kNYDvFimmQjjMhobd63N8lXP9CLtscUSgUrDd1Qp8Vc\u003d",
                "descrizione": "Attestazione di nascita"
            }
        ],
        "intestatari": [{
                "id": "2225818",
                "cognome": "NATO",
                "nome": "PRIMO",
                "sesso": "M",
                "dataNascita": "2023-10-10",
                "idComuneNascita": "5000",
                "nomeComuneNascita": "LISSONE",
                "idProvinciaNascita": "108",
                "siglaProvinciaNascita": "MB",
                "idStatoNascita": "90",
                "nomeStatoNascita": "ITALIA",
                "idComuneResidenza": "5000",
                "nomeComuneResidenza": "LISSONE",
                "idProvinciaResidenza": "108",
                "siglaProvinciaResidenza": "MB",
                "idStatoResidenza": "90",
                "nomeStatoResidenza": "ITALIA",
                "idNazionalita": "90",
                "nazionalita": "ITALIANA"
            }
        ],
        "madre": {
            "cognome": "NATA",
            "nome": "MADRE",
            "sesso": "F",
            "dataNascita": "2000-01-01",
            "idComuneNascita": "5001",
            "nomeComuneNascita": "LISSONE",
            "idProvinciaNascita": "15",
            "siglaProvinciaNascita": "MI",
            "idStatoNascita": "90",
            "nomeStatoNascita": "ITALIA",
            "idComuneResidenza": "5000",
            "nomeComuneResidenza": "LISSONE",
            "idProvinciaResidenza": "108",
            "siglaProvinciaResidenza": "MB",
            "idStatoResidenza": "90",
            "nomeStatoResidenza": "ITALIA",
            "idNazionalita": "90",
            "nazionalita": "ITALIANA",
            "flagDichiarante": false,
            "flagComparente": false,
            "flagFirmatario": false
        },
        "padre": {
            "cognome": "NATO",
            "nome": "PADRE",
            "sesso": "M",
            "dataNascita": "2000-01-01",
            "idComuneNascita": "5001",
            "nomeComuneNascita": "LISSONE",
            "idProvinciaNascita": "15",
            "siglaProvinciaNascita": "MI",
            "idStatoNascita": "90",
            "nomeStatoNascita": "ITALIA",
            "idComuneResidenza": "5000",
            "nomeComuneResidenza": "LISSONE",
            "idProvinciaResidenza": "108",
            "siglaProvinciaResidenza": "MB",
            "idStatoResidenza": "90",
            "nomeStatoResidenza": "ITALIA",
            "idNazionalita": "90",
            "nazionalita": "ITALIANO",
            "flagDichiarante": true,
            "flagComparente": false,
            "flagFirmatario": true
        },
        "datiDichiarante": {
            "comprensione": "0"
        },
        "datiDiNascita": {
            "luogoFiliazione": "ospedale del comune di LISSONE",
            "oraNascita": "10",
            "minutoNascita": "1",
            "tipoAccertamento": "1"
        },
        "composizioneCompleta": "   L\u0027anno duemilaventitre addi\u0027 ventuno del mese di dicembre alle ore diciassette e minuti   ventisette nella casa comunale. Avanti a me, CITTERIO MARGHERITA, Istruttore, Ufficiale dello   stato civile del Comune di LISSONE per delega avuta e\u0027 comparso NATO PADRE nato in LISSONE li   01.01.2000 residente in LISSONE, il quale mi ha dichiarato quanto segue:   Il giorno DIECI del mese di OTTOBRE dell\u0027anno DUEMILAVENTITRE alle ore DIECI e minuti UNO nel   ospedale del comune di LISSONE da NATA MADRE nata in LISSONE il 01.01.2000 cittadina ITALIANA   residente in LISSONE moglie del dichiarante, cittadino ITALIANO e\u0027 nato un bambino di sesso   MASCHILE.   A detto bambino che non mi viene presentato, ma della cui nascita io mi sono accertato a mezzo   della attestazione di nascita   rilasciata dall\u0027ostetrica-------- il dichiarante dà il nome di PRIMO .                                                                                                      Il presente atto viene letto all\u0027 intervenuto, il quale insieme con me, lo sottoscrive."
    },
    "testataRichiesta": {
        "idComune": 5000,
        "idOperazioneComune": "5610",
        "dataOraRichiesta": "2023-12-21T18:23:20.582+01:00",
        "nomeApplicativo": "urbi",
        "versioneApplicativo": "1.0.0",
        "fornitoreApplicativo": "padigitale"
    }
}

RESPONSE:
{
    "testataRisposta": {
        "idComune": 5000,
        "idOperazioneComune": "5610",
        "idOperazione": "1723457",
        "idEsito": 1
    },
    "errors": [{
            "code": "500",
            "severity": "E",
            "text": "Errore interno"
        }
    ],
    "infos": [{
            "code": "110527",
            "severity": "I",
            "text": "Informazioni sull'operazione da fornire in caso di assistenza : data:2023-12-21 17:23:22 , idOperazione:1723457"
        }
    ]
}

**Comment by gbuemi** [comment]
Buongiorno, 
in questa casistica occorre inviare all'interno della struttura **evento** anche l'id (p.e. osservando la request condivisa "id": 1216668). Lato nostro ci impegneremo a restituire un messaggio di errore coerente con quanto richiesto.

Grazie e saluti
Supporto ANSC
