### ISSUE TITLE
[R001] lo stato dell'allegato non passa mai a "inserito"

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#579]
Lo stato degli allegati passa da "Ricevuto" a "In elaborazione" e viceversa senza mai passare ad altri stati

**Comment by siscomanpr** [comment]
Rileviamo lo stesso problema.

**Comment by gbuemi** [comment]
Buon pomeriggio,
prendiamo in carico la segnalazione.

Un saluto.
Supporto ANSC

**Comment by mttfranci** [comment]
@biadanpad @siscomanpr ora il servizio dovrebbe funzionare nuovamente. 

Saluti

Assistenza ANSC
