### ISSUE TITLE
[R009] Errore Validazione atto Caso d'uso 1311

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#580]
Buongiorno, 
specificando la residenza straniera dell'intestatario si ottiene un errore.
di seguito request e response:

REQUEST:
{
  "evento": {
    "idAnsc": "",
    "idTipoEvento": "1",
    "idtipocontenuto": "3",
    "idUsecase": "1311",
    "descrizioneCasoUso": "Trascrizione di atto di nascita avvenuta allâ€™estero su richiesta dellâ€™autoritÃ  diplomatica o consolare",
    "stato": "CONFERMATO",
    "idVersion": "100006",
    "dataformazione": "2023-12-27",
    "ora": "9",
    "minuto": "23",
    "operatore": "DLCNTN57L67A064W",
    "operatoreNome": "MARGHERITA",
    "operatoreCognome": "CITTERIO",
    "idComuneRegistrazione": "5000",
    "nomeComuneRegistrazione": "LISSONE",
    "idProvinciaRegistrazione": "108",
    "siglaProvinciaRegistrazione": "MB",
    "numeroatto": "138",
    "allegati": [
      {
        "id": "2248652",
        "idTipoAllegato": "27",
        "hashAllegato": "xPXsjrvU74cl8DOG5H2LSonOItTo7pidjgB53OuBxEI=",
        "descrizione": "Atto estero di nascita originale o copia autentica"
      },
      {
        "id": "2248651",
        "idTipoAllegato": "26",
        "hashAllegato": "Wnd/SAmzqTd9IJyzdG7AGYgVX6N9KGa8PLFmd1TAdPc=",
        "descrizione": "Nota di trasmissione da parte dell\\'autoritÃ  consolare o diplomatica"
      }
    ],
    "intestatari": [
      {
        "cognome": "FANINI",
        "nome": "BEPPE",
        "sesso": "M",
        "dataNascita": "2023-12-25",
        "idStatoNascita": "61",
        "nomeStatoNascita": "FRANCIA",
        "idStatoResidenza": "61",
        "nomeStatoResidenza": "FRANCIA",
        "idNazionalita": "90",
        "nazionalita": "ITALIANA",
        "flagDichiarante": false,
        "flagComparente": false,
        "flagFirmatario": false
      }
    ],
    "madre": {
      "cognome": "GALO",
      "nome": "PINA",
      "sesso": "F",
      "dataNascita": "1977-12-01",
      "idStatoNascita": "113",
      "nomeStatoNascita": "MAROCCO",
      "idStatoResidenza": "164",
      "nomeStatoResidenza": "SPAGNA",
      "idNazionalita": "90",
      "nazionalita": "ITALIANA",
      "flagDichiarante": false,
      "flagComparente": false,
      "flagFirmatario": false
    },
    "padre": {
      "cognome": "FANINI",
      "nome": "LINO",
      "sesso": "M",
      "dataNascita": "1974-12-01",
      "idStatoNascita": "61",
      "nomeStatoNascita": "FRANCIA",
      "idStatoResidenza": "61",
      "nomeStatoResidenza": "FRANCIA",
      "flagDichiarante": false,
      "flagComparente": false,
      "flagFirmatario": false
    },
    "trascrizioneNascita": {
      "dataComunicazione": "2023-12-20",
      "testoLibero": "121456",
      "atto": {
        "enteEstero": {
          "nazioneEnte": "61",
          "nomeNazioneEnte": "FRANCIA",
          "idAnagraficaConsolato": "2290103",
          "nomeAnagraficaConsolato": "PARIGI",
          "nomeEnte": "78755"
        }
      },
      "attoEstero": {
        "enteEstero": {
          "nazioneEnte": "61",
          "nomeNazioneEnte": "FRANCIA",
          "nomeEnte": "2000",
          "dataTrascrizione": "2023-12-20",
          "estremiDocumento": "22544"
        }
      }
    },
    "composizioneCompleta": "      Oggi ventisette del mese di dicembre dell'anno duemilaventitre alle ore nove e minuti   ventitre nella casa comunale io sottoscritto CITTERIO MARGHERITA, Istruttore, Ufficiale dello   stato civile del Comune di LISSONE, per delega avuta, ho ricevuto da 78755 la richiesta in   data 20-12-2023 di trascrivere il documento con estremi: 22544 in data 2023-12-20 emesso da   2000 proveniente da FRANCIA, di cui mi ha trasmesso copia.   Aderendo a tale richiesta, provvedo alla trascrizione del documento come segue: 121456.   Dopo di che ho munito del mio visto ed inserito nel volume degli allegati a questo registro   copia dei documenti."
  },
  "testataRichiesta": {
    "idComune": 5000,
    "idOperazioneComune": "5623",
    "dataOraRichiesta": "2023-12-27T12:52:25.673+01:00",
    "nomeApplicativo": "urbi",
    "versioneApplicativo": "1.0.0",
    "fornitoreApplicativo": "padigitale"
  }
}

RESPONSE:
{
  "testataRisposta": {
    "idComune": 5000,
    "idOperazioneComune": "5623",
    "idOperazione": "1725090",
    "idEsito": 1
  },
  "errors": [
    {
      "code": "400003",
      "severity": "E",
      "text": "Attenzione! In caso di residenza estera comune e/o provincia di residenza non possono essere valorizzati."
    }
  ],
  "infos": [
    {
      "code": "110527",
      "severity": "I",
      "text": "Informazioni sull'operazione da fornire in caso di assistenza : data:2023-12-27 11:52:27 , idOperazione:1725090"
    }
  ]
}

Facendo varie prove, abbiamo visto che se evitiamo di inviare anche lo stato di residenza, allora la validazione va a buon fine.

Inoltre:
- per quanto riguarda padre e madre, in caso di stato di nascita/residenza stranieri, è necessario sbiancare anche i campi nomeComuneNascita/nomeComuneResidenza?
- per il soggetto intestatario, in caso di stato di nascita straniero, è necessario sbiancare anche il campo nomeComuneNascita?
-

**Comment by gbuemi** [comment]
Buonasera,
la segnalazione è stata presa in carico.

Grazie e saluti.
Supporto ANSC

**Comment by biadanpad** [comment]
Buonasera, 
nel frattempo, potrebbe indicarmi se in generale, nella classe ModelSoggetto, i campi nomeComuneNascita/nomeComuneResidenza devono essere riempiti o meno nel caso di nazione di nascita/residenza straniera?

Grazie.

**Comment by gbuemi** [comment]
Buongiorno,
in caso di soggetti stranieri anche i campi idcomune e idprovincia devono essere vuoti, oltre a quelli indicati.

Un saluto.
Supporto ANSC

**Comment by biadanpad** [comment]
bene, grazie

**Comment by asqueglia** [comment]
Buongiorno comunichiamo che con il rilascio odierno della versione 1.23.0 la segnalazione in oggetto è stata corretta; provvediamo quindi a chiudere la issue. In caso di ulteriori malfunzionamenti si prega di aprire una issue dedicata.
