### ISSUE TITLE
R007 Cittadinanza

### ISSUE THREAD

**Issue by Sem98** [italia/ansc#582]
Buongiorno, inviando una R007 per la firma dell'ufficiale di stato civile relativa ad una R009 Cittadinanza, ANSC risponde sempre con errore 400 e questo messaggio:
400
{"errors":[{"code":"406004","severity":"E","text":"Firma non avvenuta con successo"}],"infos":[{"code":"110527","severity":"I","text":"Informazioni sull'operazione da fornire in caso di assistenza : data:2023-12-27 10:04:05 , idOperazione:1725006"}],"testataRisposta":{"idComune":9493,"idEsito":1,"idOperazione":"1725006","idOperazioneComune":"2967"}}

Il payload associato alla chiamata è il seguente:

{
	"testataRichiesta": {
		"versioneApplicativo": "1.0.0",
		"idOperazioneComune": "2967",
		"idComune": 9493,
		"dataOraRichiesta": "2023-12-27T10:04:02.136",
		"nomeApplicativo": "SIDe",
		"fornitoreApplicativo": "SistemiInformativi"
	},
	"firmaInput": {
		"idEvento": "1216753",
		"parametriFirma": {
			"idModalitaInput": "2",
			"inputFirma2": "VGVzdFBhc3N3b3Jk",
			"inputFirma1": "VGVzdFVzZXI=",
			"inputFirma3": "VGVzdE90cA==",
			"idTipoFirma": "1"
		}
	}
}

Volevamo sapere come poter risolvere il problema.

**Comment by gbuemi** [comment]
Buongiorno, 
la segnalazione è stata presa in carico.

Un saluto
Supporto ANSC

**Comment by gbuemi** [comment]
Salve, è possibile riprovare?
Tra l'operazione di firma del dichiarante e quella dell'usc è presente la scansione antivirus, nel caso di firma dichiarante cartacea. Per l'atto segnalato la scansione antivirus non era stata completata.
In generale stiamo anche lavorando sulla messagistica di errore.

Grazie e saluti.
Supporto ANSC

**Comment by Sem98** [comment]
Salve ho appena riprovato e continua a darmi lo stesso errore

**Comment by gbuemi** [comment]
Salve,
come per l'atto precedente tra la firma dichiarante e la firma dell'usc sono trascorsi solo 3 secondi. Bisogna attendere la scansione antivirus della firma dichiarante cartacea conclusasi pochi secondi dopo il tentativo di firma usc. 
Come scritto nel messaggio precedente valuteremo se restituire un messaggio di errore più chiaro in casi come questi. 

Per poter registrare l'atto bisogna invocare il servizio di firma usc, in modo indicativo circa 10 / 15 secondi dopo quella del dichiarante.

Un saluto.
Supporto USC
