### ISSUE TITLE
Anomalia servizio R005 in produzione

### ISSUE THREAD

**Issue by antonioluberto** [italia/ansc#584]
Su ambiente di produzione per Comune di Grottaferrata verifichiamo in alcuni casi risposta anomala/vuota a fronte di invocazione del servizio R005; ultima occorrenza dell'anomalia in questione si è avuta ieri, "idOperazioneComune":"542bc23f-29ab-46b7-b431-3f02af28a5bf".

Nota: subito dopo, altra invocazione del servizio R005 ("idOperazioneComune":"41318289-0bbc-4013-b455-4a13a816ad3e") si è conclusa con successo

**Comment by asqueglia** [comment]
Buongiorno, verifichiamo e le facciamo sapere.

**Comment by asqueglia** [comment]
Chiudiamo la issue essendo molto vecchia. In caso si dovesse ripresentare il problema si prega di aprire una issue dedicata con il nuovo template.
