### ISSUE TITLE
[R009] Errore Validazione Caso Uso 1399 - Viene richiesto il campo "flagDichiarante" per l'intestatario (cioè il nato)

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#585]
REQUEST:
{
  "evento": {
    "idAnsc": "",
    "idTipoEvento": "1",
    "idtipocontenuto": "3",
    "idUsecase": "1399",
    "descrizioneCasoUso": "Caso d'uso di servizio (trascrizioni nascita)",
    "stato": "CONFERMATO",
    "idVersion": "100006",
    "dataformazione": "2023-12-29",
    "ora": "12",
    "minuto": "4",
    "operatore": "DLCNTN57L67A064W",
    "operatoreNome": "MARGHERITA",
    "operatoreCognome": "CITTERIO",
    "idComuneRegistrazione": "5000",
    "nomeComuneRegistrazione": "LISSONE",
    "idProvinciaRegistrazione": "108",
    "siglaProvinciaRegistrazione": "MB",
    "dataDecorrenza": "2023-12-29",
    "numeroatto": "13",
    "intestatari": [
      {
        "id": "2225818",
        "cognome": "NATO",
        "nome": "PRIMO",
        "sesso": "M",
        "dataNascita": "2023-10-10",
        "idComuneNascita": "5000",
        "nomeComuneNascita": "LISSONE",
        "idProvinciaNascita": "108",
        "siglaProvinciaNascita": "MB",
        "idStatoNascita": "90",
        "nomeStatoNascita": "ITALIA",
        "idComuneResidenza": "5000",
        "nomeComuneResidenza": "LISSONE",
        "idProvinciaResidenza": "108",
        "siglaProvinciaResidenza": "MB",
        "idStatoResidenza": "90",
        "nomeStatoResidenza": "ITALIA",
        "idNazionalita": "90",
        "nazionalita": "ITALIANA"
      }
    ],
    "madre": {
      "cognome": "NATA",
      "nome": "MADRE",
      "sesso": "F",
      "dataNascita": "2000-01-01",
      "idComuneNascita": "5001",
      "nomeComuneNascita": "LISSONE",
      "idProvinciaNascita": "15",
      "siglaProvinciaNascita": "MI",
      "idStatoNascita": "90",
      "nomeStatoNascita": "ITALIA",
      "idComuneResidenza": "5000",
      "nomeComuneResidenza": "LISSONE",
      "idProvinciaResidenza": "108",
      "siglaProvinciaResidenza": "MB",
      "idStatoResidenza": "90",
      "nomeStatoResidenza": "ITALIA",
      "idNazionalita": "90",
      "nazionalita": "ITALIANA",
      "flagDichiarante": false,
      "flagComparente": false,
      "flagFirmatario": false
    },
    "padre": {
      "cognome": "NATO",
      "nome": "PADRE",
      "sesso": "M",
      "dataNascita": "2000-01-01",
      "idComuneNascita": "5001",
      "nomeComuneNascita": "LISSONE",
      "idProvinciaNascita": "15",
      "siglaProvinciaNascita": "MI",
      "idStatoNascita": "90",
      "nomeStatoNascita": "ITALIA",
      "idComuneResidenza": "5000",
      "nomeComuneResidenza": "LISSONE",
      "idProvinciaResidenza": "108",
      "siglaProvinciaResidenza": "MB",
      "idStatoResidenza": "90",
      "nomeStatoResidenza": "ITALIA",
      "idNazionalita": "90",
      "nazionalita": "ITALIANO",
      "flagDichiarante": false,
      "flagComparente": false,
      "flagFirmatario": false
    },
    "composizioneCompleta": " L'anno duemilaventitre addi' ventinove del mese di dicembre alle ore dodici e minuti quattro nella Casa Comunale. Io, CITTERIO MARGHERITA Istruttore Ufficiale dello stato civile del Comune di LISSONE per delega avuta avendo ricevuto in data 10.12.2023 dall'Ufficiale dello Stato Civile del Comune di AREZZO (AR) copia di atto di nascita, trascrivo per intero la copia stessa, che e' del tenore seguente: L'anno duemilaventitre addi' uno del mese di dicembre alle ore dodici e minuti trenta nella casa comunale. Avanti a me, , Ufficiale dello Stato Civile del Comune di  AREZZO (AR)  e' compars   nat in li  residente in ,  quale mi ha dichiarato quanto segue: Il giorno DIECI del mese OTTOBRE dell'anno DUEMILAVENTITRE alle ore QUINDICI e minuti QUARANTACINQUE nel   e' nato un bambino di sesso MASCHILE. A detto bambino che non mi viene presentato ma della cui nascita io mi sono accertato a mezzo della attestazione di nascita rilasciata dall'ostetrica-------- il dichiarante da il nome di PRIMO                                                                                                  L'ufficiale dello Stato Civile f.to: Eseguita la trascrizione, ho munito del mio visto ed inserito la copia suddetta nel volume degli allegati a questo registro."
  },
  "testataRichiesta": {
    "idComune": 5000,
    "idOperazioneComune": "5627",
    "dataOraRichiesta": "2023-12-30T08:46:12.352+01:00",
    "nomeApplicativo": "urbi",
    "versioneApplicativo": "1.0.0",
    "fornitoreApplicativo": "padigitale"
  }
}

RESPONSE:
{
  "testataRisposta": {
    "idComune": 5000,
    "idOperazioneComune": "5627",
    "idOperazione": "1725613",
    "idEsito": 1
  },
  "errors": [
    {
      "code": "400003",
      "severity": "E",
      "text": "Il campo evento.intestatari[0].flagDichiarante nella sezione Intestatario è obbligatorio"
    }
  ],
  "infos": [
    {
      "code": "110527",
      "severity": "I",
      "text": "Informazioni sull'operazione da fornire in caso di assistenza : data:2023-12-30 07:46:14 , idOperazione:1725613"
    }
  ]
}

**Comment by mttfranci** [comment]
Buongiorno @biadanpad, trattandosi di un caso d'uso libero di trascrizione di nascita, potrebbe essere anche l'intestatario a chiedere la trascrizione. (a differenza, ad esempio, della dichiarazione resa entro i 10 giorni).

Saluti

Assistenza ANSC

**Comment by MarcoSalaPad** [comment]
Buongiorno Matteo,
riapro la issues perchè secondo noi potrebbe mancare qualcosa nei casi d'uso di servizio.
Nel caso ad esempio di una trascrizione con caso d'uso specifico (1312 - Trascr_006 su richiesta di chi ha interesse alla trascrizione) è presente tutta la sezione dei richiedente. Questo perchè appunto nel caso di trascrizioni di nascita può essere anche lo stesso soggetto nato a fare la richiesta di trascrivere l'atto.
Quindi, secondo noi, per il caso d'uso di servizio non dovrei mettere il soggetto nato come dichiarante (perchè abbiamo sempre inteso come dichiarante chi dichiara l'atto in termini di iscrizione...sto dichiarando una nuova nascita, dichiaro un matrimonio ecc) ma dovrei poterlo specifica come soggetto richiedente la trascrizione. Non sarebbe più corretto mantenere questa distiazione tra richiednete, dichiarante ecc... anche per i casi d'uso di servizio?
Grazie

**Comment by mttfranci** [comment]
@MarcoSalaPad nell'esempio di trascrizione con caso d'uso specifico (1312) la sezione richiedente deve essere valorizzata solo se il richiedente è diverso da uno degli altri soggetti coinvolti (in questo caso Intestario, Madre, Padre). E vanno gli appositi flag senza duplicare i soggetti anche qualora abbiano ruoli diversi nella formazione. (vedi anche issue #561).

Poi riguardo alla operazione iniziale con il caso d'uso di servizio (1399), come indicato anche nelle specifiche : https://github.com/italia/ansc/blob/main/docs/Mapping_casi_uso/trascrizioni/Trascr_999.csv 
E' obbligatorio indicare i flag anche per l'intestatario.

Siamo a disposizione per ogni ulteriore chiarimento.

Saluti.

Assistenza ANSC
