### ISSUE TITLE
Errore 400 R006 in seguito a R009 UnioneCivile

### ISSUE THREAD

**Issue by Sem98** [italia/ansc#586]
Buongiorno, chiamando la R006 relativa ad una R009 unione civile ottengo il seguente errore:

400:
 {"errors":[{"code":"400003","severity":"E","text":"Allegato associato all'utente è già in elaborazione"}],"infos":[{"code":"110527","severity":"I","text":"Informazioni sull'operazione da fornire in caso di assistenza : data:2024-01-03 10:12:29 , idOperazione:1726101"}],"testataRisposta":{"idComune":9493,"idEsito":1,"idOperazione":"1726101","idOperazioneComune":"3147"}}

Il payload relativo è il seguente: 

{
	"testataRichiesta": {
		"versioneApplicativo": "1.0.0",
		"idOperazioneComune": "3147",
		"idComune": 9493,
		"dataOraRichiesta": "2024-01-03T10:12:27.211",
		"nomeApplicativo": "SIDe",
		"fornitoreApplicativo": "SistemiInformativi"
	},
	"firmaDichiaranteInput": {
		"nomefile": "SC156355.pdf",
		"listaFirmatari": [
			{
				"dataNascita": "1957-02-18",
				"cognome": "PAPINI",
				"sesso": "M",
				"nome": "RICCARDO",
				"codiceFiscale": "PPNRCR57B18B509W"
			},
			{
				"dataNascita": "1957-02-18",
				"cognome": "PAPINI",
				"sesso": "M",
				"nome": "RICCARDO",
				"codiceFiscale": "PPNRCR57B18B509W"
			},
			{
				"dataNascita": "1901-01-01",
				"cognome": "PAPINI",
				"sesso": "M",
				"nome": "MARIO",
				"codiceFiscale": "PPNMRA01A01D077L"
			},
			{
				"dataNascita": "1902-02-02",
				"cognome": "PAPINI",
				"sesso": "M",
				"nome": "RICCARDO",
				"codiceFiscale": "PPNRCR02B02L117K"
			}
		],
		"tipoFile": "1",
		"idEvento": "1216984",
		"contenuto": "JVBERi0xLjQKJaqrrK0KMSAwIG9ia....",
		"tipoAllegato": "999"
	}
}

**Comment by mttfranci** [comment]
Salve @Sem98 abbiamo verificato che l'evento è stato inserito con la richiesta del servizio di validazione id operazione : 1726099. Sicuramente i messaggi potrebbero essere migliorati, ma nel caso specifico il problema è dovuto al fatto che è stato inserito come testimone1 e testimane2 lo stesso soggetto e sono entrambi dichiaranti. Situazione che non dovrebbe succedere nella realtà e va evitata.

Inoltre ricordiamo che in generale va evitato di inserire due volte lo stesso dichiarante. (ad esempio indicando la madre con il flag dichiarante e poi passandola anche esplicidamente come firmataria).

Saluti 

Assistenza ANSC

**Comment by Sem98** [comment]
Modificando i testimoni l'errore si è risolto, grazie per l'aiuto
