### ISSUE TITLE
Richiesta chiarimento notifica SC03 NOTIFICA DI MUTAZIONE ANAGRAFICA

### ISSUE THREAD

**Issue by RBiasi** [italia/ansc#587]
Buongiorno,

il comune di Grottaferrata ha ricevuto 3 notifiche di tipo SC03 NOTIFICA DI MUTAZIONE ANAGRAFICA Id Notifica: 1310066, 1610005 e 1610010.

Le tre notifiche si riferiscono tutte e tre al Codice Caso d'Uso 1311 Trascrizione di nascita: Trascrizione di atto di nascita avvenuta all'estero su richiesta dell'autorita' diplomatica o consolare.

A seguito di questi tre atti:
2023-1563-1243-058046
2024-1991-11-058046
2024-1995-13-058046

vedo che l'Ufficiale d'Anagrafe ha proceduto con l'iscrizione per nascita in AIRE dei titolari.

Domando se le notifiche non avrebbero dovuto arrivare come Codice Tipo Notifica SC02 NOTIFICA DI ISCRIZIONE AIRE.

Rimango in attesa di un Vs. gentile riscontro.

Grazie

Roberta Biasi
Deda Next

**Comment by gbuemi** [comment]
Buongiorno @RBiasi,    
dai casi d'uso 1311 e 1312 di stato civile, potrebbero essere richieste all'ufficiale di anagrafe una operazione di prima iscrizione di un bambino aire oppure una mutazione di un soggetto già presente. 
Pertanto, al prossimo rilascio, provvederemo a censire il tipo di notifica come SC02 - NOTIFICA DI ISCRIZIONE_AIRE O MUTAZIONE ANAGRAFICA. Sarà cura dell'ufficiale di anagrafe distinguere quale tra le due azioni proposte dev'essere effettuata.

Grazie e saluti,
Supporto ANSC

**Comment by RBiasi** [comment]
Grazie,

il caso d'suo 1312 si genera anche per trascrizione di atto di nascita avvenuto all'estero di cittadino residente in APR corretto?

**Comment by gbuemi** [comment]
Il caso d'uso 1312 è una trascrizione di atto di nascita avvenuta all estero su richiesta di chi ha interesse alla trascrizione.

Un saluto,
Supporto ANSC
