### ISSUE TITLE
Nascita - Ora:minuti nascita

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#59]
Non sempre l'ora e minuti di nascita sono conosciuti.
Faccio riferimento , per esempio, a trascrizioni dall'estero dove magari non tengono nota di questi dati (già tanto che alcuni Stati forniscano l'anno di nascita).

**Comment by mttfranci** [comment]
Ok, grazie, stiamo valutando la vostra segnalazione.
Saluti

Assistenza ANSC

**Comment by asqueglia** [comment]
Buongiorno confermiamo che con il rilascio della versione 1.9.1 la segnalazione è stata corretta (ora e minuto nascita sono stati resi campi opzionali). E' possibile riprovare. Chiudiamo la issue, nel caso la preghiamo di riaprirla.
