### ISSUE TITLE
TRASCRIZIONE ATTI DALL’ESTERO IN WEBAPP

### ISSUE THREAD

**Issue by asqueglia** [italia/ansc#593]
DA LISSONE

Caso d’uso 2213 
Nel corpo dell’atto esce solo il giorno di trascrizione dell’atto e non l’ora. 
Vengono richiesti gli estremi del documento estero da trascrivere, ma spesso questo dato non è indicato nel documento stesso.
Nel corpo dell’atto compare “ho ricevuto da Consolato Generale d’Italia in Zurigo la richiesta in data 19.12.2023 di trascrivere il documento con estremi numero”. Sarebbe opportuno sostituire la parola “il documento” con ciò che viene indicato nei metadati nella casella “descrizione documento”; qualora non ci fosse il numero del documento da trascrivere, la dicitura “con estremi numero” andrebbe eliminata.

Nei dati generali dei metadati viene riportato il “testo trascrizione”. In considerazione che questo testo viene già riportato nel corpo dell’atto, non comprendiamo l’utilità di riportarlo nuovamente nei metadati anche perché viene riportato solo in parte.

**Comment by asqueglia** [comment]
Dalla call di approfondimento con ANUSCA del 17/01 emerge quanto seguen

- per quanto riguarda l'ora della trascrizione, ANUSCA conferma che per le trascrizioni l’ora non è richiesta nel formulario e non ha alcun rilievo
- per quanto riguarda la segnalazione sulla minuta, è stata preso in carico
- per quanto riguarda la richiesta di omettere come metadato il riassunto della trascrizione, ANUSCA conferma che è possibile non visualizzare nella copia conforme (estratto integrale) il riassunto della trascrizione; lascia un grado di libertà nella scelta di come procedere, ci si riserva di valutare tecnicamente la soluzione migliore

**Comment by amusarra** [comment]
Chiusa per [release 1.23.3](https://github.com/italia/ansc/releases/tag/v1.23.3)

Cordiali Saluti.
Supporto ANSC
