### ISSUE TITLE
Identificativo atto non omogeneo rispetto ad anno atto

### ISSUE THREAD

**Issue by antonioluberto** [italia/ansc#599]
Buongiorno.
Su ambiente di pre-produzione del Comune di Grottaferrata si è creato, con "idOperazione":"1727929", un atto di nascita con 
"dataformazione":"2023-12-08"
All'atto in questione è attribuito identificativo nazionale riferito all'anno corrente: 2024-1217236-1289-058046

**Comment by asqueglia** [comment]
Buongiorno, come condiviso prendiamo in carico la segnalazione
