### ISSUE TITLE
Casistiche di Morte -JSON errore su coniuge

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#6]
![Cattura_6](https://user-images.githubusercontent.com/127182190/223346790-a679c7d2-58c5-4b98-8fe5-56f33ea37de6.PNG)
![Cattura_5](https://user-images.githubusercontent.com/127182190/223346588-91eb38af-80d5-4ae4-a1b1-1dd4cf62c78c.PNG)

**Comment by asqueglia** [comment]
La segnalazione è stata risolta
