### ISSUE TITLE
Download versioni ANSC

### ISSUE THREAD

**Issue by migmar68** [italia/ansc#60]
Buongiorno
Attualmente è molto scomodo entrare in ogni singolo file per fare il download. O perlomeno io non ho capito come fare un download massivo.
E' possibile creare un'altra cartella VERSIONI con un unico file zip omnicomprensivo di tutti i files necessari per la versione?

**Comment by amusarra** [comment]
Salve @migmar68 può fare quanto desiderato direttamente da GitHub accedendo alle Release e scaricare l'archivio in formato zip o tar.gz.

![image](https://user-images.githubusercontent.com/708110/230590655-c17d9bac-669c-4d61-9baf-9888ef29515e.png)

Saluti.
