### ISSUE TITLE
Certificazione impossibile per atto di nascita

### ISSUE THREAD

**Issue by antonioluberto** [italia/ansc#602]
Con "idOperazione":"25178" il Comune di Grottaferrata ha creato atto di nascita prodotto per trascrizione di dichiarazione resa alla direzione sanitaria.
La nostra applicazione non gestisce al momento il caso d'uso specifico (Trascr_022, introdotto con la versione 1.6.0 della modellazione) e quindi l'atto viene trasmesso passando per il caso d'uso di servizio Trascr_999.
Pur avendo verificato la corretta valorizzazione dell'informazione relativa alla certificabilità dell'atto ("certificabile":"1"), da ANSC non è possibile ottenere il certificato di nascita né l'estratto per riassunto (solo copia integrale).

Temiamo che il problema possa essere legato all'utilizzo da parte nostra del caso d'uso di servizio. Questo però è assolutamente fisiologico: per l'avvio in esercizio controllato è stato implementato un numero di casi d'uso certamente inferiore rispetto a quelli complessivamente previsti (che, peraltro, continuano ad essere oggetto d' integrazione).

Rimaniamo in attesa di vostro riscontro.

**Comment by antonioluberto** [comment]
Lo stesso problema si verifica per atto creato con "idOperazione":"24772"

**Comment by gbuemi** [comment]
Buongiorno @antonioluberto,
abbiamo preso la segnalazione in carico ed è in lavorazione, seguiranno aggiornamenti al più presto.

Grazie e saluti,
Supporto ANSC

**Comment by asqueglia** [comment]
Buongiorno comunichiamo che con il rilascio odierno della versione 1.23.0 la segnalazione in oggetto è stata corretta; provvediamo quindi a chiudere la issue. In caso di ulteriori malfunzionamenti si prega di aprire una issue dedicata.
