### ISSUE TITLE
Sep_Div_003: errore metadato "tipoAccordo"

### ISSUE THREAD

**Issue by antonioluberto** [italia/ansc#603]
Il Comune di Grottaferrata ha creato 3 atti di matrimonio, caso d'uso Sep_Div_003, 
"idOperazione":"19342"
"idOperazione":"26364"
"idOperazione":"26314"
in relazione ai quali, per errore nell'applicazione locale, è stato indicato 
"tipoAccordo":"1"
in luogo del valore corretto che sarebbe dovuto essere

![image](https://github.com/italia/ansc/assets/26415430/18cf115d-9039-402b-9177-a64410592172)

Come possiamo sanare il dato?

**Comment by asqueglia** [comment]
Buongiorno verifichiamo e facciamo sapere

**Comment by asqueglia** [comment]
Buongiorno, dalle verifiche effettuate vi confermiamo che potete utilizzare l'annotazione per errore materiale ed inserire all'interno del testo dell'annotazione che non si tratta di accordo di separazione bensì di un accordo di cessazione degli effetti civili. Il dato tipoAccordo non è un dato certificabile per cui non è necessario modificarlo come metadato. I soli metadati modificabili tramite l'annotazione, sono quelli certificabili ossia che vengono usati nelle certificazioni. Quando è necessario, invece, correggere un **dato non certificablie** oppure la minuta dell'atto in qualche sua parte,  è sufficiente utilizzare l'annotazione per errore materiale inserendo solo il testo dell'annotazione, che comparirà negli estratti a margine dell'atto.

**Comment by asqueglia** [comment]
Buongiorno, non avendo avuto risposte in merito chiudiamo la issue. In caso di ulteriori dubbi vi chiediamo di riaprire la issue
