### ISSUE TITLE
[ws R008] Ricerca Notifiche - Atto di Morte: notifiche non pervenute

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/ansc#604]
ambiente PROD - comune di VALEGGIO SUL MINCIO (idComune 10420)

per l'atto di morte con idAnsc 2024-2220-14-023089 non sono arrivate le notifiche ANSC da confermare.

potete verificare, così da sbloccare anche l'invio della conseguente notifica ANPR?

grazie
Alessandro ADS

**Comment by amusarra** [comment]
Buongiorno. Abbiamo preso in carico la segnalazione.

Cordiali Saluti.
Supporto ANSC.

**Comment by amusarra** [comment]
Salve @AMonopoliADS 
È corretto che non vengano generate **notifiche ANSC** per soggetti con residenza estera (2299 - Caso d'uso di servizio trascrizioni di morte) e che adesso non vengano generate neanche quello verso ANPR. In futuro sarnno integrati i soggetti AIRE e seguiranno aggiornamenti.

Se non ci sono ulteriori dubbio e/o chiarimenti, chiediamo di chiudere la issue.

Cordiali Saluti.
Supporto ANSC.

**Comment by asqueglia** [comment]
Chiudiamo la presente issue. In caso di ulteriori dubbi preghiamo di aprirne una altra dedicata
