### ISSUE TITLE
Errore Validazione Atto di Nascita- Caso d'Uso 1312

### ISSUE THREAD

**Issue by KibMcris** [italia/ansc#605]
Buongiorno,
in ambiente di produzione ed in ambiente di pre-produzione, per il caso d'uso in oggetto, specificando la residenza straniera dell'intestatario dell'atto e del dichiarante si ottiene l'errore relativo al comune e/o provincia di residenza. Riporto richiesta e response di ANSC.
L' IdOperazione ANSC è 1729585. Segnalo che il comune ha la necessità di registrare l'atto anche in produzione.
Restiamo in attesa di riscontro

"testataRichiesta": {
		"idComune": 10288,
		"idOperazioneComune": 12,
		"dataOraRichiesta": "2024-01-10 12:52:35",
		"nomeApplicativo": "PEDemografici",
		"versioneApplicativo": "1",
		"fornitoreApplicativo": "Kibernetes srl"
	},
	"evento": {
		"idTipoEvento": "1",
		"idtipocontenuto": "3",
		"idUsecase": "1312",
		"descrizioneCasoUso": "Trascrizione di atto di nascita avvenuta all estero su richiesta di chi ha interesse alla trascrizione",
		"stato": "CONFERMATO",
		"flagsecretato": "0",
		"idVersion": "100005",
		"dataformazione": "2024-01-10",
		"annoAtto": "2024",
		"ora": "12",
		"minuto": "17",
		"operatore": "MRZRNT63B25B098V",
		"operatoreNome": "Nome",
		"operatoreCognome": "Cognome",
		"redattoNellaCasaComunale": true,
		"idComuneRegistrazione": "10288",
		"nomeComuneRegistrazione": "TROPEA",
		"idProvinciaRegistrazione": "102",
		"siglaProvinciaRegistrazione": "VV",
		"dataDecorrenza": "2024-01-10",
		"numeroatto": "3",
		"sentenzaFiglioIncestuoso": false,
		"propostaAnnotazione": false,
		"allegati": [
			{
				"id": "2252345",
				"idTipoAllegato": "27",
				"hashAllegato": "KoSjQdhNB7fmZHrVOqfzXxSr/bssJWSfEZfrwBuEni8="
			},
			{
				"id": "2252346",
				"idTipoAllegato": "28",
				"hashAllegato": "q+613CHxYkOpo9DCLdfm1A3Ep6dEDgb9nOFBOi6A5tI="
			}
		],
		"intestatari": [
			{
				"codiceFiscale": "",
				"cognome": "XXX",
				"nome": "XXX",
				"sesso": "M",
				"dataNascita": "1970-04-03",
				"idStatoNascita": "8",
				"nomeStatoNascita": "ARGENTINA",
				"idStatoResidenza": "8",
				"nomeStatoResidenza": "ARGENTINA",
				"idstatocivile": "1",
				"descrizionestatocivile": "CELIBE",
				"idNazionalita": "90",
				"nazionalita": "ITALIANA",
				"flagDichiarante": false,
				"flagComparente": false,
				"flagFirmatario": false
			}
		],
		"variazioni": [],
		"madre": {
			"codiceFiscale": "",
			"cognome": "XXX",
			"nome": "XXX",
			"sesso": "F",
			"dataNascita": "0001-01-01",
			"idstatocivile": "2",
			"descrizionestatocivile": "CONIUGATA",
			"idNazionalita": "0",
			"nazionalita": "NON DEFINITA",
			"flagDichiarante": false,
			"flagComparente": false,
			"flagFirmatario": false
		},
		"padre": {
			"codiceFiscale": "",
			"cognome": "XXX",
			"nome": "XXX",
			"sesso": "M",
			"dataNascita": "0001-01-01",
			"idstatocivile": "2",
			"descrizionestatocivile": "CONIUGATO",
			"idNazionalita": "0",
			"nazionalita": "NON DEFINITA",
			"flagDichiarante": false,
			"flagComparente": false,
			"flagFirmatario": false
		},
		"dichiarante": {
			"codiceFiscale": "",
			"cognome": "XXX",
			"nome": "XXX",
			"sesso": "M",
			"dataNascita": "1970-04-03",
			"idStatoNascita": "8",
			"nomeStatoNascita": "ARGENTINA",
			"idStatoResidenza": "8",
			"nomeStatoResidenza": "ARGENTINA",
			"idstatocivile": "1",
			"descrizionestatocivile": "CELIBE",
			"idNazionalita": "90",
			"nazionalita": "ITALIANA",
			"flagDichiarante": false,
			"flagComparente": false,
			"flagFirmatario": false
		}

HTTP Status 400 
{"testataRisposta":{"idComune":10288,"idOperazioneComune":"12","idOperazione":"1729585","idEsito":1},"errors":[{"code":"400003","severity":"E","text":"Attenzione! In caso di residenza estera comune e/o provincia di residenza non possono essere valorizzati."}],"infos":[{"code":"110527","severity":"I","text":"Informazioni sull'operazione da fornire in caso di assistenza : data:2024-01-10 11:52:37 , idOperazione:1729585"}]}

**Comment by asqueglia** [comment]
Con il rilascio della versione 1.22.3 la segnalzione è stata corretta. Chiudiamo pertanto la issue; nel caso di ulteriori segnalazioni la reghiamo di riaprire questa oppure una altra dedicata.
