### ISSUE TITLE
[R009] Errore validazione evento matrimonio

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#606]
Il sistema mi avverte che in caso di residenza estera non si devono specificare provincia e comune di residenza, ma in realtà tali campi non sono stati assegnati (per entrambi gli intestatari).

Di seguito request e response in ambiente di pre-produzione

REQUEST:
{
  "evento": {
    "idAnsc": "",
    "idTipoEvento": "3",
    "idtipocontenuto": "3",
    "idUsecase": "332000",
    "descrizioneCasoUso": "Trascrizione matrimoni dall'estero - Richiesta di trascrizione da parte del Consolato/Ambasciata",
    "stato": "CONFERMATO",
    "idVersion": "100007",
    "dataformazione": "2024-01-10",
    "ora": "15",
    "minuto": "11",
    "operatore": "DLCNTN57L67A064W",
    "operatoreNome": "MARGHERITA",
    "operatoreCognome": "CITTERIO",
    "idComuneRegistrazione": "5000",
    "nomeComuneRegistrazione": "LISSONE",
    "idProvinciaRegistrazione": "108",
    "siglaProvinciaRegistrazione": "MB",
    "numeroatto": "5",
    "allegati": [
      {
        "id": "2252432",
        "idTipoAllegato": "26",
        "hashAllegato": "cTqvvhrtvs6JEHkuJzcbm/mcxTk3fhYwesXoFXS60VY=",
        "descrizione": "Nota di trasmissione da parte dell\\'autoritÃ  consolare o diplomatica"
      }
    ],
    "intestatari": [
      {
        "cognome": "ADORNI",
        "nome": "ODOARDO PAOLO",
        "sesso": "M",
        "dataNascita": "1974-06-22",
        "idStatoNascita": "116",
        "nomeStatoNascita": "MESSICO",
        "idStatoResidenza": "116",
        "nomeStatoResidenza": "MESSICO",
        "idNazionalita": "90",
        "nazionalita": "ITALIANA",
        "flagDichiarante": false,
        "flagComparente": false,
        "flagFirmatario": false
      },
      {
        "cognome": "PXXXXXXI",
        "nome": "SXXA",
        "sesso": "F",
        "dataNascita": "1980-12-01",
        "idStatoNascita": "164",
        "nomeStatoNascita": "SPAGNA",
        "idStatoResidenza": "164",
        "nomeStatoResidenza": "SPAGNA",
        "idNazionalita": "164",
        "nazionalita": "SPAGNOLA",
        "flagDichiarante": false,
        "flagComparente": false,
        "flagFirmatario": false
      }
    ],
    "datiEventoMatrimonio": {
      "luogoCelebrazione": {
        "idStato": "164",
        "nomeStato": "SPAGNA",
        "comuneEstero": "MADRID"
      },
      "dataEvento": "2018-11-01"
    },
    "trascrizioneMatrimonio": {
      "dataComunicazione": "2023-09-01",
      "testoLibero": "jjkkhhj",
      "atto": {
        "enteEstero": {
          "nazioneEnte": "164",
          "nomeNazioneEnte": "SPAGNA",
          "idAnagraficaConsolato": "2480100",
          "nomeAnagraficaConsolato": "MADRID",
          "nomeEnte": "aut. mittente"
        }
      },
      "attoEstero": {
        "enteEstero": {
          "nazioneEnte": "164",
          "nomeNazioneEnte": "SPAGNA",
          "comuneEstero": "MADRID SPAGNA",
          "nomeEnte": "nome ente",
          "dataTrascrizione": "2021-11-16",
          "estremiDocumento": "CA123445'IO"
        }
      }
    },
    "composizioneCompleta": "             Oggi dieci del mese di gennaio dell'anno duemilaventiquattro alle ore quindici e          minuti undici nella casa comunale io sottoscritto CITTERIO MARGHERITA, Istruttore,          Ufficiale dello stato civile del Comune di LISSONE, per delega avuta, ho ricevuto da          aut. mittente la richiesta in data 01-09-2023 di trascrivere il documento con          estremi: CA123445'IO in data 16-11-2021 emesso da nome ente proveniente da SPAGNA, di          cui mi ha trasmesso copia.          Aderendo a tale richiesta, provvedo alla trascrizione del documento come segue:          jjkkhhj.    Dopo di che ho munito del mio visto ed inserito nel volume degli allegati          a questo registro la richiesta di trascrizione e la copia del documento trascritto.                                                                                                 "
  },
  "testataRichiesta": {
    "idComune": 5000,
    "idOperazioneComune": "4384",
    "dataOraRichiesta": "2024-01-10T15:16:45.06+01:00",
    "nomeApplicativo": "urbi",
    "versioneApplicativo": "1.1.0",
    "fornitoreApplicativo": "padigitale"
  }
}

RESPONSE:
{
  "testataRisposta": {
    "idComune": 5000,
    "idOperazioneComune": "4384",
    "idOperazione": "1729720",
    "idEsito": 1
  },
  "errors": [
    {
      "code": "400003",
      "severity": "E",
      "text": "Attenzione! In caso di residenza estera comune e/o provincia di residenza non possono essere valorizzati."
    },
    {
      "code": "400003",
      "severity": "E",
      "text": "Attenzione! In caso di residenza estera comune e/o provincia di residenza non possono essere valorizzati."
    }
  ],
  "infos": [
    {
      "code": "110527",
      "severity": "I",
      "text": "Informazioni sull'operazione da fornire in caso di assistenza : data:2024-01-10 14:16:47 , idOperazione:1729720"
    }
  ]
}

**Comment by amusarra** [comment]
Salve @biadanpad 
Questa issue è analoga alla #605 che abbiamo già preso in carico.

Cordiali Saluti.
Supporto ANSC.

**Comment by MarcoSalaPad** [comment]
Buongiorno,
abbiamo una previsione di rilascio? Perchè abbiamo gli atti bloccati e i clienti non possono proseguire.
Grazie

**Comment by amusarra** [comment]
Salve @MarcoSalaPad 
La risoluzione delle fix per #605 e #606 è prevista con il prossimo rilascio, la cui data di rilascio è prevista per il giorno 19/01/2024.

Cordiali Saluti.
Supporto ANSC.

**Comment by amusarra** [comment]
Salve @MarcoSalaPad e @biadanpad 
Potreste riprovare a eseguire un nuovo test?

Cordiali Saluti.
Supporto ANSC.

**Comment by biadanpad** [comment]
Adesso in pre-produzione funziona

**Comment by asqueglia** [comment]
Con la versione 1.22.3 è stata corretta la segnalazione e rilasciata la correzione in tutti gli ambienti. Chiudiamo pertanto la issue; in caso di ulteriori malfunzionamenti preghiamo di riaprire questa issue o una altra dedicata.
