### ISSUE TITLE
[R010] Anteprima atto di matrimonio - UseCase 329999

### ISSUE THREAD

**Issue by MarcoSalaPad** [italia/ansc#607]
Inseriamo da gestionale l'atto di matrimonio, dopo di che, prima di effettuare la validazione, invochiamo il servizio per avere la bozza/anteprima dell'atto.

De seguito la request:

{
  "evento": {
    "idAnsc": "",
    "idTipoEvento": "3",
    "idtipocontenuto": "1",
    "idUsecase": "329999",
    "stato": "BOZZA",
    "idVersion": "100006",
    "dataformazione": "2024-01-10",
    "ora": "12",
    "minuto": "49",
    "operatore": "BRGCST86R59F205R",
    "operatoreNome": "CRISTINA",
    "operatoreCognome": "BORGATO",
    "idComuneRegistrazione": "5000",
    "nomeComuneRegistrazione": "LISSONE",
    "idProvinciaRegistrazione": "108",
    "siglaProvinciaRegistrazione": "MB",
    "dataDecorrenza": "2024-01-10",
    "numeroatto": "1",
    "allegati": [
      {
        "id": "2610799",
        "idTipoAllegato": "86",
        "hashAllegato": "pL2UxnDRPrXUCcuTH4hLmxXkLZZSeZrXdqNWvS9Qf8o=",
        "descrizione": "Certificato di eseguita pubblicazione"
      },
      {
        "id": "2610798",
        "idTipoAllegato": "90",
        "hashAllegato": "F1HCpi9XcdIH8bhLABS/Y/sZKS4VGMWbhnzO19BUwgs=",
        "descrizione": "Copia atto di matrimonio trascritto"
      }
    ],
    "intestatari": [
      {
        "cognome": "PITTELLI",
        "nome": "MARCO",
        "sesso": "M",
        "dataNascita": "1979-05-13",
        "idComuneNascita": "6218",
        "nomeComuneNascita": "MONZA",
        "idProvinciaNascita": "15",
        "siglaProvinciaNascita": "MI",
        "idStatoNascita": "90",
        "nomeStatoNascita": "ITALIA",
        "idComuneResidenza": "5000",
        "nomeComuneResidenza": "LISSONE",
        "idProvinciaResidenza": "108",
        "siglaProvinciaResidenza": "MB",
        "idStatoResidenza": "90",
        "nomeStatoResidenza": "ITALIA",
        "idNazionalita": "90",
        "nazionalita": "ITALIANA",
        "flagDichiarante": false,
        "flagComparente": false,
        "flagFirmatario": false
      },
      {
        "cognome": "DE CARLO",
        "nome": "PAOLA",
        "sesso": "F",
        "dataNascita": "1992-03-06",
        "idComuneNascita": "18713",
        "nomeComuneNascita": "RHO",
        "idProvinciaNascita": "15",
        "siglaProvinciaNascita": "MI",
        "idStatoNascita": "90",
        "nomeStatoNascita": "ITALIA",
        "idComuneResidenza": "5000",
        "nomeComuneResidenza": "LISSONE",
        "idProvinciaResidenza": "108",
        "siglaProvinciaResidenza": "MB",
        "idStatoResidenza": "90",
        "nomeStatoResidenza": "ITALIA",
        "idNazionalita": "90",
        "nazionalita": "ITALIANA",
        "flagDichiarante": false,
        "flagComparente": false,
        "flagFirmatario": false
      }
    ],
    "datiEventoMatrimonio": {
      "luogoCelebrazione": {
        "idComune": "5000",
        "nomeComune": "LISSONE",
        "idProvincia": "108",
        "siglaProvincia": "MB",
        "idStato": "90",
        "nomeStato": "ITALIA"
      },
      "dataEvento": "2023-12-30",
      "officiante": "1",
      "officianteEvento": {
        "flagDichiarante": false,
        "flagComparente": false,
        "flagFirmatario": true
      },
      "numeroTestimoni": "0",
      "pubblicazioneInPiuComuni": false,
      "pubblicazione1": {
        "idProvincia": "108",
        "provincia": "MB",
        "idComune": "5000",
        "comune": "LISSONE",
        "dataInizio": "2023-11-23",
        "dataFine": "2023-11-30"
      },
      "omissionePubblicazione": false
    },
    "datiAnnotazione": [
      {
        "testoAnnotazione": "Con dichiarazione resa nell'atto di matrimonio controscritto, gli sposi hanno scelto il regime della separazione dei beni.\n\n",
        "tipoAnnotazione": "1"
      },
      {
        "testoAnnotazione": "In data 10.01.2024 ho trasmesso notizia al ministro del culto di LISSONE dell'eseguita trascrizione dell'atto sovrascritto con l'indicazione della data in cui essa e' stata effettuata.\n\n",
        "tipoAnnotazione": "2"
      }
    ],
    "composizioneCompleta": "               L'anno duemilaventiquattro addi' dieci del mese di gennaio alle ore dodici e minuti               quarantanove nella Casa comunale. Io BORGATO CRISTINA, Istruttore Ufficiale dello               Stato civile del Comune di LISSONE per delega avuta ho ricevuto da Don Daniele Stocco               con sua nota del 02.01.2024 l'originale di atto di matrimonio, da cui risulta quanto               appresso:               L'anno DUEMILAVENTITRE addi' TRENTA del mese di DICEMBRE alle ore DIECI e minuti               TRENTA in LISSONE nella Parrocchia Cuore Immacolato di Maria sono stati uniti in               matrimonio, secondo il rito Concordatario:               PITTELLI MARCO nato in MONZA li 13.05.1979 (1979/n.1042/p.1/s.A) residente in LISSONE               cittadino ITALIANO;               DE CARLO PAOLA nata in RHO li 06.03.1992 (1992/n.207/p.1/s.A) residente in LISSONE               cittadina ITALIANA.               Agli sposi e' stata data lettura degli artt.143, 144 e 147 del Codice Civile da Don               Daniele Stocco delegato del Parroco davanti al quale il matrimonio e' stato               celebrato.               Io sottoscritto Ufficiale dello Stato Civile, ho constatato che la pubblicazione fu               eseguita senza alcuna opposizione nel comune di LISSONE dal 23.11.2023 al 30.11.2023               e che l'atto e' regolare.               Gli sposi, alla presenza degli stessi testimoni, hanno dichiarato di  scegliere il               regime della separazione dei beni, a norma dell'art. 162, secondo comma, del codice               civile.               Dato atto di quanto sopra, ho eseguito in data odierna la trascrizione dell'atto di               matrimonio, e dopo averli muniti del mio visto, inserisco l'atto medesimo e i               documenti acquisiti nel volume degli allegati al presente registro."
  },
  "testataRichiesta": {
    "idComune": 5000,
    "idOperazioneComune": "8264",
    "dataOraRichiesta": "2024-01-10T15:15:53.734+01:00",
    "nomeApplicativo": "urbi",
    "versioneApplicativo": "1.0.0",
    "fornitoreApplicativo": "padigitale"
  }
}

Come si può vedere, ci sono due annotazioni distinte tra loro (testo Annotazione 1 e testo Annotazione 2).
Nell'anteprima che ci viene restituita, non vediamo le due annotazioni riportate nella request ma viene ripetuta due volte la stessa.

![Annotazioni](https://github.com/italia/ansc/assets/52407655/3bcf5028-8f87-4dab-bc3f-3117366dbe10)

Il comune non riesce quindi a capire se è un problema di visualizzazione e proseguendo le informazioni saranno registrate correttamente. 

Attendiamo un vostro riscontro per la sistemazione dell'anteprima e per capire come gestire il proseguo dell'atto con il cliente.

**Comment by mttfranci** [comment]
Salve, abbiamo preso in carico la segnalazione.

Saluti

Assistenza ANSC

**Comment by mttfranci** [comment]
@MarcoSalaPad buongiorno, il dato viene salvato correttamente, l'anomalia è relativa alla sola visualizzazione, stiamo comunque lavorando alla soluzione.

Saluti

Assistenza ANSC

**Comment by mttfranci** [comment]
@MarcoSalaPad  dovremmo aver corretto l'anomalia con la patch #608 

Saluti

Assistenza ANSC
