### ISSUE TITLE
Numerazione atto comunale univoca

### ISSUE THREAD

**Issue by migmar68** [italia/ansc#609]
Riceviamo come Maggioli, ticket dal Comune di Monza (non in ANSC).
Il Comune di Monza deve registrare nella sua rubrica nati nel suo comune, ma dichiarati in altro comune. Nello specifico il Comune di Lissone che è in ANSC. 
Sembra dai dati che Monza ha tentato di registrare che il comune di Lissone ha attribuito a atti diversi, lo stesso numero di atto comunale. Chiaramente l'id atto ANSC è diverso in quanto è diverso il numero nazionale.
In questo momento il nostro sw ha un controllo superfluo sulla numerazione dell'atto comunale, che potremmo togliere (per un atto ANSC).

Colgo l'occasione tuttavia per chiedere un chiarimento: finora ho sempre percepito che anche la numerazione dell'atto comunale deve essere univoca, all'interno dell'anno. Per cui una nascita in quello che era la vecchia parte 1 serie A, così come la nascita parte 2 serie B, e un atto di morte parte 1, devono avere se ho capito bene 3 numeri comunali diversi, anche se fossero i primi atti dell'anno.
Potete chiarire in un senso o nell'altro?

**Comment by mttfranci** [comment]
Salve, come avete detto anche voi l'indicazione generale è che la numerazione comunale sia univoca all'interno dell'anno; però nei limiti della lunghezza massima prevista, è a carico del comune la gestione di tale numerazione e il sistema ANSC non effettua nessun controllo stringente. Questo anche perchè per noi è importante che l'id ANSC completo del tipo AAAA-NNNN-CCC-IIIIII sia univoca, la sola porzione comunale è di gestione del singolo comune e non ci sono garanzie specifiche di univocità.

Saluti

Assistenza ANSC

**Comment by migmar68** [comment]
Grazie per il riscontro

**Comment by asqueglia** [comment]
Buongiorno è stato concordato con il Dipartimento e con i comuni in produzione che non ci sarà alcun controllo da parte del sistema sul numero comunale che resta una responsabilità esclusiva dei comuni. Non è stato indicato alcun vincolo a cui è soggetto il numero comunale. Per qualsiasi richiesta di informazione o approfondimento in merito si prega di rivolgersi al Dipartimento.
