### ISSUE TITLE
idUseCase = "321311  "Matrimonio con Rito Religioso Cattolico"

### ISSUE THREAD

**Issue by Renato2502** [italia/ansc#61]
La trascizione dell'atto di matrimonio Religioso non prevede i testimoni.
nel Case in oggetto pur essendo indicato la non obbligatorietà dei testimoni gli stessi vengono resi obbligatori.
(E) 400003: Il campo evento.datiEventoMatrimonio.testimone1.nome nella sezione Testimone 1 è obbligatorio
(E) 400003: Il campo evento.datiEventoMatrimonio.testimone2.nome nella sezione Testimone  è obbligatorio
Abbiamo provato a non valorizzare  "evento.datiEventoMatrimonio.numeroTestimoni" o a valorizzarlo con 0 ma otteniamo il seguente errore: evento.datiEventoMatrimonio.numeroTestimoni nella sezione Dettagli evento non corrisponde al pattern ^[2-4]$

**Comment by amusarra** [comment]
Salve @Renato2502 
Al fine di condurre le analisi in modo agevole, potrebbe fornire l'idOperazione e il payload di richiesta?

Grazie.
Suporto ANSC

**Comment by amusarra** [comment]
Salve @Renato2502 
Il caso d'uso [3.2.1.3.1.1] **non è una trascrizione ma un matrimonio religioso celebrato con rito cattolico** non su delega di altro comune in luogo di culto cattolico, i testimoni sono in tal caso obbligatori perché così ci dice a normativa.

Le trascrizioni sono i casi d'uso **3.3.xxxx**  che non prevedono i testimoni.

Saluti.
Support ANSC

**Comment by Renato2502** [comment]
Buongiorno,
Il matrimonio in oggetto è celebrato dal ministro di culto che redige l'atto in duplice copia e ne trasmette uno all'Ufficiale di Stato Civile competente con la richiesta di trascrizione entro 5 giorni.
L'ufficiale di Stato Civile provvede alla trascrizione dell'atto ricevuto nella parte II serie A Matrimoni Religiosi (così come anche da voi indicato nei casi d'uso)
in detta trascrizione non vengono inseriti i testimoni.
Il caso d'uso in oggetto è chiaramente riferibile alla celebrazione di matrimonio religioso da parte di un ministro di culto e non dall'ufficale di stato civile o altra persona delegata.
Questa la normativa in essere.
Si allega schema modello e si resta in attesa di vostri chiarimenti.
[202304130952-1.pdf](https://github.com/italia/ansc/files/11219658/202304130952-1.pdf)

**Comment by asqueglia** [comment]
Buongiorno, si tratta di un bug che provvederemo a risolvere quanto prima.

**Comment by asqueglia** [comment]
Buongiorno, ieri è stata rilasciata la versione 1.6.2 che risolve quanto segnalato.
