### ISSUE TITLE
Dic_Nasc_030: errata valorizzazione metadato "ConsensoMadre"

### ISSUE THREAD

**Issue by antonioluberto** [italia/ansc#610]
A causa di errori sull'applicazione locale, presso il Comune di Grottaferrata (ambiente di produzione) è stato creato un atto di nascita (Dic_Nasc_030) valorizzando erroneamente l'oggetto:
_ConsensoMadre_

Questo comporta che in anteprima atto si abbia l'indicazione errata:

![image](https://github.com/italia/ansc/assets/26415430/7e32369c-a337-40b9-a3a4-8aea3851eed9)

Come possiamo sanare l'errore?

Grazie,
Antonio

**Comment by antonioluberto** [comment]
Buongiorno.
Gli identificativi degli atti interessati sono:
2024-2430-37-058046
2023-1753-1264-058046

**Comment by asqueglia** [comment]
Buongiorno come concordato durante le riunioni periodiche, questa casistica va corretta tramite la nota tecnica rilasciata il 29/02 con la versione 1.25.0 del sistema. Provvediamo pertanto a chiudere la presente issue invitandovi a contattarci per qualsiasi problematica in merito all'utilizzo della nota tecnica.
