### ISSUE TITLE
Titolo: [R009] - Prenotazione evento per gemelli non nati vivi.

### ISSUE THREAD

**Issue by gcuci** [italia/ansc#611]
buongiorno,

il servizio di prenotazione per le nascite gemellari, accetta nella Request, una lista di numeri comunali, pari al numero dei gemelli nati vivi, impostato nel campo numeroGemelliNatiVivi della stessa Request.

Questo però non permette di gestire correttamente, il contenuto degli atti, nel caso qualcuno dei gemelli sia non nato vivo. Non potendo infatti eseguire la prenotazione anche per questi, non si possono inserire nella composizione degli atti, i riferimenti agli atti di tutti gli altri gemelli (precedenti e successivi).

Potete darci indicazioni in merito?

In attesa di riscontro,

cordiali saluti.

**Comment by asqueglia** [comment]
Buon pomeriggio, la preghiamo di fare riferimento alla issue #571 dove viene trattato l'argomento e dove sono riportate le indicazioni di ANUSCA per la gestione dei casi particolari.

**Comment by gcuci** [comment]
Grazie per la risposta.

Non ci è però ancora chiaro come gestire i gemelli non nati vivi.

Potremmo momentaneamente bypassare il problema, indicando nel campo numeroGemelliNatiVivi della request, il numero totale di gemelli (compresi i non nati vivi), in modo da avere tutti gli idAnsc prenotati, anche perchè l'informazione del nato vivo o meno, è un metadato che viene poi passato per ogni singolo evento. Ma probabilmente non sarebbe la soluzione più corretta.

In fondo alla issue #571 però scrivete che '... procederemo comunque a dare la possibilità di indicare il caso in cui uno o più gemelli sono nati morti.' E' prevista una soluzione definitiva?


In attesa di riscontro,

cordiali saluti.

**Comment by asqueglia** [comment]
Buongiorno, la soluzione da applicare per questo caso è indicare il numero totale di gemelli sia quelli nati vivi che quelli nati morti, specificando il caso d'uso di servizio. Modificheremo il caso d'uso di servizio per accettare anche l'informazione del metadato natomorto.

**Comment by asqueglia** [comment]
Buongiorno comunichiamo che con il rilascio odierno della versione 1.23.0 la segnalazione in oggetto è stata corretta; provvediamo quindi a chiudere la issue. In caso di ulteriori malfunzionamenti si prega di aprire una issue dedicata.

**Comment by asqueglia** [comment]
Buongiorno comunichiamo che con il rilascio odierno della versione 1.23.0 la segnalazione in oggetto è stata corretta; provvediamo quindi a chiudere la issue. In caso di ulteriori malfunzionamenti si prega di aprire una issue dedicata.
