### ISSUE TITLE
Notifiche ANPR per titolare atto digitale iscritto all' AIRE

### ISSUE THREAD

**Issue by antonioluberto** [italia/ansc#614]
Buongiorno.

Nel caso in cui il soggetto titolare di atto di stato civile digitale sia residente all'estero ma di cittadinanza italiana e, quindi, iscritto all'AIRE di Comune italiano, come avviene al generazione della notifica ANPR collegata all'atto medesimo.
Esempio:
il cittadino
Rossi Luigi
è iscritto all'AIRE del Comune di Grottaferrata e risiede a Londra.
Contrae matrimonio a Rosignano Marittimo (con cittadina straniera).
A seguito del matrimonio deve essere, il Comune di Grottaferrata deve effettuare la mutazione di stato civile per il soggetto in questione.
Tra le generalità anagrafiche previste alla generazione/sottoscrizione dell'atto ANSC non ci pare ve ne siano di utilizzabili per comunicare ad ANSC lo stato anagrafico del soggetto, né l'eventuale comune di iscrizione AIRE dello stesso.
Ci sfugge qualcosa?
Dobbiamo attendere eventuale modifica al servizio R014 per integrare questo tipo di informazioni?

Rimaniamo in attesa di vostro riscontro.
Saluti,
Antonio

**Comment by asqueglia** [comment]
Buon pomeriggio, al momento il sistema non prevede la gestione dei soggetti aire; l'intervento rientra nel piano operativo di quest'anno. Stiamo lavorando alla pianificazione di tutte le attività previste. 
Nello specifico, per questo intervento si prevedrà di acquisire, durante la registrazione dell'evento, l'informazione del comune aire di iscrizione fondamentale per l'invio corretto delle notifiche anagrafiche. Appena avremo chiara la pianificazione e le specifiche di intervento comunicheremo tempestivamente

**Comment by antonioluberto** [comment]
Buonasera.
Integrare le informazioni relative al Comune di iscrizione AIRE in sede di registrazione dell'evento significa che si prevede di modificare tutti i casi d'uso fin qui modellati?

**Comment by asqueglia** [comment]
Buongiorno @antonioluberto, ovviamente terremo presente le implementazioni già fatte cercando di impattare il meno possibile. Siamo in produzione e non possiamo permettercelo.. questo è chiaro. Faremo sapere la soluzione che adotteremo, una volta conclusa la fase di analisi appena ci inizieremo a lavorare concretamente.

**Comment by asqueglia** [comment]
Chiudiamo la issue e faremo sapere tramite il changelog il rilascio che conterrà l'attività in oggetto.
