### ISSUE TITLE
[R006] - Errore firma USC

### ISSUE THREAD

**Issue by LucaBonini64** [italia/ansc#615]
Buongiorno,
in ambiente Pre-Produzione stiamo provando a firmare l'evento 1217781 inviato la seguente request:
{
	"firmaInput": {
		"idEvento": "1217781",
		"parametriFirma": {
			"idTipoFirma": "1",
			"idModalitaInput": "2",
			"inputFirma1": "VGVzdFVzZXI=",
			"inputFirma2": "VGVzdFBhc3N3b3Jk",
			"inputFirma3": "VGVzdE90cA=="
		}
	},
	"testataRichiesta": {
		"idComune": 6498,
		"idOperazioneComune": "653",
		"dataOraRichiesta": "2024-01-15T16:59:26.6410399+01:00",
		"nomeApplicativo": "hyperSIC.StatoCivile",
		"versioneApplicativo": "9.23.17.01.A02",
		"fornitoreApplicativo": "APKAPPA S.r.l."
	}
}
ma otteniamo la seguente risposta:
The remote server returned an error: (500) Internal Server Error.

potete verificare per cortesia?

Grazie.

**Comment by mttfranci** [comment]
@LucaBonini64 salve, sembrerebbe che stiate passando come proprietà "otp" del JWT il valore "TestOTP" invece di un valore numerico (Quello di default per l'ambiente di preproduzione "123456" o uno generato dall'applicazione).

Il servizio di firma contiene sia l'otp del JWT (numerico) che l'otp della firma remota nel payload della richiesta (alfanumerico).

Siamo a disposizione per ogni ulteriore chiarimento.

Saluti

Assistenza ANSC

**Comment by LucaBonini64** [comment]
Buongiorno @mttfranci,
inviamo il valore TestOTP perché ci era stato indicato nella #322.
Comunque per capire meglio l'otp del JWT e l'otp della firma remota sono generalmente 2 valori differenti perché il primo è per l'accesso alla procedura e l'utente lo ottiene dal portale di ANSC mentre il secondo viene ottenuto dal servizio di firma remota, è corretto?

Detto questo non riesco però a firmare anche mettendo quello di default (123456) perché invio il payload:
{"firmaInput":{"idEvento":"1217846","parametriFirma":{"idTipoFirma":"1","idModalitaInput":"2","inputFirma1":"VGVzdFVzZXI=","inputFirma2":"VGVzdFBhc3N3b3Jk","inputFirma3":"MTIzNDU2"}},
"testataRichiesta":{"idComune":6498,"idOperazioneComune":"663","dataOraRichiesta":"2024-01-16T12:29:09.018918+01:00","nomeApplicativo":"hyperSIC.StatoCivile","versioneApplicativo":"9.23.17.01.A02","fornitoreApplicativo":"APKAPPA S.r.l."}}
e ottengo:
{"errors":[{"code":"406007","severity":"E","text":"Firma Remota non avvenuta con successo"}],"infos":[{"code":"110527","severity":"I","text":"Informazioni sull'operazione da fornire in caso di assistenza : data:2024-01-16 11:29:09 , idOperazione:1732632"}],"testataRisposta":{"idComune":6498,"idEsito":1,"idOperazione":"1732632","idOperazioneComune":"663"}}

Grazie.

**Comment by mttfranci** [comment]
@LucaBonini64  si, l'otp nel JWT è proprio del sistema ANSC, presente per tutti i servizi ed è quello che autorizza ad usare il servizio.
L'otp della firma invece si usa solo per l'operazione di firma remota, è presente nel payload della richiesta e viene passato così come è al fornitore della firma.

Nel nuovo tentativo avete invece indicato "123456" per entrambi.

Invece nel JWT va quello di autenticazione (o per produzione quello generato dall'apposità funzionalità per gli USC) : 

{
  "sub": "***************",
  "iat": "1705404549",
  "exp": "1705406349",
  "nbf": "3000",
  "jti": "03e259f2-0409-42b4-9a79-9c6f8b6cdb18",
  "sede": "006114",
  "postazione": "006114-PC-****",
  **"otp": "123456"**
}

Mentre nella request andava bene la prima versione inviata (TestUser) ovvero : 

"inputFirma3": "VGVzdE90cA=="

Saluti

**Comment by LucaBonini64** [comment]
Buongiorno @mttfranci,
effettivamente usavamo lo stesso otp per entrambi i casi, adesso dovremmo aver corretto ma continua a risponderci "firma non avvenuta con successo".
Questo il Payload:
{"firmaInput":{"idEvento":"1217937","parametriFirma":{"idTipoFirma":"1","idModalitaInput":"2","inputFirma1":"VGVzdFVzZXI=","inputFirma2":"VGVzdFBhc3N3b3Jk","inputFirma3":"VGVzdE90cA=="}},
"testataRichiesta":{"idComune":6498,"idOperazioneComune":"671","dataOraRichiesta":"2024-01-17T11:24:40.6659112+01:00","nomeApplicativo":"hyperSIC.StatoCivile","versioneApplicativo":"9.23.17.01.A02","fornitoreApplicativo":"APKAPPA S.r.l."}}
e questa la response
{"errors":[{"code":"406004","severity":"E","text":"Firma non avvenuta con successo"}],"infos":[{"code":"110527","severity":"I","text":"Informazioni sull'operazione da fornire in caso di assistenza : data:2024-01-17 10:24:41 , idOperazione:1733133"}],"testataRisposta":{"idComune":6498,"idEsito":1,"idOperazione":"1733133","idOperazioneComune":"671"}}

come OTP per il JWT ho usato quello ottenuto dal portale di ANSC e come OTP per la firma lo standard 'TestOtp', cosa stiamo ancora sbagliando?

Grazie.

**Comment by asqueglia** [comment]
Buonasera con il rilascio della versione 1.23.2 la segnalazione è stata corretta. Pertanto chiudiamo la issue. In caso di ulteriori problemi si prega di aprire una issue dedicata
