### ISSUE TITLE
[ws R002] Estratto per Copia Integrale - Riconoscimento pre-natale (useCase 12216300)

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/ansc#620]
ambiente PRE - comune di FAENZA (idComune 3743)

buongiorno.

mi rifaccio ad un tema emerso nella call di questa mattina: richiesta di Estratto per Copia Integrale per Atto di Riconoscimento pre-natale.

da web-service (ws R002 - idTipoCertificato '3') non si riesce ad ottenere la copia integrale perchè il servizio risponde con l'errore:
"Soggetto intestatario non specificato correttamente"

la stessa segnalazione era già stata fatta con la issue #223 e doveva essere risolta con la versione 1.12.0.

oggi si ripresenta lo stesso problema (anche in produzione)

si può vedere come esempio la prova fatta in pre-produzione:  idOperazioneAnsc: 1732730 - data: 2024-01-16 13:35:41 ,

grazie
Alessandro ADS

**Comment by gbuemi** [comment]
Buongiorno,
vi comunichiamo che abbiamo effettuato un rilascio in preproduzione e produzione, potete riprovare?

Un saluto,
Supporto ANSC

**Comment by AMonopoliADS** [comment]
grazie @gbuemi 
il problema sembra risolto.
abbiamo richiesto l'estratto con idOperazioneAnsc 1733357 e abbiamo ottenuto il documento.

grazie

**Comment by asqueglia** [comment]
Chiudiamo la issue . In caso di ulteriori malfunzionamenti si prega di aprire una issue dedicata
