### ISSUE TITLE
[ws R009] Validazione - Riconoscimento pre-natale: intestatario senza generalità (errore)

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/ansc#622]
ambiente PRE - comune di FAENZA (idComune 3743)

la validazione di atto con generalità dell'intestatario non valorizzate (es. riconoscimento pre-natale - idUseCase 12214300) produce errore in validazione con questo messaggio:
"Il soggetto è già presente con id ..." ed il messaggio viene integrato con tutti gli idSoggettoAnsc presenti nel sistema (in questo caso, in pre-produzione, con circa 6800 id)
vedere come esempio la richiesta con idOperazioneAnsc 1733034 (data: 2024-01-17 08:59:13).

è possibile che il sistema centrale eviti la ricerca del soggetto in assenza delle generalità?

grazie
Alessandro ADS

**Comment by mttfranci** [comment]
@AMonopoliADS salve stiamo verificando la risposta del servizio.
In ogni caso per questo caso d'uso non è previsto l'intestatrio, https://github.com/italia/ansc/blob/main/docs/Mapping_casi_uso/riconoscimenti/Rico_016.csv, abbiamo verificato che se non viene inviata affatto la proprietà dell'array intestatari il messaggio sugli intestatari già presenti non viene restituito.
Oltretutto nel caso specifico, i dati dell'intestatario inviati non sembra molto significativi (in questi casi in particolare sconsigliamo di inviare dati non previsti deal caso d'uso dato che non aggiungono nessuna informazione) : 

```json
    "intestatari" : [ {
      "id" : null,
      "cognome" : null,
      "nome" : null,
      "sesso" : null,
      "descrizioneSesso" : "non conosciuto",
      "dataNascita" : null,
      "idComuneNascita" : null,
      "nomeComuneNascita" : null,
      "idProvinciaNascita" : null,
      "siglaProvinciaNascita" : null,
      "idStatoNascita" : null,
      "nomeStatoNascita" : null,
      "idComuneResidenza" : null,
      "nomeComuneResidenza" : null,
      "idProvinciaResidenza" : null,
      "siglaProvinciaResidenza" : null,
      "idStatoResidenza" : null,
      "nomeStatoResidenza" : null,
      "idNazionalita" : "90",
      "nazionalita" : "ITALIANA",
      "tipoImpedimento" : null,
      "flagDichiarante" : "false",
      "flagComparente" : "false",
      "flagFirmatario" : "false"
    } ],
```

Saluti

Assistenza ANSC

**Comment by asqueglia** [comment]
Chiudiamo la issue essendo molto vecchia. In caso si dovesse ripresentare il problema si prega di aprire una issue dedicata con il nuovo template.
