### ISSUE TITLE
ERRORE AMBIENTE TEST "Il campo evento.datiDiMorte.siglaProvinciaMorte nella sezione Dati Riconoscimento - Dati di morte non corrisponde al pattern ^[0-9]*$"

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#623]
Buongiorno,
testando i seguenti casi dei Riconoscimenti : RICO_004, RICO_005, RICO_008, RICO_012 e RICO_019 
nella richiesta di Validazione atto ci è arrivato l'errore in oggetto.

Nel json abbiamo introdotto, per esempio, il valore **TS** (provincia di Trieste).
Guardando nel tracciato evento ho visto che nelle varie "sigla provincia" esistenti nei vari model sono sempre di tipo String e negli esempi trovo 111 o RM.

Ci è venuto il dubbio se è corretto indicare la sigla alfabetica o se bisogna avere un codice numerico (immagino dalla tabella dei Comuni ANPR)

le lascio le informazioni nel caso servisse per le verifiche
  "idComune": 3655,
        "idOperazione": "1733298",

versione ansc usata 1.22

**Comment by amusarra** [comment]
Salve @annamaraspin 
Dal payload vedo come valore VC per `evento.DatiDiMorte.siglaProvinciaMorte` ed è corretto. Sull'attributo deve essere specificata la sigla mentre l'identificativo va sull'attributo `evento.DatiDiMorte.idProvinciaMorte`.

Abbiamo preso in carico la segnalazione.

Cordiali Saluti.
Supporto ANSC.

**Comment by annamaraspin** [comment]
grazie.
Attendiamo vostre notizie per riprovare.
