### ISSUE TITLE
Campo tipoNascitaSoggetto versione 1.23.0

### ISSUE THREAD

**Issue by siscomanpr** [italia/ansc#629]
Nel changelog della versione 1.23.0 è indicata l'aggiunta del campo tipoNascitaSoggetto nell'oggetto ModelDatiDiNascita, ma nel file model_evento.yaml risulta invece che sia stato aggiunto nell'oggetto ModelDocumentoRiconoscimento.

**Comment by gbuemi** [comment]
Buonasera,
si comunica che è stato corretto l'annidamento del campo tipoNascitaSoggetto, che erronamenente non faceva parte di ModelDatiDiNascita.

Grazie e saluti,
Supporto ANSC
