### ISSUE TITLE
RICO_010 allegato obbligatorio

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#634]
Buongiorno
nel mapping dello usecase in oggetto l'allegato
_Copia integrale dell'atto di nascita del figlio che viene riconosciuto_
è richiesto come obbligatorio se
_evento.datiEventoRiconoscimento.attoNascita.idComuneRegistrazione,!=,evento.idComuneRegistrazione_

Ho provato, in ambiente di test, di valorizzare entrambi i dati con lo stesso Comune.
Al momento del valida atto mi ha restituito l'errore
**400003 - Allegato obbligatorio mancante: [Copia integrale dell'atto di nascita del figlio che viene riconosciuto]**

L'allegato è sempre obbligatorio?

**Comment by amusarra** [comment]
Salve @annamaraspin
Potrebbe inviarci i dati per recuperare il payload in modo da analizzare al meglio la segnalazione?

Grazie.
Supporto ANSC.

**Comment by amusarra** [comment]
> idoperazione 1738916

Grazie. Poi siamo riiusciti a recuperare il payload e verificare l'anomalia già presa in carico.

Cordiali Saluti.
Supporto ANSC.
