### ISSUE TITLE
Annotazione relativa ad atto di dichiarazione di acquisto di cittadinanza

### ISSUE THREAD

**Issue by asqueglia** [italia/ansc#635]
SERRAVALLE SESIA

Atto formato in occasione della dichiarazione di voler acquistare la cittadinanza italiana da parte di cittadino nato in Italia e residente sul territorio fino al 18° anno di età – caso d’uso 51103 - (art. 4, c. 2 Legge n. 91/1992) e il file generato dal sistema relativo alla conseguente annotazione da apporre sull’atto di nascita dell’interessato.
Come si può notare, il testo inserito nel metadato “riassunto della dichiarazione”, presente nell’atto, è stato riportato nel testo dell’annotazione: l’annotazione generata presenta quindi una forma non corretta e non può essere accettata.

**Comment by amusarra** [comment]
Chiusa per [release 1.23.3](https://github.com/italia/ansc/releases/tag/v1.23.3)

Cordiali Saluti.
Supporto ANSC
