### ISSUE TITLE
[web-app] Divorzi / Separazione - Presenza Avvocati e Firma

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/ansc#638]
ambiente PRE - comune di FAENZA (idComune 3743)

buongiorno

non capiamo la gestione dei "firmatari" nei casi di Divorzi / Separazione con presenza di avvocati.

da questa issue di maggio 2023 (#145 ) sembra di capire che gli avvocati presenti debbano comparire tra i firmatari dell'atto.
di fatto non compaiono, nè attivando il flagFirmatario da web-service, nè registrando l'atto su web-app.

un esempio di atto su web-app appena fatto è questo: 2024‐1218557‐1001‐039010

si tratta di un caso d'uso 343000 - Descrizione caso d'uso: Conferma di accordo di separazione o divorzio
vengono indicati gli sposi e gli avvocati come presenti.
l'atto si conclude con la frase 
"Il presente atto viene letto ai dichiaranti i quali, insieme con me e con gli avvocati presenti per assisterli, lo sottoscrivono."
ma i firmatari che vengono gestiti sono solo gli sposi (sia nell'anteprima sia, sia nella procedura di firma)

potete chiarirci come è stato pensata questa situazione specifica oppure se si tratta di un bug?

grazie
Alessandro ADS

**Comment by amusarra** [comment]
Salve @AMonopoliADS 
Abbiamo preso in carico la sua segnalazione.

Cordiali Saluti.
Supporto ANSC

**Comment by asqueglia** [comment]
Buonasera con il rilascio della versione 1.23.2 la segnalazione è stata corretta. Pertanto chiudiamo la issue. In caso di ulteriori problemi si prega di aprire una issue dedicata
