### ISSUE TITLE
Trascrizione atto separazione da Stato estero su richiesta dell'interessato

### ISSUE THREAD

**Issue by rvinzani** [italia/ansc#639]
Da Rosignano: Al momento il caso d'uso prevede di inserire obbligatoriamente i dati dell'autorità mittente sono obbligatori ed è obbligatorio indicare il consolato (3.4.7.0.0.0).
Da prevedere l'eliminazione dell'obbligatorietà dell'autorità mittente?

**Comment by asqueglia** [comment]
Con la versione 1.23.6 è stata corretta la segnalzione. Chiudiamo pertanto la issue; in caso di ulteriori malfunzionamento la preghiamo di aprire una issue dedicata.
