### ISSUE TITLE
Caso uso 1314 - Trascrizione atto di nascita resa alla direzione sanitaria

### ISSUE THREAD

**Issue by siscomanpr** [italia/ansc#64]
E' normale che per il caso d'uso in oggetto, nel mapping (Trascr_022) vengono richiesti i dati `evento.trascrizioneNascita.atto.enteEstero` o è un refuso?

![image](https://user-images.githubusercontent.com/28776141/231832567-dc81420c-c6fe-467f-a8bc-3414f051e1ec.png)

**Comment by asqueglia** [comment]
Buongiorno, si tratta di un bug che stiamo provvedendo a correggere; a breve rilasceremo la fix e le faremo sapere.

**Comment by asqueglia** [comment]
Buongiorno, ieri è stato effettuato il rilascio della versione 1.6.2 che corregge la segnalazione indicata.
