### ISSUE TITLE
[R005] Modifiche post issue 401 - Annotazioni correttive multiple

### ISSUE THREAD

**Issue by LoreL56** [italia/ansc#640]
Buongiorno,

facciamo seguito alla issue 401 che avete risolto nel rilascio 1.20.0.

Stiamo testando in ambiente di preproduzione i comportamenti di annotazioni multiple di rettifica o di errore materiale apposte sullo stesso atto.

La modifica da voi apportata al servizio R005 di ricerca evento in buona parte funziona. 
Tuttavia ci sembra che non venga considerato l'orario delle annotazioni nel calcolo dei dati più recenti.

Come caso di test potete guardare l'atto di nascita con id ANSC = 1218258
![image](https://github.com/italia/ansc/assets/134919559/7bcd45e9-30c7-4e81-9a4d-d54aba0375c6)

Su tale atto sono state apposte diverse annotazioni. 
Le ultime due modificano entrambi le generalità del titolare ed hanno la stessa data ma un orario diverso:
1218710 - in data 21/01/24 00:00
![image](https://github.com/italia/ansc/assets/134919559/e04d17f2-62ed-4f58-8da3-3803a8cd6a4f)

1218737 - in data 21/01/24 01:00
![image](https://github.com/italia/ansc/assets/134919559/bf1ba7a3-a0fc-40fa-821f-76b8c7785123)

Alla richiesta dei dati dell'evento, impostando il flagRettifica="true" i dati tornati non sono quelli relativi all'annotazione apposta più recentemente (1218737) ma di quella appena prima (1218710).

Da notare che la webapp ANSC in consultazione riporta invece le generalità corrette.

Chiediamo gentilmente di verificare ed eventualmente correggere il servizio in modo da avere i dati più attuali anche in dipendenza dall'orario.

Grazie

**Comment by gbuemi** [comment]
Salve,
abbiamo preso in carico la segnalazione.

Un saluto.
Supporto ANSC
