### ISSUE TITLE
[R005] - ricerca intestatario - nessun risultato trovato in ricerca con cognome e nome

### ISSUE THREAD

**Issue by LucaBonini64** [italia/ansc#641]
Buongiorno,
permangono dei problemi sulla ricerca dell'intestatario già segnalati con la issue #518.

Il servizio R005 risponde restituendo la persona ricercata esclusivamente se si indica il codice fiscale dello stesso altrimenti non trova nessun risultato, abbiamo provato sia con solo cognome e nome che con cognome, nome e data di nascita, potete verificare?

Si allegano i payload e le response sia negative che positive.
[R005_Response_con_data_nascita.json](https://github.com/italia/ansc/files/14053590/R005_Response_con_data_nascita.json)
[R005_Payload_con_data_nascita.json](https://github.com/italia/ansc/files/14053592/R005_Payload_con_data_nascita.json)
[R005_Payload_senza_CF.json](https://github.com/italia/ansc/files/14053593/R005_Payload_senza_CF.json)
[R005_Response_senza_CF.json](https://github.com/italia/ansc/files/14053594/R005_Response_senza_CF.json)
[R005_Payload_con_CF.json](https://github.com/italia/ansc/files/14053595/R005_Payload_con_CF.json)
[R005_Response_con_CF.json](https://github.com/italia/ansc/files/14053596/R005_Response_con_CF.json)

Grazie.

Luca Bonini Apkappa

**Comment by gbuemi** [comment]
Salve @LucaBonini64 ,
abbiamo preso in carico la segnalazione.

Un saluto.
Supporto ANSC

**Comment by amusarra** [comment]
Chiusa per [release 1.23.3](https://github.com/italia/ansc/releases/tag/v1.23.3)

Cordiali Saluti.
Supporto ANSC
