### ISSUE TITLE
Errore 500 R007

### ISSUE THREAD

**Issue by Sem98** [italia/ansc#642]
Buonasera, da stamattina chiamando il servizio R007 per la fima USC ottengo errore 500 con questo messaggio di errore:

{"operation":"/services/service/firma/firma_usc/1"}

Allego il payload relativo alla chiamata:

{
	"testataRichiesta": {
		"versioneApplicativo": "1.0.0",
		"idOperazioneComune": "4887",
		"idComune": 9493,
		"dataOraRichiesta": "2024-01-25T11:08:36.947",
		"nomeApplicativo": "SIDe",
		"fornitoreApplicativo": "SistemiInformativi"
	},
	"firmaInput": {
		"idEvento": "1218738",
		"parametriFirma": {
			"idModalitaInput": "2",
			"inputFirma2": "VGVzdFBhc3N3b3Jk",
			"inputFirma1": "VGVzdFVzZXI=",
			"inputFirma3": "VGVzdE90cA==",
			"idTipoFirma": "1"
		}
	}
}

**Comment by mttfranci** [comment]
Salve stiamo verificando, intanto ci confermate che continuate ad avere il comportamento?

Saluti

Assistenza ANSC

**Comment by Sem98** [comment]
Salve, si, continuiamo ad avere il medesimo errore

**Comment by Sem98** [comment]
Buongiorno, continuiamo ad avere lo stesso errore riguardante la R007, volevamo sapere se ci fossero aggiornamenti rigurdanti il problema.
Grazie

**Comment by mttfranci** [comment]
@Sem98  si in realtà stavamo ancora raccogliendo i dettagli, ma sembrerebbe che ci sia stato un problema sull'ambiente di pre produzione che ha compromesso quello specifico evento e ci è complicato reperire i dettagli.

Potreste provare a verificare se registrando un evento simile si ripresenta?

Grazie in anticipo.

**Comment by Sem98** [comment]
Si, è tutto in preproduzione

**Comment by mttfranci** [comment]
Grazie del riscontro.

Questo tipo di errore : 

```json
{"operation":"/services/service/firma/firma_usc/1"}
```

L'anomalia potrebbe essere legata ad un problema sul JWT, il JWS o in generale sulla cornice della sicurezza.

Il servizio di firma è l'unico su cui avete questa anomalia?

Se non doveste risolvere dopo la verifica potete fornirci l'intera richiesta comprensiva delgli header, JWT, JWS ecc?

Grazie in anticipo

Potreste verificare e in caso

**Comment by Sem98** [comment]
Ciao, la R007 è l'unica che manifesta questa anomalia.

Allego JWT: "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsIng1YyI6WyJNSUlFNnpDQ0F0T2dBd0lCQWdJSUc2V0ZKYm5EemJnd0RRWUpLb1pJaHZjTkFRRUxCUUF3V2pFYk1Ca0dBMVVFQXd3U1EwRWdVRzl6ZEdGNmFXOXVhU0JUZG1sc01RMHdDd1lEVlFRTERBUkJUbEJTTVI4d0hRWURWUVFLREJaTmFXNXBjM1JsY204Z1pHVnNiQ2RKYm5SbGNtNXZNUXN3Q1FZRFZRUUdFd0pKVkRBZUZ3MHlNekEyTWpBeE5ETTJNemRhRncweU5URXdNRFV4TVRBNU1qUmFNSUdaTVJjd0ZRWURWUVFEREE0d05USXdNekl0VUVNdE1EQXdNakVkTUJzR0ExVUVDd3dVVUc5emRHRjZhVzl1YVNCa2FTQnNZWFp2Y204eE1UQXZCZ05WQkFzTUtFRnVZV2R5WVdabElFNWhlbWx2Ym1Gc1pTQlFiM0J2YkdGNmFXOXVaU0JTWlhOcFpHVnVkR1V4SHpBZEJnTlZCQW9NRmsxcGJtbHpkR1Z5YnlCa1pXeHNKMGx1ZEdWeWJtOHhDekFKQmdOVkJBWVRBa2xVTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFvVU5sUDdLSkI5V1BIY0E1a1V4KzZkNExnQ0MzN09XdW9kQ3J6UkJENWovQ3BzcFE5UHY2Q1FFaktUZ2hUZlhFU3FiNStzZ1ZUZ294dWZOQ2xoa2VveEovcGF0emp4cGxKbDVFUG9JcUJKZ3J5SFRHYTlSNCtYYm8yb2FCbXdXMUJWZnZWZ0dJZGNCUEIwT0F3NjVVV2NCSkdUalFjOGI0a0V6MGJObkpzWGVvaG9SWWVOSXIvRS9sODVhRU5weFQrWUxxelZVZ3grTjdmZ2V4Q0hqaHBORnlLUkEyTUlUcFowSHlmaFpFemxUbHhaM2tNV1lGN2V6N3ZndGdIdUJUR25odkNlY1hOVWViUmJ0cEd3YkFIRE1TaFZYL0FuUTcvcjBiNjdpSEVOWmVYditEb21Pak1TenZCR0xuMFZSbnlvS3pmSU8vQ3ZkNitLbXFEeXFDeXdJREFRQUJvM1V3Y3pBTUJnTlZIUk1CQWY4RUFqQUFNQjhHQTFVZEl3UVlNQmFBRkFZTG44cWgxNW10MUNMdXM0dXhGSlBJVjV0K01CTUdBMVVkSlFRTU1Bb0dDQ3NHQVFVRkJ3TUNNQjBHQTFVZERnUVdCQlRhbGNZUExDREVJTzF3UG80eWRyS2RhWlZuQWpBT0JnTlZIUThCQWY4RUJBTUNCNEF3RFFZSktvWklodmNOQVFFTEJRQURnZ0lCQURKZlNKN0pmQkJsMlVVQTZqci9Ic3dNNkVIUlJEZXZBNmhzTkExa3BsYXlneDlFbkdDMW4vWjhxK05NZXAzL3Z2TFcwaGcyYis2ckJSclpnaU9Nc1BoL1V2SmY5OUxoZHBEa0VSMHZOLysxM0xZYVpVZ2s1dkxtL29EaGdSK0dJSHpvNXYxVVBIeVdNczdpT0g5UXFmNE9aQjFxS1k0ZVp1bGt0U0VwZUNwbjBXYUhXb24rdnByc1FHSE5tZkw2MzdGWk5wRW9lMWJLYm9qNVNrdmwvKzV1WXVsc0IrNkFEanR6bHprLzNXM1dZMDhxUVh0cVVURzBzeWdCWjFzUzBRa0tsb1Bwa05Fb0lEMzcyRFM1MXRIZG5zejFIbFZ2MWwzaWNlRGxaQ01HcVVGRldwcVVyWE03SmVaQ0FvREp1amtwRkVvOEtlanRTNzJmQkloRG9TOFVuZC9wQTJuMXpzbjU2Z0xHVEg3aUFsTFk0azNzeDlYMmdEb2JyaENXTzQ0dDZtOTExTDlZcHd5Y0xocFlGOG0yNXFtaVZZdE5nYy8rTmJDUjZONm40VjJoanhzbWFLYlJJa0dkSExmdXh4NEpmNHB4bmlhSDdSc2pJRXR4dmIvWVA2ZXpjTVJGbG8wanlwbSt0Tmo0cWpKdlhRdzJLdUQzKzNLQmd6aWoyd3pRM09EbTlRWVNoQVNqYzZWd0ZHMUd4RkhRV2t4SkZqWjRPNExBUDYvOERtRmdhK3lpTE1GRGdvNkV2Mi83V0dvNXNMNDE1aVFCYTdiTlRMazZ2RGJ4OTBGTGUxejJsTDJUV1dmazVORmJ1QzFFc3dpbzZxcjh4N0c1MGJjMUY4MGN2ZjZ5U0paQlllcTRjY0FBUTZEYXlORzFhYkUwV2I2QTVKbWowdTZyIl19.eyJzdWIiOm51bGwsImlhdCI6MTcwNjcxNTAxMSwiZXhwIjoxNzA2Nzg3MDExLCJuYmYiOjE3MDY3MTUwMTEsImp0aSI6IlNlTUYwckExQVdNNGFGeWd4RVRtakEiLCJzZWRlIjoiMDUyMDMyIiwicG9zdGF6aW9uZSI6IjA1MjAzMi1QQy0wMDAyIiwib3RwIjoiMTIzNDU2In0.YmwuGD0pDcpQ6Lkdw6LMgf4LPuWLv83UCcRXnSRuWDeYrWeYCPuIUkB5lL2D_xajdyjjzPGHg8C1gYZYEWViR8ncZsqEGcV6xB3N3_Im2LF3YAT6FIRtCfFuCH3Zu01gLjivMLebiUpDtrSjQEmHpqYNA7pE2-9AfqzT6dIq_7UPpzzAyrqtCY7woI60NXJ-QvJcq3Ll-SMn9NMPKVPfio_hEVMRyWDoe12nyDdnGHu2uct3XiSdmFhn_VSXTUkYiKEMhgBhLQUaWTCAMG1isbRWUPP4pTW4JHB_Rr3oDjdZKMMsqEduKmFUyy7G2d5vu2hsb4P01lIe-AOQDRt7Fg"

JWS:"eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZXN0YXRhUmljaGllc3RhIjp7InZlcnNpb25lQXBwbGljYXRpdm8iOiIxLjAuMCIsImlkT3BlcmF6aW9uZUNvbXVuZSI6IjUxMjgiLCJpZENvbXVuZSI6OTQ5MywiZGF0YU9yYVJpY2hpZXN0YSI6IjIwMjQtMDEtMzFUMTU6MzA6MTAuOTA0Iiwibm9tZUFwcGxpY2F0aXZvIjoiU0lEZSIsImZvcm5pdG9yZUFwcGxpY2F0aXZvIjoiU2lzdGVtaUluZm9ybWF0aXZpIn0sImZpcm1hSW5wdXQiOnsiaWRFdmVudG8iOiIxMjE3OTUyIiwicGFyYW1ldHJpRmlybWEiOnsiaWRNb2RhbGl0YUlucHV0IjoiMiIsImlucHV0RmlybWEyIjoiVkdWemRGQmhjM04zYjNKayIsImlucHV0RmlybWExIjoiVkdWemRGVnpaWEk9IiwiaW5wdXRGaXJtYTMiOiJWR1Z6ZEU5MGNBPT0iLCJpZFRpcG9GaXJtYSI6IjEifX19.I79-p8BztsRpOjtRZlI2QAKusyNMfH5vNrHs4Q6JapkI_actms4fz4IukKwuaE7SHO__XfLu2KoYWeiT-YIIYnEoXrScHr-qEV3Fp6psppDoI1IFgHc_EiNrjQQoyOzCMOkpjvum-U3RiNuLq-CcZ4WtYeCORpw1Xe3emdzueGSq8M0zCRgPlf_3nsroTyq16lmgrmH4KHL1rcokXhS38wjgHSNfzA9miMB41bh0ZbSJtbQeB1dydsJI4QCgMEj3y1uvDv_Y_5TbnDhIKbCbMFBtoLMj1N3xUAhEVla7RDvI1QTvQJmn79oOENwYSmYp4bUU3zXe-jHsHqXFzloI2g"

**Comment by mttfranci** [comment]
@Sem98 apparentemente il campo sub del jwt che avete indicato non è impostato.
Potete verificarlo anche online, ad esempio : 
https://jwt.io/

"sub": null,

**Comment by Sem98** [comment]
Risolvendo l'errore nel JWT la R007 è tornata a funzionare correttaemnte.
Grazie per l'aiuto.

**Comment by mttfranci** [comment]
Perfetto.

Buona serata.

Assistenza ANSC
