### ISSUE TITLE
Ancora certificazione impossibile per atto di nascita 

### ISSUE THREAD

**Issue by antonioluberto** [italia/ansc#643]
Buongiorno.
Il problema relativo all'impossibilità di ottenere il certificato di nascita per atto gestito mediante caso d'uso di servizio Trascr_999 è ancora presente; fallisce ad esempio il tentativo di ottenere il certificato di nascita per
2024-1994-12-058046
sia da servizi sia da WebApp

**Comment by amusarra** [comment]
Buongiorno @antonioluberto 
Abbiamo preso in carico la sua segnalazione. 
Al fine di agevolare le attività di analisi potrebbe fornire l'idOperazione?

Cordiali Saluti.
Supporto ANSC.

**Comment by amusarra** [comment]
Salve @antonioluberto 
Siamo riusciti a recuperare l'operazione di richiesta del certificato la cui risposta è stata quella indicata a seguire.
Per il tipo di use case **Caso d'uso di servizio (trascrizioni nascita)**, il certificato che può essere richiesto è "Estratto per copia integrale", come anche mostrato da Web App.

La invitiamo per tanto a eseguire la richiesta con la tipologia di certificato richiesto.

```json
{
    "testataRisposta": {
        "idComune": 4559,
        "idOperazioneComune": "xxxxxxxxxx",
        "idOperazione": "xxxxxxx"
    },
    "errors": [
        {
            "code": "400003",
            "severity": "E",
            "text": "Il Tipo di certificato ESTRATTO_RIASSUNTO non può essere generato per l'atto 1994"
        }
    ],
    "infos": [
        {
            "code": "110527",
            "severity": "I",
            "text": "Informazioni sull'operazione da fornire in caso di assistenza : data:2024-01-25 08:55:10 , idOperazione:xxxxxx"
        }
    ]
}
```
Payload risposta servizio di certificazione.

![image](https://github.com/italia/ansc/assets/708110/1dc39eb4-d6de-4098-a91c-39c43f38347f)
Figura 1 - Richiesta certificati

Cordiali Saluti.
Supporto ANSC.

**Comment by antonioluberto** [comment]
Buonasera.
Come indicato nella https://github.com/italia/ansc/issues/602, il Comune di Grottaferrata ha creato atto di nascita per la _trascrizione di dichiarazione resa alla direzione sanitaria_.
La nostra applicazione non gestisce al momento il caso d'uso specifico (Trascr_022, introdotto con la versione 1.6.0 della modellazione) e quindi l'atto viene trasmesso passando per il caso d'uso di servizio Trascr_999.
Pur avendo verificato la corretta valorizzazione dell'informazione relativa alla certificabilità dell'atto ("certificabile":"1"), da ANSC non è possibile ottenere il certificato di nascita né l'estratto per riassunto che deve invece certamente essere possibile emettere.

Rimaniamo in attesa di vostre indicazioni

**Comment by amusarra** [comment]
Buongiorno @antonioluberto 
Potreste eseguire un nuovo test di richiesta per l'estratto per riassunto?
Dovrebbe funzionare.

Cordiali Saluti.
Supporto ANSC.

**Comment by antonioluberto** [comment]
Buonasera.
Confermiamo l'avvenuta soluzione del problema.
Saluti
