### ISSUE TITLE
Dichiarazione tardiva di filiazione fuori dal matrimonio resa all'USC da ostetrica o altro sanitario che ha assistito al parto - nato vivo ma morto prima della dichiarazione (Dic_Nasc_059)

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#644]
Ambiente test

Buongiorno,
nel mapping in oggetto sono obbligatori i dati dei genitori.
![image](https://github.com/italia/ansc/assets/127182190/42e2a511-bd50-4284-b078-07109ebcee66)

Si tratta di una Dichiarazione di Filiazione fuori dal matrimonio **non** riconosciuta. Se non è riconosciuta, non posso introdurre i dati dei genitori.

Mentre nelle stesse casistiche ma col bambino "nato morto" (dic_nasc_058) e "vivo" (dic_nasc_057) non vengono manco menzionati i dati del genitore nei mapping (giustamente).

Idem in Webapp.

**Comment by amusarra** [comment]
Buongiorno @annamaraspin 
Abbiamo preso in carico la sua segnalazioni per le verifiche preliminari.

Cordiali Saluti.
Supporto ANSC.

**Comment by amusarra** [comment]
Chiusa per [release 1.23.3](https://github.com/italia/ansc/releases/tag/v1.23.3)

Cordiali Saluti.
Supporto ANSC
