### ISSUE TITLE
Errore ore/minuti evento morte

### ISSUE THREAD

**Issue by antonioluberto** [italia/ansc#645]
Nei giorni scorsi il Comune di Grottaferrata ha apposto annotazione di rettifica su un atto di morte: era necessario correggere il dato relativo allo "stato civile" (da "Coniugato" a "Vedovo").
A causa di errore applicativo, con l'annotazione medesima è stata sovrascritta l'informazione relativa ad ore/minuti del decesso con il valore
00:00.

Com'è possibile correggere ora il dato in questione?

**Comment by gbuemi** [comment]
Salve @antonioluberto,
potete comunicarci per favore i riferimenti dell'atto di morte?

Grazie e saluti,
Supporto ANSC

**Comment by antonioluberto** [comment]
Buonasera.
L'atto ha id 2024-2805-66-058046.

Si rimane in attesa di vostra indicazione

**Comment by gbuemi** [comment]
Buongiorno @antonioluberto,
vi faremo sapere al più presto come procedere.

Un saluto
Supporto ANSC

**Comment by asqueglia** [comment]
Buongiorno @antonioluberto come concordati in call questa mattina, attendiamo una vostra autorizzazione a procedere da centro per la disassociazione dall'evento indicato, della annotazione per errore materiale non corretta che avete registrato non chè l'autorizzazione a renderla 'inefficace'. L'indirizzo a cui inviare la richiesta è assistenza.ansc@sogei.it

**Comment by asqueglia** [comment]
Chiudiamo la issue e restiamo in attesa della autorizzazione a procedere da centro come concordato, se ancora non inviata.
