### ISSUE TITLE
Anomalie cessazione effetti civili matrimonio (Sep_Div_005)

### ISSUE THREAD

**Issue by antonioluberto** [italia/ansc#647]
Presso il Comune di Grottaferrata è stato creato in data odierna l'atto
2024-3547-103-058046
("idOperazione":"34089")
per la cessazione degli atti civili del matrimonio a seguito di convenzione di negoziazione assistita da avvocati.
Si riscontrano le anomalie di seguito rappresentate:
a) in anteprima, il nome della sposa è erroneamente valorizzato con il nome dello sposo

![image](https://github.com/italia/ansc/assets/26415430/1315ae2a-dc2c-4226-8967-4bb42cb630fc)

b) nella notifica relativa all' annotazione da apporre sull'atto di nascita di sposo/a, il testo riporta la valorizzazione errata della data **dd/mm/yyyy**

Con convenzione di negoziazione assistita dagli avvocati XXXX YYYY e ZZZZZ TTTT conclusa in data **dd/mm/yyyy** trascritta nei registri di matrimonio di questo ufficio dello stato civile, al n. 2024-3547-103-058046, è stato concluso l'accordo di scioglimento (o di cessazione degli effetti civili) del matrimonio controscritto.

Vi si trova attualmente la data in cui  è stato emesso il "Nulla osta del Procuratore della Repubblica" anziché la data in cui effettivamente si è conclusa la negoziazione fra le parti (22/06/2023 nel caso in esame).

In più, nel testo dell'annotazione medesima compare l'indicazione generica
_... di scioglimento (o di cessazione degli effetti civili) del matrimonio..._
che sarebbe opportuno sostituire con l'indicazione esatta del tipo di procedimento in esame.

c) nella notifica relativa all' annotazione da apporre sull'atto di matrimonio originario, il testo riporta la valorizzazione errata della data **dd/mm/yyyy** 

Con convenzione di negoziazione assistita dagli avvocati XXXX YYYY e ZZZZZ TTTT conclusa in data **dd/mm/yyyy** trascritta nei registri di matrimonio di questo ufficio dello stato civile, al n. 2024-3547-103-058046, è stato concluso l'accordo di scioglimento (o di cessazione degli effetti civili) del matrimonio controscritto.

Vi si trova attualmente la data in cui  è stato emesso il "Nulla osta del Procuratore della Repubblica" anziché la data in cui effettivamente si è conclusa la negoziazione fra le parti (22/06/2023 nel caso in esame).

**Comment by gbuemi** [comment]
Buongiorno,
abbiamo preso in carico la issue.

Un saluto
Supporto ANSC

**Comment by amusarra** [comment]
Chiusa per [release 1.23.3](https://github.com/italia/ansc/releases/tag/v1.23.3)

Cordiali Saluti.
Supporto ANSC
