### ISSUE TITLE
Ancora su anomalie cessazione effetti civili matrimonio (Sep_Div_005)

### ISSUE THREAD

**Issue by antonioluberto** [italia/ansc#649]
Quanto segnalato in https://github.com/italia/ansc/issues/647, si ripropone in termini analoghi in relazione all'atto 
2024-3563-104-058046
("idOperazione":"34222")
per la separazione a seguito di convenzione di negoziazione assistita da avvocati .
Qui, in aggiunta, a valle della conclusione dell'iter di redazione atto, si hanno anche le notifiche relative ad annotazioni da apporre su atto di nascita di sposo/a che per, nel caso di separazione appunto, non sono previste da normativa.

**Comment by gbuemi** [comment]
Buongiorno,
abbiamo preso in carico la issue.

Un saluto,
Supporto ANSC

**Comment by amusarra** [comment]
Chiusa per [release 1.23.3](https://github.com/italia/ansc/releases/tag/v1.23.3)

Cordiali Saluti.
Supporto ANSC
