### ISSUE TITLE
[Mapping di tutti gli usecase] Possibilità di inserire la data decorrenza in tutti gli atti

### ISSUE THREAD

**Issue by corradosacco** [italia/ansc#651]
Buongiorno, nei mapping ritrovo l'indicazione della data decorrenza e dei dati relativi (motivo del recupero, ... ) solo negli usecase di servizio.
Confermate che in realtà questi dati (dataDecorrenza, oraDecorrenza, minutoDecorrenza, motivoRecupero, descrizioneMotivoRecupero) possono essere inseriti in qualsiasi usecase quando se ne presenta la necessità?

Grazie
Cordiali saluti,
 Corrado Sacco

**Comment by gbuemi** [comment]
Buongiorno,
vi invitiamo ad inviare solo i dati previsti nella documentazione dei mapping casi d'uso, se non presenti non vengono presi in considerazione.

Grazie a voi e saluti,
Supporto ANSC.
