### ISSUE TITLE
[Nascite] Comunicazione di atti di nascita di gemelli

### ISSUE THREAD

**Issue by corradosacco** [italia/ansc#652]
Buongiorno, nella webapp trovo il servizio di prenotazione degli ID nazionali per la gestione dei parti gemellari che crea le corrispondenti bozze con u.c. 11999999. Mi confermate che è comunque possibile utilizzare differenti usecase anche relativi allo stesso parto? 
Inoltre nel testo generato e nel payload di esempio non trovo nel testo e nel payload quanto atteso.

Nel testo mi sarei aspetatto: ...`Il bambino medesimo è gemello con altro al quale si riferisce il seguente atto numero 2024-1234-5678-015016 ed è il primo nato, come mi ha attestato il dichiarante.`

Nel payload mi sarei aspetatto qualcosa del tipo:
```
		"datiDiNascita": {
			...
			"numeroGemelli": "2",
			"partoGemellare": "SI",
			"progressivoGemello": "1",
			"attiGemelliPrec": "",
			"attiGemelliSucc": [
				{
					"??????????": "2024-1234-5678-015016"
				}
			],
			...
		},
```

In paricolare mi restano dubbi sugli attributi attiGemelliPrec e attiGemelliSucc.

Grazie
Cordiali saluti,
Corrado Sacco

**Comment by gbuemi** [comment]
Buonasera @corradosacco,
vi comunichiamo che non è possibile utilizzare differenti usecases relativi allo stesso parto. 

Per quel che riguarda il testo e al significato degli attributi attiGemelliPrec e attiGemelliSucc seguiranno indicazioni.

Un saluto,
Supporto ANSC

**Comment by asqueglia** [comment]
Buongiorno, ci scusiamo per il ritardo nella risposta. 
In merito alla domanda posta preghiamo di far riferimento alla issue #571 in cui è spiegato come funziona il servizio di prenotazione e quanto condiviso con ANSUCA in merito ai casi particolari.

Chiudiamo pertanto la issue. In caso di ulteriori problematiche preghiamo di aprire una issue dedicata utilizzando il template specifico per le domande.

Precisiamo che nel caso dei parti plurigemellari, da web app, in cui viene usato il caso d'uso di servizio, la minuta dell'atto è composta dall'USC in maniera manuale con le formule opportune previste da formulario sotto sua responsabilità; da servizi cooperativi la minuta viene inviata al sistema da vostro gestionale; per cui la minuta non è mai composta in automatico dal sistema.
