### ISSUE TITLE
Dominio delle nazioni - Nazionalità

### ISSUE THREAD

**Issue by corradosacco** [italia/ansc#653]
Buongiorno, il dominio delle nazioni che utilizziamo è quello di ANPR che presenta solo il sostantivo del paese (Francia, Spagna, ...) e non la nazionalità (francese, spagnola/spagnolo, ...) ; c'è un dominio anche per la nazionalità?

Grazie
Cordiali saluti,
Corrado Sacco

**Comment by gbuemi** [comment]
Buongiorno,
per le nazionalità non è presente un dominio. Confermiamo che per le nazioni è corretto utilizzare quello di ANPR.

Un saluto,
Supporto ANSC
