### ISSUE TITLE
[modelEvento] Nuovi campi dell'operatore firmatario e ruolo

### ISSUE THREAD

**Issue by corradosacco** [italia/ansc#654]
Buongiorno, con la relese 1.23 sono stati aggiunti nel model evento i campi dell'operatore firmatario (operatoreFirmatario, operatoreFirmatarioNome, operatoreFirmatarioCognome) che integrano quelli già presenti relativi all'operatore che redige l'atto (operatore, ruoloOperatore, operatoreNome, operatoreCognome). 
Se l'operatore che compare nell'atto dovesse essere registrato nei nuovi campi allora avrei necessità di registrate anche l'attributo del **ruolo** in quanto influenza il testo dell'atto stesso:
`io sottoscritto CORRADO SACCO Ufficiale dello stato civile del Comune di MILANO (MI), nella funzione di delegato del sindaco,`

Confermate che nei vecchi campi (operatore, ruoloOperatore, operatoreNome, operatoreCognome) devo registrate l'operatore che ha compilato operativamente l'atto che a priori può essere distinto da quello menzionato nell'atto e che lo firma? 

Grazie
Cordiali saluti,
Corrado Sacco

**Comment by gbuemi** [comment]
Buonasera,
confermiamo che, come indicato nella release 1.23.0 (https://github.com/italia/ansc/releases/tag/v1.23.0) i campi operatoreFirmatario, operatoreFirmatarioNome, operatoreFirmatarioCognome fanno riferimento all'operatore che firma l'atto. E può essere diverso dall'operatore che lo forma.

Un saluto,
Supporto ANSC
