### ISSUE TITLE
[usecase 2211 Morte_005] Stranamente non richiede allegati

### ISSUE THREAD

**Issue by corradosacco** [italia/ansc#655]
Buongiorno, il mapping dello usecase 2211 motore Morte_005 (Decesso durante il viaggio in treno o aereo o nave) non prevede allegati mentre, trattandosi di una trascrizione, mi aspettavo di averne di obbligatori.

Grazie
Cordiali saluti,
Corrado Sacco

**Comment by gbuemi** [comment]
Buonasera,
la segnalazione è stata presa in carico, seguiranno aggiornamenti.

Un saluto,
Supporto ANSC

**Comment by gbuemi** [comment]
Buongiorno,
abbiamo approfondito la questione con gli esperti anusca e sono in corso ulteriori verifiche.
Seguiranno aggiornamenti.

Un saluto,
Supporto ANSC
