### ISSUE TITLE
Data annotazioni

### ISSUE THREAD

**Issue by rvinzani** [italia/ansc#656]
Lissone

Negli estratti per copia integrale degli atti, per tutte le annotazioni dovrebbe risultare la data di inserimento perché è solo da quella data che l’evento al quale si riferisce l’annotazione è opponibile a terzi.
Negli estratti per sunto tale data può essere omessa

**Comment by asqueglia** [comment]
Con la versione 1.23.6 è stata corretta la segnalzione. Chiudiamo pertanto la issue; in caso di ulteriori malfunzionamento la preghiamo di aprire una issue dedicata.
