### ISSUE TITLE
[R003] Comunicazioni: Manca la decodifica del Tipo di Comunicazione.

### ISSUE THREAD

**Issue by gcuci** [italia/ansc#66]
Buongiorno,

il servizio di acquisizione delle Comunicazioni (per altre Amministrazioni) per un evento, prevede nella Response, l'id del Tipo di Comunicazione.
Nella documentazione (swagger), è indicata la codifica ANSC_26, ma questa non è presente nelle tabelle di decodifica sinora rilasciate.

E' ancora in lavorazione?

In attesa di un riscontro,

cordiali saluti.

**Comment by asqueglia** [comment]
Buongiorno, ieri è stata rilasciata la versione 1.6.2 che risolve quanto segnalato.
