### ISSUE TITLE
Caso d'Uso 331000- Trascrizione di matrimonio su richiesta dell'Interessato

### ISSUE THREAD

**Issue by KibMcris** [italia/ansc#660]
Nel validare il caso d'uso in oggetto viene restituito l'errore seguente:

 Il campo evento.intestatari[1].idStatoNascita nella sezione Generalità Sposa è obbligatorio
(E) 400003: Il campo evento.intestatari[1].nomeStatoNascita nella sezione Generalità Sposa è obbligatorio

In realtà controllando la documentazione la valorizzazione di queste due variabili non risulterebbe obbligatoria.
Facciamo presente inoltre che queste informazioni per il coniuge potrebbero non essere indicate nell'atto da trascrivere.

L'idOperazione dell'atto è la seguente: 35323
Restiamo in attesa di riscontro

**Comment by gbuemi** [comment]
Buonasera @KibMcris,
condividiamo il link alla documentazione del caso d'uso in oggetto in cui i due campi in questione risultano obbligatori https://github.com/italia/ansc/blob/main/docs/Mapping_casi_uso/trascrizioni/Trascr_Matr_001.csv

Verifichiamo però se sono da rendere opzionali.

Grazie e saluti,
Assistenza ANSC
