### ISSUE TITLE
caso d'uso 366999-  Caso d'uso di servizio (comunicazione da altri comuni)

### ISSUE THREAD

**Issue by KibMcris** [italia/ansc#661]
Con OperazioneComune= 12 stiamo tentando di registrare l'annotazione di avvenuta trascrizione di un matrimonio da parte di un comune non presente in ANSC.
Andando a validare l'evento, ANSC risponde con il seguente errore:

HTTP Status 500 
{"testataRisposta":{"idComune":10288,"idOperazioneComune":"12","idOperazione":"35386","idEsito":1},"errors":[{"code":"500","severity":"E","text":"Errore interno"}],"infos":[{"code":"110527","severity":"I","text":"Informazioni sull'operazione da fornire in caso di assistenza : data:2024-02-01 08:47:06 , idOperazione:35386"}]}.

Per altre tipologie di atti e di casi d'uso non abbiamo riscontrato problemi (esempio annotazioni su atti di morte)

Restiamo in attesa di riscontro

**Comment by gbuemi** [comment]
Buonasera,
l'errore è dovuto all'invio da parte del client di un carattere non numerico all'interno del campo intestatari[1].id = "2310956\n"
Vi invitiamo a ripetere il test inserendo solo i caratteri numerici nel campo indicato

Contiamo di gestire questa casistica indicando al client il motivo dell'errore.

Un saluto e grazie,
Supporto ANSC

**Comment by KibMcris** [comment]
Buongiorno @gbuemi , 
grazie per il supporto e l'indicazione. Confermo che stamani siamo riusciti a registrare l'annotazione. 
Ricevere informazioni più specifiche nell'errore sarebbe davvero utile.
Saluti
