### ISSUE TITLE
Informazioni sul Luogo di Nascita

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#662]
Buongiorno,
nella webapp, ad esempio facendo la dichiarazione di acquisto cittadinanza, nella tabella degli stati non ho trovato la Jugoslavia. 
Stato che non esiste più ma è fondamentale per indicare il luogo di nascita.

Il mio caso: persona nata nel 1990 a Sarajevo. La Bosnia-Erzegovina non era ancora uno stato a sé stante bensì, insieme ad altri, riunito nello stato della Jugoslavia.
Non trovo corretto indicare che sia nato in Bosnia-Erzegovina: primo perché non è vero e poi la persona, con molta probabilità  e con giusta ragione, si potrebbe rifiuterebbe di firmare un atto che riporta uno stato errato.

Ovviamente questo quesito lo pongo a prescindere dal registro e casistica.

Grazie

**Comment by gbuemi** [comment]
Buonasera @annamaraspin,
da webapp, per gestire  questa casistica, è possibile selezionare "ALTRO STATO" da menu a tendina **Stato Nascita*:** e inserire manualmente "JUGOSLAVIA" all'interno del campo **Altro stato di nascita *:**
Questo vale a prescindere dal registro e casistica.

Un saluto,
Supporto ANSC
