### ISSUE TITLE
Trascr_Morte_999 - controllo obbligatorietà coniuge, non chiaro.

### ISSUE THREAD

**Issue by gcuci** [italia/ansc#664]
buongiorno,

per il caso d'uso di servizio, Trascr_Morte_999, c'è un comportamento discordante, tra i controlli di obbligatorietà del servizio di Validazione (R009), e quelli del servizio di Rettifica (R013).

Per il servizio di validazione, non viene richiesto come obbligatorio il nome del coniuge, in nessun caso (anche se nel relativo file di mapping è indicato come obbligatorio nel caso in cui il deceduto fosse coniugato, vedovo, o unito civilmente, e che abbiamo interpretato come possibile refuso), mentre per il servizio di rettifica, il campo viene richiesto come obbligatorio come indicato nel file di mapping.

Per un esempio, potete verificare, una validazione che è andata a buon fine (idOperazione = 1742932), con lo stato civile del deceduto a 'Coniugato' senza il passaggio di alcun dato del coniuge, mentre una successiva rettifica sullo stesso evento (idOperazione = 1743140), che passa come eventoModificato le stesse informazioni senza dati del coniuge, restituisce un errore di dato obbligatorio mancante, sul nome del coniuge. Le operazioni sono state effettuate in ambiente di pre-produzione.

Potete indicarci quali sono le corrette obbligatorietà da considerare?

In attesa di riscontro,

cordiali saluti.

**Comment by amusarra** [comment]
Salve @gcuci 
Abbiamo preso in carico la sua segnalazione per la fase di verifica.

Cordiali Saluti.
Supporto ANSC.

**Comment by amusarra** [comment]
Salve @gcuci 
Analizzando i payload abbiamo notato l'uso dell'idVersion 100006. Utilizzando l'idVersion 100008 non dovreste avere il problema.

Cordiali Saluti.
Supporto ANSC.

**Comment by asqueglia** [comment]
Buon pomeriggio chiudiamo pertanto la issue; in caso di ulteriori segnalazioni si prega di aprirne una dedicata.
