### ISSUE TITLE
[R009] TIMEOUT Servizio di validazione. URGENTE!!!

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#666]
Buongiorno, 
ci hanno segnalato da Lissone che il servizio di validazione va in TIMEOUT. Hanno provato più volte anche con atti diversi.

**Comment by amusarra** [comment]
Salve @biadanpad 
Abbiamo preso in carico la segnalazione e stiamo facendo le opportune verifiche.
Al momento non rileviamo problemi; potreste chiedere di riprovare?

Cordiali Saluti.
Supporto ANSC.

**Comment by amusarra** [comment]
Salve @biadanpad 
Non rileviamo problemi di timeout, pertanto chiudiamo la issue.
Nel caso sia necessario la invitiamo a riaprire la stessa.

Cordiali Saluti.
Supporto ANSC.

**Comment by MarcoSalaPad** [comment]
Salve, in realtà stavamo aspettando che il comune ci desse conferma dopo aver riprovato una validazione.
Questa mattina non è stato possibile perchè il comune stesso era in contatto con voi per la risoluzione di un'altra problematica rilevata sulla gestione di un atto gestito tramite web app.
Comunque, non appena abbiamo feedback dal cliente, provvederemo nel caso a riaprire la issues.
