### ISSUE TITLE
Rilasci Ufficiali?

### ISSUE THREAD

**Issue by gcuci** [italia/ansc#667]
buongiorno,

sono da considerarsi ufficiali le versioni 1.23.2 e 1.23.3?

Le vediamo nella home del Progetto, ma non ci sono le consuete issue di rilascio.

In attesa di riscontro,

cordiali saluti.

**Comment by mttfranci** [comment]
@gcuci  si i rilasci sono ufficiali.
Come scritto anche da @Ennio71, abbiamo iniziato ad usare le release al posto delle issue di avviso : 
https://github.com/italia/ansc/releases

Saluti 

Assistenza ANSC
