### ISSUE TITLE
Servizio  CONSULTAZIONE_ANSC_INTESTATARIO errore

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#669]
ambiente test
idOperazione":"1748396

Mi viene restituito questo errore
400001 - Per la ricerca con anagrafica: Id Comune Nascita �andatory400001 - Per la ricerca con anagrafica: Nome Comune Nascita �andatory400001 - Per la ricerca con anagrafica: Sigla Provincia Nascita �andatory400001 - Per la ricerca con anagrafica: Codice Stato Nascita �andatory400001 - Per la ricerca con anagrafica: Nome Stato Nascita �andatory

Non riesco a capire se ho introdotto qualche dato errato sulla persona.

Grazie

**Comment by MarcoSalaPad** [comment]
Buongiorno, 

segnaliamo anche noi lo stesso problema per i soggetti che sono nati all'estero. Se un soggetto è nato in italia non si verificano problemi di validazione.

Di seguito la REQUEST:

{
  "criteriRicercaSoggetto": {
    "cognome": "BABAEIAN GHAMSARI",
    "nome": "ATENA",
    "sesso": "F",
    "codiceStatoNascita": "82",
    "nomeStatoNascita": "IRAN",
    "datanascita": "1985-03-08"
  },
  "testataRichiesta": {
    "idComune": 5000,
    "idOperazioneComune": "2304",
    "dataOraRichiesta": "2024-02-06T10:38:26.899+01:00",
    "nomeApplicativo": "urbi",
    "versioneApplicativo": "1.1.2",
    "fornitoreApplicativo": "padigitale"
  }
}

RESPONSE:

{
  "testataRisposta": {
    "idComune": 5000,
    "idOperazioneComune": "2304",
    "idOperazione": "37187",
    "idEsito": 1
  },
  "datiPaginazione": {
    "numPagina": 1,
    "numRecordPagina": 30,
    "numRecordTotali": 0
  },
  "errors": [
    {
      "code": "400001",
      "severity": "E",
      "text": "Per la ricerca con anagrafica: Id Comune Nascita è mandatory"
    },
    {
      "code": "400001",
      "severity": "E",
      "text": "Per la ricerca con anagrafica: Nome Comune Nascita è mandatory"
    },
    {
      "code": "400001",
      "severity": "E",
      "text": "Per la ricerca con anagrafica: Sigla Provincia Nascita è mandatory"
    }
  ],
  "infos": [
    {
      "code": "110527",
      "severity": "I",
      "text": "Informazioni sull'operazione da fornire in caso di assistenza : data:2024-02-06 09:38:29 , idOperazione:37187"
    }
  ]
}


Abbiamo verificato su un atto di qualche giorno fa di un soggetto nato all'estero (atto in data 30 gennaio) e non abbiamo avuto errori.

REQUEST:

{
  "criteriRicercaSoggetto": {
    "cognome": "NICKL",
    "nome": "ANDREAS ALBERT",
    "sesso": "M",
    "codiceStatoNascita": "65",
    "nomeStatoNascita": "GERMANIA",
    "datanascita": "1970-10-21"
  },
  "testataRichiesta": {
    "idComune": 5000,
    "idOperazioneComune": "2295",
    "dataOraRichiesta": "2024-01-30T10:19:11.013+01:00",
    "nomeApplicativo": "urbi",
    "versioneApplicativo": "1.1.2",
    "fornitoreApplicativo": "padigitale"
  }
}

Precisiamo anche che questa mattina è stato fatto anche un altro atto simile a quello andato in errore, dove però l'intestatario era nato in italia, e quindi non ci sono stati errori sulla validazione e l'atto è stato terminato con successo.

E' urgente perchè il comune deve fare degli atti che al momento ha rimandato a domani.

Marco Sala

**Comment by amusarra** [comment]
> ambiente test idOperazione":"1748396
> 
> Mi viene restituito questo errore 400001 - Per la ricerca con anagrafica: Id Comune Nascita �andatory400001 - Per la ricerca con anagrafica: Nome Comune Nascita �andatory400001 - Per la ricerca con anagrafica: Sigla Provincia Nascita �andatory400001 - Per la ricerca con anagrafica: Codice Stato Nascita �andatory400001 - Per la ricerca con anagrafica: Nome Stato Nascita �andatory
> 
> Non riesco a capire se ho introdotto qualche dato errato sulla persona.
> 
> Grazie

Salve @annamaraspin 
Il soggetto non è presente sul sistema ANSC, quindi tenta la ricerca la ricerca su ANPR per cui sono richiesti i dati richiesta dalla risposta.

Cordiali Saluti.
Supporto ANSC.

**Comment by amusarra** [comment]
> Buongiorno,
> 
> segnaliamo anche noi lo stesso problema per i soggetti che sono nati all'estero. Se un soggetto è nato in italia non si verificano problemi di validazione.
> 
> Di seguito la REQUEST:
> 
> { "criteriRicercaSoggetto": { "cognome": "BABAEIAN GHAMSARI", "nome": "ATENA", "sesso": "F", "codiceStatoNascita": "82", "nomeStatoNascita": "IRAN", "datanascita": "1985-03-08" }, "testataRichiesta": { "idComune": 5000, "idOperazioneComune": "2304", "dataOraRichiesta": "2024-02-06T10:38:26.899+01:00", "nomeApplicativo": "urbi", "versioneApplicativo": "1.1.2", "fornitoreApplicativo": "padigitale" } }
> 
> RESPONSE:
> 
> { "testataRisposta": { "idComune": 5000, "idOperazioneComune": "2304", "idOperazione": "37187", "idEsito": 1 }, "datiPaginazione": { "numPagina": 1, "numRecordPagina": 30, "numRecordTotali": 0 }, "errors": [ { "code": "400001", "severity": "E", "text": "Per la ricerca con anagrafica: Id Comune Nascita è mandatory" }, { "code": "400001", "severity": "E", "text": "Per la ricerca con anagrafica: Nome Comune Nascita è mandatory" }, { "code": "400001", "severity": "E", "text": "Per la ricerca con anagrafica: Sigla Provincia Nascita è mandatory" } ], "infos": [ { "code": "110527", "severity": "I", "text": "Informazioni sull'operazione da fornire in caso di assistenza : data:2024-02-06 09:38:29 , idOperazione:37187" } ] }
> 
> Abbiamo verificato su un atto di qualche giorno fa di un soggetto nato all'estero (atto in data 30 gennaio) e non abbiamo avuto errori.
> 
> REQUEST:
> 
> { "criteriRicercaSoggetto": { "cognome": "NICKL", "nome": "ANDREAS ALBERT", "sesso": "M", "codiceStatoNascita": "65", "nomeStatoNascita": "GERMANIA", "datanascita": "1970-10-21" }, "testataRichiesta": { "idComune": 5000, "idOperazioneComune": "2295", "dataOraRichiesta": "2024-01-30T10:19:11.013+01:00", "nomeApplicativo": "urbi", "versioneApplicativo": "1.1.2", "fornitoreApplicativo": "padigitale" } }
> 
> Precisiamo anche che questa mattina è stato fatto anche un altro atto simile a quello andato in errore, dove però l'intestatario era nato in italia, e quindi non ci sono stati errori sulla validazione e l'atto è stato terminato con successo.
> 
> E' urgente perchè il comune deve fare degli atti che al momento ha rimandato a domani.
> 
> Marco Sala

Salve @MarcoSalaPad.
Il motivo dell'errore è che il soggetto non è presente su ANSC e per ricercalo sul sistema ANPR sono necessari i campi richiesti. Nel vostro caso, il problema non è bloccante, basta semplicemente inserirlo come nuovo il soggetto.

Nel frattempo, valuteremo come gestire le ricerche su ANPR nel caso si soggetto estero.

Cordiali Saluti.
Supporto ANSC.

**Comment by annamaraspin** [comment]
@amusarra grazie.
ma avete cambiato qualcosa stamattina? Perché fino alle 9:30 circa ho fatto casistiche simili (atti di nascita con bambini appena nati quindi ancora non registrati in ANPR) e sono andati a buon fine.

**Comment by amusarra** [comment]
> @amusarra grazie. ma avete cambiato qualcosa stamattina? Perché fino alle 9:30 circa ho fatto casistiche simili (atti di nascita con bambini appena nati quindi ancora non registrati in ANPR) e sono andati a buon fine.

Non mi risulta. È una gestione inserita nel rilascio della release [1.23.3](https://github.com/italia/ansc/releases/tag/v1.23.3)

Cordiali Saluti.
Supporto ANSC.

**Comment by biadanpad** [comment]
Buonasera @amusarra,
non siamo affatto d'accordo con la sua risposta:

se il soggetto non è presente in ANSC la risposta giusta da dare (e che ricevevamo prima della release 1.23.3) è la seguente:
{
  "testataRisposta": {
    "idComune": 5000,
    "idOperazioneComune": "2295",
    "idOperazione": "34563",
    "idEsito": 0
  },
  "datiPaginazione": {
    "numPagina": 1,
    "numRecordPagina": 30,
    "numRecordTotali": 0
  },
  "infos": [
    {
      "code": "110527",
      "severity": "I",
      "text": "Informazioni sull'operazione da fornire in caso di assistenza : data:2024-01-30 09:19:13 , idOperazione:34563"
    }
  ],
  "soggetti": []
}

con la release 1.23.3, invece, il servizio risponde il seguente errore:
{
      "code": "400001",
      "severity": "E",
      "text": "Per la ricerca con anagrafica: Nome Comune Nascita è mandatory"
    },
    {
      "code": "400001",
      "severity": "E",
      "text": "Per la ricerca con anagrafica: Sigla Provincia Nascita è mandatory"
    }
  ],
  "infos": [
    {
      "code": "110527",
      "severity": "I",
      "text": "Informazioni sull'operazione da fornire in caso di assistenza : data:2024-02-06 12:11:20 , idOperazione:37319"
    }
  ]
}

In questo caso ci vengono richiesti come obbligatori dati che, per soggetti stranieri, ci avete espressamente detto (in altre issue) che non devono essere utilizzati.

**Comment by MarcoSalaPad** [comment]
Buongiorno,
ci sono novità in merito? Dobbiamo dire al nostro comune come operare sull'atto che dovranno fare nel pomeriggio.

**Comment by amusarra** [comment]
> Buongiorno,
> 
> segnaliamo anche noi lo stesso problema per i soggetti che sono nati all'estero. Se un soggetto è nato in italia non si verificano problemi di validazione.
> 
> Di seguito la REQUEST:
> 
> { "criteriRicercaSoggetto": { "cognome": "BABAEIAN GHAMSARI", "nome": "ATENA", "sesso": "F", "codiceStatoNascita": "82", "nomeStatoNascita": "IRAN", "datanascita": "1985-03-08" }, "testataRichiesta": { "idComune": 5000, "idOperazioneComune": "2304", "dataOraRichiesta": "2024-02-06T10:38:26.899+01:00", "nomeApplicativo": "urbi", "versioneApplicativo": "1.1.2", "fornitoreApplicativo": "padigitale" } }
> 
> RESPONSE:
> 
> { "testataRisposta": { "idComune": 5000, "idOperazioneComune": "2304", "idOperazione": "37187", "idEsito": 1 }, "datiPaginazione": { "numPagina": 1, "numRecordPagina": 30, "numRecordTotali": 0 }, "errors": [ { "code": "400001", "severity": "E", "text": "Per la ricerca con anagrafica: Id Comune Nascita è mandatory" }, { "code": "400001", "severity": "E", "text": "Per la ricerca con anagrafica: Nome Comune Nascita è mandatory" }, { "code": "400001", "severity": "E", "text": "Per la ricerca con anagrafica: Sigla Provincia Nascita è mandatory" } ], "infos": [ { "code": "110527", "severity": "I", "text": "Informazioni sull'operazione da fornire in caso di assistenza : data:2024-02-06 09:38:29 , idOperazione:37187" } ] }
> 
> Abbiamo verificato su un atto di qualche giorno fa di un soggetto nato all'estero (atto in data 30 gennaio) e non abbiamo avuto errori.
> 
> REQUEST:
> 
> { "criteriRicercaSoggetto": { "cognome": "NICKL", "nome": "ANDREAS ALBERT", "sesso": "M", "codiceStatoNascita": "65", "nomeStatoNascita": "GERMANIA", "datanascita": "1970-10-21" }, "testataRichiesta": { "idComune": 5000, "idOperazioneComune": "2295", "dataOraRichiesta": "2024-01-30T10:19:11.013+01:00", "nomeApplicativo": "urbi", "versioneApplicativo": "1.1.2", "fornitoreApplicativo": "padigitale" } }
> 
> Precisiamo anche che questa mattina è stato fatto anche un altro atto simile a quello andato in errore, dove però l'intestatario era nato in italia, e quindi non ci sono stati errori sulla validazione e l'atto è stato terminato con successo.
> 
> E' urgente perchè il comune deve fare degli atti che al momento ha rimandato a domani.
> 
> Marco Sala

Per i soggetti esteri abbiamo preso in carico la segnalazione e provvederemo a fare la fix su questa specificità.

Cordiali Saluti.
Supporto ANSC.

**Comment by amusarra** [comment]
> Buongiorno, ci sono novità in merito? Dobbiamo dire al nostro comune come operare sull'atto che dovranno fare nel pomeriggio.

Avevamo risposto. In fase di validazione dell'evento il soggetto sarà inserito in ANSC.

Cordiali Saluti.
Supporto ANSC.

**Comment by MarcoSalaPad** [comment]
Quando è prevista la fix?

**Comment by biadanpad** [comment]
> > Buongiorno, ci sono novità in merito? Dobbiamo dire al nostro comune come operare sull'atto che dovranno fare nel pomeriggio.
> 
> Avevamo risposto. In fase di validazione dell'evento il soggetto sarà inserito in ANSC.
> 
> Cordiali Saluti. Supporto ANSC.

il problema sta nel fatto che prima di richiamare il servizio di validazione dobbiamo sapere se quel soggetto esiste in ANSC oppure no.
Per fare questo richiamiamo il servizio in oggetto che però ritorna l'errore descritto. Questo non ci permette di proseguire con la validazione.

**Comment by amusarra** [comment]
> Buongiorno, ci sono novità in merito? Dobbiamo dire al nostro comune come operare sull'atto che dovranno fare nel pomeriggio.

Salve @biadanpad 
Potreste riprovare con le richieste dei soggetti esteri?

Cordiali Saluti.
Supporto ANSC.

**Comment by biadanpad** [comment]
Ci hanno riferito da Lissone che per soggetti nati all'estero il sistema è tornato a funzionare
