### ISSUE TITLE
Allegati firmati digitalmente

### ISSUE THREAD

**Issue by migmar68** [italia/ansc#67]
Buongiorno
Non ho ancora avuto modo di fare prove, ma da quello che ho visto, immagino che vengano accettate dal sistema firme  PDF di tipo PADES, ma che non vengano gestite firme tipo P7M.
Chiedo conferma se questa è la situazione attuale, e se pensate di intervenire in futuro o meno.

**Comment by amusarra** [comment]
Buongiorno @migmar68 
Gli allegati agli eventi supportati sono PDF, JPG e TIFF.
Abbiamo preso in valutazione la richiesta.
Chiudo la issue.

Saluti.
Supporto ANSC
