### ISSUE TITLE
346000	Trascrizione delle sentenze di deliberazione, da parte della Corte d’Appello, delle sentenze di nullità del matrimonio pronunciate dai Tribunali Ecclesiastici	(Sep_Div_006)

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#670]
ambiente test
idoperazione 1748599

buonasera,
nella casistica in oggetto mi viene restituito questo errore

400003 - Il campo evento.trascrizioneSeparazione.atto.enteEstero.siglaProvinciaEnte nella sezione Autorit�ittente non corrisponde al pattern ^[0-9]*$

Credo un bug visto che la sigla dovrebbero essere lettere e non numeri.
grazie

**Comment by amusarra** [comment]
Salve @annamaraspin 
Abbiamo preso in carico la sua segnalazione.
Dal payload non risulta essere presente `evento.trascrizioneSeparazione.atto.enteEstero.siglaProvinciaEnte` e in questo caso è corretto perché si tratta di nazione estera.

Cordiali Saluti.
Supporto ANSC.

**Comment by asqueglia** [comment]
Con la versione 1.24.0 appena rilasciata la segnalazione è stata corretta. Chiudiamo pertanto la issue; in caso di ulteriori problematiche si prega di aprire una issue dedicata. Si rimanda alla documentazione per analizzare il contenuto della release rilasciata.
