### ISSUE TITLE
Dati RicercaSoggettoR005

### ISSUE THREAD

**Issue by Sem98** [italia/ansc#671]
Buongiorno da stamattina quando viene chiamata la R005 per la ricercaSoggetto con questo endpoint: "https://anscservicepre.anpr.interno.it/services/service/ricerca/consultazione/ansc/intestatario/1"  il servizio risponde con:

{"testataRisposta":{"idComune":9493,"idOperazioneComune":"5636","idOperazione":"1748874","idEsito":1},"datiPaginazione":{"numPagina":1,"numRecordPagina":30,"numRecordTotali":0},"errors":[{"code":"400001","severity":"E","text":"Per la ricerca con anagrafica: Sesso è mandatory"},{"code":"400001","severity":"E","text":"Per la ricerca con anagrafica: Id Comune Nascita è mandatory"},{"code":"400001","severity":"E","text":"Per la ricerca con anagrafica: Nome Comune Nascita è mandatory"},{"code":"400001","severity":"E","text":"Per la ricerca con anagrafica: Sigla Provincia Nascita è mandatory"},{"code":"400001","severity":"E","text":"Per la ricerca con anagrafica: Codice Stato Nascita è mandatory"},{"code":"400001","severity":"E","text":"Per la ricerca con anagrafica: Nome Stato Nascita è mandatory"},{"code":"400001","severity":"E","text":"Per la ricerca con anagrafica: Data di Nascita è mandatory"}],"infos":[{"code":"110527","severity":"I","text":"Informazioni sull'operazione da fornire in caso di assistenza : data:2024-02-07 10:01:29 , idOperazione:1748874"}]}

Il payload inviato è il seguente:

{
	"testataRichiesta": {
		"versioneApplicativo": "1.0.0",
		"idOperazioneComune": "5636",
		"idComune": 9493,
		"dataOraRichiesta": "2024-02-07T10:01:28.659",
		"nomeApplicativo": "SIDe",
		"fornitoreApplicativo": "SistemiInformativi"
	},
	"criteriRicercaSoggetto": {
		"nomeStatoNascita": "",
		"cognome": "PAPINI",
		"nomeComuneNascita": "",
		"idAnpr": "",
		"codiceStatoNascita": "",
		"sesso": "",
		"nome": "EREMITA",
		"idComuneNascita": "",
		"datanascita": "",
		"codiceFiscale": "PPNRMT24B04I726W",
		"siglaProvinciaNascita": ""
	}
}

Abbiamo verificato che il soggetto è presente nella webapp ansc : https://anscwebpre.anpr.interno.it/ansc/ricerca-evento/evento/1219848  e ci chiedevamo quale potesse essere il problema.

**Comment by siscomanpr** [comment]
Buongiorno,
rileviamo un problema analogo (per ora notato in ambiente di pre-prod), tentando di ricercare un soggetto nato all'estero.

Payload:
{
    "criteriRicercaSoggetto": {
        "codiceFiscale": "",
        "cognome": "SEDICI",
        "nome": "ALBERTO",
        "sesso": "M",
        "nomeComuneNascita": "ZURIGO",
        "siglaProvinciaNascita": "",
        "codiceStatoNascita": "173",
        "nomeStatoNascita": "SVIZZERA",
        "datanascita": "1930-05-05"
    },
    "testataRichiesta": {
        "idComune": 9419,
        "idOperazioneComune": "202400000000000000000000036713",
        "dataOraRichiesta": "2024-02-07T10:35:56.2218394+01:00",
        "nomeApplicativo": "SESAMOWEB",
        "versioneApplicativo": "1.0.1.0",
        "fornitoreApplicativo": "SISCOM"
    }
}

Riceviamo i seguenti errori bloccanti:
"Per la ricerca con anagrafica: Id Comune Nascita è mandatory"
"Per la ricerca con anagrafica: Sigla Provincia Nascita è mandatory"

Ambiente: pre-produzione
idOperazione=1748839

**Comment by amusarra** [comment]
Salve.
Fate riferimento alla #669 

Cordiali Saluti.
Supporto ANSC.

**Comment by Sem98** [comment]
Salve, ho letto la issue da lei menzionata, tuttavia il soggetto di cui stiamo facendo la ricerca è gia inserito in ANSC in quanto il servizio di validazione R009 è stato già eseguito, e infatti è visibile tramite la webapp di ANSC: https://anscwebpre.anpr.interno.it/ansc/ricerca-evento/evento/1219848

**Comment by amusarra** [comment]
> Buongiorno, rileviamo un problema analogo (per ora notato in ambiente di pre-prod), tentando di ricercare un soggetto nato all'estero.
> 
> Payload: { "criteriRicercaSoggetto": { "codiceFiscale": "", "cognome": "SEDICI", "nome": "ALBERTO", "sesso": "M", "nomeComuneNascita": "ZURIGO", "siglaProvinciaNascita": "", "codiceStatoNascita": "173", "nomeStatoNascita": "SVIZZERA", "datanascita": "1930-05-05" }, "testataRichiesta": { "idComune": 9419, "idOperazioneComune": "202400000000000000000000036713", "dataOraRichiesta": "2024-02-07T10:35:56.2218394+01:00", "nomeApplicativo": "SESAMOWEB", "versioneApplicativo": "1.0.1.0", "fornitoreApplicativo": "SISCOM" } }
> 
> Riceviamo i seguenti errori bloccanti: "Per la ricerca con anagrafica: Id Comune Nascita è mandatory" "Per la ricerca con anagrafica: Sigla Provincia Nascita è mandatory"
> 
> Ambiente: pre-produzione idOperazione=1748839

Buongiorno @siscomanpr 
Il problema dei casi esteri è stato risolto con la release [1.23.4](https://github.com/italia/ansc/releases/tag/1.23.4).

Cordiali Saluti.
Supporto ANSC.

**Comment by amusarra** [comment]
> Buongiorno da stamattina quando viene chiamata la R005 per la ricercaSoggetto con questo endpoint: "https://anscservicepre.anpr.interno.it/services/service/ricerca/consultazione/ansc/intestatario/1" il servizio risponde con:
> 
> {"testataRisposta":{"idComune":9493,"idOperazioneComune":"5636","idOperazione":"1748874","idEsito":1},"datiPaginazione":{"numPagina":1,"numRecordPagina":30,"numRecordTotali":0},"errors":[{"code":"400001","severity":"E","text":"Per la ricerca con anagrafica: Sesso è mandatory"},{"code":"400001","severity":"E","text":"Per la ricerca con anagrafica: Id Comune Nascita è mandatory"},{"code":"400001","severity":"E","text":"Per la ricerca con anagrafica: Nome Comune Nascita è mandatory"},{"code":"400001","severity":"E","text":"Per la ricerca con anagrafica: Sigla Provincia Nascita è mandatory"},{"code":"400001","severity":"E","text":"Per la ricerca con anagrafica: Codice Stato Nascita è mandatory"},{"code":"400001","severity":"E","text":"Per la ricerca con anagrafica: Nome Stato Nascita è mandatory"},{"code":"400001","severity":"E","text":"Per la ricerca con anagrafica: Data di Nascita è mandatory"}],"infos":[{"code":"110527","severity":"I","text":"Informazioni sull'operazione da fornire in caso di assistenza : data:2024-02-07 10:01:29 , idOperazione:1748874"}]}
> 
> Il payload inviato è il seguente:
> 
> { "testataRichiesta": { "versioneApplicativo": "1.0.0", "idOperazioneComune": "5636", "idComune": 9493, "dataOraRichiesta": "2024-02-07T10:01:28.659", "nomeApplicativo": "SIDe", "fornitoreApplicativo": "SistemiInformativi" }, "criteriRicercaSoggetto": { "nomeStatoNascita": "", "cognome": "PAPINI", "nomeComuneNascita": "", "idAnpr": "", "codiceStatoNascita": "", "sesso": "", "nome": "EREMITA", "idComuneNascita": "", "datanascita": "", "codiceFiscale": "PPNRMT24B04I726W", "siglaProvinciaNascita": "" } }
> 
> Abbiamo verificato che il soggetto è presente nella webapp ansc : https://anscwebpre.anpr.interno.it/ansc/ricerca-evento/evento/1219848 e ci chiedevamo quale potesse essere il problema.

Buongiorno @Sem98 
Per questo caso specifico stiamo facendo i controlli necessari.

Cordiali Saluti.
Supporto ANSC.

**Comment by amusarra** [comment]
Salve @Sem98 
Potrebbe eseguire una nuova richiesta?
Il sistema ANSC adesso risponde in modo attesa per la sua richiesta.

```json
    "soggetti": [
        {
            "id": 2261277,
            "cognome": "PAPINI",
            "nome": "EREMITA",
            "sesso": "M",
            "datains": "2024-02-06T08:35:40.000+00:00",
            "dataultimoagg": "2024-02-06T09:14:22.000+00:00",
            "codiceFiscale": "PPNRMT24B04I726W",
            "idComuneNascita": 9493,
            "idStatoNascita": "90",
            "idComuneResidenza": 9493,
            "nazionalita": "ITALIANA",
            "nomeStatoNascita": "ITALIA",
            "idProvinciaNascita": 52,
            "idProvinciaResidenza": 52,
            "idNazionalita": 90,
            "idStatoResidenza": "90",
            "dataNascita": "2024-02-04T00:00:00.000+00:00"
        }
    ]
```

**Comment by Sem98** [comment]
Buongiorno abbiamo verificato che inserendo il codice fiscale nel payload per la ricerca il servizio risponde correttamente, tuttavia in caso vengano utilizzati solo nome e cognome, nonostante il soggetto sia presente su ANSC, il servizio risponde con il medesimo errore.
