### ISSUE TITLE
[ws R010] Anteprima Atti (Unione Civile / Matrimonio) - Sezione "Dati Evento": gestione della data

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/ansc#672]
ambiente PRE-PROD - comune di FAENZA (idComune 3743)

caso di trascrizione dall'estero su richiesta dell'interessato, sia per matrimonio che per unione civile
non è chiaro come vengano gestiti i metaDati nel pdf dell'atto (in particolare la data dell'evento)

caso unione civile (idAttoAnsc: 2024‐1220040‐10034‐039010 - idUseCase: 431000)
nell'estratto per copia integrale, all'interno della sezione "Dati dell'Unione Civile", la data di Unione Civile viene indicata con etichetta "Data Trasmissione"
![image](https://github.com/italia/ansc/assets/26788199/12813f9b-1882-4c4b-980d-bd5e6e7a699d)
... ma l'1/1/2024 è quella che è stata indicata come "data unione civile"
![image](https://github.com/italia/ansc/assets/26788199/288e4a46-bdee-4f09-b44b-48627b358fdb)

caso matrimonio (idAttoAnsc: 2024‐1220043‐10035‐039010 - idUseCase: 331000)
nell'estratto per copia integrale, non è proprio presente la sezione "Dati dell'evento matrimonio"

l'anomalia l'abbiamo riscontrata facendo delle prove via web-service, ma abbiamo visto che si manifesta ugualmente anche facendo gli atti su web-app (gli esempi riportati sono di atti registrati su web-app)

sarebbe necessaria qualche verifica da parte vostra.

grazie
Alessandro ADS

**Comment by asqueglia** [comment]
Buongiorno, prendiamo in carico la verifca

**Comment by asqueglia** [comment]
Con la versione 1.23.6 è stata corretta la segnalzione. Chiudiamo pertanto la issue; in caso di ulteriori malfunzionamento la preghiamo di aprire una issue dedicata.
