### ISSUE TITLE
USECASE 347000 Trascrizione provvedimenti esteri in materia matrimoniale.	Sep_Div_007

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#673]
ambiente test
idoperazione 1749560

Buongiorno,
testando la casistica in oggetto mi esce l'errore
400003 - Il campo evento.trascrizioneSeparazione.attoEstero.enteEstero.comuneEstero nella sezione Atto da trascrivere �bbligatorio

Trattandosi di un comune estero non è obbligatorio impostare solo il tag relativo allo Stato?

**Comment by amusarra** [comment]
Salve @annamaraspin 
Abbiamo preso in carico la segnalazione.

Cordiali Saluti.
Supporto ANSC.

**Comment by asqueglia** [comment]
Con la versione 1.24.0 appena rilasciata la segnalazione è stata corretta. Chiudiamo pertanto la issue; in caso di ulteriori problematiche si prega di aprire una issue dedicata. Si rimanda alla documentazione per analizzare il contenuto della release rilasciata.
