### ISSUE TITLE
[R009] Servizio di Validazione - ERRORE DI TIMEOUT

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#679]
Da circa 30 minuti il servizio in oggetto va in timeout impedendoci di proseguire lo sviluppo

**Comment by AMonopoliADS** [comment]
confermo. anche noi non riusciamo più a validare in ambiente pre-prod

**Comment by biadanpad** [comment]
Adesso il servizio risponde: 502 Bad Gateway

**Comment by mttfranci** [comment]
Buongiorno, potete cortesemente verificare se il problema persiste?

Grazie in anticipo.

Saluti

Assistenza ANSC

**Comment by biadanpad** [comment]
Adesso il servizio non è andato in timeout
