### ISSUE TITLE
[R009] Errore Validazione Annotazione per Cambio Generalità Genitore

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#680]
Buongiorno, 
provando a validare un'Annotazione per Cambio Generalità Genitore ricevo un errore non chiaro: "Nodo del caso d'uso è evento di annotazione rettifica del figlio per cambio generalita genitori".

REQUEST:
{
  "evento": {
    "idtipocontenuto": "1",
    "idUsecase": "14750000",
    "descrizioneCasoUso": "Annotazione per cambio generalitÃ  genitore",
    "stato": "CONFERMATO",
    "idVersion": "100008",
    "operatore": "DLCNTN57L67A064W",
    "operatoreNome": "MARGHERITA",
    "operatoreCognome": "CITTERIO",
    "idComuneRegistrazione": "5000",
    "nomeComuneRegistrazione": "LISSONE",
    "idProvinciaRegistrazione": "108",
    "siglaProvinciaRegistrazione": "MB",
    "intestatari": [
      {
        "cognome": "ROSSIN",
        "nome": "UGOLINO",
        "sesso": "M",
        "dataNascita": "2023-11-01",
        "idComuneNascita": "2245",
        "nomeComuneNascita": "CASTELCOVATI (BS)",
        "idProvinciaNascita": "17",
        "siglaProvinciaNascita": "BS",
        "idStatoNascita": "90",
        "nomeStatoNascita": "ITALIA",
        "idComuneResidenza": "17718",
        "nomeComuneResidenza": "AGLIE' (TO)",
        "idProvinciaResidenza": "1",
        "siglaProvinciaResidenza": "TO",
        "idStatoResidenza": "90",
        "nomeStatoResidenza": "ITALIA",
        "idNazionalita": "90",
        "nazionalita": "ITALIANA"
      }
    ],
    "composizioneCompleta": "VN VC, Padre di UGOLINO ROSSIN ha assunto il nuovo  nome e cognome NN NC",
    "datiAnnotazioneModificativa": {
      "attoIntestatario": {
        "idAnsc": "2023-1216673-3-108028",
        "idComuneRegistrazione": "5000",
        "nomeComuneRegistrazione": "LISSONE",
        "idProvinciaRegistrazione": "108",
        "siglaProvinciaRegistrazione": "MB",
        "numeroatto": "3",
        "dataformazione": "2023-12-22",
        "annoAtto": "2023",
        "tipologia": "1"
      },
      "tipoModifica": 8,
      "genitore": 2,
      "nuovoCognomeGenitore": "NC",
      "nuovoNomeGenitore": "NN",
      "vecchioCognomeGenitore": "VC",
      "vecchioNomeGenitore": "VN",
      "nuovoCognomeIntestatario": "NC"
    }
  },
  "testataRichiesta": {
    "idComune": 5000,
    "idOperazioneComune": "3548",
    "dataOraRichiesta": "2024-02-09T09:14:36.22+01:00",
    "nomeApplicativo": "urbi",
    "versioneApplicativo": "1.1.2",
    "fornitoreApplicativo": "padigitale"
  }
}

RESPONSE:
{
  "testataRisposta": {
    "idComune": 5000,
    "idOperazioneComune": "3548",
    "idOperazione": "1750357"
  },
  "errors": [
    {
      "code": "500003",
      "severity": "E",
      "text": "Nodo del caso d'uso è evento di annotazione rettifica del figlio per cambio generalita genitori"
    }
  ],
  "infos": [
    {
      "code": "110527",
      "severity": "I",
      "text": "Informazioni sull'operazione da fornire in caso di assistenza : data:2024-02-09 08:14:38 , idOperazione:1750357"
    }
  ]
}

**Comment by asqueglia** [comment]
Buongiorno prendiamo in carico la verifica

**Comment by biadanpad** [comment]
Ci siamo resi conto che il servizio chiamato non è quello corretto.
Riapriremo la issue se necessario
