### ISSUE TITLE
[R009] Caso d'uso Rico_004 (12221122): controlli su obbligatorietà dati di riconoscimento della madre

### ISSUE THREAD

**Issue by antonioluberto** [italia/ansc#682]
Il caso d'uso in questione (12221122 - Riconoscimento paterno di figlio ultraquattordicenne già riconosciuto dalla madre) prevede attualmente come obbligatoria la valorizzazione della sezione:

![image](https://github.com/italia/ansc/assets/26415430/7fbf8469-6133-47ed-a599-2be66deae4cf)

in tutti i casi in cui si indichi 
_evento.RiconoscimentoMadre.Avvenuto_ = _True_

Due le domande:
a) essendo il caso d'uso prevdisto come 
**Riconoscimento paterno di figlio ultraquattordicenne già riconosciuto dalla madre**
in quali casi _evento.RiconoscimentoMadre.Avvenuto_  dovrebbe assumere valore diverso da _True_ ?

b) la formula che la normativa prevede per la redazione di un atto di stato civile con il quale un genitore B esegua il riconoscimento di un figlio che l'altro genitore A abbia già riconosciuto in passato è la 109 che non prevede l'indicazione degli estremi dell'atto di nascita con il quale il il genitore A abbia eseguito l'iniziale riconoscimento del soggetto. Riteniamo pertanto che l'obbligatorietà della sezione sopra evidenziata debba essere rimossa.

Rimaniamo in attesa di vostro riscontro.

**Comment by DiBellaDavide** [comment]
In merito allo stesso caso d'uso in questione, in effetti anche valorizzando il campo evento.riconoscimentoMadre.Avvenuto con _false_ , i dati relativi alla sezione sopraindicati continuano ad essere obbligatori. 

Allego un caso di test:
idOperazione":"1750854"

**Comment by maxill1** [comment]
Salve,
Abbiamo preso in carico la segnalazione.

Cordiali Saluti.
Supporto ANSC.

**Comment by maxill1** [comment]
**A)** Nell'ambito del casi d'uso **12221122/RICO_004** non rileviamo casistiche in cui la proprietà `evento.riconoscimentoMadre.avvenuto` possa valere `False`, di conseguenza andrà sempre valorizzata a `True`. Analogamente il caso d'uso **12222121/RICO_007**, anch'esso derivato dalla formula 109, dovrà avere `evento.riconoscimentoPadre.avvenuto` valorizzato a `True`.

**B)** Stiamo adeguando i controlli di 12221122/RICO_004 e 12222121/RICO_007 per recepire la non obbligatorietà dei campi relativi all'atto di riconoscimento già avvenuto:
- 12221122/RICO_004 avrà obbligatorio solo `evento.riconoscimentoMadre.avvenuto=True`
- 12222121/RICO_007 avrà obbligatorio solo `evento.riconoscimentoPadre.avvenuto=True`

Cordiali Saluti.
Supporto ANSC.

**Comment by asqueglia** [comment]
Buongiorno con la versione 1.28.0 la segnalazione è stata corretta. Chiudiamo pertanto la issue
