### ISSUE TITLE
Estremi atto di morte in ANPR

### ISSUE THREAD

**Issue by antonioluberto** [italia/ansc#683]
Buonasera.
La presente per riprendere una questione già in effetti emersa nella riunione di martedì 30 gennaio e per la quale si richiede un'indicazione finale.
Il quesito si riferisce al caso in cui l'ufficiale di stato civile del Comune in ANSC trascriva - in forma digitale - un atto di morte il cui originale sia stato prodotto, evidentemente in forma cartacea, da altro Comune italiano.
La trascrizione viene necessariamente gestita secondo il caso d'uso "Trascr_Morte_999" (2299) che non prevede l'indicazione degli estremi dell'atto di morte originale (prodotto dal Comune dove sia avvenuto il decesso).
Nel momento in cui l'usc valorizzi la data della validità anagrafica del decesso, all'anagrafe del Comune che ha eseguito la trascrizione (digitale) giunge notifica per la cancellazione del soggetto (da ANPR). La notifica in questione contiene i soli estremi dell'atto di morte digitale (trascritto): ne consegue se l'applicazione locale genera il procedimento anagrafico di cancellazione a partire dalla notifica ANPR in questione (come il "flusso" ANSC prevede), in ANPR sarà infine presente il riferimento al solo atto di morte digitale del soggetto (che evidentemente non è l'atto di morte originale).

Fino a prima di ANSC, all'atto della cancellazione di un proprio residente da ANPR l'applicazione locale riportava nel procedimento anagrafico di cancellazione collegato all'atto di morte sempre e solo i riferimenti all'atto di morte originale, perché tale è sempre stata la richiesta di tutti gli usc.

La domanda finale dunque è: è corretto che nel caso quale quello sopra descritto si abbiano in ANPR i soli riferimenti all'atto di morte (digitale) trascritto?

**Comment by asqueglia** [comment]
Buongiorno @antonioluberto, al momento nel caso d'uso di servizio indicato non acquisiamo il dato dell'atto originale in maniera spacchettata; questo dato si evince dalla composizione trasmessa.
Al momento nelle notifiche lato ANPR, non vengono mai trasmessi i dati dell'atto originario trascritto; questa informazione l'USC deve desumerla dalla composizione.
Valuteremo un possibile adeguamento, dopo un approfondimento con ANUSCA sull'argomento.

**Comment by asqueglia** [comment]
Buongiorno @antonioluberto da un confronto con ANUSCA confermiamo che verrà aggiunta la sezione dell'atto collegato (atto originario cartaceo) per il caso d'uso Trascr_Morte_999" (2299)

**Comment by asqueglia** [comment]
Con la versione 1.24.0 appena rilasciata la segnalazione è stata corretta. Chiudiamo pertanto la issue; in caso di ulteriori problematiche si prega di aprire una issue dedicata. Si rimanda alla documentazione per analizzare il contenuto della release rilasciata.
