### ISSUE TITLE
Errore certificazione se richiedente con Id ANPR

### ISSUE THREAD

**Issue by antonioluberto** [italia/ansc#684]
Presso il Comune di Grottaferrata si verifica l'anomalia per effetto della quale, laddove nell'invocazione del servizio si indichi l'identificativo ANPR del soggetto fisico che esegua la richiesta, il certificato non viene prodotto (si veda "idOperazione":"38542").
Effettuando la medesima richiesta (per il medesimo soggetto titolare ed il medesimo soggetto richiedente) eliminando dalla chiamata al servizio l'identificativo ANPR del soggetto fisico che esegua la richiesta l'emissione del certificato va a buon fine (si veda "idOperazione":"38545")

**Comment by mttfranci** [comment]
Buongiorno, stiamo verificando la vostra segnalazione.

Saluti

Assistenza ANSC
