### ISSUE TITLE
Impossibile aggiornare data validità anagrafica da servizio

### ISSUE THREAD

**Issue by antonioluberto** [italia/ansc#685]
Accortosi di errore nella valorizzazione della data validità anagrafica collegata a specifico atto, l'usc prova reinviare la data medesima ma il servizio risponde indicando che l'operazione non è possibile (si veda "idOperazione":"38735").
Come può l'usc aggiornare il dato in questione?

**Comment by mttfranci** [comment]
Buongiorno @antonioluberto , purtroppo la notificha anagrafica era già stata generata quando è stata tentata la rettifica.

Pertanto l'unico modo per impostare una nuova data, è che il comune ci invii una richiesta di resettare la notifica così da poter impostare una nuova data di validità.

Saluti

Assistenza ANSC

**Comment by antonioluberto** [comment]
In che modo deve essere inviata la richiesta di resettare la notifica? Con e-mail a supporto-ansc@sogei.it ?

**Comment by asqueglia** [comment]
Buongiorno @antonioluberto come concordato alla call questa mattina, attendiamo una vostra autorizzazione per poter procedere da centro alla rigenerazione della notifica anagrafica per consentirvi di modificare la data di validità. L0indirizzo a cui inviare la richiesta è assistenza.ansc@sogei.it
