### ISSUE TITLE
Risposta anomala da servizio R005

### ISSUE THREAD

**Issue by antonioluberto** [italia/ansc#686]
Su ambiente di produzione del Comune di Grottaferrata si riscontra risposta anomala (vuota) a richiesta relativa al servizio R005 ("idOperazione":"38737")

**Comment by mttfranci** [comment]
Buongiorno @antonioluberto , stiamo verificando, intanto una domanda, se la risposta era vuota dove avete visto l'idOperazione? Grazie in anticipo

Assistenza ANSC

**Comment by mttfranci** [comment]
@antonioluberto abbiamo recuperato l'operazione, i criteri di ricerca sembrano essere : 

```json
  "criteriRicercaSoggetto" : {
    "idAnpr" : "61638065",
    "idAnscSoggetto" : "4211174",
    "idComuneNascita" : ""
  },
```
Voi vi aspettate che il soggetto "idAnscSoggetto" : "4211174" abbia eventi?

Saluti

**Comment by antonioluberto** [comment]
Buongiorno.
Abbiamo verificato che il soggetto con 
"idAnscSoggetto" : "4211174"
effettivamente non ha eventi collegati in ANSC.
Abbiamo però appena verificato anche quanto segue:
invocando il servizio R005 ("idOperazione":"40177") indicando in input le sole generalità:
Cognome
Nome
Sesso
Data di nascita
Comune di nascita
Codice fiscale
(senza valorizzazione dell' Id ANPR)
otteniamo in risposta due soggetti con le medesime generalità ma diverso Id ANSC:
"id":4211174
"id":4211177.
L'evento (atto di morte) è effettivamente collegato solo al secondo dei due soggetti ("id":4211177).

Crediamo sia da analizzare cosa abbia potuto determinare la generazione del soggetto con
"id":4211174
in ANSC.

Rimaniamo a disposizione.

**Comment by mttfranci** [comment]
Salve, in effetti sono stati inseriti erroneamente due intestatari.
Stiamo verificando la causa.

Se ritenete potete chiedere la cancellazione dell'intestatario a cui non sono legati eventi, ovvero 4211174.

Saluti

Assistenza ANSC
