### ISSUE TITLE
usecase 433000	Trascrizione di Unione Civile di sentenze di Tribunali stranieri - Richiesta di trascrizione da parte dell'interessato	(Trascr_UnCiv_003)

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#687]
Buongiorno,
guardando il mapping 
![image](https://github.com/italia/ansc/assets/127182190/d8e5423f-5a39-45dd-9570-4971e1200fc7)

L'autorità mittente dovrebbe essere un ente straniero vista la descrizione dello usecase.
Nel mapping sono obbligatori Provincia e Comune, 
manca totalmente l'indicazione dello Stato da rendere obbligatorio.

**Comment by asqueglia** [comment]
Buongionro @annamaraspin  prendiamo in carico la segnalazione

**Comment by asqueglia** [comment]
Con la versione 1.24.0 appena rilasciata la segnalazione è stata corretta. Chiudiamo pertanto la issue; in caso di ulteriori problematiche si prega di aprire una issue dedicata. Si rimanda alla documentazione per analizzare il contenuto della release rilasciata.
