### ISSUE TITLE
dic_nasc_098 e dic_nasc_111 - errore di pattern

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#689]
ambiente test
idoperazione 1753231

400003 - Il campo evento.datiDiNascita.natoMorto nella sezione Soggetto non corrisponde al pattern ^(?i)no$
400003 - Il campo evento.datiDiNascita.natoVivoMaDeceduto nella sezione Soggetto non corrisponde al pattern ^(?i)si$

come per tutte le altre casistiche impostiamo i valori a SI oppure a NO

grazie

**Comment by asqueglia** [comment]
Buon pomeriggio @annamaraspin, l'id operazione indicata corrisponde ad una verifica allegato e non ad una richiesta di validazione. Potete inviarci l'identificativo corretto in modo da poter fare le opportune verifiche ?

**Comment by annamaraspin** [comment]
Mi scusi, devo aver copiato una riga per l'altra.


idoperazione : 1754105
