### ISSUE TITLE
[R010] Errore 404001 - Dati non presenti

### ISSUE THREAD

**Issue by RosarioSalatiello** [italia/ansc#69]
Il servizio di anteprima R010 restituisce l'errore 404001 - Dati non presenti quando si prova a effettuare una stampa per presa visione. La stessa composizione di dati viene accettata quando si invia l'atto per la stampa in formato bozza. 

Per un controllo da parte vostra riporto i dettagli della richiesta:

- data e ora: 19/04/2023 12:44
- ip sorgente 88.39.36.242

Per un eventuale invio del dump della richiesta aspetto istruzioni.

Grazie,
Rosario

**Comment by amusarra** [comment]
Buongiorno @RosarioSalatiello 
Potrebbe inviare la request e response JSON o l'idOperazione in modo che sia possibile recuperare la richiesta?

Grazie.

**Comment by MichelaGarzoni** [comment]
Buongiorno, ho fatto un test analogo, partendo da un atto di morte_001 appena validato con servizio R009 da cui ho ottenuto l'id_ansc e ho fatto richiesta, attraverso il servizio R010 di un'anteprima con il flag "presaVisione" a true (operazione che una decina di gg fa andava a buon fine presentandomi l'atto senza la dicitura "anteprima") e non riesco più a scaricare l'anteprima. Il json del servizio di richiesta (anonimizzato) è il seguente e contiene tutta la parte dell'evento con annesso idAnsc:

{"testataRichiesta":{"idComune":3655,"idOperazioneComune":2534,"dataOraRichiesta":"2023-04-20T13:10:28Z","nomeApplicativo":"ASCOT Stato Civile","versioneApplicativo":"21.99.0000","fornitoreApplicativo":"Insiel S.p.A"},"presaVisione":true,"evento":{"idTipoEvento":2,"id":2,"idAnsc":"2023-4244848-20230050000011-032001","idtipocontenuto":1,"idUsecase":2101,"descrizioneCasoUso":"Decesso in abitazione o in luogo pubblico","stato":"CONFERMATO","dataformazione":"2023-04-20","ora":12,"minuto":"03","numeroatto":20230050000011,"ausilioInterprete":false,"certificabile":1,"composizioneCompleta":"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.","datiEventoMorte":{"numeroComparenti":1,"comparente1":{"cognome":"XXXXX","nome":"YYYYYY","sesso":"M","dataNascita":"1941-03-11","idComuneNascita":"006","nomeComuneNascita":"TRIESTE","idProvinciaNascita":"032","siglaProvinciaNascita":"TS","idStatoNascita":100,"nomeStatoNascita":"ITALIA","idComuneResidenza":3655,"nomeComuneResidenza":"DUINO AURISINA-DEVIN NABREŽINA","idProvinciaResidenza":32,"siglaProvinciaResidenza":"TS","idStatoResidenza":100,"nomeStatoResidenza":"ITALIA","indirizzoResidenza":"FRAZIONE VISOGLIANO/VIŽOVLJE 14/B","idNazionalita":100,"nazionalita":"ITALIANO","flagDichiarante":true,"flagComparente":true,"flagFirmatario":true},"comparente2":null},"datiDichiarante":{"comprensione":0},"coniuge":{"cognome":"RRRRR","nome":"SSSSS","sesso":"M","dataNascita":"19XX-YY-09","idComuneNascita":"006","nomeComuneNascita":"TRIESTE","idProvinciaNascita":"032","siglaProvinciaNascita":"TS","idStatoNascita":100,"nomeStatoNascita":"ITALIA","idComuneResidenza":3655,"nomeComuneResidenza":"DUINO AURISINA-DEVIN NABREŽINA","idProvinciaResidenza":32,"siglaProvinciaResidenza":"TS","idStatoResidenza":100,"nomeStatoResidenza":"ITALIA","idNazionalita":100,"nazionalita":"ITALIANO","flagDichiarante":false,"flagComparente":false,"flagFirmatario":false},"interprete":null,"datiDiMorte":{"idComuneMorte":3655,"nomeComuneMorte":"DUINO AURISINA-DEVIN NABREŽINA","idProvinciaMorte":32,"siglaProvinciaMorte":"TS","idStatoMorte":100,"nomeStatoMorte":"ITALIA","dataMorte":"2023-04-19","annoMorte":2023,"meseMorte":"04","giornoMorte":19,"minutoMorte":" 32"},"intestatari":[{"codiceFiscale":"XXXYYYNNNRNNRNNNR","cognome":"XXXX","nome":"YYYY","sesso":"F","dataNascita":"1XXX-0X-30","idComuneNascita":"006","nomeComuneNascita":"TRIESTE","idProvinciaNascita":"032","siglaProvinciaNascita":"TS","idStatoNascita":100,"nomeStatoNascita":"ITALIA","idComuneResidenza":3655,"nomeComuneResidenza":"DUINO AURISINA-DEVIN NABREŽINA","idProvinciaResidenza":32,"siglaProvinciaResidenza":"TS","idStatoResidenza":100,"nomeStatoResidenza":"ITALIA","indirizzoResidenza":"FRAZIONE AURISINA CAVE/NABREŽINA KAMNOLOMI 78/G2","idstatocivile":2,"descrizionestatocivile":"Coniugato","idNazionalita":100,"nazionalita":"ITALIANA"}]}}

La risposta che ottengo è:
{
    "testataRisposta": {
        "idComune": 3655,
        "idOperazioneComune": "2534",
        "idOperazione": "1581881",
        "idEsito": 1
    },
    "errors": [
        {
            "code": "404001",
            "severity": "E",
            "text": "Dati non presenti"
        }
    ]
}

Se sostituisco tutta la parte "evento" con la sola parte idAnsc in questo modo, come indicato da voi sopra:

{"testataRichiesta":{"idComune":3655,"idOperazioneComune":2534,"dataOraRichiesta":"2023-04-20T13:10:28Z","nomeApplicativo":"ASCOT Stato Civile","versioneApplicativo":"21.99.0000","fornitoreApplicativo":"Insiel S.p.A"},"presaVisione":true,"evento":{"idAnsc":"2023-4244848-20230050000011-032001"}}

ottengo invece la seguente risposta:

{
    "testataRisposta": {
        "idComune": 3655,
        "idOperazioneComune": "2534",
        "idOperazione": "1581882",
        "idEsito": 1
    },
    "errors": [
        {
            "code": "400001",
            "severity": "E",
            "text": "Use Case non valido"
        }
    ]
}

Se tolgo idAnsc e setto il flag a false ottengo correttamente l'anteprima dell'atto con la scritta "anteprima".

Dov'è il mio errore?
Grazie

**Comment by RosarioSalatiello** [comment]
@amusarra buongiorno. Quindi l'atto deve essere prima inviato per la validazione e poi stampato per presa visione? Da quale versione del servizio è stato introdotto questo comportamento?

Grazie

**Comment by MichelaGarzoni** [comment]
@RosarioSalatiello @amusarra buongiorno. Da quanto ho capito io con "presaVisione" a false posso vedere in qualsiasi momento l'atto anche se non ancora validato ed infatti non è obbligatorio inserire l'idAnsc (che non essendo validato non ce l'ho ancora a disposizione). Nel caso invece io richieda l'anteprima per la firma autografa dei firmatari presentiil flag "presaVisione" deve essere a true e nel corpo dell'"evento" devo avere inserito l'identificativo idAnsc che mi è stato restituito nella precedente validazione dell'atto. Ho capito male? Ho travisato nella logica del percorso che si deve seguire?

Grazie

**Comment by amusarra** [comment]
Buongiorno @RosarioSalatiello e @MichelaGarzoni confermo l'anteprima dell'evento in formato PDF senza il watermark può essere richiesto solo quanto si è in possesso dell'idAnsc o IdEvento. A seguire un esempio di richiesta andata a buon fine.

![image](https://user-images.githubusercontent.com/708110/233572800-5604033a-86d5-46d0-9cba-511061f40250.png)

Riguardo l'errore Use Case non valido ottenuto da @MichelaGarzoni può essere dovuto a qualcosa inerente all'evento. Su quest'ultimo punto faremo un tentativo di replica dell'errore utilizzando il payload usato da @MichelaGarzoni 

Cordiali Saluti.
Supporto ANSC.

**Comment by amusarra** [comment]
Salve @MichelaGarzoni 
In ambiente di pre-produzione l'evento indicato `2023-4244848-20230050000011-032001` non esiste, ecco il motivo dell'errore (vedi a seguire).

![image](https://user-images.githubusercontent.com/708110/233577014-deaa8334-1606-44af-90cc-6ad8f8a35134.png)

Come è stato scritto, l'evento deve essere prima validato e solo dopo si può richiedere l'evento in PDF senza il watermark.

Le segnalo inoltre, che il payload indicato contiene gli attributi `id `e `idAnsc` che non dovrebbero essere presenti, è riportato a seguire per completezza.

```
{
    "testataRichiesta": {
        "idComune": 3655,
        "idOperazioneComune": 2534,
        "dataOraRichiesta": "2023-04-20T13:10:28Z",
        "nomeApplicativo": "ASCOT Stato Civile",
        "versioneApplicativo": "21.99.0000",
        "fornitoreApplicativo": "Insiel S.p.A"
    },
    "presaVisione": true,
    "evento": {
        "idTipoEvento": 2,
        "id": 2,
        "idAnsc": "2023-4244848-20230050000011-032001",
        "idtipocontenuto": 1,
        "idUsecase": 2101,
        "descrizioneCasoUso": "Decesso in abitazione o in luogo pubblico",
        "stato": "CONFERMATO",
        "dataformazione": "2023-04-20",
        "ora": 12,
        "minuto": "03",
        "numeroatto": 20230050000011,
        "ausilioInterprete": false,
        "certificabile": 1,
        "composizioneCompleta": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.",
        "datiEventoMorte": {
            "numeroComparenti": 1,
            "comparente1": {
                "cognome": "XXXXX",
                "nome": "YYYYYY",
                "sesso": "M",
                "dataNascita": "1941-03-11",
                "idComuneNascita": "006",
                "nomeComuneNascita": "TRIESTE",
                "idProvinciaNascita": "032",
                "siglaProvinciaNascita": "TS",
                "idStatoNascita": 100,
                "nomeStatoNascita": "ITALIA",
                "idComuneResidenza": 3655,
                "nomeComuneResidenza": "DUINO AURISINA-DEVIN NABREŽINA",
                "idProvinciaResidenza": 32,
                "siglaProvinciaResidenza": "TS",
                "idStatoResidenza": 100,
                "nomeStatoResidenza": "ITALIA",
                "indirizzoResidenza": "FRAZIONE VISOGLIANO/VIŽOVLJE 14/B",
                "idNazionalita": 100,
                "nazionalita": "ITALIANO",
                "flagDichiarante": true,
                "flagComparente": true,
                "flagFirmatario": true
            },
            "comparente2": null
        },
        "datiDichiarante": {
            "comprensione": 0
        },
        "coniuge": {
            "cognome": "RRRRR",
            "nome": "SSSSS",
            "sesso": "M",
            "dataNascita": "19XX-YY-09",
            "idComuneNascita": "006",
            "nomeComuneNascita": "TRIESTE",
            "idProvinciaNascita": "032",
            "siglaProvinciaNascita": "TS",
            "idStatoNascita": 100,
            "nomeStatoNascita": "ITALIA",
            "idComuneResidenza": 3655,
            "nomeComuneResidenza": "DUINO AURISINA-DEVIN NABREŽINA",
            "idProvinciaResidenza": 32,
            "siglaProvinciaResidenza": "TS",
            "idStatoResidenza": 100,
            "nomeStatoResidenza": "ITALIA",
            "idNazionalita": 100,
            "nazionalita": "ITALIANO",
            "flagDichiarante": false,
            "flagComparente": false,
            "flagFirmatario": false
        },
        "interprete": null,
        "datiDiMorte": {
            "idComuneMorte": 3655,
            "nomeComuneMorte": "DUINO AURISINA-DEVIN NABREŽINA",
            "idProvinciaMorte": 32,
            "siglaProvinciaMorte": "TS",
            "idStatoMorte": 100,
            "nomeStatoMorte": "ITALIA",
            "dataMorte": "2023-04-19",
            "annoMorte": 2023,
            "meseMorte": "04",
            "giornoMorte": 19,
            "minutoMorte": " 32"
        },
        "intestatari": [
            {
                "codiceFiscale": "XXXYYYNNNRNNRNNNR",
                "cognome": "XXXX",
                "nome": "YYYY",
                "sesso": "F",
                "dataNascita": "1XXX-0X-30",
                "idComuneNascita": "006",
                "nomeComuneNascita": "TRIESTE",
                "idProvinciaNascita": "032",
                "siglaProvinciaNascita": "TS",
                "idStatoNascita": 100,
                "nomeStatoNascita": "ITALIA",
                "idComuneResidenza": 3655,
                "nomeComuneResidenza": "DUINO AURISINA-DEVIN NABREŽINA",
                "idProvinciaResidenza": 32,
                "siglaProvinciaResidenza": "TS",
                "idStatoResidenza": 100,
                "nomeStatoResidenza": "ITALIA",
                "indirizzoResidenza": "FRAZIONE AURISINA CAVE/NABREŽINA KAMNOLOMI 78/G2",
                "idstatocivile": 2,
                "descrizionestatocivile": "Coniugato",
                "idNazionalita": 100,
                "nazionalita": "ITALIANA"
            }
        ]
    }
}
```
Payload 1 - Payload evento con attributi id e idAnsc che non dovrebbero essere presenti.

Cordiali Saluti.
Supporto ANSC.

**Comment by amusarra** [comment]
@MichelaGarzoni e @RosarioSalatiello chiudo la issue perché a nostro avviso è stata risolta.

Supporto ANSC.
