### ISSUE TITLE
[ws R009] Trascrizione Nascita (cdu 1399) - Dati genitori obbligatori

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/ansc#691]
ambiente PRE-PROD - comune di FAENZA (idComune 3743)

in riferimento a quanto condiviso questa mattina, riguardo l'obbligatorietà dei campi di padre e madre nel caso d'uso 1399, comunico un esempio che va in errore in fase di validazione.

idOperazioneComune; 2024001981 - idOperazioneAnsc: 1753286

si tratta di atto nel quale sono stati indicati solo cognome e nome dei genitori e nessuna altro dato di nascita
gli errori segnalati sono questi:
Il campo evento.madre.dataNascita nella sezione Madre è obbligatorio
Il campo evento.madre.idStatoNascita nella sezione Madre è obbligatorio
Il campo evento.madre.nomeStatoNascita nella sezione Madre è obbligatorio
Il campo evento.madre.idNazionalita nella sezione Madre è obbligatorio
Il campo evento.madre.nazionalita nella sezione Madre è obbligatorio
Il campo evento.madre.idStatoResidenza nella sezione Madre è obbligatorio
Il campo evento.madre.nomeStatoResidenza nella sezione Madre è obbligatorio
Il campo evento.padre.dataNascita nella sezione Padre è obbligatorio
Il campo evento.padre.idStatoNascita nella sezione Padre è obbligatorio
Il campo evento.padre.nomeStatoNascita nella sezione Padre è obbligatorio
Il campo evento.padre.idNazionalita nella sezione Padre è obbligatorio
Il campo evento.padre.nazionalita nella sezione Padre è obbligatorio
Il campo evento.padre.idStatoResidenza nella sezione Padre è obbligatorio
Il campo evento.padre.nomeStatoResidenza nella sezione Padre è obbligatorio

grazie
Alessandro ADS

**Comment by siscomanpr** [comment]
Anche sull'ambiente pre-prod di Serravalle Sesia rileviamo la stessa problematica. 
idOperazione: 1753514

**Comment by asqueglia** [comment]
Buongiorno prendiamo in carico la segnalazione

**Comment by asqueglia** [comment]
Con la versione 1.24.0 appena rilasciata la segnalazione è stata corretta. Chiudiamo pertanto la issue; in caso di ulteriori problematiche si prega di aprire una issue dedicata. Si rimanda alla documentazione per analizzare il contenuto della release rilasciata.
