### ISSUE TITLE
[webapp]: dataAtto / dataFormazione / dataEvento - caso Unione Civile

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/ansc#697]
### Ambiente

pre-produzione

### Provenienza segnalazione

Software House

### Riferimenti operatore/comune

FAENZA

### Data del test (yyyy-mm-dd)

2024-02-13

### Caso d'uso

4.4.3.0.0.0

### Descrivi il problema

salve, pongo una questione forse già affrontata in altre issue, ma che ancora oggi ci pone dubbi di interpretazione.

caso di unione civile (useCase 4.1.1.1.1.1) e successivo accordo di scioglimento (useCase 4.4.3.0.0.0)

l'atto di unione civile (idAnsc 2024-1220586-10039-039010) è stato registrato con le seguenti informazioni:
- data dell'unione civile: 12/02/2024
- data di formazione dell'atto: 13/02/2024
![image](https://github.com/italia/ansc/assets/26788199/8648f30c-f993-42ca-92f6-9a34d5267d3f)
![image](https://github.com/italia/ansc/assets/26788199/1a83e214-017e-49ea-bc9f-b8a510179727)

in sede di redazione dell'accordo di scioglimento (idAnsc 2024‐1220596‐10040‐039010), nella sezione "Atto unione civile" richiamiamo l'atto di cui sopra, e la "data atto" che viene recuperata automaticamente è quella di formazione dell'atto (13/02/2024)
![image](https://github.com/italia/ansc/assets/26788199/28d04b12-b3ba-486b-a5b6-ac4f6087679c)
(coerentemente rispetto al fatto che, tramite web-service, quello stesso campo si chiama "dataformazione")

poi però, la composizione dell'atto (di accordo) riporta quel dato trattandolo come data dell'evento:
![image](https://github.com/italia/ansc/assets/26788199/77bfaa20-4f2e-4808-9420-b183049bd207)

l'errore è nella generazione del testo di "composizione"? oppure la "data atto" della sezione "atto unione civile" dovrebbe essere la data dell'evento e non la data formazione?

grazie
Alessandro ADS

**Comment by asqueglia** [comment]
Buonasera, con il rilascio della versione 1.26.0 è stata corretta la segnalazione. Si prega di far riferimento al changelog per i dettagli
