### ISSUE TITLE
Changelog e tabelle di decodifica

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#7]
1) nel changelog non è riportato l'aggiunta della tabella 79 ma sempre la 78 che è uscita nella versione della settimana scorsa.

2) nel changelog si dovrebbe indicare anche se nelle tabelle sono stati modificati dei record o aggiunti/eliminati. 
Ad esempio nell'ultima riunione vi avevo fatto notare i codici degli eventi erano errati visto che il json veniva bocciato. Questa modifica è stata rilasciata come tabella ma mai menzionata nel changelog. Diventa pesante ad ogni versione ricontrollare ogni record di ogni tabella.

Si richiede un file con eventuali modifiche tra la versione della scorsa settimana e quella di ieri il prima possibile per favore. 
Oppure mi assicurate che la versione 1.4 di venerdì e la 1.5 di ieri l'unica differenza è la tabella 79?

 Grazie

**Comment by mttfranci** [comment]
Salve.

1. Per la tabella 79 avete ragione, provvederemo a breve ad aggiornare il changelog.

Anche dall'interfaccia del browser di github è possibile verificare quali siano state le risorse modificate. Relativamente ai CSV delle decodifiche è stato solo aggiunta la tabelal 79.

![image](https://user-images.githubusercontent.com/29305782/223443480-cd68cc63-a240-4d5d-9c23-fdcca02efde2.png)


2. Per un livello di dettaglio maggiore, grazie alla migrazione alla piattaforma github, il dettaglio delle modifiche si può ottenere con un git diff, ad esempio sul singolo file CSV. Questo è una delle motivazioni per cui abbiamo migrato qui la documentazione. Stiamo comunque valutando la produzione di ulteriore documentazione di supporto

![image](https://user-images.githubusercontent.com/29305782/223353215-eb05a53f-949e-461f-96de-7fe8d9347998.png)

Inoltre se credete, stavamo valudando di lasciare nella documentazione solo la versione CSV, per cui la verifica delle differenze è più agevole trattandosi di un formato di testo.
Pensate sia auspicabile?

Saluti

Assistenza ANSC

**Comment by annamaraspin** [comment]
"Anche dall'interfaccia del browser di github è possibile verificare quali siano state le risorse modificate. "

Io ho scaricato la versione 1.4 venerdì. Adesso sono andata a vedere come da suo suggerimento la tabella 39 ad esempio: github mi dice che la tabella è stata modificata 3 giorni fa (quindi dopo il mio scarico di venerdì).
Ora sono andata a confrontarla ed è identica, quindi quella data di ultima modifica non è veritiera.

**Comment by mttfranci** [comment]
Salve, ma sta confrontando la versione CSV o quella XLSX? 

Lo chiediamo perchè come accennato in precedenza solo la versione CSV è confrontabile (la versione XLSX trattandosi di un binario ad ogni rigenerazione risulta variata, anche per questo proniamo di lasciare solo la versione CSV).

Ad esempio la tabella 39 da voi menzianata, nella versione CSV non ha subito modifiche dal commit iniziale : 
![image](https://user-images.githubusercontent.com/29305782/223452886-fa061d92-59ae-49be-8c4c-50bb6d16b12a.png)

Saluti

**Comment by annamaraspin** [comment]
Io sono andata a vedere la pagina che lei ha fatto print screen nella prima risposta
![Cattura_u](https://user-images.githubusercontent.com/127182190/223454131-c618bf0b-c628-4134-8958-270838aa20ae.PNG)

e come vede trovo un .csv della versione 1.4 e .xlsx della versione 1.5 e a fianco c'è la data dell'ultima modifica . 
Ho provato a fare anche il "cerca" ma di csv della versione 1.5 non mi vengono visualizzati.

**Comment by mttfranci** [comment]
Salve, mi scusi, ma il suo screenshot mostra esattamente quello che stavamo dicendo. 
Ovvero che la versione CSV della tabelal di decodifica non ha modifiche (ovvero è ferma a 5 giorni fa) invece della versione xlsx (che è di 3 giorni fa, in quanto essendo un binario risulta comunque aggiornata)

![image](https://user-images.githubusercontent.com/29305782/223458801-59522950-98de-4024-948a-04b7b3905a32.png)

**Comment by annamaraspin** [comment]
allora è sbagliata la descrizione della versione del csv... io vedo 1.4 e quindi vado a pensare che sia un file vecchio da non prendere in considerazione.

**Comment by mttfranci** [comment]
@annamaraspin nessun errore. Semplicemente viene mostrato per ogni risorsa il commento dell'ultimo commit in cui la risorsa stessa ha subito modifiche.

Queste sono scelte non operate da noi ma dalla piattaforma. Il vantaggio è che gli sviluppatori possono ritrovare lo stesso approccio per tutti i progetti ospitati.

Suggeriamo di consultare la documentazione di github e piu in generale di git per le caratteristiche intrinseche di tali strumenti.

Saluti

Assistenza ANSC

**Comment by mttfranci** [comment]
@annamaraspin  Cercheremo di fare il possibile per rendere più agevole il recepimento delle modifiche. Intanto mi permetto di segnalare che con il rilascio della versione 1.5.0 è stato reso disponibile il servizio di configurazione delle decodifiche (analogamente a quanto già avveniva in ANPR e come richiesto in alcuni degli incontri tenuti in questi mesi) : 

https://github.com/italia/ansc/blob/main/docs/openapi/R901_config_decodifica.yaml

Tale servizio permette di accedere in modo applicativo all'elenco e al dettaglio delle tabelle di decodifiche.

Siamo a disposizione per ogni ulteriore chiarimento.

Saluti

Assistenza ANSC
