### ISSUE TITLE
usecase trascr_matr_005 errore campo obbligatorio

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#702]
### Ambiente

pre-produzione

### Servizio

R009 - Servizi cooperativi validazione evento

### idOperazione

1754643

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

ponsacco

### Data del test (yyyy-mm-dd)

14.02.2024

### Descrivi il problema

in validazione atto mi restituisce
00003 - Il campo evento.trascrizioneMatrimonio.attoEstero.enteEstero.comuneEstero nella sezione Atto da trascrivere �bbligatorio

Nel mapping il Comune non è obbligatorio, inoltre al momento c'è la regola che per i Comuni esteri va indicato solo lo Stato (mi ricordo che ieri in riunione ci avete preannunciato che dovrete rivedere questa regola)

**Comment by amusarra** [comment]
Salve @annamaraspin 
Abbiamo preso in carico la segnalazione.

Cordiali Saluti.
Supporto ANSC.

**Comment by asqueglia** [comment]
Con la versione 1.24.0 appena rilasciata la segnalazione è stata corretta. Chiudiamo pertanto la issue; in caso di ulteriori problematiche si prega di aprire una issue dedicata. Si rimanda alla documentazione per analizzare il contenuto della release rilasciata.
