### ISSUE TITLE
[webapp] - [SC]: Allegati per caso d'uso 332000

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#704]
### Ambiente

pre-produzione, produzione

### Provenienza segnalazione

Software House

### Riferimenti operatore/comune

biadanpad

### Data del test (yyyy-mm-dd)

2024-02-14

### Caso d'uso

332000

### Descrivi il problema

Sia in WebApp sia nel mapping del caso d'uso viene richiesto come obbligatorio l'allegato "Atto estero di nascita originale o copia autentica":
![image](https://github.com/italia/ansc/assets/131870281/a32a3dc6-5a17-41f6-ac99-1be9af7da50f)

Credo che per questo caso d'uso, l'allegato menzionato non debba essere necessario.

**Comment by amusarra** [comment]
Salve @biadanpad 
Abbiamo preso in carico la sua segnalazione.

Cordiali Saluti.
Supporto ANSC.

**Comment by asqueglia** [comment]
Con la versione 1.24.0 appena rilasciata la segnalazione è stata corretta. Chiudiamo pertanto la issue; in caso di ulteriori problematiche si prega di aprire una issue dedicata. Si rimanda alla documentazione per analizzare il contenuto della release rilasciata.
