### ISSUE TITLE
Informazione da parte del comune di Venezia su errore in Validazione Atto

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#706]
### Ambiente

pre-produzione

### Servizio

R009 - Servizi cooperativi validazione evento

### idOperazione

----

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

venezia

### Descrivi il problema

Buongiorno,
durante i test a Venezia è uscito questo errore:
![image](https://github.com/italia/ansc/assets/127182190/533c7c68-f25d-4281-931e-bc5540e49216)

Si chiedevano quando viene scatenato. Forse hanno una basedati con soggetti ANPR troppo vecchi?

**Comment by asqueglia** [comment]
Buongiorno @annamaraspin , abbiamo bisogno dell'idoperazione effettuata oppure del payload con cui invocate il servizio per poter procedere ad una verifica opportuna.

**Comment by annamaraspin** [comment]
Mi scusi ma solo oggi mi hanno mandato il dato:
id operazione 1701915

**Comment by asqueglia** [comment]
Buongiorno abbiamo verificato che il soggetto da voi indicato nella richiesta di validazione (con id anpr 137902468) non esiste in ambiente di test comuni.
Da ulteriori verifiche comunichiamo che per il comune di Venezia non sono presenti soggetti registrati in ambiente di test comuni.
