### ISSUE TITLE
[SC]: Errore in validazione u.c. 52999

### ISSUE THREAD

**Issue by corradosacco** [italia/ansc#711]
### Ambiente

pre-produzione

### Servizio

R009 - Servizi cooperativi validazione evento

### idOperazione

1759703

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Milano, Sacco Corrado

### Data del test (yyyy-mm-dd)

2024-02-21

### Descrivi il problema

Nel validare l'evento di usecase 52999 mi imbatto in questa segnalazione:
`Errore chiamata al servizio ANSC: code=404003, severity=E, text=Evento non trovato`

**Comment by gbuemi** [comment]
Buongiorno @corradosacco,
nel payload inoltrato viene inviato un evento collegato con id: 149 inesistente in ambiente di preproduzione.

Un saluto,
Supporto ANSC
