### ISSUE TITLE
[SC]: Errore validazione Annotazione modificativa generica

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#712]
### Ambiente

pre-produzione

### Servizio

R013 - Servizi cooperativi per la validazione della rettifica

### idOperazione

1760584

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

biadanpad

### Data del test (yyyy-mm-dd)

2024-02-22

### Descrivi il problema

Il servizio ritorna l'errore: "Attenzione! Dati incompleti: intestatario non presente" anche se i dati dell'intestatario sono completi ed il soggetto è presente in ANSC:
![image](https://github.com/italia/ansc/assets/131870281/beb29ebc-563a-4cf0-831b-7631c5a7e6f2)

### Payload (json)

```JSON
REQUEST:
{
    "evento": {
        "idTipoEvento": "1",
        "idtipocontenuto": "1",
        "idUsecase": "14850000",
        "descrizioneCasoUso": "Annotazione modificativa generica",
        "stato": "CONFERMATO",
        "idVersion": "100008",
        "dataformazione": "2024-02-22",
        "ora": "17",
        "minuto": "08",
        "operatore": "DLCNTN57L67A064W",
        "operatoreNome": "MARGHERITA",
        "operatoreCognome": "CITTERIO",
        "idComuneRegistrazione": "5000",
        "nomeComuneRegistrazione": "LISSONE",
        "idProvinciaRegistrazione": "108",
        "siglaProvinciaRegistrazione": "MB",
        "numeroatto": "3550",
        "intestatari": [{
                "cognome": "BARTALI",
                "nome": "LUCA",
                "sesso": "M",
                "dataNascita": "2023-12-20",
                "idStatoNascita": "113",
                "nomeStatoNascita": "MAROCCO",
                "idComuneResidenza": "20052",
                "nomeComuneResidenza": "PISTOIA (PT)",
                "idProvinciaResidenza": "47",
                "siglaProvinciaResidenza": "PT",
                "idStatoResidenza": "90",
                "nomeStatoResidenza": "ITALIA",
                "idNazionalita": "90",
                "nazionalita": "ITALIANA"
            }
        ],
        "composizioneCompleta": "cambio nome e cognome\n",
        "flagAnnotazioneNonCertificabile": false,
        "datiAnnotazioneModificativa": {
            "attoIntestatario": {
                "idAnsc": "2023-1216703-6-108028",
                "idComuneRegistrazione": "5000",
                "nomeComuneRegistrazione": "LISSONE",
                "idProvinciaRegistrazione": "108",
                "siglaProvinciaRegistrazione": "MB",
                "numeroatto": "6",
                "dataformazione": "2023-12-22",
                "annoAtto": "2023",
                "tipologia": "1"
            },
            "tipoModifica": 8,
            "nuovoCognomeIntestatario": "NC",
            "nuovoNomeIntestatario": "NN",
            "vecchioNomeIntestatario": "VN",
            "vecchioCognomeIntestatario": "VC"
        }
    },
    "testataRichiesta": {
        "idComune": 5000,
        "idOperazioneComune": "3550",
        "dataOraRichiesta": "2024-02-22T17:08:52.569+01:00",
        "nomeApplicativo": "urbi",
        "versioneApplicativo": "1.1.5",
        "fornitoreApplicativo": "padigitale"
    }
}

RESPONSE:
{
    "testataRisposta": {
        "idComune": 5000,
        "idOperazioneComune": "3550",
        "idOperazione": "1760584"
    },
    "errors": [{
            "code": "400003",
            "severity": "E",
            "text": "Attenzione! Dati incompleti: intestatario non presente"
        }
    ],
    "infos": [{
            "code": "110527",
            "severity": "I",
            "text": "Informazioni sull'operazione da fornire in caso di assistenza : data:2024-02-22 16:08:54 , idOperazione:1760584"
        }
    ]
}
```

**Comment by biadanpad** [comment]
Ottengo lo stesso errore anche per Annotazione per cambio generalità genitore:

REQUEST:
{
    "evento": {
        "idTipoEvento": "1",
        "idtipocontenuto": "1",
        "idUsecase": "14750000",
        "descrizioneCasoUso": "Annotazione per cambio generalità genitore",
        "stato": "CONFERMATO",
        "idVersion": "100008",
        "dataformazione": "2024-02-22",
        "ora": "17",
        "minuto": "08",
        "operatore": "DLCNTN57L67A064W",
        "operatoreNome": "MARGHERITA",
        "operatoreCognome": "CITTERIO",
        "idComuneRegistrazione": "5000",
        "nomeComuneRegistrazione": "LISSONE",
        "idProvinciaRegistrazione": "108",
        "siglaProvinciaRegistrazione": "MB",
        "numeroatto": "3550",
        "intestatari": [{
                "cognome": "BARTALI",
                "nome": "LUCA",
                "sesso": "M",
                "dataNascita": "2023-12-20",
                "idStatoNascita": "113",
                "nomeStatoNascita": "MAROCCO",
                "idComuneResidenza": "20052",
                "nomeComuneResidenza": "PISTOIA (PT)",
                "idProvinciaResidenza": "47",
                "siglaProvinciaResidenza": "PT",
                "idStatoResidenza": "90",
                "nomeStatoResidenza": "ITALIA",
                "idNazionalita": "90",
                "nazionalita": "ITALIANA"
            }
        ],
        "composizioneCompleta": "VN VC, Padre di LUCA BARTALI ha assunto il nuovo  nome e cognome NN NC\ncambio nome e cognome padre\n",
        "datiAnnotazioneModificativa": {
            "attoIntestatario": {
                "idAnsc": "2023-1216703-6-108028",
                "idComuneRegistrazione": "5000",
                "nomeComuneRegistrazione": "LISSONE",
                "idProvinciaRegistrazione": "108",
                "siglaProvinciaRegistrazione": "MB",
                "numeroatto": "6",
                "dataformazione": "2023-12-22",
                "annoAtto": "2023",
                "tipologia": "1"
            },
            "tipoModifica": 8,
            "genitore": 2,
            "nuovoCognomeGenitore": "NC",
            "nuovoNomeGenitore": "NN",
            "vecchioCognomeGenitore": "VC",
            "vecchioNomeGenitore": "VN",
            "nuovoCognomeIntestatario": "NC"
        }
    },
    "testataRichiesta": {
        "idComune": 5000,
        "idOperazioneComune": "3550",
        "dataOraRichiesta": "2024-02-22T17:19:37.237+01:00",
        "nomeApplicativo": "urbi",
        "versioneApplicativo": "1.1.5",
        "fornitoreApplicativo": "padigitale"
    }
}

RESPONSE:
{
    "testataRisposta": {
        "idComune": 5000,
        "idOperazioneComune": "3550",
        "idOperazione": "1760597"
    },
    "errors": [{
            "code": "400003",
            "severity": "E",
            "text": "Attenzione! Dati incompleti: intestatario non presente"
        }
    ],
    "infos": [{
            "code": "110527",
            "severity": "I",
            "text": "Informazioni sull'operazione da fornire in caso di assistenza : data:2024-02-22 16:19:38 , idOperazione:1760597"
        }
    ]
}

**Comment by gbuemi** [comment]
Buongiorno,
abbiamo preso in carico la segnalazione.

Un saluto,
Supporto ANSC

**Comment by asqueglia** [comment]
Buonasera, la segnalazione è stata corretta con la versione 1.25.0. La issue viene chiusa. In caso di ulteriori problematiche si prega di aprire una issue dedicata.
