### ISSUE TITLE
Caso d'uso Rico_005: anomala richiesta campo "Riconoscimento genitore"

### ISSUE THREAD

**Issue by antonioluberto** [italia/ansc#713]
### Ambiente

pre-produzione, produzione

### Servizio

R009 - Servizi cooperativi validazione evento

### idOperazione

assente

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Grottaferrata

### Descrivi il problema

Il caso d'uso in oggetto si riferisce a "Riconoscimento paterno di figlio di ignoti ultra14enne".
La modellazione riporta al momento l'indicazione relativa alla necessità di valorizzare il campo:

![image](https://github.com/italia/ansc/assets/26415430/c0c691ba-444d-4d21-bb28-84fcd2a4d0c6)

che, a nostro avviso, non ha senso (esegue il riconoscimento solo il padre, la madre non esiste).
La nostra supposizione pare confermata dalla modellazione relativa al caso d'uso "duale" 
Rico_008 - Riconoscimento materno di figlio di ignoti ultra14enne
che non prevede campo equivalente a quello sopra indicato.

Rimaniamo in attesa di vostro riscontro.

**Comment by amusarra** [comment]
Buongiorno @antonioluberto 
Abbiamo preso in carico la segnalazione e faremo le opportune verifiche.
Avete eseguito anche la prova di validazione? Nel caso potreste fornire il payload?

Cordiali Saluti.
Supporto ANSC.

**Comment by asqueglia** [comment]
Buonasera, la segnalazione è stata corretta con la versione 1.25.0. La issue viene chiusa. In caso di ulteriori problematiche si prega di aprire una issue dedicata.
