### ISSUE TITLE
[SC]:Informazione su versione 1.24 - retro compatibilità 

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#714]
### Ambiente

pre-produzione

### Servizio

R009 - Servizi cooperativi validazione evento

### idOperazione

----

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

ponsacco, anna maraspin

### Descrivi il problema

Buonasera,
come da ultima riunione del 13c.m. vi avevamo comunicato l'imminente uscita del rilascio di una nuova versione del nostro gestionale.
Mi confermate che la retro compatibilità è estesa a tutte le modifiche effettuate indifferentemente dal servizio rilasciate nella vostra versione 1.24?

**Comment by mttfranci** [comment]
Buongiorno.

Si con la versione 1.24.0 è stata pubblicata una nuova versione del data model : 

https://github.com/italia/ansc/blob/main/docs/Decodifiche/100_dec_versione.csv

ma i relativi controlli si attivano solo se viene indicata l'idVersion = 100009.

Con le versioni precedenti vengono applicati i precedenti set di controlli fino alla fine del supporto delle stesse. (3 mesi dalla data in cui una versione non è più l'ultima).

Saluti
