### ISSUE TITLE
[R009] per Matr_999_2 - ancora richiesto il numeroTestimoni.

### ISSUE THREAD

**Issue by gcuci** [italia/ansc#715]
### Ambiente

pre-produzione

### Servizio

R009 - Servizi cooperativi validazione evento

### idOperazione

1760868

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Bagnacavallo

### Data del test (yyyy-mm-dd)

2024-02-23

### Descrivi il problema

buongiorno,

per il caso d'uso di servizio Matr_999_2: Caso d'uso di servizio (matrimoni con rito religioso), segnaliamo che si presenta ancora l'anomalia sul numeroTestimoni, già oggetto di una precedente issue #189, risolta con la versione 1.10.0.

Inviando una richiesta di validazione, in ambiente di pre-produzione, con numeroTestimoni = '0' (previsto dal mapping come obbligatorio, quindi lo valorizziamo), il servizio restituisce:

{
  "testataRisposta": {
    "idComune": 595,
    "idOperazioneComune": "9366",
    "idOperazione": "1760868",
    "idEsito": 1
  },
  "errors": [
    {
      "code": "400003",
      "severity": "E",
      "text": "Il campo evento.datiEventoMatrimonio.numeroTestimoni nella sezione Dettagli evento non corrisponde al pattern ^[2-4]$"
    }
  ],
  "infos": [
    {
      "code": "110527",
      "severity": "I",
      "text": "Informazioni sull'operazione da fornire in caso di assistenza : data:2024-02-23 09:37:20 , idOperazione:1760868"
    }
  ]
}

In attesa di riscontro,

cordiali saluti.

**Comment by amusarra** [comment]
Salve @gcuci 
Abbiamo preso in carico la segnalazione.

Cordiali Saluti.
Supporto ANSC.

**Comment by asqueglia** [comment]
Buonasera, la segnalazione è stata corretta con la versione 1.25.0. La issue viene chiusa. In caso di ulteriori problematiche si prega di aprire una issue dedicata.
