### ISSUE TITLE
[SC]: Errore in validazione u.c. 12221122 

### ISSUE THREAD

**Issue by elenadimartino** [italia/ansc#716]
### Ambiente

pre-produzione

### Servizio

R009 - Servizi cooperativi validazione evento

### idOperazione

1761038

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Milano Elena Di Martino

### Data del test (yyyy-mm-dd)

2024-02-23

### Descrivi il problema

Buongiorno, nel validare l'evento 12221122 con tipologia consenso consenso contestuale all'evento ci imabattiamo nell' errore che richiede l'atto di consenso madre, sezione che  in questo caso non si attiva. Questo è l'errore  :"errors":[{"code":"400003","severity":"E","text":"Il campo evento.consensoMadre.atto.idProvinciaRegistrazione nella sezione Atto Consenso Madre è obbligatorio"},{"code":"400003","severity":"E","text":"Il campo evento.consensoMadre.atto.siglaProvinciaRegistrazione nella sezione Atto Consenso Madre è obbligatorio"},{"code":"400003","severity":"E","text":"Il campo evento.consensoMadre.atto.idComuneRegistrazione nella sezione Atto Consenso Madre è obbligatorio"},{"code":"400003","severity":"E","text":"Il campo evento.consensoMadre.atto.nomeComuneRegistrazione nella sezione Atto Consenso Madre è obbligatorio"},{"code":"400003","severity":"E","text":"Il campo evento.consensoMadre.atto.idtipocontenuto nella sezione Atto Consenso Madre è obbligatorio"},{"code":"400003","severity":"E","text":"Il campo evento.consensoMadre.atto.numeroatto nella sezione Atto Consenso Madre è obbligatorio"}....

Nella web-app se proviamo la stessa tipologia di consenso, per questo usecase, abbiamo notato che nel payload nel consenso madre vengono passati dei dati atto lo stesso anche se non presente:{
	"consensoMadre": {
		"altroUfficiale": {},
		"atto": {
			"idtipocontenuto": "1",
			"tipologia": "1"
		},
		"sentenzaTribunale": {},
		"tipoConsenso": "1"
	}
}

**Comment by gbuemi** [comment]
Buongiorno,
abbiamo preso in carico la segnalazione.

Un saluto,
Supporto ANSC

**Comment by gbuemi** [comment]
Salve,
come specificato nella documentazione del caso d'uso https://github.com/italia/ansc/blob/93736bf11d0bf9661dfb5e6a1604283fac00a0db/docs/Mapping_casi_uso/riconoscimenti/Rico_004.csv#L238 alla riga 238 il campo evento.consensoMadre.tipoConsenso è sempre obbligatorio.

- Se evento.consensoMadre.tipoConsenso = 2 gli ulteriori campi dalla riga 171 alla riga 196 con obbligatorietà = SI sono obbligatori.

- Se evento.consensoMadre.tipoConsenso != 2  gli ulteriori campi dalla riga 171 alla riga 196 NON sono obbligatori. 

Quindi, per esempio, se da gestionale viene ricomposta la request da voi inviata aggiungendo la sezione 
`            "consensoMadre": {
            "tipoConsenso": "1"
        }`
l'evento viene validato correttamente, così come avviene da webapp. 

Inviando invece un tipoConsenso = 2 oppure omettendo questa sezione vengono richiesti gli ulteriori gli ulteriori campi obbligatori
`            "consensoMadre": {
            "tipoConsenso": "2"
        }`

A disposizione per ulteriori chiarimenti.

Un saluto,
Supporto ANSC
