### ISSUE TITLE
Integrazione dati caso d'uso 344000 (Sep_Div_004) - Accordo di modifica delle condizioni di separazione o divorzio

### ISSUE THREAD

**Issue by MarcoSalaPad** [italia/ansc#717]
### Ambiente

produzione

### Servizio

R009 - Servizi cooperativi validazione evento

### idOperazione

ASSENTE

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Lissone - Marco Sala

### Data del test (yyyy-mm-dd)

22/02/2024

### Descrivi il problema

Il caso d'uso specificato in oggetto, sia tramite web services che da web app, è stato impostato solo con i dati che prevedono un documento proveniente da un ente esterno al comune (il tribunale).

Tuttavia gli accordi per la modifica delle condizioni possono essere fatti dai coniugi sia a seguito di una separazione che di un divorzio.
Nell formula ministeriale 121 septies è scritto: “di essere legalmente separati o divorziati a seguito di…. (indicare il provvedimento che ha pronunciato la separazione o il divorzio con tutti i dati per identificarlo);”

La separazione o il divorzio al quale si riferisce l’accordo di modifica delle condizioni, può essere avvenuto con:
-	Provvedimento del Tribunale 
-	Accordo di separazione / divorzio innanzi all’ufficiale dello Stato Civile
-	Negoziazione assistita dagli avvocati e trascritta in comune

In base alla tipologia di separazione o divorzio la dicitura diventa la seguente:
1.	: “di essere legalmente separati o divorziati a seguito di Provvedimento del Tribunale di …. N. ….. in data ……
2.	: “di essere legalmente separati o divorziati a seguito di accordo concluso innanzi all’ufficiale dello Stato civile del Comune di …. in data …. di cui all’atto iscritto nei registri di matrimonio del Comune di …. al n. …. P. II S. C Anno ….. e confermato con dichiarazioni di cui all’atto n. ….. P. II S. C Anno …..
3.	: “di essere legalmente separati o divorziati a seguito di convenzione di negoziazione assistita in data …. di cui all’atto iscritto nei registri di matrimonio del Comune di …. al n. … P. II S. C Anno ….

Ad oggi per questo caso d'uso, come detto in precedenza, si può indicare solo un provvedimento dal tribunale e quindi la frase che viene riportata nella minuta della webapp è la numero 1 della sezione sopra.

Per questo motivo andrebbe previsto una scelta a monte della tipologia di separazione o divorzio come per i casi d’uso 342000 e 350000.
Quindi per questo caso d'uso andrebbero anche modificati i dati richiesti nel data model del caso d'uso 344000.

In attesa di un riscontro.
Grazie

**Comment by gbuemi** [comment]
Buongiorno,
abbiamo preso in carico la segnalazione.

Un saluto,
Supporto ANSC

**Comment by gbuemi** [comment]
Salve @MarcoSalaPad, 
vi comunichiamo che è stata segnalata la stessa problematica sul caso d'uso 350000 - Riconciliazione matrimonio in un comune diverso da quello di registrazione dell’atto, issue https://github.com/italia/ansc/issues/708 e che la questione verrà approfondita con gli esperti Anusca. Seguiranno aggiornamenti in merito.

Un saluto,
Supporto ANSC

**Comment by asqueglia** [comment]
Buongiorno con la versione 1.28.0 la segnalazione è stata corretta. Chiudiamo pertanto la issue
