### ISSUE TITLE
[SC]: conflitto variabile "nazioneEnte" in "model_evento.yaml"

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#719]
### Ambiente

pre-produzione, produzione

### Servizio

R009 - Servizi cooperativi validazione evento

### idOperazione

---

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

biadanpad

### Data del test (yyyy-mm-dd)

2024-02-26

### Descrivi il problema

La versione 1.24.0 del file "model_evento.yaml" contiene la definizione della variabile "nazioneEnte" sia nella classe "ModelEnteEstero" sia nella sua classe madre "ModelEnteDichiarante".

Questo genera un conflitto.

**Comment by biadanpad** [comment]
stessa cosa per la variabile "nomeNazioneEnte"

**Comment by asqueglia** [comment]
Buongiorno verifichiamo e le facciamo sapere

**Comment by asqueglia** [comment]
Buongiorno, appena la segnalazione verrà corretta comunicheremo il rilascio. Vi faremo sapere appena possibile

**Comment by biadanpad** [comment]
Buongiorno, 
avremmo bisogno di una stima dei tempi per la risoluzione del problema per poter pianificare i sviluppi

**Comment by asqueglia** [comment]
Buonasera, la segnalazione è stata corretta con la versione 1.25.0. La issue viene chiusa. In caso di ulteriori problematiche si prega di aprire una issue dedicata.

**Comment by biadanpad** [comment]
Buongioeno, 
idVersione rimane 100009? Lo chiedo perchè nel changelog non è riportata la release 1.25.0
