### ISSUE TITLE
Errore 400 nella R003

### ISSUE THREAD

**Issue by Sem98** [italia/ansc#720]
### Ambiente

pre-produzione

### Servizio

R003 - Servizi cooperativi comunicazioni

### idOperazione

1762463

### idEvento o idAnsc

 1998-1220263-724-052032

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

9493

### Data del test (yyyy-mm-dd)

2024/02/26

### Descrivi il problema

Nel momento in cui eseguo una R003 con il seguente payload:
{
	"ComunicazioneRequest": {
		"idAnsc": "1998-1220263-724-052032"
	},
	"testataRichiesta": {
		"versioneApplicativo": "1.0.0",
		"idOperazioneComune": "6954",
		"idComune": 9493,
		"dataOraRichiesta": "2024-02-26T14:56:34.997",
		"nomeApplicativo": "SIDe",
		"fornitoreApplicativo": "SistemiInformativi"
	}
}

ottengo l'errore:

Response code: 400
Response payload: {"testataRisposta":{"idComune":9493,"idOperazioneComune":"6954","idOperazione":"1762463","idEsito":1},"errors":[{"code":"400001","severity":"E","text":"IdAnsc non valido..."}]}

Abbiamo testato anche inserendo con il solo idEvento "1220263" ma il risultato è il medesimo.

**Comment by asqueglia** [comment]
Buongiorno, il payload da voi trasmesso ci sembra non corretto.
Potete riprovare seguendo il payload di esempio fornito di seguito (sostituendo le variabili come più opportuno). Restiamo in attesa i un vostro riscontro.

{
  "testataRichiesta": {
        "idComune": {{idComune}},
        "idOperazioneComune": "APP2022032210000",
        "dataOraRichiesta": "{{dataOraRichiesta}}",
        "nomeApplicativo": "{{nomeApplicativo}}",
        "versioneApplicativo": "{{versioneApplicativo}}",
        "fornitoreApplicativo": "{{fornitoreApplicativo}}"
  },
  "idAnsc": "{{idAnscTestFlusso01}}"
}

**Comment by Sem98** [comment]
Confermo con modificando il payload la R003 funziona correttamente. Grazie
