### ISSUE TITLE
[SC]: indicazioni caso d'uso Citt_005 - Citt_006 - Citt_028 - Citt_029

### ISSUE THREAD

**Issue by antonioluberto** [italia/ansc#723]
### Ambiente

produzione

### Servizio

R009 - Servizi cooperativi validazione evento

### idOperazione

assente

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Grottaferrata

### Descrivi il problema

I casi d'uso in oggetto fanno riferimento all'acquisto della cittadinanza italiana a seguito di servizio militare prestato nelle Forze Armate italiane. Questa possibilità parrebbe in effetti esser venuta meno : la legge 23 agosto 2004, n.226 ha stabilito la sospensione anticipata dall' 1 gennaio 2005 del servizio di leva obbligatoria ed ha dettato la nuova disciplina dei volontari di truppa in ferma prefissata. In particolare, il reclutamento dei volontari può riguardare solo persone che siano in possesso della cittadinanza italiana (art. 4 della citata legge).

Richiediamo pertanto una verifica da parte vostra sull'effettiva necessità di gestire il caso d'uso in questione.

**Comment by rvinzani** [comment]
Salve, faremo una verifica con gli esperti Anusca e le risponderemo appena possibile

**Comment by asqueglia** [comment]
Buonasera, da un confronto con ANUSCA comunichiamo quanto segue.

La legge sulla cittadinanza non è stata cambiata per cui anche se in disaccordo con l’articolo indicato non è possibile eliminare la casistica prevista dalla normativa.
Sicuramente è una casistica non utilizzata al momento, ma se dovesse cambiare la legge potrebbe diventare nuovamente lecita.

**Comment by asqueglia** [comment]
Chiudiamo la issue in caso di uklteiori chiarimenti si prega di aprirne una altra dedicata
