### ISSUE TITLE
[SC]: [R009] per Sep_Div_006 - controllo errato su siglaProvinciaEnte dell'Autorità mittente.

### ISSUE THREAD

**Issue by gcuci** [italia/ansc#728]
### Ambiente

pre-produzione

### Servizio

R009 - Servizi cooperativi validazione evento

### idOperazione

1763466

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Bagnacavallo

### Data del test (yyyy-mm-dd)

2024-02-27

### Descrivi il problema

buongiorno,

segnaliamo che in fase di validazione del caso d'uso Sep_Div_006, se viene valorizzato il campo 'siglaProvinciaEnte' dell'Autorità mittente, con una stringa coerente, il servizio restituisce un'anomalia di non corrispondenza al pattern ^[0-9]*$.

In attesa di riscontro,

cordiali saluti.

**Comment by gbuemi** [comment]
Buonasera,
vi comunichiamo che la segnalazione è stata presa in carico.

Un saluto,
Supporto ANSC

**Comment by asqueglia** [comment]
Buonasera, la segnalazione è stata corretta con la versione 1.25.0. La issue viene chiusa. In caso di ulteriori problematiche si prega di aprire una issue dedicata.
