### ISSUE TITLE
R012 firma dichiarante elettronica invio email

### ISSUE THREAD

**Issue by MichelaGarzoni** [italia/ansc#73]
Buongiorno,
ho provato con diversi atti ma ottengo sempre la stessa risposta e non riesco ad individuare l'errore che mi viene segnalato. L'atto è validato e ho un idAnsc ed un idEvento abbinato. Il json inviato al servizio è il seguente ed è analogo all'esempio da voi fornito, dove nella sezione "firmatario" indico solamente il nome ed il cognome del soggetto e non tutti i campi relativi al model soggetto:

{
"testataRichiesta":{
"idComune":3655
,"idOperazioneComune":"5"
,"dataOraRichiesta":"2023-04-19T09:58:01Z"
,"nomeApplicativo":"ASCOT Stato Civile"
,"versioneApplicativo":"21.99.0000"
,"fornitoreApplicativo":"Insiel S.p.A"
}
,"emailDichiarante":"michela.garzoni@insiel.it"
,"idEvento":"4244848"
,"idAnsc":"2023-4244848-20230050000011-032001"
,"firmatario":{
"nome":"XXX-NomeComparente"
,"cognome":"YYY-CognomeComparente"
}
}

ed ottengo sempre la risposta:
{
    "errors": [
        {
            "code": "400003",
            "severity": "E",
            "text": "Dati in ingresso non corretti"
        }
    ],
    "esito": {
        "codice": "400003",
        "descrizione": "Dati in ingresso non corretti"
    },
    "testataRisposta": {
        "idComune": 3655,
        "idEsito": 1,
        "idOperazioneComune": "5"
    }
}

ma tra i dati inviati io non vedo dati non corretti.
Mi sapete indicare quale sia il dato non corretto che mi viene segnalato?
Grazie

**Comment by amusarra** [comment]
Salve @MichelaGarzoni l'ambiente che sta utilizzando è validazione e non pre-produzione. La invitiamo a usare l'ambiente di pre-produzione per l'integrazione con il gestionale e i servizi cooperativi. Dovrebbe quindi eseguire il test in ambiente di pre-produzione e nel caso dovesse ottenere lo stesso errore, vedremo d'indagare.


A seguire un esempio di richiesta e risposta eseguita in ambiente di pre-produzione.

```
{
    "testataRichiesta": {
        "idComune": 580,
        "idOperazioneComune": "APP2022032210000",
        "dataOraRichiesta": "2022-08-09",
        "nomeApplicativo": "CLIENT-ANSC",
        "versioneApplicativo": "1.3.0",
        "fornitoreApplicativo": "SOGEI"
    },
    "emailDichiarante": "email@email.it",
    "idEvento": "951278",
    "idAnsc": "2023-951278-4323432-016017",
    "firmatario": {
        "nome": "Antonio",
        "cognome": "Musarra"
    }
}
```
Payload 1 - Richiesta Firma dichiarante per presa visione

```
{
    "esito": {
        "codice": "200",
        "descrizione": "Ok"
    },
    "testataRisposta": {
        "idComune": 580,
        "idEsito": 0,
        "idOperazioneComune": "APP2022032210000"
    },
    "idPresaVisione": "1863051"
}

```
Payload 2 - Risposta del servizio di Firma per Presa Visione

Cordiali Saluti.
Supporto ANSC

**Comment by amusarra** [comment]
Salve @MichelaGarzoni abbiamo appena verificato in ambiente di pre-produzione che il problema si verifica nel caso d'uso specifico. Prediamo questa issue come BUG.

Cordiali Saluti.
Supporto ANSC.

**Comment by asqueglia** [comment]
Buongiorno è stata rilasciata la versione 1.7.0 che corregge la segnalzione in oggetto.
