### ISSUE TITLE
[SC]: Controlli obbligatorietà caso d'uso 12999999 - Rico_999

### ISSUE THREAD

**Issue by siscomanpr** [italia/ansc#730]
### Ambiente

pre-produzione, produzione

### Servizio

R009 - Servizi cooperativi validazione evento

### idOperazione

1764442

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Serravalle Sesia

### Descrivi il problema

Per il caso d'uso in oggetto vengono richiesti obbligatori i campi della data di nascita e del comune di nascita dell'intestatario. Essendo un caso d'uso di servizio, potrebbe capitare che sia necessario usare questa casistica per i riconoscimenti precedenti alla nascita. Per questo motivo riteniamo che data di nascita e comune di nascita non debbano essere obbligatori.

**Comment by gbuemi** [comment]
Buongiorno,
abbiamo preso in carico la segnalazione.

Un saluto,
Supporto ANSC

**Comment by siscomanpr** [comment]
Siamo consapevoli che è più corretto usare i casi d'uso specifici, ma ci sono alcuni nostri clienti che stanno facendo i test per accedere alla fase di adozione controllata e devono testare anche i casi d'uso di servizio. Da qui è stato rilevato il problema...

Inoltre, visto che i casi d'uso di servizio esistono anche per bypassare eventuali problemi sul caso d'uso specifico, riteniamo che debba essere affrontato il problema per ovviare a eventuali problemi futuri.
