### ISSUE TITLE
[SC]: firma ufficiale stato civile

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#733]
### Ambiente

pre-produzione

### Servizio

R007 - Servizi cooperativi firma ufficiale di stato civile

### idOperazione

1765652

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

ponsacco, anna maraspin

### Data del test (yyyy-mm-dd)

28.02.2024

### Descrivi il problema

Buonasera,
al momento della firma ufficiale stato civile mi ritorna l'errore
406011 - L'evento non pu� essere firmato, l'atto necessita della firma di uno o pi� dichiaranti.

Senza fare nulla altro, ritento ad inviare la firma dell'ufficiale: esito positivo

Oggi ho provato su 2 atti ed entrambi con lo stesso problema.

**Comment by gbuemi** [comment]
Buongiorno,
abbiamo preso in carico la segnalazione.

Un saluto,
Supporto ANSC

**Comment by gbuemi** [comment]
Buongiorno @annamaraspin,
la questione nasce dal fatto che lo stato dell'evento, dopo la firma del dichiarante, viene aggiornato in modo asincrono (in alcuni casi d'uso sono necessarie più firme dei dichiaranti).
 
Pertanto, come risulta dal nostro sistema, il tempo trascorso tra la firma dichiarante ed il primo tentativo di firma usc è stato troppo breve:
 
- 15:03:50 - firma dichiarante OK 
- 15:04:16 - firma usc KO 
- 15:04:19 - aggiornamento asincrono stato evento 
- 15:04:58 - firma usc OK 

Alle 15:04:20 l'evento poteva essere firmato dall'usc senza problemi.

Grazie e saluti,
Supporto ANSC
