### ISSUE TITLE
[SC]: Caso d'uso Dic_Nasc_999 - richiesta di aggiunta di un soggetto dichiarante facoltativo.

### ISSUE THREAD

**Issue by gcuci** [italia/ansc#734]
### Ambiente

pre-produzione

### Servizio

R009 - Servizi cooperativi validazione evento

### idOperazione

assente

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Bagnacavallo

### Descrivi il problema

buongiorno,

chiediamo se fosse possibile aggiungere al mapping del Dic_Nasc_999 - Caso d'uso di servizio (dichiarazioni nascita), il soggetto dichiarante facoltativo.

Questo ci permetterebbe di poter utilizzare (almeno per questa prima fase), il caso d'uso di servizio, per gestire alcuni dei casi d'uso di nascita, per i quali il dichiarante è diverso da padre, madre o entrambi.
Le dichiarazioni di nascita con questa caratteristica sono diverse, e non potendo utilizzare il caso d'uso di servizio (in quanto non inserendo le informazioni del dichiarante, non è possibile acquisirne la firma), saremmo costretti a gestire tutti i casi specifici.

L'aggiunta del soggetto dichiarante, viceversa, ci permetterebbe di gestire da subito tutti questi casi, per implementare comunque la gestione dei casi specifici, in successivi aggiornamenti.

 
In attesa di riscontro,

cordiali saluti.

**Comment by gbuemi** [comment]
Buongiorno,
abbiamo preso in carico la segnalazione.

Un saluto,
Supporto ANSC

**Comment by asqueglia** [comment]
Buonasera, con il rilascio della versione 1.26.0 è stata corretta la segnalazione. Si prega di far riferimento al changelog per i dettagli
