### ISSUE TITLE
[SC]: usecase matr_999_2

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#739]
### Ambiente

pre-produzione

### Servizio

R009 - Servizi cooperativi validazione evento

### idOperazione

1767501

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

ponsacco, anna maraspin

### Data del test (yyyy-mm-dd)

01.03.2024

### Descrivi il problema

Stavo provando la modifica sul numero testimoni a zero apportata nella versione 1.25
Continua l'errore
400003 - Il campo evento.datiEventoMatrimonio.numeroTestimoni nella sezione Dettagli evento non corrisponde al pattern ^[2-4]$

**Comment by asqueglia** [comment]
Buongiorno , verifichiamo e le facciamo sapere

**Comment by asqueglia** [comment]
Abbiamo verificato che l'intervento è stato eseguito circoscrivendolo al caso d'uso di servizio matr_999_2 (riti religiosi), che ha id 329999, come richiesto nella precedente issue; 
il caso d'uso relativo all'operazione indicata nella presente issue è il 319999 matr_999_1 riti civili. Appena possibile estenderemo l'intervento anche a questa casistica

**Comment by asqueglia** [comment]
Buonasera, con il rilascio della versione 1.26.0 è stata corretta la segnalazione. Si prega di far riferimento al changelog per i dettagli
