### ISSUE TITLE
[R009] Errore allegato obbligatorio mancante (Procura)

### ISSUE THREAD

**Issue by siscomanpr** [italia/ansc#74]
Come già segnalato nella issue https://github.com/italia/ansc/issues/32, continuiamo a ricevere l'errore di allegato obbligatorio mancante anche per i seguenti casi d'uso: 11114000 e 11114100

Ambiente = preproduzione
idOperazione = 1582096

**Comment by asqueglia** [comment]
Buongiorno, verifichiamo la problematica e facciamo sapere non appena possibile

**Comment by asqueglia** [comment]
Buongiorno è stata rilasciata la versione 1.7.0 che corregge la segnalazione in oggetto.
