### ISSUE TITLE
[SC]: Consultazione Intestatario soggetto estero richiede comune o provincia di nascita

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#744]
### Ambiente

produzione

### Servizio

R005 - Servizi cooperativi consultazione

### idOperazione

46490

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Lissone - biadanpad

### Data del test (yyyy-mm-dd)

2024-03-01

### Descrivi il problema

In caso di soggetto nato all'estero viene erroneamente richiesto di specificare il comune o la provincia di nascita.

Questo problema blocca il lavoro dei comuni.

### Payload (json)

```JSON
REQUEST:
{
  "criteriRicercaSoggetto": {
    "cognome": "XXXX",
    "nome": "XXXX",
    "sesso": "X",
    "codiceStatoNascita": "156",
    "nomeStatoNascita": "SENEGAL",
    "datanascita": "XXXX-XX-XX"
  },
  "testataRichiesta": {
    "idComune": 5000,
    "idOperazioneComune": "8350",
    "dataOraRichiesta": "2024-03-01T12:12:18.361+01:00",
    "nomeApplicativo": "urbi",
    "versioneApplicativo": "1.1.5",
    "fornitoreApplicativo": "padigitale"
  }
}

RESPONSE:
{
  "testataRisposta": {
    "idComune": 5000,
    "idOperazioneComune": "8350",
    "idOperazione": "46490",
    "idEsito": 1
  },
  "datiPaginazione": {
    "numPagina": 1,
    "numRecordPagina": 30,
    "numRecordTotali": 0
  },
  "errors": [
    {
      "code": "400001",
      "severity": "E",
      "text": "Bisogna inserire il Nome del comune di nascita o la Sigla della provincia di nascita"
    }
  ],
  "infos": [
    {
      "code": "110527",
      "severity": "I",
      "text": "Informazioni sull'operazione da fornire in caso di assistenza : data:2024-03-01 11:12:20 , idOperazione:46490"
    }
  ]
}
```

**Comment by gbuemi** [comment]
Buongiorno,
abbiamo preso in carico la segnalazione.

Un saluto,
Supporto ANSC

**Comment by biadanpad** [comment]
Ci sono notizie in merito?
Vi ricordo che questo problema (che nelle versioni precedenti non si manifestava) blocca il normale lavoro dei comuni.

**Comment by MarcoSalaPad** [comment]
Buongiorno

il comune di Lissone ci ha nuovamente segnalato di essere bloccato con un ennesimo atto, (è almeno il terzo) perchè l'intestatario è nato all'estero. 
E' veramente urgente risolvere la situazione.

**Comment by gbuemi** [comment]
Buongiorno @MarcoSalaPad,
il messaggio è stato recepito. La fix è stata effettuata e siamo in fase di test.
Seguiranno aggiornamenti.

Un saluto
Supporto ANSC

**Comment by mttfranci** [comment]
@MarcoSalaPad  abbiamo appena rilasciato la fix, potreste cortesemente riprovare?

Grazie in anticipo.

**Comment by biadanpad** [comment]
Buongiorno, 
il comune ha riprovato, ma riscontriamo ancora problemi: il messaggio di errore non compare più, ma il sistema ci risponde con un soggetto con id=null (così come datains e dataultimoagg).

Questo soggetto sembra essere presente nella banca dati ANSC, dato che in risposta ricevo anche il codice fiscale e la data di nascita.

REQUEST:
{
  "criteriRicercaSoggetto": {
    "cognome": "XXXX",
    "nome": "YYYY",
    "sesso": "M",
    "codiceStatoNascita": "156",
    "nomeStatoNascita": "SENEGAL",
    "datanascita": "1960-01-10"
  },
  "testataRichiesta": {
    "idComune": 5000,
    "idOperazioneComune": "8350",
    "dataOraRichiesta": "2024-03-06T08:48:17.762+01:00",
    "nomeApplicativo": "urbi",
    "versioneApplicativo": "1.1.5",
    "fornitoreApplicativo": "padigitale"
  }
}

RESPONSE:
{
  "testataRisposta": {
    "idComune": 5000,
    "idOperazioneComune": "8350",
    "idOperazione": "47805",
    "idEsito": 0
  },
  "datiPaginazione": {
    "numPagina": 1,
    "numRecordPagina": 30,
    "numRecordTotali": 0
  },
  "infos": [
    {
      "code": "110527",
      "severity": "I",
      "text": "Informazioni sull'operazione da fornire in caso di assistenza : data:2024-03-06 07:48:21 , idOperazione:47805"
    }
  ],
  "soggetti": [
    {
      "id": null,
      "cognome": "XXXX",
      "nome": "YYYY",
      "sesso": "M",
      "datains": null,
      "dataultimoagg": null,
      "codiceFiscale": "CFCFCFCFCFCFCFCF",
      "idStatoNascita": "156",
      "idComuneResidenza": 5000,
      "nomeStatoNascita": "SENEGAL",
      "idProvinciaResidenza": 108,
      "dataNascita": "YYYY-MM-DDT00:00:00.000+00:00",
      "idStatoResidenza": "90"
    }
  ]
}

**Comment by mttfranci** [comment]
@biadanpad buongiorno, 

Adesso il comportamento appare corretto.

I campi indicati non sono valorizzati perchè il soggetto non è presente in ANSC, ma solo in ANPR.
In questo caso viene restituita l'anagrafica come presente su ANPR ma senza ovviamente alcune informazioni (per questo sono null id e data di inserimento / aggiornamento in ANSC).

Saluti

Assistenza ANSC

**Comment by biadanpad** [comment]
Buongiorno, 
il servizio in questione è quello di CONSULTAZIONE ANSC INTESTATARIO, pertanto mi aspetteri in risposta solo soggetti presenti in banca dati ANSC.
Inoltre, se il soggetto è presente in ANPR, perchè non ne vedo il relativo id?

**Comment by mttfranci** [comment]
@biadanpad l'anomalia, che era effettivamente presente ed è stata corretta, era quello che impediva di cercare un intestatario nato all'estero. 
L'idea del servizio è quella di fornire le generalità più aggiornate possibile (da ANSC quando presenti, altrimenti da ANPR) da usare per la sezione intestatario della registrazione degli atti.

Cercheremo di integrare meglio la documentazione del servizio, comunque potete aspettarvi che il risultato sia il seguente 
- soggetto non trovato : per i criteri indicatino è presente nessun soggetto nè in ANPR nè in ANSC
- soggetto trovato ma id non presente : il soggetto è presente in ANPR con le generalità indicate
- soggetto trovato con id presente : il soggetot è già censito anche in ANSC.

Per l'id anpr del soggetto stiamo valutando se inserirlo nella risposta.

Chiarito questo comportamento, quale è la situazione che comporta un blocco per voi?

Saluti 

Assistenza ANSC

**Comment by biadanpad** [comment]
Il blocco era dovuto al fatto che una risposta di questo genere (dati del soggetto provenienti da ANPR, con id ANSC = null) non era mai stata riscontrata e di conseguenza non contemplata dal nostro applicativo. Presumo quindi che sia una novità introdotta nelle ultime release.
 
Questo evidenzia ancora una volta quanto la mancanza di documentazione sia fonte di dubbi e problematiche.
 
Il continuo evolvere delle API, inoltre, sta causando non pochi problemi di integrazione.
Sarebbe auspicabile minimizzare gli interventi sui servizi già in uso e soprattutto sapere in anticipo quali saranno le modifiche in tal senso prima che vengano pubblicate.
 
Alla luce di quanto appena spiegato, abbiamo provveduto a modificare il nostro applicativo in modo da interpretare correttamente i dati ricevuti.

**Comment by mttfranci** [comment]
@biadanpad abbiamo aggiornato la documentazione della consultazione intestatario.

https://github.com/italia/ansc/blob/v1.25.2/docs/openapi/R005_consultazione_ansc.yaml

Saluti

Assistenza ANSC

**Comment by BiancaTre** [comment]
Buongiorno.
Nella stesura dell'atto di morte ANSC di un soggetto nato nell'attuale Comune "Cortaccia sulla strada del vino" ma che alla data evento nascita (ossia 24/12/1944) era Cortaccia - Trento compare il seguente messaggio:
Non è stato possibile reperire l'id ANPR della provincia per il comune di CORTACCIA con la data 1944-12-24. Impossibile proseguire
Nel 1948 Cortaccia è passato dalla provincia di Trento alla provincia di Bolzano. In ANPR la persona è correttamente indicata come nata a Cortaccia (TN). E' un problema di nostro gestionale oppure le tabelle di decodifica ANPR per questo Comune (che ha prima cambiato provincia e poi denominazione) presentano qualche errore?
