### ISSUE TITLE
[SC]: [R009] Matrimoni con Rito Civile - nazionalità dei testimoni non disponibile.

### ISSUE THREAD

**Issue by gcuci** [italia/ansc#750]
### Ambiente

pre-produzione

### Servizio

R009 - Servizi cooperativi validazione evento

### idOperazione

assente

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Firenze

### Descrivi il problema

buonasera,

per i casi d'uso di Matrimonio con Rito Civile, per i quali è prevista la presenza dei testimoni, non sempre l'informazione sulla nazionalità di questi ultimi, è disponibile.

Per questi casi, però, compreso quello di servizio (Matr_999_1), i campi 'idNazionalita', e 'nazionalita', dei testimoni presenti, sono obbligatori.

Chiediamo di rendere facoltative queste informazioni, altrimenti non possiamo validare gli eventi, per queste situazioni.

In attesa di riscontro,

cordiali saluti.

**Comment by asqueglia** [comment]
Verifichiamo e le facciamo sapere

**Comment by asqueglia** [comment]
Buonasera, con il rilascio della versione 1.26.0 è stata corretta la segnalazione. Si prega di far riferimento al changelog per i dettagli
