### ISSUE TITLE
[SC]: Carattere di tabulazione in testo annotazione automatica

### ISSUE THREAD

**Issue by siscomanpr** [italia/ansc#751]
### Ambiente

pre-produzione

### Servizio

R005 - Servizi cooperativi consultazione

### idOperazione

1770075

### idEvento o idAnsc

2024-1222332-00000-002137

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Serravalle Sesia

### Data del test (yyyy-mm-dd)

05/03/2024

### Descrivi il problema

Consultando la notifica di annotazione automatica con id 2024-1222332-00000-002137, rileviamo che il testo dell'annotazione proposto contiene un carattere di tabulazione dopo la dicitura "Con decreto". 
Nello specifico si tratta di un'annotazione automatica in seguito ad una trascrizione di decreto prefettizio di cambio cognome/nome (codice caso uso 1331). Se vi serve anche l'idANSC dell'atto che ha scatenato l'evento è: 2024-1222331-10-002137.
Potete sostituire questa tabulazione con uno spazio?

Siscom SPA

**Comment by asqueglia** [comment]
Buongiorno, verifichiamo e le facciamo sapere
