### ISSUE TITLE
RILASCIO CERTIFICAZIONI ANSC [webapp]: 

### ISSUE THREAD

**Issue by StatoCivileLissone** [italia/ansc#753]
### Ambiente

produzione

### Provenienza segnalazione

Comune

### Riferimenti operatore/comune

LISSONE

### Descrivi il problema

In base alla normativa vigente, sulle certificazioni da produrre a soggetti privati deve essere apposta, a pena di nullità, una delle seguenti diciture:
1) Il presente certificato non può essere prodotto agli organi della pubblica amministrazione o ai privati gestori di pubblici servizi (DICITURA GIA’ PREVISTA SULLA WEBAPP)
2) Ai sensi dell’art. 40, DPR 28/12/2000 N. 445, il presente certificato è rilasciato solo per l’estero (DICITURA GIA’ PREVISTA SULLA WEBAPP)
3) Certificato rilasciato per i procedimenti disciplinati da norme sull’immigrazione
4) Rilasciato ai fini dell'acquisizione d'ufficio

Le diciture n.3 e 4 non sono ancora previste in fase di certificazioni su Webapp.

Rif. Legge: 
Art. 15 Legge 12/11/2011 n. 183 (ex Art. 43 comma 5 del d.P.R. 28 dicembre 2000, n.445)
Circolare Presidenza Consiglio dei Ministri – Direttiva 14/2011
Circolare Ministro per la Pubblica Amministrazione e la Semplificazione N. 3/2012 e N. 5/2012

**Comment by asqueglia** [comment]
Buongiorno in merito alle diciture previste sui certificati, faremo un ulteriore approfondimento con ANUSCA con cui abbiamo sempre condiviso quanto finora presente.

**Comment by asqueglia** [comment]
Buongiorno, con la versione 1.30.0 rilasciata ieri 01/07/2024, sono stati adeguati i possibili usi e conseguenti diciture su certificati ed estratti, secondo quanto condiviso con gli esperti ANSUCA. Chiudiamo pertanto la issue.
