### ISSUE TITLE
[SC]: Cancellazione Atto Servizio R011

### ISSUE THREAD

**Issue by KibMcris** [italia/ansc#756]
### Ambiente

pre-produzione

### Servizio

R010 - Servizi cooperativi anteprima, R011 - Servizi cooperativi per la cancellazione logica di un atto

### idOperazione

1771451

### idEvento o idAnsc

2024-1222618-60-102044

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Tropea

### Data del test (yyyy-mm-dd)

07-03-2024

### Descrivi il problema

Con IdOperazione=1771449 abbiamo validato il processo verbale delle firme relative all'atto 2024-1222618-60-102044.  Sia nella risposta che da WebApp vediamo correttamente l'atto nello stato= FIRMATO DAL DICHIARANTE. Successivamente abbiamo testato la cancellazione dell'atto con servizio R011 andata a buon fine. Si veda idOperazione=1771451.
Come specificato nella issue #489 e come previsto dal rilascio della versione 1.23.0, ci aspettavamo che l'atto non fosse cancellato logicamente ma fosse consultabile in uno stato ANNULLATO. Consultando la WebApp inserendo come criterio di ricerca Stato=ANNULLATO, l'atto NON risulta consultabile. Confermo invece che da servizio cooperativo R010 riusciamo a visualizzarlo.

Allo stesso tempo abbiamo notato che un atto cancellato in stato="CONFERMATO", correttamente viene cancellato logicamente e non risulta consultabile da WEBAPP come specificato nella issue #489. Richiamando con servizio R010 l'anteprima dell'atto appena cancellato, ANSC risponde con il PDF dell'atto. Si veda in questo caso l'atto idAnsc 2024-1222557-57-102044.

Restiamo in attesa di riscontro

**Comment by amusarra** [comment]
Salve @KibMcris 
Abbiamo preso in carico la segnalazione.

Cordiali Saluti.
Supporto ANSC.

**Comment by amusarra** [comment]
Buongiorno @KibMcris 
Il comportamento as-is prevede che gli atti vadano in `STATO=ANNULLATO` nei soli casi in cui per essi siano stati emessi provvedimenti di rettifica. In caso contrario, è previsto lo `STATO=CANCELLATO`.

Con il prossimo rilascio, è stata tuttavia apportata una modifica al software finalizzata a inibire la possibilità di visualizzare in PDF gli eventi nello stato in questione.

Cordiali Saluti.
Supporto ANSC.
