### ISSUE TITLE
Trascrizione nascita da ospedale

### ISSUE THREAD

**Issue by siscomanpr** [italia/ansc#76]
Il problema segnalato con la issue https://github.com/italia/ansc/issues/64 non ci risulta risolto.
Nell'ultimo changelog della versione 1.6.2, avete indicato che è stato risolto per la web application, ma anche da lì non vediamo cambiamenti.
Nel file di Mapping Trascr_022 (che non risulta modificato con la nuova versione 1.6.2), richiedete sempre l'oggetto `evento.trascrizioneNascita.atto.enteEstero`. Cosa che ci sembrava strana visto che la direzione sanitaria può solo essere un ente italiano. Quindi vorremmo la conferma se dobbiamo popolare l'oggetto enteEstero comunque con nome stato Italia, o se è un refuso nelle specifiche.
Inoltre sulla web application abbiamo notato che, nella sezione "Atto da trascrivere" ci permette di selezionare anche uno stato estero dell'ente.

**Comment by asqueglia** [comment]
Buongiorno, si confermiamo che va valorizzato l'enteEstero con nome stato Italia e indicando nel nome ente l'ospedale o la direzione sanitaria in cui è avvenuto il parto.

**Comment by siscomanpr** [comment]
Va bene, grazie.

**Comment by asqueglia** [comment]
La issue viene chiusa nel caso si prega di riaprirla
