### ISSUE TITLE
Annotazioni: anomalia a seguito di aggiornamento modellazione

### ISSUE THREAD

**Issue by antonioluberto** [italia/ansc#761]
### Ambiente

pre-produzione, produzione

### Servizio

R013 - Servizi cooperativi per la validazione della rettifica

### idOperazione

1774118

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Grottaferrata

### Descrivi il problema

Con la release 
![image](https://github.com/italia/ansc/assets/26415430/a2a4f6c7-7cd6-47c8-9f58-8583f863ad60)

l'oggetto "ModelSeparazione" è stato integrato con la gestione di:

tipoSeparazioneDivorzio
assegnoMantenimento
datiAssegnoMantenimento

Se oggi si prova ad inserire un annotazione su un atto di matrimonio inviato (correttamente) in ANSC con una versione di servizi/modellazione antecedente alla 1.22, l'apposizione dell'annotazione medesima fallisce.

Si veda, in ambiente di pre-produzione, "idOperazione":"1774118"

**Comment by gbuemi** [comment]
Buonasera @antonioluberto,
abbiamo preso in carico la segnalazione.

Un saluto,
Supporto ANSC
