### ISSUE TITLE
[SC]: annotazione automatica non generata

### ISSUE THREAD

**Issue by COlivatoADS** [italia/ansc#763]
### Ambiente

pre-produzione

### Servizio

R002 - Servizi cooperativi certificazioni

### idOperazione

assente

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Faenza

### Data del test (yyyy-mm-dd)

2024-03-13

### Descrivi il problema

non capiamo come mai non venga registrata annotazione automatica su atto di nascita (digitale) in seguito a registrazione di matrimonio (trascrizione da estero).

l'iter testato è il seguente:
1. atto di nascita - trascrizione da estero (idAttoAnsc: 2024-1223169-75-039010 - cdu 1399)
il soggetto intestatario dell'atto acquisisce idSoggettoAnsc: 2273008

2. atto di matrimonio - trascrizione da estero (idAttoAnsc: 2024-1223170-80-039010 - cdu  331000)
nei dati della sposa viene passato l'idSoggettoAnsc che collega il soggetto al suo atto di nascita.

eseguendo richiesta di estratto sull'atto di nascita non compare l'annotazione di matrimonio
scaricando la lista della notifiche, l'annotazione di matrimonio sull'atto di nascita viene recepita come "( da inviare via PEC ) "

siamo sicuri che questo flusso abbia sempre funzionato.
un elemento che può essere utile per l'analisi del problema, è che l'atto di nascita è stato registrato con caso d'uso di servizio invece che con caso d'uso specifico di trascrizione da estero.
ma questo non ci risulta possa rappresentare un problema nella registrazione successiva dell'annotazione.

potete verificare e farci sapere?

grazie

**Comment by AMonopoliADS** [comment]
abbiamo controllato l'atto registrato su web-app, per il quale abbiamo segnalato in call che a parità di condizioni, l'annotazione sull'atto di primario è stata registrata in automatico.

l'atto di nascita è quello con idAnsc: 2024‐1223142‐10052‐039010

notiamo questa differenza che probabilmente giustifica la differenza di gestione:
- l'atto da web-service è stato registrato con il cdu 1399 - Caso d'uso di servizio trascrizioni nascita
- l'atto su web-app è stato registrato con il cdu 11999999 - Caso d'uso di servizio (dichiarazioni nascita) 
(ma sempre caso d'uso di servizio)

**Comment by rvinzani** [comment]
Abbiamo preso in carico il problema. Le faremo sapere appena possibile.

**Comment by rvinzani** [comment]
Buongiorno, non è stata generata automaticamente l'annotazione a seguito dell'utilizzo del caso d'uso di servizio per trascrizione perchè il sistema non può sapere se tale caso d'uso di servizio sia stato utilizzato per formare un atto di nascita proprio perchè si tratta di trascrizione generica. E' necessario quindi in questo caso procedere con l'annotazione manuale sull'atto sempre tramite caso d'uso di servizio.
Chiudiamo la issue. Se sono necessari ulteriori chiarimenti vi preghiamo di aprire una nuova issue con riferimento a questa stessa
