### ISSUE TITLE
COMUNICAZIONI/ANNOTAZIONI AUTOMATICHE PER CASO D'USO 350000 RICONCILIAZIONE [webapp]: 

### ISSUE THREAD

**Issue by StatoCivileLissone** [italia/ansc#766]
### Ambiente

produzione

### Provenienza segnalazione

Comune

### Riferimenti operatore/comune

LISSONE

### Data del test (yyyy-mm-dd)

2024-03-13

### Caso d'uso

350000

### Descrivi il problema

CASO D’USO 350000 RICONCILIAZIONE

Annotazione riconciliazione per atto di matrimonio generata da ANSC:
Con dichiarazione resa dinanzi a MARGHERITA CITTERIO in data 22/07/2006 iscritta nei registri di matrimonio del Comune di LISSONE anno 2006 n.19, i coniugi separati hanno manifestato di essersi riconciliati in data 06/01/2024.

Occorre variare i campi come segue:
da: MARGHERITA CITTERIO -> a: Ufficiale dello Stato Civile del Comune di Lissone
da: 22/07/2006 (data del matrimonio) ->   a: 13.03.2024 (data dichiarazione resa all’USC)
da: ANNO 2006 N. 19 (riferimento trascrizione atto di matrimonio) ->  a: al n. 2024-6589-44-108028 (atto registrazione della riconciliazione)

Comunicazione a ufficio anagrafe:
NON DEVONO ESSERE GENERATE COMUNICAZIONI PER UFFICIO ANAGRAFE PER QUESTO CASO D’USO

**Comment by gbuemi** [comment]
@StatoCivileLissone, per l'intervento dal centro assistenza, vi chiediamo per favore di inviare un PEC all'indirizzo email assistenza.ansc@sogei.it con tutte indicazioni del caso.

Grazie,
Supporto ANSC
