### ISSUE TITLE
[SC]: Impossibilità implementazione versione API (1.26.0) - campi non più presenti su classe AllegatoOutput

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#769]
### Ambiente

produzione

### Servizio

R001 - Servizi cooperativi allegati

### idOperazione

-

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

biadanpad

### Data del test (yyyy-mm-dd)

2024-03-15

### Descrivi il problema

Dopo aver aggiornato le API alla versione ultima (1.26.0), la classe AllegatoOutput non contiene più le variabili idAllegato, statoAllegato, idDocumentum, tipoAllegato, hash, codice, descrizione e tipologia (alcune sembra siano state spostate sulla class ModelAllegatoRif), ma il servizio R001 non è stato aggiornato e fa ancora riferimento al vecchio AllegatoOutput.

Risulta pertanto impossibile implementare la nuova versione delle API

**Comment by gbuemi** [comment]
Salve @biadanpad,
vi comunichiamo che l'R001 non è stato modificato con l'ultima release. La questione nasce dal fatto che è stata rilasciata una nuova API per l'anteprima dell'attestazione di conformità sull'R010 e contiene un model con lo stesso nome.

E' stata appena rilasciata la documentazione aggiornata dell'R010 per evitare sovrascritture in fase di generazione dei models, vedi changelog https://github.com/italia/ansc/releases/tag/v.1.26.2

In generale, è consigliabile utilizzare dei prefix per la generazione dei models.

Un saluto,
Supporto ANSC
