### ISSUE TITLE
[SC]: R007 - mancanza controlli in caso di firma digitale

### ISSUE THREAD

**Issue by SNoccaADS** [italia/ansc#771]
### Ambiente

pre-produzione

### Servizio

R007 - Servizi cooperativi firma ufficiale di stato civile, R012 - Servizi cooperativi firma elettronica del dichiarante

### idOperazione

2128024

### idEvento o idAnsc

2024-1223451-105-039010

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Faenza

### Data del test (yyyy-mm-dd)

2024-03-18

### Descrivi il problema

Ci risulta che, diversamente da quanto accade nella web-app, qualora i firmatari di un atto optino per la firma digitale, lato servizi cooperativi sia possibile invocare il servizio R007 di firma dell'ufficiale di stato civile e concludere l'atto anche nel caso in cui nessuno dei firmatari abbia di fatto effettuato la presa visione del documento.
Potete verificare?

**Comment by amusarra** [comment]
Salve @SNoccaADS.
Abbiamo preso in carico la sua segnalazione.

Cordiali Saluti.
Supporto ANSC.

**Comment by gbuemi** [comment]
Salve @SNoccaADS,
il problema è stato risolto, potete ripetere il test?

Un saluto,
Supporto ANSC
