### ISSUE TITLE
[SC]: problema R007 Firma attestazione

### ISSUE THREAD

**Issue by ManuelDeMeo** [italia/ansc#772]
### Ambiente

pre-produzione

### Servizio

R007 - Servizi cooperativi firma ufficiale di stato civile

### idOperazione

2128607

### idEvento o idAnsc

1220294

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Grottaferrata

### Data del test (yyyy-mm-dd)

2024-03-18

### Descrivi il problema

Buongiorno, la richiesta con idOperazione 2128607 relativa al servizio R007 /attestazione/firma/ restituisce i seguenti errori:
- 400001 : Sezione firma input non impostata 
- 400001 : Campo obbligatorio non compilato

In richiesta tuttavia sono stati compilati tutti i dati, stiamo sbagliando qualcosa?
Grazie

**Comment by gbuemi** [comment]
Buonasera @ManuelDeMeo,
il problema era nella documentazione, abbiamo appena rilasciato la versione 1.26.3 vedi changelog https://github.com/italia/ansc/blob/main/docs/Changelog.md

Grazie per la segnalazione

Un saluto,
Supporto ANSC

**Comment by ManuelDeMeo** [comment]
Grazie, abbiamo adeguato i model e vi confermo che adesso funziona.

Riapro un attimo la issue per una domanda che potrà essere utile a tutti in merito al servizio correlato di anteprima.

Prima della firma dell'attestazione di conformità il nuovo servizio R010 /anteprima/attestazione restituiva correttamente l'anteprima dell'attestazione da firmare (vedi idOperazione: 2128484

Una volta firmata l'attestazione, lo stesso servizio di anteprima restituisce errore "406004 - Evento firmato o annullato" che poi è lo stesso errore restituito dal servizio R007 se provo a rifirmare un'attestazione firmata in precedenza.

La domanda quindi è: è corretto che non si possa più consultare l'anteprima di un'attestazione già firmata?
Grazie

**Comment by gbuemi** [comment]
Salve @ManuelDeMeo,
l'R010 /anteprima/attestazione è da utilizzare solo prima della firma dell'atto.

Successivamente è possibile consultare l'atto tramite il servizio l'[R005](https://github.com/italia/ansc/blob/main/docs/openapi/R005_consultazione_ansc.yaml) e reperire l'attestazione di conformità con l'[R001 ](https://github.com/italia/ansc/blob/main/docs/openapi/R001_allegato.yaml).

Per le prossime volte, se la issue risulta corretta, vi chiediamo gentilmente di aprire una discussion per questo genere di quesiti.

Grazie e saluti,
Supporto ANSC
