### ISSUE TITLE
[SC]: data annotazione su notifica

### ISSUE THREAD

**Issue by antonioluberto** [italia/ansc#773]
### Ambiente

pre-produzione, produzione

### Servizio

R005 - Servizi cooperativi consultazione

### idOperazione

2129300

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Grottaferrata

### Descrivi il problema

In riferimento all'atto 
2024-1223534-55-058046
redatto per la trascrizione di accordo di negoziazione assistita (cessazione degli effetti civili del matrimonio) le notifiche relative all'annotazione da apporre sull'atto di nascita di sposo/a riportano errata valorizzazione del campo:

![image](https://github.com/italia/ansc/assets/26415430/fabed722-d156-44d9-aa2c-018240b7a64f)

Dovrebbe trattarsi della data in cui fosse stata apposta in precedenza l'annotazione di matrimonio sull'atto di nascita di sposo/a; questo dato non è disponibile all'usc, in generale, al momento della trascrizione dell' accordo di negoziazione assistita; in più, non è previsto nella modellazione di "Sep_Div_005".
La notifica riporta però la data in cui è stato inviata in ANSC la trascrizione dell' accordo di negoziazione assistita, informazione certamente errata.

Lo stesso problema si presenta in produzione (atto: 2024-5553-191-058046).

Verosimilmente la cosa migliore è lasciare vuota la data in questione sulla notifica (--/--/----).

Rimaniamo comunque in attesa di vostro riscontro.

**Comment by rvinzani** [comment]
Abbiamo preso in carico la segnalazione: nel caso il sistema non la conosca la data di annotazione dell'atto di matrimonio sull'atto di nascita questa non verrà riportata nella copia dell'atto

**Comment by asqueglia** [comment]
Buongiorno con il rilascio della versione 1.27.0 è stata effettuata la correttiva richiesta (lasciare in bianco la data contenuta nell'annotazione). chiudiamo pertanto la issue. In caso di ulteriori segnalazioni si prega di riaprirne una altra dedicata.
