### ISSUE TITLE
[mapping] Caso d'uso Morte_999

### ISSUE THREAD

**Issue by MarcoSalaPad** [italia/ansc#78]
Buongiorno,
stiamo lavorando sulla mappatura e sviluppo del caso d'uso di servizio Morte_999

Si tratta di un chiarimento per non sbagliare l'interpretazione che stiamo dando ai vari campi:

![image](https://user-images.githubusercontent.com/52407655/235102559-9e35a0b2-d230-40ca-87b1-9c517bd24815.png)

In questo campo, che è obbligatorio, quale data va indicata nell'invio che mandiamo ad ANSC? La data di registrazione dell'atto che il comune sta inserendo nella banca dati? Oppure dobbiamo prevedere un campo per la decorrenza nel caso di atti che arrivano dall'estero e quindi la decorrenza è quella di effettiva comunicazione e non quella di morte (nel caso che la comunicazione dal consolato arrivi molto tempo dopo l'effettivo decesso del soggetto?).
Ho provato a verificare tutti gli altri casi d'uso rilasciati (non 999) e a meno di sviste non ho trovato questa data richiesta da nessun'altra parte.

Grazie
Marco Sala
Pa Digitale Spa

**Comment by rfamiglini** [comment]
Buongiorno,
verifichiamo e le facciamo sapere.

**Comment by rfamiglini** [comment]
La data decorrenza ha lo scopo di recuperare eventi redatti in modalità cartacea, in caso di malfunzionamento momentaneo del sistema o indisponibilità di connessione.

Il campo deve essere valorizzato con la data formazione se l'evento viene registrato direttamente in digitale, se invece si tratta di un recupero per malfunzionamento si deve inserire la data in cui è stato effettivamente formato l'evento cartaceo.
