### ISSUE TITLE
[SC R002_certificazione]: nella richiesta del certificato per estratto integrale errore 500 

### ISSUE THREAD

**Issue by MichelaGarzoni** [italia/ansc#780]
### Ambiente

pre-produzione

### Servizio

R002 - Servizi cooperativi certificazioni

### idOperazione

2130918

### idEvento o idAnsc

idAnsc:"2024-1220426-19-032001" ,idEvento:"1220426"

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

3655 - Duino Aurisina

### Data del test (yyyy-mm-dd)

 data:2024-03-20 10:02:27

### Descrivi il problema

In risposta otteniamo:
    "errors": [
        {
            "code": "500",
            "severity": "E",
            "text": "Errore interno"
        }
Volevamo sapere se abbiamo impostato qualcosa nel json della richiesta del certificato dell'estratto integrale in modo errato, in quanto non riusciamo a individuare l'errore presente o la mancanza di informazione necessaria al funzionamento del servizio.
Grazie

### Payload (json)

```JSON
{
"testataRichiesta":{
"idComune":3655
,"idOperazioneComune":"19"
,"dataOraRichiesta":"2024-03-20T10:02:27Z"
,"nomeApplicativo":"AAAAAAA"
,"versioneApplicativo":"21.99.0000"
,"fornitoreApplicativo":"IIIIIIIII"
}
,"idAnsc":"yyyy-nnnnnn-nn-nnnnnn"
,"idEvento":"1220426"
,"intestatario":{
"id":"nnnnnn"
}
,"richiedente":{
"id":"nnnnnn"
,"codiceFiscale":"XXXXXX"
,"cognome":"XXXXX"
,"nome":"XXXX"
,"sesso":"M"
,"dataNascita":"1985-12-05"
}
,"idTipoCertificato":"3"
}
```

**Comment by gbuemi** [comment]
Buongiorno @MichelaGarzoni,
abbiamo preso in carico la segnalazione

Un saluto,
Supporto ANSC

**Comment by gbuemi** [comment]
Salve @MichelaGarzoni. 
il problema è rientrato.

Un saluto,
Supporto ANSC
