### ISSUE TITLE
[webapp]: Login error

### ISSUE THREAD

**Issue by gcuci** [italia/ansc#781]
### Ambiente

pre-produzione

### Provenienza segnalazione

Software House

### Riferimenti operatore/comune

Bagnacavallo

### Data del test (yyyy-mm-dd)

2024-03-20

### Descrivi il problema

Da questa mattina, non riusciamo ad accedere alla Web Application, viene visualizzata una popup con il messaggio 'Login error'.

![LoginError](https://github.com/italia/ansc/assets/128400400/4ef6ad39-6fa9-434c-950a-3906ee37960d)

**Comment by gbuemi** [comment]
Buongiorno @gcuci,
abbiamo preso in carico la segnalazione.

Un saluto,
Supporto ANSC

**Comment by gbuemi** [comment]
Salve @gcuci,
il problema è rientrato.

Un saluto,
Supporto ANSC
