### ISSUE TITLE
[SC R007_firma_usc]: errore in fase di firma dell'atto quando l'USC ha firmato l'attestazione di conformità degli allegati

### ISSUE THREAD

**Issue by MichelaGarzoni** [italia/ansc#782]
### Ambiente

pre-produzione

### Servizio

R007 - Servizi cooperativi firma ufficiale di stato civile

### idOperazione

2131034

### idEvento o idAnsc

id_ansc = 2024-1223684-31-032001

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

3655 - Duino Aurisina

### Data del test (yyyy-mm-dd)

data:2024-03-20 10:34:29

### Descrivi il problema

L'atto è stato firmato dai firmatari, successivamente è stata scaricata l'anteprima di attestazione di conformità degli allegati e l'USC ha firmato l'attestazione. In fase di firma conclusiva dell'atto da parte dell'USC otteniamo l'errore:
400003 - Stato evento non valido per l'operazione richiesta: lo stato deve essere CONFERMATO se l'atto non prevede firmatari altrimenti FIRMATO DAL DICHIARANTE. 
accedendo alla web-app per verificare lo stato dell'atto, questo risulta:
![image](https://github.com/italia/ansc/assets/128141738/47835662-ffa2-403b-be2a-2e5ed5f13ec9)

### Payload (json)

```JSON
{
"testataRichiesta":{
"idComune":3655
,"idOperazioneComune":"31"
,"dataOraRichiesta":"2024-03-20T11:34:28Z"
,"nomeApplicativo":"AAAAAAAA"
,"versioneApplicativo":"21.99.0000"
,"fornitoreApplicativo":"IIIIIIIIIII"
}
,"firmaInput":{
"idEvento":"1223684"
,"parametriFirma":{
"idTipoFirma":"1"
,"idModalitaInput":"2"
,"inputFirma1":"VGVzdFVzZXI="
,"inputFirma2":"VGVzdFBhc3N3b3Jk"
,"inputFirma3":"VGVzdE90cA=="
}
}
}
```

**Comment by gbuemi** [comment]
Salve,
abbiamo preso in carico la segnalazione

Un saluto,
Supporto ANSC

**Comment by gbuemi** [comment]
Buongiorno @MichelaGarzoni,
la questione nasce dal fatto che l'atto è stato validato con l'idVersion 100009. 
Il nuovo flusso con la firma del certificato di attestazione di conformità è previsto dalla versione 100010, vi invitiamo quindi a fare un test aggiornando questo campo come indicato. 

Stiamo inoltre prevedendo un controllo per evitare che si verifichi una situazione come questa da voi riportata.

Grazie e saluti,
Supporto ANSC
