### ISSUE TITLE
[SC]: Estratto per Copia Integrale - Errore Interno

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#783]
### Ambiente

pre-produzione

### Servizio

R002 - Servizi cooperativi certificazioni

### idOperazione

2131465

### idEvento o idAnsc

2024-1223777-10-108028

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

biadanpad

### Data del test (yyyy-mm-dd)

2024-03-20

### Descrivi il problema

Richiamando il servizio per ottenere l'estratto per copia integrale dell'atto dopo averlo fatto firmare ai dichiaranti e all'USC, oltre che aver firmato l'attestazione di conformità dei documenti allegati, il sistema restituisce l'errore in oggetto

### Payload (json)

```JSON
REQUEST:
{
    "idAnsc": "2024-1223777-10-108028",
    "idEvento": "1223777",
    "richiedente": {
        "id": "2225818"
    },
    "intestatario": {
        "id": "2225818"
    },
    "idTipoCertificato": "3",
    "conPaternitaMaternita": false,
    "testataRichiesta": {
        "idComune": 5000,
        "idOperazioneComune": "5640",
        "dataOraRichiesta": "2024-03-20T14:52:11.663+01:00",
        "nomeApplicativo": "urbi",
        "versioneApplicativo": "1.2.0",
        "fornitoreApplicativo": "padigitale"
    }
}

RESPONSE:
{
    "testataRisposta": {
        "idComune": 5000,
        "idOperazioneComune": "5640",
        "idOperazione": "2131465"
    },
    "errors": [{
            "code": "500",
            "severity": "E",
            "text": "Errore interno"
        }
    ],
    "infos": [{
            "code": "110527",
            "severity": "I",
            "text": "Informazioni sull'operazione da fornire in caso di assistenza : data:2024-03-20 13:52:14 , idOperazione:2131465"
        }
    ]
}
```

**Comment by gbuemi** [comment]
Salve @biadanpad,
il problema è rientrato.

Un saluto,
Supporto ANSC
