### ISSUE TITLE
[SC]: hasAllegatiDaAttestare=true anche quando l'atto non ha allegati

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#784]
### Ambiente

pre-produzione

### Servizio

R010 - Servizi cooperativi anteprima

### idOperazione

2131620

### idEvento o idAnsc

1223785

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

biadanpad

### Data del test (yyyy-mm-dd)

2024-03-20

### Descrivi il problema

il sistema risponde dicendo che ci sono allegati per cui firmare l'attestazione, ma in realtà non ce ne sono

### Payload (json)

```JSON
REQUEST:
{
  "idEvento": "1223785",
  "testataRichiesta": {
    "idComune": 5000,
    "idOperazioneComune": "9549",
    "dataOraRichiesta": "2024-03-20T15:48:24.927+01:00",
    "nomeApplicativo": "urbi",
    "versioneApplicativo": "1.2.0",
    "fornitoreApplicativo": "padigitale"
  }
}

RESPONSE:
{
  "testataRisposta": {
    "idComune": 5000,
    "idOperazioneComune": "9549",
    "idOperazione": "2131620"
  },
  "infos": [
    {
      "code": "110527",
      "severity": "I",
      "text": "Informazioni sull'operazione da fornire in caso di assistenza : data:2024-03-20 14:48:27 , idOperazione:2131620"
    }
  ],
  "allegatoOutput": {
    "contenuto": "JVBERi0xLjQKJaqrr............zEwMwolJUVPRgo=",
    "nomeFile": "preview.pdf",
    "tipoFile": "PDF"
  },
  "hasAllegatiDaAttestare": true
}
```

**Comment by asqueglia** [comment]
Buongiorno verifichiamo e le facciamo sapere

**Comment by asqueglia** [comment]
Abbiamo preso incarico la correttiva; il servizio dovrebbe restituire in output una risposta da cui si evince che non ci sono allegati da attestare

**Comment by biadanpad** [comment]
Potrebbe ad esempio restituire il numero di allegati da attestare

**Comment by asqueglia** [comment]
Buongionro, con la versione 1.27.0 abbiamo corretto l'anomalia. Chiudiamo pertanto la issue
