### ISSUE TITLE
[SC]: R007 - Errore nella firma remota dell'Attestazione di conformità

### ISSUE THREAD

**Issue by siscomanpr** [italia/ansc#785]
### Ambiente

produzione

### Servizio

R007 - Servizi cooperativi firma ufficiale di stato civile

### idOperazione

54400

### idEvento o idAnsc

7053

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Serravalle Sesia

### Data del test (yyyy-mm-dd)

21/03/2024

### Descrivi il problema

Tentando di firmare l'attestazione di conformità di un allegato di un atto di cittadinanza, riceviamo sempre l'errore:
"Firma Remota non avvenuta con successo".
Essendo la prima volta che viene usato questo servizio in ambiente di produzione non riusciamo a capire se è un problema nostro o del sistema centrale. Verificando le credenziali della firma remota passate al servizio, ci sembrano corrette. Sono stati fatti diversi tentativi quindi escluderei il problema dell'OTP scaduto.
Potete farci sapere da cosa può dipendere questo errore? 

In ambiente di test (con le credenziali di test di firma remota) il servizio funziona correttamente.

La questione sarebbe abbastanza urgente visto che stiamo parlando dell'ambiente di produzione e l'atto è rimasto in sospeso da firmare.

**Comment by gbuemi** [comment]
Buonasera @siscomanpr,
dai log di ieri in corrispondenza del tentativo di firma ci risultano errori verso il servizio di firma aruba del tipo: **Errore servizio firma remota: 0004: Otp Credential Invalid Or Blocked.**

Dai log di oggi invece vediamo che le firme sono sono state applicate, infatti l'evento con id 7053 risulta firmato da USC.

Un saluto,
Supporto ANSC

**Comment by siscomanpr** [comment]
Riapro la issue per chiarire che:
Dai log di oggi pomeriggio l'atto risulta firmato perché il comune non poteva più aspettare (ci aspettavamo una risposta questa mattina) e abbiamo deciso di tornare alla versione precedente del modelevento "100009" in modo che si potesse evitare la firma dell'attestazione e fare direttamente la firma usc dell'atto.
Ieri il comune ha tentato di firmare **l'attestazione di conformità** diverse volte con diversi OTP (sicuramente validi perché erano appena rilasciati) e con le credenziali corrette (le stesse con il servizio di firma usc funzionano) ma restituiva sempre quell'errore.

**Comment by gbuemi** [comment]
@siscomanpr vi comunichiamo che stiamo approfondendo la questione.

Grazie,
Supporto ANSC

**Comment by mttfranci** [comment]
Salve @siscomanpr , dovremmo aver corretto l'anoamalia, quando volete potete riprovare.

Saluti

Assistenza ANSC

**Comment by siscomanpr** [comment]
Il comune nei prossimi giorni farà altri atti e proveremo. Nel caso ci fossero ancora problemi riapriremo la issue.
Grazie.
