### ISSUE TITLE
[SC]: R001 errore download allegato Attestazione di conformità

### ISSUE THREAD

**Issue by siscomanpr** [italia/ansc#786]
### Ambiente

pre-produzione

### Servizio

R001 - Servizi cooperativi allegati

### idOperazione

2133938

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Serravalle Sesia

### Data del test (yyyy-mm-dd)

22/03/2024

### Descrivi il problema

Come avete indicato in questa issue: https://github.com/italia/ansc/issues/772, stavamo tendando di consultare/scaricare il file dell'attestazione di conformità firmata, ma chiamando il servizio R001 funzione /allegato, riceviamo l'errore 
`L'utente loggato non ha accesso alla risorsa`.
Manca solo qualche autorizzazione sul nostro operatore di test (come Siscom) oppure c'è qualche problema di altro genere?

**Comment by mttfranci** [comment]
Buongiorno, stiamo verificando la vostra segnalazione.

Saluti

Assistenza ANSC

**Comment by mttfranci** [comment]
@siscomanpr potete riprovare?
L'anomalia dovrebbe essere stata risolta con la patch 1.26.6 di ANSC.

Saluti 

Assistenza SNC

**Comment by siscomanpr** [comment]
Ora funziona, grazie.
