### ISSUE TITLE
[SC]: obbligatorietà officianteEventoMatrimonio per Sep_Div_001 e Sep_Div_002.

### ISSUE THREAD

**Issue by gcuci** [italia/ansc#788]
### Ambiente

pre-produzione

### Servizio

R009 - Servizi cooperativi validazione evento

### idOperazione

2136229

### idEvento o idAnsc

1222877

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Firenze

### Data del test (yyyy-mm-dd)

2024-03-25

### Descrivi il problema

Per i casi d'uso Sep_Div_001 e Sep_Div_002, è prevista l'obbligatorietà dell'Officiante dell'evento di Matrimonio. Questa informazione, però, non sempre è disponibile. Chiediamo se possibile rendere il campo facoltativo.

Per un esempio, potete far riferimento alla richiesta di validazione, effettuata oggi, con idOperazione = '2136229'.

In attesa di riscontro,

cordiali saluti.

**Comment by asqueglia** [comment]
Buon pomeriggio le formule 121-ter e 121-quater applicate rispettivamente ai casi d'uso indicati, richiedono obbligatoriamente l'officiante

_i quali mi dichiarano:_
- _di avere contratto matrimonio in data ..., in ........, **dinanzi a ...,** di cui all’atto iscritto/trascritto nei 
registri dello stato civile del Comune di ... , n... parte ... serie .... anno .....);_

Per rendere opzionale l'officiante dovremmo modificare la formula censita eliminando la frase 'dinanzi a'.
Chiederemo un approfondimento in merito ad ANUSCA e le facciamo sapere.

**Comment by antonioluberto** [comment]
La sezione nella formula cui si fa riferimento nel post sopra ci risulta richieda la sola indicazione se il matrimonio sia stato celebrato
- dinanzi a Parroco/Ministro di Culto
ovvero
- dinanzi a ufficiale di stato civile.

**Comment by asqueglia** [comment]
Buongiorno @antonioluberto abbiamo verificato che  il campo 'officianteEventoMatrimonio' è un testo libero per cui potete tranquillamente trasmettere Parroco/Ministro culto / Ufficiale di stato civile a seconda del caso. Chiudiamo pertanto la issue. In caso di ulteriori segnalazioni si prega di aprire una algtra issue dedicata.
