### ISSUE TITLE
[SC]: R013 - Errore di validazione "Evento non trovato"

### ISSUE THREAD

**Issue by siscomanpr** [italia/ansc#789]
### Ambiente

pre-produzione

### Servizio

R013 - Servizi cooperativi per la validazione della rettifica

### idOperazione

2136855

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Serravalle Sesia

### Data del test (yyyy-mm-dd)

25/03/2024

### Descrivi il problema

Cercando di validare un evento di annotazione modificativa generica (caso d'uso 14850000) il sistema restituisce l'errore: `Evento non trovato`
Lo stesso tipo di evento l'avevamo già testato sempre in ambiente di pre-produzione un paio di settimane fa e funzionava correttamente (es. idOperazione 1768872) 
Oggi, in seguito ad alcune nostre modifiche, abbiamo fatto nuovamente dei test su questo caso d'uso ma sembra non funzioni più.
Abbiamo verificato che l'evento che viene passato nel blocco `attoIntestatario` esiste, e confrontando il nuovo json con quelli inviati qualche settimana fa non notiamo altre mancanze.
Potete verificare se è un problema vostro? 

Grazie
Mauro Maccagno
Siscom SPA

**Comment by gbuemi** [comment]
Buongiorno @siscomanpr,
abbiamo preso in carico la segnalazione.

Un saluto,
Supporto ANSC

**Comment by gbuemi** [comment]
Buongiorno,
vi invitiamo ad aggiornare l'idVersion all'ultima versione pubblicata e di effettuare un nuovo test.

Grazie e saluti,
Supporto ANSC
