### ISSUE TITLE
File Decodifica 61_desc_stato_civile

### ISSUE THREAD

**Issue by MarcoSalaPad** [italia/ansc#79]
Buongiorno,

nel nostro lavoro di sviluppo ci siamo accorti di una incongruenza tra la specifica degli stati civili tra ANPR e ANSC.

Se vado dal sito di ANPR e scarico la tabella di decodifica dello stato civile, io vedo quanto segue

![image](https://user-images.githubusercontent.com/52407655/235155767-2b140561-a215-4f8f-816f-84a711eebf44.png)

Quindi nella nostra mappatura per l'anagrafe abbiamo da sempre utilizzato l'id 9 per inviare quella tipologia di stato civile legata ai cittadini.

Ora, nel file di decodifica di ANSC l'id di quello specifico stato civile è 

![image](https://user-images.githubusercontent.com/52407655/235156123-07efe40b-5d4c-470d-9c01-4b5bed8d17a3.png)

C'è un errore nella creazione dei vostro file di decodifica? Altrimenti dobbiamo andare a fare ulteriori modifiche sulla decodifica degli stati civili tra ANPR e ANSC

Grazie
Marco Sala
Pa Digitale Spa

**Comment by rfamiglini** [comment]
Buongiorno,
verifichiamo e vi facciamo sapere.

**Comment by asqueglia** [comment]
Buongiorno è stata rilasciata la versione 1.7.0 che corregge la segnalazione in oggetto.
