### ISSUE TITLE
[webapp]: Atto di morte - Caso d'uso Morte_004 (redazione testo)

### ISSUE THREAD

**Issue by migmar68** [italia/ansc#791]
### Ambiente

pre-produzione

### Provenienza segnalazione

Software House

### Riferimenti operatore/comune

Migliori

### Descrivi il problema

ci chiediamo se questo comportamento che abbiamo notato è un refuso o una scelta.
questo caso d'uso riconduce alla formula 191 e solo a questa:
![image](https://github.com/italia/ansc/assets/124561581/25160af3-b7ae-4f0b-af28-4f9da365232b)

come si vede la formula ministeriale non lascia adito a dubbi: l'autorità che richiede la trascrizione, come da titolo della formula è fissa.

a video ho i campi della autorità mittente. il nome autorità è richiesto obbligatorio. compilerei così la form:
![image](https://github.com/italia/ansc/assets/124561581/185a5cfc-36da-4ce2-81c9-42bf6ffc0651)

il testo che viene quindi formato automaticamente è:

_Oggi 26/03/2024 io sottoscritto G.B. Ufficiale dello stato civile del Comune di POGGIO A CAIANO (PO), nella funzione di delegato del sindaco, ho ricevuto dal Procuratore della Repubblica presso il Tribunale del **Procuratore della Repubblica presso il Tribunale di** di **TIVOLI** (RM) ITALIA Numero 564/GT/2 in data 21/03/2024, di cui mi ha trasmesso copia.
Aderendo a tale richiesta provvedo alla trascrizione del documento, come segue:.
Dopo di che, ho munito del mio visto ed inserito nel volume degli allegati a questo registro la richiesta di trascrizione e la copia del documento trascritto._

note:

- manca "la richiesta in data ....."
- è presente come da formula un testo fisso, ma sembra un doppione del campo nome autorità mittente
- manca "di trascrivere"
- premendo "visualizza anteprima atto" la sezione "Autorità mittente" è duplicata
- nella mappatura dati del caso morte_004 è correttamente citata la formula 191. suppongo inutile la formula 197 che pure è citata (ma non obbligatoria quindi non è un vero problema)

PS: caso simulato, ma non salvato.

**Comment by gbuemi** [comment]
Buongiorno,
abbiamo preso in carico la segnalazione.

Un saluto,
Supporto ANSC

**Comment by asqueglia** [comment]
Buongiorno con la versione 1.28.0 la segnalazione è stata corretta. Chiudiamo pertanto la issue
