### ISSUE TITLE
[webapp]: problema con allegati

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#792]
### Ambiente

pre-produzione

### Provenienza segnalazione

Software House

### Riferimenti operatore/comune

ponsacco, anna maraspin

### Data del test (yyyy-mm-dd)

2024-03-27

### Caso d'uso

dic_nasc_001

### Descrivi il problema

Buongiorno,
ho voluto replicare sulla webapp la casistica del ticket #790 fatto tramite gestionale.

![image](https://github.com/italia/ansc/assets/127182190/1c42bdb4-168b-478b-86b1-49c59a644d7f)

Ho provato più volte a cliccare su "verifica allegato" ma permane l'errore.

Vi allego anche idatto e numero comunale
![image](https://github.com/italia/ansc/assets/127182190/aefffd5a-5b81-4558-962a-2a407c501a7f)

**Comment by amusarra** [comment]
Buongiorno @annamaraspin 
Abbiamo preso in carico la sua segnalazione.

Cordiali Saluti.
Supporto ANSC.

**Comment by amusarra** [comment]
Salve @annamaraspin 
Prima di poter cliccare sul link **Verifica Allegati**, deve cliccare sul link **Conferma**.

Cordiali Saluti.
Supporto ANSC:

**Comment by annamaraspin** [comment]
ops, grazie. Ero sicura di averlo fatto
