### ISSUE TITLE
Richiesta riscontro discussion 787 - info su firma attestazione conformità allegati

### ISSUE THREAD

**Issue by siscomanpr** [italia/ansc#793]
### Ambiente

pre-produzione, produzione

### Servizio

R007 - Servizi cooperativi firma ufficiale di stato civile, R010 - Servizi cooperativi anteprima

### idOperazione

0

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Serravalle Sesia

### Descrivi il problema

Apriamo questa issue solo per richiamare l'attenzione su questa discussion https://github.com/italia/ansc/discussions/787 di cui stiamo aspettando una risposta da alcuni giorni. 
Per noi è importante avere una risposta nel più breve tempo possibile per poter terminare lo sviluppo della funzione di firma attestazione conformità e permettere ai comuni di utilizzare la nuova funzione al più presto (evitando loro di dover riprendere altri atti già conclusi e svolgere l'operazione di firma dell'attestazione tramite nota tecnica).

Grazie
Siscom SPA

**Comment by mttfranci** [comment]
Salve @siscomanpr  abbiamo risposto alla discussione #787 .

Siamo a disposizione per ogni ulteriore chiarimento.

Saluti
