### ISSUE TITLE
[SC]: R009 validazione caso 1344 - Trascrizione della sentenza di adozione di maggiorenne emessa dal tribunale [Trascr_016]

### ISSUE THREAD

**Issue by siscomanpr** [italia/ansc#794]
### Ambiente

produzione

### Servizio

R009 - Servizi cooperativi validazione evento

### idOperazione

58718

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Comune di Loano

### Data del test (yyyy-mm-dd)

28/03/2024

### Descrivi il problema

Tentando di validare il caso d'uso in oggetto, adozione di maggiorenne (straniero) da tribunale, il sistema richiede obbligatori i dati di entrambi i genitori e anche del nuovo cognome del soggetto.
Il comune di Loano ci segnala che in questo caso non è corretto indicare i dati degli adottanti nei campi di Padre e Madre, ma che sarebbe opportuno ci fossero degli appositi campi per gli adottanti. Nel caso specifico poi, l'adottante è solo 1, quindi in ogni caso non è detto che ci siano 2 adottanti.
Inoltre non dovrebbe richiedere obbligatorio il nuovo cognome perché non è detto che ci sia un cambio di cognome contestuale all'adozione. In questo caso per esempio mantiene il cognome e la cittadinanza precedente.

La richiesta è urgente, e riteniamo che non si possa usare il caso d'uso di servizio perché, oltre a non generare le dovute annotazioni sull'atto di nascita primario (già digitale), c'è il problema che non è possibile impostare la certificabilità e questo tipo di atto non dovrebbe essere certificabile.

**Comment by rvinzani** [comment]
Salve, abbiamo contattato il comune e suggerito di utilizzare i casi d'uso di servizio per registrare la trascrizione della sentenza di adozione e l'annotazione sull'atto di nascita. Per adeguare il caso d'uso specifico secondo le particolarità da voi segnalate ci confronteremo con gli esperti Anusca prima di procedere

**Comment by asqueglia** [comment]
ANUSCA conferma che devono essere indicati i dati degli adottanti (non deve essere vincolante che ne debbano essere due); i genitori naturali non vanno acquisiti o quantomeno possono essere acquisiti come campi aggiuntivi opzionali (non da ricercare ma da compilare a mano). Stesso discorso anche per i minori per adozioni non legittimanti. Nella maggior parte dei casi c’è l’aggiunta del cognome dell’adottante, ma la sentenza di adozione potrebbe anche disporre diversamente (es. senza procedere con l’aggiunta dell’adottante); quindi nuovo cognome deve essere opzionale. La certificazione può essere rilasciata con l’annotazione certificabile dell’adozione

**Comment by asqueglia** [comment]
Buongiorno la segnalazione è stata corretta con il rilascio odierno della versione 1.30.0
