### ISSUE TITLE
[mapping] Parte e serie in use_case gestiti

### ISSUE THREAD

**Issue by migmar68** [italia/ansc#8]
Buongiorno
Chiedo un chiarimento sul file [3_dec_use_case.csv](https://github.com/italia/ansc/blob/main/docs/Mapping_casi_uso/3_dec_use_case.csv)  in cui sono presenti le colonne Parte e Serie.
Risultano censite la Parte 3, e la Parte 2 Serie B2. Forse sono convenzioni con cui si intende qualcosa? Non mi sembra esistano. Grazie.

**Comment by asqueglia** [comment]
Buongiorno, parte e serie sono state inserite nella documentazione su richiesta di alcune software house, per una comodità di mappatura. Il sistema ANSC non utilizza questi metadati, nè li controlla. Verificheremo comunque la documentazione eliminando i valori indicati non previsti.
