### ISSUE TITLE
[R009] Campi (non) obbligatori - caso d'uso Morte 2101

### ISSUE THREAD

**Issue by RosarioSalatiello** [italia/ansc#80]
Invocando il servizio di validazione otteniamo i seguenti errori relativi a campi riportati come obbligatori, ma che in realtà nella documentazione non risultano tali:

HttpResponse Body: {
    "testataRisposta": {
        "idComune": 5000,
        "idOperazione": "1583842",
        "idEsito": 1
    },
    "errors": [{
            "code": "400003",
            "severity": "E",
            "text": "Il campo evento.intestatari[0].idProvinciaNascita nella sezione Deceduto è obbligatorio"
        }, {
            "code": "400003",
            "severity": "E",
            "text": "Il campo evento.intestatari[0].siglaProvinciaNascita nella sezione Deceduto è obbligatorio"
        }, {
            "code": "400003",
            "severity": "E",
            "text": "Il campo evento.intestatari[0].idComuneNascita nella sezione Deceduto è obbligatorio"
        }, {
            "code": "400003",
            "severity": "E",
            "text": "Il campo evento.intestatari[0].nomeComuneNascita nella sezione Deceduto è obbligatorio"
        }, {
            "code": "400003",
            "severity": "E",
            "text": "Il campo evento.intestatari[0].idProvinciaResidenza nella sezione Deceduto è obbligatorio"
        }, {
            "code": "400003",
            "severity": "E",
            "text": "Il campo evento.intestatari[0].siglaProvinciaResidenza nella sezione Deceduto è obbligatorio"
        }, {
            "code": "400003",
            "severity": "E",
            "text": "Il campo evento.intestatari[0].idComuneResidenza nella sezione Deceduto è obbligatorio"
        }, {
            "code": "400003",
            "severity": "E",
            "text": "Il campo evento.intestatari[0].nomeComuneResidenza nella sezione Deceduto è obbligatorio"
        }, {
            "code": "400003",
            "severity": "E",
            "text": "Il campo evento.datiEventoMorte.comparente1.idProvinciaNascita nella sezione Comparente 1 è obbligatorio"
        }, {
            "code": "400003",
            "severity": "E",
            "text": "Il campo evento.datiEventoMorte.comparente1.siglaProvinciaNascita nella sezione Comparente 1 è obbligatorio"
        }, {
            "code": "400003",
            "severity": "E",
            "text": "Il campo evento.datiEventoMorte.comparente1.idComuneNascita nella sezione Comparente 1 è obbligatorio"
        }, {
            "code": "400003",
            "severity": "E",
            "text": "Il campo evento.datiEventoMorte.comparente1.nomeComuneNascita nella sezione Comparente 1 è obbligatorio"
        }, {
            "code": "400003",
            "severity": "E",
            "text": "Il campo evento.datiEventoMorte.comparente1.nazionalita nella sezione Comparente 1 non corrisponde al pattern ^[\\p{L}']+[ \\p{L}'/\\-]*[ \\p{L}'\\.]*$"
        }, {
            "code": "400003",
            "severity": "E",
            "text": "Il campo evento.datiEventoMorte.comparente1.idProvinciaResidenza nella sezione Comparente 1 è obbligatorio"
        }, {
            "code": "400003",
            "severity": "E",
            "text": "Il campo evento.datiEventoMorte.comparente1.siglaProvinciaResidenza nella sezione Comparente 1 è obbligatorio"
        }, {
            "code": "400003",
            "severity": "E",
            "text": "Il campo evento.datiEventoMorte.comparente1.idComuneResidenza nella sezione Comparente 1 è obbligatorio"
        }, {
            "code": "400003",
            "severity": "E",
            "text": "Il campo evento.datiEventoMorte.comparente1.nomeComuneResidenza nella sezione Comparente 1 è obbligatorio"
        }
    ]
}

Segnaliamo inoltre che i campi Tipo Evento e Tipo Contenuto nella sezione Formazione Atto non vengono riportati nella documentazione. Vengono omessi perché si dà per scontato che siano presenti in ogni caso d'uso?

**Comment by rfamiglini** [comment]
Buongiorno,
si tratta di un bug che verrà risolto in uno dei prossimi rilasci.
Per quanto riguarda la domanda sulla documentazione: sì, si da per scontato che Tipo Evento e Tipo Contenuto nella sezione Formazione Atto siano dati obbligatori per ogni caso d'uso.

**Comment by RosarioSalatiello** [comment]
Buongiorno,
sarebbe possibile sapere se e quali sono gli altri casi d'uso impattati da questo stesso bug e quando si prevede di effettuare il rilascio che lo correggerà?

Grazie,
Rosario
