### ISSUE TITLE
[webapp]: atto di matrimonio celebrato con la presenza dell’interprete 

### ISSUE THREAD

**Issue by rvinzani** [italia/ansc#801]
### Ambiente

produzione

### Provenienza segnalazione

Comune

### Riferimenti operatore/comune

Comune di Lissone

### Data del test (yyyy-mm-dd)

02/04/2024

### Caso d'uso

311111

### Descrivi il problema

il testo nel corpo dell’atto relativo all’interprete risulta il seguente:

“mi sono state fatte per mezzo di ….”.

La formula 71 (Caso di matrimonio di persona che non conosce la lingua italiana -articoli 13 e 66 del decreto del presidente della Repubblica 3 novembre 2000, n. 396-) prevede invece quanto segue:

- "La richiesta, le dichiarazioni, le risposte alle domande di cui sopra, da parte di ..., che non conosce la lingua italiana, mi sono state fatte per mezzo di ... nato(a) in ... il ... cittadino(a) ..., residente in ... che da me assunto
(a) ad interprete ha giurato di bene e fedelmente adempiere all'incarico che gli (le) è stato affidato. A mezzo dello stesso interprete ho comunicato a ... gli articoli precitati del codice civile, la risposta di ... di volersi unire in matrimonio con lui (lei) nonché la mia dichiarazione della loro unione in matrimonio.

La chiusura dell’atto è attualmente la seguente:

“Il presente atto viene letto agli intervenuti, i quali tutti, insieme con me, lo sottoscrivono”.

Mentre, secondo la formula anzidetta dovrebbe essere:

“Il presente atto, dopo essere stato comunicato dall'interprete a ... ed averne io dato lettura agli altri intervenuti, è stato da tutti, insieme con me, sottoscritto.

**Comment by gbuemi** [comment]
La segnalazione è stata corretta e appena rilasciata con la versione 1.33.0
