### ISSUE TITLE
[SC]: R005 - Consultazione intestatario/soggetto richiede obbligatorio comune di nascita

### ISSUE THREAD

**Issue by siscomanpr** [italia/ansc#802]
### Ambiente

pre-produzione

### Servizio

R005 - Servizi cooperativi consultazione

### idOperazione

2148823

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Serravalle Sesia

### Data del test (yyyy-mm-dd)

03/04/2024

### Descrivi il problema

Buongiorno,
richiamando il servizio R005, per la ricerca dell'intestatario di un evento, indicando cognome, nome e data di nascita, riceviamo l'errore : 
`Bisogna inserire il Nome del comune di nascita o la Sigla della provincia di nascita o lo stato di nascita`
Abbiamo invece notato che la stessa ricerca con gli stessi parametri tramite web app non segnala questo messaggio.
E' normale che la ricerca fatta da servizi cooperativi si comporti in modo diverso (richiedendo obbligatorio il comune di nascita) rispetto a quella della web app?

### Payload (json)

```JSON
{
    "criteriRicercaSoggetto": {
        "cognome": "ANTONELLI",
        "nome": "VITTORIA",
        "datanascita": "2023-06-06"
    },
}
```

**Comment by gbuemi** [comment]
Buon pomeriggio,
il servizio R005 /consultazione/ansc/intestatario/{version} dev'essere invocato per anagrafica completa oppure con una delle seguenti proprietà valorizzata "idAnpr", "idAnscSoggetto" oppure "codiceFiscale".

Un saluto,
Supporto ANSC

**Comment by siscomanpr** [comment]
Mi permetto di riaprire la issue.
Sulla Web app di ANSC è consentita la ricerca con solo cognome, nome e data di nascita. Perché tramite servizi cooperativi è obbligatorio inserire anche il comune di nascita?
Reputiamo che sia molto scomodo dover inserire tutti i dati del soggetto per ricercarlo, anche considerando che su ANPR è possibile ricercare i soggetti anche solo per cognome e nome.

**Comment by gbuemi** [comment]
Salve @siscomanpr,
l'API di R005 /consultazione/ansc/intestatario/{version} è paragonabile con l'API di ricerca intestatario richiamata in fase di composizione dell'evento, vedi screenshot a seguire e i campi in richiesti in input sono coerenti con quel che succede sulla webapp ANSC

![image](https://github.com/italia/ansc/assets/26254765/bce34e7c-6dfb-4ebe-af07-fc50cc1e3a9a)

Un saluto,
Supporto ANSC

**Comment by siscomanpr** [comment]
Salve @gbuemi 
Dalla web app di ANSC, nell'homepage, ci sono disponibili questi 2 metodi di ricerca evento per soggetto:

![ANSC1](https://github.com/italia/ansc/assets/28776141/f4ef5ee6-d399-4608-a9ce-83975266debf)

![ANSC2](https://github.com/italia/ansc/assets/28776141/7f9f4480-73b0-4cfb-b708-fa096f8f27f6)

e come può vedere è possibile ricercare l'evento anche solo per cognome, nome e data di nascita del soggetto intestatario (oppure per codice fiscale). Non c'è anche il campo del comune di nascita come parametro.
Quella che ha postato Lei è riferita alla ricerca del soggetto in fase di caricamento di un nuovo evento.
A noi interessa la ricerca dell'evento per cognome e nome del soggetto in modo da permettere il rilascio dei certificati dal nostro gestionale.
Restiamo in attesa di un riscontro.
Grazie.

**Comment by gbuemi** [comment]
Salve @siscomanpr,
ci aveva portato fuori pista l'idoperazione che ci ha condiviso in fase di apertura della issue, fa riferimento al servizio di ricerca intestatario, R005 /consultazione/ansc/intestatario/{version}, che è paragonabile con l'API di ricerca intestatario in fase di composizione evento.

L'API che permette di ricercare gli eventi per soggetto è l'R005 /consultazione/ansc/soggetto/{version}. 
Vi comunichiamo che abbiamo preso in carico la richiesta per fare in modo di poter ricercare gli eventi inviando nome, cognome e data di nascita così come da webapp.

Un saluto,
Supporto ANSC

**Comment by siscomanpr** [comment]
Grazie per la presa in carico.
In realtà pensavamo di utilizzare il servizio di ricerca R005 /consultazione/ansc/intestatario/{version} proprio per cercare tutti gli eventi di cui quel soggetto è intestatario, per evitare per esempio che, se cerco un soggetto che è intestatario di un atto di nascita ma è anche un soggetto collegato ad un altro atto (es. come padre), non mi restituisse anche l'atto del figlio.
Se abbiamo inteso male l'utilizzo di questi servizi di consultazione mi faccia sapere.

P.S. In ogni caso il problema del parametro obbligatorio comune di nascita è presente anche utilizzando l'R005 /consultazione/ansc/soggetto/{version}.

Grazie per il riscontro.

Mauro Maccagno 
Siscom SPA

**Comment by gbuemi** [comment]
Il servizio R005 /consultazione/ansc/intestatario/{version} ritorna un elenco di soggetti, non un elenco di eventi e non verrà modificato. Questo servizio è stato realizzato per la ricerca degli intestatari, viene prima effettuata un ricerca su ANSC e nel caso in cui venga trovato viene effettuata una ricerca sulla banca dati di ANPR. Questo servizio è invocabile con una chiave forte (idAnpr/idAnscSoggetto/codiceFiscale) o l'intera anagrafica di un soggetto e non è oggetto della modifica.

Il servizio R005 /consultazione/ansc/soggetto/{version} è proprio quello che fa al caso vostro, ricerca tutti gli eventi di cui quel soggetto è intestatario. Non ricerca dove è stato inserito come padre, per esempio. In questo servizio possiamo modificare l'obbligatorietà dei dati in input accettando, come fa oggi la webapp, il nome, cognome e la data di nascita.

E' più chiaro adesso?

Saluti
Supporto ANSC

**Comment by gbuemi** [comment]
Salve @siscomanpr,
dalla versione 1.28.0 è possibile ricercare l'evento tramite R005 /consultazione/ansc/soggetto/{version} inviando solo nome, cognome e data di nascita. 

Un saluto,
Supporto ANSC
