### ISSUE TITLE
[SC]: R009 errore conformità dati anagrafici

### ISSUE THREAD

**Issue by siscomanpr** [italia/ansc#803]
### Ambiente

produzione

### Servizio

R009 - Servizi cooperativi validazione evento

### idOperazione

63669

### Provenienza segnalazione

Comune

### Comune di riferimento e operatore

Serravalle Sesia - Anna Urban

### Data del test (yyyy-mm-dd)

03/04/2024

### Descrivi il problema

Il comune di SERRAVALLE SESIA sta cercando di validare in ambiente di produzione un atto di nascita con il caso d'uso 1311 (trascrizione da estero) di un soggetto che ha appena acquistato la cittadinanza italiana. 
Non ci sono stati problemi con l'atto di cittadinanza, che è stato validato e firmato correttamente.
Validando invece l'atto di nascita di questo soggetto nato in GEORGIA nel 1973, il sistema restituisce l'errore: 
`Attenzione! I dati del soggetto intestatario con idANSC=5216789 inseriti non sono conformi ai dati anagrafici registrati`
Per quanto abbiamo potuto verificare i dati di cognome, nome, data di nascita e stato estero di nascita sono corretti e sono gli stessi inviati con l'atto di cittadinanza. 
Si fa presente che questo soggetto è già registrato su ANPR come 'soggetto cancellato' con gli stessi dati anagrafici che stiamo trasmettendo.
Potete verificare il motivo di questo errore bloccante?

**Comment by gbuemi** [comment]
Buongiorno @siscomanpr,
abbiamo preso in carico la segnalazione.

Un saluto,
Supporto ANSC

**Comment by gbuemi** [comment]
Salve @siscomanpr 
la situazione è stata sanata da centro, potete riprovare?

Un saluto,
Supporto ANSC
