### ISSUE TITLE
[SC]: R009 validazione caso uso 11223000 - calcolo 10 giorni dichiarazione tardiva

### ISSUE THREAD

**Issue by siscomanpr** [italia/ansc#804]
### Ambiente

produzione

### Servizio

R009 - Servizi cooperativi validazione evento

### idOperazione

62980

### Provenienza segnalazione

Comune

### Comune di riferimento e operatore

Magliano Alpi - Negrino Irene

### Data del test (yyyy-mm-dd)

03/04/2024

### Descrivi il problema

Il comune di Magliano Alpi questa mattina doveva registrare un evento di nascita con dichiarazione tardiva di bambino nato il 23/03/2024. Ha tentato di validare l'atto caricandolo con il caso d'uso in oggetto 11223000 (Dich_Nas_048) ma il sistema restituiva l'errore: 
`Per proseguire è necessario inserire nella sezione Soggetto una data di nascita inferiore ai 10 giorni, escluso il giorno della nascita.`
Calcolando i giorni dalla data di nascita del soggetto, oggi sarebbe stato l'11° giorno senza contare il giorno della nascita, per questo motivo si è cercato di registrarlo con il caso d'uso della dichiarazione tardiva.
Visto che la registrazione dell'atto era improrogabile, il comune ha deciso di registrare comunque l'evento utilizzando il caso d'uso di servizio, ma segnaliamo l'anomalia per richiedere una verifica sul calcolo del numero dei giorni e il relativo messaggio bloccante che il comune ha ricevuto.

**Comment by asqueglia** [comment]
Buongiorno prendiamo in carico la segnalazione
