### ISSUE TITLE
[SC]: Errore validazione atto - caso d'uso 12214300 (non incestuoso)

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#805]
### Ambiente

pre-produzione

### Servizio

R009 - Servizi cooperativi validazione evento

### idOperazione

2149721

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Lissone - biadanpad

### Data del test (yyyy-mm-dd)

2024-04-04

### Descrivi il problema

Pur avendo specificato che non c'è una sentenza per figlio incestuoso, viene richiesta l'autorizzazione del tribunale.
Con le versioni precedenti alla 100010 questo problema non si presenta

**Comment by rvinzani** [comment]
Salve, il sistema verifica che i dichiaranti siano di età maggiore di 16 anni. Nella richiesta è stato indicata una data di nascita del padre del 2024. Saluti

**Comment by rvinzani** [comment]
Chiudo la issue. Nel caso fossero necessari ulteriori chiarimenti si prega di aprire una nuova issue che faccia riferimento a questa
