### ISSUE TITLE
[SC]: Anteprima - Matrimonio: ordine dei firmatari in calce all'atto

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/ansc#809]
### Ambiente

produzione

### Servizio

R010 - Servizi cooperativi anteprima

### idOperazione

66307

### idEvento o idAnsc

2024-7790-339-037054

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

SAN LAZZARO DI SAVENA

### Data del test (yyyy-mm-dd)

2024-04-05

### Descrivi il problema

nell'anteprima dell'atto i firmatari vengono in questo ordine:
- i testimoni
- gli sposi
- l'officiante

gli sposi dovrebbero venire prima dei testimoni.

**Comment by asqueglia** [comment]
Buongiorno verifichiamo e le facciamo sapere

**Comment by asqueglia** [comment]
Buon pomeriggio con il rilascio della versione 1.29.0 la segnalazione è stata corretta. Chiudiamo pertanto la issue
