### ISSUE TITLE
[R010] Descrizione comune e provincia in stampe

### ISSUE THREAD

**Issue by RosarioSalatiello** [italia/ansc#81]
Buongiorno,
sia in fase di stampa per anteprima che in presa visione il comune e la provincia nell'intestazione dell'atto non vengono valorizzati. Sarebbe possibile sapere quali campi servono affinché la stampa venga compilata correttamente? O si tratta di un bug?

![image](https://user-images.githubusercontent.com/128143833/235853187-d4c044b4-c009-45a3-ad17-6fbea420fe89.png)

Grazie mille,
Rosario

**Comment by RosarioSalatiello** [comment]
ambiente di preproduzione
caso d'uso 11111000
idoperazione 1584583
JWS Payload: {"evento":{"idTipoEvento":"1","idtipocontenuto":"1","idUsecase":"11111000","stato":"BOZZA","dataformazione":"2023-05-03","ora":"11","minuto":"25","operatore":"XXXXXXXXXXXXXXXX","numeroatto":"1","tipoDichiarante":"1","ausilioInterprete":"false","intestatari":[{"cognome":"TEST","nome":"NASCITA","sesso":"M","dataNascita":"2023-05-03","idComuneNascita":"5000","nomeComuneNascita":"LISSONE","idProvinciaNascita":"108","siglaProvinciaNascita":"MB","idStatoNascita":"100","nomeStatoNascita":"XXXXXXXX"}],"madre":{"cognome":"XXXXXXXX","nome":"XXXXXXXX","sesso":"F","dataNascita":"1990-08-15","idComuneNascita":"","nomeComuneNascita":"XXXXXXXX","idProvinciaNascita":"","siglaProvinciaNascita":"EE","idStatoNascita":"436","nomeStatoNascita":"XXXXXXXX","idComuneResidenza":"5000","nomeComuneResidenza":"XXXXXXXX","idProvinciaResidenza":"47","siglaProvinciaResidenza":"PT","idStatoResidenza":"100","nomeStatoResidenza":"XXXXXXXX","idNazionalita":"436","nazionalita":"XXXXXXXX","flagDichiarante":false,"flagComparente":false,"flagFirmatario":false},"padre":{"cognome":"XXXXXXXX","nome":"XXXXXXXX","sesso":"M","dataNascita":"1992-08-24","idComuneNascita":"","nomeComuneNascita":"XXXXXXXX","idProvinciaNascita":"","siglaProvinciaNascita":"EE","idStatoNascita":"436","nomeStatoNascita":"XXXXXXXX","idComuneResidenza":"5000","nomeComuneResidenza":"XXXXXXXX","idProvinciaResidenza":"47","siglaProvinciaResidenza":"PT","idStatoResidenza":"100","nomeStatoResidenza":"XXXXXXXX","idNazionalita":"436","nazionalita":"XXXXXXXX","flagDichiarante":false,"flagComparente":false,"flagFirmatario":false},"dichiarante":{"idStatoNascita":"436"},"datiDichiarante":{"comprensione":"0"},"datiDiNascita":{"luogoFiliazione":"ospedale del comune di LISSONE","oraNascita":"0","minutoNascita":"0","tipoAccertamento":"4"},"composizioneCompleta":" L\u0027anno duemilaventitre addi\u0027 tre del mese di maggio alle ore undici e minuti venticinque nella    casa comunale. Avanti a me, XXXXXXXX, , Ufficiale dello stato civile del Comune di  -------   XXXXXXXX  e\u0027 comparso XXXXXXXX nato in XXXXXXXX li 24.08.1992 residente in XXXXXXXX,  --   cittadino XXXXXXXX il quale mi ha dichiarato quanto segue: ----------------------------------   Il giorno TRE del mese di MAGGIO dell\u0027anno DUEMILAVENTITRE alle ore ZERO e minuti ZERO nel  ---   ospedale del comune di LISSONE da XXXXXXXX nata in XXXXXXXX il 15.08.1990  --   cittadina XXXXXXXX residente in XXXXXXXX moglie del dichiarante, cittadino XXXXXXXX e\u0027  ---   nato un bambino di sesso MASCHILE. ------------------------------------------------------------   A detto bambino che non mi viene presentato, ma della cui nascita io mi sono accertato a mezzo    della attestazione di nascita rilasciata dall\u0027ostetrica il dichiarante dÃ  il nome di NASCITA .    -----------------------------------------------------------------------------------------------   Il presente atto viene letto all\u0027 intervenuto, il quale insieme con me, lo sottoscrive. -------                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            L\u0027UFFICIALE DI STATO CIVILE:                                                                     "},"testataRichiesta":{"idComune":5000}}

**Comment by rfamiglini** [comment]
Buon pomeriggio,
per compilare la stampa di Comune e Provincia di formazione dell'atto servono i seguenti campi da aggiungere alla sezione "evento" del payload:
idComuneRegistrazione
nomeComuneRegistrazione
idProvinciaRegistrazione
siglaProvinciaRegistrazione

In copia un payload di esempio:
 "evento": {
        "idTipoEvento": "1",
        "idtipocontenuto": "1",
        "idUsecase": "11111000",
        "descrizioneCasoUso": "Dichiarazione entro i 10 giorni - resa dal padre",
        "stato": "CONFERMATO",
        "dataformazione": "2022-11-29",
        "dataDecorrenza": "2022-10-29",
        "ora": "18",
        "minuto": "36",
        "annoAtto": "2022",
        "numeroatto": "4323432",
        "tipoDichiarante": "1",
        "ausilioInterprete": "false",
        "idComuneRegistrazione": "1000000",
        "nomeComuneRegistrazione": "ANPR",
        "idProvinciaRegistrazione": "58",
        "siglaProvinciaRegistrazione": "RM",
        "operatore": "CRUMRA67S47Z127B",
        "ruoloOperatore": "2",
        "operatoreNome": "MARIE",
        "operatoreCognome": "CURIE",
        "redattoNellaCasaComunale": true,
        "intestatari": [
            {
                "id": "49933",
                "cognome": "BATISTINI",
                "nome": "Alessio",
                "sesso": "M",
                "dataNascita": "2022-11-28",
                "idComuneNascita": "8165",
                "nomeComuneNascita": "ROMA",
                "idProvinciaNascita": "58",
                "siglaProvinciaNascita": "ROMA",
                "idStatoNascita": "90",
                "nomeStatoNascita": "ITALIA",
                "documentoRiconoscimento": {}
            }
        ],
        "madre": {
            "id": "45686",
            "idsoggettoanpr": "266044",
            "codiceFiscale": "NGLSGL20E41H501I",
            "cognome": "Angela",
            "nome": "Squeglia",
            "sesso": "F",
            "dataNascita": "2020-05-01",
            "idComuneNascita": "8165",
            "nomeComuneNascita": "ROMA",
            "idProvinciaNascita": "58",
            "siglaProvinciaNascita": "RM",
            "idStatoNascita": "90",
            "nomeStatoNascita": "ITALIA",
            "idComuneResidenza": "2780",
            "nomeComuneResidenza": "CESENA",
            "idProvinciaResidenza": "40",
            "siglaProvinciaResidenza": "FC",
            "idStatoResidenza": "90",
            "nomeStatoResidenza": "ITALIA",
            "indirizzoResidenza": "",
            "idNazionalita": "90",
            "nazionalita": "ITALIANA",
            "flagDichiarante": false,
            "flagComparente": false,
            "flagFirmatario": false,
            "documentoRiconoscimento": {}
        },
        "padre": {
            "id": "43500",
            "idsoggettoanpr": "265097",
            "codiceFiscale": "BTSNDR89H28H501Y",
            "cognome": "BATISTINI",
            "nome": "ANDREA",
            "sesso": "M",
            "dataNascita": "1989-06-28",
            "idComuneNascita": "18345",
            "nomeComuneNascita": "ROMA",
            "idProvinciaNascita": "58",
            "siglaProvinciaNascita": "RM",
            "idStatoNascita": "90",
            "nomeStatoNascita": "ITALIA",
            "idComuneResidenza": "2780",
            "nomeComuneResidenza": "CESENA",
            "idProvinciaResidenza": "40",
            "siglaProvinciaResidenza": "FC",
            "idStatoResidenza": "90",
            "nomeStatoResidenza": "ITALIA",
            "indirizzoResidenza": "",
            "idNazionalita": "11",
            "nazionalita": "AUSTRIACA",
            "flagDichiarante": true,
            "flagComparente": false,
            "flagFirmatario": true,
            "documentoRiconoscimento": {}
        },
        "datiDichiarante": {
            "comprensione": "0",
            "motivoImpedimentoScrittura": ""
        },
        "datiDiNascita": {
            "luogoFiliazione": "",
            "sceltaCognome": "1",
            "oraNascita": "18",
            "minutoNascita": "37",
            "precisazioneCognome": "",
            "natoMorto": "NO",
            "natoVivoMaDeceduto": "NO",
            "tipoAccertamento":"1"
        },
        "composizioneCompleta": "L'anno 2022 addì 29 del mese di novembre alle ore 18 e minuti 36 nella Casa Comunale avanti a me, MARIE CURIE Ufficiale dello Stato Civile del Comune di ANPR per delega ricevuta è comparso ANDREA BATISTINI nato in ROMA (RM) il 28/06/1989 con cittadinanza AUSTRIACA residente in CESENA (FC) il quale mi ha dichiarato quanto segue: Il giorno 28 del mese di novembre dell'anno 2022 alle ore 18 e minuti 37 da Squeglia Angela nata in ROMA (RM) il 01/05/2020 con cittadinanza ITALIANA residente in CESENA (FC) moglie del dichiarante, con cittadinanza AUSTRIACA, è nato un bambino di sesso Maschile. A detto bambino che non mi viene presentato, ma della cui nascita io mi sono accertato, il dichiarante dà il nome di Alessio. Il presente atto viene letto agli intervenuti, i quali tutti, insieme con me, lo sottoscrivono.",
        "datains": "2022-11-29T18:36:08.560762",
        "dataultimoagg": "2022-11-29T18:37:42.357608",
        "allegati": [
            {
                "id": {{idAllegatoFlusso01}},
                "idTipoAllegato": 2,
                "idStatoAllegato": 3
            }
        ]
    }

**Comment by RosarioSalatiello** [comment]
Grazie, adesso funziona correttamente
