### ISSUE TITLE
[webapp]: Cittadinanza caso d'uso [5.2.1.2.3] - Errore bloccante

### ISSUE THREAD

**Issue by COlivatoADS** [italia/ansc#816]
### Ambiente

pre-produzione

### Provenienza segnalazione

Software House

### Riferimenti operatore/comune

Faenza

### Data del test (yyyy-mm-dd)

2024-04-09

### Caso d'uso

[5.2.1.2.3] Straniero riconosciuto durante la maggiore età da cittadino italiano

### Descrivi il problema

ID ATTO 1312254
Impossibile validare l'evento
![image](https://github.com/italia/ansc/assets/26922024/2c756cb8-15fe-4304-b046-434ae5afd0c2)

I campi  sono stati compilati correttamente 
![image](https://github.com/italia/ansc/assets/26922024/23a2cca4-d853-4cbf-a9f0-17d424e73391)

A cosa è dovuta la segnalazione?
Grazie
Christian - ADS

**Comment by rvinzani** [comment]
Buongiorno, abbiamo preso in carico la vostra segnalazione. Le faremo sapere appena sarà possibile riprovare

**Comment by asqueglia** [comment]
Buongiorno con la versione 1.28.0 la segnalazione è stata corretta. Chiudiamo pertanto la issue
