### ISSUE TITLE
[R006] Errore Invio Firma Dichiarante

### ISSUE THREAD

**Issue by eschoysman** [italia/ansc#817]
### Ambiente

pre-produzione

### Servizio

R006 - Servizi cooperativi firma dichiarante

### idOperazione

2159397

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Siena 9493

### Data del test (yyyy-mm-dd)

09/04/2024

### Descrivi il problema

In seguito all'invio della R006 ricevo il seguente errore:
```json
{
    "errors": [
        {
            "code": "400003",
            "severity": "E",
            "text": "Non sono stati recuperati firmatari per i dati inseriti"
        }
    ],
    "infos": [
        {
            "code": "110527",
            "severity": "I",
            "text": "Informazioni sull'operazione da fornire in caso di assistenza : data:2024-04-09 14:34:12 , idOperazione:2159397"
        }
    ],
    "testataRisposta": {
        "idComune": 9493,
        "idEsito": 1,
        "idOperazione": "2159397",
        "idOperazioneComune": "11722"
    }
}
```

### Payload (json)

```JSON
{
    "firmaDichiaranteInput": {
        "contenuto": "CONTENUTO_PDF_BASE64",
        "idEvento": "1312285",
        "listaFirmatari": [
            {
                "codiceFiscale": "PPNSRN04A17D612V",
                "cognome": "PAPINI",
                "dataNascita": "2004-01-17",
                "nome": "ASTRONAUTA",
                "sesso": "M"
            },
            {
                "codiceFiscale": "PPNZRR96H54I726G",
                "cognome": "PAPINI",
                "dataNascita": "1996-06-14",
                "nome": "AZZURRA101",
                "sesso": "F"
            },
            {
                "codiceFiscale": "PPNRCR57B18B509W",
                "cognome": "PAPINI",
                "dataNascita": "1957-02-18",
                "nome": "RICCARDO",
                "sesso": "M"
            }
        ],
        "nomefile": "SC156773.pdf",
        "tipoAllegato": "999",
        "tipoFile": "1"
    },
    "testataRichiesta": {
        "dataOraRichiesta": "2024-04-09T14:34:11.282017",
        "fornitoreApplicativo": "SistemiInformativi",
        "idComune": 9493,
        "idOperazioneComune": "11722",
        "nomeApplicativo": "SIDe",
        "versioneApplicativo": "1.0.0"
    }
}
```

**Comment by rvinzani** [comment]
Buongiorno, uno dei dichiaranti inseriti nel servizio di firma (Papini Riccardo) non risulta presente nei dati inviati tramite il servizio di validazione. Restiamo in attesa di una vostra verifica

**Comment by eschoysman** [comment]
Buongiorno,

l'errore di sopra si è risolto.

Tuttavia, ottengo lo stesso messaggio di errore con i seguenti payload:
[PayloadR006.txt](https://github.com/italia/ansc/files/14945420/PayloadR006.txt)
[PayloadR009.txt](https://github.com/italia/ansc/files/14945423/PayloadR009.txt)

Come si può vedere, nella R009 vengono passati due intestatari e due avvocati, tutti come firmatari, e nessun altro soggetto.
La R006, tuttavia, passando gli stessi soggetti come firmatari restituisce l'errore "Non sono stati recuperati firmatari per i dati inseriti".

Potete dare supporto?
