### ISSUE TITLE
[Documentazione]: Errore denominazione campo su model_evento.yaml

### ISSUE THREAD

**Issue by siscomanpr** [italia/ansc#818]
### Ambiente

pre-produzione, produzione

### Servizio

R009 - Servizi cooperativi validazione evento

### idOperazione

nessuno

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Serravalle Sesia

### Descrivi il problema

Buongiorno, 
segnaliamo un errore nella denominazione di un campo nel file model_evento.yaml: 
oggetto: `ModelTrascrizioneNascita`
campo: `dataProvvidementoCambioCognome` che invece dovrebbe essere `dataProvvedimentoCambioCognome`
In fase di validazione il sistema controlla il nome di campo corretto e anche nei files di mapping il campo è corretto. 
Noi abbiamo provveduto a correggere il codice autogenerato dallo yaml, quindi ora riusciamo a validare l'evento, ma converrebbe sistemarlo in caso ci fosse necessità di rigenerare il codice partendo dagli yaml pubblicati.

**Comment by gbuemi** [comment]
Buongiorno,
grazie per la segnalazione, provvediamo ad aggiornare la documentazione.

Un saluto,
Supporto ANSC

**Comment by asqueglia** [comment]
Buongiorno con la versione 1.28.0 la segnalazione è stata corretta. Chiudiamo pertanto la issue
