### ISSUE TITLE
[webapp]: Composizione atto nascita: formula 16

### ISSUE THREAD

**Issue by rvinzani** [italia/ansc#819]
### Ambiente

pre-produzione

### Provenienza segnalazione

Software House

### Riferimenti operatore/comune

Comune di Milano

### Descrivi il problema

La formula 16 riporta: " … (nome e cognome della puerpera), nata in … il … **cittadina italiana** residente in”
Nella composizione ANSC forma la frase nel seguente modo: 
… nata in …  il …, **con cittadinanza ITALIANA**, residente in “

E’ ammissibile questa difformità?

**Comment by rvinzani** [comment]
E' necessario modificare la composizione per renderla uguale a quanto previsto dalla formula

**Comment by asqueglia** [comment]
Buongiorno con la versione 1.28.0 la segnalazione è stata corretta. Chiudiamo pertanto la issue
