### ISSUE TITLE
[SC]: Estratti di matrimonio, comune di nascita

### ISSUE THREAD

**Issue by rvinzani** [italia/ansc#820]
### Ambiente

produzione

### Servizio

R002 - Servizi cooperativi certificazioni

### idOperazione

7697

### idEvento o idAnsc

2024‐7697‐128‐023089

### Provenienza segnalazione

Comune

### Comune di riferimento e operatore

Valeggio sul Mincio

### Descrivi il problema

Abbiamo trascritto degli atti di matrimonio brasiliani, inserendo anche il comune di nascita brasiliano.

La certificazione emessa al termine della redazione, tuttavia, risulta priva di indicazione del dato del comune (pur presente nei metadati), comparendo solo lo stato.

È possibile certificare nell'intestazione anche il luogo di nascita?

**Comment by rvinzani** [comment]
Abbiamo verificato con Anusca che il dato può essere inserito laddove presente. Prendiamo quindi in carico la richiesta

**Comment by asqueglia** [comment]
Buongiorno con la versione 1.28.0 la segnalazione è stata corretta. Chiudiamo pertanto la issue
