### ISSUE TITLE
[SC]: trascr_matr_002 Trascrizione matrimoni dall'estero - Richiesta di trascrizione da parte del Consolato/Ambasciata

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#821]
### Ambiente

pre-produzione

### Servizio

R009 - Servizi cooperativi validazione evento

### idOperazione

2166136

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

ponsacco, anna maraspin

### Descrivi il problema

da mapping l'unico allegato obbligatorio risulta essere la Nota di trasmissione da parte dell'autorità consolare o diplomatica.
Lo abbiamo inviato con esito positivo.
Inviamo la richiesta di validazione atto e ci restituisce l'errore "400003 - Allegato obbligatorio mancante: [Atto estero di nascita originale o copia autentica]".

Ho ricontrollato l'elenco degli allegati previsti nel file di mapping: tale allegato nemmeno è nemmeno mezionato.

Ha ragione il mapping o l'esito dell'invio?

**Comment by rvinzani** [comment]
Salve, prendiamo in carico la vostra segnalazione e vi risponderemo al più presto

**Comment by gbuemi** [comment]
Buongiorno @annamaraspin,
vediamo che nella request è stato inviato idVersion": 100008 corrispondente alla v1.23.x quando era richiesto come obbligatorio l'allegato l'Atto estero di nascita originale o copia autentica.
Dalla versione 1.24.x è stato reso opzionale, quindi aggiornando l'idVersion il comportamento del servizio sarà coerente con la documentazione. 

Condividiamo la issue in cui è stato segnalato il problema sull'allegato in questione https://github.com/italia/ansc/issues/704.

Un saluto,
Supporto ANSC
