### ISSUE TITLE
[SC]: Trascrizione di matrimonio in imminente pericolo di vita durante un viaggio in aereo o nave	(Trascr_Matr_005)

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#826]
### Ambiente

pre-produzione

### Servizio

R009 - Servizi cooperativi validazione evento

### idOperazione

2169377

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

sala bolognese, anna maraspin

### Descrivi il problema

versione ANSC utilizzata 1.23 che dalla tabella 100 dovrebbe avere la retrocompatibilità sino al 19 maggio
cerco di validare l'atto in oggetto e ricevo l'errore (controllo inserito in versione successiva):
400003 - Attenzione! idUseCase e idTipoContenuto non coerenti.

**Comment by rvinzani** [comment]
Buongiorno, potreste per favore verificare la correttezza dell'identificativo dell'operazione in quanto non ci risulta coerente con il caso d'uso indicato. Grazie

**Comment by annamaraspin** [comment]
Buongiorno,
faccio un nuovo atto e Le faccio sapere il nuovo id

**Comment by rvinzani** [comment]
Grazie, prendiamo in carico la vostra segnalazione

**Comment by rvinzani** [comment]
Buongiorno, abbiamo verificato che questo tipo di controllo non è subordinato alla versione utilizzata.
E' quindi necessario inviare in tipo contenuto il valore 3
Chiudo la issue. In caso fossero necessari ulteriori chiarimenti vi preghiamo di riaprire la issue o inserirne una nuova che faccia riferimento a questa
