### ISSUE TITLE
[webapp]: Matrimonio STRANIERI (3.1.1.1.1.1 Matrimonio con rito civile nella casa comunale)

### ISSUE THREAD

**Issue by rvinzani** [italia/ansc#828]
### Ambiente

produzione

### Provenienza segnalazione

Comune

### Riferimenti operatore/comune

Rosignano Marittimo

### Data del test (yyyy-mm-dd)

16/04/2024

### Caso d'uso

[3.1.1.1.1.1] Matrimonio con rito civile nella casa comunale

### Descrivi il problema

Nel caso di matrimoni tra stranieri è necessario prevedere tra le opzioni di scelta (pubblicazione in più comuni, omissione pubblicazioni etc) anche l'opzione
- **Omissione pubblicazioni (stranieri)**
In questo caso non deve comparire la sezione pubblicazioni e nemmeno la sezione Autorizzazione omissione pubblicazioni
Deve comparire una sezione:
**Data rilascio attestazione assenza impedimento al matrimonio (cittadini stranieri)**

Nel campo **Legge regime patrimoniale** deve essere proposta la dicitura:
Gli sposi, alla presenza degli stessi testimoni, mi hanno dichiarato di scegliere la legge .... da applicare ai loro rapporti patrimoniali, ai sensi dell'art. 22 del regolamento UE n 1103/2016

Aggiungere tra gli allegati il certificato delle dichiarazioni per la celebrazione del matrimonio per cittadini stranieri non domiciliati o residenti in Italia rilasciato da questo comune in data

**Comment by rvinzani** [comment]
Si riportano le indicazioni ricevute da ANUSCA:
Nel caso di matrimoni tra stranieri è necessario prevedere tra le opzioni di scelta (pubblicazione in più comuni, omissione pubblicazioni etc) anche l'opzione
- Stranieri non domiciliati né residenti
In questo caso non deve comparire la sezione pubblicazioni e nemmeno la sezione Autorizzazione omissione pubblicazioni
Deve comparire una sezione:

Estremi certificazione (obbligatorio)
Autorità straniera
Tipo documentazione allegata
-	indicare il tipo di documento (nullaosta ex art. 116 o certificato di capacità matrimoniale)


Nel campo Legge regime patrimoniali deve essere proposta la dicitura:

Gli sposi, alla presenza degli stessi testimoni, mi hanno dichiarato di scegliere la legge .... da applicare ai loro rapporti patrimoniali, ai sensi dell'art. 22 del regolamento UE n 1103/2016 (da inserire nella composizione)

Nel campo annotazione contestuale proporre la voce: 

Nella dichiarazione resa nell’atto di matrimonio controscritto gli sposi hanno dichiarato di scegliere la legge .... da applicare ai loro rapporti patrimoniali, ai sensi dell'art. 22 del regolamento UE n 1103/2016

Aggiungere tra gli allegati nullaosta di cui all’art. 116 o documentazione equivalente(obbligatorio)

Nella composizione aggiungere (se presente nullaosta in allegato)
Il documento presentato è ….(riportare la tipologia di certificazione presentata) rilasciato dal ….(Autorità straniera)

Prima della formula di chiusura aggiungere:
Do atto che la pubblicazione non ha avuto luogo trattandosi di stranieri non residenti o domiciliati nello stato

**Comment by asqueglia** [comment]
Buon pomeriggio con il rilascio della versione 1.29.0 la segnalazione è stata corretta. Chiudiamo pertanto la issue
