### ISSUE TITLE
Utilizzo tipoDichiarante del ModelEvento e ruolo del ModelDatiDichiarante

### ISSUE THREAD

**Issue by corradosacco** [italia/ansc#84]
Quale differenza c'è tra il campo **tipoDichiarante** del **ModelEvento** e il campo **ruolo** del **ModelDatiDichiarante**?
Entrambi hanno il dominio ANSC_4 e l'ultimo non lo trovo in nessun caso d'uso mappato.

Cordiali saluti

**Comment by asqueglia** [comment]
Buongiorno, ci scusiamo per il ritardo nella risposta. Confermiamo che tipoDichiarante assume i valori espressi nella tabella di decodifica ANSC_4 mentre ruolo dichiarante è un refuso.
Provvederemo ad aggiornare la documentazione appena possibile.

**Comment by asqueglia** [comment]
Buonasera con la versione 1.11.0 è stata corretta la segnalazione. 
La issue viene chiusa nel caso si prega di riaprirla.
