### ISSUE TITLE
[SC]: Anteprima Annotazione automatica non disponibile.

### ISSUE THREAD

**Issue by gcuci** [italia/ansc#840]
### Ambiente

pre-produzione

### Servizio

R010 - Servizi cooperativi anteprima

### idOperazione

2191302

### idEvento o idAnsc

2024-1313107-00000-039002

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Bagnacavallo

### Data del test (yyyy-mm-dd)

2024-04-24

### Descrivi il problema

Nella Web Application, aprendo la sezione delle Notifiche, è possibile, per ogni Notifica, visualizzarne il pdf, per procedere poi alla gestione, tramite Accettazione o Rifiuto. Questo, sia per Notifiche di tipo Trascrizione, che per quelle di tipo Annotazione automatica.

Per i servizi cooperativi, invece, è possibile recuperare il pdf di anteprima dell'evento notificato, solo per le Notifiche di tipo Trascrizione, mentre non è possibile per le Annotazioni automatiche, in quanto il servizio di Anteprima, restituisce un errore di "Annotazione automatica non approvata...". Ma, anche per i servizi, così come per la Web Application, sarebbe utile prendere visione dell'Annotazione, tramite il pdf, prima di procedere con la Conferma o meno.

E' possibile eliminare questo controllo, e permettere la consultazione del pdf dell'Annotazione, prima della sua effettiva conferma da parte dell'USC?

**Comment by gbuemi** [comment]
Salve @gcuci,
vi chiediamo di riprovare per favore.

Un saluto,
Supporto ANSC

**Comment by gcuci** [comment]
Confermo che adesso, anche nel caso di Notifica di Annotazione automatica, non ancora confermata, il servizio di Anteprima restituisce il pdf dell'Annotazione, passandogli il relativo idAnsc. (idOperazione del test: 2195141).

Grazie
