### ISSUE TITLE
[webapp]: 312111 - Matrimonio su delega di altro comune

### ISSUE THREAD

**Issue by rvinzani** [italia/ansc#841]
### Ambiente

produzione

### Provenienza segnalazione

Comune

### Riferimenti operatore/comune

San Lazzaro di Savena

### Data del test (yyyy-mm-dd)

14/04/2024

### Caso d'uso

312111

### Descrivi il problema

La dicitura e la formula indicati vanno indicati nei matrimoni (ex Parte 1, nei vecchi registri erano prestampati) i quali si celebrano sulla base del certificato di eseguita pubblicazione presentato dagli sposi.
La formula 54 infatti è nel "TITOLO I" del Decreto Ministeriale, riguardante le "FORMULE PER RIEMPIRE GLI SPAZI VUOTI DEI MODULI STAMPATI" 
I matrimoni su delega, formati in parte II Serie C sono su atti in bianco; bisogna quindi seguire il " TITOLO II - FORMULE PER GLI ATTI DA SCRIVERE INTEGRALMENTE SU FOGLI IN BIANCO"
In questo titolo c'è la formula 120 da utilizzare SENZA AGGIUNGERE LA FORMULA 54.
Come già detto non viene presentato per questo tipo di matrimonio alcun certificato di eseguita pubblicazione.
L'indicazione dello stesso mette in condizioni all'ufficiale dello Stato Civile che firma l'atto di scrivere una cosa falsa.
Si continua a suggerire di eliminarla dal testo.

**Comment by rvinzani** [comment]
Si riporta quanto condiviso con gli esperti ANUSCA:
Nella delega del comune che ha effettuato le pubblicazioni deve essere presente l’indicazione di dove sono state effettuate le pubblicazioni e del periodo in cui sono avvenute le pubblicazioni. Queste informazioni devono essere riportate nella trascrizione dell’atto di delega.
Si conferma l’eliminazione della formula 54

**Comment by asqueglia** [comment]
Buon pomeriggio con il rilascio della versione 1.29.0 la segnalazione è stata corretta. Chiudiamo pertanto la issue
