### ISSUE TITLE
[SC]: anomalia testo notifica di tipo annotazione nascita

### ISSUE THREAD

**Issue by antonioluberto** [italia/ansc#844]
### Ambiente

produzione

### Servizio

R008 - Servizi cooperativi notifiche

### idOperazione

non dispinibile

### idEvento o idAnsc

2024-8724-331-058046

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Grottaferrata

### Data del test (yyyy-mm-dd)

29/04/2024

### Descrivi il problema

Caso d'uso  Citt_012.
Il testo della notifica relativa all'annotazione che dovrebbe apporsi sull'atto di nascita del titolare si presenta nella forma:

Con atto del **GROTTAFERRATA** di GROTTAFERRATA (RM) Numero **XXX** in data **dd/mm/yyyy** è stato accertato che %%%%%% %%%%%% è cittadino italiano.

Chiaramente il "primo" GROTTAFERRATA" è errato.
Inoltre:
a) in corrispondenza di **XXX**  si trova attualmente il numero dell'accertamento del Sindaco: qui deve essere riportato il numero dell'atto di cittadinanza.
b) in corrispondenza di **dd/mm/yyyy** si trova attualmente la data dell'accertamento del Sindaco: qui deve essere riportata la data dell'atto di cittadinanza.

**Comment by gbuemi** [comment]
Buongiorno @antonioluberto,
il nome del comune si ripete perché è stata inviata la stringa "GROTTAFERRATA" nel campo evento.trascrizioneCittadinanza.autoritaMittente.nomeEnte. Dovrebbe invece essere riportato in questo caso sarebbe "Comune". A seguire un estratto del payload di validazione ricevuto.

           ` "autoritaMittente": {
                "dataTrascrizione": "AAAA-MM-GG",
                "estremiDocumento": "ABC",
                "idComuneEnte": "4559",
                "idProvinciaEnte": "58",
                "nomeComuneEnte": "GROTTAFERRATA",
                "nomeEnte": "GROTTAFERRATA",
                "siglaProvinciaEnte": "RM"
            }, `

Gli altri due punti sono stati presi in carico.

Per correggere il testo dell'annotazione automatica da centro vi chiediamo di inviarci una PEC con il testo dell'annotazione da impostare.

Grazie e saluti,
Supporto ANSC

**Comment by rvinzani** [comment]
Gent.le Dott. Luberto, da un confronto con gli esperti ANUSCA risulta che sia la composizione dell'atto che dell'annotazione sono corretti. Gli estremi dell'atto devono essere inseriti solo nel riassunto della trascrizione.
Chiudiamo pertanto la issue. Nel caso fossero necessari ulteriori chiarimenti la preghiamo di riaprire la issue o di aprirne una nuova che faccia riferimento alla stessa

**Comment by antonioluberto** [comment]
Buongiorno.
Riapriamo la issue perché qualcosa non ci è ancora chiaro:
se il testo della notifica inviata al Comune: 
_Con atto del Comune di GROTTAFERRATA (RM) Numero **XXX** in data **dd/mm/yyyy** è stato accertato che %%%%%% %%%%%% è cittadino italiano._

le informazioni
 **XXX**
**dd/mm/yyyy**
devono necessariamente - ed esplicitamente - fare riferimento all'atto di cittadinanza e non all'accertamento che ha determinato la redazione dell'atto di cittadinanza medesimo. Detta diversamente, con un esempio: 
se il Comune di Frosinone riceve la notifica:
_Con atto del Comune di GROTTAFERRATA (RM) Numero **XXX** in data **dd/mm/yyyy** è stato accertato che %%%%%% %%%%%% è cittadino italiano._
deve poter essere certo che le informazioni 
_Numero **XXX** in data **dd/mm/yyyy**_ 
siano riferite all'**_atto di cittadinanza_** prodotto a Grottaferrata, non all'accertamento prodotto dal Sindaco di Grottaferrata.
Rimaniamo in attesa di vostro riscontro ulteriore.

**Comment by antonioluberto** [comment]
Buongiorno.
Riapriamo la issue perché qualcosa non ci è ancora chiaro:
se il testo della notifica inviata al Comune:
Con atto del Comune di GROTTAFERRATA (RM) Numero XXX in data dd/mm/yyyy è stato accertato che %%%%%% %%%%%% è cittadino italiano.

le informazioni, rispettivamente:
XXX,
dd/mm/yyyy
devono necessariamente - ed esplicitamente - fare riferimento all'atto di cittadinanza e non all'accertamento che ha determinato la redazione dell'atto di cittadinanza medesimo. Detta diversamente, con un esempio:
se il Comune di Frosinone riceve la notifica:
Con atto del Comune di GROTTAFERRATA (RM) Numero XXX in data dd/mm/yyyy è stato accertato che %%%%%% %%%%%% è cittadino italiano.
deve poter essere certo che le informazioni
Numero XXX in data dd/mm/yyyy
siano riferite all'atto di cittadinanza prodotto a Grottaferrata, non all'accertamento prodotto dal Sindaco di Grottaferrata.
Rimaniamo in attesa di vostro riscontro ulteriore.

Aggiungiamo che anomalia analoga a quella qui in origine descritta si è verificata:

in pre-produzione, per atto 2024-3413610-154-058046

**Comment by rvinzani** [comment]
Salve, sia il caso d'uso di preproduzione 3413610 che quello di produzione 26891 , mi sembra si riferiscano al caso d'uso Citt_004 5.2.1.4.3- Figlio minore di chi ha acquista la cittadinanza italiana e non citt_012. Nello specifico sono presenti solo i riferimenti del documento presenti nella sezione autorità mittente e tali vengono riportati . Analogamente nel citt_012 sono riportati nell'annotazione  i riferimenti presenti nella sezione dell'autorità mittente e non i riferimenti relativi ai dati dell'accertamento (anche se nel vostro caso coincidono). 
Come già detto, consultando gli esperti ANUSCA sembra che questo sia il corretto comportamento
Saluti

**Comment by antonioluberto** [comment]
Buongiorno.
Confermiamo che, in particolare, l' atto 2024-3413610-154-058046 in pre-produzione è riferito al caso d'uso "Citt_004", ma il concetto a nostro avviso rimane il medesimo; riprendendo ancora il medesimo esempio già citato nei post precedenti:
se un qualsiasi Comune terzo riceve la notifica:
_Con atto del Comune di GROTTAFERRATA (RM) Numero XXX in data dd/mm/yyyy è stato accertato che %%%%%% %%%%%% è cittadino italiano_.
deve poter essere certo che le informazioni
Numero **XXX** in data **dd/mm/yyyy**
siano riferite all'atto di cittadinanza prodotto a Grottaferrata, non all'accertamento prodotto dal Sindaco di Grottaferrata.
Ciò detto, valutate voi a questo punto se chiudere eventualmente la issue in ragione delle indicazioni che avete condiviso con Anusca.

**Comment by rvinzani** [comment]
Da un confronto con Anusca, la formula applicata (form. 140) e applicata da ANSC prevede gli estremi dell'accertamento  del sindaco e non i riferimenti della trascrizione dello stesso
