### ISSUE TITLE
[SC]: anomalia testo notifica di tipo annotazione matrimonio

### ISSUE THREAD

**Issue by antonioluberto** [italia/ansc#845]
### Ambiente

produzione

### Servizio

R008 - Servizi cooperativi notifiche

### idOperazione

non dispinibile

### idEvento o idAnsc

2024-8769-345-058046

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Grottaferrata

### Data del test (yyyy-mm-dd)

22/04/2024

### Descrivi il problema

Sono stati redatti ed inviati in ANSC due atti matrimonio:
- uno relativo all'accordo preliminare di scioglimento del matrimonio, ID Atto: 2024-6223-244-058046
- uno relativo alla conferma dell'accordo di scioglimento del matrimonio, ID Atto: 2024-8769-345-058046
L'invio in ANSC della conferma dell'accordo genera la notifica ANSC con il testo:

_Con accordo concluso innanzi all'ufficiale di stato civile del Comune di GROTTAFERRATA, in data 08/03/2024, di cui all'atto iscritto nei registri di matrimonio del predetto ufficio dello stato civile, al n. 244,e confermato con dichiarazioni di cui all'atto iscritto nei predetti registri, al n. 2024-8769-345-058046, è stato sciolto il matrimonio controscritto._

Come si può vedere, nel testo della notifica, quando ci si riferisce all'atto preliminare c'è solo il numero locale dell'atto (244) mentre quando ci si riferisce alla conferma c'è l'id intero (2024-8769-345-058046).

**Comment by asqueglia** [comment]
Buongiorno @antonioluberto, abbiamo analizzato meglio i payload e il sistema.
La formula dell'annotazione configurata a sistema prevede già l'inserimento dell'idAnsc presente nel payload a questo path: evento.separazione.accordoSeparazione.idAnsc
se presente, altrimenti inserisce i dati di cui dispone considerando l'atto associato cartaceo.

In questo caso specifico i dati dell'atto sono stati inseriti manualmente e non ricercati, di conseguenza il sistema si è comportato come se l'atto collegato fosse cartaceo; nello specifico il payload dell'atto con  ID Atto: 2024-8769-345-058046 risulta sprovvisto di evento.separazione.accordoSeparazione.idAnsc.

Chiudiamo pertanto la issue. In caso di ulteriori pèroblemi preghiamo di aprirne una altra dedicata.
