### ISSUE TITLE
[SC]: R009 Errore in validazione usecase 1314 senza genitori

### ISSUE THREAD

**Issue by corradosacco** [italia/ansc#846]
### Ambiente

pre-produzione

### Servizio

R009 - Servizi cooperativi validazione evento

### idOperazione

2198497

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Milano

### Descrivi il problema

Nel validare un evento usecase 1314 senza aver inserito i dati dei genitori riceviamo l'errore:
`Errore chiamata al servizio ANSC: code=400003, severity=E, text=Per proseguire é necessario che il sesso della Madre sia diverso dal sesso del Padre`

**Comment by rvinzani** [comment]
Buongiorno, nel caso non si vogliano indicare i genitori, è necessario non inviare i dati impostati a null

**Comment by corradosacco** [comment]
Buongiorno, attualmente i genitori vengono comunicati a null o con valori "" perchè i flag sono obbligatori, infatti se omettiamo la madre riscontriamo l'errore:
`Errore chiamata al servizio ANSC: code=400003, severity=E, text=Il campo evento.madre.flagDichiarante nella sezione Madre è obbligatorio`
Con quale modalità dobbiamo comunicare il genitore senza dati?

**Comment by rvinzani** [comment]
Salve, inviando solo i dati dei flag a false

**Comment by corradosacco** [comment]
grazie
