### ISSUE TITLE
[SC]: R009 Errore in validazione usecase 1314 senza indicazione del padre

### ISSUE THREAD

**Issue by corradosacco** [italia/ansc#847]
### Ambiente

pre-produzione

### Servizio

R009 - Servizi cooperativi validazione evento

### idOperazione

2198470

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Milano

### Descrivi il problema

Nel validare un evento usecase 1314 in cui è inserita la madre (Nome, Cognome e sesso) ma non il padre riceviamo questo errore:
`Errore chiamata al servizio ANSC: code=400003, severity=E, text=Per proseguire é necessario che il sesso del Padre coincida con il sesso inserito in Atto di nascita del Padre`

**Comment by rvinzani** [comment]
Anche in questo caso, se non si vogliono inviare i dati del padre è necessario non inviare i dati impostati a null
