### ISSUE TITLE
[SC]: R010 Errore in anteprima di atto prenotato

### ISSUE THREAD

**Issue by corradosacco** [italia/ansc#848]
### Ambiente

pre-produzione

### Servizio

R010 - Servizi cooperativi anteprima

### idOperazione

2198542

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Milano

### Descrivi il problema

Nel richiedere l'anteprima dell'atto in compilazione ma già prenotato in quanto il parto è gemellare, riscontriamo il seguente errore:
`Errore chiamata al servizio ANSC: code=400003, severity=E, text=Il campo evento.composizioneCompleta mancante`
Prima della prenotazione, quindi prima del reperimento dell'idAnsc, l'anteprima funziona.

**Comment by corradosacco** [comment]
Ci risulta che tutti i dati obbligatori, inclusa la composizione completa, siano comunicati.

**Comment by asqueglia** [comment]
Buongiorno, abbiamo verificato che l'atto 1613215 prenotato risulta ancora in stato BOZZA e privo della composizione (ossia della minuta) come potete verificare tramite la web app o tramite il servizio di consultazione R005.  Prima di utilizzare il servizio di anteprima R010 è necessario procedere alla conferma e validazione dell'atto, completando la bozza tramite il servizio di validazione R009.

**Comment by corradosacco** [comment]
Abbiamo superato il problema chiamando l'R010 senza inserire id e idAnsc quando l'evento non è completo; in questo modo viene comunque creata l'anteprima con i dati parziali.

Grazie
