### ISSUE TITLE
[SC]: Anteprima certificati -  annotazioni troncate

### ISSUE THREAD

**Issue by asqueglia** [italia/ansc#853]
### Ambiente

produzione

### Servizio

R002 - Servizi cooperativi certificazioni

### idOperazione

NA

### Provenienza segnalazione

Comune

### Comune di riferimento e operatore

Serravalle

### Descrivi il problema

estratto di nascita con annotazione di cittadinanza spaginata.. nell'estratto e nell'anteprima della annotazione , il contenuto risulta troncato.

L'annotazione è stata inserita tramite caso d'uso di servizio

**Comment by asqueglia** [comment]
Rilasciata con versione 1.28.1

**Comment by mttfranci** [comment]
Salve a tutti,

La patch 1.28.1 risolve questo problema.
Notare che questa situazione dipendeva dal fatto che per una composizione completa era stato usato un carattere **NBSP** invece di un normale spazio.
Per evitare comportamenti imprevisti, si consiglia di evitare caratteri NBSP o altri caratteri di controllo se non strettamente necessario.

Saluti

Assistenza ANSC
