### ISSUE TITLE
[R001] Campo descrizione libera per allegato 998

### ISSUE THREAD

**Issue by corradosacco** [italia/ansc#86]
Nei test case di servizio è previsto che l'allegato 998 abbia una descrizione libera; non trovo il campo con cui passare questa descrizione al servizio R001.

Cordiali saluti

**Comment by asqueglia** [comment]
Buongiorno si tratta di un bug che verrà corretto al prossimo rilascio. Faremo sapere prima possibile

**Comment by asqueglia** [comment]
Buongiorno con la versione 1.9.0 appena rilasciata abbiamo corretto l'errore. E' possibile riprovare. chiudiamo la issue in caso vi preghiamo di riaprirla.
