### ISSUE TITLE
[SC]: Trascrizione matrimonio con rito religioso

### ISSUE THREAD

**Issue by asqueglia** [italia/ansc#863]
### Ambiente

produzione

### Servizio

R009 - Servizi cooperativi validazione evento

### idOperazione

NA

### Provenienza segnalazione

Comune

### Comune di riferimento e operatore

Lissone

### Descrivi il problema

valutare se apporre automaticamente l’annotazione contestuale alla data di trascrizione, relativa alla comunicazione dell’avvenuta trascrizione all’ente di culto?

Anusca conferma che è opportuna la compilazione automatica della annotazione contestuale

**Comment by asqueglia** [comment]
Buonasera con la versione 1.32 è stata corretta la segnalazione. Chiudiamo pertanto la issue

**Comment by SilviaRivi** [comment]
Buongiorno,
si chiede maggiori delucidazioni per la comunicazione al ministro di culto.
Si chiede se tale annotazione è da apporre automaticamente sull’atto (ex. 2A) oppure se non è più necessaria?
E se tale annotazione è da apporre esce automaticamente o va caricata manualmente dall'USC?
