### ISSUE TITLE
[SC]: La ricerca per Intestatario, non restituisce il Comune di nascita.

### ISSUE THREAD

**Issue by gcuci** [italia/ansc#865]
### Ambiente

pre-produzione

### Servizio

R005 - Servizi cooperativi consultazione

### idOperazione

2215953

### idEvento o idAnsc

idAnscSoggetto: 2421381

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Bagnacavallo

### Data del test (yyyy-mm-dd)

2024-05-10

### Descrivi il problema

Nei ModelSoggetto restituiti dal servizio, non sono presenti le informazioni sul Comune di nascita, nonostante queste siano correttamente presenti nel sistema, come si può riscontrare con una ricerca per soggetto, dalla Web Application.

**Comment by asqueglia** [comment]
Buongiorno, stiamo verificando e le facciamo sapere appena possibile

**Comment by mttfranci** [comment]
@gcuci dovremmo aver risolto l'anomalia, potreste riprovare?

Grazie in anticipo.
