### ISSUE TITLE
[SC]: R012 problema con Invio email.

### ISSUE THREAD

**Issue by OrazioCostanzo** [italia/ansc#867]
### Ambiente

pre-produzione

### Servizio

R012 - Servizi cooperativi firma elettronica del dichiarante

### idOperazione

assente

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

COMUNETEST052032 - INF.OR

### Descrivi il problema

Sto conducendo dei test sull'invio dei dati al servizio R012 per l'invio di email, come descritto nella specifica qui: 
https://github.com/italia/ansc/blob/main/docs/openapi/R012_firma_dichiarante_elettronica.yaml.
Sto ricevendo una risposta di errore 404001 dal servizio, il quale è mappato con il  codice di errore "DATI_NON_TROVATI" nel documento disponibile qui: https://github.com/italia/ansc/blob/main/docs/openapi/Codici%20d'errore.xlsx (DATA_NOT_FOUND -> 404 -> 404001-> Dati non presenti.)
Presumo che il servizio faccia una ricerca in funzione del nome e cognome all'interno del db, ma sembra che per alcuni nomi e cognomi non riesca a trovare corrispondenze, generando questo errore. Per altri casi, invece, l'operazione si conclude con successo.

**Comment by gbuemi** [comment]
Buongiorno @OrazioCostanzo,
per analizzare la issue è necessario indicare idEvento o idAnsc e/o idOperazione e data del test. 

Grazie,
Supporto ANSC

**Comment by OrazioCostanzo** [comment]
Salve,
ecco i dati richiesti:
idAnsc: 2024-1224244-1699-052032
idEvento: 1224244 
idOperazione non risulta nella testataRisposta

data del test: 15/5/2024

ps. ho fatto diversi test con diversi nomi e cognomi

**Comment by gbuemi** [comment]
Salve @OrazioCostanzo,
abbiamo effettuato le verifiche del caso e vediamo che il firmatario inviato sull'R012 non corrisponde con il dichiarante inviato in fase di validazione evento. Infatti, per l'evento 1224424, il dichiarante risulta essere RICCARDO PAPINI. Nelle varie request inoltrate sono sempre stati inviati soggetti differenti. Vi invitiamo a effettuare un test inviando il soggetto sopraindicato.

Ci impegniamo però a gestire l'errore restituendo un chiaro messaggio di errore al client.

Un saluto,
Supporto ANSC
