### ISSUE TITLE
[SC]: R009 Validazione caso 2102 "401 Errore nella validazione del JWS"

### ISSUE THREAD

**Issue by migmar68** [italia/ansc#870]
### Ambiente

pre-produzione

### Servizio

R009 - Servizi cooperativi validazione evento

### idOperazione

assente

### idEvento o idAnsc

assente

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Sassofeltrio

### Data del test (yyyy-mm-dd)

2024-05-20

### Descrivi il problema

Riceviamo alcune volte da questa chiamata un errore di validazione, che non riusciamo a interpretare. Allego json di una chiamata che è andata in errore 401. Se potete aiutarci a individuare il problema.

### Payload (json)

```JSON
{
	"testataRichiesta": {
		"versioneApplicativo": "1",
		"idComune": 23080,
		"dataOraRichiesta": "2024-05-20",
		"nomeApplicativo": "Jdemos ANSC",
		"fornitoreApplicativo": "Maggioli Spa"
	},
	"evento": {
		"idTipoEvento": "2",
		"minuto": "41",
		"datiDiMorte": {
			"dataMorte": "2024-05-20",
			"idComuneMorte": "23080",
			"nomeStatoMorte": "ITALIA",
			"oraMorte": "0",
			"nomeComuneMorte": "SASSOFELTRIO",
			"siglaProvinciaMorte": "RN",
			"idStatoMorte": "90",
			"idProvinciaMorte": "99",
			"minutoMorte": "0"
		},
		"composizioneCompleta": "L'anno DUEMILAVENTIQUATTRO addi' VENTI del mese di MAGGIO alle ore SEDICI e minuti QUARANTUNO nella Casa Comunale. Io CIUCCI BRUNO Sindaco Ufficiale dello stato civile del Comune di SASSOFELTRIO Sindaco avendo ricevuto dal Direzione sanitaria un avviso di morte con la data 20 MAGGIO 2024, che munito del mio visto, inserisco nel volume degli allegati a questo registro, do atto che:\nIl giorno VENTI del mese MAGGIO dell'anno DUEMILAVENTIQUATTRO alle ore --  e minuti -- in SASSOFELTRIO Casa posta in località Farneto 1A e' morto BARBINI EMANUELE  di cittadinanza ITALIANA residente in SASSOFELTRIO nato in CREMA li 23 NOVEMBRE 2005 e che era CELIBE    \n",
		"idVersion": "100011",
		"idComuneRegistrazione": "099031",
		"allegati": [{
			"hashAllegato": "e+YPR0/0tnmQWX0KcJbsjWwa0+URkgez9LBrdsUFRXU=",
			"descrizione": "alfabetico.pdf",
			"idStatoAllegato": "1",
			"id": "2520652",
			"idTipoAllegato": "32",
			"flagAttestazione": "false"
		}, {
			"hashAllegato": "e+YPR0/0tnmQWX0KcJbsjWwa0+URkgez9LBrdsUFRXU=",
			"descrizione": "alfabetico.pdf",
			"idStatoAllegato": "1",
			"id": "2520653",
			"idTipoAllegato": "35",
			"flagAttestazione": "false"
		}],
		"intestatari": [{
			"siglaProvinciaResidenza": "RN",
			"nomeStatoNascita": "ITALIA",
			"dataNascita": "2005-11-23",
			"cognome": "BARBINI",
			"nazionalita": "ITALIA",
			"codiceFiscale": "BRBMNL05S23D142V",
			"idStatoResidenza": "90",
			"idStatoNascita": "90",
			"nomeComuneResidenza": "CREMA",
			"flagComparente": false,
			"nomeComuneNascita": "CREMA",
			"flagFirmatario": false,
			"flagDichiarante": false,
			"idComuneNascita": "3391",
			"idNazionalita": "100",
			"idProvinciaNascita": "19",
			"descrizionestatocivile": "CELIBE",
			"idComuneResidenza": "3391",
			"idsoggettoanpr": "136941719",
			"idProvinciaResidenza": "19",
			"nome": "EMANUELE",
			"idstatocivile": "1",
			"siglaProvinciaNascita": "CR",
			"nomeStatoResidenza": "ITALIA",
			"sesso": "M"
		}],
		"idUsecase": "2102",
		"idProvinciaRegistrazione": "99",
		"stato": "CONFERMATO",
		"datiEventoMorte": {
			"tipoTrasmissione": "1",
			"descrizioneTrasmissione": "Direzione sanitaria",
			"dataTrasmissione": "2024-05-20",
			"attoNascitaDeceduto": {
				"idProvinciaRegistrazione": "19",
				"siglaProvinciaRegistrazione": "CR",
				"numeroatto": "267",
				"serie": "A",
				"idtipocontenuto": "1",
				"parte": "1",
				"idComuneRegistrazione": "3391",
				"annoAtto": "2005",
				"nomeComuneRegistrazione": "CREMA",
				"tipologia": "1"
			}
		},
		"siglaProvinciaRegistrazione": "RN",
		"numeroatto": "17",
		"idtipocontenuto": "1",
		"dataformazione": "2024-05-20",
		"ora": "16",
		"nomeComuneRegistrazione": "SASSOFELTRIO"
	},
	"datiPaginazione": {
		"numRecordTotali": 0,
		"numRecordPagina": 1,
		"numPagina": 1
	}
}
```

**Comment by gbuemi** [comment]
Buon pomeriggio @migmar68,
vi chiediamo di verificare che il JWT e JWS siano corretti, in tal caso vi chiediamo di fornirci il payload completo comprensivo di header.

Un saluto,
Supporto ANSC

**Comment by migmar68** [comment]
Grazie, questo è un altro caso simile.
[chiamata_validazione_errore_JWS_conheaders.json](https://github.com/italia/ansc/files/15399260/chiamata_validazione_errore_JWS_conheaders.json)

**Comment by gbuemi** [comment]
Grazie mille @migmar68, vi chiediamo gentilmente anche il payload della response per tutti gli approfondimenti 
del caso.

Un saluto,
Supporto ANSC

**Comment by gbuemi** [comment]
@migmar68 vi invitiamo a consultare le FAQ contenute nel documento [SpecificheTecnicheServiziCooperativiJWT_v1.1.1.pdf](https://github.com/italia/ansc/blob/main/docs/Note/SpecificheTecnicheServiziCooperativiJWT/SpecificheTecnicheServiziCooperativiJWT_v1.1.1.pdf)

Aggiungiamo che al contrario del token JWT, il JWS non risulterebbe valido. Come indicato nelle FAQ sopracitate è possibile verificarli tramite il debugger disponibile all’indirizzo jwt.io. Pertanto, vi invitiamo a fare un confronto con le richieste che vengono processate correttamente per analizzare come mai il JWS in alcune chiamate non viene propagato correttamente.

Un saluto,
Supporto ANSC

**Comment by migmar68** [comment]
i colleghi mi hanno aggiunto queste informazioni, grazie intanto

[req_res_errore_val_jws.txt](https://github.com/italia/ansc/files/15401617/req_res_errore_val_jws.txt)

**Comment by gbuemi** [comment]
Grazie @migmar68.
Come anticipato in precedenza, dalla response si evince che è presente un "Errore nella validazione del JWS". Vi invitiamo a seguire quanto riportato nell'ultimo messaggio per effettuare delle verifiche di validità JWT, JWS e sul vostro gestionale. Chiudiamo la issue.

Un saluto e grazie,
Supporto ANSC
