### ISSUE TITLE
Mapping use case 442000 - Manifestazione di volontà di scioglimento dell'unione civile tra persone dello stesso sesso di una sola parte

### ISSUE THREAD

**Issue by MarcoSalaPad** [italia/ansc#872]
### Ambiente

pre-produzione, produzione

### Servizio

R001 - Servizi cooperativi allegati

### idOperazione

assente

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Lissone

### Data del test (yyyy-mm-dd)

2024-05-21

### Descrivi il problema

Buongiorno,
stiamo sviluppando il caso d'uso in oggetto, e abbiamo dei dubbi in merito alla gestione dei metadati di questo atto.
Il caso d'uso prevede che la volontà di scioglimento provenga da una sola delle parti.
Ma in che modo viene definito quale dei due soggetti colui che presenta la richiesta?
Dalla web app abbiamo visto che appena si accede a questo caso d'uso, c'è la possibilità di definire eventuali impedimenti per il coniuge1: questo si intende che di default nel WS chi fa la richiesta è Unito Civilmente 1?

Una volta creato l'atto dalla web app, andando a visualizzare l'atto non si vede da nessuna parte nei metadati chi è la persona che ha presentato questa richiesta di scioglimento...va quindi inteso sempre come il primo soggetto? Se non si legge la minuta dell'atto questa informazione non è presente nei metadati.

**Comment by gbuemi** [comment]
Buon pomeriggio @MarcoSalaPad,
confermiamo che colui che presenta la richiesta è l'Unito civilmente 1.

Un saluto e grazie,
Supporto ANSC
