### ISSUE TITLE
[SC]: Errore 404 R901

### ISSUE THREAD

**Issue by Sem98** [italia/ansc#873]
### Ambiente

pre-produzione

### Servizio

R901 - Servizio di configurazione per il reperibimento delle tabelle di decodifica

### idOperazione

Vuoto

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

9493

### Data del test (yyyy-mm-dd)

22/05/2024

### Descrivi il problema

Buongiorno, provando il serivizio per il recupero dell'elenco decofiche utilizzando la R901 con il payload allegato, riceviamo un errore 404 senza però payload riguardante l'errore.
Nei test abbiamo provato sia ad allegare l'oggetto vuoto DecodificaElencoReqeust sia inviando solo la testata richiesta e l'errore è il medesimo. Come possiamo risolvere?

### Payload (json)

```JSON
{
	"testataRichiesta": {
		"versioneApplicativo": "1.0.0",
		"idOperazioneComune": "14252",
		"idComune": 9493,
		"dataOraRichiesta": "2024-05-22T10:32:37.410792",
		"nomeApplicativo": "SIDe",
		"fornitoreApplicativo": "SistemiInformativi"
	},
	"DecodificaElencoRequest": {}
}
```

**Comment by gbuemi** [comment]
Buon pomeriggio @Sem98,
potete fornirci per favore l'intero URL utilizzato per invocare il servizio?

Grazie,
Supporto ANSC

**Comment by Sem98** [comment]
Buon pomeriggio, continuando con le prove in attesa di risposta abbiamo notato che l'endoint utilizzato era sbagliato, abbiamo provveduto a siostituirlo con quello corretto e funziona tutto come dovrebbe.
