### ISSUE TITLE
[SC]: 11111200  - "Allegato obbligatorio mancante" ma è quello richiesto in base al tipo accertamento

### ISSUE THREAD

**Issue by Hdemografici** [italia/ansc#879]
### Ambiente

pre-produzione

### Servizio

R009 - Servizi cooperativi validazione evento

### idOperazione

2245409

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

assente

### Data del test (yyyy-mm-dd)

2024/05/23

### Descrivi il problema

Buongiorno 
viene segnalato Allegato obbligatorio mancante: [Dichiarazione di nascita sostitutiva resa da dichiarante]
è stato indicato "tipoAccertamento": "3", e tra gli allegati c'è "id": "2522127",
"idTipoAllegato": "3" che corrisponde a "Dichiarazione   di nascita sostitutiva resa da dichiarante"

sembra che ci sia corrispondenza tra il tipo accertamento e l'allegato collegato

ho verificato anche #130

**Comment by gbuemi** [comment]
Buon pomeriggio,
vi invitiamo a consultare la request inviata, ci risulta che l'unico allegato propagato è quello con id 2522128 avente idTipoAllegato=5, e a riprovare, accertandovi di aver propagato tutti gli allegati richiesti.

Per la issue corrente non è essenziale ma vi invitiamo ad aggiornare il campo idVersion all'ultima versione rilasciata consultabile a questo [link](https://github.com/italia/ansc/blob/main/docs/Decodifiche/100_dec_versione.csv).

Un saluto,
Supporto ANSC

**Comment by Hdemografici** [comment]
in realtà nella richiesta 2245409, gli allegati sono 2, riporto la porzione interessata
`"allegati": [ 
{ 
"id": "2522127",
"idTipoAllegato": "3",
"hashAllegato": "5WnWaCEX2z8xIGHysP2otq0DweUp0emnPYK3dLpyLbg=",
"id": "2522128",
"idTipoAllegato": "5",
"hashAllegato": "SeCwLufSOl3sDj/4BNoYWlj+ObQeOj4uj14bQdWWevw="
}
],`

**Comment by gbuemi** [comment]
Il payload inviato non è formalmente corretto, vi invitiamo a validarlo tramite un json validator come per esempio [jsonlint](https://jsonlint.com/)

In particolare l'array di oggetti di tipo allegato non contiene la chiusura del primo oggetto e l'apertura del secondo, e in fase di conversione viene recepito solo il primo dei due allegati. Vi invitiamo a sanare il problema e ripetere il test.

       ` "allegati": [
            {
                "id": "2522127",
                "idTipoAllegato": "3",
                "hashAllegato": "5WnWaCEX2z8xIGHysP2otq0DweUp0emnPYK3dLpyLbg="
            },
            {
                "id": "2522128",
                "idTipoAllegato": "5",
                "hashAllegato": "SeCwLufSOl3sDj/4BNoYWlj+ObQeOj4uj14bQdWWevw="
            }
        ],`

Un saluto,
Supporto ANSC
