### ISSUE TITLE
[SC]: Caratteri accentati - R009 - validazione/evento

### ISSUE THREAD

**Issue by mgasp24** [italia/ansc#880]
### Ambiente

pre-produzione

### Servizio

R009 - Servizi cooperativi validazione evento

### idOperazione

assente

### idEvento o idAnsc

assente

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Sassofeltrio

### Data del test (yyyy-mm-dd)

22/05/2024

### Descrivi il problema

in relazione alla issue #870 abbiamo verificato che il problema si presenta se all'interno delle stringhe ci sono lettere accentate. Vorremmo sapere se ANSC gestisce questi caratteri oppure è necessario normalizzarli (carattere con l'apostrofo). 
L'esempio è riportato nella issue #870 
Grazie

**Comment by gbuemi** [comment]
Buongiorno @mgasp24,
i caratteri accentati possono essere inviati però nell'header Content-Type bisognerebbe indicare anche il charset, per esempio `Content-type: application/json; charset=utf-8`

Un saluto,
Supporto ANSC
