### ISSUE TITLE
[SC]: Notifiche anagrafiche con verifica lato ANPR

### ISSUE THREAD

**Issue by Abstractconstruct** [italia/ansc#881]
### Ambiente

pre-produzione

### Servizio

R008 - Servizi cooperativi notifiche

### idOperazione

Assente

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

SIENA

### Descrivi il problema

Salve,

mi scuso in anticipo per aver già aperto una discussione a riguardo due settimana fa ma che non ha ricevuto risposte.

Volevamo chiedere per quanto riguarda la suddetta attività in cosa consisteva di preciso. Inoltre non ci è chiaro a quali servizi cooperativi è associata.

Saluti,
Rimaniamo in attesa di un Vostro riscontro.

**Comment by amusarra** [comment]
Salve @Abstractconstruct 
Chiudiamo questa issue in quanto è attiva la discussione #862 

Cordiali Saluti.
Supporto ANSC.
