### ISSUE TITLE
[SC]: Metadati non presenti in Estratto e Anteprima

### ISSUE THREAD

**Issue by MarcoSalaPad** [italia/ansc#884]
### Ambiente

pre-produzione, produzione

### Servizio

R002 - Servizi cooperativi certificazioni, R009 - Servizi cooperativi validazione evento, R010 - Servizi cooperativi anteprima

### idOperazione

2252205

### idEvento o idAnsc

2024-2713295-25-108028

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Lissone

### Data del test (yyyy-mm-dd)

2024-05-27

### Descrivi il problema

Buongiorno, 
sia nell'anteprima che nell'estratto per copia integrale non vengono riportati i dati del matrimonio, nonostante questi siano presenti tra i metadati sia in fase di anteprima che validazione.
Abbiamo visto che in alcuni atti presenti in produzione, nell'estratto di matrimonio di questo caso d'uso è presente la sezione "Dati evento matrimonio".

**Comment by asqueglia** [comment]
Buongiorno la segnalazione è stata corretta con il rilascio odierno della versione 1.30.0
