### ISSUE TITLE
[SC]:  Problema con firma USC 

### ISSUE THREAD

**Issue by OrazioCostanzo** [italia/ansc#888]
### Ambiente

pre-produzione

### Servizio

R007 - Servizi cooperativi firma ufficiale di stato civile

### idOperazione

2255142

### idEvento o idAnsc

2614093

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

COMUNETEST052032 - INF.OR

### Data del test (yyyy-mm-dd)

2024-05-28

### Descrivi il problema

Salve,
Sto provando a contattare la R007 dopo aver effettuato la firma dichairante digitale con la R012. Il servizio mi risponde con un errore: "Mancata attestazione di conformità degli allegati.".  Nella webapp c'e' un passaggio intermedio tra la firma dichairante e la firma usc, questo passaggio e' "l'attestazione di conformita'". /vorrei sapere qual'e' il servizio che gestisce questo evento.
Grazie.

**Comment by asqueglia** [comment]
Buongiorno, il servizio da invocare per la firma dell'attestazione di conformità è l'R007 operation attestazione/firma/? mentre se volete l'anteprima dell'attestazione di conformità automaticamente generata dal sistema il servizio da utilizzare è R010 operation /anteprima/attestazione/?

**Comment by OrazioCostanzo** [comment]
Grazie.
Buona giornata.
