### ISSUE TITLE
modelSoggetto - campi sesso e genere

### ISSUE THREAD

**Issue by corradosacco** [italia/ansc#89]
Vediamo che nel **ModelSoggetto** sono presenti due campi 
- **sesso** (codice + descrizione)
- **genere** (ANSC_05)
in quali casi devono essere utilizzati?

Cordiali saluti

**Comment by asqueglia** [comment]
Buongiorno si tratta di un refuso nella documentazione che provvederemo a correggere nel prossimo rilascio.

**Comment by asqueglia** [comment]
Buongiorno, la segnalazione è stata corretta con la versione 1.8.0 appena rilasciata.
