### ISSUE TITLE
[SC]: evento.datiAdozioneMinoriInternazionale mancante

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#893]
### Ambiente

pre-produzione, produzione

### Servizio

R009 - Servizi cooperativi validazione evento, R010 - Servizi cooperativi anteprima

### idOperazione

-

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Lissone - biadanpad

### Data del test (yyyy-mm-dd)

29-05-2024

### Descrivi il problema

Buongiorno, 

stiamo tentando di implementare il caso d'uso 14950000 - Annotazione per adozione internazionale di minore - Dic_Nasc_998_4.

Il mapping del caso d'uso fa riferimento all'oggetto datiAdozioneMinoriInternazionale che però non è definito nella classe ModelEvento.

Non possiamo quindi procedere all'implementazione.

**Comment by gbuemi** [comment]
Buon pomeriggio @biadanpad,
provvederemo ad aggiornare quanto prima il ModelEvento, grazie per la segnalazione.

Inoltre confermiamo che potete implementare il caso d'uso così come indicato sul mapping del caso d'uso Dic_Nasc_998_4.

Un saluto,
Supporto ANSC

**Comment by gbuemi** [comment]
Salve @biadanpad,
vi comunichiamo che la documentazione è stata aggiornata.

Un saluto,
Supporto ANSC
