### ISSUE TITLE
[SC]: Consultazione ANSC [R005] - La ricerca per Intestatario, non restituisce la località estera di nascita, nel caso di cittadino nato all'estero.

### ISSUE THREAD

**Issue by gcuci** [italia/ansc#895]
### Ambiente

pre-produzione

### Servizio

R005 - Servizi cooperativi consultazione

### idOperazione

2258238

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Bagnacavallo

### Data del test (yyyy-mm-dd)

2024-05-28

### Descrivi il problema

Nel ModelSoggetto restituito dal servizio, non è presente l'informazione della località estera di nascita, nel caso di cittadino nato all'estero, nonostante questa sia correttamente presente nel sistema, come si può riscontrare con una ricerca per soggetto, dalla Web Application.

**Comment by gbuemi** [comment]
Salve @gcuci,
provvederemo ad aggiornare la documentazione, non è prevista la restituzione della località estera di nascita.

Un saluto e grazie,
Supporto ANSC
