### ISSUE TITLE
[SC]: URGENTE versione 1.28.8! mapping matr_riconc_001 ritornato pre modifiche 1.28.4

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#897]
### Ambiente

pre-produzione

### Servizio

R009 - Servizi cooperativi validazione evento

### idOperazione

---------------------

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

ponsacco, anna maraspin

### Descrivi il problema

Buongiorno,
il mapping di matr_riconc_001 nella versione 1.28.8 è ritornato ad essere senza le modifiche che erano state fatte nella 1.28.4 (aggiunta di tag vari).
Abbiamo fatto lavoro inutile?
si prega di avere una risposta in tempi brevi in quanto a breve rilasceremo una versione come vi abbiamo accennato nella riunione di pochi giorni fa.
[Matr_Riconc_001_1_28_
[Matr_Riconc_001_1_28_4.xlsx](https://github.com/user-attachments/files/15511284/Matr_Riconc_001_1_28_4.xlsx)
8.xlsx](https://github.com/user-attachments/files/15511264/Matr_Riconc_001_1_28_8.xlsx)

grazie

allego sia excel della 1.28.4 che della 1.28.8

**Comment by amusarra** [comment]
Salve @annamaraspin 
Si, stiamo verificando ma probabilmente c'è stato un errore nella documentazione pubblicato.
Nel prossimo rilascio sarà sistemata.

Cordiali Saluti.
Supporto ANSC.

**Comment by annamaraspin** [comment]
Ok, quindi le modifiche effettuate nella 1.28.4 sono corrette
grazie

**Comment by amusarra** [comment]
Salve @annamaraspin 
Adesso la documentazione di mapping è quella corretta. 

Cordiali Saluti.
Supporto ANSC.
