### ISSUE TITLE
[SC]: R006 / R012 non funzionanti

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/ansc#899]
### Ambiente

pre-produzione

### Servizio

R006 - Servizi cooperativi firma dichiarante, R012 - Servizi cooperativi firma elettronica del dichiarante

### idOperazione

r012: 2024003723 - r006: 2024003724 

### idEvento o idAnsc

2024-2713694-132-039010

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

FAENZA

### Data del test (yyyy-mm-dd)

2024-05-31

### Descrivi il problema

i servizi di firma dichiarante (sia cartacea che elettronica) sembra non stiano funzionando in questo momento.
non otteniamo risposta.
gli altri servizi invece mi risultano funzionare correttamente correttamente

potete verificare per piacere?
grazie
Alessandro ADS

**Comment by asqueglia** [comment]
Buon pomeriggio, stiamo in fase di rilascio per cui c'è stato un momentaneo disservizio. Potete riprovare. Chiudiamo pertanto la issue
