### ISSUE TITLE
[SC]: Annotazione automatica non approvata

### ISSUE THREAD

**Issue by Abstractconstruct** [italia/ansc#903]
### Ambiente

pre-produzione

### Servizio

R010 - Servizi cooperativi anteprima

### idOperazione

2268297

### idEvento o idAnsc

2024-2613593-00000-052032

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

SIENA

### Data del test (yyyy-mm-dd)

2024-06-03

### Descrivi il problema

Salve,

Fino alla settimana scorsa era possibile recuperare l'artefatto pdf di un'annotazione automatica recuperata da una notifica non ancora approvata.

E' cambiato il flusso di gestione di una notifica di un'annotazione automatica da gestire tramite PEC? Da documentazione e issue vecchi, pensavo fosse necessario assicurarsi (fino alla scorsa settimana era possibile recuperare il pdf prima di approvare) di inviare al comune di competenza prima di approvare la notifica. Quindi per il momento solo approvando la notifica si può scaricare il pdf.

Saluti,
Rimaniamo in attesa di un Vostro riscontro.

### Come riprodurre il problema

Eseguire la r010 su un id ansc associato ad un'annotazione automatica recuperata da una notifica non ancora approvata

### Payload (json)

```JSON
{"testataRichiesta":{"versioneApplicativo":"1.0.0","idOperazioneComune":"14985","idComune":9493,"dataOraRichiesta":"2024-06-03T09:53:41.355907","nomeApplicativo":"SIDe","fornitoreApplicativo":"SistemiInformativi"},"evento":{"operatoreNome":"xxx","idAnsc":"2024-2613593-00000-052032","idVersion":"100008","operatoreCognome":"xxx","operatore":"xxx","idUsecase":"11999999"},"presaVisione":"true"}


{"testataRisposta":{"idComune":9493,"idOperazioneComune":"14985","idOperazione":"2268297"},"errors":[{"code":"407001","severity":"E","text":"Annotazione automatica non approvata..."}],"infos":[{"code":"110527","severity":"I","text":"Informazioni sull'operazione da fornire in caso di assistenza : data:2024-06-03 09:53:42 , idOperazione:2268297"}]}
```

**Comment by gbuemi** [comment]
Buonasera,
il flusso non è stato modificato, e adesso è possibile recuperare l'anteprima di un'annotazione automatica non ancora approvata.

Un saluto,
Supporto ANSC
