### ISSUE TITLE
[SC]: R012 vs R006 - sincronizzazione del tipo di firma e controlli sistema centrale 

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/ansc#904]
### Ambiente

pre-produzione

### Servizio

R006 - Servizi cooperativi firma dichiarante, R012 - Servizi cooperativi firma elettronica del dichiarante

### idOperazione

2268571

### idEvento o idAnsc

2024-2813195-133-039010

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

FAENZA

### Data del test (yyyy-mm-dd)

2024-06-03

### Descrivi il problema

vi segnalo alcune note riguardo il flusso di firma dichiarante, nei casi in cui si passi da firma elettronica a firma cartacea.

atto di nascita con unico dichiarante padre.
1. definisco la modalità di firma elettronica ed invio il link di conferma visione (ws R012 - Invio mail)
2. il dichiarante non riesce a dare la conferma (ad esempio per i problemi che ci sono da venerdì pomeriggio, ma in generale potrebbe succedere che per qualche ragione il dichiarante non riesca a firmare)
3. annullo il link (ws R012 - annulla link) e decido di inviare la dichiarazione cartacea
4. verifico lo stato della presa visione (ws R012 - verifica stato) e ottengo conferma la richiesta è in stato annullato
5. invio la dichiarazione firmata in cartaceo (ws R006) ed il servizio mi risponde con errore "Non ci sono firmatari per evento"

dalle prove fatte, il sospetto è che il sistema non senta l'avvenuto annullamento della presa visione, e che attenda ancora il perfezionamento del processo di firma elettronica (dubbio sostenuto anche dal fatto che, se richiedo nuovamente l'anteprima dell'atto con ws R010, il firmatario risulta ancora di tipo "Online", nonostante l'avvenuto annullamento).
se questo fosse vero (cioè che il sistema sente ancora che il tipo di firma deve essere elettronico), allora anche il messaggio di errore (rif. punto '5.') è fuorviante: non è vero che "non ci sono firmatari per evento", ma "non ci sono firmatari DI TIPO CARTACEO per l'evento" 
quest'ultimo è solo un problema di forma della messaggistica - che servirebbe a chiarire meglio la situazione... -, ma di fatto quello che si vuole segnalare è che no sono riuscito a passare da firma elettronica a firma cartacea.

chiedo indicazioni per capire dove sia il problema che blocca il processo.

grazie
Alessandro ADS

**Comment by asqueglia** [comment]
Buongiorno verifichiamo e e facciamo sapere

**Comment by asqueglia** [comment]
Buon pomeriggio abbiamo verificato la segnalzione replicandola in sviluppo. Il comportamento, da voi riscontrato,  si verifica quando si invoca il servizio di firma cartacea del dichiarante R006, senza passare esplicitamente i firmatari. Per consentire ai vari possibili firmatari di scegliere una qualunque modalità di firma, il servizio R006, se invocato senza specificare i firmatari, prende in considerazione i soli firmatari che avevano dichiarato di firmare in cartaceo e non quelli che avevano dichiarato di firmare in digitale; anche se, infatti,  il link è stato annullato, è sempre possibile riprovare la firma digitale con l'invio di un nuovo link. 
Per recuperare il firmatario, cambiando metodo di firma, è necessario invocare il servizio di firma cartacea R006 firmadichiarante/upload/{versione} esplicitando i dati del firmatario; di seguito un esempio

"firmaDichiaranteInput": {
        "contenuto": {{base64Allegato}},
        "nomefile": {{nomeFile}},
        "idEvento": {{idEvento}},
        "tipoFile": "1",
        "tipoAllegato": "999",
        "stato": "1",
        "listaFirmatari": [
          {
          "nome": {{nomeFirmatario}},
          "cognome": {{cognomeFirmatario}},
          "sesso": {{sessoFirmatario}},
          "dataNascita": {{dataNascitaFirmatario}}
          }
        ]
      }
    }

Consigliamo quindi di invocare il servizio come indicato.

**Comment by AMonopoliADS** [comment]
dalle prove fatte abbiamo anche notato che se si ripete la validazione dell'atto (ws R009) viene in qualche modo ripristinata la situazione iniziale in cui i firmatari vengono interpretati come "cartacei" (nonostante il json di validazione sia sostanzialmente lo stesso).
è corretta come interpretazione?
dopo la validazione, infatti, l'invio della dichiarazione firmata (ws R006) va a buon fine senza segnalazioni e senza indicare la lista dei firmatari.
se non lo considerate un bug, valutate almeno la richiesta di dettagliare meglio il messaggio di errore perchè può risultare fuorviante.

grazie

**Comment by asqueglia** [comment]
ok Valuteremo di dettagliare meglio il messaggio di ritorno. Chiudiamo pertanto la issue.
