### ISSUE TITLE
[SC]: Nuove casistiche vers.1.29

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#905]
### Ambiente

pre-produzione

### Servizio

R009 - Servizi cooperativi validazione evento

### idOperazione

....

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

ponsacco, anna maraspin

### Descrivi il problema

Buongiorno,
nel file  3_dec_use_case all'interno della cartella MAPPING non trovo i nuovi codici (provato sia nel csv che nel xls) per trovare il nome alfanumerico associato

![image](https://github.com/italia/ansc/assets/127182190/f1570341-d35e-45fe-ba35-971f0e9d9e33)

**Comment by asqueglia** [comment]
Buongionro provvediamo subito ad aggiornare la documentazione le faremo sapere appena disponibile
