### ISSUE TITLE
[SC]: URGENTE - Annullamento Link Firma Elettronica - Errore di TimeOut

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#906]
### Ambiente

pre-produzione, produzione

### Servizio

R012 - Servizi cooperativi firma elettronica del dichiarante

### idOperazione

non ricevo risposta

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Lissone - biadanpad

### Data del test (yyyy-mm-dd)

2024-06-04

### Descrivi il problema

Il servizio di annullamento del link per la firma elettronica va in timeout.

La request allegata è relativa ad un tentativo fatto nell'ambiente di pre-produzione, ma lo stesso errore è stato riscontrato dal comune in produzione

### Payload (json)

```JSON
REQUEST:
{
    "idPresaVisione": "2525723",
    "testataRichiesta": {
        "idComune": 5000,
        "idOperazioneComune": "5994",
        "dataOraRichiesta": "2024-06-04T09:37:46.197+02:00",
        "nomeApplicativo": "urbi",
        "versioneApplicativo": "1.3.4",
        "fornitoreApplicativo": "padigitale"
    }
}
```

**Comment by gbuemi** [comment]
Buon pomeriggio @biadanpad,
il problema dovrebbe essere rientrato, chiudiamo la issue.

Un saluto,
Supporto ANSC

**Comment by biadanpad** [comment]
Buonasera, 
ci segnala il comune che il problema persiste.

Vi prego di verificare ed accertarvi della risoluzione del problema prima di chiudere nuovamente la issue: il nostro cliente è solito utilizzare la firma elettronica ed ha bisogno di sapere con sicurezza se può sfruttarla o meno.

**Comment by gbuemi** [comment]
Buonasera @biadanpad,
vi comunichiamo che abbiamo verificato la risoluzione prima di rispondere, in preproduzione il problema non si è verificato dopo il rilascio. In produzione non possiamo firmare atti e, grazie alla vostra segnalazione, abbiamo visto che c'è stato un problema in fase di rilascio della nuova versione sul solo ambiente di produzione.

Confermiamo adesso l'avvenuto rilascio anche in produzione.

Un saluto e grazie,
Supporto ANSC
