### ISSUE TITLE
[SC]: URGENTE - Firma Dichiarante Elettronica - Link Non Valido

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#907]
### Ambiente

pre-produzione, produzione

### Servizio

R012 - Servizi cooperativi firma elettronica del dichiarante

### idOperazione

-

### idEvento o idAnsc

2813256

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Lissone - biadanpad

### Data del test (yyyy-mm-dd)

2024-06-04

### Descrivi il problema

La mail arriva regolarmente, ma il link non è valido:

![image](https://github.com/italia/ansc/assets/131870281/64a36a45-a6c0-4776-b654-d2156986e5fc)

L'idEvento è relativo ad un test eseguito in pre-produzione, ma lo stesso problema ci è stato segnalato dal comune anche in produzione.

### Payload (json)

```JSON
REQUEST:
{
    "emailDichiarante": "xxx.xxx@xxx.xxx",
    "idEvento": "2813256",
    "idAnsc": "2024-2813256-30-108028",
    "firmatario": {
        "cognome": "XXX",
        "nome": "XXX"
    },
    "testataRichiesta": {
        "idComune": 5000,
        "idOperazioneComune": "5994",
        "dataOraRichiesta": "2024-06-04T09:36:14.01+02:00",
        "nomeApplicativo": "urbi",
        "versioneApplicativo": "1.3.4",
        "fornitoreApplicativo": "padigitale"
    }
}

RESPONSE:
{
    "esito": {
        "codice": "200",
        "descrizione": "Ok"
    },
    "testataRisposta": {
        "idComune": 5000,
        "idEsito": 0,
        "idOperazioneComune": "5994"
    },
    "idPresaVisione": "2525723"
}
```

**Comment by gbuemi** [comment]
Buon pomeriggio @biadanpad,
il problema dovrebbe essere rientrato, chiudiamo la issue.

Un saluto,
Supporto ANSC

**Comment by biadanpad** [comment]
Buonasera, 
ci segnala il comune che il problema persiste.

Vi prego di verificare ed accertarvi della risoluzione del problema prima di chiudere nuovamente la issue: il nostro cliente è solito utilizzare la firma elettronica ed ha bisogno di sapere con sicurezza se può sfruttarla o meno.
