### ISSUE TITLE
[SC]: Annullamento Atto - Errore Timeout

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#908]
### Ambiente

pre-produzione, produzione

### Servizio

R011 - Servizi cooperativi per la cancellazione logica di un atto

### idOperazione

non ricevo risposta

### idEvento o idAnsc

15108

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Lissone - biadanpad

### Data del test (yyyy-mm-dd)

2024-06-04

### Descrivi il problema

Il servizio va in timeout.

L'idEvento è relativo all'ambiente di produzione, ma riscontriamo lo stesso problema in pre-produzione

### Payload (json)

```JSON
REQUEST:
{
    "evento": {
        "id": "15108",
        "idAnsc": "2024-15108-72-108028",
        "idVersion": "100012",
        "operatore": "PRVNLT87B66A794S",
        "operatoreNome": "NICOLETTA",
        "operatoreCognome": "PREVITALI"
    },
    "testataRichiesta": {
        "idComune": 5000,
        "idOperazioneComune": "6146",
        "dataOraRichiesta": "2024-06-04T09:02:18.62+02:00",
        "nomeApplicativo": "urbi",
        "versioneApplicativo": "1.3.3",
        "fornitoreApplicativo": "padigitale"
    }
}
```

**Comment by amusarra** [comment]
Salve @biadanpad 
Abbiamo verificato che si è trattato di un problema temporaneo.

Vi chiediamo di riprovare e in caso di ulteriori errori riaprire la issue.

Cordiali Saluti.
Supporto ANSC.
