### ISSUE TITLE
[SC]: Errore firma USC - urgente

### ISSUE THREAD

**Issue by siscomanpr** [italia/ansc#910]
### Ambiente

produzione

### Servizio

R007 - Servizi cooperativi firma ufficiale di stato civile

### idOperazione

146105 - 146506

### idEvento o idAnsc

15109

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

LOANO

### Descrivi il problema

Questa mattina il comune di Loano sta rilevando problemi nella fase di firma di un atto di nascita di pre-riconoscimento.
L'errore si presenta nella fase di firma USC. In un primo momento, come errore restituiva: 
`400103 | USC dell'operazione di firma diverso da chi ha firmato l'attestazione` (idoperazione 146105) (nonostante l'operatore era lo stesso che aveva firmato l'attestazione pochi secondi prima);
poi ha iniziato a dare:
`400003 | Stato evento non valido per l'operazione richiesta: lo stato deve essere CONFERMATO se l'atto non prevede firmatari altrimenti FIRMATO DAL DICHIARANTE.` (idoperazione 146506);
Da una verifica sui LOG la firma dell'attestazione aveva dato un errore di timeout, ma lo stato dell'atto risulta comunque essere FIRMATO PER CONFORMITA'.

Aggiungo che ora consultando l'evento 15109 con il servizio R005 restituisce errore: `401003 | Evento non modificabile`

Potete verificare urgentemente il motivo di questi errori visto che il problema si presenta sull'ambiente di produzione? 

Grazie
Siscom SPA per il comune di Loano

**Comment by mttfranci** [comment]
@siscomanpr  stavamo verificando il problema, ma ci sembra che l'evento coinvolt (15109) sia stato cancellato?
Nel caso specifico avere già risolto in qualche modo?
Saluti

**Comment by siscomanpr** [comment]
Da una verifica sui log del nostro software, tra le richieste inviate, non ci risulta sia stato chiamato il servizio R011. Contattiamo il comune per capire se è stato fatto qualcosa sul portale.
A voi risulta effettivamente cancellato?

**Comment by siscomanpr** [comment]
Scusate se insisto, ma prima di procedere vorremmo essere sicuri sia noi che il comune:
L'evento con id 15109 in effetti ora non è più visibile sul portale web di ANSC, quindi probabilmente l'operatore (che non ricorda quali operazioni ha fatto con certezza) l'ha cancellato involontariamente direttamente da webapp.
Se ci confermate che è stato effettivamente cancellato, provvederemo a rimuoverlo anche dalla banca dati locale e comunico al comune che deve procedere nuovamente con il caricamento dell'atto.
Grazie.

**Comment by mttfranci** [comment]
@siscomanpr  si stavamo terminando anche queste verifiche.

A noi risulta una operazione da web app alle 9.24 circa sull'evento {"idEvento":15109}.
Tale operazione ha comportanto la cancellazione dell'evento.

Saluti

Assistenza ANSC.

**Comment by siscomanpr** [comment]
Grazie, procediamo con un nuovo caricamento dell'atto.
