### ISSUE TITLE
[SC]: firma dichiarazione conformità - errore

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#912]
### Ambiente

pre-produzione

### Servizio

R007 - Servizi cooperativi firma ufficiale di stato civile

### idOperazione

2277320

### idEvento o idAnsc

2024-2713600-246-050028

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

ponsacco, anna maraspin

### Data del test (yyyy-mm-dd)

2024-06-05

### Descrivi il problema

test con versione 1.28 dello usecase SEP_DIV_003

Non riesco a capire perché cade, potete aiutarmi?

**Comment by amusarra** [comment]
Salve @annamaraspin 
Abbiamo preso in carico la segnalazione.

Cordiali Saluti.
Supporto ANSC.

**Comment by asqueglia** [comment]
Buongiorno, con la patch 1.29.5 è stata risolta la segnalazione. Chiudiamo pertanto la issue
