### ISSUE TITLE
[SC]: R001 Verifica Allegato

### ISSUE THREAD

**Issue by OrazioCostanzo** [italia/ansc#917]
### Ambiente

pre-produzione

### Servizio

R001 - Servizi cooperativi allegati

### idOperazione

2280138

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

COMUNETEST052032 - INF.OR

### Data del test (yyyy-mm-dd)

2024-06-06

### Descrivi il problema

Saleve, 
sto cercando di inviare un nuovo atto di nascita, specificamente il caso 11112000. Tuttavia, alla prima richiesta di verifica dell'allegato, il servizio risponde con "statoAllegato" = 5 (In elaborazione). Nelle richieste successive, lo "statoAllegato" rimane 1 (Ricevuto).

Non dovrebbe lo "statoAllegato" diventare 3 (Inserito) per indicare che è stato completamente inserito nel sistema?
Grazie.

### Payload (json)

```JSON
PRIMA RISPOSTA:
{
   "testataRisposta":{
      "idComune":9493,
      "idOperazioneComune":"15340",
      "idOperazione":"2280173",
      "idEsito":0
   },
   "infos":[
      {
         "code":"110527",
         "severity":"I",
         "text":"Informazioni sull'operazione da fornire in caso di assistenza : data:2024-06-06 10:34:28 , idOperazione:2280173"
      }
   ],
   "allegatoOutput":{
      "idAllegato":"2526711",
      "statoAllegato":"5",
      "idDocumentum":null
   }
}

SUCCESSIVE RISPOSTE:
{
   "testataRisposta":{
      "idComune":9493,
      "idOperazioneComune":"15344",
      "idOperazione":"2280193",
      "idEsito":0
   },
   "infos":[
      {
         "code":"110527",
         "severity":"I",
         "text":"Informazioni sull'operazione da fornire in caso di assistenza : data:2024-06-06 10:38:37 , idOperazione:2280193"
      }
   ],
   "allegatoOutput":{
      "idAllegato":"2526711",
      "statoAllegato":"1",
      "idDocumentum":null
   }
}
```

**Comment by OrazioCostanzo** [comment]
Ok, Grazie.

**Comment by mttfranci** [comment]
@OrazioCostanzo l'anomalia dovrebbe essere rientrata.

Saluti

Assistenza ANSC
