### ISSUE TITLE
[SC]: Richiesta chiarimenti sull'utilizzo dell'idVersion del Model Evento, nel servizio di Validazione.

### ISSUE THREAD

**Issue by gcuci** [italia/ansc#918]
### Ambiente

pre-produzione

### Servizio

R009 - Servizi cooperativi validazione evento

### idOperazione

2282609

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Bagnacavallo

### Data del test (yyyy-mm-dd)

2024-06-07

### Descrivi il problema

Non ci è molto chiaro, come venga gestito l'idVersion del Model Evento.

Con il rilascio 1.27.0 del 27-03-2024, sono state introdotte delle modifiche al Model Evento (tra queste, la proprietà 'evento.trascrizioneCittadinanza.flagCambioGeneralita', ed il nuovo ModelSoggetto, 'evento.trascrizioneCittadinanza.intestatarioVecchieGeneralita'), e contestualmente rilasciata la versione '100011'.

Attualmente noi utilizziamo l'idVersion: '100010' (passeremo tra breve alle più recenti, comunque la versione è indicata come valida sino al 23-06-2024), e stiamo riscontrando delle anomalie, nella validazione dei casi d'uso Citt_045 e Citt_046, collegate alle modifiche del Model Evento, indicate su.
Sino alla settimana scorsa le validazioni funzionavano correttamente (vd. validazione con idOperazione='2258116', effettuata in data 28-05-2024), mentre durante alcuni test effettuati oggi, ci vengono restituiti degli errori di campi obbligatori mancanti, su 'flagCambioGeneralita' e 'intestatarioVecchieGeneralita' (vd. validazione con idOperazione='2282609').

Come dobbiamo interpretare queste risposte? Non è corretta la nostra interpretazione dell'idVersion, o il servizio non lo sta gestendo correttamente?

**Comment by gbuemi** [comment]
Buongiorno @gcuci,
il servizio di validazione al momento non sta gestendo correttamente l'idVersion. Abbiamo preso in carico la segnalazione e seguiranno aggiornamenti in merito.

Grazie e saluti,
Assistenza ANSC

**Comment by asqueglia** [comment]
Buongiorno con la versione 1.29.4 il problema è stato corretto. Pertanto chiudiamo la issue
