### ISSUE TITLE
[SC]: Anteprima per presa visione - Dati in ingresso non corretti

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#919]
### Ambiente

produzione

### Servizio

R010 - Servizi cooperativi anteprima

### idOperazione

156603

### idEvento o idAnsc

2024-15526-159-108028

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Lissone - biadanpad

### Data del test (yyyy-mm-dd)

2024-06-10

### Descrivi il problema

tentando di scaricare l'anteprima per presa visione si ottiene l'errore in oggetto

### Payload (json)

```JSON
REQUEST:
{
  "presaVisione": true,
  "evento": {
    "idAnsc": "2024-15526-159-108028",
    "idVersion": "100012",
    "operatore": "XXXX",
    "operatoreNome": "XXXX",
    "operatoreCognome": "XXXX"
  },
  "testataRichiesta": {
    "idComune": 5000,
    "idOperazioneComune": "12090",
    "dataOraRichiesta": "2024-06-10T12:25:43.341+02:00",
    "nomeApplicativo": "urbi",
    "versioneApplicativo": "1.3.3",
    "fornitoreApplicativo": "padigitale"
  }
}

RESPONSE:
{
  "testataRisposta": {
    "idComune": 5000,
    "idOperazioneComune": "12090",
    "idOperazione": "156603",
    "idEsito": 1
  },
  "errors": [
    {
      "code": "400003",
      "severity": "E",
      "text": "Dati in ingresso non corretti"
    }
  ],
  "infos": [
    {
      "code": "110527",
      "severity": "I",
      "text": "Informazioni sull'operazione da fornire in caso di assistenza : data:2024-06-10 10:25:44 , idOperazione:156603"
    }
  ]
}
```

**Comment by amusarra** [comment]
Salve @biadanpad 
Potreste inviarci `idOperazione` o il payload della prima operazione di validazione?
Da controlli che abbiamo eseguito, risulta che `idComuneRegistrazione` sia impostato al codice ISTAT.

Cordiali Saluti.
Supporto ANSC.

**Comment by biadanpad** [comment]
Il valore de idComuneRegistrazione passato sembra quello giusto: 5000

idOperazione: 156601

REQUEST:
{
  "evento": {
    "id": "15526",
    "idAnsc": "2024-15526-159-108028",
    "idTipoEvento": "1",
    "idtipocontenuto": "3",
    "idUsecase": "1314",
    "descrizioneCasoUso": "Trascrizione atto di nascita resa alla direzione sanitaria",
    "stato": "CONFERMATO",
    "idVersion": "100012",
    "dataformazione": "2024-06-10",
    "ora": "12",
    "minuto": "10",
    "operatore": "XXXX",
    "operatoreNome": "XXXX",
    "operatoreCognome": "XXXX",
    "idComuneRegistrazione": "5000",
    "nomeComuneRegistrazione": "LISSONE",
    "idProvinciaRegistrazione": "108",
    "siglaProvinciaRegistrazione": "MB",
    "numeroatto": "159",
    "allegati": [
      {
        "id": "10413259",
        "idTipoAllegato": "100",
        "hashAllegato": "chl3uPI2hfn4u/WtOYlKFPblFrTjd9wgVUxVEQEG/zM=",
        "descrizione": "Atto di dichiarazione di nascita redatto dalla direzione sanitaria"
      }
    ],
    "intestatari": [
      {
        "cognome": "XXXX",
        "nome": "XXXX",
        "sesso": "X",
        "dataNascita": "XXXX-XX-XX",
        "idComuneNascita": "5646",
        "nomeComuneNascita": "MILANO",
        "idProvinciaNascita": "15",
        "siglaProvinciaNascita": "MI",
        "idStatoNascita": "90",
        "nomeStatoNascita": "ITALIA",
        "idComuneResidenza": "5000",
        "nomeComuneResidenza": "LISSONE",
        "idProvinciaResidenza": "108",
        "siglaProvinciaResidenza": "MB",
        "idStatoResidenza": "90",
        "nomeStatoResidenza": "ITALIA",
        "idNazionalita": "90",
        "nazionalita": "ITALIANA"
      }
    ],
    "madre": {
      "cognome": "XXXX",
      "nome": "XXXX",
      "sesso": "X",
      "dataNascita": "XXXX-XX-XX",
      "idComuneNascita": "190",
      "nomeComuneNascita": "ALCAMO",
      "idProvinciaNascita": "81",
      "siglaProvinciaNascita": "TP",
      "idStatoNascita": "90",
      "nomeStatoNascita": "ITALIA",
      "idComuneResidenza": "5000",
      "nomeComuneResidenza": "LISSONE",
      "idProvinciaResidenza": "108",
      "siglaProvinciaResidenza": "MB",
      "idStatoResidenza": "90",
      "nomeStatoResidenza": "ITALIA",
      "idNazionalita": "90",
      "nazionalita": "ITALIANA",
      "flagDichiarante": false,
      "flagComparente": false,
      "flagFirmatario": false
    },
    "padre": {
      "cognome": "XXXX",
      "nome": "XXXX",
      "sesso": "X",
      "dataNascita": "XXXX-XX-XX",
      "idComuneNascita": "6361",
      "nomeComuneNascita": "NAPOLI",
      "idProvinciaNascita": "63",
      "siglaProvinciaNascita": "NA",
      "idStatoNascita": "90",
      "nomeStatoNascita": "ITALIA",
      "idComuneResidenza": "5000",
      "nomeComuneResidenza": "LISSONE",
      "idProvinciaResidenza": "108",
      "siglaProvinciaResidenza": "MB",
      "idStatoResidenza": "90",
      "nomeStatoResidenza": "ITALIA",
      "idNazionalita": "90",
      "nazionalita": "ITALIANO",
      "flagDichiarante": false,
      "flagComparente": false,
      "flagFirmatario": false
    },
    "datiDiNascita": {
      "luogoFiliazione": "Fondazione IRCCS Ca' Granda - Ospedale Maggiore Policlinico - Clinica Mangiagalli",
      "oraNascita": "11",
      "minutoNascita": "23"
    },
    "trascrizioneNascita": {
      "dataComunicazione": "2024-06-07",
      "testoLibero": "FONDAZIONE IRCCS CA' GRANDA\r\nOSPEDALE MAGGIORE POLICLINICO\r\nATTO DI DICHIARAZIONE DI NASCITA\r\nL'anno 2024 addi' 07 del mese di GIUGNO alle ore 11 e minuti 05 presso la Fondazione IRCCS Ca' Granda Ospedale Maggiore Policlinico - Clinica Mangiagalli sita nel comune di Milano, innanzi alla sottoscritta SALA LINA MARIA addetta alla Direzione sanitaria, \r\na cio' espressamente autorizzata dal Direttore Sanitario con delega conservata in atti, e' comparso il Sig. GIANNINI SALVATORE nato a NAPOLI il 09.08.1984 residente a LISSONE il quale, nella sua veste di Padre dichiara quanto segue:\r\nIl giorno SEI DEL MESE DI GIUGNO DELL'ANNO DUEMILAVENTIQUATTRO alle ore 11 e minuti 23 in questo centro di nascita e' nato un bambino di sesso MASCHILE al quale viene dato nome di VINCENZO e il cognome di GIANNINI.\r\nDetto bambino, la cui nascita e' comprovata dall'allegata attestazione di nascita, e' nato dalla Sig.ra FILIPPI ANNA RITA nata a ALCAMO il 27.09.1991 di cittadinanza ITALIANA residente a LISSONE coniugata con il Sig. GIANNINI SALVATORE nato a NAPOLI il 09.08.1984 di cittadinanza ITALIANA residente a LISSONE.\r\nIl bambino medesimo, come attestato dal dichiarante e' gemello, ed e' il 1 nato.\r\nIl dichiarante chiede di trasmettere, ai fini della trascrizione, la dichiarazione di nascita sottoscritta, unitamente all'attestazione di nascita al Comune di Lissone.\r\nIl presente atto, dopo essere stato letto, viene insieme con me sottoscritto dal dichiarante.\r\nIL DICHIARANTE: F.to GIANNINI SALVATORE.\r\nL'ADDETTA ALLA DIREZIONE SANITARIA: F.to SALA LINA MARIA.",
      "atto": {
        "enteEstero": {
          "nomeEnte": "Fondazione IRCCS Ca' Granda - Ospedale Maggiore Policlinico - Clinica Mangiagalli",
          "idComuneEnte": "5646",
          "nomeComuneEnte": "MILANO",
          "idProvinciaEnte": "15",
          "siglaProvinciaEnte": "MI",
          "nazioneEnte": "90",
          "nomeNazioneEnte": "ITALIA",
          "dataTrascrizione": "2024-06-07",
          "estremiDocumento": "ATTO DI DICHIARAZIONE DI NASCITA"
        }
      }
    },
    "composizioneCompleta": "      Oggi dieci del mese di giugno dell'anno duemilaventiquattro alle ore dodici e minuti dieci      nella Casa Comunale. Io CITTERIO MARGHERITA, Istruttore, Ufficiale di Stato Civile del Comune      di LISSONE per delega avuta, ho ricevuto dalla Direzione Sanitaria della Fondazione IRCCS Ca'      Granda Ospedale Maggiore Policlinico - Clinica Mangiagalli - Via Commenda, 12 - MILANO la      richiesta in data 07.06.2024 di trascrivere atto di dichiarazione di nascita di cui mi ha      trasmesso copia.      Aderendo a tale richiesta provvedo alla trascrizione per intero del documento, come segue:      FONDAZIONE IRCCS CA' GRANDA      OSPEDALE MAGGIORE POLICLINICO      ATTO DI DICHIARAZIONE DI NASCITA      L'anno 2024 addi' 07 del mese di GIUGNO alle ore 11 e minuti 05 presso la Fondazione IRCCS Ca'      Granda Ospedale Maggiore Policlinico - Clinica Mangiagalli sita nel comune di Milano, innanzi      alla sottoscritta SALA LINA MARIA addetta alla Direzione sanitaria, a cio' espressamente      autorizzata dal Direttore Sanitario con delega conservata in atti, e' comparso il Sig.      GIANNINI SALVATORE nato a NAPOLI il 09.08.1984 residente a LISSONE il quale, nella sua veste      di Padre dichiara quanto segue:      Il giorno SEI DEL MESE DI GIUGNO DELL'ANNO DUEMILAVENTIQUATTRO alle ore 11 e minuti 23 in      questo centro di nascita e' nato un bambino di sesso MASCHILE al quale viene dato nome di      VINCENZO e il cognome di GIANNINI.      Detto bambino, la cui nascita e' comprovata dall'allegata attestazione di nascita, e' nato      dalla Sig.ra FILIPPI ANNA RITA nata a ALCAMO il 27.09.1991 di cittadinanza ITALIANA residente      a LISSONE coniugata con il Sig. GIANNINI SALVATORE nato a NAPOLI il 09.08.1984 di cittadinanza      ITALIANA residente a LISSONE.      Il bambino medesimo, come attestato dal dichiarante e' gemello, ed e' il 1 nato.      Il dichiarante chiede di trasmettere, ai fini della trascrizione, la dichiarazione di nascita      sottoscritta, unitamente all'attestazione di nascita al Comune di Lissone.      Il presente atto, dopo essere stato letto, viene insieme con me sottoscritto dal dichiarante.      IL DICHIARANTE: F.to GIANNINI SALVATORE.      L'ADDETTA ALLA DIREZIONE SANITARIA: F.to SALA LINA MARIA.      Dopo di che ho munito del mio visto ed inserito nel volume degli allegati a questo registro la      richiesta di trascrizione e la copia del documento trascritto."
  },
  "testataRichiesta": {
    "idComune": 5000,
    "idOperazioneComune": "12090",
    "dataOraRichiesta": "2024-06-10T12:25:38.394+02:00",
    "nomeApplicativo": "urbi",
    "versioneApplicativo": "1.3.3",
    "fornitoreApplicativo": "padigitale"
  }
}

RESPONSE:
{
  "testataRisposta": {
    "idComune": 5000,
    "idOperazioneComune": "12090",
    "idOperazione": "156601",
    "idEsito": 0
  },
  "infos": [
    {
      "code": "110527",
      "severity": "I",
      "text": "Informazioni sull'operazione da fornire in caso di assistenza : data:2024-06-10 10:25:39 , idOperazione:156601"
    }
  ],
  "idEvento": "15526",
  "idTipoEvento": "1",
  "idAnsc": "2024-15526-159-108028"
}

**Comment by amusarra** [comment]
Salve @biadanpad 
Ci servirebbe avere la **prima operazione di validazione** (ovvero, quella per cui è stato restituito `idAnsc`) e non le due successive operazioni di aggiornamento.

Grazie.
Supporto ANSC.

**Comment by biadanpad** [comment]
Quella che vi ho precedentemente inviato è la prima richiesta di validazione.

L'evento era stato prenotato inquanto si tratta di un parto gemellare.

Questo è l'idOperazione della prenotazione: 156546

**Comment by amusarra** [comment]
Grazie @biadanpad.
Stiamo verificando.

Cordiali Saluti.
Supporto ANSC.

**Comment by asqueglia** [comment]
Buongiorno, abbiamo individuato il problema in prenotazione atti e appena risolto provvederemo a rilasciare la fix. Intanto abbiamo  corretto gli atti in stato confermato per consentirvi di procedere. Restiamo in attesa di un vostro feedback

**Comment by asqueglia** [comment]
Buongiorno con la versione 1.29.4 il problema è stato corretto. Pertanto chiudiamo la issue
