### ISSUE TITLE
Ciclo di vita delle Annotazioni.

### ISSUE THREAD

**Issue by gcuci** [italia/ansc#92]
buongiorno,

segnaliamo che l'attuale gestione delle Annotazioni prevede lo stesso ciclo di vita del generico Evento/Atto, e quindi il passaggio (obbligato), dagli stati di 'Bozza', 'Confermato', 'Firmato Da Dichiarante' e 'Firmato Da USC'. 

Evidentemente, per le Annotazioni, non ha significato la firma del dichiarante (e quindi il relativo stato).

E' una situazione transitoria?

In attesa di un riscontro,

cordiali saluti.

**Comment by asqueglia** [comment]
Buongiorno, per le annotazioni la firma del dichiarante non è richiesta in quanto necessaria la sola firma dell'USC; ci siamo accorti però che manca un controllo bloccante che lo impedisca nel caso in cui venga erroneamente invocata la firma del dichiarante. Provvederemo ad inserirlo in uno dei prossimi rilasci. Grazie mille per la segnalazione.

**Comment by asqueglia** [comment]
Buongiorno, la segnalazione è stata corretta con la versione 1.8.0 appena rilasciata.
