### ISSUE TITLE
[SC]: Annotazione per adozione internazionale di minore - Dati mancanti necessari per l'annotazione di adozione (tipologia/attoNascita/attoAdozione)

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#920]
### Ambiente

pre-produzione

### Servizio

R015 - Servizi cooperativi per la validazione delle adozioni internazionali

### idOperazione

2288191

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Lissone - biadanpad

### Data del test (yyyy-mm-dd)

2024-06-10

### Descrivi il problema

Tentando di validare un'annotazione di adozione internazionale di minore otteniamo l'errore in oggetto.
Potreste indicarci cosa manca?

### Payload (json)

```JSON
REQUEST:
{
  "evento": {
    "idtipocontenuto": "1",
    "idUsecase": "14950000",
    "descrizioneCasoUso": "Annotazione per adozione internazionale di minore",
    "stato": "CONFERMATO",
    "idVersion": "100013",
    "operatore": "DLCNTN57L67A064W",
    "operatoreNome": "MARGHERITA",
    "operatoreCognome": "CITTERIO",
    "idComuneRegistrazione": "5000",
    "nomeComuneRegistrazione": "LISSONE",
    "idProvinciaRegistrazione": "108",
    "siglaProvinciaRegistrazione": "MB",
    "intestatari": [
      {
        "id": "2526953"
      }
    ],
    "composizioneCompleta": " ____________ ____________ e' stato adottato da ____________ ____________ e ____________ ____________ ai sensi dell'art. 35 della legge 4 maggio 1983, n.184 (provvedimento del ____________ del Comune di ____________ (__) numero ____________ in data ____________ trascritto nei registri di nascita del Comune di LISSONE (MB) con numero 2024-2813690-7-108028 e pertanto assume il cognome di Â§NATO_COGNOME_NUOVOÂ§.\n",
    "datiAdozioneMinoriInternazionale": {
      "attoNascita": {
        "idAnsc": "2024-2813874-8-108028",
        "idComuneRegistrazione": "5000",
        "nomeComuneRegistrazione": "LISSONE",
        "idProvinciaRegistrazione": "108",
        "siglaProvinciaRegistrazione": "MB",
        "idtipocontenuto": "1",
        "numeroatto": "8",
        "dataformazione": "2024-06-10",
        "annoAtto": "2024",
        "tipologia": "1"
      },
      "attoAdozione": {
        "idAnsc": "2024-2813690-7-108028",
        "idComuneRegistrazione": "5000",
        "nomeComuneRegistrazione": "LISSONE",
        "idProvinciaRegistrazione": "108",
        "siglaProvinciaRegistrazione": "MB",
        "idtipocontenuto": "1",
        "numeroatto": "7",
        "dataformazione": "2024-06-06",
        "annoAtto": "2024",
        "tipologia": "1"
      },
      "tipologia": "1"
    }
  },
  "testataRichiesta": {
    "idComune": 5000,
    "idOperazioneComune": "3587",
    "dataOraRichiesta": "2024-06-10T15:27:16.459+02:00",
    "nomeApplicativo": "urbi",
    "versioneApplicativo": "1.3.6",
    "fornitoreApplicativo": "padigitale"
  }
}

RESPONSE:
{
  "testataRisposta": {
    "idComune": 5000,
    "idOperazioneComune": "3587",
    "idOperazione": "2288191"
  },
  "errors": [
    {
      "code": "400013",
      "severity": "E",
      "text": "Dati mancanti necessari per l'annotazione di adozione (tipologia/attoNascita/attoAdozione)"
    }
  ],
  "infos": [
    {
      "code": "110527",
      "severity": "I",
      "text": "Informazioni sull'operazione da fornire in caso di assistenza : data:2024-06-10 13:27:18 , idOperazione:2288191"
    }
  ]
}
```

**Comment by gbuemi** [comment]
Buongiorno @biadanpad,
abbiamo preso in carico la segnalazione, seguiranno aggiornamenti.

Un saluto,
Supporto ANSC

**Comment by gbuemi** [comment]
Buongiorno @biadanpad,
vi comunichiamo che inserendo gli id relativi all'atto di adozione e all'atto di nascita la validazione l'operazione avrebbe esito positivo, nello specifico i campi sarebbero _evento.datiAdozioneMinoriInternazionale.attoAdozione.id_ e _evento.datiAdozioneMinoriInternazionale.attoNascita.id_.

Per il caso di test da voi indicato per esempio

`"datiAdozioneMinoriInternazionale": {
      "attoNascita": {
        "id": "2813874",
        "idAnsc": "2024-2813874-8-108028",
        "idComuneRegistrazione": "5000",
        "nomeComuneRegistrazione": "LISSONE",
        "idProvinciaRegistrazione": "108",
        "siglaProvinciaRegistrazione": "MB",
        "idtipocontenuto": "1",
        "numeroatto": "8",
        "dataformazione": "2024-06-10",
        "annoAtto": "2024",
        "tipologia": "1"
      },
      "attoAdozione": {
        "id": "2813690",
        "idAnsc": "2024-2813690-7-108028",
        "idComuneRegistrazione": "5000",
        "nomeComuneRegistrazione": "LISSONE",
        "idProvinciaRegistrazione": "108",
        "siglaProvinciaRegistrazione": "MB",
        "idtipocontenuto": "1",
        "numeroatto": "7",
        "dataformazione": "2024-06-06",
        "annoAtto": "2024",
        "tipologia": "1"
      },
      "tipologia": "1"
    }`

Stiamo comunque procedendo ad aggiornare la documentazione indicando quanto riportato e ad accedere ai due atti collegati anche solo tramite idAnsc.

Grazie e saluti,
Supporto ANSC

**Comment by asqueglia** [comment]
Buongiorno la segnalazione è stata corretta con il rilascio odierno della versione 1.30.0

**Comment by biadanpad** [comment]
Buonasera, 
stiamo provando nuovamente ma otteniamo un altro errore: "Dati necessari per annotazione Adozione internazionale non presenti".

Di seguito request e response.

REQUEST:
{
    "evento": {
        "idTipoEvento": "1",
        "idtipocontenuto": "2",
        "idUsecase": "14950000",
        "descrizioneCasoUso": "Annotazione per adozione internazionale di minore",
        "stato": "CONFERMATO",
        "idVersion": "100014",
        "dataformazione": "2024-07-02",
        "ora": "14",
        "minuto": "07",
        "operatore": "DLCNTN57L67A064W",
        "operatoreNome": "MARGHERITA",
        "operatoreCognome": "CITTERIO",
        "idComuneRegistrazione": "5000",
        "nomeComuneRegistrazione": "LISSONE",
        "idProvinciaRegistrazione": "108",
        "siglaProvinciaRegistrazione": "MB",
        "numeroatto": "3592",
        "intestatari": [{
                "id": "2618984"
            }
        ],
        "composizioneCompleta": " ____________ ____________ e' stato adottato da ____________ ____________ e ____________ ____________ ai sensi dell'art. 35 della legge 4 maggio 1983, n.184 (provvedimento del ____________ del Comune di ____________ (__) numero ____________ in data ____________ trascritto nei registri di nascita del Comune di LISSONE (MB) con numero 2024-3014043-12-108028 e pertanto assume il cognome di Â§NATO_COGNOME_NUOVOÂ§.\n",
        "datiAdozioneMinoriInternazionale": {
            "attoNascita": {
                "idAnsc": "2024-3014047-13-108028",
                "idComuneRegistrazione": "5000",
                "nomeComuneRegistrazione": "LISSONE",
                "idProvinciaRegistrazione": "108",
                "siglaProvinciaRegistrazione": "MB",
                "idtipocontenuto": "3",
                "numeroatto": "13",
                "dataformazione": "2024-07-02",
                "annoAtto": "2024",
                "tipologia": "1"
            },
            "attoAdozione": {
                "idAnsc": "2024-3014043-12-108028",
                "idComuneRegistrazione": "5000",
                "nomeComuneRegistrazione": "LISSONE",
                "idProvinciaRegistrazione": "108",
                "siglaProvinciaRegistrazione": "MB",
                "idtipocontenuto": "3",
                "numeroatto": "12",
                "dataformazione": "2024-07-02",
                "annoAtto": "2024",
                "tipologia": "1"
            },
            "tipologia": "1"
        }
    },
    "testataRichiesta": {
        "idComune": 5000,
        "idOperazioneComune": "3592",
        "dataOraRichiesta": "2024-07-02T14:08:22.27+02:00",
        "nomeApplicativo": "urbi",
        "versioneApplicativo": "1.3.7",
        "fornitoreApplicativo": "padigitale"
    }
}

RESPONSE:
{
  "testataRisposta": {
    "idComune": 5000,
    "idOperazioneComune": "3592",
    "idOperazione": "2336214"
  },
  "errors": [
    {
      "code": "400003",
      "severity": "E",
      "text": "Dati necessari per annotazione Adozione internazionale non presenti"
    }
  ],
  "infos": [
    {
      "code": "110527",
      "severity": "I",
      "text": "Informazioni sull'operazione da fornire in caso di assistenza : data:2024-07-02 12:08:23 , idOperazione:2336214"
    }
  ]
}

**Comment by gbuemi** [comment]
Buon pomeriggio @biadanpad,
stiamo verificando.

Un saluto,
Supporto ANSC

**Comment by biadanpad** [comment]
Buongiorno, 
ci sono novità in merito?

**Comment by gbuemi** [comment]
Buongiorno @biadanpad,
la fix verrà rilasciata con la versione 1.31.0 del 31 luglio.

Un saluto,
Supporto ANSC

**Comment by asqueglia** [comment]
Buonasera con la versione 1.32 è stata corretta la segnalazione. Chiudiamo pertanto la issue
