### ISSUE TITLE
[R002] Certificazioni: Modifica della Request non segnalata nel Changelog 1.7.0 e swagger con errore.

### ISSUE THREAD

**Issue by gcuci** [italia/ansc#93]
Buongiorno,

con il nuovo rilascio 1.7.0, è stata modificata la Request prevista per il servizio di Certificazione. Ci siamo accorti della variazione, in quanto adesso il servizio richiede obbligatoriamente il soggettoRichiedente, ed il soggettoRiferimentoAtto (entrambi ModelSoggetto).

Provando inoltre a rigenerare le classi dallo swagger (R002_certificazione.yaml) viene sollevata un'eccezione, in quanto non è corretto il riferimento al ModelSoggetto (punta a base_servizi.yaml, invece di model_evento.yaml). Effettuando la correzione localmente, abbiamo comunque generato la nuova Request.

Invocando però il servizio, nonostante siano presenti i ModelSoggetto, soggettoRichiedente e soggettoRiferimentoAtto (per ora valorizziamo in entrambi solo l'idSoggettoanpr, con valori fittizi), vengono restituiti i 2 errori di 'Soggetto richiedente non specificato' e 'Soggetto riferimento non specificato'. Sono previsti dei campi obbligatori? E se si, quali?
Per una verifica potete far riferimento all'idOperazione: 1585945, sempre in preproduzione.

In attesa di un riscontro,

cordiali saluti.

**Comment by mttfranci** [comment]
Grazie della segnalazione.

Abbiamo integrato il changelog della versione 1.7.0.

Ecco l'aggiunta : 

### Changed
      Servizi Cooperativi 
		R002_certificazione.yaml
			- sostituito idAnprRichiedente con richiedente
			- sostituito idAnprRiferimentoAtto con intestatario
			- modificato tipo Idutenterilascio da BigDecimal a String in ModelCertificato
### Removed
      Servizi Cooperativi 
    R002_certificazione.yaml		
    - cancellazione idUsc	

Saluti

Assistenza ANSC
