### ISSUE TITLE
[SC]: citt_044 incongruenza tra mapping e webapp

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#930]
### Ambiente

pre-produzione

### Servizio

R009 - Servizi cooperativi validazione evento

### idOperazione

2299137

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

ponsacco, anna maraspin

### Descrivi il problema

Nel mapping di citt_044 il tutore-familiare può essere omesso se
evento.datiEventoCittadinanza.presenzaInteressato,=,true

Nella Webapp il tutore-familiare è sempre obbligatorio.

A rigor di logica mi sembra più corretta l'obbligatorietà della webapp in quanto l'intestatario dell'atto è impedito a presentarsi in Comune e quindi manderà sempre qualcuno a fare le sue veci.
Ma non conoscendo il lato burocratico, non giurerei che la mia logica sia corretta

L'idoperazione riportato è di una prova dove non ho indicato il tutore

**Comment by gbuemi** [comment]
Buongiorno @annamaraspin,
è stato un caso d'uso approfondito con gli esperti anusca in passato e confermiamo che il comportamento corretto è quello della webapp. Procederemo ad aggiornare la documentazione e il comportamento del servizio di validazione.

Un saluto e grazie,
Supporto ANSC

**Comment by asqueglia** [comment]
Buongiorno la segnalazione è stata corretta con il rilascio odierno della versione 1.30.0
