### ISSUE TITLE
[SC]: Errore "Claims iat del JWT non valido."

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#933]
### Ambiente

produzione

### Servizio

R001 - Servizi cooperativi allegati, R002 - Servizi cooperativi certificazioni, R005 - Servizi cooperativi consultazione

### idOperazione

non ricevuto

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Lissone - biadanpad

### Data del test (yyyy-mm-dd)

2024-06-18

### Descrivi il problema

Buongiorno, 
questa mattina il comune di Lissone sta avendo dei problemi con i servizi ricevendo in risposta l'errore in oggetto.
Come potete vedere dallo screenshot di seguito, certe volte si presenta il problema, mentre altre no:
![image](https://github.com/italia/ansc/assets/131870281/04757ef2-f39c-4389-960d-699696f7afe4)

**Comment by gbuemi** [comment]
Buongiorno @biadanpad,
potreste fornirci per favore una delle request andata in KO, completa di header e body? Vi chiediamo di inviarla via email a assistenza.ansc@sogei.it.

Grazie e saluti,
Supporto ANSC

**Comment by gbuemi** [comment]
Per un analisi immediata lato client, vi invitiamo a consultare le FAQ presenti nel documento [SpecificheTecnicheServiziCooperativiJWT_v1.1.1.pdf](https://github.com/italia/ansc/blob/main/docs/Note/SpecificheTecnicheServiziCooperativiJWT/SpecificheTecnicheServiziCooperativiJWT_v1.1.1.pdf)

Un saluto,
Supporto ANSC

**Comment by biadanpad** [comment]
Grazie per l'informazione.
Verifichiamo la sincronizzazione dei nostri server

________________________________
Da: gbuemi ***@***.***>
Inviato: martedì 18 giugno 2024 14:34
A: italia/ansc ***@***.***>
Cc: Bianchini Daniele ***@***.***>; Mention ***@***.***>
Oggetto: Re: [italia/ansc] [SC]: Errore "Claims iat del JWT non valido." (Issue #933)


Salve @biadanpad<https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fbiadanpad&e=3c68d96e&h=deccd9e4&f=y&p=n>,
abbiamo approfondito la questione negli accessi in cui si evidenzia l'errore "Claims iat del JWT non valido". Ci risulta che il parametro iat sia avanti di circa un secondo rispetto ai nostri server, pertanto non risulta essere valido.

A seguire una evidenza di un accesso effettuato in tarda mattinata:

Tue Jun 18 2024 12:21:47: URL=Libraesva ESG attenzione!: i link numerici sono spesso insicuri!:<https://192.168.93.120:5424/services/service/doc/allegato/upload/1,IP=,IDP=,IDS=108028,CF=XXXX,OTP=YYY,MSG=Claims> https://192.168.93.120:5424/services/service/doc/allegato/upload/1,IP=,IDP=,IDS=108028,CF=XXXX,OTP=YYY,MSG=Claims<https://192.168.93.120:5424/services/service/doc/allegato/upload/1,IP=,IDP=,IDS=108028,CF=XXXX,OTP=YYY,MSG=Claims> iat del JWT non valido.

Andando a visionare la transazione questo il JWT decodificato:

{
"sub": "XXXX",
"iat": 1718706108,
"exp": 1718922108,
"nbf": 1718922108,
"jti": "5w7UQDGFZY18z_hvv_tVcQ",
"sede": "108028",
"postazione": "108028-PC-0034",
"otp": "YYY"
}

In questo caso corrisponde a martedì 18 giugno 2024 12:21:48 GMT+02:00 DST mentre sul datapower risulta che la transazione sia arrivata alle:

• 2024-06-18
• 12:21:47 CEST

Vi chiediamo pertanto di verificare la configurazione del server NTP del client ANSC.

Questo problema non si è presentato finora e ci risulta che nessun altra software house lo abbia riscontrato.
Chiudiamo la issue e in caso di ulteriori questioni può sempre essere riaperta.

Un saluto,
Supporto ANSC

—
Reply to this email directly, view it on GitHub<https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fitalia%2Fansc%2Fissues%2F933%23issuecomment-2175991831&e=3c68d96e&h=baccaf01&f=y&p=n>, or unsubscribe<https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FA7OC4SKB33UCOSN3SAFOPYDZIASLRAVCNFSM6AAAAABJPOHMD6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCNZVHE4TCOBTGE&e=3c68d96e&h=45058ce1&f=y&p=n>.
You are receiving this because you were mentioned.

________________________________
[https://www.padigitale.it/Logo-Mail.gif]
<http://www.padigitale.it>
Questo messaggio e i suoi allegati possono contenere informazioni riservate ed è destinato esclusivamente al destinatario o al suo rappresentante. Qualsiasi forma di distribuzione, divulgazione, riproduzione, copia del contenuto di questa e-mail (compresi gli allegati) è severamente vietata dalla legge italiana ai sensi dell'articolo 616 del Codice Penale e in conformità al regolamento generale sulla protezione dei dati 679/2016. Se non si è il destinatario previsto di questo messaggio e-mail e del suo contenuto, si prega di avvisare immediatamente il mittente e cancellare successivamente questo messaggio e tutti i suoi allegati.
Rispetta l'ambiente. Non stampare questa mail se non è necessario.[https://www.padigitale.it/Foglia-Mail.gif]
