### ISSUE TITLE
[webapp]: Web App oggi non funzionante

### ISSUE THREAD

**Issue by migmar68** [italia/ansc#934]
### Ambiente

pre-produzione

### Provenienza segnalazione

Software House

### Riferimenti operatore/comune

Poggio a Caiano

### Descrivi il problema

Oggi cercando di entrare nella web app ANSC scopo verifica delle prove, riceviamo da stamattina l'errore 

```
<env:Envelope xmlns:env="http://schemas.xmlsoap.org/soap/envelope/">
<env:Body>
<env:Fault>
<faultcode>env:Client</faultcode>
<faultstring>Rejected by policy. (from client)</faultstring>
</env:Fault>
</env:Body>
</env:Envelope>
```

**Comment by amusarra** [comment]
Salve @migmar68 
Ci sono dei problemi con la validazione dei certificati che sono in fase di risoluzione.
Nel frattempo potreste accedere con il vostro account SPID qualora il codice fiscale associato sia corrispondente a quello dell'utenza abilitata.

Cordiali Saluti.
Supporto ANSC.

**Comment by mttfranci** [comment]
@migmar68 buon pomeriggio.
Ora l'accesso dovrebbe funzionare nuovamente.
Saluti

Assistenza ANSC

**Comment by migmar68** [comment]
Confermo grazie
