### ISSUE TITLE
[SC]: Validazione caso 14850000 - Annotazione modificativa generica

### ISSUE THREAD

**Issue by siscomanpr** [italia/ansc#936]
### Ambiente

produzione

### Servizio

R009 - Servizi cooperativi validazione evento

### idOperazione

171562

### Provenienza segnalazione

Comune

### Comune di riferimento e operatore

Comune di Magliano Alpi

### Data del test (yyyy-mm-dd)

19/06/2024

### Descrivi il problema

In seguito alla trascrizione di un atto di nascita estero di cittadina straniera che ha appena acquistato la cittadinanza italiana, il comune deve provvedere a registrare anche un'annotazione di cambiamento del cognome (avvenuto in seguito al matrimonio di cui si è anche trascritto l'atto estero). 
E' stato quindi utilizzato il caso d'uso "14850000 - Annotazione modificativa generica" in modo da registrare l'annotazione di cambiamento del cognome e contemporaneamente fare la variazione di cognome sul soggetto.
In fase di validazione dell'evento il sistema restituisce gli errori allegati: 

![image](https://github.com/italia/ansc/assets/28776141/96020b8f-030f-4bf9-8436-0e6d562c186a)

Il comune di residenza e la cittadinanza del soggetto non sono dati disponibili ne sull'atto di nascita estero, ne su quello di matrimonio estero.
Potete rendere non obbligatori questi campi?

**Comment by asqueglia** [comment]
Buongiorno la segnalazione è stata corretta con il rilascio odierno della versione 1.30.0
