### ISSUE TITLE
[SC]: Validazione caso 1312 - nuovi campi obbligatori

### ISSUE THREAD

**Issue by siscomanpr** [italia/ansc#937]
### Ambiente

pre-produzione, produzione

### Servizio

R009 - Servizi cooperativi validazione evento

### idOperazione

2311739 (ambiente pre-produzione)

### Provenienza segnalazione

Comune

### Comune di riferimento e operatore

Serravalle Sesia - Anna Urban

### Data del test (yyyy-mm-dd)

19/06/2024

### Descrivi il problema

Dalla versione 1.29 e con idVersion: 100013, per il caso d'uso 1312 il sistema richiede come obbligatori i campi di cittadinanza e residenza del soggetto intestatario. 

![image](https://github.com/italia/ansc/assets/28776141/50ea454d-403e-4914-be57-d4a70fa00c92)

Come già discusso altre volte, queste informazioni non sono sempre disponibili sull'atto di nascita che si sta trascrivendo, quindi l'ufficiale di stato civile non può inserirli. 

Visto che il comune aveva urgenza di trascrivere questo atto, siamo quindi tornati all' idVersion: 100012.

Restiamo in attesa di un riscontro

**Comment by gbuemi** [comment]
Buongiorno @siscomanpr,
potreste per favore fornirci l'idOperazione di produzione dell'operazione registrata tramite idVersion: 100012?

Un saluto e grazie,
Supporto ANSC

**Comment by siscomanpr** [comment]
l'IDOperazione fornito nel primo messaggio era riferito all'ambiente di pre-produzione.

Di seguito fornisco gli IDOperazione dell'ambiente di produzione:
- 171576 (con versione 100013 che ha dato errore)
- 171588 (con versione 100012 che ha dato esito positivo)

Allego request e response delle 2 operazioni:
[1312.zip](https://github.com/user-attachments/files/15926346/1312.zip)

**Comment by asqueglia** [comment]
Buongiorno la segnalazione è stata corretta con il rilascio odierno della versione 1.30.0
