### ISSUE TITLE
[webapp]: Impossibile completare [1.3.1.2] su WebApp

### ISSUE THREAD

**Issue by antonioluberto** [italia/ansc#938]
### Ambiente

pre-produzione

### Provenienza segnalazione

Software House

### Riferimenti operatore/comune

Grottaferrata

### Data del test (yyyy-mm-dd)

21/06/2024

### Caso d'uso

[1.3.1.2] 

### Descrivi il problema

Nella redazione dell'atto

![image](https://github.com/italia/ansc/assets/26415430/eaa31d68-a08d-44fa-a180-1077a2c17bd9)

riferito al caso d'uso in oggetti, si prova l'inserimento dei due allegati richiesti come obbligatori e l'operazione pare inizialmente avvenire con successo:

![image](https://github.com/italia/ansc/assets/26415430/7be90fee-e695-4786-9590-5fcb32bfc4bf)

Al click su "Valida evento", però, la WebApp restituisce errore:

![image](https://github.com/italia/ansc/assets/26415430/a0ac600d-8744-49d9-ab58-b72e3d85e410)

A questo è solo possibile eseguire "Salva bozza" ma, evidentemente, sulla bozza medesima non si trovano gli allegati che si è provato ad inserire

**Comment by mttfranci** [comment]
@antonioluberto in effetti c'è stato un errore sull'elaborazione di un allegato che ora dovrebbe essere a posto.
Potete riprovare?

Saluti

Assistenza ANSC

**Comment by mttfranci** [comment]
Non avendo ricevuto altri feedback chiudiamo la issue.

Saluti

Assistenza ANSC
