### ISSUE TITLE
[R002] Certificazioni: Con la nuova versione (1.7.0), il servizio restituisce sempre un errore.

### ISSUE THREAD

**Issue by gcuci** [italia/ansc#94]
Buongiorno,

nel precedente issue (#93), oltre alla variazione della request del servizio con il nuovo rilascio, segnalavamo anche, che con la nuova versione, il servizio ci restituisce sempre un errore.

In particolare, nonostante nella request siano presenti i ModelSoggetto, soggettoRichiedente e soggettoRiferimentoAtto, vengono sempre restituiti i 2 errori di 'Soggetto richiedente non specificato' e 'Soggetto riferimento non specificato'. Inoltre non è chiaro se, e quali campi dei due ModelSoggetto, siano obbligatori. Per una verifica in preproduzione, potete far riferimento all'idOperazione: 1586210.

In attesa di un riscontro,

cordiali saluti.

**Comment by asqueglia** [comment]
Buongiorno, si tratta di un refuso della documentazione che abbiamo provveduto immediatamente a correggere nella versione 1.7.1 appena rilasciata. Potete scaricare l'openapi aggiornata del servizio di certificazione. Grazie mille per la segnalzione
