### ISSUE TITLE
[webapp]: Presenza del firmatario Unito 2 non previsto nello usecase 442000

### ISSUE THREAD

**Issue by corradosacco** [italia/ansc#946]
### Ambiente

pre-produzione

### Provenienza segnalazione

Software House

### Riferimenti operatore/comune

Corrado Sacco / Milano

### Caso d'uso

442000

### Descrivi il problema

Buongiorno, ho notato che la webapp richiede erroneamente la firma del secondo unito civilmente nello usecase 442000 "Manifestazione di volontà di scioglimento dell'unione civile tra persone dello stesso sesso di una sola parte".

**Comment by asqueglia** [comment]
Buonasera con la versione 1.32 è stata corretta la segnalazione. Chiudiamo pertanto la issue
