### ISSUE TITLE
[R002] Certificazioni: Il servizio risponde sempre con un errore.

### ISSUE THREAD

**Issue by gcuci** [italia/ansc#95]
Buongiorno

scusate se insisto ancora (vd, #93 e #94), ma oltre alla documentazione che avete aggiornato (changelog e openapi), il problema che avevamo sollevato, è che con questa nuova Request, il servizio ci restituisce sempre i 2 errori di 'Soggetto richiedente non specificato' e 'Soggetto riferimento non specificato', anche se i due ModelSoggetto ci sono. Per una verifica in preproduzione, potete far riferimento all'idOperazione: 1586210.

Inoltre volevamo sapere se, e quali campi dei due ModelSoggetto, sono obbligatori. Nelle precedenti versioni, passavamo due idAnpr fittizi, ed il servizio rispondeva correttamente. 

In attesa di un riscontro,

cordiali saluti.

**Comment by asqueglia** [comment]
Buongiorno, come riportato negli openapi aggiornati del servizio di certificazione il payload del servizio R002 deve contenere per i soggetti gli oggetti **richiedente** e **intestatario**, obbligatori.
Nella richiesta da lei inviata invece sono stati indicati nel payload gli oggetti soggettoRichiedente e soggettoRiferimentoAtto, come da vecchie specifiche errate.
I soggetti richiedente ed intestatrio che vengono trasmessi devono essere soggetti esistenti, altrimenti il servizio restituisce errore.

le indico un payload di esempio
{
  "testataRichiesta": {
        "idComune": {{idComune}},
        "idOperazioneComune": "APP2022032210000",
        "dataOraRichiesta": "1",
        "nomeApplicativo": "Applicativo Demografico",
        "versioneApplicativo": "1.0.0",
        "fornitoreApplicativo": "Nome Fornitore"
  },
    "idAnsc": "2023-569992-122-999999",
    "idEvento": "569992",
    "**intestatario**": {
        "id": "434703"
    },
    "**richiedente**": {
        "codiceFiscale": "BTSXXXXX",
        "cognome": "BATXXXX",
        "nome": "XXXXX",
        "sesso": "M",
        "dataNascita": "1989-06-28",
        "idComuneNascita": "18345",
        "nomeComuneNascita": "ROMA",
        "idProvinciaNascita": "58",
        "siglaProvinciaNascita": "RM",
        "idStatoNascita": "90",
        "nomeStatoNascita": "ITALIA",
        "idComuneResidenza": "2780",
        "nomeComuneResidenza": "CESENA",
        "idProvinciaResidenza": "40",
        "siglaProvinciaResidenza": "FC",
        "idStatoResidenza": "90",
        "nomeStatoResidenza": "ITALIA",
        "indirizzoResidenza": "",
        "idNazionalita": "90",
        "nazionalita": "ITALIANA"
    },
    "idTipoCertificato": "3"
}

**Comment by gcuci** [comment]
grazie per la risposta.

In effetti non erano aggiornati i nome delle proprietà che settavamo nella request del servizio. Non ci eravamo accorti che con la 1.7.1, nello swagger, oltre alla correzione dell'errore, c'era stata anche la modifica dei nomi.

Adesso però, effettuando le chiamate con i nomi corretti, il servizio restituisce un Errore 500 (errore interno). Potete far riferimento all'operazione con id: 1587189.

Abbiamo fatto più prove modificando i dati di 'richiedente' ed 'intestatario'. In quella indicata, li abbiamo valorizzati entrambi, con i dati completi dell'intestatario effettivo dell'evento di cui si vuole la Certificazione (quindi dovrebbero essere dati validi).

Non avendo però dettagli indicativi nell'errore della response, non riusciamo a capire dove sbagliamo.

Potete darci informazioni più precise su come valorizzare 'richiedente' ed 'intestatario', e quali campi del ModelSoggetto devono essere valorizzati obbligatoriamente?

**Comment by asqueglia** [comment]
Buongiorno i dati trasmessi nelle sezioni richiedente e intestatario sono corretti. Abbiamo riscontrato un bug che provvederemo quanto prima a correggere. Vi faremo sapere non appena rilasceremo la correttiva.

**Comment by antonioluberto** [comment]
Vi chiediamo gentilmente di rilasciare, contestualmente alla soluzione del bug, la documentazione che indichi in dettaglio quali siano i dati obbligatori per l'invocazione del servizio R002.

**Comment by asqueglia** [comment]
Buongiorno, la segnalazione è stata corretta con la versione 1.8.0 appena rilasciata.
