### ISSUE TITLE
[SC]: R008 - idEsito=999 ma sembra tutto ok

### ISSUE THREAD

**Issue by Hdemografici** [italia/ansc#951]
### Ambiente

pre-produzione

### Servizio

R008 - Servizi cooperativi notifiche

### idOperazione

2336125

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

colli al metauro

### Data del test (yyyy-mm-dd)

2024/07/02

### Descrivi il problema

L'operazione indicata restituisce i dati della notifica ma nella testataRisposta trovo idEsito=999, mi sarei aspettato in idEsito=0 avendo restituito correttamente i dati.

**Comment by asqueglia** [comment]
Buongiorno verifichiamo e le facciamo sapere

**Comment by asqueglia** [comment]
Buonasera con la versione 1.32 è stata corretta la segnalazione. Chiudiamo pertanto la issue
