### ISSUE TITLE
[SC]: Casi d'uso Trascrizioni Matrimoni (use case 331000, 332000, 339999) e Riconciliazioni (use case 350000)

### ISSUE THREAD

**Issue by MarcoSalaPad** [italia/ansc#954]
### Ambiente

pre-produzione, produzione

### Servizio

R009 - Servizi cooperativi validazione evento

### idOperazione

assente

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Lissone

### Data del test (yyyy-mm-dd)

2024-07-04

### Descrivi il problema

Buongiorno,
su richiesta del comune di Lissone segnaliamo che per i seguenti casi d'uso di trascrizioni di matrimoni

Trascrizione di matrimonio estero richiesta da interessato - USE CASE 331000
Trascrizione di matrimonio estero richiesta da Consolato/Ambasciata - USE CASE 332000
Caso d'uso di servizio (trascrizioni matrimonio) – USE CASE 339999

e riconciliazioni

Riconciliazione - USE CASE 350000

non sono presenti, ne da Web App e di conseguenza ne dai servizi cooperativi, le sezioni per riportare gli atti di nascita degli sposi.

Andrebbero integrati come già fatto per altri casi d'uso di matrimoni (ad esempio USE CASE 312111 per Matrimonio con rito civile con delega di altro comune nella casa comunale).

Grazie
Pa Digitale Spa

**Comment by asqueglia** [comment]
Buongiorno, verifichiamo la segnalazione. Faremo sapere appena possibile

**Comment by asqueglia** [comment]
Buonasera con la versione 1.32 è stata corretta la segnalazione. Chiudiamo pertanto la issue
