### ISSUE TITLE
[SC]: 11214100	Dichiarazione nei termini di filiazione fuori dal matrimonio resa all'USC dal procuratore del padre di bimbo nato morto

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#955]
### Ambiente

pre-produzione

### Servizio

R001 - Servizi cooperativi allegati

### idOperazione

----

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

anna maraspin

### Descrivi il problema

Buongiorno,
mi dicono che in questa casistica mancherebbe la possibilità di inviare l'allegato relativo all'Atto Notarile.
Al caso ne parliamo con il Comune giovedì 11 che abbiamo la riunione per chiarimenti.

**Comment by asqueglia** [comment]
Verifichiamo e le facciamo sapere. Un saluto

**Comment by asqueglia** [comment]
Buonasera con la versione 1.32 è stata corretta la segnalazione. Chiudiamo pertanto la issue
