### ISSUE TITLE
matr_019 - Sesso testimone

### ISSUE THREAD

**Issue by amusarra** [italia/ansc#957]
### Discussed in https://github.com/italia/ansc/discussions/952

<div type='discussions-op-text'>

<sup>Originally posted by **annamaraspin** July  3, 2024</sup>
Buongiorno,
nella versione 1.30.0 il campo sesso testimone è divenuto obbligatorio solo per il secondo, terzo e quarto testimone.
Nel primo il campo risulta facoltativo.
Immagino che siano tutti e 4 obbligatori.
Ho trovato lo stesso problema anche in altri usecase</div>

**Comment by asqueglia** [comment]
Buonasera con la versione 1.32 è stata corretta la segnalazione. Chiudiamo pertanto la issue
