### ISSUE TITLE
Richiesta info sulla gestione delle Annotazioni.

### ISSUE THREAD

**Issue by gcuci** [italia/ansc#96]
Buongiorno

con l'ultimo rilascio (1.7.0) è stato modificato il ModelDatiAnnotazione (datiAnnotazione del ModelEvento), limitandolo a due soli campi (testoAnnotazione e tipoAnnotazione), e con l'indicazione nella descrizione, che conterrà le Annotazioni contestuali. Sono informazioni che dobbiamo passare noi in fase di validazione dell'evento, o saranno generate automaticamente dal sistema?

Come sono collegate, invece, le altre tipologie di Annotazioni, all'Evento primario?

Per fare una prova, abbiamo registrato e firmato 2 Annotazioni, su un Evento di Nascita registrato in precedenza. Le Annotazioni sono state registrate correttamente, e sulla Web Application risulta tutto corretto (l'Evento di nascita ha id: 951027). Utilizzando però il servizio REST di Consultazione, sia per evento, che per soggetto, non si riescono ad estrarre i dati delle Annotazioni. Viene estratto il solo evento con tutti gli altri metadati. Provando anche la ricerca dell'evento, impostando nel filtro, l'id dell'Annotazione, non viene restituito niente.
Inoltre, utilizzando la funzionalità di Anteprima, nella Web Application vengono stampate anche le Annotazioni, mentre il servizio REST restituisce un pdf, senza le Annotazioni. 

Potreste darci delle informazioni più dettagliate?

In attesa di un riscontro,

cordiali saluti.

**Comment by gcuci** [comment]
Facendo riferimento al documento indicato (NotaProcessoAnnotazioniAndQuickCoopServiceFlow.pdf), ed agli attuali servizi disponibili, abbiamo ancora qualche dubbio che elenchiamo di seguito:

- per le Annotazioni contestuali da trasmettere con l'evento, sono stati previsti i campi 'tipoAnnotazione' e 'testoAnnotazione'. La tipologia indicherà anche se l'Annotazione è 'certificabile' o meno?

- alcune Annotazioni contestuali, sono generate, con un testo parzialmente completato (es. in attesa del dettaglio della successiva Trascrizione nel Comune di Residenza), per essere poi aggiornate in modo definitivo, in un secondo momento (es. alla ricezione della notifica di avvenuta Trascrizione). Come saranno gestiti questi casi?

- nel pdf che descrive la gestione delle Annotazioni, è indicato, nel caso di Annotazioni automatiche, per Atto primario cartaceo, che il Comune che ha formato l'evento, acquisirà l'identificativo dell'Annotazione da un'apposita Comunicazione, e potrà recuperare l'Annotazione, tramite il servizio di ConsultazioneANSC, passandogli l'identificativo. Non è chiaro come recuperare l'identificativo dell'Annotazione, dall'attuale Response del servizio di Comunicazione, mentre, provando ad utilizzare il servizio di ConsultazioneANSC, passandogli l'identificativo di un'Annotazione (abbiamo utilizzato uno dei casi d'uso di servizio, per verifica: idEventoAnnotazione: 951845, idEventoCollegato: 951027), questa non viene restituita (anche effettuando la ricerca per Soggetto).


In attesa di un riscontro,

cordiali saluti.

**Comment by asqueglia** [comment]
Buongiorno, 
rispondo ai punti richiesti.
1. al  momento non è stato previsto di indicare la certificabilità delle annotazioni contestuali; lato web app abbiamo consentito l'inserimento di una annotazione contestuali per i soli casi d'uso di matrimonio/unione civile per indicare il regime patrimoniale separazione dei beni o altra legge consentita. Lato servizi cooperativi è possibile inviare insieme all'atto anche una annotazione contestuale. Faremo un approfondimento sulla certificabilità delle annotazioni
2. il sistema non consente la gestione delle annotazioni contestuali parziali da completare in un secondo momento; da approfondimenti intercorsi con gli esperti ANUSCA, si apprende che la procedura attualmente in uso è una prassi usata per comodità, mentre la procedura corretta è quella di annotare l'atto interamente solamente quando è pervenuta la conferma della trascrizione. Quindi questi casi verranno gestiti con la registrazione dell'annotazione a margine completa.
3. il servizio con cui viene notificata la generazione automatica dell'annotazione è il servizio di notifica R008 e non quello di comunicazione R003. E' possibile invocare il servizio di notifiche utilizzando come criterio di ricerca l'intervallo temporaleo, di seguito un esempio, in cui la response del servizio restituisce proprio l'identificativo di una annotazione.
Per reperire il contenuto dell'annotazione è possibile utilizzare il servizio di consultazione R005, trasmettendo in input l'identificativo della annotazione, come da esempio in calce.
request R008
{
    "testataRichiesta": {
        "idComune": {{idComune}},
        "idOperazioneComune": "APP2022032210000",
        "dataOraRichiesta": "{{dataOraRichiesta}}",
        "nomeApplicativo": "{{nomeApplicativo}}",
        "versioneApplicativo": "{{versioneApplicativo}}",
        "fornitoreApplicativo": "{{fornitoreApplicativo}}"
    },
    "criteriRicercaNotifiche": {
        "dataInizio": "2023-05-04",
        "dataFine": "2023-05-04"
    }
}

response R008
{
    "testataRisposta": {
        "idComune": 1000000,
        "idOperazioneComune": "APP2022032210000",
        "idOperazione": "1026216",
        "idEsito": 0
    },
    "notifiche": [
        {
            "idAnsc": "2023-569781-00000-999999",
            "idComuneFormazione": "1000000",
            "idComuneCompetente": "1000000",
            "idSoggettoRif": "434068",
            "dataInizioValidita": "2023-05-04 09:38:00.0",
            "dataFineValidita": "2023-05-04 09:38:00.0"
        }
 ]
}

request R005

{
    "testataRichiesta": {
        "idComune": {{idComune}},
        "idOperazioneComune": "APP2022032210000",
        "dataOraRichiesta": "{{dataOraRichiesta}}",
        "nomeApplicativo": "{{nomeApplicativo}}",
        "versioneApplicativo": "{{versioneApplicativo}}",
        "fornitoreApplicativo": "{{fornitoreApplicativo}}"
    },
    "criteriRicercaEvento": {
        "id": 569781,
        "idAnsc": "2023-569781-00000-999999"
    }
}

response R005

{
    "testataRisposta": {
        "idComune": 1000000,
        "idOperazioneComune": "APP2022032210000",
        "idOperazione": "1026217",
        "idEsito": 0
    },
    "modelEventoDTO": [
        {
            "id": 569781,
            "idAnsc": "2023-569781-00000-999999",
            "idTipoEvento": "1",
            "idtipocontenuto": "4",
            "idUsecase": "10000000",
            "stato": "GENERATA DA SISTEMA",
            "dataformazione": "2023-05-04",
            "ora": "09",
            "minuto": "38",
            "idComuneRegistrazione": "1000000",
            "nomeComuneRegistrazione": "BRAIES",
            "idProvinciaRegistrazione": "21",
            "siglaProvinciaRegistrazione": "BZ",
            "operatore": "TRNLNA91D41A083B",
            "ruoloOperatore": "2",
            "operatoreNome": "ALAN",
            "operatoreCognome": "TURING",
            "redattoNellaCasaComunale": true,
            "eventoCollegato": {
                "idAnsc": "2023-569772-4795984-999999",
                "idComuneRegistrazione": "1000000",
                "nomeComuneRegistrazione": "BRAIES",
                "idProvinciaRegistrazione": "21",
                "siglaProvinciaRegistrazione": "BZ",
                "idtipocontenuto": "1",
                "dataformazione": "2023-02-02",
                "numeroatto": "4795984",
                "annoAtto": "2023",
                "tipologia": "3"
            },
            "composizioneCompleta": "FELICIANO WENZ ha contratto matrimonio con Federica Rossi il 12/02/2023 nel Comune di BRAIES. L'atto fu iscritto nei registri di matrimonio del Comune di BRAIES con numero 2023-569772-4795984-999999.",
            "datains": "2023-05-04T09:38:02.205608",
            "dataultimoagg": "2023-05-04T09:38:02.205608"
        }
    ],
    "datiPaginazione": {
        "numPagina": 1,
        "numRecordPagina": 30,
        "numRecordTotali": 1
    }
}
