### ISSUE TITLE
[SC]: Anteprima - Matrimonio Fuori dalla Casa Comunale (cdu 311211): Numero Civico del Luogo Celebrazione

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/ansc#963]
### Ambiente

pre-produzione

### Servizio

R009 - Servizi cooperativi validazione evento

### idOperazione

2359954

### idEvento o idAnsc

2024-3014878-186-039010

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

FAENZA

### Descrivi il problema

metaDato numeroCivico, all'interno della sezione evento.datiEventoMatrimonio.luogoCelebrazione

il campo - richiesto come obbligatorio - viene passato nel json del servizio di validazione ma non viene riportato nell'anteprima dell'atto

lo stesso comportamento si verifica anche su atto inserito da web-app (idAttoAnsc 2024‐3014882‐10123‐039010)

suggerisco di verificare la stessa anomalia anche sulle unioni civili - fuori dalla casa comunale.

grazie
Alessandro ADS

**Comment by asqueglia** [comment]
Grazie mille per la segnalazione. Verifichiamo e le facciamo sapere.

**Comment by asqueglia** [comment]
Buonasera con la versione 1.32 è stata corretta la segnalazione. Chiudiamo pertanto la issue
