### ISSUE TITLE
[webapp]: richiesta tasto "indietro" su preprod

### ISSUE THREAD

**Issue by migmar68** [italia/ansc#964]
### Ambiente

pre-produzione

### Provenienza segnalazione

Software House

### Riferimenti operatore/comune

Maggioli

### Descrivi il problema

Non è un problema, ma una richiesta finalizzata a migliorare i test come sw house per la redazione atto, sulla web app che ora ci prendono molto tempo a causa delle tante casistiche.

Sarebbe possibile - solo in ambiente preprod - aggiungere in fase di redazione atto, quando si arriva alla fase COMPILAZIONE DATI (dove chiede le varie variabili e mostra la composizione atto) , aggiungere un tasto INDIETRO per tornare alle scelte precedenti, che determinano il caso d'uso, e poterle eventualmente cambiare senza dover per forza uscire e ricominciare?

**Comment by mttfranci** [comment]
Salve, comprendiamo l'esigenza, ma in generale cerchiamo di escludere differenze di comportamento tra l'ambiente di preproduzione e produzione, tranne in casi  eccezionali.

Saluti

Assistenza ANSC
