### ISSUE TITLE
[SC/webapp] Anteprima Atto / Certificazione: modalità di visualizzazione di Località Estera e Stato di Nascita

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/ansc#966]
### Ambiente

pre-produzione, produzione

### Servizio

R002 - Servizi cooperativi certificazioni, R010 - Servizi cooperativi anteprima

### idOperazione

0

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

SAN LAZZARO DI SAVENA

### Descrivi il problema

buongiorno.

dal tavolo di confronto del 16/07/2024 è emersa la richiesta - condivisa dai partecipanti - di uniformare la modalità di visualizzazione di comune e stato di nascita nelle anteprime / certificazioni (si parla del caso specifico di soggetto nato all'estero).

allo stato attuale, nella maggior parte dei casi viene indicato prima lo stato e poi, tra parentesi, il nome della localita estera, come nell'esempio che riporto:
![image](https://github.com/user-attachments/assets/81e3cf28-e8f2-4b67-a153-1494888ef582)

la richiesta è quella di invertire l'ordine dei dei due elementi, indicando quindi prima la località estera e poi, tra parentesi, lo stato di appartenenza.

grazie
Alessandro ADS

**Comment by mttfranci** [comment]
Salve @AMonopoliADS .

Pianificheremo l'intervento in uno dei prossimi rilasci.

Se concordate, visto che mentre lo stato è sempre obbligatorio, la località non lo è, pensavamo di utilizzare questo comportamento : 

* Se la località è presente : BARCELLONA (SPAGNA)
* Se la località non è presente : SPAGNA
Va bene?

Saluti

**Comment by AMonopoliADS** [comment]
grazie del riscontro Matteo

dal mio punto di vista, l'approccio che proponi è coerente anche rispetto alla versione dei primi atti dove la località non veniva indicata. per cui per me va bene.
non so se gli altri lettori vogliono contribuire per confermare o suggerire approcci diversi.

intanto grazie
Alessandro

**Comment by asqueglia** [comment]
Buonasera con la versione 1.32 è stata corretta la segnalazione. Chiudiamo pertanto la issue
