### ISSUE TITLE
[SC/webapp]: Anteprima Atto / Certificazione: Matrimonio estero VS Unione Civile Estero

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/ansc#967]
### Ambiente

pre-produzione, produzione

### Servizio

R002 - Servizi cooperativi certificazioni, R010 - Servizi cooperativi anteprima

### idOperazione

0

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

FAENZA

### Descrivi il problema

si chiede di verificare ed uniformare il comportamento delle anteprime e delle certificazioni tra Matrimoni (che sembrerebbero più aggiornati) ed Unioni Civili.
nel caso specifico è stato testato l'evento avvenuto all'estero.

nell'Estratto per Copia Integrale:
- per il matrimonio (es. 2024‐3015169‐259‐039010) la sezione "Dati Evento Matrimonio" propone:
![image](https://github.com/user-attachments/assets/c22ac1b4-2ba6-4bc9-afa6-43a3ff0f0b97)
- per l'unione civile (es. 2024‐3015173‐260‐039010) la sezione "Dati Evento Unione Civile" propone:
![image](https://github.com/user-attachments/assets/47838d8f-7e48-4196-8b0c-e8310c8d8e84)
(viene indicata solo la data)

nell'Estratto per Riassunto:
- per il matrimonio:
![image](https://github.com/user-attachments/assets/d71a6f98-c6c7-449a-b409-663d84f6b63c)
- per l'unione civile:
![image](https://github.com/user-attachments/assets/03494d44-e7df-4a49-bc7a-941e84711ca7)
(manca il luogo dove è avvenuta l'unione / in assenza dell'atto di nascita del secondo contraente, vengono indicati puntini / la "E" che anticipa l'indicazione del secondo contraente è maiuscola e potrebbe sembrare parte del cognome / c'è un punto dopo la sigla provincia di nascita del primo contraente)

nel Certificato Semplice:
- per il matrimonio:
![image](https://github.com/user-attachments/assets/6e81ca4f-64f4-4b93-a8e8-0bfe6b36b60c)
- per l'unione civile
![image](https://github.com/user-attachments/assets/47f5007b-3ed7-4b49-956a-64519f57e755)
(manca il luogo dove è avvenuta l'unione / in assenza dell'atto di nascita del secondo contraente, vengono indicati puntini / la "e" che anticipa l'indicazione del secondo contraente in questo caso è minuscola, ma non è in grassetto / c'è un punto dopo la sigla provincia di nascita del primo contraente / la serie dell'atto di nascita del primo contraente è attaccata al testo "del comune...")

grazie
Alessandro ADS

**Comment by asqueglia** [comment]
Buonasera con la versione 1.32 è stata corretta la segnalazione. Chiudiamo pertanto la issue
