### ISSUE TITLE
[R006] – Informazioni sui campi da passare in richiesta

### ISSUE THREAD

**Issue by ManuelDeMeo** [italia/ansc#97]
Buongiorno,
a seguito delle vostre modifiche abbiamo provato ad invocare nuovamente il servizio di Firma Autografa del dichiarante. (R006) (/firmadichiarante/upload/1)

Test effettuato: 08/05/2023
Ambiente: preproduzione

La richiesta che mandiamo è del tipo:

```json
{
   "firmaDichiaranteInput":{
      "contenuto":"JVBERi0xLjQKJeLjz9MKMyAwIG9iago8PC9UeXBliUlRU9GCg==",
      "protocollo":"11111/2023",
      "nomefile":"StampaDocumentiFascicolo_07_03_2023 94108.pdf",
      "idEvento":"950715",
      "tipoFile":"1",
      "tipoAllegato":"999",
      "listaFirmatari":[
         {
            "nome":"EMILI",
            "cognome":"RESI",
            "codiceFiscale":"RSEMLE93R41Z222Y",
            "sesso":"F",
            "dataNascita":"1993-09-30"
         }
      ]
   },
   "testataRichiesta":{
      "idComune":4559,
      "idOperazioneComune":"2",
      "dataOraRichiesta":"1",
      "nomeApplicativo":"Civilia Next",
      "versioneApplicativo":"1.0.0",
      "fornitoreApplicativo":"Deda Next"
   }
}

```
(NB: ho troncato la stringa dentro contenuto per rendere la issue leggibile)

Precedentemente nell’oggetto lista firmatari inserivamo solo nome,cognome e codiceFiscale ed il servizio rispondeva correttamente.
Successivamente al rilascio ha smesso di funzionare:
•	Abbiamo provato ad aggiungere i campi sesso e dataNascita ma il servizio ha risposto ancora negativamente.
•	Abbiamo anche provato a passare una richiesta con nome,cognome,sesso,datanascita senza il codice fiscale ma nemmeno questa ha funzionato.
•	Abbiamo verificato che sulla documentazione non fossero cambiate le decodifiche per il tipo allegato ed il tipo file, ma a quanto risultano ancora valide ( PDF = 1 e Processo Verbale=999 )

Il servizio risponde sempre con il seguente messaggio:

```json
{
   "errors":[
      {
         "code":"400003",
         "severity":"E",
         "text":"Dati in ingresso non corretti"
      }
   ],
   "testataRisposta":{
      "idComune":4559,
      "idEsito":1,
      "idOperazione":"1586513",
      "idOperazioneComune":"2"
   }
}
```

Potete per favore indicare quali sono i parametri non corretti nella richiesta?
Più in generale è possibile in qualche modo indicare nella risposta quale è il parametro che causa problemi?

Grazie

**Comment by anbatistini** [comment]
Buongiorno,
verifichiamo e le facciamo sapere.

**Comment by asqueglia** [comment]
Buongiorno, la segnalazione è stata corretta con la versione 1.8.0 appena rilasciata.
