### ISSUE TITLE
[SC]: Anteprima Conformità: Controllo su Firma Dichiaranti - Messaggio di Errore

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/ansc#970]
### Ambiente

pre-produzione, produzione

### Servizio

R010 - Servizi cooperativi anteprima

### idOperazione

220346

### idEvento o idAnsc

2024-20520-719-037054

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

SAN LAZZARO DI SAVENA

### Data del test (yyyy-mm-dd)

2024-07-19

### Descrivi il problema

con la comunicazione sopra-descritta stiamo richiedendo l'Anteprima dell'Attestazione di Conformità (ws R010) in seguito all'upload della DICHIARAZIONE FIRMATA dai dichiaranti (ws R006).

in risposta alla richiesta dell'Anteprima dell'Attestazione di Conformità (ws R010), otteniamo l'errore:
"L'evento non può essere firmato, l'atto necessita della firma di uno o più dichiaranti."

rilevo due anomalie in questo messaggio:
1. msg. "l'evento non può essere firmato".
non sto firmando l'evento, ma sto richiedendo l'anteprima dell'attestazione di conformità. 
ritengo che il messaggio sia fuorviante perchè mi fa venire il dubbio di avere richiesto la firma USC dell'atto, mentre ho solo richiesto l'anteprima dell'attestazione di conformità.
2. msg. "l'atto necessita della firma di uno o più dichiaranti".
mi viene segnalata un'informazione non corretta e nuovamente fuorviante.
la DICHIARAZIONE FIRMATA è stata inviata (ws R006) ed il flusso è andato a buon fine (idOperazioneANSC: 220345)

dalle prove eseguite fino ad oggi, riteniamo che la situazione di errore sia unicamente collegata allo stato di "verifica in corso" del documento che è stato inviato con il servizio R006 (Firma Dichiarante).
infatti, con la ripetizione dell'invio, il servizio di Anteprima Attestazione (ws R010) va a buon fine.

se confermate che la situazione descritta fotografa la realtà dei fatti, vi chiediamo di rendere più chiaro il messaggio di errore.
con l'attuale messaggio la prima cosa a cui si pensa è che manca qualcosa nella gestione della firma dei dichiaranti...

situazione analoga si presenta tentando di validare l'atto (ws R009) in un momento in cui gli allegati mandati in upload (ws R001) sono in stato di verifica, ma in quel caso il servizio di validazione risponde con il messaggio più chiaro:
"La verifica di almeno un allegato è ancora in corso"

la richiesta, quindi, è quella di rispondere in maniera altrettanto chiara e coerente anche in sede di richiesta dell'Attestazione di Conformità.

se invece abbiamo malinterpretato i fatti, attendiamo chiarimenti riguardo la natura dell'errore.

grazie
Alessandro ADS

**Comment by asqueglia** [comment]
Buongionro prendiamo in carico l'anomalia e le facciamo sapere appena possibile

**Comment by AMonopoliADS** [comment]
salve.

non mi ritrovo con l'avvenuta soluzione.
ho appena provato due atti in pre-produzione ed ho lo stesso problema segnalato.

1.
atto: 2024-3414090-234-039010 (pre-produzione - comune di FAENZA)
anteprima di attestazione con idOperazioneAnsc 2482755, restituisce errore:
```
  <errors>
    <severity>E</severity>
    <code>406011</code>
    <text>L'evento non può essere firmato, l'atto necessita della firma di uno o più dichiaranti.</text>
  </errors>
```
ripetuta la richiesta (idOperazioneAnsc 2482762): l'operazione è andata a buon fine

2.
atto: 2024-3414097-235-039010 (pre-produzione - comune di FAENZA)
anteprima di attestazione con idOperazioneAnsc 2482831, restituisce errore:
```
  <errors>
    <severity>E</severity>
    <code>406011</code>
    <text>L'evento non può essere firmato, l'atto necessita della firma di uno o più dichiaranti.</text>
  </errors>
```
ripetuta la richiesta (idOperazioneAnsc 2482854): l'operazione è andata a buon fine

potete verificare?
grazie
Alessandro ADS

**Comment by asqueglia** [comment]
Buon pomeriggio, monitoreremo la situazione. Chiudiamo la issue e in caso di malfunzionamento si prega di aprirne una altra nuova dedicata
