### ISSUE TITLE
[SC]: notifiche atti in anpr

### ISSUE THREAD

**Issue by dandreap** [italia/ansc#971]
### Ambiente

pre-produzione

### Servizio

R004 - Servizi cooperativi consultazione anagrafe per gestione anagrafica evento di stato civile

### idOperazione

non c'è

### Provenienza segnalazione

Comune

### Comune di riferimento e operatore

tarcento

### Descrivi il problema

Ho inserito in atto di nascita (id ansc 2718925) tramite webservice ma non c'è alcuna notifica in anpr per l'iscrizione anagrafica. Forse non è ancora attiva il servizio di notifica ad anpr?
Grazie

**Comment by asqueglia** [comment]
Buongiorno, il numero indicato 2718925 non corrisponde ad alcun atto. Per consentirci di indagare e verificare la situazione, potete inviarci i riferimenti corretti dell'atto da voi registrato per il quale non trovate le notifiche anagrafiche ?
Un saluto

**Comment by dandreap** [comment]
Buon giorno

Ora mi sono accorta di aver preso l'IDANSC 2718925 invece dell'IDATTO 3113319...


[cid:3f7ca4a1-a9bb-432e-bf26-ac1fad86a883]


Paola D'Andrea
Istruttore amministrativo - Servizi demografici - Città di Tarcento - Provincia di Udine
contatti: ***@***.******@***.***> (personale non utilizzare per  mail aventi carattere ufficiale) tel 0432 780698 (diretto) - 780691  780693  780694 (altri telefoni dell'ufficio)
Rispetta l’ambiente: se non ti e` necessario non stampare questa mail
Avviso ri riservatezza. Informativa ai sensi dell'art. 13 del D. Lgs. 30/06/2003 n. 196.
Il presente messaggio contiene dati personali ai sensi del D.Lgs. 196/2003, la cui consultazione, elaborazione, modificazione, conservazione, diffusione e utilizzo in qualsiasi forma, modo e misura da parte di soggetti non autorizzati, secondo modalità non consentite o per scopi difformi da quelli concordati costituisce trattamento illecito e fonte di grave responsabilità penale, civile e amministrativa. In caso di erronea ricezione del presente messaggio si prega pertanto di avvisare immediatamente il mittente e di eliminare il contenuto.


________________________________
Da: asqueglia ***@***.***>
Inviato: mercoledì 24 luglio 2024 08:33
A: italia/ansc
Cc: Dandrea Paola - Tarcento; Author
Oggetto: Re: [italia/ansc] [SC]: notifiche atti in anpr (Issue #971)


Buongiorno, il numero indicato 2718925 non corrisponde ad alcun atto. Per consentirci di indagare e verificare la situazione, potete inviarci i riferimenti corretti dell'atto da voi registrato per il quale non trovate le notifiche anagrafiche ?
Un saluto

**Comment by asqueglia** [comment]
Buongiorno abbiamo verificato l'evento indicato; non è stata confermata la notifica generata per l'evento registrato; quesro il motivo per cui non è stata predisposta l'operazione anagrafica.
Se non viene confermata la presa visione dell'evento da parte del comune di residenza (anche se si tratta dello stesso comune che ha registrato l'atto), non viene predisposta la notifica anagrafica.

Le invio il link al documento in cui è spiegato il flusso di conferma esplicita delle varie notifiche.
https://github.com/italia/ansc/blob/main/docs/Note/Nota_Processo_Flusso_Conferma/Nota_Processo_Flusso_Conferma.pdf

**Comment by dandreap** [comment]
ho accettato la notifica direttamente da webapp. Sono entrata in ANPRtest ma non trovo alcuna notifica nella sezione delle notifiche ansc. Manca ancora qualcosa?


Paola D'Andrea
Istruttore amministrativo - Servizi demografici - Città di Tarcento - Provincia di Udine
contatti: ***@***.******@***.***> (personale non utilizzare per  mail aventi carattere ufficiale) tel 0432 780698 (diretto) - 780691  780693  780694 (altri telefoni dell'ufficio)
Rispetta l’ambiente: se non ti e` necessario non stampare questa mail
Avviso ri riservatezza. Informativa ai sensi dell'art. 13 del D. Lgs. 30/06/2003 n. 196.
Il presente messaggio contiene dati personali ai sensi del D.Lgs. 196/2003, la cui consultazione, elaborazione, modificazione, conservazione, diffusione e utilizzo in qualsiasi forma, modo e misura da parte di soggetti non autorizzati, secondo modalità non consentite o per scopi difformi da quelli concordati costituisce trattamento illecito e fonte di grave responsabilità penale, civile e amministrativa. In caso di erronea ricezione del presente messaggio si prega pertanto di avvisare immediatamente il mittente e di eliminare il contenuto.


________________________________
Da: asqueglia ***@***.***>
Inviato: mercoledì 24 luglio 2024 09:42
A: italia/ansc
Cc: Dandrea Paola - Tarcento; Author
Oggetto: Re: [italia/ansc] [SC]: notifiche atti in anpr (Issue #971)


Buongiorno abbiamo verificato l'evento indicato; non è stata confermata la notifica generata per l'evento registrato; quesro il motivo per cui non è stata predisposta l'operazione anagrafica.
Se non viene confermata la presa visione dell'evento da parte del comune di residenza (anche se si tratta dello stesso comune che ha registrato l'atto), non viene predisposta la notifica anagrafica.

Le invio il link al documento in cui è spiegato il flusso di conferma esplicita delle varie notifiche.
https://github.com/italia/ansc/blob/main/docs/Note/Nota_Processo_Flusso_Conferma/Nota_Processo_Flusso_Conferma.pdf

**Comment by asqueglia** [comment]
Buongionro, abbiamo verificato che non avete trasmesso la data di validità anagrafica  per l'evento 3113319. La data di decorrenza anagrafica è indispensabile per poter generare le notifiche anagrafiche. Potete trasmettere la data di validità anagrafica,  utilizzando il servizio R014 /evento/data-validita/{version}  oppure da web app alla voce 'Altri servizi'

**Comment by dandreap** [comment]
Perfetto. Grazie. Risolto


Paola D'Andrea
Istruttore amministrativo - Servizi demografici - Città di Tarcento - Provincia di Udine
contatti: ***@***.******@***.***> (personale non utilizzare per  mail aventi carattere ufficiale) tel 0432 780698 (diretto) - 780691  780693  780694 (altri telefoni dell'ufficio)
Rispetta l’ambiente: se non ti e` necessario non stampare questa mail
Avviso ri riservatezza. Informativa ai sensi dell'art. 13 del D. Lgs. 30/06/2003 n. 196.
Il presente messaggio contiene dati personali ai sensi del D.Lgs. 196/2003, la cui consultazione, elaborazione, modificazione, conservazione, diffusione e utilizzo in qualsiasi forma, modo e misura da parte di soggetti non autorizzati, secondo modalità non consentite o per scopi difformi da quelli concordati costituisce trattamento illecito e fonte di grave responsabilità penale, civile e amministrativa. In caso di erronea ricezione del presente messaggio si prega pertanto di avvisare immediatamente il mittente e di eliminare il contenuto.


________________________________
Da: asqueglia ***@***.***>
Inviato: mercoledì 24 luglio 2024 11:24
A: italia/ansc
Cc: Dandrea Paola - Tarcento; Author
Oggetto: Re: [italia/ansc] [SC]: notifiche atti in anpr (Issue #971)


Buongionro, abbiamo verificato che non avete trasmesso la data di validità anagrafica per l'evento 3113319. La data di decorrenza anagrafica è indispensabile per poter generare le notifiche anagrafiche. Potete trasmettere la data di validità anagrafica, utilizzando il servizio R014 /evento/data-validita/{version} oppure da web app alla voce 'Altri servizi'
