### ISSUE TITLE
[SC]: Caso Uso 52154 - Mapping incompleto e Metadati su estratto per copia integrale non coerenti

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#972]
### Ambiente

pre-produzione

### Servizio

R009 - Servizi cooperativi validazione evento

### idOperazione

-

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Lissone - biadanpad

### Data del test (yyyy-mm-dd)

2024-07-24

### Descrivi il problema

Buongiorno, 

confrontando il mapping del caso d'uso in oggetto con quello che viene richiesto in fase di compilazione in WebApp si nota che il mapping è incompleto: manca la parte relativa alla sezione "Atto da trascrivere" (BindingObject = evento.trascrizioneCittadinanza.attoEstero.enteEstero).

Si segnala inoltre che sia nella generazione dell'anteprima, sia nella generazione dell'estratto per copia integrale, i metadati relativi alle sezioni "Autorità mittente" e "Atto da trascrivere" sono invertiti.

**Comment by gbuemi** [comment]
Buongiorno @biadanpad,
vi preghiamo di fornirci gli id operazione delle API che presentano anomalie.
Grazie.

Un saluto,
Supporto ANSC

**Comment by biadanpad** [comment]
idOperazione estratto per copia integrale: 2387371

il PDF riporta i metadati delle sezioni "Autorità mittente" e "Atto da trascrivere" invertiti

**Comment by mttfranci** [comment]
In effetti nell'ultima pubblicazione della documentazione una sezione era mancante.
Il mapping del caso d'uso è stato aggiornato con la patch 1.31.1

Saluti

**Comment by biadanpad** [comment]
I PDF generati con i servizi di certificazione e anteprima continuano a riportare i metadati delle sezioni "Autorità mittente" e "Atto da trascrivere" invertiti

Si veda ad esempio idOperazione: 2387371

Stessa cosa da WebApp

**Comment by asqueglia** [comment]
Buongionro abbiamo verificato prendiamo in carico la segnalzione

**Comment by asqueglia** [comment]
Buon pomeriggio, la segnalazione è stata corretta con il rilascio della patch 1.32.8
