### ISSUE TITLE
[SC]: R006 - Non sono stati recuperati firmatari per i dati inseriti

### ISSUE THREAD

**Issue by Hdemografici** [italia/ansc#973]
### Ambiente

pre-produzione

### Servizio

R006 - Servizi cooperativi firma dichiarante

### idOperazione

2384422

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

colli al metauro

### Data del test (yyyy-mm-dd)

2024-07-24

### Descrivi il problema

Buongiorno, non capisco come mai ho l'errore in oggetto, ho verificato i dati dei soggetti come suggerito nella #817 e mi sembra tutto uguale, dove sbaglio?
grazie mille

**Comment by asqueglia** [comment]
Buongiorno, abbiamo notato che trasmettete alcuni soggetti in maniera errata, c'è uno spazio di troppo nel nome; ad esempio 
  {
                "cognome": "KLAUS",
                **"nome": " JOHNNY",**
                "sesso": "M",
                "dataNascita": "1993-08-07"
            },

controllate meglio i dati trasmessi. Chiudiamo pertanto la issue. Se avete altri problemi riapritela pure.
