### ISSUE TITLE
[SC]: 

### ISSUE THREAD

**Issue by migmar68** [italia/ansc#974]
### Ambiente

pre-produzione

### Servizio

R002 - Servizi cooperativi certificazioni

### idOperazione

assente

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Maggioli

### Descrivi il problema

Nella segnalazione #256 è stato fatto presente il vincolo del Consolato, e in risposta è stata aggiunta la tabella 97 Consolato.
Non è chiaro se id e descrizione Consolato restino obbligatori.

Non è chiaro come fa la web app esempio per certificazione richiesta da ente, quando seleziono il territorio POLINESIA FRANCESE a presentare solo il consolato PARIGI, mentre se scelgo lo stato FRANCIA mi presenta 5 consolati.

**Comment by mttfranci** [comment]
L'origine delle associazioni, è la tabella di anpr :+1: 
Stati Territori Consolati – xls

Che si può reperire anche qui : 
https://www.anagrafenazionale.interno.it/area-tecnica/tabelle-di-decodifica/

In cui per ogni Stato/Territorio sono indicati il/i consolato/i competente/i, ad esempio : 

![image](https://github.com/user-attachments/assets/45b9483c-cd1f-4c97-82ea-e30e0f751cfe)


Come vedete per la Francia sono indicati 5 consolati, mentre per la polinesia, solo Parigi.

Saluti

Assistenza ANSC
