### ISSUE TITLE
[SC]: Anteprima - Cittadinanza (cdu 52122) - Sezione "Atto Collegato"

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/ansc#975]
### Ambiente

pre-produzione

### Servizio

R010 - Servizi cooperativi anteprima

### idOperazione

2387477

### idEvento o idAnsc

2024-3113494-208-039010

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

FAENZA

### Data del test (yyyy-mm-dd)

2024-07-25

### Descrivi il problema

in presenza di atto collegato che si riferisce ad atto cartaceo, nell'anteprima di stampa viene indicato solo l'anno e non anche il numero
![image](https://github.com/user-attachments/assets/c62c53f2-e8f3-4c0e-ac23-0adf0b77b18a)

contestualmente noto che i campi "id tipo contenuto" e "tipologia" vengono espressi sulla base del codice e non con descrizione (mi chiedevo se fosse corretto)

grazie
Alessandro ADS

**Comment by asqueglia** [comment]
Buongiorno prendiamo in carico la segnalazione. Grazie

**Comment by asqueglia** [comment]
Buon pomeriggio, con la versione 1.32.8 è stata corretta la segnalzione
