### ISSUE TITLE
[SC]: ModelMatrimonio incompleto

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#977]
### Ambiente

pre-produzione, produzione

### Servizio

R009 - Servizi cooperativi validazione evento, R010 - Servizi cooperativi anteprima

### idOperazione

-

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Lissone - biadanpad

### Data del test (yyyy-mm-dd)

2024-07-26

### Descrivi il problema

La classe ModelMatrimonio è incompleta: manca l'oggetto enteEstero necessario per il caso d'uso 313111.
In questo modo non è possibile implementare il caso d'uso

**Comment by gbuemi** [comment]
Salve @biadanpad, 
il problema presente sulla documentazione condivisa dovrebbe essere risolto al prossimo rilascio.

Un saluto,
Supporto ANSC

**Comment by biadanpad** [comment]
Quando è previsto il prossimo rilascio?

**Comment by gbuemi** [comment]
Nella prima settimana di agosto.

Un saluto,
Supporto ANSC

**Comment by asqueglia** [comment]
Buonasera con la versione 1.32 è stata corretta la segnalazione. Chiudiamo pertanto la issue
