### ISSUE TITLE
[webapp]: validazione atto con stesso numero comunale

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#981]
### Ambiente

pre-produzione

### Provenienza segnalazione

Software House

### Riferimenti operatore/comune

 anna maraspin, ponsacco

### Data del test (yyyy-mm-dd)

2024-08-01

### Descrivi il problema

Ho fatto una prova in webapp per vedere se c'è un blocco o almeno un avviso nel caso in cui l'utente introduca lo stesso numero comunale.
Sono riuscita a creare due atti con il numero comunale 10116.
Sarebbe possibile introdurre un controllo sia in webapp che nei servizi cooperativi?
Non vorrei che qualche utente usi sia webapp che il proprio gestionale creando doppioni o problemi derivanti da questo sul database del gestionale interno.

![image](https://github.com/user-attachments/assets/2f855fe9-fb12-443b-82b0-89c3d8f4de7c)

**Comment by Hdemografici** [comment]
la quesitone era stata affrontata anche in #609

**Comment by annamaraspin** [comment]
@asqueglia  buongiorno,
ci sono forse novità se verrà introdotto il controllo?
In riferimento al #609 il nostro prodotto garantisce che l'utente non possa immettere lo stesso numero comunale. Il problema resta se l'utente decida, contro le regole che daremo, di lavorare un misto tra proprio gestionale e webapp come già dicevo.

**Comment by asqueglia** [comment]
Buongiorno @annamaraspin  ci sarà un approfondimento in merito a fine agosto con i comuni in adozione controllata. Le faremo sapere le decisioni prese, subito dopo l'approfondimento. Al momento l'attività è sospesa e per ora non è previsto alcun controllo.

**Comment by asqueglia** [comment]
Buongiorno è stato concordato con il Dipartimento e con i comuni in produzione che non ci sarà alcun controllo da parte del sistema sul numero comunale che resta una responsabilità esclusiva dei comuni. Non è stato indicato alcun vincolo a cui è soggetto il numero comunale. Per qualsiasi richiesta di informazione o approfondimento in merito si prega di rivolgersi al Dipartimento.
