### ISSUE TITLE
[SC]: RICO_015 errore 400003 - Attenzione! Il comune non risulta essere valido.

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#987]
### Ambiente

pre-produzione

### Servizio

R009 - Servizi cooperativi validazione evento

### idOperazione

2413127

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

ponsacco, anna maraspin

### Descrivi il problema

Buongiorno.
Non riesco a capire a quale Comune si riferisce e perché sarebbe invalido. Nell'atto ho usato gli stessi Comuni che ho usato anche in altri test senza problemi del genere.
Al caso è possibile avere un messaggio più esaustivo?
grazie

**Comment by gbuemi** [comment]
Buongiorno @annamaraspin,
l'errore si presenta perché l'intestatario risulta essere nato nel 2020 in un comune cessato nel 1957, Acquasanta con id=50.

Ci impegneremo a restituire un messaggio di errore più chiaro.

Un saluto,
Supporto ANSC

**Comment by annamaraspin** [comment]
Grazie mille.
Mi risultava un altro Comune selezionato a video, avevo dei dati "sporchi" in una tabella
