### ISSUE TITLE
problemi con accesso ad ANSC

### ISSUE THREAD

**Issue by LucaBonini64** [italia/ansc#99]
Buongiorno,
abbiamo ricevuto ieri le utenze per accedere all'applicazione web di ANSC:
- https://anscwebpre.anpr.interno.it/ansc/login/ansc
- https://anscwebpre.anpr.interno.it/ansc/login/otp
ma richiamando entrambi gli URL la risposta è:
Http/1.1 Service Unavailable

Luca Bonini APKAPPA

**Comment by migmar68** [comment]
Oggi rilevo lo stesso problema.
Marco Migliori MAGGIOLI

**Comment by mttfranci** [comment]
Buongiorno, stiamo verificando.

Assistenza ANSC

**Comment by mttfranci** [comment]
@LucaBonini64  @migmar68 ora dovrebbe essere a posto, potreste riprovare?
Grazie in anticipo.

Assistenza ANSC

**Comment by migmar68** [comment]
Accesso riuscito, grazie.

**Comment by LucaBonini64** [comment]
L'URL adesso risponde correttamente, purtroppo poi mi va in timeout la richiesta di autenticazione con SPID: spidpre.anpr.interno.it ha impiegato troppo tempo a rispondere.

**Comment by mttfranci** [comment]
@LucaBonini64  in collaudoal momento  è possibile solo l'accesso tramite CNS con i certificati inviati in fase di attivazione.

**Comment by LucaBonini64** [comment]
Si, l'ho scoperto oggi alle 14.00 quando mi hanno mandato i certificati che prima non mi avevano inviato. Grazie.
