### ISSUE TITLE
[SC]: Consultazione Soggetto - Soggetto non trovato

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/ansc#990]
### Ambiente

produzione

### Servizio

R005 - Servizi cooperativi consultazione

### idOperazione

257875

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

San Lazzaro di Savena

### Data del test (yyyy-mm-dd)

2024-08-08

### Descrivi il problema

idVersion 100012

contesto: due atti di cittadinanza per lo stesso soggetto (giuramento + acquisto)

con la validazione del giuramento (idAttoAnsc 2024-23615-793-037054), l'intestatario dell'atto acquisisce l'idSoggettoANSC 15312880
in sede di formazione dell'atto di acquisto, con servizio di consultazione soggetto si va a cercare l'idSoggettoAnsc, ma il servizio non restituisce dati (idOperazioneAnsc 257875)

a parità di condizioni (caratteristiche dell'intestatario e idVersion), la consultazione corrispondente all'idOperazioneAnsc 229244 ha restituito i dati attesi

tra un atto e l'altro c'è stato un rilascio di versione ansc (lo segnalo perchè la supposizione è che il problema possa essere collegato a questo).

ho visto una recente segnalazione che potrebbe avere la stessa origine (issue #989) che però non ha ancora ricevuto risposta.
non sapendo se il problema sia lo stesso ho aperto questa issue

grazie
Alessandro ADS

**Comment by asqueglia** [comment]
Buon pomeriggio, prendiamo in carico la segnalazione. Le facciamo sapere appena risolta la problematica

**Comment by asqueglia** [comment]
Buongiorno è stata appena rilasciata una patch che risolve il problema della ricerca . Chiudiamo pertanto la issue
