### ISSUE TITLE
[SC]: Notifiche atti in ANPR

### ISSUE THREAD

**Issue by KibMcris** [italia/ansc#992]
### Ambiente

pre-produzione

### Servizio

R004 - Servizi cooperativi consultazione anagrafe per gestione anagrafica evento di stato civile

### idOperazione

-

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Tropea

### Data del test (yyyy-mm-dd)

14/08/2024

### Descrivi il problema

Per l'idansc 2024-3313263-118-102044 sono state accettate le notifiche di presa visione ed annotazione dell'atto (id 2024-3313264-00000-102044 e 2024-3313263-118-102044). A chiusura dell'atto è stata inviata anche la data di validità anagrafica relativa all'evento (si veda idOperazioneComune =179) a cui ANSC ha risposto  con esito positivo con operazione id=2426894.

Sia da servizio 4005 che da webApp ANPR non viene generata la notifica anagrafica.

Questo comportamento anche per l'atto 2024-3114376-267-102044, 2024-2913505-79-102044 e 2024-2913392-74-102044. Abbiamo controllato di aver confermato la presa visione delle notifiche generate da ansc e di aver inviato correttamente anche gli idschedasoggettoanpr in fase di validazione dell'atto.

Si precisa che altre notifiche anagrafiche sono state generate correttamente nei giorni scorsi.

Stiamo sbagliando qualcosa?

**Comment by amusarra** [comment]
Salve @KibMcris 
Potrebbe fare adesso una verifica della disponibilità delle notifiche anagrafiche?

Cordiali Saluti.
Supporto ANSC.

**Comment by KibMcris** [comment]
Buonasera @amusarra ho controllato e confermo che adesso vedo quasi tutte le notifiche e le abbiamo scaricate anche tramite servizio cooperativo.
Non risulta ancora generata la notifica relative all'atto 3114376.

**Comment by amusarra** [comment]
> Buonasera @amusarra ho controllato e confermo che adesso vedo quasi tutte le notifiche e le abbiamo scaricate anche tramite servizio cooperativo. Non risulta ancora generata la notifica relative all'atto 3114376.

Abbiamo analizzato i log e per lo specifico atto `3114376` c'è un errore un fase di generazione della notifica verso ANPR a causa dell'errore: 
- il contenuto dell'elemento "nazionalita" non è completo. È previsto un elemento "{descrizioneLocalita, descrizioneStato}"

Sembrerebbe che per il coniuge non siano pervenuti i dati della Nazionalità. Adesso faremo un controllo.

Cordiali Saluti.
Supporto ANSC.

**Comment by KibMcris** [comment]
Confermo che in fase di validazione dell'atto non sono stati inviati i dati relativi alla nazionalità del coniuge. Però chiaramente in fase di validazione e registrazione dell'atto in ANSC non abbiamo riscontrato nessuna anomalia (anche perchè la cittadinanza del coniuge potrebbe non essere conosciuta)

**Comment by amusarra** [comment]
Buongiorno @KibMcris 
Potrebbe controllare se anche per l'evento 3114376 è arrivata la notifica su ANPR.

Grazie.
Supporto ANSC.

**Comment by amusarra** [comment]
Salve @KibMcris 
Abbiamo rilasciato la versione [1.32.7](https://github.com/italia/ansc/releases/tag/v1.32.7) che risolve il problema segnalato; chiudiamo quind la issue.

Cordiali Saluti.
Supporto ANSC.
