### ISSUE TITLE
[SC]: R009 - errore validazione caso 14950000 Annotazione per adozione internazionale di minore

### ISSUE THREAD

**Issue by siscomanpr** [italia/ansc#993]
### Ambiente

pre-produzione

### Servizio

R009 - Servizi cooperativi validazione evento

### idOperazione

2427043

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

Serravalle Sesia

### Data del test (yyyy-mm-dd)

14/08/2024

### Descrivi il problema

In fase di validazione del caso d'uso in oggetto ricevo l'errore: 
`Dati mancanti nuove generalita sull'atto di adozione nuovoNome nuovoCognome`
Non riusciamo a capire quale sia il problema visto che l'atto di adozione era stato validato correttamente con la sola indicazione del nuovo cognome (nuovo nome non è obbligatorio da mapping).

**Comment by amusarra** [comment]
Salve @siscomanpr 
Abbiamo preso in carico la segnalazione.

Cordiali Saluti.
Supporto ANSC.

**Comment by asqueglia** [comment]
Chiusa con versione 1.32.4
