### ISSUE TITLE
[SC]: Anteprima Per Presa Visione - Errore "Dati in ingresso non corretti"

### ISSUE THREAD

**Issue by biadanpad** [italia/ansc#994]
### Ambiente

produzione

### Servizio

R010 - Servizi cooperativi anteprima

### idOperazione

283170

### idEvento o idAnsc

2024-25310-143-108028

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

biadanpad - Lissone

### Data del test (yyyy-mm-dd)

2024-08-23

### Descrivi il problema

Richiamando il servizio di anteprima per presa visione, in risposta otteniamo l'errore "Dati in ingresso non corretti"

idOperazione:
283170
283174
283177
283180
283182
283187
283289

In ambiente di pre-produzione non riscontriamo il problema (idOperazione: 2438833)

**Comment by gbuemi** [comment]
Buongiorno @biadanpad,
è possibile far riprovare nuovamente il comune? E' stato fatto un rilascio che dovrebbe risolvere l'anomalia. Vi chiediamo di chiudere la issue se il problema non persiste.

Grazie,
Supporto ANSC

**Comment by biadanpad** [comment]
Il comune mi ha risposto che dopo vari tentativi sono riusciti ad andare avanti (alle 9:18 - idOperazione:283493), non è pertanto possibile ripetere il test

**Comment by gbuemi** [comment]
Il tentativo andato a buon fine vale come test di risoluzione, perchè eseguito con la nuova versione del servizio di anteprima.

Grazie,
Supporto ANSC
